### ISSUE TITLE
vmselect query and query_range still return samples till 5min after target had been remove from vmagent

### ISSUE THREAD

**Issue by waldoweng** [VictoriaMetrics/VictoriaMetrics#1025]
**Describe the bug**
when one target was remove from `vmagent`, metrics of this target did not stop and continue after 5min from the time target was removed.

after some code reading, I found `vmselect` use default step 5min when calling `query` and `query_range` without `step` parameter. `vmselect` will use `step` for search `window` execpt `scrape_interval` is larger than `window`(not exactly but quite):

https://github.com/VictoriaMetrics/VictoriaMetrics/blob/8749c2dd9257044cc14eca069228e0d73cba608c/app/vmselect/promql/rollup.go#L512-L523

and `vmalert` depend on `vmselect` since it get all the data via `api/v1/query`: 
https://github.com/VictoriaMetrics/VictoriaMetrics/blob/8749c2dd9257044cc14eca069228e0d73cba608c/app/vmalert/datasource/vm.go#L72-L112
1. recording-rules apply on metrics with gaps smaller than 5min will output no gaps at all, since the above policy will fill the gap with previous value.
2. alert-rules also are affected by the above policy.

maybe this is related to staleness marker? https://github.com/VictoriaMetrics/VictoriaMetrics/issues/365#issuecomment-598361505

**To Reproduce**
```yaml
global:
  scrape_interval: 15s
  scrape_timeout: 10s
scrape_configs:
- job_name: node_exporter
  honor_labels: true
  honor_timestamps: true
  metrics_path: /metrics
  scheme: http
  static_configs:
  - targets:
    - 127.0.0.1:9090
```

1. setup victoria-metrics with the above prometheus.yaml
2. change the target in the above config from `127.0.0.1:9090` to `127.0.0.1:9091`
3. reload vmagent
4. query vmselect with url `http://localhost:8481/select/1/prometheus/api/v1/query?query=up` (`step` parameter not set)

and metrics `up{instance="localhost:9090"}` preserved for 5min

**Expected behavior**
metrics stop within maybe 1~2 scrape interval ?

**Screenshots**

**Version**
The line returned when passing `--version` command line flag to binary. For example:
```
$ ./vmselect --version
vmselect-20210119-114142-tags-v1.47.0-cluster-0-ga00df790
```

**Comment by waldoweng** [comment]
maybe vmselect can use maxPrevInterval as window when possible?
https://github.com/waldoweng/VictoriaMetrics/commit/1ca1b865c5a3a20188d1595244aeace5a76e7094

**Comment by f41gh7** [comment]
Hello, first of all vmagent doesn't support `global ` config section. So in your case, default scrape interval will be used (1 min). And metric should be threat as stale after 3 scrape intervals, as far as i remember. And there is also `search.latencyOffset` flag (30 s by default).
  I suggest you to decrease scrape_interval. 

 ```yaml
scrape_configs:
- job_name: node_exporter
  honor_labels: true
  honor_timestamps: true
  metrics_path: /metrics
  scrape_interval: 10s
  scrape_timeout: 10s
  scheme: http
  static_configs:
  - targets:
    - 127.0.0.1:9090
```
