### ISSUE TITLE
quick way to configure vmagent to scrape data from all cluster pods

### ISSUE THREAD

**Issue by Kamzs** [VictoriaMetrics/VictoriaMetrics#1033]
**Is your feature request related to a problem? Please describe.**
I am trying to configure vmagent to scrape data of all possible resources on all namespaces (i.e. I want to be able to see in grafana metrics for all pods, services, nodes).   
I would love to know what is the easiest way to tell vmagent to scrape data from everything on the cluster.

**Step to reproduce**

I deployed VM cluster (including vmoperator, vmselect, vminsert, vmstorage and vmagent) on my k8s cluster (pic A) following https://github.com/VictoriaMetrics/operator/blob/master/docs/quick-start.MD#VMAgent 

I configured grafana's datasource as vmselect's url.
I understand that vm operator as default creates VMServiceScrapes only for vm's services (pic B) and thus I can see in grafana only vm's pods.

Quick start docs present a way to add own VMServiceScrape and thus I was able to add extra targets to my vmagent passing namespace and port name (pic C). On the other hand I was not able to create simple yaml file telling agent to scrape data from every single pod / service / node in the cluster.

Adding targets by selectors / port names / namespaces does not seem as good way to configure agent to collect all possible data and that is why I am asking if there is a more convenient way to do it.

**pic A**
```
kubectl get pods -A
NAME                                                     READY   STATUS    RESTARTS   AGE
monitoring-system   vm-operator-d785689cd-2mfm7                              1/1     Running     0          2d22h
monitoring-system   vmagent-example-vmagent-7ffdf59dfd-lftww                 2/2     Running     0          2d22h
monitoring-system   vmstorage-example-vmcluster-persistent-0                 1/1     Running     0          2d22h
monitoring-system   vmstorage-example-vmcluster-persistent-1                 1/1     Running     0          2d22h
monitoring-system   vmselect-example-vmcluster-persistent-1                  1/1     Running     0          2d22h
monitoring-system   vmselect-example-vmcluster-persistent-0                  1/1     Running     0          2d22h
monitoring-system   vminsert-example-vmcluster-persistent-575dc47d94-c4v8c   1/1     Running     0          2d22h
monitoring-system   vminsert-example-vmcluster-persistent-575dc47d94-k7lt5   1/1     Running     0          2d22h
```

**pic B**
```
kubectl get VMServiceScrapes -A
NAMESPACE           NAME                                     AGE
monitoring-system   vmagent-example-vmagent                  2d22h
monitoring-system   vmselect-example-vmcluster-persistent    2d22h
monitoring-system   vminsert-example-vmcluster-persistent    2d22h
monitoring-system   vmstorage-example-vmcluster-persistent   2d22h
```

**pic C**
```
apiVersion: operator.victoriametrics.com/v1beta1
kind: VMServiceScrape
metadata:
  name: own
  namespace: monitoring-system
spec:
  selector: {}
  endpoints:
  - port: web
 ```

**Comment by hagen1778** [comment]
@f41gh7 @tenmozes I'll just tag you guys in case you have a moment to take a look on the question.

**Comment by valyala** [comment]
@f41gh7 , could you look into this question?

**Comment by f41gh7** [comment]
One of possible ways to monitor whole cluster, to create global VMServiceScrape with broad selector, it will scrape from `metrics` port at all pods backed by service: 
```yaml
apiVersion: operator.victoriametrics.com/v1beta1
kind: VMServiceScrape
metadata:
  name: services
  namespace: monitoring-system
spec:
  discoveryRole: "endpoints"
  jobLabel: "app.kubernetes.io/name"
  endpoints:
    - port: metrics
  namespaceSelector:
    any: true
  selector: {}
```
 
It can be also configured to scrape targets with annotations: `prometheus.io/scrape: true`, as more convenient method for kubernetes cluster monitoring with classic victoriametrics installation. For example:

pod scrape
```yaml
apiVersion: operator.victoriametrics.com/v1beta1
kind: VMPodScrape
metadata:
  name: all-scrape
spec:
  podMetricsEndpoints:
    - scheme: http
      relabelConfigs:
        - sourceLabels:
            [__meta_kubernetes_pod_annotation_prometheus_io_scrape]
          action: keep
          regex: "true"
        - targetLabels:
            [__meta_kubernetes_pod_annotation_prometheus_io_scheme]
          action: replace
          targetLabel: __scheme__
          regex: (https?)
        - sourceLabels:
            [__meta_kubernetes_pod_annotation_prometheus_io_path]
          action: replace
          targetLabel: __metrics_path__
          regex: (.+)
        - sourceLabels:
            [
                __address__,
                __meta_kubernetes_pod_annotation_prometheus_io_port,
            ]
          action: replace
          targetLabel: __address__
          regex: ([^:]+)(?::\d+)?;(\d+)
          replacement: $1:$2
  selector: {}
  namespaceSelector:
    any: true

```

target deployment:
```yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    k8s-app: kube-dns
  name: coredns
  namespace: kube-system
spec:
  replicas: 2
  selector:
    matchLabels:
      k8s-app: kube-dns
  template:
    metadata:
      annotations:
        prometheus.io/port: "9153"
        prometheus.io/scheme: http
        prometheus.io/scrape: "true"
      creationTimestamp: null
      labels:
        k8s-app: kube-dns
    spec:
      containers:
      - args:
        - -conf
        - /etc/coredns/Corefile
        image: k8s.gcr.io/coredns:1.6.7
        imagePullPolicy: IfNotPresent
        livenessProbe:
          failureThreshold: 5
          httpGet:
            path: /health
            port: 8080
            scheme: HTTP
          initialDelaySeconds: 60
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 5
        name: coredns
        ports:
        - containerPort: 53
          name: dns
          protocol: UDP
        - containerPort: 53
          name: dns-tcp
          protocol: TCP
        - containerPort: 9153
          name: metrics
          protocol: TCP
        readinessProbe:
          failureThreshold: 3
          httpGet:
            path: /ready
            port: 8181
            scheme: HTTP
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 1
...
```
