### ISSUE TITLE
remote_write for Prometheus is not working

### ISSUE THREAD

**Issue by krakazyabra** [VictoriaMetrics/VictoriaMetrics#106]
Hi! in case of closed issue #100 

I also have cluster version in kubernetes, but `:8480/api/v1/write` is for single-version.
in prometheus.yaml i wrote
```
    remote_write:
      - url: https://victoriametrics-stage.domain.org/insert
        queue_config:
          max_samples_per_send: 10000
          max_shards: 100
```
in ingress
```
      - path: /insert*
        backend:
          serviceName: victoria-metrics-vminsert
          servicePort: 8480
```
in service
```
  ports:
    - name: http
      port: 8480
      protocol: TCP
      targetPort: http
  selector:
    app: vminsert
```
but still have errors like
```level=error ts=2019-07-17T11:05:13.913Z caller=queue_manager.go:699 component=remote queue=0:https://victoriametrics-stage.domain.org/insert msg="non-recoverable error" count=213 err="server returned HTTP status 404 Not Found: <html>"```

**Comment by krakazyabra** [comment]
UPD:  
After some experiments with ingress i get another error:  
```level=error ts=2019-07-17T12:34:32.757Z caller=queue_manager.go:699 component=remote queue=0:https://victoriametrics-stage.domain.org/insert msg="non-recoverable error" count=408 err="server returned HTTP status 400 Bad Request: cannot parse path \"/insert/\": cannot find {authToken}"```  
for getting this error i modified ingress.yaml to such view:  
```
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  annotations:
    kubernetes.io/ingress.class: nginx-internal
    nginx.ingress.kubernetes.io/rewrite-target: /insert
  name: victoria-metrics-vminsert-ingress
  namespace: monitoring
spec:
  rules:
  - host: victoriametrics-stage.domain.org
    http:
      paths:
      - path: /insert(/|$)(.*)
        backend:
          serviceName: victoria-metrics-vminsert
          servicePort: 8480
  tls:
  - hosts:
    - victoriametrics-stage.domain.org
status:
  loadBalancer:
    ingress:
    - {}
```
