### ISSUE TITLE
High memory footprint for vmagent v1.55.1

### ISSUE THREAD

**Issue by pmitra43** [VictoriaMetrics/VictoriaMetrics#1113]
After upgrading from v1.53.1 to v1.55.1, I see a high memory footprint of vmagent.

**Screenshots**
![image](https://user-images.githubusercontent.com/7530897/110083974-64492580-7db5-11eb-8ad3-59cd604225c5.png)

**Version**
vmagent v1.55.1

**Spec**
```
    containers:
    - name: vmagent
      readinessProbe:
        initialDelaySeconds: 60
    extraArgs:
      promscrape.maxScrapeSize: 100MB
      promscrape.suppressDuplicateScrapeTargetErrors: "true"
      promscrape.suppressScrapeErrors: "true"
    image:
      repository: victoriametrics/vmagent
      tag: v1.55.1
    podScrapeNamespaceSelector: {}
    podScrapeSelector: {}
    relabelConfig:
      key: global_relabel.yaml
      name: monitoring-vmagent-cluster-relabel-config
    remoteWrite:
    - url: http://vminsert-monitoring-vmcluster-persistent.victoria-metrics.svc.cluster.local:8480/insert/0/prometheus/api/v1/write
      urlRelabelConfig:
        key: cluster_specific_relabel.yaml
        name: monitoring-vmagent-cluster-relabel-config
    replicaCount: 1
    resources:
      limits:
        cpu: 2
        ephemeral-storage: 10Gi
        memory: 16Gi
    serviceAccountName: vmagent
    serviceScrapeNamespaceSelector: {}
    serviceScrapeSelector: {}
```
