### ISSUE TITLE
vmagent proxy_url with https

### ISSUE THREAD

**Issue by adelbot** [VictoriaMetrics/VictoriaMetrics#1116]
**Bug explain**
When we use proxy_url with https with consul_sd_configs, the scrapper need TLS configuration.
We receive this message :
> VictoriaMetrics/lib/promscrape/scrapework.go:238        error when scraping "http://xxx.xxx.xxx.xxx:9100/metrics" from job "node-exporter" with labels {app_ccx="xxx",nodename="xxxxxx.net.intra.laposte.f"}: error when scraping "http://xxx.xxx.xxx.xxx:9100/metrics": error when sending CONNECT request to proxy "https://s__proxy__:3128": cannot send CONNECT request for dstAddr="xxx.xxx.xxx.xxx:9100": tls: either ServerName or InsecureSkipVerify must be specified in the tls.Config; try -enableTCP6 command-line flag if you scrape ipv6 addresses_

**To Reproduce**
```yml

- job_name: auto_via_consul_60s
      scrape_interval: 60s
      tls_config:
        insecure_skip_verify: true
      proxy_url: https://__proxy__:3128
      consul_sd_configs:
```

**Expected behavior**
where can we configure TLS option fr proxy_url ?

**Version**
vmagent-20210303-095335-tags-v1.55.1-0-g3a68b9448
