### ISSUE TITLE
vmalert - To call rules via rulesfiles

### ISSUE THREAD

**Issue by cathyalex** [VictoriaMetrics/VictoriaMetrics#1145]
I have deployed victoria metrics in my k8s cluster to use as long term storage for my prometheus metrics. I have also deployed vmalert and I have configured the datasource, remoteread, remotewrite, alertmanager notifer urls and alertmanager related parameters such as receivers in the configuration file. However, I could not find a way to configure the rule files. I have a bunch of rules file so I would like to configure the rules file path in the configuration. 

I could see mention of  "-rule" command line argument to call the rulefiles. However I could not find a way to configure it in my values.yaml file. Could you please advise?

Please note - vmalert is working fine if i configure the alerts (with groups and rules) inside my config file. I tested it by configuring few alerts. However, in my case since I have lot of rules to be configured - I will not be able to update groups inside the config. It will be great if there is anyway to call the rules yaml files directly.

**Comment by f41gh7** [comment]
Hello, i can suggest you to use additional volume with configmap, that contains your rules and provide extraArg with `rule: path_to_cm_file`

 For example:
```yaml
cat << EOF > example_rules.yaml

EOF
```
groups:
- name: groupFiring
  rules:
  - alert: VMRows
    for: 1s
    expr: |
      go_memstats_alloc_bytes
        >
         0
```bash
kubectl create configmap extra-rules --from-file=example_rules.yaml
```

 With operator you can add it via:
```yaml
apiVersion: operator.victoriametrics.com/v1beta1
kind: VMAlert
metadata:
  name: example-vmalert
spec:
  replicaCount: 1
  datasource:
    url: "http://vmsingle-example-vmsingle-pvc.default.svc:8429"
  notifier:
    url: "http://vmalertmanager-example-alertmanager.default.svc:9093"
  evaluationInterval: "30s"
  ruleSelector:
    matchLabels:
      managed-by: vm-operator
  ruleNamespaceSelector: {}
  extraArgs:
    rule: "/etc/extra-rules/example_rules.yaml"
  volumes:
    - name: extra-rules
      configMap:
        name: extra-rules
  volumeMounts:
    - name: extra-rules
      mountPath: /etc/extra-rules
```

 With helm chart, edit values.yaml:
```yaml
server:
  extraArgs:
    rule: "/etc/extra-rules/example_rules.yaml"
  extraVolumes:
    - name: extra-rules
      configMap:
        name: extra-rules

  # Extra Volume Mounts for the container
  extraVolumeMounts:
    - name: extra-rules
      mountPath: /etc/extra-rules
```

**Comment by cathyalex** [comment]
Thanks @f41gh7 for the quick response. I have configured it in extraArgs, extraVolumes and extraVolumeMounts as suggested by you in values.yaml. However, I could see a separate alert rule configuration in values.yaml as shown below. Could you please let know what is to be configured in that section?

  # vmalert alert rules configuration configuration:
  # use existing configmap if specified
  # otherwise .config values will be used
  configMap: ""
  config:
    alerts:
      groups: []

I have tried giving value as 'extra-rules' in the above configmap section. Pods are running but it seems the alerts/groups are not taken properly and Im getting the below warning in vmalert pod logs.

{"ts":"2021-03-24T05:16:04.454Z","level":"info","caller":"VictoriaMetrics/lib/logger/flag.go:20","msg":"flag \"version\" = \"false\""}
{"ts":"2021-03-24T05:16:04.461Z","level":"info","caller":"VictoriaMetrics/app/vmalert/manager.go:84","msg":"reading rules configuration file from \"/config/alert-rules.yaml;/opt/apps/monitoring/vmalert/rules/alert_rules.yaml\""}
{"ts":"2021-03-24T05:16:04.461Z","level":"warn","caller":"VictoriaMetrics/app/vmalert/config/config.go:254","msg":"no groups found in /config/alert-rules.yaml;/opt/apps/monitoring/vmalert/rules/alert_rules.yaml"}
{"ts":"2021-03-24T05:16:04.462Z","level":"info","caller":"VictoriaMetrics/lib/httpserver/httpserver.go:82","msg":"starting http server at http://:8880/"}
{"ts":"2021-03-24T05:16:04.462Z","level":"info","caller":"VictoriaMetrics/lib/httpserver/httpserver.go:83","msg":"pprof handlers are exposed at http://:8880/debug/pprof/"}

**Comment by cathyalex** [comment]
> Hello, i can suggest you to use additional volume with configmap, that contains your rules and provide extraArg with `rule: path_to_cm_file`
> 
> For example:
> 
> ```yaml
> cat << EOF > example_rules.yaml
> groups:
> - name: groupFiring
>   rules:
>   - alert: VMRows
>     for: 1s
>     expr: |
>       go_memstats_alloc_bytes
>         >
>          0
> EOF
> ```
> 
> ```shell
> kubectl create configmap extra-rules --from-file=example_rules.yaml
> ```
> 
> With operator you can add it via:
> 
> ```yaml
> apiVersion: operator.victoriametrics.com/v1beta1
> kind: VMAlert
> metadata:
>   name: example-vmalert
> spec:
>   replicaCount: 1
>   datasource:
>     url: "http://vmsingle-example-vmsingle-pvc.default.svc:8429"
>   notifier:
>     url: "http://vmalertmanager-example-alertmanager.default.svc:9093"
>   evaluationInterval: "30s"
>   ruleSelector:
>     matchLabels:
>       managed-by: vm-operator
>   ruleNamespaceSelector: {}
>   extraArgs:
>     rule: "/etc/extra-rules/example_rules.yaml"
>   volumes:
>     - name: extra-rules
>       configMap:
>         name: extra-rules
>   volumeMounts:
>     - name: extra-rules
>       mountPath: /etc/extra-rules
> ```
> 
> With helm chart, edit values.yaml:
> 
> ```yaml
> server:
>   extraArgs:
>     rule: "/etc/extra-rules/example_rules.yaml"
>   extraVolumes:
>     - name: extra-rules
>       configMap:
>         name: extra-rules
> 
>   # Extra Volume Mounts for the container
>   extraVolumeMounts:
>     - name: extra-rules
>       mountPath: /etc/extra-rules
> ```

Thanks @f41gh7 for the quick response. I have configured it in extraArgs, extraVolumes and extraVolumeMounts as suggested by you in values.yaml. However, I could see a separate alert rule configuration in values.yaml as shown below. Could you please let know what is to be configured in that section? Attached the snap for reference

image

I have tried giving value as 'extra-rules' in the above configmap section. Pods are running but it seems the alerts/groups are not taken properly and Im getting the below warning in vmalert pod logs.

{"ts":"2021-03-24T05:16:04.454Z","level":"info","caller":"VictoriaMetrics/lib/logger/flag.go:20","msg":"flag "version" = "false""}
{"ts":"2021-03-24T05:16:04.461Z","level":"info","caller":"VictoriaMetrics/app/vmalert/manager.go:84","msg":"reading rules configuration file from "/config/alert-rules.yaml;/opt/apps/monitoring/vmalert/rules/alert_rules.yaml""}
{"ts":"2021-03-24T05:16:04.461Z","level":"warn","caller":"VictoriaMetrics/app/vmalert/config/config.go:254","msg":"no groups found in /config/alert-rules.yaml;/opt/apps/monitoring/vmalert/rules/alert_rules.yaml"}
{"ts":"2021-03-24T05:16:04.462Z","level":"info","caller":"VictoriaMetrics/lib/httpserver/httpserver.go:82","msg":"starting http server at http://:8880/"}
{"ts":"2021-03-24T05:16:04.462Z","level":"info","caller":"VictoriaMetrics/lib/httpserver/httpserver.go:83","msg":"pprof handlers are exposed at http://:8880/debug/pprof/"}

**Comment by cathyalex** [comment]
@f41gh7 
Further to the update above, I have done couple of below things after which the alerts started working with **single rule file**.
1. Added label to the configmap with below command
    _kubectl label configmap extra-rules app=vmalert-victoria-metrics-alert-server -n monitoring_
2. Updated rules file name from "alert_rules.yaml" to "alert-rules.yaml"

However, when i placed 2 rule files in /opt/apps/monitoring/vmalert/rules/  path - it is not working as expected. Below are steps I have followed,
1. Placed 2 files in rules path namely 'alert-rules.yaml' and 'fed-amf-fed-amf-amf-cc-alerts-rules.yaml'.
2. Deleted and created 'extra-rules' configmap again by pointing the entire dir in **--from-file** instead of specifying the yaml file. Also added label to the configmap.
   _kubectl create configmap extra-rules --from-file=/opt/apps/monitoring/vmalert/rules/ -n monitoring
   kubectl label configmap extra-rules app=vmalert-victoria-metrics-alert-server -n monitoring_
2. In values.yaml, updated the -rule args as below to take all yaml files in the directory,
    rule: "/opt/apps/monitoring/vmalert/rules/*.yaml"
3. There are no errors in logs, but I could see its processing only the groups specified in 'alert-rules.yaml'. No group from the other rule file has been processed or taken.
4. I have verified the same by doing curl -> http://<vmalert-addr>/api/v1/groups
   (only the groups (vm_process_alert) specified in 'alert-rules.yaml' are fetched by this api)

_{"data":{"groups":[{"name":"vm_process_alert","type":"prometheus","id":"15153622779680699191","file":"/config/alert-rules.yaml","interval":"1m0s","concurrency":1,"alerting_rules":[{"id":"13301505857649700468","name":"process_cpu_seconds_total","type":"prometheus","group_id":"15153622779680699191","expression":"process_cpu_seconds_total \u003e 0.1","for":"1m0s","last_error":"","last_exec":"2021-03-24T12:58:28.885032376Z","labels":{"severity":"high"},"annotations":{"summary":"process_cpu_seconds_total is greater than 0.1"}}],"recording_rules":null}]},"status":"success"}[root@master-node linux-amd64]#_

Could you please let know if rule files name need to be in any specific name format or please correct me if i have done anything wrong in the above mentioned steps? In my case i need to add multiple rules file with different names.

Thanks

**Comment by f41gh7** [comment]
Get it, seems like helm chart incorrectly renders "*" symbol. 

 Need to apply fix for it. 

 Will do it soon.

**Comment by cathyalex** [comment]
> Get it, seems like helm chart incorrectly renders "*" symbol.
> 
> Need to apply fix for it.
> 
> Will do it soon.

 Thanks for your response @f41gh7. So at present, multiple rule files usage is not supported in vmalert? Is my understanding correct?

**Comment by f41gh7** [comment]
can you try it with `vmalert` chart version `0.3.23` ? 

 It should be ready soon.

**Comment by f41gh7** [comment]
> > Get it, seems like helm chart incorrectly renders "*" symbol.
> > Need to apply fix for it.
> > Will do it soon.
> 
> Thanks for your response @f41gh7. So at present, multiple rule files usage is not supported in vmalert? Is my understanding correct?

 It must support multiple files with wildcard, but if you pass command arg `-rule=/path/*.yaml` it will expand path with first matched file, that why for kubernetes arg `-rule="/path/*.yaml"` must be quoted.  New chart version must fix it.

**Comment by cathyalex** [comment]
> can you try it with `vmalert` chart version `0.3.23` ?
> 
> It should be ready soon.

@f41gh7 I have updated the vm repo and installed vmalert with below command by using the --version explicitly. However, still the issue persists.
**./helm install vmalert vm/victoria-metrics-alert --version 0.3.23 -f /opt/apps/monitoring/vmalert/values.yaml -n monitoring**
NAME: vmalert
LAST DEPLOYED: Thu Mar 25 10:45:02 2021
NAMESPACE: monitoring
STATUS: deployed
REVISION: 1
TEST SUITE: None

**Below is the docker image version present in worker node:**
**victoriametrics/vmalert                            v1.56.0                 5327e03efeb0   8 days ago           17MB**

**values.yaml image config for your reference:**
_server:
  name: server
  enabled: true
  image:
    repository: victoriametrics/vmalert
    tag: "" # rewrites Chart.AppVersion
    pullPolicy: IfNotPresent
  nameOverride: ""
  fullnameOverride: ""_

**Please let know if there are any issues with the installation command/config I have mentioned above.**

As you have mentioned that it is taking the first matched file - I have tried to edit my second filename as '**aa**_fed-amf-fed-amf-amf-cc-alerts-rules.yaml' (to pick that file first) and kept the 'alert-rules.yaml' file name as such.
I re-did the below steps,
1. Deleted and created 'extra-rules' configmap again by pointing the entire dir in --from-file
2. Below is the content of extra-rules config
     
![image](https://user-images.githubusercontent.com/81250004/112424301-2dce4d00-8d5a-11eb-96fe-5d898045cd54.png)

3. As you can note in the attached image, 'amf-cc.alert.rules' group is mentioned first in the configmap. Same goes with the files in the dir path as well. (i.e) aa_fed-amf-fed-amf-amf-cc-alerts-rules.yaml is placed first. 
4. However, vmalert is picking only the group mentioned in 'alert-rules.yaml' file. I verified the same with checking groups api.

**Could you please let know if there is anything to do with rule file name - as its only considering the groups in alerts-rules.yaml file?**

Also I edited the 'alert-rules.yaml' to '**ab**_alert-rules.yaml' and re-created configmap and re-installed the vmalert.
I could see no groups have been picked up and could see below logs in the pods.

_{"ts":"2021-03-25T05:26:51.109Z","level":"info","caller":"VictoriaMetrics/app/vmalert/manager.go:84","msg":"reading rules configuration file from \"/config/alert-rules.yaml;/opt/apps/monitoring/vmalert/rules/*.yaml\""}
**{"ts":"2021-03-25T05:26:51.109Z","level":"warn","caller":"VictoriaMetrics/app/vmalert/config/config.go:254","msg":"no groups found in /config/alert-rules.yaml;/opt/apps/monitoring/vmalert/rules/*.yaml"}**
{"ts":"2021-03-25T05:26:51.110Z","level":"info","caller":"VictoriaMetrics/lib/httpserver/httpserver.go:82","msg":"starting http server at http://:8880/"}
{"ts":"2021-03-25T05:26:51.110Z","level":"info","caller":"VictoriaMetrics/lib/httpserver/httpserver.go:83","msg":"pprof handlers are exposed at http://:8880/debug/pprof/"}_

**Comment by cathyalex** [comment]
@f41gh7 Hi Nikolay, Any update on the above mentioned query?

**Comment by f41gh7** [comment]
> @f41gh7 Hi Nikolay, Any update on the above mentioned query?

 Sorry for delay, 

 Cannot reproduce it, for me it works, example steps:

```yaml
#values.yaml
  extraArgs:
    envflag.enable: "true"
    envflag.prefix: VM_
    loggerFormat: json
    rule: "/etc/extra-rules/*.yaml"

  # Extra Volumes for the pod
  extraVolumes:
    - name: extra-rules
      configMap:
        name: extra-r

  # Extra Volume Mounts for the container
  extraVolumeMounts:
     - name: extra-rules
       mountPath: /etc/extra-rules
```

 Pod args: 
```yaml
  containers:
  - args:
    - -rule=/config/alert-rules.yaml
    - -datasource.url=http://some
    - -datasource.basicAuth.password=
    - -datasource.basicAuth.username=
    - -notifier.url=http://some
    - -remoteRead.url=
    - -remoteWrite.url=
    - -envflag.enable=true
    - -envflag.prefix=VM_
    - -loggerFormat=json
    - -rule="/etc/extra-rules/*.yaml"
    name: victoria-metrics-alert-server
```

 cm content:

```yaml
Name:         extra-r
Namespace:    default

Data
====
example2_rules.yaml:
----
groups:
- name: groupFiring5
  rules:
  - alert: VMRows
    for: 1s
    expr: |
      go_memstats_alloc_bytes
        >
         0

example_rules.yaml:
----
groups:
- name: groupFiring1
  rules:
  - alert: VMRows
    for: 1s
    expr: |
      go_memstats_alloc_bytes
        >
         0
```

log content: 

```json
{"ts":"2021-03-29T09:39:17.224Z","level":"info","caller":"VictoriaMetrics/app/vmalert/manager.go:84","msg":"reading rules configuration file from \"/config/alert-rules.yaml;/etc/extra-rules/*.yaml\""}
{"ts":"2021-03-29T09:39:17.225Z","level":"info","caller":"VictoriaMetrics/lib/httpserver/httpserver.go:82","msg":"starting http server at http://:8880/"}
{"ts":"2021-03-29T09:39:17.225Z","level":"info","caller":"VictoriaMetrics/lib/httpserver/httpserver.go:83","msg":"pprof handlers are exposed at http://:8880/debug/pprof/"}
{"ts":"2021-03-29T09:39:18.797Z","level":"info","caller":"VictoriaMetrics/app/vmalert/group.go:215","msg":"group \"groupFiring1\" started; interval=1m0s; concurrency=1"}
{"ts":"2021-03-29T09:39:46.057Z","level":"info","caller":"VictoriaMetrics/app/vmalert/group.go:215","msg":"group \"groupFiring5\" started; interval=1m0s; concurrency=1"}
```
