### ISSUE TITLE
vmagent  discovers targets for kubernetes role pods incorrectly

### ISSUE THREAD

**Issue by f41gh7** [VictoriaMetrics/VictoriaMetrics#1170]
**Describe the bug**

 When job contains multiple namespaces, targets discovery becomes inconsistent - some ports are missing, if pod has multiple ports.

**To Reproduce**
```yaml
scrape_configs:
  - job_name: 'kubernetes-pods'

    kubernetes_sd_configs:
    - role: pod
      namespaces:
        names:
        - tvpp-cis
        - tvpp-b2b-cis1
        - tvpp-b2b-cis2

    relabel_configs:
    - source_labels: [meta_kubernetes_pod_annotation_prometheus_io_port, __meta_kubernetes_pod_container_port_number]
      action: keep_if_equal
    - source_labels: [__meta_kubernetes_pod_annotation_prometheus_io_scrape]
      action: keep
      regex: true
    - source_labels: [__meta_kubernetes_pod_annotation_component]
      action: drop
      regex: (springboot|jboss)
    - source_labels: [__meta_kubernetes_pod_annotation_prometheus_io_path]
      action: replace
      target_label: __metrics_path
      regex: (.+)
    - source_labels: [address, meta_kubernetes_pod_annotation_prometheus_io_port]
      action: replace
      regex: ([^:]+)(?::\d+)?;(\d+)
      replacement: $1:$2
      target_label: __address
    - action: labelmap
      regex: __meta_kubernetes_pod_label_(.+)
    - source_labels: [__meta_kubernetes_namespace]
      action: replace
      target_label: kubernetes_namespace
    - source_labels: [__meta_kubernetes_pod_name]
      action: replace
      target_label: kubernetes_pod_name
    - source_labels: [__meta_kubernetes_pod_annotation_application_framework]
      action: replace
      target_label: application_framework
```
**Expected behavior**

 Must discover all targets.
**Version**
The line returned when passing `--version` command line flag to binary. For example:
```
1.55 +
```

**Additional context**
```bash
v1.55.1 - VictoriaMetrics/lib/promscrape/scraper.go:353  kubernetes_sd_configs: added targets: 210, removed targets: 0; total targets: 210
v.1.56.0 -  VictoriaMetrics/lib/promscrape/scraper.go:359  kubernetes_sd_configs: added targets: 29, removed targets: 0; total targets: 29
v1.57.1 -  VictoriaMetrics/lib/promscrape/scraper.go:359  kubernetes_sd_configs: added targets: 58, removed targets: 0; total targets: 58
```
```bash
ports:
  - containerPort: 8080
  - containerPort: 9080
```

**Comment by lujiajing1126** [comment]
@f41gh7 Would this issue cause `pod` label missing in some metrics, since we've observed this behavior recently.

**Comment by f41gh7** [comment]
> @f41gh7 Would this issue cause `pod` label missing in some metrics, since we've observed this behavior recently.

 I'm not sure.

 This case related to kubernetes discovery, when you specify more then one namespace at job name, like:
```yaml
    kubernetes_sd_configs:
    - role: pod
      namespaces:
        names:
        - tvpp-cis
        - tvpp-b2b-cis1
```

 In this case only targets from one of namespaces will be added to the scraping.
