### ISSUE TITLE
vmagent issues with proxy_url

### ISSUE THREAD

**Issue by ThomasADavis** [VictoriaMetrics/VictoriaMetrics#1179]
**Describe the bug**

I'm trying to get vmagent, to scrape a prometheus push proxy.

https://github.com/prometheus-community/PushProx

With prometheus, it works correctly.

With vmagent, I get 

```
error  when scraping "http://dev-k3s-2.omni:9100/metrics": error when sending  CONNECT request to proxy "http://dev-k3s-2:8080/": unexpected status  code received: 500; want: 200; try -enableTCP6 command-line flag if you  scrape ipv6 addresses
```

**To Reproduce**

Go to https://github.com/prometheus-community/PushProx.  Follow the steps to set up a simple proxy/client.

The proxy/client config there assumes a node-exporter is running.  It can be any exporter.

**Expected behavior**

vmagent able to scrape the proxy the same as prometheus.

**Screenshots**

**Version**
```
[root@dev-k3s-2 v]# ./vmagent-prod --version
vmagent-20210330-124411-tags-v1.57.1-0-g2d3082bb5
```

**Used command-line flags**

```
[root@dev-k3s-2 v]# ./vmagent-prod -remoteWrite.tmpDataPath /var/lib/metrics/ -promscrape.config /etc/prometheus/prometheus.yml -remoteWrite.url http://omni-vmetric.omni/insert/100000/prometheus/api/v1/write
```

Prometheus config:

```
[root@dev-k3s-2 v]# cat /etc/prometheus/prometheus.yml 
# my global config
global:
  scrape_interval:     15s # Set the scrape interval to every 15 seconds. Default is every 1 minute.
  evaluation_interval: 15s # Evaluate rules every 15 seconds. The default is every 1 minute.
  # scrape_timeout is set to the global default (10s).

# Alertmanager configuration
alerting:
  alertmanagers:
  - static_configs:
    - targets:
      # - alertmanager:9093

# Load rules once and periodically evaluate them according to the global 'evaluation_interval'.
rule_files:
  # - "first_rules.yml"
  # - "second_rules.yml"

# A scrape configuration containing exactly one endpoint to scrape:
# Here it's Prometheus itself.
scrape_configs:
  # The job name is added as a label `job=<job_name>` to any timeseries scraped from this config.
  - job_name: 'prometheus'

    # metrics_path defaults to '/metrics'
    # scheme defaults to 'http'.

    static_configs:
    - targets: ['localhost:9090']

  - job_name: node
    proxy_url: http://dev-k3s-2:8080/
    static_configs:
      - targets: ['dev-k3s-2.omni:9100']
```
