### ISSUE TITLE
Resource sync problem in vmagent

### ISSUE THREAD

**Issue by lujiajing1126** [VictoriaMetrics/VictoriaMetrics#1182]
**Describe the bug**

According to the discussion in issue #1170 and further investigation later, I have confirmed the problem which I suppose is different from the one reported in that issue.

The critical problem here is the resource sync procedure in the `vmagent`.

We are using `promscrape.config` generated from `VMServiceScrape` crds, 

```yaml
global:
  scrape_interval: 30s
  external_labels:
    prometheus: monitoring-system/beta-vmagent
scrape_configs:
- job_name: monitoring-system/vmagent-beta-vmagent/0
  honor_labels: false
  kubernetes_sd_configs:
  - role: endpoints
    namespaces:
      names:
      - monitoring-system
  metrics_path: /metrics
  relabel_configs:
  - action: keep
    source_labels:
    - __meta_kubernetes_service_label_app_kubernetes_io_component
    regex: monitoring
  - action: keep
    source_labels:
    - __meta_kubernetes_service_label_app_kubernetes_io_instance
    regex: beta-vmagent
  - action: keep
    source_labels:
    - __meta_kubernetes_service_label_app_kubernetes_io_name
    regex: vmagent
  - action: keep
    source_labels:
    - __meta_kubernetes_service_label_managed_by
    regex: vm-operator
  - action: keep
    source_labels:
    - __meta_kubernetes_endpoint_port_name
    regex: http
  - source_labels:
    - __meta_kubernetes_endpoint_address_target_kind
    - __meta_kubernetes_endpoint_address_target_name
    separator: ;
    regex: Node;(.*)
    replacement: ${1}
    target_label: node
  - source_labels:
    - __meta_kubernetes_endpoint_address_target_kind
    - __meta_kubernetes_endpoint_address_target_name
    separator: ;
    regex: Pod;(.*)
    replacement: ${1}
    target_label: pod
  - source_labels:
    - __meta_kubernetes_pod_name
    target_label: pod
  - source_labels:
    - __meta_kubernetes_namespace
    target_label: namespace
  - source_labels:
    - __meta_kubernetes_service_name
    target_label: service
  - source_labels:
    - __meta_kubernetes_service_name
    target_label: job
    replacement: ${1}
  - target_label: endpoint
    replacement: http
```

and I check the `/api/v1/targets` API to examine the relabeling config. A strange target (together with a normal case) are listed below,

```
# abnormal
[{
                "discoveredLabels": {
                    "__address__": "172.16.135.74:8080",
                    "__meta_kubernetes_endpoint_address_target_kind": "Pod",
                    "__meta_kubernetes_endpoint_address_target_name": "opr-merchant-promote-ack-deploy-7c6b6f9c89-4v4p8",
                    "__meta_kubernetes_endpoint_node_name": "cn-hangzhou.172.16.20.115",
                    "__meta_kubernetes_endpoint_port_name": "http-8080",
                    "__meta_kubernetes_endpoint_port_protocol": "TCP",
                    "__meta_kubernetes_endpoint_ready": "true",
                    "__meta_kubernetes_endpoints_label_app": "opr-merchant-promote-ack",
                    "__meta_kubernetes_endpoints_label_group": "opr",
                    "__meta_kubernetes_endpoints_labelpresent_app": "true",
                    "__meta_kubernetes_endpoints_labelpresent_group": "true",
                    "__meta_kubernetes_endpoints_name": "opr-merchant-promote",
                    "__meta_kubernetes_namespace": "sqb",
                    "__meta_kubernetes_service_cluster_ip": "10.0.15.45",
                    "__meta_kubernetes_service_label_app": "opr-merchant-promote-ack",
                    "__meta_kubernetes_service_label_group": "opr",
                    "__meta_kubernetes_service_labelpresent_app": "true",
                    "__meta_kubernetes_service_labelpresent_group": "true",
                    "__meta_kubernetes_service_name": "opr-merchant-promote",
                    "__meta_kubernetes_service_type": "ClusterIP",
                    "__metrics_path__": "/metrics",
                    "__scheme__": "http",
                    "job": "sqb/opr-merchant-promote/0",
                    "prometheus": "monitoring-system/hera-vmagent"
                },
                "labels": {
                    "endpoint": "http-8080",
                    "group": "opr",
                    "instance": "172.16.135.74:8080",
                    "job": "opr-merchant-promote",
                    "namespace": "sqb",
                    "prometheus": "monitoring-system/hera-vmagent",
                    "service": "opr-merchant-promote"
                },
                "scrapePool": "opr-merchant-promote",
                "scrapeUrl": "http://172.16.135.74:8080/metrics",
                "lastError": "",
                "lastScrape": "2021-04-03T14:21:14.463Z",
                "lastScrapeDuration": 0.014,
                "health": "up"
            },
# normal
{
                "discoveredLabels": {
                    "__address__": "172.16.135.65:8080",
                    "__meta_kubernetes_endpoint_address_target_kind": "Pod",
                    "__meta_kubernetes_endpoint_address_target_name": "aop-backend-sms-ack-deploy-7b6d66d558-jxzpv",
                    "__meta_kubernetes_endpoint_node_name": "cn-hangzhou.172.16.20.115",
                    "__meta_kubernetes_endpoint_port_name": "http-8080",
                    "__meta_kubernetes_endpoint_port_protocol": "TCP",
                    "__meta_kubernetes_endpoint_ready": "true",
                    "__meta_kubernetes_endpoints_label_app": "aop-backend-sms-ack",
                    "__meta_kubernetes_endpoints_label_group": "opr",
                    "__meta_kubernetes_endpoints_labelpresent_app": "true",
                    "__meta_kubernetes_endpoints_labelpresent_group": "true",
                    "__meta_kubernetes_endpoints_name": "aop-backend-sms",
                    "__meta_kubernetes_namespace": "sqb",
                    "__meta_kubernetes_pod_annotation_init0_ft_shouqianba_com_stages": "hera",
                    "__meta_kubernetes_pod_annotation_kubernetes_io_psp": "ack.privileged",
                    "__meta_kubernetes_pod_annotation_redeploy_timestamp": "1602644699791",
                    "__meta_kubernetes_pod_annotationpresent_init0_ft_shouqianba_com_stages": "true",
                    "__meta_kubernetes_pod_annotationpresent_kubernetes_io_psp": "true",
                    "__meta_kubernetes_pod_annotationpresent_redeploy_timestamp": "true",
                    "__meta_kubernetes_pod_container_name": "aop-backend-sms-ack",
                    "__meta_kubernetes_pod_container_port_name": "http-8080",
                    "__meta_kubernetes_pod_container_port_number": "8080",
                    "__meta_kubernetes_pod_container_port_protocol": "TCP",
                    "__meta_kubernetes_pod_controller_kind": "ReplicaSet",
                    "__meta_kubernetes_pod_controller_name": "aop-backend-sms-ack-deploy-7b6d66d558",
                    "__meta_kubernetes_pod_host_ip": "172.16.20.115",
                    "__meta_kubernetes_pod_ip": "172.16.135.65",
                    "__meta_kubernetes_pod_label_app": "aop-backend-sms-ack",
                    "__meta_kubernetes_pod_label_group": "opr",
                    "__meta_kubernetes_pod_label_pod_template_hash": "7b6d66d558",
                    "__meta_kubernetes_pod_labelpresent_app": "true",
                    "__meta_kubernetes_pod_labelpresent_group": "true",
                    "__meta_kubernetes_pod_labelpresent_pod_template_hash": "true",
                    "__meta_kubernetes_pod_name": "aop-backend-sms-ack-deploy-7b6d66d558-jxzpv",
                    "__meta_kubernetes_pod_node_name": "cn-hangzhou.172.16.20.115",
                    "__meta_kubernetes_pod_phase": "Running",
                    "__meta_kubernetes_pod_ready": "true",
                    "__meta_kubernetes_pod_uid": "28a0f73e-8708-4e44-aa1a-cf8adaa8408a",
                    "__meta_kubernetes_service_cluster_ip": "10.0.9.83",
                    "__meta_kubernetes_service_label_app": "aop-backend-sms-ack",
                    "__meta_kubernetes_service_label_group": "opr",
                    "__meta_kubernetes_service_labelpresent_app": "true",
                    "__meta_kubernetes_service_labelpresent_group": "true",
                    "__meta_kubernetes_service_name": "aop-backend-sms",
                    "__meta_kubernetes_service_type": "ClusterIP",
                    "__metrics_path__": "/metrics",
                    "__scheme__": "http",
                    "job": "sqb/aop-backend-sms/0",
                    "prometheus": "monitoring-system/hera-vmagent"
                },
                "labels": {
                    "endpoint": "http-8080",
                    "group": "opr",
                    "instance": "172.16.135.65:8080",
                    "job": "aop-backend-sms",
                    "namespace": "sqb",
                    "pod": "aop-backend-sms-ack-deploy-7b6d66d558-jxzpv",
                    "prometheus": "monitoring-system/hera-vmagent",
                    "service": "aop-backend-sms"
                },
                "scrapePool": "aop-backend-sms",
                "scrapeUrl": "http://172.16.135.65:8080/metrics",
                "lastError": "",
                "lastScrape": "2021-04-03T14:21:26.535Z",
                "lastScrapeDuration": 0.007,
                "health": "up"
            }]
```

As you can see in the excerpted response, the pod labels are totally missing. So after relabel, the pod label could be missing.

**To Reproduce**

I suppose any network latency while starting up or huge object transfering/decoding could easily reproduce the issue.

**Version**

vmagent 1.57.1

**Used command-line flags**

```yaml
# for k8s ContainerSpec
args:
- '-httpListenAddr=:8429'
- '-promscrape.config=/etc/vmagent/config_out/vmagent.env.yaml'
- '-remoteWrite.maxDiskUsagePerURL=1073741824'
- '-remoteWrite.tmpDataPath=/tmp/vmagent-remotewrite-data'
- >-
  -remoteWrite.url=http://vminsert-hera-vmcluster:8480/insert/0/prometheus/api/v1/write
```
