### ISSUE TITLE
vmalert: plotting a recorded metric along with the original in grafana requires a offset for them to match

### ISSUE THREAD

**Issue by raags** [VictoriaMetrics/VictoriaMetrics#1232]
**Describe the bug**
The screenshot below shows the difference in the original query and the recording rule. The graph does not match without the `offset` equal to the scrape interval.

![99452354-544b2a00-291b-11eb-9e30-56da95252d4e](https://user-images.githubusercontent.com/697714/115220656-6decd980-a126-11eb-9e78-0ea6beab6ea4.png)

The following parameters have been explored:
* `-search.latencyOffset=15s` - (victoriametrics) to ensure recording rule doesn't miss any datapoint (due to delay in scraping)
- `-datasource.queryStep=15s` - (vmagent) - to ensure step matches grafana step
- `-evaluationInterval=15s` - (vmagent) - matches scrape interval
- `-datasource.lookback=15s` - (vmagent) - to let vmagent "offset" match the search latency offset. This should ideally *fix* the issue I'm seeing.

**To Reproduce**
**docker-compose.yml**
```
version: '2.4'
services:
  victoriametrics:
    container_name: victoriametrics
    image: victoriametrics/victoria-metrics
    ports:
      - 8428:8428
    volumes:
      - vmdata:/vmdata
    command:
      - '-storageDataPath=/vmdata'
      - '-httpListenAddr=:8428'
      - '-selfScrapeInterval=0'
      - '-search.latencyOffset=15s'
  vmagent:
    container_name: vmagent
    image: victoriametrics/vmagent
    depends_on:
      - victoriametrics
    ports:
      - 8429:8429
    volumes:
      - vmagentdata:/vmagentdata
      - ./vm.yml:/tmp/vm.yml
    command:
      - '-promscrape.config=/tmp/vm.yml'
      - '-remoteWrite.url=http://victoriametrics:8428/api/v1/write'
  vmalert:
    container_name: vmalert
    image: victoriametrics/vmalert
    depends_on:
      - victoriametrics
    volumes:
      - ./vmalert_rules.yml:/tmp/alert.rules
    command:
      - '-rule=/tmp/alert.rules'
      # dummy notifier
      - '-notifier.url=http://127.0.0.1:9093'
      - '-datasource.url=http://victoriametrics:8428'
      - '-remoteWrite.url=http://victoriametrics:8428'
      - '-datasource.queryStep=15s'
      - '-evaluationInterval=15s'
      - '-datasource.lookback=15s'
```
**vm.yml**
```
---
global:
  scrape_interval:     15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: static_scrape
    static_configs:
    - targets:
        - victoriametrics:8428
```

**alert.rules**
```
groups:
 - name: HistogramAggregations
   rules:
     - record: test:scrape_duration_seconds:15s
       expr: >
         sum(rate(scrape_duration_seconds{instance=~"victoriametrics.*"}[15s]))
```
Plotting `test:scrape_duration_seconds:15s` and `sum(rate(scrape_duration_seconds{instance=~"victoriametrics.*"}[15s]))` still requires a `15s` offset to match.

**Expected behavior**
The original and recorded metric should match.

**Version**
The line returned when passing `--version` command line flag to binary. For example:
```
$ victoriametrics --version
victoria-metrics-20210408-064138-tags-v1.58.0-0-gedd1590ac
```

One round of discussion here: https://github.com/VictoriaMetrics/VictoriaMetrics/issues/832
