### ISSUE TITLE
Victoria-metrics Deduplication issue

### ISSUE THREAD

**Issue by fortindavid** [VictoriaMetrics/VictoriaMetrics#1238]
We are using victoria-metrics with prometheus
Prometheus remote-write to victoria-metrics and grafana is connected to victoria-metrics
When we are using more than one replica, metrics  in grafana are multiply 2 or 3
I have read and apply the following recommendations from victoria-metrics website in order to fix this issue:
1- Use the same scrape interval between prometheus and viuctoria metrics
2- Define an externalLabel in prometheus

```yaml
victoriametrics:
dedup.minScrapeInterval: 60s

prometheus:
    prometheusSpec:
      scrapeInterval: 60s
      externalLabels:
         datacenter: dev1
```
		 
It did not fix the issue, do you have any other solution to fix this bug

Victoria-metrics (Chart: 0.6.18 - Docker: v1.58.0)
kube-prometheus-stack (prometheus-operator): (Chart: 14.0.1 - Docker: v0.47.0 )

**Comment by f41gh7** [comment]
Hello, can you try to use following relabel config for prometheus-operator remoteWrite:

```yaml
writeRelabelConfigs:
        - action: labeldrop
          regex: prometheus_replica
```

Example of usage:
```yaml
prometheusOperator:
  nodeSelector:
    type: monitoring
prometheusK8s:
  remoteWrite:
    - url: "http://victoriametrics:8428/api/v1/write"
      writeRelabelConfigs:
        - action: labeldrop
          regex: prometheus_replica
      queueConfig:
        maxshards: 30
        capacity: 20000
        maxsamplespersend: 10000
  externalLabels:
    environment: Production
    cluster: cluster1
```

 By default, prometheus-operator adds per-replica label, which prevents data de-duplication.
