### ISSUE TITLE
Vmbackupmanager incorrect time

### ISSUE THREAD

**Issue by autokilla47** [VictoriaMetrics/VictoriaMetrics#1239]
**Describe the bug**
I am using a [vmbackupmanager](https://docs.victoriametrics.com/vmbackupmanager.html) container to create backups. I have the correct time and date in the container.
But after performing the backup, the directory with the backup has an incorrect hour(12 not 16).
```
[root@host]# ll /data/hourly/
total 0
drwx------. 5 root root 79 Apr 22 16:00 2021-04-22:12
[root@host]# docker exec -it vmbackupmanager date
Thu Apr 22 16:07:20 MSK 2021
```

**To Reproduce**
Run docker-compose file with vmbackupmanager service:
```
  vmbackupmanager:
    container_name: vmbackupmanager
    image: victoriametrics/vmbackupmanager:v1.56.0-enterprise
    depends_on:
      - "victoriametrics"
    volumes:
      - vmdata:/storage
      - /data:/data
      - /etc/localtime:/etc/localtime
    command:
      - '--eula'
      - '--disableWeekly'
      - '--disableMonthly'
      - '--keepLastHourly=7'
      - '--keepLastDaily=3'
      - '--storageDataPath=/storage'
      - '--loggerTimezone=Europe/Moscow'
      - '--snapshot.createURL=http://localhost:8428/snapshot/create'
      - '--dst=fs:///data'
```

**Expected behavior**
Name of folder have to be "2021-04-22:16"
```
[root@host]# docker exec -it vmbackupmanager date
Thu Apr 22 16:07:20 MSK 2021
[root@host]# ll /data/hourly/
total 0
drwx------. 5 root root 79 Apr 22 16:00 2021-04-22:16
```

**Version**
```
 build version: vmbackupmanager-20210317-002537-tags-v1.56.0-enterprise-0-g3646cbc86
```
