### ISSUE TITLE
vmagent does not recognize write_relabel_configs and does not write aggregated records

### ISSUE THREAD

**Issue by vkuznet** [VictoriaMetrics/VictoriaMetrics#1266]
**Describe the bug**
We would like to have the following setup:
- one VM instance (let's call it VM1) collect metrics
- vmagent reads from VM instance VM1 and based on prometheus record rules aggregated metrics which should be written to another VM instance (VM2).

The vmagent reads prometheus config and have section `remove_writes`. In this section I can specify `write_relabel_configs` to only select aggregated records to write.

**To Reproduce**
I have the following setup:
- run local VM instance to store aggregated records
- run local vmagent which scrape metrics from other source. It has the following configuration
```
rule_files:
  - "agg.rules"

remote_write:
  - url: http://localhost:8428/api/v1/write
    queue_config:
      max_samples_per_send: 10000
      max_shards: 30
    write_relabel_configs:
    - target_label: "aggregator"
      replacement: "vm"
    - source_labels: [aggregate]
      regex: "1h"
      action: keep

scrape_configs:
  - job_name: 'srv'
    scrape_interval: 60s
    file_sd_configs:
      - files:
        - srv.json
```
The `agg.rules` has the following content:
```
groups:
- name: srv
  rules:
  - record: avg_over_time:used_space:1h
    expr: avg_over_time(used_space[1h])
    labels:
      aggregate: 1h
```
and, srv.json contains URLs of servers we scape from.

**Expected behavior**
I expect only aggregated records `avg_over_time:used_space:1h` to be written in VM2 instance. Instead I see all `used_space` records in VM2 instance

**Version**
The line returned when passing `--version` command line flag to binary. For example:
```
$ ./victoria-metrics-prod --version
victoria-metrics-20210501-070722-tags-v1.59.0-0-gfb097ff77
```

**Used command-line flags**
```
#!/bin/bash
tsdb=/wma/vk/VictoriaMetrics/tsdb
mkdir -p $tsdb
nohup ./victoria-metrics-prod \
          -opentsdbHTTPListenAddr=:4242 \
          -retentionPeriod=1w \
          -storageDataPath=$tsdb \
          -search.maxConcurrentRequests=32 2>& 1>& vm.log < /dev/null &
```

**Additional context**
The common use-case, read from one source (Prometheus or VM), and write aggregated records into another VM.
