### ISSUE TITLE
Password from a file for vmauth

### ISSUE THREAD

**Issue by jtyr** [VictoriaMetrics/VictoriaMetrics#1290]
**Is your feature request related to a problem? Please describe.**
In the Kubernetes world, it's kind of weird to mix up secrets with plain configuration. It would be better to leverage the possibility to mount passwords from a `Secret` as files and then just point to a file from the config.

**Describe the solution you'd like**
I would like to have the following Secret where each data represents a password for a specific user:

```yaml
apiVersion: v1
kind: Secret
metadata:
  name: victoriametrics-vmauth
stringData:
  user1.pass: topsecretpassword
```

I would like have a ConfigMap that would hold the config:

```yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: victoriametrics-vmauth
stringData:
  config: |
    users:
      - username: user1
        ### THIS IS REQUIRED TO BE IMPLEMENTED
        password_file: /var/run/secrets/victoriametrics/auth/user1.pass
        url_prefix: "http://localhost:8428"
```

Then the Pod would be configured with Volumes that are mounted inside the container - one for the Secret, one for the ConfigMap.

**Describe alternatives you've considered**
N/A

**Additional context**
This feature opens the possibility to use external secret managers (e.g. [Kubernetes External Secrets](https://github.com/external-secrets/kubernetes-external-secrets)).

**Comment by valyala** [comment]
FYI, it is possible to specify passwords in `-auth.config` via environment variables. For example, the following config automatically replaces `%{PASSWORD_FROM_ENV_VAR}` with the value of `PASSWORD_FROM_ENV_VAR` environment variable:

```yaml
users:
- username: user1
  password: "%{PASSWORD_FROM_ENV_VAR}"
  ...
```

See https://docs.victoriametrics.com/vmauth/#auth-config for details.

This functionality has been appeared in [v1.40.0](https://docs.victoriametrics.com/CHANGELOG.html) after the commit c402265e883dac8045c76f8a6232540d47fa496a . See [this issue](https://github.com/VictoriaMetrics/VictoriaMetrics/issues/583) for more details.
