### ISSUE TITLE
VictoriaMetric/operator

### ISSUE THREAD

**Issue by WuJingLearn** [VictoriaMetrics/VictoriaMetrics#1356]
When I use Operator to build a cluster, can I set the cluster mode of VmSelect service to NodePort

**Comment by f41gh7** [comment]
Its possible with serviceSpec:

 It will create additional service for vmselect with name - `vmselect-node-access` and service for vminsert with name - `vminsert-example-vmcluster-persistent-additional-service`

```yaml
apiVersion: operator.victoriametrics.com/v1beta1
kind: VMCluster
metadata:
  name: example-vmcluster-persistent
spec:
  retentionPeriod: "4"
  replicationFactor: 2
  vmstorage:
    replicaCount: 1
  vmselect:
    replicaCount: 1
    serviceSpec:
         metadata:
               name: vmselect-node-access
         spec:
            type: NodePort
            ports:
            - name: http
              nodePort: 30581
              port: 8481
              protocol: TCP
              targetPort: 8481
  vminsert:
    replicaCount: 1
    serviceSpec:
       spec:
         spec:
            type: NodePort
```
