### ISSUE TITLE
vmagent can't scrape metrics with default k8s resources and streamParse is enabled

### ISSUE THREAD

**Issue by firaxis** [VictoriaMetrics/VictoriaMetrics#1365]
**Describe the bug**
Vmagent can't scrape from cadvisor.

**To Reproduce**
Setup vmagent with 
```
extraArgs:
    promscrape.streamParse: "true"
```
Add a scrape job like
```
- bearer_token_file: /var/run/secrets/kubernetes.io/serviceaccount/token
  job_name: kubelet-cadvisor
  metrics_path: /metrics/cadvisor
  scheme: https
  tls_config:
    caFile: /var/run/secrets/kubernetes.io/serviceaccount/ca.crt
    insecure_skip_verify: true
```
The response size is about 3.2Mb.
I can query it from vmagent container with curl. Curl total_time is about 1s.

**Expected behavior**
It should work.
Btw, it works if I bump memory limits to 800Mi, in my case.

**Logs**
```
error	VictoriaMetrics/lib/promscrape/scrapework.go:258	error when scraping "https://10.249.64.44:10250/metrics/cadvisor" from job "kubelet-cadvisor" with labels {}: cannot read Prometheus exposition data: context deadline exceeded
```

**Version**
The line returned when passing `--version` command line flag to binary. For example:
```
vmagent-20210609-161942-tags-v1.61.0-0-gb83a51366
```

**Used command-line flags**
```
/vmagent-prod 
-httpListenAddr=:8429 
-promscrape.config=/etc/vmagent/config_out/vmagent.env.yaml 
-promscrape.streamParse=true 
-remoteWrite.maxDiskUsagePerURL=1073741824 
-remoteWrite.relabelConfig=/etc/vm/relabeling/global_relabeling.yaml 
-remoteWrite.tmpDataPath=/tmp/vmagent-remotewrite-data
-remoteWrite.url=https://vm-single/api/v1/write/
```
