### ISSUE TITLE
1 minute gap on some metrics

### ISSUE THREAD

**Issue by xenofree** [VictoriaMetrics/VictoriaMetrics#1390]
**Describe the bug**
I have 1 minute lag on some metics beetwen prometheus and victoriametrics.
Can i have some help on this issue. Thanks

```  curl 'http://prometheus:9090/api/v1/query'
  {
    "status": "success",
    "data": {
      "resultType": "vector",
      "result": [
        {
          "metric": {
            "__name__": "probe_duration_seconds",
            "instance": "xxx",
            "job": "xxx"
          },
          "value": [
            1623938537.323,
            "0.000694671"
          ]
        }
      ]
    }
  }
```
```  curl 'http://victoriametrics:8428/api/v1/query'
  {
    "status": "success",
    "data": {
      "resultType": "vector",
      "result": [
        {
          "metric": {
            "__name__": "probe_duration_seconds",
            "datacenter": "xxx",
            "instance": "xxx",
            "job": "xxx"
          },
          "value": [
            1623938537,
            "0.000523012"
          ]
        }
      ]
    }
}
```

![image](https://user-images.githubusercontent.com/35098906/122411434-0bc51f00-cf85-11eb-83b9-9de74b82cf95.png)

**Version**
```  / # /victoria-metrics-prod --version
  victoria-metrics-20210611-102507-tags-v1.61.1-0-g2ef2e3d6f`
  / # ps
  /victoria-metrics-prod -retentionPeriod=3 -selfScrapeInterval=1m -dedup.minScrapeInterval=1m
```

**Prometheus Configuration**
```
    remote_write:
    - url: http://x.x.x.x8428/api/v1/write
      queue_config:
        capacity: 20000
        max_samples_per_send: 10000
        max_shards: 30
      write_relabel_configs:
      - source_labels: [ datacenter ]
        target_label: datacenter
        regex: (^xxx)-\d*$
        replacement: $1
        action: replace
```
