### ISSUE TITLE
Reload TLS certificates / keys from disk automatically

### ISSUE THREAD

**Issue by fujin** [VictoriaMetrics/VictoriaMetrics#1420]
**Is your feature request related to a problem? Please describe.**
In my environment, we are using Istio service-mesh. As part of that, we have to scrape some Application metrics over Strict mTLS. To scrape metrics over strict mTLS, we inject an automatically-rotated client certificate, key and root ca into a volume, mounted on the pod's filesystem. You can find a [reference configuration for Prometheus here](https://istio.io/latest/docs/ops/integrations/prometheus/#tls-settings). I have translated this to my vmagent setup.

The certificate is automatically rotated every 24 hours.

When the certificate is rotated, vmagent immediately begins failing scraping of the strict mTLS workloads, reporting e.g.:
```
cannot read data: cannot scrape "https://10.0.112.4:9091/metrics": Get "https://10.0.112.4:9091/metrics": remote error: tls: expired certificate
```

I confirmed the valid, rotated certificate is able to access the resource by executing into the pod and testing with cURL.

The problem seems to be in vmagent not reloading the tlsConfig certificate, keypair, or root CA, when they are updated (on-disk).

**Describe the solution you'd like**
- Reload certificates automatically from disk with filesystem (contents) watcher.
See https://github.com/prometheus/common/pull/173

**Describe alternatives you've considered**
- Move application-specific metrics off strict mTLS
- Reloading vmagent seems to not reload tlsConfig as the contents of the configuration file have not changed

**Additional context**
vmagent, vmsingle etc 1.58 via https://github.com/VictoriaMetrics/helm-charts/tree/master/charts/victoria-metrics-k8s-stack chart.

My `VMPodScrape` looks like this if it's helpful:
```  
    podMetricsEndpoints:
    - port: metrics
      path: /metrics
      scheme: https
      tlsConfig:
        caFile: /etc/prom-certs/root-cert.pem
        certFile: /etc/prom-certs/cert-chain.pem
        keyFile: /etc/prom-certs/key.pem
        insecureSkipVerify: true
```

And the `VMAgentSpec` relevant section:
```
      volumes:
        - name: istio-certs
          emptyDir:
            medium: Memory
      volumeMounts:
        - mountPath: /etc/prom-certs
          name: istio-certs
      podMetadata:
        annotations:
          traffic.sidecar.istio.io/includeInboundPorts: "" # do not intercept any inbound ports
          traffic.sidecar.istio.io/includeOutboundIPRanges: "" # do not intercept any outbound traffic
          proxy.istio.io/config:
            | # configure an env variable `OUTPUT_CERTS` to write certificates to the given folder
            proxyMetadata:
              OUTPUT_CERTS: /etc/istio-output-certs
          sidecar.istio.io/userVolumeMount: '[{"name": "istio-certs", "mountPath": "/etc/istio-output-certs"}]' # mount the shared volume at sidecar proxy
```
