### ISSUE TITLE
Metrics Values ​​differ between Promtheus and VictoriaMetrics

### ISSUE THREAD

**Issue by ktpktr0** [VictoriaMetrics/VictoriaMetrics#1429]
I use docker swarm to install two Prometheus and set up remote_ Write to Victoria metrics. When I use vmselect and Prometheus to query data, I find that the data of Victoria metrics is much higher than that of Prometheus

prometheus:

![image](https://user-images.githubusercontent.com/41657218/124268559-3f4e9e80-db6c-11eb-87f4-b74648ce533e.png)

VictoriaMetrics:
![image](https://user-images.githubusercontent.com/41657218/124269101-06fb9000-db6d-11eb-9eae-859082b88441.png)

**Comment by valyala** [comment]
It looks like two identically configured Prometheus instances write data to the same VictoriaMetrics. If this is the case, then the deduplication must be enabled at VictoriaMetrics side. See [the deduplication docs](https://docs.victoriametrics.com/#deduplication) for more details. If the de-duplication isn't enabled in this case, then some functions such as `rate()` can return unexpectedly high results, since they improperly detect e.g. counter resets.

If Prometheus instances scrape different target sets, then it is recommended setting up distinct external labels per each Prometheus, so they write metrics to different time series in VictoriaMetrics. See [Prometheus configuration docs](https://docs.victoriametrics.com/#prometheus-setup) for more details.

**Comment by ktpktr0** [comment]
According to your guidance, my final configuration is as follows. Must the value of - dedup. Minscrapeinterval of vmstorage also be 1ms?, Or is it equal to scratch_ Config in intervalprometheus configuration

```
 vmstorage:
    image: victoriametrics/vmstorage:v1.61.1-cluster
    hostname: vmstorage
    networks:
      - monitor
    ports:
      - 8482:8482
      - 8400:8400
      - 8401:8401
    volumes:
      - /data/vmcluster/storage:/storage
    command:
      - '--storageDataPath=/storage'
      - '--retentionPeriod=1'

  vminsert:
    image: victoriametrics/vminsert:v1.61.1-cluster
    hostname: vminsert
    networks:
      - monitor
    ports:
      - 8480:8480
    depends_on:
      - "vmstorage"
    command:
      - '--storageNode=vmstorage:8400'
      - '--replicationFactor=2'

 vmselect:
    image: victoriametrics/vmselect:v1.61.1-cluster
    hostname: vmselect
    networks:
      - monitor
    ports:
      - 8481:8481
    depends_on:
      - "vmstorage"
    command:
      - '--storageNode=vmstorage:8401'
      - '--cacheDataPath=/tmp'
      - '--dedup.minScrapeInterval=1ms'
```
