### ISSUE TITLE
vmauth host header for backends

### ISSUE THREAD

**Issue by anvpetrov** [VictoriaMetrics/VictoriaMetrics#1445]
I have instalation of vmselect in Openshift cluster.
vmselect url is under ingress controller(haproxy).

If I try to configure vmauth to proxy requests to this vmselect , its return error from Openshift ingress : Service Unavalible.
I think vmauth dont add host header to request.

**To Reproduce**
1. Setup vmauth with config
```
[root@p1cube-cn1066lv install]# cat vmauth_config.yaml
users:
- username: grafana-infra-dev
  password: Qw12345
  url_prefix: http://vmselect-mon.apps.ocp-cluster.local.domain/select/0/prometheus
```

2. Try to add datasource to grafana and its return error: Service Unavalible.

**Expected behavior**
vmauth correctly proxies requests to vmselect

**Logs**
Error from grafana: Service Unavalible
**Version**
v1.62.0
