### ISSUE TITLE
Target described in  VmServiceScrape not shown

### ISSUE THREAD

**Issue by d-malko** [VictoriaMetrics/VictoriaMetrics#1451]
**Describe the bug**

Hello team! 
I wanted to switch from Prometheus in my k8s cluster, but have an issue with discovering my service.
I installed the latest VictoriaMetrics using helm chart 
```
helm install vm vm/victoria-metrics-k8s-stack -f values.yaml -n monitoring
```
For example, I choose the service `contract-service` in the namespace `rn-develop`. All metrics gathered on port 9321(k8s service alias is `management`) with path `/actuator/prometheus`. You can see screenshot with metrics below in the part with screenshots.
Create k8s` manifest for kind vmservicescrape (you can see the full configuration below) in one with contract-service namespace.

But at this moment, I don't see a target with my service and metrics from it.

I talked with some of your teammates in slack's channel, but at this moment we didn't manage to make it work.
If needed, I can add any additional information you need.
I need your help very much )

As suggestions, I think this issue can be related to:
* RBAC
* service port not picked correctly. I tried to choose numeric 9321 and alias `management`

**To Reproduce**
Install VM using helm chart
```


helm list -n monitoring
NAME	NAMESPACE 	REVISION	UPDATED                              	STATUS  	CHART                           	APP VERSION
vm  	monitoring	1       	2021-07-13 17:34:51.938992 +0300 EEST	deployed	victoria-metrics-k8s-stack-0.2.9	1.16.0

values.yaml
...
vmagent:
  enabled: true
  spec:
    scrapeInterval: 25s
    serviceScrapeNamespaceSelector: {}
    serviceScrapeSelector: {}
    externalLabels:
      cluster: qnt-low
    extraArgs:
      promscrape.streamParse: "true"
...
```
VmServiceScape
```

apiVersion: operator.victoriametrics.com/v1beta1
kind: VMServiceScrape
metadata:
  name: {{ include "contract-service.fullname" . }}
  namespace: cm-develop
spec:
  discoveryRole: service
  targetLabels: []
  podTargetLabels: []
  endpoints:
    - port: management
      path: /actuator/prometheus
      scheme: http
      scrapeTimeout: 2s
  namespaceSelector: {}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "contract-service.name" . }}
      app.kubernetes.io/component: "cm"

```
vmagent part of config from container
```
/ # cat /etc/vmagent/config_out/vmagent.env.yaml
global:
  scrape_interval: 25s
  external_labels:
    cluster: qnt-low
    prometheus: monitoring/vmetrics-victoria-metrics-k8s-stack
scrape_configs:
- job_name: cm-develop/contract-service/0
  honor_labels: false
  kubernetes_sd_configs:
  - role: service
    namespaces:
      names:
      - cm-develop
  scrape_timeout: 2s
  metrics_path: /actuator/prometheus
  scheme: http
  relabel_configs:
  - action: keep
    source_labels:
    - __meta_kubernetes_service_label_app_kubernetes_io_component
    regex: cm
  - action: keep
    source_labels:
    - __meta_kubernetes_service_label_app_kubernetes_io_name
    regex: contract-service
  - action: keep
    source_labels:
    - __meta_kubernetes_service_port_name
    regex: "management"
  - source_labels:
    - __meta_kubernetes_namespace
    target_label: namespace
  - source_labels:
    - __meta_kubernetes_service_name
    target_label: service
  - source_labels:
    - __meta_kubernetes_service_name
    target_label: job
    replacement: ${1}
  - target_label: endpoint
    replacement: "management"
```
**Expected behavior**
I want to see target `contract-service` and metrics from it.

**Logs**
I don't see any errors in the log
In the operator log, I can see strings
```
{"level":"info","ts":1626187686.6764777,"logger":"controllers.VMServiceScrape","msg":"Reconciling VMServiceScrape","vmservicescrape":"cm-develop/contract-service"}
{"level":"info","ts":1626187686.6765938,"logger":"controllers.VMServiceScrape","msg":"found vmagent objects ","vmservicescrape":"cm-develop/contract-service","len: ":1}
{"level":"info","ts":1626187686.67661,"logger":"controllers.VMServiceScrape","msg":"reconciling servicescrapes for vmagent","vmservicescrape":"cm-develop/contract-service","vmagent":"vm-victoria-metrics-k8s-stack"}
```

**Screenshots**
All my VmServiceScrapes
![image (1)](https://user-images.githubusercontent.com/26520297/125572602-a9c762cc-7511-4934-95d9-0b2b211ccb68.png)
Description of contract-service vmServiceScrape
![image (2)](https://user-images.githubusercontent.com/26520297/125572675-abb13540-6399-492c-8693-d5754da2d482.png)
Metrics from contract service can be gathered

![image (3)](https://user-images.githubusercontent.com/26520297/125572715-e1f4de16-1308-44b1-a8fa-8543c1292c8e.png)

Targets visible at  this moment
![image (4)](https://user-images.githubusercontent.com/26520297/125572900-950c347e-af82-4fe3-ad03-38ab87aa79a0.png)

**Version**

Kubernetes EKS
v1.20.4-eks-6b7464

```
helm list -n monitoring
NAME	NAMESPACE 	REVISION	UPDATED                              	STATUS  	CHART                           	APP VERSION
vm  	monitoring	1       	2021-07-13 17:34:51.938992 +0300 EEST	deployed	victoria-metrics-k8s-stack-0.2.9	1.16.0
```
