### ISSUE TITLE
Problem querying specific metric ranges. Doesn't work for all ranges what we need.

### ISSUE THREAD

**Issue by mr-yaky** [VictoriaMetrics/VictoriaMetrics#1486]
**Summary**
On VictoriaMetrics when querying specific ranges, even if theres data stored on the metric, we get no result.

**Steps to reproduce**

1. Go to grafana and query `Z04_30S_AGG_TS{_id_park="5013f7bb284a2917e1ca9812"}`.
1. Select different periods.

![image](https://user-images.githubusercontent.com/18198525/126752962-0a82464f-900f-4f25-ba0a-006812eedc59.png)
![image (1)](https://user-images.githubusercontent.com/18198525/126752966-e434b4c0-6402-4e6b-900f-9ec277b9cbc1.png)

When we select last 90 days (or **periods between -50/-100 days** ) we get no result, but we know there are datapoints stored.

**Additional Information**

* It's happening with different versions for us
* It doesn't happen to all metrics in the enviroment (e.g  some other our metrics doesn't have this problem)
* Same metrics with different tags have different behaviour
* Looks like the metrics/tags not working are the same in the 3 enviroments, so could be data related?.
* We get the same result querying via HTTP.

**Version**
v1.61.1, v1.63.0 (cluster version)

**Comment by valyala** [comment]
@mr-yaky , which `-retentionPeriod` do you pass to `vmstorage`?

The issue could be related to response cache, which could cache results outside the retention period. Try sending http requests to `http://<vmselect>:8481//internal/resetRollupResultCache`, where `<vmselect>` must be substituted with every existing `vmselect` host. This will reset response caches at `vmselect` nodes. Then try sending the same queries again and verify whether they return expected results. See also https://docs.victoriametrics.com/#backfilling

**Comment by mr-yaky** [comment]
@valyala Thank you for your answer.
We have `search.disableCache` as `True` and it was before in our configuration. 

```
vmstorage:
  replicaCount: 2
  extraArgs:
    dedup.minScrapeInterval: 1ms
  retentionPeriod: 120
  ...

vmselect:
  replicaCount: 3
  extraArgs:
    dedup.minScrapeInterval: 1ms
    search.latencyOffset: 0s
    search.maxPointsPerTimeseries: 600000
    search.disableCache: true
    ....
```

I'm not sure if we can try any from these recommendations from https://docs.victoriametrics.com/#backfilling if we already have disabled cache.
