### ISSUE TITLE
Add timeseries with failed scrape targets

### ISSUE THREAD

**Issue by weastur** [VictoriaMetrics/VictoriaMetrics#1529]
**Is your feature request related to a problem? Please describe.**
When some target fails to scrape, we can know the fact of fail by `vm_promscrape_targets` metric, but the only fact of fail. We don't know the exactly failed target. I know that this information can be found on `/api/v1/targets` api or even logs, but it's hard to make an alert without an existing corresponding metric. 

**Describe the solution you'd like**
Add timeseries or label indicating failed target.

**Comment by hagen1778** [comment]
Hi @weastur! Thank you for a feature request.
In my personal opinion, failing target has event-like nature, not a time series one. For example, if target goes down due to network issues, the metric for it will be created and remain active until target is back. After that, there will be no use for that metric anymore. So it is more like an event, not a continuous state.
Also, users can have thousands of targets configured/discovered. And if, for example, there will be network split and vmagent become isolated from the network - it will have to create thousands of metrics to reflect the state for every failed target. This could result into unexpected cardinality explosion.

I'd advice to create a following alert:
```
    - alert: TooManyScrapeErrors
        expr: sum(increase(vm_promscrape_scrapes_failed_total[5m])) by (instance) > 0
        for: 15m
        labels:
          severity: warning
        annotations:
          dashboard: "http://your-grafana:3000/d/G7Z9GzMGz?viewPanel=31&var-instance={{ $labels.instance }}"
          targets: "http://{{ $labels.instance }}:8429/api/v1/targets"
          summary: "Vmagent on instance {{ $labels.instance }} fails to scrape targets for last 15m"
```
On receiving such an alert, operator can either use `dashboard` link to see the overall status for vmagent, or use `targets` link and go directly to this specific vmagent UI to see the actual failing target.
