### ISSUE TITLE
delta and changes return wrong data 

### ISSUE THREAD

**Issue by manoja1** [VictoriaMetrics/VictoriaMetrics#1556]
**Describe the bug**
We are running on the latest v1.64.1

In VictoriaMetrics`delta` and `changes` return `1` even when the previous data point has no data. This is different from how Prometheus works.  

**Screenshots**
See grafana charts below. we started reporting a new metric `asserts:version:info` and immediately `delta[5m]` and `changes[5m]` return `1`.

<img width="2377" alt="Screen Shot 2021-08-23 at 2 30 42 PM" src="https://user-images.githubusercontent.com/33231759/130522154-1c28bbbb-13fc-463b-bd5c-2e25e1a51937.png">

**Expected behavior**
See below promtool test that exhibits the desired behavior.  

```
evaluation_interval: 1m
tests:
  - interval: 1m
    input_series:
      - series: 'test:stale{workload="test"}'
        values: 'stale stale 1  2 stale 2 stale'
    promql_expr_test:
      - expr: changes(test:stale[1m]) > 0
        eval_time: 1m
        exp_samples:

      - expr: changes(test:stale[1m]) > 0
        eval_time: 2m
        exp_samples:

      - expr: changes(test:stale[1m]) > 0
        eval_time: 3m
        exp_samples:
          - labels: '{workload="test"}'
            value: 1

      - expr: changes(test:stale[1m]) > 0
        eval_time: 4m
        exp_samples:

      - expr: changes(test:stale[1m]) > 0
        eval_time: 5m
        exp_samples:

      - expr: changes(test:stale[1m]) > 0
        eval_time: 6m
        exp_samples:
      
      # test delta
      - expr: delta(test:stale[1m]) > 0
        eval_time: 1m
        exp_samples:

      - expr: delta(test:stale[1m]) > 0
        eval_time: 2m
        exp_samples:

      - expr: delta(test:stale[1m]) > 0
        eval_time: 3m
        exp_samples:
          - labels: '{workload="test"}'
            value: 1

      - expr: delta(test:stale[1m]) > 0
        eval_time: 4m
        exp_samples:

      - expr: delta(test:stale[1m]) > 0
        eval_time: 5m
        exp_samples:

      - expr: delta(test:stale[1m]) > 0
        eval_time: 6m
        exp_samples:

```

**Version**
version metric from`vm_app_version`
<img width="1656" alt="Screen Shot 2021-08-23 at 2 29 28 PM" src="https://user-images.githubusercontent.com/33231759/130522033-3466e2ee-f8a5-4a17-a4c7-d84f518591af.png">
