### ISSUE TITLE
rate behaves differently than in Prometheus

### ISSUE THREAD

**Issue by kalgary** [VictoriaMetrics/VictoriaMetrics#165]
**Describe the bug**
Hi, 
I'm evaluating the use of Victoria metrics as long term storage, my goal is to get rid of Prom federation.

I have noticed a different behavior when the same query is run against prom and victoria metrics. 

rate(process_cpu_seconds_total{job="$instance-kafka1"}[1m])

VICTORIA METRICS

![image](https://user-images.githubusercontent.com/43787166/63831553-245ae400-c96f-11e9-9bae-3e9d84b1dbda.png)

PROMETHEUS
![image](https://user-images.githubusercontent.com/43787166/63831620-49e7ed80-c96f-11e9-883b-ed8a888247fb.png)

stored time series seems to contain the same data:

process_cpu_seconds_total{job="$instance-kafka1"}

VICTORIA METRICS

![image](https://user-images.githubusercontent.com/43787166/63831755-a9de9400-c96f-11e9-81bc-799201662c46.png)

PROMETHEUS
![image](https://user-images.githubusercontent.com/43787166/63831791-bebb2780-c96f-11e9-949e-52a4b5135e3a.png)

Configuration on Prometheus side:
```
remote_write:
- url: http://10.8.24.62:8428/api/v1/write
  remote_timeout: 30s
  queue_config:
    capacity: 100000
    max_shards: 30
    max_samples_per_send: 10000
    batch_send_deadline: 5s
    max_retries: 10
    min_backoff: 30ms
    max_backoff: 100ms
``` 
**Expected behavior**
I expect to see the same graph when querying the two different backends from grafana, Prom or Victoria metrics should produce the same trends, but as you can see in the graphs, this is not the case.

**Version**
```
$ ./victoria-metrics-prod --version
victoria-metrics-20190813-235905-tags-v1.25.0-0-g5b411222
```
