### ISSUE TITLE
vmagent could not discovery targets with  openstack_sd_config

### ISSUE THREAD

**Issue by nevlkv** [VictoriaMetrics/VictoriaMetrics#1655]
**Describe the bug**
Vmagent could not connect and discovery targets in openstack endpoints, prometheus with same config work correctly

**To Reproduce**
**Used config** 

```
global:
  scrape_interval: 1m # Set the scrape interval to every 1 minute seconds. Default is every 1 minute.
  scrape_timeout: 1m


scrape_configs:
  - job_name: 'openstack-node'
    openstack_sd_configs:
      - role: 'instance'
        region: 'ru-*****-1'
        identity_endpoint: 'https://iam.*******.ru/v3'
        username: 'prometheus'
        domain_name: '*******'
        domain_id: '******'
        project_id: '*********'
        password: '********'
        port: 9100
    relabel_configs:
      - source_labels: [__meta_openstack_tag_prometheus]
        regex: true
        action: keep
      - source_labels: [__meta_openstack_instance_name]
        action: replace
        target_label: instance_name
      - source_labels: [__meta_openstack_instance_flavor]
        action: replace
        target_label: instance_flavor
      - source_labels: ['__address__']
        action: replace
        replacement: ${1}
        regex: '([a-zA-Z0-9-\.]+):\d+'
        target_label: instance
      - action: labelmap
        regex: __meta_openstack_tag_(.+)
```

**Expected behavior**
Vmagent could not discovery targets, and write logs

**Logs**
`{"ts":"2021-09-27T05:26:16.119Z","level":"error","caller":"VictoriaMetrics/lib/promscrape/config.go:814","msg":"skipping openstack_sd_config targets for job_name \"openstack-node\" because of error: cannot get API config: both project_id and domain_name present"}
`

when clear project_id, write

`
skipping openstack_sd_config targets for job_name \"openstack-node\" because of error: cannot refresh OpenStack api token: cannot get computeEndpoint, account doesn't have enough permissions, availability: public, region: ******; error: cannot find compute url for the given availability: \"public\", region: \"******\""}
`

**Version**

`
Image:         victoriametrics/vmagent:v1.65.0
`

**Used command-line flags**
```
    Args:
      -promscrape.config=/config/scrape.yml
      -remoteWrite.tmpDataPath=/tmpData
      -remoteWrite.url=http://************:80/insert/0/prometheus/
      -envflag.enable=true
      -envflag.prefix=VM_
      -loggerFormat=json
      -promscrape.config=/etc/prometheus/prometheus.yml
      -promscrape.streamParse=true
      -remoteWrite.maxBlockSize=100MB
      -remoteWrite.maxDiskUsagePerURL=500MB
      -remoteWrite.sendTimeout=60s
 ```
