### ISSUE TITLE
vmagent consul_sd_configs : refresh_interval not found in type consul.SDConfig

### ISSUE THREAD

**Issue by adelbot** [VictoriaMetrics/VictoriaMetrics#1679]
**Describe the bug**
when i use consul_sd_configs with refresh_interval, the config yaml is refused.

**To Reproduce**
```
- job_name: consul-60s
  disable_keepalive: true
  #disable_compression: true
  honor_timestamps: true
  scrape_interval: 60s
  proxy_url: https://%{W2_-PROXY_URL}
  proxy_basic_auth:
    username: %{W2_-PROXY_USER}
    password: %{W2_-PROXY_PASSWORD}
  proxy_tls_config:
    ca_file: /etc/pki/ca-trust/extracted/pem/ca-bundle.crt
  consul_sd_configs:
  - server: consul-api:8500
    token: %{CONSUL_TOKEN}
    datacenter: %{CONSUL_DATACENTER}
    tag_separator: ','
    scheme: http
    allow_stale: true
    refresh_interval: 30s
    services:
      - %{CONSUL_PREFIX}-exporters-%{ITAAS_PARTNER}-%{ITAAS_CCX}
    tags:
      - 60s
      - prometheus
```

**Expected behavior**
Config consul available

**Logs**
{"ts":"2021-10-06T14:26:37.090+0200","level":"error","caller":"VictoriaMetrics/lib/promscrape/scraper.go:138","msg":"cannot read \"/config/vmagent-conf.yaml\": cannot parse Prometheus config from \"/config/vmagent-conf.yaml\": cannot load `scrape_config_files` from \"/config/vmagent-conf.yaml\": cannot parse \"/template.in/*.yaml\" from `scrape_config_files`: yaml: unmarshal errors:\n  line 19: field refresh_interval not found in type consul.SDConfig; continuing with the previous config"}

**Version**
1.66.2
```
