### ISSUE TITLE
Vmalert throws errors when reloading removed file from configmap

### ISSUE THREAD

**Issue by arramos84** [VictoriaMetrics/VictoriaMetrics#1708]
Vmalert throws errors when reloading removed file from configmap.

When `vmalert` uses a configmap of the form:

```
apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    app: vmalert
    component: vmalert-rules
  name: vmalert-rules
  namespace: tsdb
data:
  alerts1.yml: "rules1"
    ...
  alertsn.yml: "rulesn"
```

Then say there is an update to the configmap that is mounted to the `vmalert` pod. The update removes a file called `remove_alerts.yml`. The configmap reloader (sidecar to `vmalert` we run) then triggers the reload endpoint at `localhost:8482/-/reload"`.

We then see this error:

```
2021-10-14T22:22:57.954Z	error	VictoriaMetrics/app/vmalert/main.go:278	cannot parse configuration file: errors(1): failed to parse file "/etc/vmalert/rules/removed_alerts.yml": error reading alert rule file: open /etc/vmalert/rules/removed_alerts.yml: no such file or directory
```

and see `vmalert_config_last_reload_successful=0`

<img width="2457" alt="Screen Shot 2021-10-14 at 4 07 13 PM" src="https://user-images.githubusercontent.com/2239830/137407411-790e17a2-4939-4122-862c-b8a46f07cf9c.png">

Tried with `1.65.0` `1.66.1` and `1.67.0` over the last week. Seems to be intermittent. Maybe some stale caching?

Thanks!
