### ISSUE TITLE
VMagent can't connect to targets (Target list is empty)

### ISSUE THREAD

**Issue by mikomeister** [VictoriaMetrics/VictoriaMetrics#1722]
Hello all, im trying to install victoria-metrics-k8s-stack chart via ArgoCd, want to get data from node-exporter, but there is some issue, can't find any metrics, while investigation Im find that targets in VM agent are empty (or not displayed), im kind of new in VM, so how I can debug the issue to fins root cause?
screenshots with targets 
<img width="1644" alt="image" src="https://user-images.githubusercontent.com/32574241/137766967-f6d0344f-5534-43e2-9ee0-014868c46007.png">

log from vmagent

```

level=info ts=2021-10-18T15:25:33.149951221Z caller=main.go:147 msg="Starting prometheus-config-reloader" version="(version=0.48.1, branch=refs/tags/v0.48.1, revision=1e955299682630e4085adc2253f5689031eb0d0e)"
level=info ts=2021-10-18T15:25:33.150005368Z caller=main.go:148 build_context="(go=go1.16.4, user=paulfantom, date=20210601-15:27:27)"
level=error ts=2021-10-18T15:25:33.151053651Z caller=runutil.go:101 msg="function failed. Retrying in next tick" err="trigger reload: reload request failed: Post \"http://localhost:8429/-/reload\": dial tcp 127.0.0.1:8429: connect: connection refused"
level=info ts=2021-10-18T15:25:38.154484241Z caller=reloader.go:355 msg="Reload triggered" cfg_in=/etc/vmagent/config/vmagent.yaml.gz cfg_out=/etc/vmagent/config_out/vmagent.env.yaml watched_dirs=/etc/vm/relabeling
level=info ts=2021-10-18T15:25:38.154551729Z caller=reloader.go:219 msg="started watching config file and directories for changes" cfg=/etc/vmagent/config/vmagent.yaml.gz out=/etc/vmagent/config_out/vmagent.env.yaml dirs=/etc/vm/relabeling
level=info ts=2021-10-18T15:50:09.312600356Z caller=reloader.go:355 msg="Reload triggered" cfg_in=/etc/vmagent/config/vmagent.yaml.gz cfg_out=/etc/vmagent/config_out/vmagent.env.yaml watched_dirs=/etc/vm/relabeling
level=info ts=2021-10-18T15:53:09.409142294Z caller=reloader.go:355 msg="Reload triggered" cfg_in=/etc/vmagent/config/vmagent.yaml.gz cfg_out=/etc/vmagent/config_out/vmagent.env.yaml watched_dirs=/etc/vm/relabeling
```

VMServiceScrape custom resource code

```
apiVersion: operator.victoriametrics.com/v1beta1
kind: VMServiceScrape
metadata:
  name: victoria-metrics-victoria-metrics-k8s-stack-node-exporter
  namespace: victoria-metrics
spec:
  endpoints:
    - port: metrics
  jobLabel: jobLabel
  selector:
    matchLabels:
      app: prometheus-node-exporter
```

block for node-exporter from /etc/vmagent/config_out/vmagent.env.yaml
```
- job_name: victoria-metrics/victoria-metrics-victoria-metrics-k8s-stack-node-exporter/0
  honor_labels: false
  kubernetes_sd_configs:
  - role: endpoints
    namespaces:
      names:
      - victoria-metrics
  relabel_configs:
  - action: keep
    source_labels:
    - __meta_kubernetes_service_label_app
    regex: prometheus-node-exporter
  - action: keep
    source_labels:
    - __meta_kubernetes_endpoint_port_name
    regex: metrics
  - source_labels:
    - __meta_kubernetes_endpoint_address_target_kind
    - __meta_kubernetes_endpoint_address_target_name
    separator: ;
    regex: Node;(.*)
    replacement: ${1}
    target_label: node
  - source_labels:
    - __meta_kubernetes_endpoint_address_target_kind
    - __meta_kubernetes_endpoint_address_target_name
    separator: ;
    regex: Pod;(.*)
    replacement: ${1}
    target_label: pod
  - source_labels:
    - __meta_kubernetes_pod_name
    target_label: pod
  - source_labels:
    - __meta_kubernetes_namespace
    target_label: namespace
  - source_labels:
    - __meta_kubernetes_service_name
    target_label: service
  - source_labels:
    - __meta_kubernetes_service_name
    target_label: job
    replacement: ${1}
  - source_labels:
    - __meta_kubernetes_service_label_jobLabel
    target_label: job
    regex: (.+)
    replacement: ${1}
  - target_label: endpoint
    replacement: metrics
```

K8s service for node exporter
```apiVersion: v1
kind: Service
metadata:
  name: victoria-metrics-prometheus-node-exporter
  namespace: victoria-metrics
  labels:
    app: prometheus-node-exporter
    argocd.argoproj.io/instance: victoria-metrics
    chart: prometheus-node-exporter-2.1.0
    heritage: Helm
    jobLabel: node-exporter
    release: victoria-metrics
status:
  loadBalancer: {}
spec:
  ports:
    - name: metrics
      protocol: TCP
      port: 9100
      targetPort: 9100
  selector:
    app: prometheus-node-exporter
    release: victoria-metrics
  clusterIP: x.y.z
  clusterIPs:
    - x.y.z
  type: ClusterIP
  sessionAffinity: None
```
