### ISSUE TITLE
OOM killer after upgrading vmagent cluster from version v1.67.0 to v1.68.0

### ISSUE THREAD

**Issue by lucalandi** [VictoriaMetrics/VictoriaMetrics#1745]
# Issue
After upgrading vmagent cluster to version `v1.68.0` GKE started to kill vmagent cluster pods cause of high memory utilization.

Not sure yet if this is matching exactly #1728 

## Mitigation
We had to add the parameter `promscrape.noStaleMarkers` to make sure that vmagent instances are within the same resource limits as version `v1.67.0`

## Details

This section contains more details about the issue.

The cluster running in namespace `sre-victoriametrics-prod` has:

- `v1.68.0` `vmagent-20211022-171351-tags-v1.68.0-0-gf64f62692`
- flag `promscrape.noStaleMarkers` specified

The cluster running in namespace `sre-victoriametrics-poc` has:
- `v1.68.0` `vmagent-20211022-171351-tags-v1.68.0-0-gf64f62692`
- NO flag `promscrape.noStaleMarkers` specified

Both clusters are running in the same GKE cluster.

### Pre-upgrade status

```
kubectl -n sre-victoriametrics-prod top po --sort-by=memory
NAME                                  CPU(cores)   MEMORY(bytes)
vmcluster-vmstorage-2                 362m         3799Mi
vmcluster-vmstorage-3                 440m         3496Mi
vmcluster-vmstorage-1                 409m         3440Mi
vmcluster-vmstorage-4                 394m         3031Mi
vmcluster-vmstorage-0                 360m         2554Mi
vmcluster-vminsert-68c9947bb7-65j5h   898m         539Mi
vmcluster-vminsert-68c9947bb7-ppp5q   724m         455Mi
vmcluster-vminsert-68c9947bb7-t9tgt   507m         425Mi
vmagent-cluster-1                     1239m        378Mi
vmagent-cluster-2                     1123m        342Mi
vmagent-cluster-0                     1291m        317Mi
vmagent-cluster-3                     1171m        303Mi
vmcluster-vmselect-74b854f55d-4q8gx   20m          130Mi
vmcluster-vmselect-74b854f55d-n8kmd   2m           123Mi
vmcluster-vmselect-74b854f55d-brzgh   1m           121Mi
vmcluster-vmselect-74b854f55d-psn7p   3m           67Mi
```

vmagent-cluster stateful set:
```yaml
apiVersion: apps/v1
kind: StatefulSet
metadata:
  labels:
    app: vmagent-cluster
    app.kubernetes.io/name: victoria-metrics-cluster
    app.kubernetes.io/instance: victoria-metrics
  name: vmagent-cluster
  namespace: sre-victoriametrics-prod
spec:
  serviceName: vmagent
  selector:
    matchLabels:
      app: vmagent-cluster
      app.kubernetes.io/name: victoria-metrics-cluster
      app.kubernetes.io/instance: victoria-metrics
  replicas: 4 # the numbers of replicas has to match the promscrape.cluster.membersCount parameter
  podManagementPolicy: OrderedReady
  template:
    metadata:
      annotations:
        sidecar.istio.io/inject: "false"
        prometheus.io/port: "8429"
        prometheus.io/scrape: "true"
      labels:
        app: vmagent-cluster
        app.kubernetes.io/name: victoria-metrics-cluster
        app.kubernetes.io/instance: victoria-metrics
    spec:
      automountServiceAccountToken: true
      initContainers:
        - name: init
          image: busybox:latest
          command:
            - /bin/sh
            - -c
            - |-
              set -ex;
              echo HOSTNAME=${HOSTNAME}
              export MEMBER=${HOSTNAME##*-}
              echo PROMSCRAPE_CLUSTER_MEMBER_NUM=${MEMBER} > /vmagentData/memberID
              cat /vmagentData/memberID
              ls -latrh /vmagentData
          env:
            - name: HOSTNAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
          volumeMounts:
            - name: vmagent-volume
              mountPath: /vmagentData
      containers:
        - name: victoria-metrics-agent
          image: "victoriametrics/vmagent:v1.67.0"
          workingDir: /
          command:
            - /bin/sh
            - -c
            - |-
              set -ex
              ls -latrh /
              ls -latrh /vmagentData
              cat /vmagentData/memberID
              source /vmagentData/memberID
              echo ${PROMSCRAPE_CLUSTER_MEMBER_NUM}
              ./vmagent-prod \
                -promscrape.config=/config/scrape.yml \
                -promscrape.maxDroppedTargets=3000 \
                -promscrape.maxScrapeSize=90000000 \
                -promscrape.streamParse \
                -promscrape.cluster.replicationFactor=2 \
                -promscrape.cluster.membersCount=4 \
                -promscrape.cluster.memberNum=${PROMSCRAPE_CLUSTER_MEMBER_NUM} \
                -remoteWrite.tmpDataPath=/vmagentData \
                -remoteWrite.url=http://vminsert.sre-victoriametrics-prod.svc.cluster.local:8480/insert/0/prometheus/ \
                -remoteWrite.queues=20 \
                -envflag.enable=true \
                -envflag.prefix=VM_ \
                -loggerFormat=json      
          imagePullPolicy: IfNotPresent
          ports:
            - name: http
              containerPort: 8429
          readinessProbe:
            httpGet:
              path: /health
              port: http
            initialDelaySeconds: 5
            periodSeconds: 15
          livenessProbe:
            tcpSocket:
              port: http
            initialDelaySeconds: 5
            periodSeconds: 15
            timeoutSeconds: 5
          volumeMounts:
            - name: vmagent-volume
              mountPath: /vmagentData
            - name: config
              mountPath: /config
          resources:
            limits:
              cpu: 5
              memory: 3Gi
            requests:
              cpu: 2
              memory: 500Mi
      serviceAccountName: vmagent
      terminationGracePeriodSeconds: 10
      volumes:
        - name: config
          configMap:
            name: vmagent-config
  volumeClaimTemplates:
    - metadata:
        name: vmagent-volume
      spec:
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: "50Gi"

```

### Post-upgrade status

Going to provide here the status of a different cluster since I could not maintain in prod the configuration without parameter `promscrape.noStaleMarkers`.

CPU and memory usage went up a lot. Check the details below for the new limits I gave:

```
kubectl -n sre-victoriametrics-poc top po --sort-by=memory
NAME                                  CPU(cores)   MEMORY(bytes)
vmagent-cluster-0                     4827m        8743Mi
vmagent-cluster-1                     4747m        8033Mi
vmagent-cluster-3                     4657m        6707Mi
vmagent-cluster-2                     2788m        2978Mi
vmcluster-vmstorage-4                 437m         1752Mi
vmcluster-vmstorage-0                 423m         1731Mi
vmcluster-vmstorage-2                 384m         1654Mi
vmcluster-vmstorage-3                 325m         1550Mi
vmcluster-vmstorage-1                 336m         1533Mi
vmcluster-vminsert-67c7445d85-tz457   814m         486Mi
vmcluster-vminsert-67c7445d85-wnmfs   1106m        457Mi
vmcluster-vminsert-67c7445d85-2pg5g   301m         282Mi
vmcluster-vmselect-594d4f8dfd-gr54d   1m           39Mi
vmcluster-vmselect-594d4f8dfd-8nhlk   1m           33Mi
```

```yaml
apiVersion: apps/v1
kind: StatefulSet
metadata:
  labels:
    app: vmagent-cluster
    app.kubernetes.io/name: victoria-metrics-cluster
    app.kubernetes.io/instance: victoria-metrics
  name: vmagent-cluster
  namespace: sre-victoriametrics-poc
spec:
  serviceName: vmagent
  selector:
    matchLabels:
      app: vmagent-cluster
      app.kubernetes.io/name: victoria-metrics-cluster
      app.kubernetes.io/instance: victoria-metrics
  replicas: 4 # the numbers of replicas has to match the promscrape.cluster.membersCount parameter
  podManagementPolicy: OrderedReady
  template:
    metadata:
      annotations:
        sidecar.istio.io/inject: "false"
        prometheus.io/port: "8429"
        prometheus.io/scrape: "true"
      labels:
        app: vmagent-cluster
        app.kubernetes.io/name: victoria-metrics-cluster
        app.kubernetes.io/instance: victoria-metrics
    spec:
      automountServiceAccountToken: true
      initContainers:
        - name: init
          image: busybox:latest
          command:
            - /bin/sh
            - -c
            - |-
              set -ex;
              echo HOSTNAME=${HOSTNAME}
              export MEMBER=${HOSTNAME##*-}
              echo PROMSCRAPE_CLUSTER_MEMBER_NUM=${MEMBER} > /vmagentData/memberID
              cat /vmagentData/memberID
              ls -latrh /vmagentData
          env:
            - name: HOSTNAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
          volumeMounts:
            - name: vmagent-volume
              mountPath: /vmagentData
      containers:
        - name: victoria-metrics-agent
          image: "victoriametrics/vmagent:v1.68.0"
          workingDir: /
          command:
            - /bin/sh
            - -c
            - |-
              set -ex
              ls -latrh /
              ls -latrh /vmagentData
              cat /vmagentData/memberID
              source /vmagentData/memberID
              echo ${PROMSCRAPE_CLUSTER_MEMBER_NUM}
              ./vmagent-prod \
                -promscrape.config=/config/scrape.yml \
                -promscrape.maxDroppedTargets=100 \
                -promscrape.maxScrapeSize=90000000 \
                -promscrape.streamParse \
                -promscrape.cluster.replicationFactor=2 \
                -promscrape.cluster.membersCount=4 \
                -promscrape.cluster.memberNum=${PROMSCRAPE_CLUSTER_MEMBER_NUM} \
                -remoteWrite.tmpDataPath=/vmagentData \
                -remoteWrite.url=http://vminsert.sre-victoriametrics-poc.svc.cluster.local:8480/insert/0/prometheus/ \
                -remoteWrite.queues=20 \
                -envflag.enable=true \
                -envflag.prefix=VM_ \
                -loggerFormat=json      
          imagePullPolicy: IfNotPresent
          ports:
            - name: http
              containerPort: 8429
          readinessProbe:
            httpGet:
              path: /health
              port: http
            initialDelaySeconds: 5
            periodSeconds: 15
          livenessProbe:
            tcpSocket:
              port: http
            initialDelaySeconds: 5
            periodSeconds: 15
            timeoutSeconds: 5
          volumeMounts:
            - name: vmagent-volume
              mountPath: /vmagentData
            - name: config
              mountPath: /config
          resources:
            limits:
              cpu: 5
              memory: 20Gi
            requests:
              cpu: 2
              memory: 500Mi
      serviceAccountName: vmagent
      terminationGracePeriodSeconds: 10
      volumes:
        - name: config
          configMap:
            name: vmagent-config
  volumeClaimTemplates:
    - metadata:
        name: vmagent-volume
      spec:
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: "50Gi"
```
It's currently stable but it's evident that there was a big jump in CPU/Memory usage. I left this cluster running without `promscrape.noStaleMarkers` on purpose.

### Current PROD

```yaml
apiVersion: apps/v1
kind: StatefulSet
metadata:
  labels:
    app: vmagent-cluster
    app.kubernetes.io/name: victoria-metrics-cluster
    app.kubernetes.io/instance: victoria-metrics
  name: vmagent-cluster
  namespace: sre-victoriametrics-prod
spec:
  serviceName: vmagent
  selector:
    matchLabels:
      app: vmagent-cluster
      app.kubernetes.io/name: victoria-metrics-cluster
      app.kubernetes.io/instance: victoria-metrics
  replicas: 4 # the numbers of replicas has to match the promscrape.cluster.membersCount parameter
  podManagementPolicy: OrderedReady
  template:
    metadata:
      annotations:
        sidecar.istio.io/inject: "false"
        prometheus.io/port: "8429"
        prometheus.io/scrape: "true"
      labels:
        app: vmagent-cluster
        app.kubernetes.io/name: victoria-metrics-cluster
        app.kubernetes.io/instance: victoria-metrics
    spec:
      automountServiceAccountToken: true
      initContainers:
        - name: init
          image: busybox:latest
          command:
            - /bin/sh
            - -c
            - |-
              set -ex;
              echo HOSTNAME=${HOSTNAME}
              export MEMBER=${HOSTNAME##*-}
              echo PROMSCRAPE_CLUSTER_MEMBER_NUM=${MEMBER} > /vmagentData/memberID
              cat /vmagentData/memberID
              ls -latrh /vmagentData
          env:
            - name: HOSTNAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
          volumeMounts:
            - name: vmagent-volume
              mountPath: /vmagentData
      containers:
        - name: victoria-metrics-agent
          image: "victoriametrics/vmagent:v1.68.0"
          workingDir: /
          command:
            - /bin/sh
            - -c
            - |-
              set -ex
              ls -latrh /
              ls -latrh /vmagentData
              cat /vmagentData/memberID
              source /vmagentData/memberID
              echo ${PROMSCRAPE_CLUSTER_MEMBER_NUM}
              ./vmagent-prod \
                -promscrape.config=/config/scrape.yml \
                -promscrape.maxDroppedTargets=3000 \
                -promscrape.maxScrapeSize=90000000 \
                -promscrape.streamParse \
                -promscrape.noStaleMarkers \
                -promscrape.cluster.replicationFactor=2 \
                -promscrape.cluster.membersCount=4 \
                -promscrape.cluster.memberNum=${PROMSCRAPE_CLUSTER_MEMBER_NUM} \
                -remoteWrite.tmpDataPath=/vmagentData \
                -remoteWrite.url=http://vminsert.sre-victoriametrics-prod.svc.cluster.local:8480/insert/0/prometheus/ \
                -remoteWrite.queues=20 \
                -envflag.enable=true \
                -envflag.prefix=VM_ \
                -loggerFormat=json      
          imagePullPolicy: IfNotPresent
          ports:
            - name: http
              containerPort: 8429
          readinessProbe:
            httpGet:
              path: /health
              port: http
            initialDelaySeconds: 5
            periodSeconds: 15
          livenessProbe:
            tcpSocket:
              port: http
            initialDelaySeconds: 5
            periodSeconds: 15
            timeoutSeconds: 5
          volumeMounts:
            - name: vmagent-volume
              mountPath: /vmagentData
            - name: config
              mountPath: /config
          resources:
            limits:
              cpu: 5
              memory: 7Gi
            requests:
              cpu: 2
              memory: 500Mi
      serviceAccountName: vmagent
      terminationGracePeriodSeconds: 10
      volumes:
        - name: config
          configMap:
            name: vmagent-config
  volumeClaimTemplates:
    - metadata:
        name: vmagent-volume
      spec:
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: "50Gi"
```

### Profiling

I have attached a single tar.gz file containing multiple profiles: `25_10_2021_upgrade_vmagent_issue.tar.gz`.
[25_10_2021_upgrade_vmagent_issue.tar.gz](https://github.com/VictoriaMetrics/VictoriaMetrics/files/7412611/25_10_2021_upgrade_vmagent_issue.tar.gz)

#### `sre-victoriametrics-poc`

This is the cluster running `v1.68.0` and no `promscrape.noStaleMarkers` flag.

Ran profiles for 60 seconds and obtained heap for 2 instances in the cluster with high memory utilization:
```
-rw-r--r--@ 1 llandi  staff   108K 25 Oct 13:23 vmpoc-vmagent-cluster-0_heap
-rw-r--r--@ 1 llandi  staff   142K 25 Oct 13:22 vmpoc-vmagent-cluster-0_profile
-rw-r--r--@ 1 llandi  staff   106K 25 Oct 13:24 vmpoc-vmagent-cluster-1_heap
-rw-r--r--@ 1 llandi  staff   141K 25 Oct 13:26 vmpoc-vmagent-cluster-1_profile
```

#### `sre-victoriametrics-prod`

This is the cluster running `v1.68.0` and flag `promscrape.noStaleMarkers`.

Ran profiles for 60 seconds and obtained heap for 2 instances:
```
-rw-r--r--@ 1 llandi  staff    64K 25 Oct 13:29 vmprod-vmagent-cluster-0_heap
-rw-r--r--@ 1 llandi  staff    81K 25 Oct 13:29 vmprod-vmagent-cluster-0_profile
-rw-r--r--@ 1 llandi  staff    67K 25 Oct 13:34 vmprod-vmagent-cluster-1_heap
-rw-r--r--@ 1 llandi  staff    80K 25 Oct 13:33 vmprod-vmagent-cluster-1_profile
```

**Comment by wu0407** [comment]
```
spec:
  containers:
  - args:
    - --reload-url=http://localhost:8429/-/reload
    - --config-envsubst-file=/etc/vmagent/config_out/vmagent.env.yaml
    - --watched-dir=/etc/vm/relabeling
    - --config-secret-name=victoria/vmagent-victoria-metrics-k8s-stack
    - --config-secret-key=vmagent.yaml.gz
    command:
    - /usr/local/bin/config-reloader
    env:
    - name: POD_NAME
      valueFrom:
        fieldRef:
          apiVersion: v1
          fieldPath: metadata.name
    image: victoriametrics/operator:config-reloader-0.1.0
    imagePullPolicy: IfNotPresent
    name: config-reloader
    resources:
      limits:
        cpu: 100m
        ephemeral-storage: 7Gi
        memory: 25Mi
      requests:
        cpu: 100m
        ephemeral-storage: 256Mi
        memory: 25Mi
    terminationMessagePath: /dev/termination-log
    terminationMessagePolicy: FallbackToLogsOnError
    volumeMounts:
    - mountPath: /etc/vmagent/config
      name: config
    - mountPath: /etc/vmagent/config_out
      name: config-out
    - mountPath: /etc/vm/relabeling
      name: relabeling-assets
      readOnly: true
    - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
      name: vmagent-victoria-metrics-k8s-stack-token-zz7wp
      readOnly: true
  - args:
    - -httpListenAddr=:8429
    - -promscrape.config=/etc/vmagent/config_out/vmagent.env.yaml
    - -promscrape.maxScrapeSize=64MB
    - -promscrape.streamParse=true
    - -promscrape.suppressDuplicateScrapeTargetErrors=true
    - -remoteWrite.maxDiskUsagePerURL=1073741824
    - -remoteWrite.tmpDataPath=/tmp/vmagent-remotewrite-data
    - -remoteWrite.url=http://vm-cluster-victoria-metrics-cluster-vminsert.vm-cluster.svc:8480/insert/0/prometheus/api/v1/write,http://vminsert-victoria-metrics-k8s-stack.victoria.svc:8480/insert/0/prometheus/api/v1/write
    image: victoriametrics/vmagent:v1.67.0
    imagePullPolicy: IfNotPresent
    livenessProbe:
      failureThreshold: 10
      httpGet:
        path: /health
        port: 8429
        scheme: HTTP
      periodSeconds: 5
      successThreshold: 1
      timeoutSeconds: 5
    name: vmagent
    ports:
    - containerPort: 8429
      name: http
      protocol: TCP
    readinessProbe:
      failureThreshold: 10
      httpGet:
        path: /health
        port: 8429
        scheme: HTTP
      periodSeconds: 5
      successThreshold: 1
      timeoutSeconds: 5
    resources:
      limits:
        cpu: "2"
        ephemeral-storage: 7Gi
        memory: 1Gi
      requests:
        cpu: 50m
        ephemeral-storage: 256Mi
        memory: 200Mi
    terminationMessagePath: /dev/termination-log
    terminationMessagePolicy: FallbackToLogsOnError
    volumeMounts:
    - mountPath: /tmp/vmagent-remotewrite-data
      name: persistent-queue-data
    - mountPath: /etc/vmagent/config_out
      name: config-out
      readOnly: true
    - mountPath: /etc/vmagent-tls/certs
      name: tls-assets
      readOnly: true
    - mountPath: /etc/vm/relabeling
      name: relabeling-assets
      readOnly: true
    - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
      name: vmagent-victoria-metrics-k8s-stack-token-zz7wp
      readOnly: true
  dnsPolicy: ClusterFirst
  enableServiceLinks: true
  nodeName: 10.12.97.25
  priority: 0
  restartPolicy: Always
  schedulerName: default-scheduler
  securityContext: {}
  serviceAccount: vmagent-victoria-metrics-k8s-stack
  serviceAccountName: vmagent-victoria-metrics-k8s-stack
  terminationGracePeriodSeconds: 30
  tolerations:
  - effect: NoExecute
    key: node.kubernetes.io/not-ready
    operator: Exists
    tolerationSeconds: 120
  - effect: NoExecute
    key: node.kubernetes.io/unreachable
    operator: Exists
    tolerationSeconds: 120
  volumes:
  - emptyDir: {}
    name: persistent-queue-data
  - name: config
    secret:
      defaultMode: 420
      secretName: vmagent-victoria-metrics-k8s-stack
  - name: tls-assets
    secret:
      defaultMode: 420
      secretName: tls-assets-vmagent-victoria-metrics-k8s-stack
  - emptyDir: {}
    name: config-out
  - configMap:
      defaultMode: 420
      name: relabelings-assets-vmagent-victoria-metrics-k8s-stack
    name: relabeling-assets
  - name: vmagent-victoria-metrics-k8s-stack-token-zz7wp
    secret:
      defaultMode: 420
      secretName: vmagent-victoria-metrics-k8s-stack-token-zz7wp
```

1.67.0 cpu and memory:
![vmagent-resource-ues-1 67 0-cpu](https://user-images.githubusercontent.com/7602218/139634183-f0a2ef6f-292a-4cab-9c3c-d704f1e83ae9.png)
![vmagent-resource-ues-1 67 0-memory](https://user-images.githubusercontent.com/7602218/139634187-ca26a4a0-a5e4-4a8b-a72f-32d7cb4b45a9.png)

1.68.0  cpu and memory:
![vmagent-resource-ues-memory-1 68 0](https://user-images.githubusercontent.com/7602218/139634214-1dcb1176-c5e4-400c-a497-c3d7c56c0332.png)
![vmagent-resource-ues-cpu-1 68 0](https://user-images.githubusercontent.com/7602218/139634219-b19faf2b-7041-4a30-b7ee-4aa1db522e5d.png)
