### ISSUE TITLE
vmauth fail to open vmui

### ISSUE THREAD

**Issue by v98765** [VictoriaMetrics/VictoriaMetrics#1752]
**Describe the bug**
vmauth generate wrong url to single-node VM. vmauth-host:8427/vmui/vmui/ and got `404 page not found`

**To Reproduce**
click on vmui url. http code:

`See docs at <a href='https://docs.victoriametrics.com/'>https://docs.victoriametrics.com/</a></br>Useful endpoints:</br><a href="/vmui">/vmui</a> - Web UI<br/><a href="/targets">/targets</a> - discovered targets list<br/><a href="/api/v1/targets">/api/v1/targets</a> - advanced information about discovered targets in JSON format<br/><a href="/config">/config</a> - -promscrape.config contents<br/><a href="/metrics">/metrics</a> - available service metrics<br/><a href="/flags">/flags</a> - command-line flags<br/><a href="/api/v1/status/tsdb">/api/v1/status/tsdb</a> - tsdb status page<br/><a href="/api/v1/status/top_queries">/api/v1/status/top_queries</a> - top queries<br/><a href="/api/v1/status/active_queries">/api/v1/status/active_queries</a> - active queries<br/>`

**Expected behavior**
vmui works with vmauth

**Version**
```
vmauth-20211022-171212-tags-v1.68.0-0-gf64f62692
victoria-metrics-20211022-171155-tags-v1.68.0-0-gf64f62692
```

**Comment by hy-ntyni** [comment]
I'm seeing this with a trivial vmauth config.

```
users:
- {bearer_token: foobar, url_prefix: 'http://victoriametrics:8428'}
```
All requests to /vmui/ via vmauth return HTTP 301 with Location: vmui/ .

Sniffing the requests, it looks like vmauth strips the trailing slash from the path unconditionally but vmui insists on seeing it.

I tried backing up to v1.64.0 to see if this broke with 48f33d098b91a65fe406dc74f7b332afdf39a204 but that did not change the situation for me. But I suppose the path.Clean() call earlier (https://github.com/VictoriaMetrics/VictoriaMetrics/blob/master/app/vmauth/target_url.go#L41 ) already trims the slash.

Not sure if it's more easily fixed on the vmui side.

**Comment by hy-ntyni** [comment]
> I'm seeing this with a trivial vmauth config.

> All requests to /vmui/ via vmauth return HTTP 301 with Location: vmui/ .
 
> Sniffing the requests, it looks like vmauth strips the trailing slash from the path unconditionally but vmui insists on seeing it.

Hi, I think at least the 'need more info' tag could be removed from this issue. It should be trivial to reproduce.

Hope somebody finds the time to look at this :)

**Comment by wenerme** [comment]
any workaround ? deployed by operator the generated config like

```yaml
- url_map:
  - url_prefix: http://vmselect-demo.monitoring-system.svc:8481/select/50
    src_paths:
    - /vmui
    - /vmui/vmui
    - /graph
    - /prometheus/graph
    - /prometheus/api/v1/label.*
    - /graphite.*
    - /prometheus/api/v1/query.*
    - /prometheus/api/v1/rules
    - /prometheus/api/v1/alerts
    - /prometheus/api/v1/metadata
    - /prometheus/api/v1/rules
    - /prometheus/api/v1/series.*
    - /prometheus/api/v1/status.*
    - /prometheus/api/v1/export.*
    - /prometheus/federate
    - /prometheus/api/v1/admin/tsdb/delete_series
```

but visit /vmui/ will redirect to vmui/ cause the final path is `/vmui/vmui/`
