### ISSUE TITLE
proxy_url not working

### ISSUE THREAD

**Issue by pollynesterovich** [VictoriaMetrics/VictoriaMetrics#1755]
When adding proxy_url to additionalScrapeConfigs metrics are not collected and are not displayed in https://vmagent/config.
Installed victoria-metrics-k8s-stack with vmagent v1.68.0. 
Please tell me what could be the problem?
```
- job_name:controller-manager/0
  honor_timestamps: true
  params:
    _scheme:
    - https
  metrics_path: /metrics
  scheme: http
  kubernetes_sd_configs:
  - role: endpoints
    namespaces:
      names:
      - vm
  proxy_url: http://pushprox-kube-controller-manager-proxy.vm.svc.cluster.local:8080
```
