### ISSUE TITLE
Make more secure location  vmagent/config 

### ISSUE THREAD

**Issue by nevlkv** [VictoriaMetrics/VictoriaMetrics#1764]
In new 1.68.0 location `/config`  show config. If config contain section `openstack_sd_configs` and etc, passwords show in plain format

prometheus show is more secure

```
 openstack_sd_configs:
  - identity_endpoint: https://iam.ХХХХХХХ/v3
    username: prometheus
    userid: ""
    password: <secret>
```

Please make more secure !!!
