### ISSUE TITLE
scrape_config_files: ignore entries with key'#', better error reporting

### ISSUE THREAD

**Issue by jelmd** [VictoriaMetrics/VictoriaMetrics#1789]
In the main json config file given via `--promscrape.config` entries with the key `'#'` get silently ignored (hurray :1st_place_medal: ). However, if on splits its static configs into separate config files, vmagent dies with ` cannot parse ... from 'scrape_config_files': yaml: unmarshal errors ...`

**To Reproduce**
- /tmp/promscrape.json
```
{
    "global": {
        "scrape_interval": "15s",
        "external_labels": { "gz": "qetesh" }
    },
    "#": "this entry/comment gets ignored",
    "scrape_config_files": [ "scrape.d/*.json" ]
}
```
- /tmp/scrape.d/self.json
```
[{
    "job_name": "vmagent",
    "#": "this entry/comment lets vmagent explode",
    "scrape_interval": "10s",
    "scrape_timeout": "25s",
    "static_configs": [{ "targets": [ "localhost:8429" ] }],
    "metric_relabel_configs": [{
        "action": "drop",
        "source_labels": [ "__name__" ],
        "regex": "vm_log_messages_total|flag"
    },{
        "regex": "instance", "action": "labeldrop"
    }]
}]
```
vmagent --promscrape.config=/tmp/promscrape.json ...

**Expected behavior**
vmagent should ignore '#' in scrape_configs included via file as well. Also error messages could be enhanced to be able to determine much easier, which included file[s] caused the error.

**Logs**
```
2021-11-06T03:10:04.671Z	info	VictoriaMetrics/app/vmagent/main.go:117	started vmagent in 0.003 seconds
2021-11-06T03:10:04.671Z	info	VictoriaMetrics/lib/promscrape/scraper.go:101	reading Prometheus configs from "/data/vmagent/promscrape.json"
2021-11-06T03:10:04.671Z	info	VictoriaMetrics/lib/httpserver/httpserver.go:83	starting http server at http://127.0.0.1:8429/
2021-11-06T03:10:04.672Z	info	VictoriaMetrics/lib/httpserver/httpserver.go:84	pprof handlers are exposed at http://127.0.0.1:8429/debug/pprof/
2021-11-06T03:10:04.673Z	fatal	VictoriaMetrics/lib/promscrape/scraper.go:104	cannot read "/data/vmagent/promscrape.json": cannot parse Prometheus config from "/data/vmagent/promscrape.json": cannot load `scrape_config_files` from "/data/vmagent/promscrape.json": cannot parse "/data/vmagent/scrape.d/*.json" from `scrape_config_files`: yaml: unmarshal errors:
  line 6: field # not found in type promscrape.ScrapeConfig
  line 7: field # not found in type promscrape.ScrapeConfig
```
After this vmagent dies (NOTE: this log comes from a real setup, not from the example above, which is a slightly simplified stripped down version).

**Version**
1.68.0

**Comment by valyala** [comment]
[Single-node VictoriaMetrics](https://docs.victoriametrics.com/#how-to-scrape-prometheus-exporters-such-as-node-exporter) and [vmagent](https://docs.victoriametrics.com/vmagent.html) don't allow unsupported fields in files pointed by `scrape_config_files`. This is needed in order to reduce the probability of silent configuration error or typo. However, such unsupported fields are allowed by default in the file pointed by `-promscrape.config`. This allows passing Prometheus config files without any modifications to `-promscrape.config` - `vmagent` just ignores unsupported fields in the file by default. This behavior can be changed by passing `-promscrape.config.strictParse` command-line flag to `vmagent`.

I'd suggest using the following workaround for your case: to use plain comment lines which start with `#`:
```yml
[{
    "job_name": "vmagent",
    # this entry/comment doesn't let vmagent to explode
    "scrape_interval": "10s",
    "scrape_timeout": "25s",
    "static_configs": [{ "targets": [ "localhost:8429" ] }],
    "metric_relabel_configs": [{
        "action": "drop",
        "source_labels": [ "__name__" ],
        "regex": "vm_log_messages_total|flag"
    },{
        "regex": "instance", "action": "labeldrop"
    }]
}]
```

This works without issues, since both `-promscrape.config` and `scrape_config_files` are parsed as YAML instead of JSON, and YAML allows using plain comments that start with `#`. It is OK to pass a yaml which looks like a json, since yaml is a superset of json.

The error message logging has been improved in the commit fd596945e7332f3d0927ad0cbae78a85fa89a2ec .
