### ISSUE TITLE
vmauth_user_requests_total metric improves

### ISSUE THREAD

**Issue by zensu** [VictoriaMetrics/VictoriaMetrics#1805]
**Describe the bug**

When using bearer_token in vmauth, the metric vmauth_user_requests_total does not identify the user (label username). 
I have multiple bearer_tokens in vmauth config and they are summed up in the metric. As result metric looks like this
`vmauth_user_requests_total{username="bearer_token"} 251`

**To Reproduce**

My vmauth config:
```
users:
- bearer_token: "token_0"
  url_prefix: "http://vmselect:8481"
- bearer_token: "token_1"
  url_prefix: "http://vmselect:8481/select/1/prometheus"
```

**Expected behavior**

I think it would be good If you add some identify field for vmauth config with bearer_token. For example:
```
users:
- name: "user_0" 
  bearer_token: "token_0"
  url_prefix: "http://vmselect:8481"
```
And I will see metrics something like this:
`vmauth_user_requests_total{username="user_0"} 35`
`vmauth_user_requests_total{username="user_1"} 100`

**Version**

vmauth-20210923-200501-tags-v1.66.2-0-g9f1964967
