### ISSUE TITLE
Vm scrapping k8s  kubernetes_sd_config, time to time data missing

### ISSUE THREAD

**Issue by renchili** [VictoriaMetrics/VictoriaMetrics#1807]
**Describe the bug**
![image](https://user-images.githubusercontent.com/33677006/141251918-f143c5e4-17e4-4354-84b3-1f80431ec5cc.png)
![image](https://user-images.githubusercontent.com/33677006/141251706-65cd63a9-c6da-44b8-a8b3-acbbf0d8f066.png)

for targets under  kubernetes_sd_configs.
The user reported that data missing from time to time.
And we set up 2 independent clusters that are missing data at different times.
![image](https://user-images.githubusercontent.com/33677006/141252682-2330a05b-3290-4802-a1b7-5d3374951f60.png)
When losing data there is no target unreachable or marked as `down`
**To Reproduce**
configuration is
```
- job_name: kube-state
  honor_timestamps: true
  scrape_interval: 1m
  scrape_timeout: 10s
  metrics_path: /metrics
  scheme: HTTP
  kubernetes_sd_configs:
  - api_server: https://xxxxxxxxxxxxxxxxxxxxxx.xxxxxxx.us-west-2.eks.amazonaws.com
    role: endpoints
    bearer_token_file: /config/eks-center
    tls_config:
      insecure_skip_verify: true
    namespaces:
      names:
      - xxxxxxxxx
```
**Expected behaviour**
No data losing

**Logs**
no log related to this issue

**Version**
vmagent:
vmagent-20211008-135241-tags-v1.67.0-0-g6058edb0d
vmstorage:
vmstorage-20211008-140613-tags-v1.67.0-cluster-0-g20fa4b01c
vmselect:
vmselect-20211008-140608-tags-v1.67.0-cluster-0-g20fa4b01c
vminsert:
vminsert-20211008-140602-tags-v1.67.0-cluster-0-g20fa4b01c

**Used command-line flags**
vmagent:
```
-promscrape.config=prometheus.yml -remoteWrite.url=xxxxx -http.connTimeout=1000ms -promscrape.maxScrapeSize=250MB -promscrape.suppressDuplicateScrapeTargetErrors -promscrape.cluster.membersCount=9 -promscrape.cluster.memberNum=0 -promscrape.streamParse=true -promscrape.consulSDCheckInterval=60s -remoteWrite.queues=10  -promscrape.cluster.replicationFactor=2
```
vmselect:
```
-dedup.minScrapeInterval=13s -search.logSlowQueryDuration=15s -search.maxQueryDuration=50s -cacheDataPath=/logs -search.maxQueryLen=1MB -storageNode=...... 
```
vminsert:
```
-replicationFactor=2 -maxLabelsPerTimeseries=50 -storageNode=....
```
vmstorage：
```
-search.maxUniqueTimeseries=2000000  -storageDataPath=/lingtian/opt/vmstorage-data -retentionPeriod=1y -bigMergeConcurrency=1
```
