### ISSUE TITLE
All Recording rules having periodic gap without any datapoints 

### ISSUE THREAD

**Issue by tbuchier** [VictoriaMetrics/VictoriaMetrics#1812]
Hello, 

We found out that in one of our environment, all the recording rules present periodic gap without any datapoint.

Setup:
VM Operator v0.19.1
VM Cluster + Alert v1.67.0

Example:
![image](https://user-images.githubusercontent.com/16001560/141605399-e7b00702-ebe3-437e-859b-872cc3aaa9da.png)

![image](https://user-images.githubusercontent.com/16001560/141604205-ee6257eb-acb9-4b4a-a513-48da17a6b114.png)

But if I graph the original query specified in the recording rule, it has data:
![image](https://user-images.githubusercontent.com/16001560/141604214-fbba0699-c0b1-4550-bb58-e0e1b7982973.png)

This affect ALL recording rules and only happen in one environment.

Can't find any logs saying that rules failed to be calculated or anything.
The only logs of VMAlert are recording group being started 
```
2021-11-12T09:37:42.350Z	info	VictoriaMetrics/app/vmalert/group.go:244	group "XXX" started; interval=15s; concurrency=1
...
```

VMAlert CR spec:

```
apiVersion: operator.victoriametrics.com/v1beta1
kind: VMAlert
metadata:
  annotations:
    meta.helm.sh/release-name: vm-alert
    meta.helm.sh/release-namespace: victoria-metrics
    operator.victoriametrics.com/vmalert-deduplicate-rules: "true"
  finalizers:
  - apps.victoriametrics.com/finalizer
  labels:
    app.kubernetes.io/instance: vm-alert
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: vm-alert
    app.kubernetes.io/version: 0.1.0
    helm.sh/chart: vm-alert-0.1.0
  name: vm-alert
  namespace: victoria-metrics
spec:
  datasource:
    url: http://vmselect-vm-cluster.victoria-metrics.svc.cluster.local:8481/select/0/prometheus/
  evaluationInterval: 15s
  image:
    repository: docker.io/victoriametrics/vmalert
    tag: v1.67.0
  notifier:
    url: http://alertmanager-operated.monitoring.svc.cluster.local:9093
  remoteWrite:
    url: http://vminsert-vm-cluster.victoria-metrics.svc.cluster.local:8480/insert/0/prometheus
  replicaCount: 1
  resources: {}
  ruleNamespaceSelector: {}
  ruleSelector:
    matchLabels:
      app: kube-victoria-metrics-stack
      release: vmstack
  tolerations:
  - operator: Exists
```

VMAlert doesn't feel too busy as resource usage seems quite low

![image](https://user-images.githubusercontent.com/16001560/141605182-6f00966c-7bf5-4be6-96b8-9b517f20ebfe.png)

VMCluster seems quite fine too

![image](https://user-images.githubusercontent.com/16001560/141605231-2d03d8ee-d79b-44c3-83b0-7a87bf52fe4d.png)

Any ideas ?
Thanks

**Comment by YuriKravetc** [comment]
Hello,
Can you also attach the graphs from the Troubleshooting part, please?

**Comment by tbuchier** [comment]
Hello, here it is:

![image](https://user-images.githubusercontent.com/16001560/141880199-f7b9bf2f-e91a-4d03-b08e-9b29175216da.png)

**Comment by goodqinjin** [comment]
ping

**Comment by f41gh7** [comment]
Hi, can you share some additional information
1) vmselect configuration. Were default flag values changed?
2) visualize vmalert's metric for given group - vmalert_alerting_rules_last_evaluation_samples. It must provide information about samples, returned by query request.

 In case of too low value for vmselect's flag `search.latencyOffset`, lets say 5s (default value is 30s), it's possible to get empty result for `/query` api requests.

**Comment by tbuchier** [comment]
Hi,

1. Nothing special changed, we use a vmcluster CR here is the vmselect key:
```
  vmselect:
    cacheMountPath: /select-cache
    image:
      repository: docker.io/victoriametrics/vmselect
      tag: v1.67.0-cluster
    podDisruptionBudget:
      maxUnavailable: 1
    replicaCount: 2
    resources:
      limits:
        cpu: "4"
        memory: 8Gi
      requests:
        cpu: "2"
        memory: 4Gi
    storage:
      volumeClaimTemplate:
        spec:
          accessModes:
          - ReadWriteOnce
          resources:
            requests:
              storage: 10Gi
          storageClassName: exclusive-local-storage-csi-driver-sc
```

2) vmalert I enabled the scraping of it's metrics:
Here is the graph for `vmalert_recording_rules_last_evaluation_samples` for one recording rule that has those gap

![image](https://user-images.githubusercontent.com/16001560/142094922-5c881aeb-e40d-4d7a-b896-d09567ba0a9d.png)

For all if I zoom in, we can see that they all drop to 0 at the same time together:
![image](https://user-images.githubusercontent.com/16001560/142095110-65d34eb0-3e79-492a-a895-f6f3cadbf4e4.png)
