### ISSUE TITLE
Question: Where should TLS/SSL certs be placed in docker containers?

### ISSUE THREAD

**Issue by BenB196** [VictoriaMetrics/VictoriaMetrics#186]
I am setting up Victoria Metrics in Docker, and want to use TLS. While I see that you can specify the cert locations using -tlsCertFile and -tlsKeyFile. I was wondering where to actually mount the cert/key?

If I try to mount the cert/key under /etc/victoria_metrics, I get the error:
```
ERROR: for victoria-metrics01  Cannot start service victoria-metrics01: OCI runtime create failed: container_linux.go:345: starting container process caused "process_linux.go:281: applying cgroation for process caused \"mountpoint for cgroup not found\"": unknown
```

Here is the docker compose file I am using:

```
version: '3.7'
services:
  victoria-metrics01:
   image: victoriametrics/victoria-metrics:v1.27.3
    container_name: victoriametrics01
    expose:
      - 8428
    command:
      - '-deleteAuthKey=<snip>'
      - '-httpAuth.username=<snip>'
      - '-httpAuth.password=<snip>'
      - '-retentionPeriod=16'
      - '-snapshotAuthKey=<snip>'
      - '-tls'
      - '-tlsCertFile=/etc/victoria-metrics/prometheus01.crt'
      - '-tlsKeyFile=/etc/victoria-metrics/prometheus01.key'
    volumes:
      - type: volume
        source: vm_certs
        target: /etc/victoria-metrics
        volume:
          nocopy: true
    logging:
      driver: "json-file"
      options:
        max-size: "5m"
        max-file: "1"
    networks:
      - prometheus_backend
    user: "1006:1006" #Note the NFS share that is being used as the cert volume is owned by a user with uid 1006
networks:
  prometheus_backend:
    driver: bridge
    ipam:
      config:
        - subnet: 10.111.0.32/29
  prometheus_conf:
    driver_opts:
      type: nfs
      o: "addr=10.10.25.1,hard,tcp,nolock,sync,rw"
      device: ":/mnt/data/prometheus/prometheus-conf"
```
