### ISSUE TITLE
Docker Swarm service discovery: invalid __address__ value for tasks

### ISSUE THREAD

**Issue by ashtuchkin** [VictoriaMetrics/VictoriaMetrics#2038]
**Describe the bug**
First of all, there's a typo on [this line](https://github.com/VictoriaMetrics/VictoriaMetrics/blob/9866dd95c14ae450c71ddc538aedc9a43df31273/lib/promscrape/discovery/dockerswarm/tasks.go#L124) - it should use `__address__` instead of `__address`.

Secondly, the `__address__` field that is calculated in `addTasksLabels` function linked above is always replaced by the same field in `commonLabels`, on lines 127 and 140. `commonLabels` map includes `__address__` field - it's coming from both `servicesLabels` and `hostLabels` above (the latter overwrites the former). 

As a result, `__address__` label of each task is always the same as in the `hostLabels`, which is always that host's external ip and either port 80 or whatever port is set in the config.

This prevents scraping all tasks unless they expose their metrics endpoint at that port.

**To Reproduce**
1. Install docker and initialize docker swarm (`docker swarm init`).
2. Create the following `stack.yaml`:
```yaml
version: "3.8"

services:
  vm:
    image: victoriametrics/victoria-metrics:v1.71.0
    entrypoint: [ "/bin/sh", "-ec" ]
    command:
      - |
        echo "$$PROM_SCRAPE_FILE" > /dev/shm/prometheus.yml
        exec /victoria-metrics-prod -httpListenAddr=:8428 -promscrape.config=/dev/shm/prometheus.yml
    environment:
      PROM_SCRAPE_FILE: |
        scrape_configs:
        - job_name: 'dockerswarm'
          dockerswarm_sd_configs:
            - host: unix:///var/run/docker.sock
              role: tasks
              port: 1  # used when task is not publishing ports 
          relabel_configs:
            # Only keep containers that are running.
            - source_labels: [__meta_dockerswarm_task_state]
              regex: running
              action: keep
            # Fetch metrics on a particular port, if given.
            - source_labels: ["__address__", "__meta_dockerswarm_service_label_metrics_port"]
              regex: "([0-9.]+):([0-9]+);([0-9]+)"
              replacement: "$$1:$$3"
              target_label: __address__
    volumes:
      - "vm-data:/victoria-metrics-data"
      - "/var/run/docker.sock:/var/run/docker.sock"
    networks:
      - custom-network
    deploy:
      labels:
        metrics-port: 8428

volumes:
  vm-data:

networks:
  custom-network:
```
Note, in this stack victoriametrics serves both as a scraper and a task that is scraped.
Also note, no ports are published, so port :8428 is only accessible from custom-network.

3. Deploy this stack:
```shell
$ docker stack deploy vm -c stack.yaml
```
4. Observe scrape error:
```shell
$ docker service logs --since 1m -f vm_vm
...
vm_vm.1.fih7mavoyu7s@ubuntu-s-1vcpu-1gb-nyc3-01    | 2022-01-06T20:41:31.856Z	info	VictoriaMetrics/lib/promscrape/scraper.go:387	dockerswarm_sd_configs: added targets: 1, removed targets: 0; total targets: 1
vm_vm.1.fih7mavoyu7s@ubuntu-s-1vcpu-1gb-nyc3-01    | 2022-01-06T20:42:24.206Z	error	VictoriaMetrics/lib/promscrape/scrapework.go:341	error when scraping "http://167.71.166.64:8428/metrics" from job "dockerswarm" with labels {instance="167.71.166.64:8428",job="dockerswarm"}: error when scraping "http://167.71.166.64:8428/metrics": dial tcp4 167.71.166.64:8428: connect: connection refused; try -enableTCP6 command-line flag if you scrape ipv6 addresses
```
Note, here 167.71.166.64 is the public ip of the host I used.

**Expected behavior**
`__address__` field should be the task's ip:port in that particular attached network and not overridden by the host ip.

**Version**
I'm using latest official docker image `victoriametrics/victoria-metrics:v1.71.0`

**Used command-line flags**
See stack definition above.
