### ISSUE TITLE
Allow to run behind a reverse proxy at a subpath

### ISSUE THREAD

**Issue by mvadu** [VictoriaMetrics/VictoriaMetrics#2066]
**Is your feature request related to a problem? Please describe.**
Currently Victoria metrics assumes root path, and has many subpaths all assuming / as starting point. (e.g. /vmui, /metrics etc). If we are running behind a proxy at a subpath, we can get the  landing page easily, but all the subsequent pages fail.

**Describe the solution you'd like**
Allow for a config for subpath, which then be used to render all links.

**Additional context**
I have this setup which is using traefik as my ingress controller for docker swarm. I can get the main page just fine. It even works for the manually navigating to http://host/victoria/vmui, but not as a regular navigation from homepage.

```yaml
victoriametrics:
    image: victoriametrics/victoria-metrics
    deploy:
      labels:
        - traefik.enable=true
        - traefik.http.routers.victoria.rule=PathPrefix(`/victoria`)|| HeadersRegexp(`Referer`, `.*/victoria/.*`)
        - traefik.http.routers.victoria.entrypoints=web
        - traefik.http.services.victoria.loadbalancer.server.port=8428
        - traefik.http.routers.victoria.middlewares=victoria-stripprefix
        - traefik.http.middlewares.victoria-stripprefix.stripprefix.prefixes=/victoria
      placement:
        constraints: [node.role==manager]
    volumes:
      - ../../volumes/victoriametrics/data:/storage
    command:
      - '--storageDataPath=/storage'
      - '--httpListenAddr=:8428'
      - '--influxListenAddr=:8089'
```
