### ISSUE TITLE
panic   VictoriaMetrics/lib/storage/merge.go:77 BUG: the next TSID is smaller than the current TSID

### ISSUE THREAD

**Issue by tfagart** [VictoriaMetrics/VictoriaMetrics#2082]
Hello
**Describe the bug**

Without knowing why, victoriametrics daemon does not start anymore and reload in circle. 
This seems to be linked to the metrics.
When I delete the metrics, victoriametrics daemon start properly.

**To Reproduce**
* Having my metrics
* Start Daemon

**Expected behavior**
The damon should start properly

**Logs**
Check if any warnings or errors were logged by VictoriaMetrics components
or components in communication with VictoriaMetrics (e.g. Prometheus, Grafana).
```
panic   VictoriaMetrics/lib/storage/merge.go:77 BUG: the next TSID=&{MetricGroupID:11476588284539612460 JobID:3309264923 InstanceID:4227594369 MetricID:1629150234862918511} is smaller than the current TSID=&{MetricGroupID:11476588284539612460 JobID:3309264923 InstanceID:4227594369 MetricID:1629150234862918683}
github.com/VictoriaMetrics/VictoriaMetrics/lib/logger.logMessage({0xb64085, 0x3b}, {0xc000150480, 0x107}, 0x2)
```
**Version**
build version: victoria-metrics-20210923-200036-tags-v1.66.2-0-g9f1964967

**Used command-line flags**
Docker Compose

```
root@vm-debian-1:/data/docker-compose# more victoriametrics/docker-compose.yml
version: '2.2'
services:
  victoriametrics:
    container_name: victoriametrics
    image: victoriametrics/victoria-metrics:latest
    volumes:
      - /data/docker/victoriametrics/data:/victoria-metrics-data
    command: "-graphiteListenAddr=:2003"
    ports:
      - 8428:8428
      - 2003:2003
    restart: always
```
Thanks

Thomas
