### ISSUE TITLE
gce_sd_config[].zone is displayed as {} on vmagent:8429/config

### ISSUE THREAD

**Issue by artifactori** [VictoriaMetrics/VictoriaMetrics#2179]
**Describe the bug**
Instead of the content of the configuration, `gce_sd_config[].zone` is displayed as `{}` on `vmagent:8429/config`.

**To Reproduce**
Configure this as scrape config:
```yaml
- job_name: job-1
  gce_sd_configs:
  - project: project-1
    zone: '*'
```

Open `vmagent:8429/config` and the configuration will be shown as:
```yaml
- job_name: job-1
  gce_sd_configs:
  - project: project-1
    zone: {}
```

**Expected behavior**
`vmagent:8429/config` should show the zone configuration, instead of just `{}`.

**Logs**
N/A

**Screenshots**
N/A

**Version**
`victoriametrics/vmagent:v1.72.0`

**Used command-line flags**
```
-httpListenAddr=:8429
-promscrape.config=/etc/vmagent/config_out/vmagent.env.yaml
-promscrape.streamParse=true
```
