### ISSUE TITLE
Question: How to limit users to just /query* subpaths with vmauth

### ISSUE THREAD

**Issue by bbkgh** [VictoriaMetrics/VictoriaMetrics#2181]
Hi. We want to separate query subpath of our users with different extra_filters with VMAuth but they can view Vmui(Single-node VictoriaMetrics page) including paths like top_queries and active_queries and it's a security issue. Is there any solution for limiting this in vmauth level? (We can also limit this paths by changing k8s ingress object to just /api/v1,... subpaths in reverse proxy)

**Comment by valyala** [comment]
This can be done with `url_map` feature in [vmauth](https://docs.victoriametrics.com/vmauth.html):

```yml
users:
- username: "foobar"
  url_map:
  - src_paths:
    - "/api/v1/query.*"
    - "/api/v1/label/[^/]+/values"
    - "/api/v1/series"
    - "/(graph|vmui).*"
    url_prefix: "http://victoriametrics:8428/"
```

This config allows "foobar" user access API paths, which match regexps listed at `src_path` section.
