### ISSUE TITLE
Force set all_tenants from openstack_sd_configs

### ISSUE THREAD

**Issue by nevlkv** [VictoriaMetrics/VictoriaMetrics#2182]
vmagent 1.70 with config 
```
    openstack_sd_configs:
      - role: 'instance'
        region: '*****'
        identity_endpoint: 'https://******/v3'
        domain_name: '*****'
        project_name: 'ServiceUsers'
        username: 'prometheus.reader'
        password: '*****'
        all_tenants: true
        refresh_interval: 60s
    relabel_configs:
       - source_labels: [__meta_openstack_instance_status]
         action: keep
         regex: ACTIVE
       - source_labels: [__meta_openstack_instance_name]
         target_label: instance
       - action: labelmap
         regex: __meta_openstack_tag_label_(.+)
```
not returnes any instancies with global readonly user (home project may be empty)

prometheus with same config work perfectly

getServer function try  to fetch list of servers and [omit all_tenats on request](https://github.com/VictoriaMetrics/VictoriaMetrics/blob/6bc52fe41a7cf389606cb8e742f27d7b08f7a6c1/lib/promscrape/discovery/openstack/instance.go#L116) but openstack defaults may be changed, and list become empty
