### ISSUE TITLE
High CPU on vmstorage usage after upgrade in 1.73.0 and 1.73.1

### ISSUE THREAD

**Issue by xenofree** [VictoriaMetrics/VictoriaMetrics#2242]
**Describe the bug**
High CPU on vmstorage usage after upgrade in 1.73.0 and 1.73.1 and vmstorage get killed by oom even if -memory.allowedPercent is set

**Screenshots**

![image](https://user-images.githubusercontent.com/35098906/155331803-1695dd94-8b11-481a-89d7-d77490c7c244.png)

![image](https://user-images.githubusercontent.com/35098906/155331871-5aa5b647-0f98-4c7f-af57-605d8871002a.png)

![image](https://user-images.githubusercontent.com/35098906/155332957-7ef9fa8c-bdc3-41b9-a2da-c4bca16a8601.png)

**Used command-line flags**
```
services:
  vminsert:
    image: victoriametrics/vminsert:v1.73.1-cluster
    command:
      - '-storageNode=vmstorage:8400'
      - '-memory.allowedPercent=10'

  vmstorage:
    image: victoriametrics/vmstorage:v1.73.1-cluster
    command:
      - '-storageDataPath=/victoria-metrics-data'
      - '-dedup.minScrapeInterval=1m'
      - '-retentionPeriod=12'
      - '-memory.allowedPercent=40'

  vmselect:
    image: victoriametrics/vmselect:v1.73.1-cluster
    command:
      - '-storageNode=vmstorage:8401'
      - '-dedup.minScrapeInterval=1m'
      - '-search.latencyOffset=0s'
      - '-memory.allowedPercent=10'
```

[vmstorage_mem_pprof.txt](https://github.com/VictoriaMetrics/VictoriaMetrics/files/8124777/vmstorage_mem_pprof.txt)
[vmstorage_cpu_pprof.txt](https://github.com/VictoriaMetrics/VictoriaMetrics/files/8124778/vmstorage_cpu_pprof.txt)
