### ISSUE TITLE
Vmagent - overrideable alerting rules feature

### ISSUE THREAD

**Issue by bojleros** [VictoriaMetrics/VictoriaMetrics#2398]
**Is your feature request related to a problem? Please describe.**

Usually alerting standard are based on baseline rules which are applied for all assets. It's also a common case where you have to define some overrides for example:

- having one particular application that does not play well when load is to high
- having 10TB filesystem where 95% used space is fine while on 10GB it is not

Considering second example one would likely end up with rules like this:

```
groups:
- name: thresholds
  rules:
    - record: node:filesystem_space_max_percentage:gauge
      expr: 0.85
    - record: node:filesystem_space_max_percentage:gauge
      expr: 0.90
      labels:
        instance: lucyfer.barek.prook.net:9100
        mountpoint: /home
    - record: node:filesystem_space_percentage:gauge
      expr: |
        (
        1 -
          (
          node_filesystem_avail_bytes{critical="true",fstype=~"ext.*|xfs|tmpfs"}
          /
          node_filesystem_size_bytes{critical="true",fstype=~"ext.*|xfs|tmpfs"}
          )
        )

- name: nodes
  rules:
  - alert: Filesystem space
    expr: |
      node:filesystem_space_percentage:gauge
      >
      on (instance, mountpoint) group_left()
        (
        node:filesystem_space_max_percentage:gauge
        or
        on(instance,mountpoint)
          count by(instance,mountpoint)(node:filesystem_space_percentage:gauge)*0 + scalar(node:filesystem_space_max_percentage:gauge{instance="",mountpoint=""})
        )
    for: 5m
    labels:
      severity: warning
    annotations:
      summary: "{{ title $labels.env }} server filesystem space utilization is high"
      description: "Filesystem space usage is {{ humanizePercentage $value}}. Reported on {{ $labels.mountpoint }} by instance {{ $labels.instance }} at {{ $labels.location }}."
```

Please let me know if you know a better method. This one is based on some robustperception article. It works but it is quite complicated. Let's consider having priority of label set matching as follows: (instance,mountpoint), (application), (project), () aka default. This will result in chain of nested group_left() to be performed for almost every case. Moreover you will have to add more levels of grouping here if there is a need of another label set to be used.

**Describe the solution you'd like**
Perhaps having overrides implemented like that is makes an interesting starting point:
https://medium.com/@hauskrechtmartin/how-we-solved-our-need-to-override-prometheus-alerts-b9faf9a4558c

```
- alert: K8SNodeCPUUtilization
  expr: K8SNodeCPUUtilization > 90
  for: 5m
  labels:
    severity: high
  annotations:
    identifier: '{{ $labels.kubernetes_cluster }}/{{ $labels.instance_name }}'
    msg: Node CPU ultilization by containers has been over 90% for more than 5m.
    reason: Node CPU ultilization by containers is high. Recalculate CPU request and limits.
    value: '{{ printf "%.2f" $value }}%'
    
 # The override rule
    
- alert: K8SNodeCPUUtilizationDev
  override: ["K8SNodeCPUUtilization"]
  enabled: true
  expr: K8SNodeCPUUtilization{kubernetes_cluster="kube-dev"} > 90
  for: 1h
  labels:
    severity: warning
  annotations:
    identifier: '{{ $labels.kubernetes_cluster }}/{{ $labels.instance_name }}'
    msg: Node CPU ultilization by containers has been over 90% for more than 1h.
    reason: Node CPU ultilization by containers is high. Recalculate CPU request and limits.
    value: '{{ printf "%.2f" $value }}%'
```

**Describe alternatives you've considered**
I don't know any other alternatives and personally i dislike idea of preprocessor since it makes things more complex.

**Additional context**
There is still hope that some more elegant solution exists so please post it if you have one :)
