### ISSUE TITLE
vmagent: Prometheus does not assume default values if missing

### ISSUE THREAD

**Issue by duhow** [VictoriaMetrics/VictoriaMetrics#2417]
**Describe the bug**
Installing Helm Chart [bitnami/kube-state-metrics](https://artifacthub.io/packages/helm/bitnami/kube-state-metrics) with no custom values, creates the following service:

```yaml
Name:              kube-state-metrics
Namespace:         logging
Labels:            app.kubernetes.io/instance=kube-state-metrics
                   app.kubernetes.io/managed-by=Helm
                   app.kubernetes.io/name=kube-state-metrics
                   helm.sh/chart=kube-state-metrics-2.2.13
Annotations:       meta.helm.sh/release-name: kube-state-metrics
                   meta.helm.sh/release-namespace: logging
                   prometheus.io/scrape: true
Selector:          app.kubernetes.io/instance=kube-state-metrics,app.kubernetes.io/name=kube-state-metrics
Type:              ClusterIP
IP Family Policy:  SingleStack
IP Families:       IPv4
IP:                10.0.103.106
IPs:               10.0.103.106
Port:              http  8080/TCP
TargetPort:        http/TCP
Endpoints:         
Session Affinity:  None
Events:            <none>
```

The **Service** has the annotation `prometheus.io/scrape: true`, but vmagent won't start scrapping the Service if `prometheus.io/port` is not specified.

**To Reproduce**
Install Helm Chart above.

**Expected behavior**
As the **Service** provides a **Port**, use that Service port as default, unless the annotation (if any) specifies another port.

**Logs**
N/A

**Screenshots**
N/A

**Version**
```
victoria-metrics-20220318-180401-tags-v1.75.0-0-g87d356348
```

**Used command-line flags**
```yaml
USER-SUPPLIED VALUES:
podDisruptionBudget:
  enabled: false
server:
  fullnameOverride: vmetrics
  ingress:
    enabled: false
  persistentVolume:
    enabled: true
    size: 8Gi
  retentionPeriod: 1
  scrape:
    enabled: true
  vmbackupmanager:
    enable: false
```
