### ISSUE TITLE
Add support dns_sd_configs in vmalert

### ISSUE THREAD

**Issue by vitalvas** [VictoriaMetrics/VictoriaMetrics#2460]
**Is your feature request related to a problem? Please describe.**
I want to push alerts to "big" alertmanager cluster.

**Describe the solution you'd like**
Add support dns_sd_configs in vmalert.
For me, the ideal configuration would be:
```
dns_sd_configs:
  - port: 9093
    type: 'A'
    names:
      - 'zone-a.alertmanager.example'
      - 'zone-b.alertmanager.example'
      - 'zone-c.alertmanager.example'
```

**Describe alternatives you've considered**
I was considering installing a balancer between vmalert and alertmanager. Also write a discovery script to populate static_configs endpoints on vmagent startup.

**Additional context**
Alertmanager is spaced so that it does not have a single point of failure (located in different regions). Because of this, it is not possible to statically specify the configuration for sending alerts.
