### ISSUE TITLE
vmalert: support reusable templates 

### ISSUE THREAD

**Issue by AndrewChubatiuk** [VictoriaMetrics/VictoriaMetrics#2510]
**Is your feature request related to a problem? Please describe.**
VMalert supports templating for annotations. It would be nice to be able to define custom templates in a separate location instead of writing repeatable infinite strings in a definition of each annotation where it's needed. 

**Describe the solution you'd like**
add a flag `-template="dir/*.yaml"`, same as for rules, to specify a file glob for templates and load them during a startup before rules validation.

**Describe alternatives you've considered**
Now it looks like this:

`custom_rule.yaml`
```
groups:
  - name: AlertGroupName
    rules:
      - alert: AlertName
        expr: any_metric > 100
        for: 30s
        labels:
          alertname: 'Any metric is too high'
          severity: 'warning'
        annotations:
          dashboard: '{{ $externalURL }}/d/dashboard?orgId=1&{{ $qstr := "" }}{{- range $label := .CommonLabels -}}{{- $qstr = (printf "%s&var-%s=%s" $qstr $label $label)  -}}{{- end -}}{{ $qstr }}'
```

and would be nice to have

`custom_template.tpl`
```
{{ define "grafana.filter" -}}
  {{- $labels := .arg0 -}}
  {{- range $name, $label := . -}}
    {{- if (ne $name "arg0") -}}
      {{- ( or (index $labels $label) "All" ) | printf "&var-%s=%s" $label -}}
    {{- end -}}
  {{- end -}}
{{- end -}}
```

`custom_rule.yaml`
```
groups:
  - name: AlertGroupName
    rules:
      - alert: AlertName
        expr: any_metric > 100
        for: 30s
        labels:
          alertname: 'Any metric is too high'
          severity: 'warning'
        annotations:
          dashboard: '{{ $externalURL }}/d/dashboard?orgId=1{{ template "grafana.filter" (args .CommonLabels "account_id" "any_label") }}'
```
