### ISSUE TITLE
VMAuth - dynamic accountID forwarding

### ISSUE THREAD

**Issue by noamApps** [VictoriaMetrics/VictoriaMetrics#2512]
**Is your feature request related to a problem? Please describe.**

We have a vm tenant that is used for testing an agent that sends metrics, we run the tests during development and also as a part of our CI.

We want the tests to run as quickly as possible so instead of booting a vm container for each test suite, we've deployed a victoria-metrics cluster, so now the tests will just randomize a tenant id, however we since victoria-metrics cluster mode uses a different endpoints for selection and insertion (and we didn't wanted to create a vm client interface that will be used only in testing as it will miss the point of mimicking production) we've put a vmauth in front of the cluster to proxy the requests to vminsert/vmselect accordingly, using the following configuration:

```
      - bearer_token: "100"
        url_map:
        - src_paths:
          - "/api/v1/query"
          - "/api/v1/query_range"
          - "/api/v1/label/[^/]+/values"
          url_prefix:
          - "http://victoria-metrics-cluster-vmselect:8481/select/100/prometheus"
        - src_paths: ["/api/v1/write"]
          url_prefix: "http://victoria-metrics-cluster-vminsert:8480/insert/100/prometheus"
        - src_paths: ["/api/v1/admin/tsdb/delete_series"]
          url_prefix: "http://victoria-metrics-cluster-vmselect:8481/delete/100/prometheus"
... 
```

However, since vmauth currently requires each tenant id to have an explicit configuration, this setup is limited to around 1800 users, that is because the k8s vmauth deployment config is mounted from secret which is limited to 1MB in size, this limit will not scale well as the company grow in devs and in tests.

although we are currently facing this issue in a tests, this would also limit other use-cases which might be more interesting to the community, as it means that using vmauth as proxy for new tenants requires a manual update of the secret for every new tenant, also people migrating from vm single mode to vm cluster mode will probably need to refactor code that interacts with victoria metrics, vmauth can potentially make the transition friction-less

**Describe the solution you'd like**

I understand that vmauth primary goal is to give a basic authorization layer, so I have few suggestions:
- allow victoria metrics single mode to support multiple tenants
- allow vmauth to operate with dynamic tenant proxying, something like:
```
      - tenant_id: "100" # instead of bearer_token or username
        url_map:
        - src_paths:
          - "/api/v1/query"
          - "/api/v1/query_range"
          - "/api/v1/label/[^/]+/values"
          url_prefix:
          - "http://victoria-metrics-cluster-vmselect:8481/select/{tenenat_id}/prometheus"
        - src_paths: ["/api/v1/write"]
          url_prefix: "http://victoria-metrics-cluster-vminsert:8480/insert/{tenenat_id}/prometheus"
        - src_paths: ["/api/v1/admin/tsdb/delete_series"]
          url_prefix: "http://victoria-metrics-cluster-vmselect:8481/delete/{tenenat_id}/prometheus"
```

**Describe alternatives you've considered**

using a in-house solution for proxying, currently prefer to avoid it.
