### ISSUE TITLE
Result contains metrics with the same labelset after applying rule labels

### ISSUE THREAD

**Issue by pollynesterovich** [VictoriaMetrics/VictoriaMetrics#2513]
There is an vmalerts config:
```
groups:
- name: test-group
  rules:

  - alert: TEST
    expr: ({__name__=~"test-health_.*",job="test-job"}) > 0
    for: 1m
    labels:
      severity: slack
    annotations:
      summary: Test {{ $labels.__name__ }} problems.
```
I find the following error in the logs: 
`result contains metrics with the same labelset after applying rule labels`
Please tell me how to correctly pass the value __name__  in order to display it in summary?
