### ISSUE TITLE
scrape_config basic_auth not working after upgrade to 1.77.0

### ISSUE THREAD

**Issue by ApocBoots** [VictoriaMetrics/VictoriaMetrics#2551]
**Describe the bug**
I use Victoriametrics (single-node, docker) to scrape metrics from multiple Prometheus instances over HTTPS using basic authentication.

Since I upgraded victoriametrics docker-image to 1.77.0 all jobs with basic_auth configured are getting "401 Authorization Required" Errors (see Logs) and metrics are not scraped anymore.
On my web browser I'm still able to manually log in using the same basic authentication credentials. 

After reverting to 1.76.1 everything is working as expected again.

**To Reproduce**

My scrape-job is configured as follows:
```
- job_name: 'example-job'
  honor_labels: true
  metrics_path: '/federate'
  basic_auth:
    username: 'scraper'
    password: 'secret'
  params:
    'match[]':
    - '{__name__=~".+"}'
  scheme: https
  scrape_interval: '15s'
  static_configs:
  - targets:
    - 'prometheus-federation.example.com:443'
  tls_config:
    ca_file: '/config/ca-file.pem'
```

**Expected behavior**
Victoriametrics using basic_auth username and password to scrape.

**Logs**
```
May 06 15:23:47 server.example.com victoria-metrics[5873]: 2022-05-06T13:23:47.195Z        error        VictoriaMetrics/lib/promscrape/scrapework.go:355        error when scraping "https://prometheus-federation.example.com:443/federate?match%5B%5D=%7B__name__%3D~%22.%2B%22%7D" from job "example-job" with labels {instance="prometheus-federation.example.com:443",job="example-job"}: unexpected status code returned when scraping "https://prometheus-federation.example.com:443/federate?match%5B%5D=%7B__name__%3D~%22.%2B%22%7D": 401; expecting 200; response body: "<html>\r\n<head><title>401 Authorization Required</title></head>\r\n<body>\r\n<center><h1>401 Authorization Required</h1></center>\r\n<hr><center>nginx</center>\r\n</body>\r\n</html>\r\n"
```

**Version**
```
$ ./victoria-metrics-prod --version
victoria-metrics-20220505-081124-tags-v1.77.0-0-g97f9c2f66
```
**Used command-line flags**
 -storageDataPath=/storage -promscrape.config=/config/prometheus.yml -relabelConfig=/config/relabel.yml -selfScrapeInterval=15s -selfScrapeInstance server.example.com -selfScrapeJob victoria-metrics -retentionPeriod=1y -promscrape.maxScrapeSize=128MB
