### ISSUE TITLE
Results different from prometheus when setting 'label_configs' incorrectly when using blackbox exporter

### ISSUE THREAD

**Issue by sungjunyoung** [VictoriaMetrics/VictoriaMetrics#2644]
**Describe the bug**
With misconfigured `label_configs`, the behavior of vmagent scrape is different with prometheus. below is my config
```yaml
- job_name: blackbox
  scrape_interval: 1s
  metrics_path: /probe
  params:
    module: [icmp]
  kubernetes_sd_configs:
    - role: node
  relabel_configs:
    - source_labels: [__meta_kubernetes_node_address_InternalIP]
      target_label: __param_target
    - source_labels: [__meta_kubernetes_node_address_InternalIP]
      target_label: host
    - source_labels: [module] # <-
      target_label: __param_module # <-
    - source_labels: [__meta_kubernetes_node_address_Hostname]
      target_label: instance
    - target_label: __address__
      replacement: blackbox-exporter:9115
```
Prometheus scrape metrics from blackbox exporter with `module` parameter, but vmagent not
- Prometheus -> blackbox-exporter:9115/probe?module=icmp&target=X.X.X.X
- VMAgent -> blackbox-exporter:9115/probe?target=X.X.X.X

**To Reproduce**
This situation can be easily reproduced with a unit test. by just adding that lines
<img width="692" alt="image" src="https://user-images.githubusercontent.com/16697306/170401713-7d0282e0-3301-4c2d-ae4a-c526eba49fd8.png">

According to my analysis, the situation occurs in the following order.
1. in relabel logic, `__param_module` label is set to empty string because `module` label is not exists in original label
2. vmagent will remove empty labels (promreleabel/relabel.go remoteEmptyLabels) because it doen't have value 
3. The query parameter is only created by `getParmsFromLabels` function that iterate parsed labels. Because there is no `__params_module` in labels, so `module` query parameter is ignored

**Expected behavior**
VMAgent should scrape via query parameter `module=icmp` like prometheus

**Logs**

**Screenshots**

**Version**
v1.77.1

**Used command-line flags**
