### ISSUE TITLE
remote_write: server returned HTTP status 504 Gateway Time-out

### ISSUE THREAD

**Issue by tothbalintjanos** [VictoriaMetrics/VictoriaMetrics#2653]
Hello Team,

I'd need a bit of help and your advise. I've set up a VictoriaMetrics cluster and we're sending data to it from 3 different prometheus instances via remote_write. I have the issue that after a few minutes the data doesn't arrive to VM anymore.

I see a lot of logs like this from prometheus which tries to sends the data:
`ts=2022-05-27T11:50:25.594Z caller=dedupe.go:112 component=remote level=warn remote_name=52e070 url=https://vminsert.XYZ/insert/0/prometheus msg="Failed to send batch, retrying" err="server returned HTTP status 504 Gateway Time-out: <html>"`

Logs from nginx in the receiver side:
`2022/05/27 12:12:32 [error] 49#49: *45504843 upstream timed out (110: Connection timed out) while reading response header from upstream, client: 10.180.0.11, server: vminsert.XYZ, request: "POST /insert/0/prometheus HTTP/1.1", upstream: "http://100.100.3.2:8480/insert/0/prometheus", host: "vminsert.XYZ"
2022/05/27 12:12:32 [error] 52#52: *45480473 upstream timed out (110: Connection timed out) while reading response header from upstream, client: 10.180.0.11, server: vminsert.XYZ, request: "POST /insert/0/prometheus HTTP/1.1", upstream: "http://100.100.3.2:8480/insert/0/prometheus", host: "vminsert.XYZ"
2022/05/27 12:12:33 [error] 53#53: *45461884 upstream timed out (110: Connection timed out) while reading response header from upstream, client: 10.180.0.11, server: vminsert.gXYZ, request: "POST /insert/0/prometheus HTTP/1.1", upstream: "http://100.100.3.2:8480/insert/0/prometheus", host: "vminsert.XYZ"`

Some settings of the VM cluster:
```
vmstorage:
    replicaCount: 4
####
vmselect:
    extraArgs:
      search.maxQueryDuration: 5m0s
      search.maxQueueDuration: 5m0s
      search.maxConcurrentRequests: "10"
    replicaCount: 4
####
vminsert:
      extraArgs:
        insert.maxQueueDuration: 5m0s
        maxConcurrentInserts: "100"
        maxLabelsPerTimeseries: "100"
      replicaCount: 4
```

The remote_write config of prometheus:
```
remote_write:
- url: https://vminsert.XYZ/insert/0/prometheus/
  remote_timeout: 5m
  basic_auth:
    username: vmuser
    password: <secret>
  follow_redirects: true
  queue_config:
    capacity: 2500
    max_shards: 200
    min_shards: 1
    max_samples_per_send: 500
    batch_send_deadline: 5s
    min_backoff: 30ms
    max_backoff: 100ms
  metadata_config:
    send: true
    send_interval: 1m
```

I also tried to tweak the queue_config parameters here (capacity and shards), but it didn't solve the 504 issue above.

Can you advise please with some best practices?
Thank you!
