### ISSUE TITLE
question about MetricsQL rate() function 

### ISSUE THREAD

**Issue by q605450469** [VictoriaMetrics/VictoriaMetrics#2689]
I found some interesting phenomena regarding the rate() calculation. Before I used prometheus as collection and storage, now I store the data in vm via remote_write of prometheus. use grafana to query vm directly to show the metrics. But the following phenomenon was found.

My environment.

prometheus:
version: 2.23.0
config:
```
global:
  scrape_interval: 10s
  scrape_timeout: 10s
  evaluation_interval: 10s

remote_write:
- url: http://vm-host:8428/api/v1/write
  remote_timeout: 30s
  queue_config:
    capacity: 2500
    max_shards: 200
    min_shards: 1
    max_samples_per_send: 500
    batch_send_deadline: 5s
    min_backoff: 30ms
    max_backoff: 100ms
  metadata_config:
    send: true
    send_interval: 1m
```

vm:
version: 1.77.2
run command:
/victoria-metrics-prod -storageDataPath=/data/victoria-metrics-major -retentionPeriod=30d

![image](https://user-images.githubusercontent.com/14797492/172145740-69aa596d-816f-4b3a-8cb3-cfe7636538fc.png)
![image](https://user-images.githubusercontent.com/14797492/172145828-907246b2-0ec5-402a-a43a-f7e9ec7c9f5a.png)

![image](https://user-images.githubusercontent.com/14797492/172145983-d3aa3bc0-a6d4-4de7-970e-2f9bf3cace8e.png)
![image](https://user-images.githubusercontent.com/14797492/172146070-1a4c162b-a0da-4220-a553-c9dfbe841485.png)

These are the metrics for different nodes of the same service, with time windows of 10s and 20s. you can see that the data in node A has changed, but not in node b.

I read the [article](https://medium.com/@romanhavronenko/victoriametrics-promql-compliance-d4318203f51e) on rate() optimization and roughly understand how MetricsQL is calculated. But I have no idea about this.

I tried to get the raw data to calculate it manually. the query is :
```
/api/v1/query_range?query=sum(http_server_requests_seconds_count{uri="/sohuapp/p/home/{uid}/rc",application="INDEX.MOBIL-APP.ONLINE", instance="{ip}:8800"})&start=1654507800&end=1654508100&step=10s
```
It is found that manual calculation can produce the same data as the query result.
I'm wondering if this is a problem with the original data timestamp. So I exported the raw data via ```export/csv```

ip.A: 
![image](https://user-images.githubusercontent.com/14797492/172148807-2a9568ad-2875-4ffc-96a4-cbf854193004.png)

ip.B:
 
![image](https://user-images.githubusercontent.com/14797492/172148899-a9390a7a-b487-4e37-a121-c144a00094b8.png)

No problems found and consistent with prometheus collection times.

but

After I compared the data several times, I found that the last digit of the timestamp of the original data is greater than 5, and this problem must appear.
![image](https://user-images.githubusercontent.com/14797492/172150068-3d66386b-9029-4840-9686-49a39b9c99d4.png)

I confirmed this after several attempts.

So, why does this happen?
