### ISSUE TITLE
vmalert: support additionalAlertRelabelConfigs in VMAlert CRD

### ISSUE THREAD

**Issue by tamcore** [VictoriaMetrics/VictoriaMetrics#2690]
**Describe the solution you'd like**
The Prometheus CRD allows defining _additionalAlertRelabelConfigs_, which would be a nice to have feature for VMAlert as well.

**Describe alternatives you've considered**
Unless I'm mistaken, currently we would have to try to manually create the configMap and pass it via --notifier.config, which then collides with notifier.url and would force us to define everything in the file passed via notifier.config.

`
vmalert 2022-06-07T06:59:34.201Z    fatal    VictoriaMetrics/app/vmalert/main.go:137    failed to init: failed to init notifier: only one of -notifier.config or -notifier.url flags must be specified
`

BUT, then the Operator will refuse to deploy the VMAgent, as there's no notifier defined (as we have passed --notifier-config via extraArgs and removed notifier/notifiers from the CR)

`cannot create or update vmalert: victoriametrics, cannot find any notifiers. cr.spec.Notifiers, cr.spec.Notifier and discovered alertmanager are empty
`

So we're basically stuck.

**Comment by datamuc** [comment]
Another option could be to allow `-notifier.config` even when `-notifier.url` is present the urls just have to be added to the static configs right?

**Comment by datamuc** [comment]
Thanks to @f41gh7 we have a workaround:

Set notifiers to some dummy url:

``` yaml
  notifiers:
  - url: http://localhost:666/
```

And then overwrite the notifier.url in extraArgs with an empty string:

``` yaml
 extraArgs: {{ toYaml .Values.vmalert.extraArgs | nindent 4 }}
   notifier.config: /etc/vm/configs/vmalert-notifier-{{ .Release.Name }}/notifier.yaml
   notifier.url: ""
   configMaps:
   - vmalert-notifier-{{ .Release.Name }}
```

and  the vmalert-notifier configmap looks like this:

``` yaml
apiVersion: v1
kind: ConfigMap
metadata:
  creationTimestamp: null
  name: vmalert-notifier-{{ .Release.Name }}
  namespace: {{ .Release.Namespace }}
data:
  notifier.yaml: |-
    dns_sd_configs:
    - names:
      - vmalertmanager-{{ .Release.Name }}
      type: A
      port: 9093
```

**Comment by hagen1778** [comment]
Hey @f41gh7! Does https://github.com/VictoriaMetrics/operator/commit/7011084f9cccc340848cb7589d5cecccb1e2f908 mean that the issue can be closed?

**Comment by tamcore** [comment]
In our case, not really. If you were using multiple notifiers in the `VMAlert.spec` with different `basicAuth` credentials, you'll be stuck, as it doesn't seem to be possible to have a per-url `basic_auth` block in the `notifier.config` file defined. However, if you're only using a single target, then it works.

So it's a step in the right direction, but not there yet. Ideally, It would still be possible to define notifiers in the CRD and simply have the referenced `notifier.config` included in the generated vmalert config.

**Comment by f41gh7** [comment]
> Hey @f41gh7! Does [VictoriaMetrics/operator@7011084](https://github.com/VictoriaMetrics/operator/commit/7011084f9cccc340848cb7589d5cecccb1e2f908) mean that the issue can be closed?

 Yep, it should solve issue with notifier service discovery.



> In our case, not really. If you were using multiple notifiers in the `VMAlert.spec` with different `basicAuth` credentials, you'll be stuck, as it doesn't seem to be possible to have a per-url `basic_auth` block in the `notifier.config` file defined. However, if you're only using a single target, then it works.
> 
> So it's a step in the right direction, but not there yet. Ideally, It would still be possible to define notifiers in the CRD and simply have the referenced `notifier.config` included in the generated vmalert config.

 It's an issue with current `vmalert` configuration file. Not sure how to solve it properly, maybe each sd config should have own http client auth params, which will override global one?


Something like:

```yam;
#notifiers_config.yaml
    basic_auth:
       user_name: user
    dns_sd_configs:
    - names:
      - vmalertmanager-{{ .Release.Name }}
      type: A
      port: 9093
  consul_sd_configs:
   - server: http://localhost:8501
      notifier:
          basic_auth:
              user_name: user
              password: pass
   - server: http://localhost:8506
      notifier:
          bearerToken: token
```

 @hagen1778  WDYT?

**Comment by hagen1778** [comment]
Wouldn't it make the notifier config not compatible with Prometheus configuration https://prometheus.io/docs/prometheus/latest/configuration/configuration/#alertmanager_config?

**Comment by hagen1778** [comment]
Hi @tamcore! If we extend `notifier.config.static_configs` to support auth settings per target - would it suffice?

**Comment by tamcore** [comment]
@hagen1778 yep, it would :)

**Comment by hagen1778** [comment]
I think it should be quite easy to implement. However, it won't be compatible with Prometheus. Let's see what we can do.

**Comment by valyala** [comment]
FYI, vmalert supports various authorization options for notifiers starting from [v1.82.0](https://github.com/VictoriaMetrics/VictoriaMetrics/releases) - see [these docs](https://docs.victoriametrics.com/vmalert.html#notifier-configuration-file).

**Comment by datamuc** [comment]
Please reopen, the problem has nothing to do with authorization. The problem is that the operator does not allow to use a notifier.config (if for example one want's to use alert_relabel_config). That is because -notifier.url and -notifier.config are mutually exclusive.

We have this [workaround](https://github.com/VictoriaMetrics/VictoriaMetrics/issues/2690#issuecomment-1203638820) though

**Comment by f41gh7** [comment]
> Please reopen, the problem has nothing to do with authorization. The problem is that the operator does not allow to use a notifier.config (if for example one want's to use alert_relabel_config). That is because -notifier.url and -notifier.config are mutually exclusive.
> 
> We have this [workaround](https://github.com/VictoriaMetrics/VictoriaMetrics/issues/2690#issuecomment-1203638820) though

 Can you provide more details? Errors, CRD examples or any other information how to reproduce an issue?

 With the latest version of operator v0.29.1 and latest CRDs, following example works as expected:
```
apiVersion: operator.victoriametrics.com/v1beta1
kind: VMAlert
metadata:
  name: example-vmalert
spec:
  replicaCount: 1
  datasource:
    url: "http://vmsingle-example-vmsingle-pvc.default.svc:8429"
  notifierConfigRef:
    key: notifier.yaml
    name: vmalert-notifier
  selectAllByDefault: false
---
apiVersion: v1
kind: Secret
metadata:
  name: vmalert-notifier
stringData:
  notifier.yaml: |
        static_configs:
          - targets:
              - http://vmalertmanager-example-0.default.svc:9093
              - http://vmalertmanager-example-1.default.svc:9093
        alert_relabel_configs:
          - target_label: "foo"
            replacement: "bar"
```
