### ISSUE TITLE
Magento: convert to user:pass@host proxyUrl from ServiceMonitor to valid proxy_basic_auth settings in VMServiceScrape CR

### ISSUE THREAD

**Issue by TamCore** [VictoriaMetrics/VictoriaMetrics#2700]
**Is your feature request related to a problem? Please describe.**

vmagent seems to have problems with `http://user:pass@host` like `proxyUrl` values in ServiceMonitor / VMServiceScrape CRs. Or at least when both `proxyUrl: http://user:pass@host`are used in combination with basicAuth settings for the actual target. 
While digging, I've noticed, that vmagent actually supports passing username and password through `proxy_basic_auth` in it's configuration.

**Describe the solution you'd like**

- The operator should, when converting ServiceMonitor CRs, with `http://user:pass@host`like `proxyURL` values, to VMServiceScrape CRs, split
  - the `proxyURL` field from ServiceMonitor into both `VMServiceScrape.spec.endpoints[].proxyURL` (containing only the actual URL) 
  - and `VMServiceScrape.spec.endpoints[].vm_scrape_params.proxy_client_config.basic_auth.username and password` fields (containing the credentials required to authenticating agains the proxy)

So basically converting from a ServiceMonitor like
```
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: haproxies-4cc26fd0
  namespace: config
spec:
  endpoints:
  - basicAuth:
      password:
        key: password
        name: haproxy-cred
      username:
        key: user
        name: haproxy-cred
    path: /metrics
    proxyUrl: http://username:password@1.2.3.4:8888
```
to a VMServiceScrape like
```
apiVersion: operator.victoriametrics.com/v1beta1
kind: VMServiceScrape
metadata:
  name: haproxies-4cc26fd0
  namespace: config
spec:
  endpoints:
  - basicAuth:
      password:
        key: password
        name: haproxy-cred
      username:
        key: user
        name: haproxy-cred
    path: /metrics
    proxyURL: http://1.2.3.4:8888
    vm_scrape_params:
      proxy_client_config:
        basic_auth:
          username: "username from servicemonitor"
          password: "password from servicemonitor"
```
