### ISSUE TITLE
Strange timestamp in response

### ISSUE THREAD

**Issue by zivan1** [VictoriaMetrics/VictoriaMetrics#272]
**Describe the bug**
In VictoriaMetrics output metrics timestamps are 30 sec back of origin.

**To Reproduce**
Prometheus configuration:
```
global:
  scrape_interval:     15s 
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
    - targets: ['localhost:9100']
remote_write:
- url: http://localhost:8428/api/v1/write
  queue_config:
    max_samples_per_send: 10000
    max_shards: 30
```

Sample query:
`
curl http://localhost:9090/api/v1/query?query=up; curl http://localhost:8428/api/v1/query?query=up
`

Response:
`
{"status":"success","data":{"resultType":"vector","result":[{"metric":{"__name__":"up","instance":"localhost:9100","job":"prometheus"},"value":[1576755366.615,"1"]}]}}{"status":"success","data":{"resultType":"vector","result":[{"metric":{"__name__":"up","instance":"localhost:9100","job":"prometheus"},"value":[1576755336,"1"]}]}}
`

1576755366 from prometheus
1576755336 from victoriametrics

**Expected behavior**
Same timestamp

**Versions**
prometheus, version 2.13.1
victoria-metrics-20191211-223012-tags-v1.31.0-0-g440a1511
