### ISSUE TITLE
vmalert: Recording rule of last time a metric changed during replay?

### ISSUE THREAD

**Issue by chriswiggins** [VictoriaMetrics/VictoriaMetrics#2731]
**Describe the bug**
I'm trying to reproduce in `vmalert` what I have in Prometheus, which is to record the last time a metric reported a 1 (as "up") and the last time it reported a 0 (as "down"). We use VictoriaMetrics as long-term storage, so want to implement the rule here as it could be a month or longer before the metric comes back "up"

The `vmalert` rule:

```yml
groups:
  - name: MetricStateChange
    interval: 30s
    concurrency: 2
    rules:
    - record: metric_last_down
      expr: timestamp(sum_over_time(metric{type="responding"}[2m]) == 0) or metric_last_down
    - record: metric_last_up
      expr: timestamp(sum_over_time(metric{type="responding"}[2m]) == 1) or metric_last_up
```

It appears as though the `or` part of the recording rule doesn't work in `vmalert` when I'm doing a replay, likely because the "last" value hasn't been written to VM by the time the next rule evaluation comes past. It might also be failing during normal execution, but I haven't tested that yet

**To Reproduce**
I'm running `vmalert` as follows to try and backfill the data:
```bash
./vmalert-prod -rule=/config/rules.yml -datasource.url=http://victoriametrics:8428 -remoteWrite.url=http://victoriametrics:8428 -replay.timeFrom=2022-06-15T00:00:00Z -replay.timeTo=2022-06-15T04:55:00Z -replay.rulesDelay=3s -remoteWrite.flushInterval=1
s -replay.maxDatapointsPerQuery=10
```

**Expected behavior**

I expect that any metric that is currently "up", but previously was "down", for its metric_last_down timestamp to stay level (i.e, the last_down time). However, the metric just stops being recorded after it flips back online.

Is doing a rule like this supported in `vmalert`? Any pointers / tips?

**Versions**
vmalert: v1.77.2
victoriametrics: v1.77.2
