### ISSUE TITLE
vmagent how <ec2_sd_config> works in china region

### ISSUE THREAD

**Issue by tripitakav** [VictoriaMetrics/VictoriaMetrics#2735]
Hi，I am using vmagent on ec2 in china region, and I found that <ec2_sd_config> can't work because of aws endpoint.

The ec2 endpoint in China region is different from ec2 endpoint in global.

So how can I pass the china region ec2 endpoint to vmagent？

**Comment by f41gh7** [comment]
Hello, can you try to specify it at `endpoint` configuration for ec2_sd_config:

```yaml
- job_name: ec2
  ec2_sd_configs:
  - endpoint: ec2.cn-north-1.amazonaws.com.cn
     region: cn-north-1
```

https://docs.amazonaws.cn/en_us/aws/latest/userguide/endpoints-Beijing.html
