### ISSUE TITLE
 error "cannot load TLS certificate" with option selectAllByDefault: true 

### ISSUE THREAD

**Issue by Man-from-Nocturne** [VictoriaMetrics/VictoriaMetrics#2827]
**Describe the bug**
I try to use default manifest for deploy VMagent and get error:
  
`2022-07-02T23:29:14.506Z fatal VictoriaMetrics/lib/promscrape/scraper.go:106 cannot read "/etc/vmagent/config_out/vmagent.env.yaml": cannot parse Prometheus config from "/etc/vmagent/config_out/vmagent.env.yaml": cannot parse `scrape_config`: cannot parse auth config for `job_name` "serviceScrape/monitoring/prometheus-operator-kube-p-kube-etcd/0": cannot load TLS certificate from `cert_file`="/etc/vm/secrets/etcd-client-cert/healthcheck-client.crt", `key_file`="/etc/vm/secrets/etcd-client-cert/healthcheck-client.key": open /etc/vm/secrets/etcd-client-cert/healthcheck-client.crt: no such file or directory`

I guess that problem is :
`selectAllByDefault: true / serviceScrapeNamespaceSelector: {} `
because when I don't use these strings I don't get this issue.

**To Reproduce**
```
Use default manifest:

apiVersion: operator.victoriametrics.com/v1beta1
kind: VMAgent
metadata:
  name: example-vmagent
spec:
  selectAllByDefault: true
  replicaCount: 1
  resources:
    requests:
      cpu: "250m"
      memory: "350Mi"
    limits:
      cpu: "500m"
      memory: "850Mi"
  extraArgs:
    memory.allowedPercent: "40"
  remoteWrite:
    - url: "http://vmsingle-example-vmsingle-pvc.default.svc:8429/api/v1/write"
```
or use something like this:

```
apiVersion: operator.victoriametrics.com/v1beta1
kind: VMAgent
metadata:
  name: example-vmagent
spec:
  serviceScrapeNamespaceSelector: {}
  podScrapeNamespaceSelector: {}
  podScrapeSelector: {}
  serviceScrapeSelector: {}
  nodeScrapeSelector: {}
  nodeScrapeNamespaceSelector: {}
  staticScrapeSelector: {}
  staticScrapeNamespaceSelector: {}
  replicaCount: 1
  scrapeInterval: 60s
  remoteWrite:
    - url: "http://vmsingle-example-vmsingle-pvc.default.svc:8429/api/v1/write"
```

**Expected behavior**
Successfully running VMagent pod. 

**Logs**
`2022-07-02T23:29:14.506Z fatal VictoriaMetrics/lib/promscrape/scraper.go:106 cannot read "/etc/vmagent/config_out/vmagent.env.yaml": cannot parse Prometheus config from "/etc/vmagent/config_out/vmagent.env.yaml": cannot parse `scrape_config`: cannot parse auth config for `job_name` "serviceScrape/monitoring/prometheus-operator-kube-p-kube-etcd/0": cannot load TLS certificate from `cert_file`="/etc/vm/secrets/etcd-client-cert/healthcheck-client.crt", `key_file`="/etc/vm/secrets/etcd-client-cert/healthcheck-client.key": open /etc/vm/secrets/etcd-client-cert/healthcheck-client.crt: no such file or directory`

**Version**
Image
victoriametrics/vmagent:v1.77.1
```

**Comment by Man-from-Nocturne** [comment]
I have tried  to mount my secret but it doesn't  work
```
  volumeMounts:
      - name: etcd-client-cert
        mountPath: "/etc/vm/secrets/"
  volumes:
        - name: etcd-client-cert
          secretName: etcd-client-cert
```

**Comment by Man-from-Nocturne** [comment]
works with this one:
```
spec:
  secrets:
    - etcd-client-cert
```
VMagent can parse correctly:
form vmagent/config_out/vmagent.env.yaml:
```
  scheme: https
  tls_config:
    insecure_skip_verify: false
    ca_file: /etc/vm/secrets/etcd-client-cert/ca.crt
    cert_file: /etc/vm/secrets/etcd-client-cert/healthcheck-client.crt
    key_file: /etc/vm/secrets/etcd-client-cert/healthcheck-client.key
  bearer_token_file: /var/run/secrets/kubernetes.io/serviceaccount/token
```
