### ISSUE TITLE
RemoteWrite leads 5-6minutes Lag

### ISSUE THREAD

**Issue by sundy-li** [VictoriaMetrics/VictoriaMetrics#287]
**Describe the bug**
We have been using VM for about 2 months, recently we found that the metrics are 5~6 minutes lag than Prometheus. I really need some advices to help solve that.  Thanks

**Version**
```
$ ./victoria-metrics-prod --version
victoria-metrics-20191224-105655-tags-v1.31.3-0-g5cb8d977
Single Version
```

**Additional context**

Prometheus Configurations:

```
remote_write:
- url: http://xxx:8428/api/v1/write
  remote_timeout: 30s
  queue_config:
    capacity: 20000
    max_shards: 50
    min_shards: 1
    max_samples_per_send: 100000
    batch_send_deadline: 5s
    min_backoff: 30ms
    max_backoff: 100ms
```

VM Configurations:

```
./victoria-metrics -storageDataPath=/data1/vm -retentionPeriod=3 -httpListenAddr=:8428
```

Some metrics of Prometheus
```
prometheus_remote_storage_pending_samples{queue="0:xxx} 200000
```

Some metrics of VM
```
vm_blocks{type="indexdb"} 223635
vm_blocks{type="storage/big"} 86686550
vm_blocks{type="storage/small"} 50965739
vm_merges_total{type="indexdb"} 417663
vm_merges_total{type="storage/big"} 28
vm_merges_total{type="storage/small"} 1180652
vm_metric_rows_skipped_total{name="vmselect"} 13772448590
vm_missing_metric_names_for_metric_id_total 0
vm_missing_tsids_for_metric_id_total 0
vm_new_timeseries_created_total 7585641
vm_nfs_dir_remove_failed_attempts_total 0
vm_opentsdb_request_errors_total{name="write", net="tcp"} 0
vm_opentsdb_request_errors_total{name="write", net="udp"} 0
vm_opentsdb_requests_total{name="write", net="tcp"} 0
vm_opentsdb_requests_total{name="write", net="udp"} 0
vm_parts{type="indexdb"} 21
vm_parts{type="storage/big"} 7
vm_parts{type="storage/small"} 27
vm_pending_rows{type="indexdb"} 0
vm_pending_rows{type="storage"} 199930
```

Prometheus screenshot.

![image](https://user-images.githubusercontent.com/3325189/72403957-c0ef1880-378e-11ea-9319-4bfa90abed1d.png)

Vm screenshot (By Promxy, 2 VM nodes are delayed, we have using http curl to ensure that)

![image](https://user-images.githubusercontent.com/3325189/72404026-ea0fa900-378e-11ea-9d83-dfbe73a26f4f.png)
