### ISSUE TITLE
VMagent don't discover new targets with consul_sd

### ISSUE THREAD

**Issue by MrLayup** [VictoriaMetrics/VictoriaMetrics#2899]
VMagent discover new targets from consul_sd only after restart. Consul agent on the same host as vmagent.
Strange messages in logs, when I place new services in consul: 
```
Jul 21 12:20:10 HOST vmagent: 2022-07-21T09:20:10.503Z#011error#011VictoriaMetrics/lib/promscrape/config.go:505#011there were errors when discovering consul targets for job "apps", so preserving the previous targets
Jul 21 12:20:40 HOST vmagent: 2022-07-21T09:20:40.502Z#011error#011VictoriaMetrics/lib/promscrape/config.go:952#011skipping consul_sd_config targets for job_name "apps" because of error: cannot get API config: cannot query consul agent info: cannot fetch "http://localhost:8500/v1/agent/self": dial tcp4 127.0.0.1:8500: connect: connection refused
```
Why VMagent use default hard coded values for server and scheme? I've changed hard coded values to https, 8501 and  insecure_skip_verify: true. It worked in my case, SD works like SD :) 

**Config:**
```
- job_name: apps
  consul_sd_configs:
  - server: localhost:8501
    scheme: https
    tags:
    - metrics
    tls_config:
      insecure_skip_verify: true
  - token: TOKEN
  relabel_configs:
  - source_labels:
    - __meta_consul_service_metadata_metrics_path
    target_label: __metrics_path__
  - source_labels:
    - __meta_consul_service_metadata_metrics_scheme
    regex: "^(http|https)$"
    target_label: __scheme__
  - source_labels:
    - __meta_consul_dc
    target_label: consul_dc
  - source_labels:
    - __meta_consul_health
    target_label: consul_health
  - action: labelmap
    regex: __meta_consul_metadata_(.+)
    replacement: "$1"
  - source_labels:
    - __meta_consul_node
    target_label: host
  - source_labels:
    - __meta_consul_node
    - __meta_consul_service_port
    separator: ":"
    target_label: instance
  - source_labels:
    - __meta_consul_service
    target_label: job
  - source_labels:
    - __meta_consul_node
    - __meta_consul_service_port
    separator: ":"
    target_label: __address__
```
