### ISSUE TITLE
Vmalert externalLabels override the same labels selected from datasource

### ISSUE THREAD

**Issue by okzheng** [VictoriaMetrics/VictoriaMetrics#2903]
Following is the vmalert config about external labels.
external_labels:
    region: cn-sh
    env: production
    grafana_datasource: Prometheus-CM
We have a vmagent which scrapes some various targets in multiple regions. And some of metrics contain a label named **region** but different value. For example: 
```
cloudmonitor_nas_capacity{region="cn-sh", app="cloudmonitor", env="production", instance="172.17.15.2", job="cloudmonitor", namespace="monitoring", service="cloudmonitor"} 
cloudmonitor_nas_capacity{region="cn-hk", app="cloudmonitor", env="production", instance="172.17.16.2", job="cloudmonitor", namespace="monitoring", service="cloudmonitor"} 
```
Metrics have been written to a tenant in vmcluster that the vmalert read from and write to.
When we add a sample recording rule to the vmalert for testing, we found the vmalert modified labels which name was consistent with external_labels config. 
```
groups:
  - name: test-recording-rule
    rules:
    - expr: (cloudmonitor_nas_meteredSize + cloudmonitor_nas_meteredIASize) / cloudmonitor_nas_capacity
        * 1024 *1024 * 1024
      record: cloudmonitor_nas:usage
```

The result was that labels' value were override(label region): 
```
cloudmonitor_nas:usage{app="cloudmonitor", env="production", grafana_datasource="Prometheus-CM", instance="172.17.16.2",  job="cloudmonitor", namespace="monitoring", region="cn-sh", service="cloudmonitor"}
```

When we queried metrics using the above expr, we got an expected result the label region was not modified.
We expected the vmalert could add that labels if them were not found in selected metrics. But if them were found in selected metrics already, vmalert should not attempt to modify it.  
 The behavior is inconsistent with vmagent or Prometheus. 
Please help explain it and give me a solution? Thanks.
