### ISSUE TITLE
InfluxDB protocol does not properly convert to prometheus metrics (resulting in missing/unselectable data)

### ISSUE THREAD

**Issue by erkexzcx** [VictoriaMetrics/VictoriaMetrics#3113]
I am using Telegraf agent to deliver metrics via InfluxDB protocol to VictoriaMetrics. I am using [below plugin](https://github.com/influxdata/telegraf/tree/master/plugins/inputs/linux_sysctl_fs):
```toml
# Provides Linux sysctl fs metrics
[[inputs.linux_sysctl_fs]]
  # no configuration
```

Here is the example output:
```
> linux_sysctl_fs,host=foo dentry-want-pages=0i,file-max=44222i,aio-max-nr=65536i,inode-preshrink-nr=0i,dentry-nr=64340i,dentry-unused-nr=55274i,file-nr=1568i,aio-nr=0i,inode-nr=35952i,inode-free-nr=12957i,dentry-age-limit=45i 1490982022000000000
```

The issue is here:

- Measurement: `linux_sysctl_fs`
- Field: `file-max`
- Prometheus format: `linux_sysctl_fs_file-max` which is **invalid metric name format**.

Here is the [prometheus metric naming specification](https://prometheus.io/docs/concepts/data_model/#metric-names-and-labels). It says:
> It may contain ASCII letters and digits, as well as underscores and colons. It must match the regex `[a-zA-Z_:][a-zA-Z0-9_:]*`.

As you can see [here](https://regex101.com/r/xj250M/1), it does not match given regex and it basically means influxdb metrics ingestion functionality is broken.

**Comment by erkexzcx** [comment]
This can be workarounded in Telegraf. The downside of this is that it will be applied to all other outputs.
```toml
# Workaround for https://github.com/VictoriaMetrics/VictoriaMetrics/issues/3113
[[processors.regex]]
  namepass = ["*"]
  [[processors.regex.field_rename]]
    pattern = "-"
    replacement = "_"
```
