### ISSUE TITLE
vmagent: support validation for the YAML anchors/aliases

### ISSUE THREAD

**Issue by scor2k** [VictoriaMetrics/VictoriaMetrics#3117]
Hello! We are using YAML anchors to simplify the final configuration for the vmagent: 

```
---
common_labels: &common_labels
  cluster: 'vm'
  cloud_type: 'aws'
  deployment_type: 'saas'
  monitoring: 'True'

….

scrape_configs:
- job_name: 'vmagent'
  scrape_interval: 15s
  static_configs:
    - targets: ['localhost:8429']
      labels: *common_labels
....
```

After upgrading from 1.65.0 -> 1.81.2 we faced the issue with the YAML unmarshaling:

```
cannot read "/opt/…./vmutils/conf.d/vmagent/targets.yaml": cannot parse Prometheus config from "/opt/…./vmutils/conf.d/vmagent/targets.yaml": cannot unmarshal data: yaml: unmarshal errors:
  line 2: field common_labels not found in type promscrape.Config
```

The issue might be solved by `-promscrape.config.strictParse=false` but I believe this is the wrong way and might be used as a temporary solution only. 

Could you please fix the config validation for the vmagent? 

Thank you.

**Comment by AndrewChubatiuk** [comment]
@scor2k
please try to update your config to 
```
---
scrape_configs:
- job_name: 'vmagent'
  scrape_interval: 15s
  static_configs:
    - targets: ['localhost:8429']
      labels: &common_labels
        cluster: 'vm'
        cloud_type: 'aws'
        deployment_type: 'saas'
        monitoring: 'True'
    - target: ['localhost:8888']
       labels: *common_labels
```
and it will not require `-promscrape.config.strictParse=false`
