### ISSUE TITLE
When reporting duplicate rules/alerts errors, specify duplicate rule

### ISSUE THREAD

**Issue by Lusitaniae** [VictoriaMetrics/VictoriaMetrics#3127]
I'm currently using Ansible templates to generate alerts based on conditions/variables defined in group/host vars, in some cases during new server deployments we may add duplicate variables (temporarily/by mistake) and get an error while testing the config file.

**Describe the solution you'd like**
Ideally, when reporting the duplicate rule error, vmalert should print the rule itself that's causing the error. As I'm running this against 100s of hosts, it can be difficult to find out exactly which rule is duplicated.

This is the current error
```
2022-09-19T08:05:47.539Z\tfatal\tVictoriaMetrics/app/vmalert/main.go:95\tfailed to parse [\"/tmp/source\"]: errors(1): invalid group \"generated-rules\" in file \"/tmp/source\": rule \"isOnline\" duplicate"], "stdout": "", "stdout_lines": []}

```

**Describe alternatives you've considered**

I can try to prevent this from ansible, while generating the template, but I thinks this would be useful generally to anyone.

**Comment by dmitryk-dk** [comment]
Hi @Lusitaniae ! Thank you for your question. 
As i see from your error log there is present group and rule
```
invalid group \"generated-rules\" in file \"/tmp/source\": rule \"isOnline\" duplicate"
```
And what cause the issue

**Comment by Lusitaniae** [comment]
Yes, but I’m generating 100 rules with the same template, so I need the
full alert details to know which one is duplicate

**Comment by Lusitaniae** [comment]
to give more context

In regular alerts we have expressions like

```
metric
* on(instance) group_left(nodename) (node_uname_info) 
* on(instance) group_left(customer) (customer_info) 
```

Which will give nodename + customer details we use on the alert message

For a certain metric, we want to track the absence of it. In which case we can't do a "JOIN"

so we generate the alert for each one (so nodename + customer details are hardcoded)

```
[% for validator in groups['private_validators'] %]
    - alert: IsOffline
      annotations:
        description: << hostvars[validator]['inventory_hostname'] >> 
        summary: << hostvars[validator]['inventory_hostname'] >>
      expr: absent(metric_that_we_track{node_identifier="<< hostvars[validator][node_identifier'] >>"}) == 1
      for: 30s
      labels:
        severity: critical
```
