### ISSUE TITLE
Making use of `labelkeep`in `VMPodScrape` causes `VMAgent.spec.externalLabels` to be dropped

### ISSUE THREAD

**Issue by tamcore** [VictoriaMetrics/VictoriaMetrics#3137]
**Describe the bug**
We just encountered an issue, where a `VMPodScrape` was deployed with
```
spec:
  podMetricsEndpoints:
    - port: metrics
      relabelConfigs:
        - action: replace
          replacement: xxxxxx
          targetLabel: job
        - action: replace
          sourceLabels:
            - pod
          targetLabel: instance
        - action: labelkeep
          regex: (job|instance)
```
and came to notice, that `externalLabels` defined on the `VMAgent` CR with
```
spec:
  externalLabels:
    cluster: foo
```
for example, are not included in the metrics sent to our VictoriaMetrics cluster. 

Upon changing the regex in the deployed `VMPodScrape` to
```
regex: (job|instance|cluster)
```
to respect our `externalLabels` labels as well, everything started to work as expected.

We believe this is a bug and the usage of `action: labelkeep` on a `VMPodScrape` (and other CRs) should not prevent defined `externalLabels` from being applied to the ingested metrics.

**To Reproduce**
See above.

**Expected behavior**
Usage of `action: labelkeep` should not prevent defined `externalLabels` from being applied to the ingested metrics.

**Logs**
None

**Screenshots**
None

**Version**
Running in K8s. Used images are:
- vmagent:v1.79.2
- operator:v0.28.5

**Comment by f41gh7** [comment]
Hello, sorry for delay. It looks like we use `externalLabels` in different way and it's not the same as prometheus does. 

Our scrape configuration `externalLabels` is available for relabeling with `relabel_configs`, while prometheus simply attach it to the metrics per remote target. https://github.com/prometheus/prometheus/blob/b8af4632be96081f60d280971d7ddc298d27a006/storage/remote/write.go#L183

 It's `vmagent` issue. @valyala  WDYT?

**Comment by valyala** [comment]
I think `vmagent` should add `external_labels` from `global` section of [scrape config](https://prometheus.io/docs/prometheus/latest/configuration/configuration/#scrape_config) to the scraped metrics after the relabeling in the same way as Prometheus does, since users expect that `external_labels` are added unconditionally to the scraped metrics, and the relabeling cannot modify the `external_labels`. For example, the following `external_labels` must be present in all the scraped metrics:

```yaml
global:
  external_labels:
    environment: prod
    datacenter: foobar
```
