### ISSUE TITLE
VMAgent stops routing if both keep_metrics and keep are used

### ISSUE THREAD

**Issue by slavitch** [VictoriaMetrics/VictoriaMetrics#3148]
**ISSUE:**

This should work for both bob=alice tags and metrics in the list.  It does not work.   I can select keep_metrics or keep but not both.

```
- action: keep_metrics
  regex:
  - "metric_a"
  - "metric_b"
  - "foo_.+"
- action: keep
  source_labels: [bob]
  regex: alice
```  
**REPRODUCE**:

Run vmagent with two remote write targets each with their own urlRelabelConfig

 -remoteWrite.url=${URL1}  -remoteWrite.urlRelabelConfig=${CONF1}  -remoteWrite.url=${URL2}  -remoteWrite.urlRelabelConfig="" 

URL1 has the file above.  URL2 gets all the metrics, which is great.

If only keep_metrics is set,  it works, the metrics are forwarded to URL1
```
- action: keep_metrics
  regex:
  - "metric_a"
  - "metric_b"
  - "foo_.+"
  ```
  
  if only keep is set, it works,  metrics with the tag bob=alice are fowarded to URL1
```
- action: keep
  source_labels: [bob]
  regex: alice
```

If both are set in the same file, no forwarding happens at all to URL1.  If the yaml is invalid, it doesn't say so or why.

**Expectation:**   

Allow for multiple rules in an urlRelabelConfig,  or a precedence, or an error if the formatting is incorrect.
