### ISSUE TITLE
When a promscrape config contains a target that contains the scheme, vmagent will drop the target without an error message

### ISSUE THREAD

**Issue by denisgolius** [VictoriaMetrics/VictoriaMetrics#3208]
**Describe the bug**
 when a promscrape config contains a target that contains the scheme (http/https), vmagent will drop the target without an error message

**To Reproduce**
add a http/https scheme to scrape target, see an examples below:

**prometheus.yml**:
```yaml
global:
  scrape_interval: 10s

scrape_configs:
  - job_name: 'vmagent'
    static_configs:
      - targets: ['http://vmagent:8429']
  - job_name: 'vmalert'
    static_configs:
      - targets: ['vmalert:8880']
  - job_name: 'victoriametrics'
    static_configs:
      - targets: ['victoriametrics:8428']

```

**Expected behavior**
vmagent will not start or print out an error to logs/stdout as it works in prometheus 

**Screenshots**
![image](https://user-images.githubusercontent.com/5650611/194561103-2d2ed955-e4dc-4eb1-b016-aecfd02d86af.png)
