### ISSUE TITLE
vmalertmanager not able to discover configs defined using VMAlertmanagerConfig

### ISSUE THREAD

**Issue by sreeragunnikrishnan** [VictoriaMetrics/VictoriaMetrics#3211]
**Describe the bug**
VM Alertmanager is not able to discover multiple VMAlertmanagerConfig defined using VMAlertmanagerConfig CRDs. I have the alertmanager configuration defined using both Secrets and VMAlertmanagerConfig
However the configselector never works discovering VMAlertmanagerConfig.Below is my vmalertmanager configuration. 

```
apiVersion: operator.victoriametrics.com/v1beta1
kind: VMAlertmanager
metadata:
  name: vm-test-vmalertmanager
  namespace: vm
  labels:
    app: vm-test-vmalertmanager
spec:
  replicaCount: 2
  configSecret: vm-test-vmalertmanager-config
  logLevel: debug
  configSelector:
    matchLabels:
      managed-by: vm-operator
  podMetadata:
    labels:
      app: vm-test-vmalertmanager
    annotations:
      prometheus.io/scrape: "true"
      prometheus.io/port: "9093"
  externalURL: https://vmalertmanager.private.in
  image:
    pullPolicy: IfNotPresent
    repository: ***************.dsp.ecr.ap-south-1.amazonaws.com/*******
    tag: v0.24.0
  rollingUpdateStrategy: RollingUpdate
  resources:
    limits:
      cpu: "200m"
      memory: "128Mi"
    requests:
      cpu: "50m"
      memory: "64Mi"
```

I have deployed both the secret and VMAlertmanagerConfigs in the same namespace 'vm' .

Providing sample VMAlertmanagerConfigs as well.

---
```
apiVersion: operator.victoriametrics.com/v1beta1
kind: VMAlertmanagerConfig
metadata:
  name: vm-alertmanager-testone-config
  namespace: vm
  labels:
    managed-by: vm-operator
spec:
  route:
    receiver: prod-alerts
    group_wait: 30s
    group_interval: 5m
    repeat_interval: 5h
    group_by:
      - alertname
      - instance
      - alert
    routes:
      - match:
          severity: 'test-alerts'
        continue: true
        receiver: 'prod-alerts'
  receivers:
    - name: 'prod-alerts'
      slack_configs:
      - api_url: 
          key: 'https://hooks.slack.com/*******/*************************'
        send_resolved: true
        channel: '#prod-alerts'
        text: "{{ range .Alerts }}<!channel> {{ .Annotations.summary }}\n{{ .Annotations.description }}\n{{ end }}"
```
---
```
apiVersion: operator.victoriametrics.com/v1beta1
kind: VMAlertmanagerConfig
metadata:
  name: vm-alertmanager-testtwo-config
  namespace: vm
  labels:
    managed-by: vm-operator
spec:
  route:
    receiver: stage-alerts
    group_wait: 30s
    group_interval: 5m
    repeat_interval: 5h
    group_by:
      - alertname
      - instance
      - alert
    routes:
      - match:
          severity: 'testtwo-alerts'
        continue: true
        receiver: 'stage-alerts'
  receivers:
    - name: 'stage-alerts'
      slack_configs:
      - api_url: 
          key: 'https://hooks.slack.com/*****/*************************'
        send_resolved: true
        channel: '#stage-alerts'
        text: "{{ range .Alerts }}<!channel> {{ .Annotations.summary }}\n{{ .Annotations.description }}\n{{ end }}"

```

Issue can be reproduced with this configurations.

**Comment by sreeragunnikrishnan** [comment]
@valyala Can you please check

**Comment by hagen1778** [comment]
cc @k1rk @zekker6 @f41gh7

**Comment by sreeragunnikrishnan** [comment]
Any luck with this? @hagen1778 @k1rk @zekker6 @f41gh7

**Comment by f41gh7** [comment]
Hello, sorry for delay, It's an issue with your `VMAlertmanagerConfig`. Operator logs should help identify an issue:

```
{"level":"error","ts":1666874309.2733288,"logger":"factory","msg":"bad configs found during alertmanager config building","alertmanager":"stack-victoria-metrics-k8s-stack","error":"errors: cannot build alertmanager receiver config for object: vm/vm-alertmanager-testone-config, err: cannot find secret for VMAlertmanager config: vm-alertmanager-testone-config, receiver: prod-alerts, err :resource name may not be empty;cannot build alertmanager receiver config for object: vm/vm-alertmanager-testtwo-config, err: cannot find secret for VMAlertmanager config: vm-alertmanager-testtwo-config, receiver: stage-alerts, err :resource name may not be empty"}
```

 It says, that `api_url` is defined not correctly. Expected, that it contains - `key` and `name` for secret with actual slack api key.

 Try at first create secret with actual url:

```yaml
apiVersion: v1
kind: Secret
metadata:
  name: slack-access
  namespace: vm
stringData:
  url: 'https://hooks.slack.com/*****/*************************'
```

 And add it as reference to the `api_url`
```yaml
apiVersion: operator.victoriametrics.com/v1beta1
kind: VMAlertmanagerConfig
metadata:
  name: vm-alertmanager-testone-config
  namespace: vm
  labels:
    managed-by: vm-operator
spec:
  route:
    receiver: prod-alerts
    group_wait: 30s
    group_interval: 5m
    repeat_interval: 5h
    group_by:
      - alertname
      - instance
      - alert
    routes:
      - match:
          severity: 'test-alerts'
        continue: true
        receiver: 'prod-alerts'
  receivers:
    - name: 'prod-alerts'
      slack_configs:
        - api_url:
            name: slack-access
            key: 'url'
          send_resolved: true
          channel: '#prod-alerts'
          text: "{{ range .Alerts }}<!channel> {{ .Annotations.summary }}\n{{ .Annotations.description }}\n{{ end }}"
---
apiVersion: operator.victoriametrics.com/v1beta1
kind: VMAlertmanagerConfig
metadata:
  name: vm-alertmanager-testtwo-config
  namespace: vm
  labels:
    managed-by: vm-operator
spec:
  route:
    receiver: stage-alerts
    group_wait: 30s
    group_interval: 5m
    repeat_interval: 5h
    group_by:
      - alertname
      - instance
      - alert
    routes:
      - match:
          severity: 'testtwo-alerts'
        continue: true
        receiver: 'stage-alerts'
  receivers:
    - name: 'stage-alerts'
      slack_configs:
        - api_url:
            name: slack-access
            key: 'url'
          send_resolved: true
          channel: '#stage-alerts'
          text: "{{ range .Alerts }}<!channel> {{ .Annotations.summary }}\n{{ .Annotations.description }}\n{{ end }}"

```
