### ISSUE TITLE
Missing labels from vmagent

### ISSUE THREAD

**Issue by mbaykara** [VictoriaMetrics/VictoriaMetrics#3217]
**Describe the bug**
Deployed only vmagent with helm chart `victoria-metrics-agent-0.8.17` in order to replace prometheus to send data TSDB.

**To Reproduce**
`helm install vmagent -f values.yaml vmagent vm/victoria-metrics-agent`

`values.yaml`
```
extraArgs:
  envflag.enable: "true"
  loggerFormat: json
  remoteWrite.headers: X-Scope-OrgID:mycluster
remoteWriteUrls:
- http://myapp.com/api/v1/push
replicaCount: 1
resources:
  limits:
    memory: 2Gi
  requests:
    cpu: 0.5
    memory: 1Gi
service:
  enabled: true

```

**Expected behavior**
After adding vmagent metrics to grafana as datasource, following labels are missing:
`deployements, cronJobs,`

**Screenshots**
expected as from prometheus:
`prometheus as datasource when explore:`

![prometheus png](https://user-images.githubusercontent.com/31475871/194869955-6daedc42-a19f-42e3-9100-927e24e9e7f3.png)

`vmagent as datasource:`
![vmagent](https://user-images.githubusercontent.com/31475871/194870849-4da9588e-12b6-4247-b0ca-09536c53b0cd.png)

For VictoriaMetrics health-state issues please provide full-length screenshots 
![vmgrafana](https://user-images.githubusercontent.com/31475871/194871316-91804975-50c6-47ab-8cdb-1c641123d880.png)
