### ISSUE TITLE
Single VictoriaMetrics v1.82.0 does not work in Docker on Windows 10

### ISSUE THREAD

**Issue by krzysion** [VictoriaMetrics/VictoriaMetrics#3236]
**Describe the bug**
Single VictoriaMetrics v1.82.0 does not work in Docker on Windows 10
Version <= v1.81.2 works fine.

**To Reproduce**
Windows 10 Professional
Rancher Desktop 1.6.0

docker-compose.yml

```yml
version: '3.7'
services:
  victoriametrics:
    image: victoriametrics/victoria-metrics:v1.82.0
    ports:
      - 8428:8428
    volumes:
      - ./vmdata:/vmdata
    command:
      - '--storageDataPath=/vmdata'
      - '--retentionPeriod=12'
      - '--loggerFormat=json'
      - '--httpListenAddr=:8428'
```

**Logs**
```json
{\"ts\":\"2022-10-13T19:48:07.183Z\",\"level\":\"panic\",\"caller\":\"VictoriaMetrics/lib/fs/fs.go:215\",\"msg\":\"FATAL: cannot move /vmdata/data/small/2022_10/351_102_20221013152800.000_20221013193930.000_171DB82EE0D26EF9 to /vmdata/data/small/2022_10/351_102_20221013152800.000_20221013193930.000_171DB82EE0D26EF9.must-remove.1665690473149556872: rename /vmdata/data/small/2022_10/351_102_20221013152800.000_20221013193930.000_171DB82EE0D26EF9 /vmdata/data/small/2022_10/351_102_20221013152800.000_20221013193930.000_171DB82EE0D26EF9.must-remove.1665690473149556872: permission denied\"}
{\"ts\":\"2022-10-13T19:53:54.472Z\",\"level\":\"panic\",\"caller\":\"VictoriaMetrics/lib/fs/fs.go:215\",\"msg\":\"FATAL: cannot move /vmdata/indexdb/171DB8DEE526120E/491_1_171DB8FA47AB9D51 to /vmdata/indexdb/171DB8DEE526120E/491_1_171DB8FA47AB9D51.must-remove.1665690821416036809: rename /vmdata/indexdb/171DB8DEE526120E/491_1_171DB8FA47AB9D51 /vmdata/indexdb/171DB8DEE526120E/491_1_171DB8FA47AB9D51.must-remove.1665690821416036809: permission denied\"}
```
