### ISSUE TITLE
Metrics relabeling issue with regex

### ISSUE THREAD

**Issue by redhelling21** [VictoriaMetrics/VictoriaMetrics#3251]
**Describe the bug**
I collect cadvisor metrics using the Docker Swarm service discovery, and I want to change the value of a task name.

Here is an extract of my config :
```
- job_name: 'cadvisor'
    dockerswarm_sd_configs:
      - host: unix:///var/run/docker.sock
        role: tasks
        port: 8080
    relabel_configs:
      - source_labels: [__meta_dockerswarm_service_name]
        regex: monitoring_cadvisor
        action: keep
      - source_labels: [__meta_dockerswarm_node_hostname]
        target_label: instance
    metric_relabel_debug: true
    metric_relabel_configs:
      - source_labels: [instance, container_label_com_docker_swarm_task_name]
        separator: ';'
        regex: '(.*?)\..*;(.*?)\..*'
        replacement: '$2:$1'
        target_label: container_label_com_docker_swarm_task_name
        action: replace
```

The pre-scrape relabeling process works normally, but the metrics part does not, as if it was ignored by vmagent. I tested the regex on several samples and it should work perfectly. I also tried changing it to get rid of the anti-slashes, just in case, but nothing changed.

**Expected behavior**
With a label **instance**=subdomain.domain.com and **container_label_com_docker_swarm_task_name**=myservice.h408nlaxmv8oqkn1pjjtd71to.nv987lz99rb27lkjjnfiay0g4, the final value of **container_label_com_docker_swarm_task_name** should be _myservice:subdomain_.
Instead, the metrics is untouched.

**Logs**
Nothing shows in the logs of vmagent.
When the metric_relabel_debug: true option is enabled, the "before" and "after" metrics are identical.

**Version**
1.82.1

**Used command-line flags**
For VM : 
     - --storageDataPath=/storage
     - --graphiteListenAddr=:2003
     - --opentsdbListenAddr=:4242
     - --httpListenAddr=:8428
     - --influxListenAddr=:8089
     - --vmalert.proxyURL=http://vmalert:8880
For VMAgent : 
     - --promscrape.config=/etc/prometheus/prometheus.yml
     - --remoteWrite.url=http://victoriametrics:8428/api/v1/write

Thanks in advance for your help...
