### ISSUE TITLE
vmagent: 403 error while scraping with bearer_token

### ISSUE THREAD

**Issue by virtualb0x** [VictoriaMetrics/VictoriaMetrics#3253]
**Describe the bug**
I've receive 403 error while trying to scrpape hashicorp vault metrics endpoint via vmagent.

I have got prometheus and victoriametrics deployments in k8s cluster. I have identical scrape_configs for boths pods (vmagent and prometheus):

```
- job_name: vault
  metrics_path: /v1/sys/metrics
  params:
    format:
    - prometheus
  scheme: https
  bearer_token: hvs.CAESIC_Rm1HPfXz2HcQ7B2OH_mybearertokenstringendshere
  static_configs:
  - targets:
    - vault.hashicorp.svc.cluster.local:8200

```

But if prometheus returns 1 for availability of metrics endpoint, so vmagent always returns 0
I've found the error log:
2022-10-20T12:05:49.658Z warn VictoriaMetrics/lib/promscrape/scrapework.go:388 cannot scrape \"http://vault.hashicorp.svc.cluster.local:8200/v1/sys/metrics?format=prometheus\" (job \"vault\", labels {instance=\"vault.hashicorp.svc.cluster.local:8200\",job=\"vault\"}): cannot read data: unexpected status code returned when scraping \"http://vault.hashicorp.svc.cluster.local:8200/v1/sys/metrics?format=prometheus\": 403; expecting 200; response body: \"{\\\"errors\\\":[\\\"permission denied\\\"]}\\n\"\n"

It seems like vmagent doesn't put bearer_token. But  I do not know how  to explore problem exactly

**To Reproduce**
Move scrape config for hashicorp vauult from prometheus to vm agent and receive 0  for availability
**Expected behavior**
VMagent returns metrics for hashicorp vault according to https://developer.hashicorp.com/vault/docs/configuration/telemetry#prometheus

**Logs**
2022-10-20T12:05:49.658Z warn VictoriaMetrics/lib/promscrape/scrapework.go:388 cannot scrape \"http://vault.hashicorp.svc.cluster.local:8200/v1/sys/metrics?format=prometheus\" (job \"vault\", labels {instance=\"vault.hashicorp.svc.cluster.local:8200\",job=\"vault\"}): cannot read data: unexpected status code returned when scraping \"http://vault.hashicorp.svc.cluster.local:8200/v1/sys/metrics?format=prometheus\": 403; expecting 200; response body: \"{\\\"errors\\\":[\\\"permission denied\\\"]}\\n\"\n"

**Version**
1.82.0
