### ISSUE TITLE
Specify credentials for vmagent multitenant

### ISSUE THREAD

**Issue by nthienan** [VictoriaMetrics/VictoriaMetrics#3257]
I’m experimenting `vmagent` multitenant. I’d like to route traffic via `vmauth` that’s in front of `vminsert`. How can I specify username and password for `remoteWrite.multitenantURL` in `vmagent` deployment? 

Btw, I’m using `vmoperator` to deploy the whole system. It'd be great if `vmoperator` supports reference to a k8s secret

**Comment by denisgolius** [comment]
Hi @nthienan !

See https://docs.victoriametrics.com/operator/api.html#vmagentremotewritespec and example below:
```
kind: VMAgent
spec:
   remoteWriteSettings:
     useMultiTenantMode: true
   remoteWrite:
   - url: http://vminsert-behind-auth
     basicAuth:
       username:
         key: user
         name: auth-secret
       password:
         key: password
         name: auth-secret
```
