### ISSUE TITLE
vmalert: send alerts to alertmanager with header

### ISSUE THREAD

**Issue by vandud** [VictoriaMetrics/VictoriaMetrics#3260]
**Is your feature request related to a problem? Please describe.**
I use Cortex's Alertmanager (multitenant Alertmanager)
But Vmalert can't send alerts to different Alertmanagers depending on tenant

**Describe the solution you'd like**
I dont know how better realize integration Vmalert with Cortex's Alertmanager
Perhaps it makes sense to add header to alert group configuration that will be sent to `-notifier.url`
Something like this:
```
groups:
  - name: alert_group
    headers: 
      [ <string>, ...]
    notifier_headers:
      [ "X-Scope-OrgID: <tenant_id>", ...]
    interval: 10s
    rules: []
```
Or add cli-flag that will enable of integration with Cortex's Alertmanager

**Describe alternatives you've considered**
Now I use Openresty for solving this problem
Vmalert configured with flag `-notifier.url=http://nginx/vmalert-alertmanager` and it sends all alerts to Nginx
All alertrules in Vmalert has label `tenant` with `tenant_id`
For example:
```
groups:
  - name: windows_exporter
    labels:
      tenant: "4"
    rules: []
```
My Nginx has configured like this:
```
location ~ /vmalert-alertmanager(/api/v2/alerts) {
  set $tenant "fake";
  access_by_lua_block {
    ngx.req.read_body()
    local body = ngx.req.get_body_data()
    local jq = require "resty.jq".new()
    jq:compile("map(.labels.tenant) | unique | .[] | tonumber")
    ngx.var.tenant = tonumber(jq:filter(body))
    jq:teardown()
  }
  proxy_pass http://alertmanager/alertmanager$1;
  proxy_set_header X-Scope-OrgID $tenant;
}
```
So Nginx adds `X-Scope-OrgID` header with `tenant_id` from label to every query
