### ISSUE TITLE
[VMAGENT] Cant use regex for label instance in relabelConfigs

### ISSUE THREAD

**Issue by isality** [VictoriaMetrics/VictoriaMetrics#3279]
Hello, Team

**Describe the bug**

I have config, bellow

```yaml
apiVersion: operator.victoriametrics.com/v1beta1
kind: VMStaticScrape
metadata:
  labels:
    k8s-metrics: "true"
  name: test-vm-agent-static-scrape
  namespace: default
spec:
  jobName: aws-test-666
  targetEndpoints:
    - labels:
        exporter_port: "8881"
      relabelConfigs:
          - sourceLabels:
              - instance
            regex: "10.10.0.0:8881"
            replacement: aws-confluence
            targetLabel: domain
      path: /metrics
      targets:
      - 10.10.0.0:8881
```

After applying a label domain does not exist

But if i'm using regex `"(.*)"`

```yaml
apiVersion: operator.victoriametrics.com/v1beta1
kind: VMStaticScrape
metadata:
  labels:
    k8s-metrics: "true"
  name: test-vm-agent-static-scrape
  namespace: default
spec:
  jobName: aws-test-666
  targetEndpoints:
    - labels:
        exporter_port: "8881"
      relabelConfigs:
          - sourceLabels:
              - instance
            regex: "(.*)"
            replacement: aws-confluence
            targetLabel: domain
      path: /metrics
      targets:
      - 10.10.0.0:8881
```
then my new label "domain" contains a word "aws-confluence".

It's seems like a harcode for a label "instance", if ii using other source label with same value (ip socket) relabing works fine. Do you validate a instance? 

**To Reproduce**

1. Apply this manifest 
```yaml
apiVersion: operator.victoriametrics.com/v1beta1
kind: VMStaticScrape
metadata:
  labels:
    k8s-metrics: "true"
  name: test-vm-agent-static-scrape
  namespace: default
spec:
  jobName: aws-test-666
  targetEndpoints:
    - labels:
        exporter_port: "8881"
      relabelConfigs:
          - sourceLabels:
              - instance
            regex: "10.10.0.0:8881"
            replacement: aws-confluence
            targetLabel: domain
      path: /metrics
      targets:
      - 10.10.0.0:8881
```
2. Check vmagent UI, the job aws-test-666 have not a new label "domain"

**Expected behavior**
1. regexp works
2. target label "domain" contains value (aws-confluence in my case) from replacement field

**Logs**

```
2022-10-26T18:38:48.919+0300	info	VictoriaMetrics/app/vmagent/remotewrite/remotewrite.go:164	Successfully reloaded relabel configs
2022-10-26T18:38:49.283+0300	info	VictoriaMetrics/lib/promscrape/config.go:128	restarting service discovery routines...
2022-10-26T18:38:49.312+0300	info	VictoriaMetrics/lib/promscrape/config.go:171	restarted service discovery routines in 0.029 seconds, stopped=0, started=0, restarted=1
2022-10-26T18:38:49.516+0300	info	VictoriaMetrics/lib/promscrape/scraper.go:181	found changes in "/etc/vmagent/config_out/vmagent.env.yaml"; applying these changes
2022-10-26T18:38:49.520+0300	info	VictoriaMetrics/lib/promscrape/scraper.go:403	static_configs: added targets: 1, removed targets: 1; total targets: 129

```

**Version**

```
vmagent:v1.80.0
```
