### ISSUE TITLE
vmagent: wrong scrape_duration in one of targets

### ISSUE THREAD

**Issue by mef13** [VictoriaMetrics/VictoriaMetrics#3293]
**Describe the bug**
Hi!
I use vmagent to scrape a several targets on localhost and one of targets has wrong scrape_duration duration.

example of my targets:

```yaml 
global:
  scrape_interval: 15s
  scrape_timeout: 15s
  external_labels:
    collector: tester
scrape_configs:

- job_name: test-db
  static_configs:
  - targets:
    - 127.0.0.1:3001
  relabel_configs:
  - source_labels:
    - instance
    replacement: db.test
    target_label: instance

- job_name: test-math
  static_configs:
  - targets:
    - 127.0.0.1:3000
  relabel_configs:
  - source_labels:
    - instance
    replacement: math.test
    target_label: instance
```

And test-db has scrape duration about 2 second

![image](https://user-images.githubusercontent.com/15233008/198993410-e2913d9b-4dab-4bdf-86f4-d172c33d4a62.png)

But if i click on "response" I got ~ 40-60 ms ever.
![image](https://user-images.githubusercontent.com/15233008/198994135-a7cad887-dd82-49c8-91f6-60a6803e987e.png)

**Version**
I test it on 
`vmagent-20221014-071846-tags-v1.82.1-0-g011f52718`
and
`vmagent-20221029-004945-tags-v1.83.0-0-g740f7ac5e`
