### ISSUE TITLE
vmagent: there is no (easy?) way to find out why certain target was dropped

### ISSUE THREAD

**Issue by b-a-t** [VictoriaMetrics/VictoriaMetrics#3311]
**Is your feature request related to a problem? Please describe.**

I was trying to adapt certain Prometheus relabeling configuration as was given in the blog post sample code([this one, to be exact](https://webera.blog/how-to-scale-gitlab-runners-into-kubernetes-using-hpa-based-on-external-metrics-throughout-16adfd996f08)) to VictoriaMetrics and it took me some time to find the correct setup.

After translating `prometheusSpec` into `VMPodScrape` I could see the results of the new scraper in the list of discovered targets together with an extensive list of the discovered labels, but target labels were presented by just `{}` and the whole target was marked as dropped.

I tried to check logs in the vmgent pod and overall looked around, but couldn't figure out why is this happening. So I started to remove relabeling rules one by one to simplify my configuration and on one of the iterations the target with the `UP` status and correctly processed labels.

It turned out that one of the relabeling rules:
```yaml
               - action: keep
                regex: your-gitlab-runner-name
                source_labels:
                - __meta_kubernetes_pod_label_name
```
was failing due to the absence of `__meta_kubernetes_pod_label_name` label and that invalidated the whole relabeling chain and dropped discovered target.

This, similar or completely opposite kinds of errors may happen during the development process, but the lack of any indication of what and where something went wrong makes fixing the issue really hard.

**Describe the solution you'd like**
I'd like to see some sort of helper message or log line that would assist in locating and fixing failing (re)labeling rules and scraping in general.

The message could be just printed to the Pod console or, even better, printed in the additional 4th column in the output of `vmagent` `discovered targets` list, similar to the `Last error`  for active targets.

**Comment by f41gh7** [comment]
We already have debug mode for relabeling, you have to try it out:

https://docs.victoriametrics.com/vmagent.html#relabeling

It will print to the vmagent stdout, why target was dropped by relabeling rule.

 For `VMPodScrape` it can be enabled with following syntax:

```
kind: VMPodScrape
spec:
  podMetricsEndpoints:
  - port: http
    vm_scrape_params:
         relabel_debug: true
```
 Hope it helps. 


   I think, that UI page could display relabeling debug information for job, if it's enabled.
