### ISSUE TITLE
vmagent: support different headers for each remote_write.url

### ISSUE THREAD

**Issue by yutian1224** [VictoriaMetrics/VictoriaMetrics#3325]
We usually push to different receive stores by labels via relabel_configs and multi `-remoteWrite.url`,
but in vmagent we can only add global headers via `-remoteWrite.headers`.

If each URL requires a different tenant, there is no way to implement push.

**Comment by hagen1778** [comment]
> If each URL requires a different tenant, there is no way to implement push.

Does your remote storage system support only headers for detecting the tenant?

**Comment by yutian1224** [comment]
I used a set of distributors to distinguish between different back-end storage systems by header.
I should use the following config in prometheus, but it can't be implemented in vmagent:
```yaml
remote_write:
- url: http://store/api/v1/receive  # same store url
  name: store-1
  headers:
    THANOS-TENANT: store-1  # different storage with tenant
  write_relabel_configs:
  - source_labels:
    - ['job']
    regex: "store-1"
    action: keep
- url: http://store/api/v1/receive
  name: store-2
  headers:
    THANOS-TENANT: store-2
  write_relabel_configs:
  - source_labels:
    - ['job']
    regex: "store-2"
    action: keep
```
