### ISSUE TITLE
Metrics being routed to incorrect accountID / tenant

### ISSUE THREAD

**Issue by nickmoeck** [VictoriaMetrics/VictoriaMetrics#3383]
**Describe the bug**
Metrics with a vm_account_id label set are sometimes stored in the wrong account ID. They also seem to sometimes be sent to both the correct and an incorrect account ID.

**To Reproduce**
vmagent1 scrapes targets and remote writes them to vmagent2 (as well as two separate VM single servers)
vmagent2 uses relabelConfig to add vm_account_id label based on the job label, as follows:
```
- if: '{job="jobNameA"}'
  target_label: vm_account_id
  replacement: 2000

- if: '{job=~"jobNameX|jobNameY|jobNameZ"}'
  target_label: vm_account_id
  replacement: 1000

- if: '{job=~"jobNameC|jobNameD|jobNameE"}'
  target_label: vm_account_id
  replacement: 3000

- if: '{job="jobNameB"}'
  target_label: vm_account_id
  replacement: 4000
```

vmagent2 then remote writes to vminsert

vmagent2, vminsert, vmstorage and vmwrite are all on the same server (172.16.0.23)

Querying for `up{}` at http://vmselect/select/4000/vmui returns metrics from jobNameB, jobNameC, jobNameA and jobNameX
It does NOT return all of the metrics from jobNameC, jobNameA, or jobNameX

**Expected behavior**
Querying for `up{}` at http://vmselect/select/4000/vmui should only return metrics from jobNameB

**Logs**
relabelDebug logs on vmagent2 indicate that the proper vm_account_id is being set on all metrics.

**Versions**
```
root@vmagent1:~# vmagent --version
vmagent-20220707-225818-tags-v1.78.1-0-gcf849aab7
```

```
root@victoriametrics:/# vmagent --version
vmagent-20221110-223837-tags-v1.83.1-0-gbbe1a1472

root@victoriametrics:/# vminsert --version
vminsert-20221110-224647-tags-v1.83.1-cluster-0-g6d984cdef

root@victoriametrics:/# vmstorage --version
vmstorage-20221110-224656-tags-v1.83.1-cluster-0-g6d984cdef

root@victoriametrics:/# vmselect --version
vmselect-20221110-224652-tags-v1.83.1-cluster-0-g6d984cdef
```

**Used command-line flags**
Note that for debugging, I'm running two instances of vmagent on vmagent2 and remote writing to both from vmagent1, so that I can see the relabelDebug info AND have it write to the cluster

vmagent1:
```
/usr/local/bin/vmagent -promscrape.config=/etc/prometheus/prometheus.yml -remoteWrite.url=http://172.16.0.23:4200/api/v1/write -remoteWrite.url=http://172.16.0.23:8429/api/v1/write -remoteWrite.url=http://172.16.0.15:8428/api/v1/write -remoteWrite.url=http://172.17.0.15:8428/api/v1/write
-promscrape.config.strictParse=false
```

vmagent2 / cluster
```
/usr/local/bin/vmstorage -storageDataPath /data -retentionPeriod 6 -httpListenAddr 172.16.0.23:8482 -vminsertAddr 172.16.0.23:8400 -vmselectAddr 172.16.0.23:8401
/usr/local/bin/vmselect -httpListenAddr 172.16.0.23:8481 -storageNode 172.16.0.23:8401 -storageNode 172.17.0.23:8401
/usr/local/bin/vminsert -httpListenAddr 172.16.0.23:8480 -storageNode 172.16.0.23:8400 -storageNode 172.17.0.23:8400
/usr/local/bin/vmagent -remoteWrite.relabelConfig=/etc/vmagent/relabel.yml -remoteWrite.url=http://172.16.0.23:8480/insert/multitenant/prometheus/api/v1/write -promscrape.config.strictParse=false
/usr/local/bin/vmagent -httpListenAddr=172.16.0.23:4200 -remoteWrite.relabelDebug -remoteWrite.tmpDataPath=/tmp/debug/ -remoteWrite.relabelConfig=/etc/vmagent/relabel.yml -remoteWrite.url=http://172.16.0.23:8480/insert/multitenant/prometheus/api/v1/write -promscrape.config.strictParse=false
```

**Comment by nickmoeck** [comment]
I just discovered that vminsert can do the relabelling I want, so I probably don't need the second vmagent. It seems (pending a longer test) that eliminating vmagent2 and remote writing directly from vmagent1 to vminsert resolves the issue. So, it appears that the issue is with vmagent's relabelling. Seems like it's a race condition.

**Comment by zekker6** [comment]
Hi @nickmoeck 
I've just tried to reproduce this issue with the following configurations(all based on your setup):
vmagent1 scrape config:
```
scrape_configs:
  - job_name: jobNameA
    scrape_interval: 3s
    static_configs:
      - targets: ['127.0.0.1:8429']

  - job_name: jobNameX
    scrape_interval: 3s
    static_configs:
      - targets: ['127.0.0.1:8429']

  - job_name: jobNameY
    scrape_interval: 3s
    static_configs:
      - targets: ['127.0.0.1:8429']

  - job_name: jobNameZ
    scrape_interval: 3s
    static_configs:
      - targets: ['127.0.0.1:8429']

  - job_name: jobNameC
    scrape_interval: 3s
    static_configs:
      - targets: ['127.0.0.1:8429']

  - job_name: jobNameD
    scrape_interval: 3s
    static_configs:
      - targets: ['127.0.0.1:8429']

  - job_name: jobNameE
    scrape_interval: 3s
    static_configs:
      - targets: ['127.0.0.1:8429']

  - job_name: jobNameB
    scrape_interval: 3s
    static_configs:
      - targets: ['127.0.0.1:8429']
```

vmagent2 relabel:
```
- if: '{job="jobNameA"}'
  target_label: vm_account_id
  replacement: 2000

- if: '{job=~"jobNameX|jobNameY|jobNameZ"}'
  target_label: vm_account_id
  replacement: 1000

- if: '{job=~"jobNameC|jobNameD|jobNameE"}'
  target_label: vm_account_id
  replacement: 3000

- if: '{job="jobNameB"}'
  target_label: vm_account_id
  replacement: 4000
```

cluster:
```
./vmstorage-prod 
./vminsert-prod  -storageNode=localhost:8400
./vmselect-prod  -storageNode=localhost:8401
```

vmagents:
```
./vmagent-prod  -httpListenAddr=:8429 -promscrape.config=vmagent-config.yml -remoteWrite.url=http://localhost:4200/api/v1/write
./vmagent-prod  -httpListenAddr=:4200 -remoteWrite.relabelDebug=false -remoteWrite.relabelConfig=./relabel.yml  -remoteWrite.url=http://localhost:8480/insert/multitenant/prometheus/api/v1/write
```

Query results after some time this was up:
```
$ curl -s -d 'query=up{}' 127.0.0.1:8481/select/4000/prometheus/api/v1/query | jq
{
  "status": "success",
  "isPartial": false,
  "data": {
    "resultType": "vector",
    "result": [
      {
        "metric": {
          "__name__": "up",
          "instance": "127.0.0.1:8429",
          "job": "jobNameB"
        },
        "value": [
          1669287894,
          "1"
        ]
      }
    ]
  }
}


$ curl -s -d 'query=up{}' 127.0.0.1:8481/select/3000/prometheus/api/v1/query | jq
{
  "status": "success",
  "isPartial": false,
  "data": {
    "resultType": "vector",
    "result": [
      {
        "metric": {
          "__name__": "up",
          "instance": "127.0.0.1:8429",
          "job": "jobNameC"
        },
        "value": [
          1669287898,
          "1"
        ]
      },
      {
        "metric": {
          "__name__": "up",
          "instance": "127.0.0.1:8429",
          "job": "jobNameD"
        },
        "value": [
          1669287898,
          "1"
        ]
      },
      {
        "metric": {
          "__name__": "up",
          "instance": "127.0.0.1:8429",
          "job": "jobNameE"
        },
        "value": [
          1669287898,
          "1"
        ]
      }
    ]
  }
}

$ curl -s -d 'query=up{}' 127.0.0.1:8481/select/2000/prometheus/api/v1/query | jq
{
  "status": "success",
  "isPartial": false,
  "data": {
    "resultType": "vector",
    "result": [
      {
        "metric": {
          "__name__": "up",
          "instance": "127.0.0.1:8429",
          "job": "jobNameA"
        },
        "value": [
          1669287905,
          "1"
        ]
      }
    ]
  }
}

$ curl -s -d 'query=up{}' 127.0.0.1:8481/select/1000/prometheus/api/v1/query | jq
{
  "status": "success",
  "isPartial": false,
  "data": {
    "resultType": "vector",
    "result": [
      {
        "metric": {
          "__name__": "up",
          "instance": "127.0.0.1:8429",
          "job": "jobNameX"
        },
        "value": [
          1669287984,
          "1"
        ]
      },
      {
        "metric": {
          "__name__": "up",
          "instance": "127.0.0.1:8429",
          "job": "jobNameY"
        },
        "value": [
          1669287984,
          "1"
        ]
      },
      {
        "metric": {
          "__name__": "up",
          "instance": "127.0.0.1:8429",
          "job": "jobNameZ"
        },
        "value": [
          1669287984,
          "1"
        ]
      }
    ]
  }
}
```
As far as I can see there is no issue in vmagents setup there. 

Could you please check if  `up{}` metrics have `job` label which is used for matching in relabeling config?
