### ISSUE TITLE
Monitor external nodes for configuration errors

### ISSUE THREAD

**Issue by marksugar** [VictoriaMetrics/VictoriaMetrics#3392]
I have a configuration issue when I
use vm-operator (victoria-metrics-operator-0.16.1 VERSION:0.29.2) in kubernetes to monitor servers outside of the cluster, I am unable to properly discover and add nodes outside of the cluster

node(172.16.100.49) running  node_exporter using docker and I need to add this node to the vm monitor

```
[test@172.16.100.49 ~]$ docker ps -a
CONTAINER ID   IMAGE                                     COMMAND                  CREATED         STATUS        PORTS     NAMES
b08a3853c9ae   quay.io/prometheus/node-exporter:v1.1.2   "/bin/node_exporter …"   17 months ago   Up 15 hours             node_exporter
```
configure the following 
```
cat <<EOF | kubectl apply -f -
apiVersion: operator.victoriametrics.com/v1beta1
kind: VMAgent
metadata:
  name: example-vmagent
  namespace: vm
spec:
  serviceScrapeSelector: {}
  serviceAccountName: vmagent
  inlineScrapeConfig: |
    - job_name: "example-node"
      static_configs:
      - targets: ["172.16.100.49:9100"]
  remoteWrite:
    - url: "http://vmagent-vmagent-victoriametrics:8429/api/v1/write"
EOF
```
vmagent and svc
```
# kubectl -n vm get vmagent,svc
NAME                                                           AGE
vmagent.operator.victoriametrics.com/example-vmagent           14m
vmagent.operator.victoriametrics.com/vmagent-victoriametrics   7h26m

NAME                                          TYPE        CLUSTER-IP      EXTERNAL-IP   PORT(S)                      AGE
service/victoria-metrics-operator             ClusterIP   10.68.243.200   <none>        8080/TCP,443/TCP             7h50m
service/vm-grafana                            ClusterIP   10.68.169.189   <none>        80/TCP                       6h59m
service/vmagent-example-vmagent               ClusterIP   10.68.20.132    <none>        8429/TCP                     14m
```

In the configuration in vmagent I found the configuration

`# kubectl -n vm exec -it  vmagent-vmagent-victoriametrics-59db4bd477-t6sxn   cat /etc/vmagent/config_out/vmagent.env.yaml | grep example`
```
- job_name: serviceScrape/vm/vmagent-example-vmagent/0
  honor_labels: false
  kubernetes_sd_configs:
  - role: endpoints
    namespaces:
      names:
      - vm
  metrics_path: /metrics
  relabel_configs:
  - action: keep
    source_labels:
    - __meta_kubernetes_service_label_app_kubernetes_io_component
    regex: monitoring
  - action: keep
    source_labels:
    - __meta_kubernetes_service_label_app_kubernetes_io_instance
    regex: example-vmagent
  - action: keep
    source_labels:
    - __meta_kubernetes_service_label_app_kubernetes_io_name
    regex: vmagent
  - action: keep
    source_labels:
    - __meta_kubernetes_service_label_managed_by
    regex: vm-operator
  - action: keep
    source_labels:
    - __meta_kubernetes_endpoint_port_name
    regex: http
  - source_labels:
    - __meta_kubernetes_endpoint_address_target_kind
    - __meta_kubernetes_endpoint_address_target_name
    separator: ;
    regex: Node;(.*)
    replacement: ${1}
    target_label: node
  - source_labels:
    - __meta_kubernetes_endpoint_address_target_kind
    - __meta_kubernetes_endpoint_address_target_name
    separator: ;
    regex: Pod;(.*)
    replacement: ${1}
    target_label: pod
  - source_labels:
    - __meta_kubernetes_pod_name
    target_label: pod
  - source_labels:
    - __meta_kubernetes_pod_container_name
    target_label: container
  - source_labels:
    - __meta_kubernetes_namespace
    target_label: namespace
  - source_labels:
    - __meta_kubernetes_service_name
    target_label: service
  - source_labels:
    - __meta_kubernetes_service_name
    target_label: job
    replacement: ${1}
  - target_label: endpoint
    replacement: http
```
`curl 172.16.100.49:9100/metrics`
```
# kubectl exec -it nginx-mem-69fd86c945-58sv5 -- curl 172.16.100.49:9100/metrics
...
go_gc_duration_seconds{quantile="0"} 1.048e-05
go_gc_duration_seconds{quantile="0.25"} 1.785e-05
go_gc_duration_seconds{quantile="0.5"} 1.875e-05
go_gc_duration_seconds{quantile="0.75"} 2.024e-05
go_gc_duration_seconds{quantile="1"} 3.427e-05
go_gc_duration_seconds_sum 0.00128552
go_gc_duration_seconds_count 65
# HELP go_goroutines Number of goroutines that currently exist.
```
however, the targets in the VMAgent UI show 0
![image](https://user-images.githubusercontent.com/21120630/204031241-66fe5d28-c7f4-40b6-93d4-d5a0d6051e07.png)

How should I configure it to add external monitoring to the cluster?

Thank you very much!
