### ISSUE TITLE
How does the metric vmalert_recording_rules_last_evaluation_samples work?

### ISSUE THREAD

**Issue by virtualb0x** [VictoriaMetrics/VictoriaMetrics#3399]
#question

Hello.

Could you be so kind to explain how does the metric vmalert_recording_rules_last_evaluation_samples work? 

We have a CM cluster , installed from Helm chart victoria-metrics-k8s-stack

A piece of config for vmagent (values.yml file):
```
vmalert:
  enabled: true
  spec:
    selectAllByDefault: true
    image:
      repository: "victoriametrics/vmalert"
      tag: v1.82.0
    evaluationInterval: 5m
    rulePath:
      - "/etc/vmalert/config/vm-victoria-rulefiles-0/*.yaml"
      - "/etc/vmalert/config/vm-victoria-alertfiles-0/*.yaml"
    datasource:
      url: "http://vmselect-victoria.victoriametrics.svc.cluster.local:8481/select/0/prometheus/"
    notifier:
      url: "http://vmalertmanager-victoria.victoriametrics.svc.cluster.local:9093"
```

I have picked up one rule as an example:
```
apiVersion: operator.victoriametrics.com/v1beta1
kind: VMRule
metadata:
  annotations:
    meta.helm.sh/release-name: victoria
    meta.helm.sh/release-namespace: victoriametrics
  generation: 1
  labels:
    app: victoria-metrics-k8s-stack
    app.kubernetes.io/instance: victoria
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: victoria-metrics-k8s-stack
    app.kubernetes.io/version: 1.82.0
  name: victoria-k8s.rules
  namespace: victoriametrics
spec:
  groups:
  - name: k8s.rules
    rules:
    - expr: |-
        sum by (cluster, namespace, pod, container) (
          irate(container_cpu_usage_seconds_total{job="kubelet", metrics_path="/metrics/cadvisor", image!=""}[5m])
        ) * on (cluster, namespace, pod) group_left(node) topk by (cluster, namespace, pod) (
          1, max by(cluster, namespace, pod, node) (kube_pod_info{node!=""})
        )
      record: node_namespace_pod_container:container_cpu_usage_seconds_total:sum_irate
```

So, I suppose that the record rule **node_namespace_pod_container:container_cpu_usage_seconds_total:sum_irate** has to be evaluating

I see data in grafana when VM is a datasource.
![image](https://user-images.githubusercontent.com/68299651/204271686-a9eee271-fa3b-4b6e-8e05-ef03dd18b363.png)

I also checked out https://github.com/VictoriaMetrics/VictoriaMetrics/issues/1953 this issue, and make a curl-request:
![image](https://user-images.githubusercontent.com/68299651/204272169-f4df966e-4dc8-4c4f-96ba-cb2c6712745d.png)

But when I'm cheking out metrics at vmagent/vmalert service I see zero both in erroe and sample matrics:
vmalert_recording_rules_error{recording="node_namespace_pod_container:container_cpu_usage_seconds_total:sum_irate", group="k8s.rules", id="5270911604183599248"} 0
 
vmalert_recording_rules_last_evaluation_samples{recording="node_namespace_pod_container:container_cpu_usage_seconds_total:sum_irate", group="k8s.rules", id="5270911604183599248"} 0

Can you please help me to investigate this vase. As far as  I undertand VMalert has to see this record, the record exists and present in vmStorage

**Comment by hagen1778** [comment]
Hello! Which version of vmalert is this? Can you show how `vmalert_recording_rules_last_evaluation_samples{recording="node_namespace_pod_container:container_cpu_usage_seconds_total:sum_irate", group="k8s.rules"} ` changes in time (in Grafana or vmui)? Please note, I removed the `id` label in case If ID has changed for some reason.

**Comment by virtualb0x** [comment]
Hello! Thank you for the fast reply :)

VMalert is of version 1.82 I suppose (from my pod):

```
 # /vmalert-prod --version
vmalert-20221007-005142-tags-v1.82.0-0-g832276064

```

Grafana data:
![image](https://user-images.githubusercontent.com/68299651/204575386-e6f6386e-def4-4771-92f3-764b6b52fdd1.png)

As for vmui I have no one, but can install if it really matters

As for vmalert UI:
![image](https://user-images.githubusercontent.com/68299651/204575699-55692086-84c7-4c12-a015-87b58272280d.png)

Does the VMalert ui shows it is ok, and grafana says NO according to my screenshots?

**Comment by hagen1778** [comment]
Hm, it is very weird. Looks like vmalert bug. Could you please show what API returns you for this specific rule? Check `/vmalert/api/v1/rules` endpoint and find your rule to check `lastSamples ` param.

**Comment by virtualb0x** [comment]
I suppose it returns:

```
{"name":"k8s.rules","rules":[{"ruleState":"","name":"node_namespace_pod_container:container_cpu_usage_seconds_total:sum_irate","query":"sum by (cluster, namespace, pod, container) (\n  irate(container_cpu_usage_seconds_total{job=\"kubelet\", metrics_path=\"/metrics/cadvisor\", image!=\"\"}[5m])\n) * on (cluster, namespace, pod) group_left(node) topk by (cluster, namespace, pod) (\n  1, max by(cluster, namespace, pod, node) (kube_pod_info{node!=\"\"})\n)","duration":0,"lastError":"","evaluationTime":0.037311883,"lastEvaluation":"2022-11-30T06:00:55.279896503Z","health":"ok","type":"recording","datasourceType":"prometheus","lastSamples":281,"id":"5270911604183599248","group_id":"3328198445870819846","updates":[{},{},{},{},{},{},{},{},{},{},{},{},{},{},{},{},{},{},{},{}]},
...
further data is ommited
``

**Comment by hagen1778** [comment]
Thanks! The response contains `"lastSamples": 281`, which is very weird since the same method is used for both: setting metrics value and value returned from API:
1. https://github.com/VictoriaMetrics/VictoriaMetrics/blob/8322760647f0e59778b89de14406fe73232e5814/app/vmalert/recording.go#L81-L82
2. https://github.com/VictoriaMetrics/VictoriaMetrics/blob/8322760647f0e59778b89de14406fe73232e5814/app/vmalert/recording.go#L204

I don't have ideas why you see the discrepancy. Can we try to investigate it a bit further?
Does it happen to this specific rule only? What happens if you restart vmalert - will metric show the correct value? If you check vmalert's /metrics page - do you see the same value for this specific metric as in Grafana?

**Comment by virtualb0x** [comment]
Yes, we can

It happens to  all rules I have in VM:
![image](https://user-images.githubusercontent.com/68299651/204770132-8e9a4f02-0337-4a30-a6b9-553f17511dee.png)

It's also weird because an error metrics also show zero.  Example:
**vmalert_recording_rules_error**{recording="node_quantile:kubelet_pleg_relist_duration_seconds:histogram_quantile", group="kubelet.rules", id="8563899369226980997"} 0

**vmalert_recording_rules_last_evaluation_samples**{recording="node_quantile:kubelet_pleg_relist_duration_seconds:histogram_quantile", group="kubelet.rules", id="8563899369226980997"} 0

So it looks like we have neither errors, no samples :)

The pod restart doesnt make sense. The metric stays strange.

Yes, vmalerts /metrics page shows zero (as posted above).

I'm not very friendly to Golang, sorry, but I want to ask you if I'm right in my investigation of above code:
in first code block we return a value after float64 func, and in second block code we return the value as is?

https://github.com/VictoriaMetrics/VictoriaMetrics/blob/8322760647f0e59778b89de14406fe73232e5814/app/vmalert/recording.go#L82

vs

https://github.com/VictoriaMetrics/VictoriaMetrics/blob/8322760647f0e59778b89de14406fe73232e5814/app/vmalert/recording.go#L214

Can it somehow matter?

**Comment by hagen1778** [comment]
> Can it somehow matter?

No, it doesn't matter.

> So it looks like we have neither errors, no samples :)

It can be so when recording rule expression just doesn't get anything in response. For example, if you have recording rule with an expression that filters by the non-existing label `my_metrics{unknownLabel="unknownValue"}`, then you'll have neither errors nor samples in response.

On your screenshot, all the metrics have 0 samples. Is this expected or it is the same situation as with `node_namespace_pod_container:container_cpu_usage_seconds_total:sum_irate` ?

**Comment by virtualb0x** [comment]
No, it is not expected. I picked up the random record rule  as an example

Let us check several more rules

1.
```
vmalert_recording_rules_last_evaluation_samples{recording=":node_memory_MemAvailable_bytes:sum", group="node.rules", id="4238716903624357938"} 0
```

```
{"ruleState":"","name":":node_memory_MemAvailable_bytes:sum","query":"sum(\n  node_memory_MemAvailable_bytes{job=\"node-exporter\"} or\n  (\n    node_memory_Buffers_bytes{job=\"node-exporter\"} +\n    node_memory_Cached_bytes{job=\"node-exporter\"} +\n    node_memory_MemFree_bytes{job=\"node-exporter\"} +\n    node_memory_Slab_bytes{job=\"node-exporter\"}\n  )\n) by (cluster)","duration":0,"lastError":"","evaluationTime":0.006555156,"lastEvaluation":"2022-12-01T06:13:32.602218052Z","health":"ok","type":"recording","datasourceType":"prometheus"**,"lastSamples":1,**"id":"4238716903624357938","group_id":"13064738789534478380","updates":[{},{},{},{},{},{},{},{},{},{},{},{},{},{},{},{},{},{},{},{}]},
```


2.
```
vmalert_recording_rules_last_evaluation_samples{recording="count:up1", group="kube-prometheus-general.rules", id="15014982907591039652"} 0
```

```
,"rules":[{"ruleState":"","name":"count:up1","query":"count without(instance, pod, node) (up == 1)","duration":0,"lastError":"","evaluationTime":0.009232698,"lastEvaluation":"2022-12-01T06:13:01.83978725Z","health":"ok","type":"recording","datasourceType":"prometheus",**"lastSamples":63**,"id":"15014982907591039652","group_id":"11180328799576542464","updates":[{},{},{},{},{},{},{},{},{},{},{},{},{},{},{},{},{},{},{},{}]},
```


3.
```
vmalert_recording_rules_last_evaluation_samples{recording="node:node_num_cpu:sum", group="node.rules", id="10448227652904886789"} 0
```

```
"health":"ok","type":"recording","datasourceType":"prometheus","**lastSamples":5,**"id":"10448227652904886789","group_id":"13064738789534478380","updates":[{}]},{"state":"","name":":node_memory_MemAvailable_bytes:sum",
```

No one record rule returns value grater than zero.

**Comment by hagen1778** [comment]
Thanks! I have no idea what is happening here. I've checked multiple deployments of different versions and the metric shows expected numbers.
Have you tried updating vmalert? Can you reproduce the same behavior using compose files [here](https://github.com/VictoriaMetrics/VictoriaMetrics/tree/master/deployment/docker) ?

**Comment by virtualb0x** [comment]
Hello. I
ll try to do it in a week. I've already upgraded the VMalert version to the last 1.84 one. Nothing changes. Can you please tell me the  oldest version of vm alert you had tested and it was okay?

Ans also the example of  some recording rule from your tests. Want to apply it to my installation.

I suppose it can be misconfiguation on my side. But have no idea where to  look it for. I have to almost identical clusters and problrm is the same :(

**Comment by hagen1778** [comment]
I've checked multiple versions in different installations. 1.84 should work as well.
As an example, try running https://github.com/VictoriaMetrics/VictoriaMetrics/blob/master/deployment/docker/docker-compose.yml and modify [the list of rules](https://github.com/VictoriaMetrics/VictoriaMetrics/blob/e509552e92c9aa23f36d2af4ba2a7c4dc1ce3566/deployment/docker/docker-compose.yml#L66-L69) with some examples of recording rules:
```
      - alert: rows
        expr: vm_rows > 0
      - record: rows
        expr: sum(vm_rows)
```
or any other rules which you find sufficient for experiment. Docker-compose env is supposed to be an isolated env with correctly configured vmalert and datasource. So if you can reproduce your issue there - then 99% of the job is done and all that is left is just to fix it.

**Comment by virtualb0x** [comment]
Hi!

I tested with docker-compose. It shows everything is ok 
![image](https://user-images.githubusercontent.com/68299651/208509154-319bf02d-f9df-4923-af30-45a0b742db41.png)

Don't understand whats wrong with k8s installation with vm stack helm. But still problem seems to be on my side. May be I'll try to do it with minikube later

Thank you for help

**Comment by virtualb0x** [comment]
I've found out the reason. 

We have 
    rulePath:
      - "/etc/vmalert/config/vm-victoria-rulefiles-0/*.yaml"
      - "/etc/vmalert/config/vm-victoria-alertfiles-0/*.yaml"
  in vmalert configuration. 
  
  
```
vmalert:
  enabled: true
  # spec for VMAlert crd
  # https://github.com/VictoriaMetrics/operator/blob/master/docs/api.MD#vmalertspec
  spec:
    selectAllByDefault: true
    image:
      tag: v1.82.0
    evaluationInterval: 15s
    rulePath:
      - "/etc/vmalert/config/vm-victoria-rulefiles-0/*.yaml"
      - "/etc/vmalert/config/vm-victoria-alertfiles-0/*.yaml"
    datasource:
      url: "http://vmselect-victoria.victoriametrics.svc.cluster.local:8481/select/0/prometheus/"
```

Can you plz tell me if the manifest is ok? I need to apply custorm recordingRules and rules which we are configure without helm redeploy, just in VMRule and VMalert 

When I comment these strings and redeploy helm the metric is ok

@hagen1778  plz
