### ISSUE TITLE
AuthToken error when using victoria-metrics-cluster

### ISSUE THREAD

**Issue by tbounsiar** [VictoriaMetrics/VictoriaMetrics#3402]
Hello

I used chart `victoria-metrics-cluster` to deploy vm cluster in k8s using flux-cd
```yml
victoria-metrics-cluster:
    skip: false
    namespace: hdp-victoria-metrics
    chartSpec:
      chart: victoria-metrics-cluster
      sourceRef:
        kind: HelmRepository
        name: victoria-metrics
    dependsOn:
      # CephFS should be available to create PVC for storage
      - name: cephfs
    valuesOverride: |
      vmselect:
        env:
          - name: VM_FLAGS
            value: "-search.cacheTimestampOffset=87840h -search.maxPointsPerTimeseries=30000000"

      vminsert:
        extraArgs:
          opentsdbHTTPListenAddr: ":4242"

      vmstorage:
        env:
          - name: VM_FLAGS
            value: "-retentionPeriod=10y"
        persistentVolume:
          size: 32Gi
          storageClass: "{{ include "flux-blueprint.storageClassPosix" $ }}"
```
but when i try to write metrics using openSDB http server endpoint `/api/put` i get this error
```
{"ts":"2022-11-26T09:30:17.315Z","level":"warn","caller":"VictoriaMetrics/lib/ingestserver/opentsdbhttp/server.go:92","msg":"remoteAddr: \"10.233.100.24:57580\"; requestURI: /api/put; cannot parse path \"/api/put\": cannot find {authToken} in \"/api/put\"; expecting /{prefix}/{authToken}/{suffix} format"}
{"ts":"2022-11-26T09:30:26.934Z","level":"warn","caller":"VictoriaMetrics/lib/ingestserver/opentsdbhttp/server.go:92","msg":"remoteAddr: \"10.233.100.24:57580\"; requestURI: /api/put; cannot parse path \"/api/put\": cannot find {authToken} in \"/api/put\"; expecting /{prefix}/{authToken}/{suffix} format"}
{"ts":"2022-11-27T09:30:19.199Z","level":"warn","caller":"VictoriaMetrics/lib/ingestserver/opentsdbhttp/server.go:92","msg":"remoteAddr: \"10.233.100.24:43168\"; requestURI: /api/put; cannot parse path \"/api/put\": cannot find {authToken} in \"/api/put\"; expecting /{prefix}/{authToken}/{suffix} format"}
{"ts":"2022-11-27T09:30:25.956Z","level":"warn","caller":"VictoriaMetrics/lib/ingestserver/opentsdbhttp/server.go:92","msg":"remoteAddr: \"10.233.100.24:43168\"; requestURI: /api/put; cannot parse path \"/api/put\": cannot find {authToken} in \"/api/put\"; expecting /{prefix}/{authToken}/{suffix} format"}
{"ts":"2022-11-28T09:30:14.629Z","level":"warn","caller":"VictoriaMetrics/lib/ingestserver/opentsdbhttp/server.go:92","msg":"remoteAddr: \"10.233.100.24:49962\"; requestURI: /api/put; cannot parse path \"/api/put\": cannot find {authToken} in \"/api/put\"; expecting /{prefix}/{authToken}/{suffix} format"}
{"ts":"2022-11-28T09:30:23.429Z","level":"warn","caller":"VictoriaMetrics/lib/ingestserver/opentsdbhttp/server.go:92","msg":"remoteAddr: \"10.233.100.24:49962\"; requestURI: /api/put; cannot parse path \"/api/put\": cannot find {authToken} in \"/api/put\"; expecting /{prefix}/{authToken}/{suffix} format"}
```

Thanks
