### ISSUE TITLE
vmalert: set alert restore function and short health check would cause vmalert failed directly

### ISSUE THREAD

**Issue by Howie59** [VictoriaMetrics/VictoriaMetrics#3462]
**Describe the bug**
i deploy vmalert and vm cluster(vm insert, vm storage, vm select)
vmalert enable alert restore function and k8s health(readiness and ) check in following code
```yaml
          probe:
            readinessProbe:
              tcpSocket:
                port: {port}
              periodSeconds: 5
              timeoutSeconds: 5
            livenessProbe:
              httpGet:
                scheme: HTTP
                path: /healthz
                port: {port}
              periodSeconds: 5
              timeoutSeconds: 5
```
before vmalert start, vm cluster component failed.

vmalert start and try to restore alert, it fetch failed and wait for timeout(about 1 min). but vmalert health check would kill process in about 10s

it would cause vmalert failed directly on every start before vm cluster started.

if pod failed down restart duration is long, it would cause lost alert

**Logs**
set log level error, `kubectl logs xxx` get empty log

**Version**
latest versio

**Used command-line flags**
Please provide the command-line flags used for running VictoriaMetrics and its components. 
            - -rule=/vmalert/etc/*.yaml
            - -datasource.url=http://vmselect-vmcluster:{port}/select/0/prometheus
#            - -remoteRead.url=http://vmselect-vmcluster:{port}/select/0/prometheus
#            - -remoteWrite.url=http://vminsert-vmcluster.default:{port}/insert/0/prometheus
            - -notifier.url=http://{alarm}/api
            - -log.level=ERROR
            - -httpListenAddr=:{port}
