### ISSUE TITLE
vmalert alert resolved inaccuracy

### ISSUE THREAD

**Issue by 4wen** [VictoriaMetrics/VictoriaMetrics#3507]
**Describe the bug**
my rules:
```
groups:
- name: test_template
  rules:
  - alert: node_cpu_seconds_total__3200215
    expr: 100 - (avg by(endpoint) (rate(node_cpu_seconds_total{mode="idle",endpoint="xxx-137"}[2m]))* 100) >= 50.00000
    for: 1m
    labels:
      mark_tags: 483,1
      priority: 1
    annotations:
      description: ""
      summary: ""
```

query data from grafana:
<img width="1417" alt="image" src="https://user-images.githubusercontent.com/26673236/208667752-e5b9d335-d8bb-48fb-9363-17184ac3dab1.png">

query alert state:
<img width="1424" alt="image" src="https://user-images.githubusercontent.com/26673236/208668577-66999e27-4a87-4a5b-b486-27cb305121b7.png">

why alert state inaccuracy?It between firing and pending,firing for a while and then pending.

**Used command-line flags**
```
    -loggerTimezone=Asia/Shanghai \
    -loggerFormat=json \
    -httpListenAddr=:28880 \
    -configCheckInterval=17s \
    -evaluationInterval=30s \
    -rule=xxx.yml \
    -datasource.url=https://xxx.com \
    -datasource.basicAuth.username=xxx \
    -datasource.basicAuth.password=xxx \
    -remoteWrite.url=https://xxx.com \
    -remoteWrite.basicAuth.username=xx \
    -remoteWrite.basicAuth.password=xx \
    -remoteRead.url=https://xxx.com \
    -remoteRead.basicAuth.username=xx \
    -remoteRead.basicAuth.password=xx \
    -notifier.url=https://xxx.com \
```
