### ISSUE TITLE
After upgrade to v1.85.1 from v1.77.2 all metrics before a certain date disappeared

### ISSUE THREAD

**Issue by lucalandi** [VictoriaMetrics/VictoriaMetrics#3525]
# Describe the bug
After upgrading to version 1.85.1 a full time frame of metrics disappeared.

Currently using VictoriaMetrics cluster version without operator in AKS.

Details of the upgrade:
* start from current version `v1.77.2`
* upgrade to version `v1.84.0` - around Dec 14, 2022, 6:29 PM EST
* upgrade to version `v1.85.1` - around Dec 14, 2022, 6:29 PM EST
* the same progression was applied to 2 AKS clusters (1 non-production cluster and then production)

The progression for the upgrade was done in this way because of this note in the release notes:
```
Update note 1: this release drops support for direct upgrade from VictoriaMetrics versions prior v1.28.0. Please upgrade to v1.84.0, wait until finished round 2 of background conversion line is emitted to log by single-node VictoriaMetrics or by vmstorage, and then upgrade to newer releases.
```

**There are no visible metrics for anything before 2022-12-16 19:35:00 EST**

`victoriametrics` namespace cluster:
```
NAME                                      READY   STATUS    RESTARTS   AGE
pod/kube-state-metrics-8454f5b479-wkstn   1/1     Running   0          4d14h
pod/vmagent-56bff5bc5f-p8zh6              1/1     Running   0          3d13h
pod/vmalert-5ff8bc4df6-7vpcm              1/1     Running   0          4d14h
pod/vmcluster-vminsert-6fdf68db76-9spbv   1/1     Running   0          4d14h
pod/vmcluster-vminsert-6fdf68db76-wzbcb   1/1     Running   0          4d14h
pod/vmcluster-vmselect-8bcc4b7cf-tc76c    1/1     Running   0          4d14h
pod/vmcluster-vmselect-8bcc4b7cf-zw6nv    1/1     Running   0          4d14h
pod/vmcluster-vmstorage-0                 1/1     Running   0          4d14h
pod/vmcluster-vmstorage-1                 1/1     Running   0          4d14h
```

PVCs details:
```
k -n victoriametrics get pvc
NAME                                     STATUS   VOLUME                                     CAPACITY   ACCESS MODES   STORAGECLASS   AGE
vmstorage-volume-vmcluster-vmstorage-0   Bound    pvc-edf66493-8d14-433f-81aa-d508c083f787   500Gi      RWO            default        475d
vmstorage-volume-vmcluster-vmstorage-1   Bound    pvc-44c3cf9b-7d03-4791-affa-a319217c843a   500Gi      RWO            default        475d
```

# To Reproduce
A good starting point would be to follow the progression described in the previous section. I didn't personally try to reproduce it but I can maybe attempt something in a non-production AKS cluster.

# Expected behavior
After the upgrade I am expecting VictoriaMetrics to keep time-series data based on the current retention parameters set for vmstorage component.

# Logs

vmstorage logs during the upgrade
[Explore-logs-2022-12-22 23_46_40_vmstorage_ALL_logs.txt](https://github.com/VictoriaMetrics/VictoriaMetrics/files/10290971/Explore-logs-2022-12-22.23_46_40_vmstorage_ALL_logs.txt)

# Screenshots
There are no visible metrics for anything before 2022-12-16 19:35:00 EST
![image](https://user-images.githubusercontent.com/3875971/209241358-a0f297d1-4d36-49fc-8651-c4d55924cb6a.png)

I unfortunately don't have metrics from the upgrade itself but I remember I checked that all metrics were ok before calling it out a success in terms of upgrade process.

This is what I see from `vmagent` dashboard:
![image](https://user-images.githubusercontent.com/3875971/209242970-fdb7e60b-7454-4592-bf58-9bad12df395f.png)
![image](https://user-images.githubusercontent.com/3875971/209242994-144a5e90-3975-4dab-9b59-8407810ddcc8.png)
![image](https://user-images.githubusercontent.com/3875971/209243040-608ee91e-c853-46c2-8a14-6212541d280f.png)

This is what I see from `victoriametrics-cluster` dashboard:
![image](https://user-images.githubusercontent.com/3875971/209243277-7bd85455-a68f-49e3-ab1b-3632f12e7ced.png)
![image](https://user-images.githubusercontent.com/3875971/209243309-f7005258-4609-4557-a2fa-79e4c0086f96.png)
![image](https://user-images.githubusercontent.com/3875971/209243331-6a28b56b-c28d-43e4-9795-dbbba28ccf30.png)
![image](https://user-images.githubusercontent.com/3875971/209243353-6bb1efb2-2ec8-45a9-a9d4-ac96c19ccd84.png)
![image](https://user-images.githubusercontent.com/3875971/209243374-33c8bee5-3872-4824-a9bf-0c909a785d50.png)

# Version

Target v1.85.1 images used:
* `docker.io/victoriametrics/vmagent@sha256:e9c6d56f279e981a38d5343bbae76dc13a55cbe7ce918a39dac2b7ca43571e3b # victoriametrics/vmagent:v1.85.1`
* `docker.io/victoriametrics/vmalert@sha256:81c0389a717a293b66278a8fcd6009a27236ac3f2604479fcbc95098e0c9a8a1 # victoriametrics/vmalert:v1.85.1`
* `docker.io/victoriametrics/vminsert@sha256:4dc5969c11ac73ff791c63ad05b7018eb7ce89bdc217dbde87999bfb5995d2a7 # victoriametrics/vminsert:v1.85.1-cluster`
* `docker.io/victoriametrics/vmselect@sha256:0903c3ec63ff0e26b57d5ab0eb5b2cbb35197f4fa394b100a8af0a648bf6225b # victoriametrics/vmselect:v1.85.1-cluster`
* `docker.io/victoriametrics/vmstorage@sha256:c8af42945a012700fe1f3e5c7ec18eb0afeb87dcfc3595e8a6956049c4abbd0f # victoriametrics/vmstorage:v1.85.1-cluster`

VM versions:
```
pod: vmalert-5ff8bc4df6-7vpcm \| version: vmalert-20221214-211531-tags-v1.85.1-0-g09a70d3e9
pod: vmcluster-vminsert-6fdf68db76-9spbv \| version: vminsert-20221214-212305-tags-v1.85.1-cluster-0-g5da63d1ae
pod: vmcluster-vminsert-6fdf68db76-wzbcb \| version: vminsert-20221214-212305-tags-v1.85.1-cluster-0-g5da63d1ae
pod: vmcluster-vmselect-8bcc4b7cf-tc76c \| version: vmselect-20221214-212414-tags-v1.85.1-cluster-0-g5da63d1ae
pod: vmcluster-vmselect-8bcc4b7cf-zw6nv \| version: vmselect-20221214-212414-tags-v1.85.1-cluster-0-g5da63d1ae
pod: vmcluster-vmstorage-0 \| version: vmstorage-20221214-212508-tags-v1.85.1-cluster-0-g5da63d1ae
pod: vmcluster-vmstorage-1 \| version: vmstorage-20221214-212508-tags-v1.85.1-cluster-0-g5da63d1ae
pod: \| version: vmagent-20221214-211441-tags-v1.85.1-0-g09a70d3e9
```

# Troubleshooting

I have decided to check the file system and see if the data was deleted or not.
The PVCs are old compared to the time frame of the operations and there's no big change in terms of utilised this space.

**From a file system inspection of the vmstorage instances the data seems to be there.**

From `vmcluster-vmstorage-0`:

```
k -n victoriametrics exec -it vmcluster-vmstorage-0 -- /bin/sh
/ # du -sh /storage/data/small/*
347.5M  /storage/data/small/2022_09
292.1M  /storage/data/small/2022_10
13.8M   /storage/data/small/2022_11
32.3M   /storage/data/small/2022_12
4.0K    /storage/data/small/snapshots
/ # du -sh /storage/data/big/*
9.9G    /storage/data/big/2022_09
18.6G   /storage/data/big/2022_10
21.2G   /storage/data/big/2022_11
15.4G   /storage/data/big/2022_12
4.0K    /storage/data/big/snapshots
```
From `vmcluster-vmstorage-1`:

```
k -n victoriametrics exec -it vmcluster-vmstorage-1 -- /bin/sh
/ # du -sh /storage/data/small/*
282.4M  /storage/data/small/2022_09
150.6M  /storage/data/small/2022_10
21.5M   /storage/data/small/2022_11
37.2M   /storage/data/small/2022_12
4.0K    /storage/data/small/snapshots
/ # du -sh /storage/data/big/*
9.1G    /storage/data/big/2022_09
18.8G   /storage/data/big/2022_10
21.7G   /storage/data/big/2022_11
15.2G   /storage/data/big/2022_12
4.0K    /storage/data/big/snapshots
```

Tried also to clear caches based on this:

> Update notes: it is recommended [clearing caches](https://docs.victoriametrics.com/#cache-removal) after the upgrade from [v1.78.0](https://github.com/VictoriaMetrics/VictoriaMetrics/releases/tag/v1.78.0) in order to immediately fix the issue for newly ingested data. Otherwise the issue may exist for newly ingested data for up to a day after the upgrade.

It cleared the cache but it did not help in showing back the data that disappeared.

vmstorage stateful set:
```yaml
apiVersion: apps/v1
kind: StatefulSet
metadata:
  labels:
    app: vmstorage
    app.kubernetes.io/name: victoria-metrics-cluster
    app.kubernetes.io/instance: vmcluster
  name: vmcluster-vmstorage
  namespace: victoriametrics
spec:
  serviceName: vmcluster-vmstorage
  selector:
    matchLabels:
      app: vmstorage
      app.kubernetes.io/name: victoria-metrics-cluster
      app.kubernetes.io/instance: vmcluster
  replicas: 2
  podManagementPolicy: OrderedReady
  template:
    metadata:
      annotations:
        prometheus.io/port: "8482"
        prometheus.io/scrape: "true"
      labels:
        app: vmstorage
        app.kubernetes.io/name: victoria-metrics-cluster
        app.kubernetes.io/instance: vmcluster
    spec:
      automountServiceAccountToken: true
      containers:
        - name: victoria-metrics-cluster-vmstorage
          image: docker.io/victoriametrics/vmstorage@sha256:c8af42945a012700fe1f3e5c7ec18eb0afeb87dcfc3595e8a6956049c4abbd0f # victoriametrics/vmstorage:v1.85.1-cluster
          imagePullPolicy: "IfNotPresent"
          securityContext:
            {}
          args:
            - "--retentionPeriod=3" # retentionPeriod unit is months
            - "--storageDataPath=/storage"
            - --envflag.enable=true
            - --envflag.prefix=VM_
            - --loggerFormat=json
          ports:
            - name: http
              containerPort: 8482
            - name: vminsert
              containerPort: 8400
            - name: vmselect
              containerPort: 8401
          livenessProbe:
            failureThreshold: 10
            initialDelaySeconds: 30
            periodSeconds: 30
            tcpSocket:
              port: http
            timeoutSeconds: 5
          readinessProbe:
            failureThreshold: 3
            httpGet:
              path: /health
              port: http
            initialDelaySeconds: 5
            periodSeconds: 15
            timeoutSeconds: 5
          resources:
            requests: { memory: "2Gi", cpu: "1" }
            limits: { memory: "4Gi", cpu: "2" }
          volumeMounts:
            - name: vmstorage-volume
              mountPath: /storage
              subPath:
      serviceAccountName: vmcluster
      terminationGracePeriodSeconds: 60
      volumes:
  volumeClaimTemplates:
    - metadata:
        name: vmstorage-volume
      spec:
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: "500Gi"
```
