### ISSUE TITLE
signal SIGSEGV: segmentation violation

### ISSUE THREAD

**Issue by KES777** [VictoriaMetrics/VictoriaMetrics#3533]
**Describe the bug**
```
monaas-victoria-1  | panic: runtime error: invalid memory address or nil pointer dereference
monaas-victoria-1  | [signal SIGSEGV: segmentation violation code=0x1 addr=0x18 pc=0x8fad5a]
monaas-victoria-1  | 
monaas-victoria-1  | goroutine 82 [running]:
monaas-victoria-1  | github.com/VictoriaMetrics/VictoriaMetrics/lib/promscrape.(*Config).mustStart(0x0)
monaas-victoria-1  | 	github.com/VictoriaMetrics/VictoriaMetrics/lib/promscrape/config.go:119 +0x7a
monaas-victoria-1  | github.com/VictoriaMetrics/VictoriaMetrics/lib/promscrape.runScraper({0x7ffd7ada2f61, 0x1c}, 0xcaefd0, 0xc000072f00)
monaas-victoria-1  | 	github.com/VictoriaMetrics/VictoriaMetrics/lib/promscrape/scraper.go:115 +0x28c
monaas-victoria-1  | github.com/VictoriaMetrics/VictoriaMetrics/lib/promscrape.Init.func1()
monaas-victoria-1  | 	github.com/VictoriaMetrics/VictoriaMetrics/lib/promscrape/scraper.go:65 +0x74
monaas-victoria-1  | created by github.com/VictoriaMetrics/VictoriaMetrics/lib/promscrape.Init
monaas-victoria-1  | 	github.com/VictoriaMetrics/VictoriaMetrics/lib/promscrape/scraper.go:63 +0xa5
monaas-victoria-1  | panic: runtime error: invalid memory address or nil pointer dereference
monaas-victoria-1  | [signal SIGSEGV: segmentation violation code=0x1 addr=0x18 pc=0x8fad5a]
monaas-victoria-1  | 
monaas-victoria-1  | goroutine 77 [running]:
monaas-victoria-1  | github.com/VictoriaMetrics/VictoriaMetrics/lib/promscrape.(*Config).mustStart(0x0)
monaas-victoria-1  | 	github.com/VictoriaMetrics/VictoriaMetrics/lib/promscrape/config.go:119 +0x7a
monaas-victoria-1  | github.com/VictoriaMetrics/VictoriaMetrics/lib/promscrape.runScraper({0x7ffd9edebf61, 0x1c}, 0xcaefd0, 0xc0002fa060)
monaas-victoria-1  | 	github.com/VictoriaMetrics/VictoriaMetrics/lib/promscrape/scraper.go:115 +0x28c
monaas-victoria-1  | github.com/VictoriaMetrics/VictoriaMetrics/lib/promscrape.Init.func1()
monaas-victoria-1  | 	github.com/VictoriaMetrics/VictoriaMetrics/lib/promscrape/scraper.go:65 +0x74
monaas-victoria-1  | created by github.com/VictoriaMetrics/VictoriaMetrics/lib/promscrape.Init
monaas-victoria-1  | 	github.com/VictoriaMetrics/VictoriaMetrics/lib/promscrape/scraper.go:63 +0xa5
monaas-victoria-1  | panic: runtime error: invalid memory address or nil pointer dereference
monaas-victoria-1  | [signal SIGSEGV: segmentation violation code=0x1 addr=0x18 pc=0x8fad5a]

```

**To Reproduce**
docker-copose.yml
```yaml
  victoria:
    restart: unless-stopped
    image: victoriametrics/victoria-metrics
    expose:
      - "8428"
    command: [
      "-loggerLevel", "PANIC",
      "-promscrape.config", "/etc/victoria/prometheus.yml",
    ]
    volumes:
      - ./prometheus.yml:/etc/victoria/prometheus.yml
      - victoria-data:/victoria-metrics-data
```

**Expected behavior**
It should work. There should not be `SIGSEGV` when unknown option was met.

**Logs**
See above

**Screenshots**

For VictoriaMetrics health-state issues please provide full-length screenshots 
of Grafana dashboards if possible:
* [Grafana dashboard for single-node VictoriaMetrics](https://grafana.com/dashboards/10229)
link is broken ((

**Version**
```
$ ./victoria-metrics-prod --version
victoria-metrics-20221220-184303-heads-public-single-node-0-g1d7b5cb83
```

**Used command-line flags**
see above

**Comment by KES777** [comment]
```yaml
global:
  scrape_timeout:      10s
  scrape_interval:     10s
  evaluation_interval: 10s
  external_labels:
    monitor: monaas-office

# Alertmanager configuration
alerting:
  alertmanagers:
  - static_configs:
    - targets:
      - alertmanager:9093

# Load rules once and periodically evaluate them according to the global 'evaluation_interval'.
rule_files:
 # - "first_rules.yml"
 # - "second_rules.yml"

scrape_configs:
  - job_name: prometheus
    scrape_interval: 60s
    static_configs:
      - targets: ['prometheus:9090']

  - job_name: office-node
    scrape_interval: 60s
    static_configs:
      - targets: ['sysinfo-exporter:9100']
        labels:
          alias: 'sysinfo'

  - job_name: promscale
    scrape_interval: 60s
    static_configs:
      - targets: ['promscale:9201']

  # Problem here that *:9323 is publically available on host. This is not secure. See cAdvisor.
  #  - job_name: docker
  #    static_configs:
  #      - targets: ['host.docker.internal:9323']
  - job_name: cadvisor
    scrape_interval: 60s
    static_configs:
    - targets: ['cadvisor-exporter:8080']
      labels:
        alias: 'cadvisor'

  ## Add OpenVPN Node Exporter
  - job_name: openvpn
    scrape_interval: 60s
    static_configs:
      - targets: ['ovpn-exporter:9176']

  - job_name: pdns-auth
    scrape_interval: 60s
    static_configs:
      - targets: ['pdns-auth:8080']

  - job_name: pdns-recursor
    scrape_interval: 60s
    static_configs:
      - targets: ['pdns-recursor:8080']

  - job_name: postgres
    scrape_interval: 60s
    static_configs:
      - targets: ["postgres-exporter:9187"]

  - job_name: pushgateway
    scrape_interval: 60s
    static_configs:
      - targets: ['pushgateway:9091']

  - job_name: victoria
    scrape_interval: 60s
    static_configs:
      - targets: ['victoria:8428']


remote_write:
  - url: "http://promscale:9201/write"
remote_read:
  - url: "http://promscale:9201/read"
    read_recent: true
```
