### ISSUE TITLE
Healthcheck does not work

### ISSUE THREAD

**Issue by KES777** [VictoriaMetrics/VictoriaMetrics#3539]
**Describe the bug**
https://hub.docker.com/r/victoriametrics/victoria-metrics
![image](https://user-images.githubusercontent.com/799021/209470176-290198fc-8a9c-4b1c-a86c-94f48182fc57.png)

**To Reproduce**
```yml
  victoria:
    restart: unless-stopped
    image: victoriametrics/victoria-metrics
    expose:
      - "8428"
    volumes:
      - victoria-data:/victoria-metrics-data
    healthcheck:
      test: [ "CMD", "curl", "-v", "http://victoria:8428/metrics" ]
      start_period: 10s
      interval: 1m30s
      timeout: 5s
      retries: 2
```

**Expected behavior**
VM container does not have `curl`. Command should be replaced with `wget`

`wget -q -o 1 http://victoria:8428/metrics`

**Version**
```
victoria-metrics-20221220-184303-heads-public-single-node-0-g1d7b5cb83
```
