### ISSUE TITLE
Vmagent: Metrics are lost if label and value match on different targets

### ISSUE THREAD

**Issue by svesh** [VictoriaMetrics/VictoriaMetrics#355]
**Describe the bug**
Metrics are lost if label and value match on different targets in one job.

**To Reproduce**
To reproduce bug: Export simple metric from 2 or more exporters in one job:
```
# HELP dnsmasq_auth DNS queries for authoritative zones
# TYPE dnsmasq_auth gauge
dnsmasq_auth 0
```
Query VM for this metric. You'll see only one metric.

**Version**
```
vmagent-20200226-202229-tags-v1.34.1-0-g63a88a61
```

**Used command-line flags**
Not important

**Comment by valyala** [comment]
`vmagent` shouldn't merge metrics with identical labels and values, which are scraped from distinct targets, since it should add `instance` label with different values to the metric scraped from different  targets.

@svesh , could you provide the minimal `prometheus.yml` file contents, which leads to the issue?

**Comment by svesh** [comment]
My test prometheus.yml
```
global:
  scrape_interval: 15s
  scrape_timeout: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: test-job
    static_configs:
      - targets:
          - srv1:9990
          - srv2:9990
          - srv3:9990
```

**Comment by valyala** [comment]
I cannot reproduce the issue with the following steps:
1. Run local VictoriaMetrics:
```
/path/to/victoria-metrics
```

2. Create `prometheus.yml` file with the following contents:
```yml
global:
  scrape_interval: 5s

scrape_configs:
- job_name: vmagent
  static_configs:
  - targets: ['localhost:8429', '127.0.0.1:8429']
```

3. Run `vmagent` with the following args:
```
/path/to/vmagent -remoteWrite.url=http://localhost:8428/api/v1/write -promscrape.config=prometheus.yml
```

4. Wait for a while and run the following curl query:

```
curl localhost:8428/api/v1/export -d 'match[]=go_threads'
```

5. Note the output contains multiple time series with distinct `instance` values that match `targets` addresses from `prometheus.yml` config:
```
{"metric":{"__name__":"go_threads","job":"vmagent","instance":"127.0.0.1:8429"},"values":[10,10,10,10,10,10,10,10,10,10,10],"timestamps":[1583261581196,1583261586196,1583261591196,1583261596196,1583261601196,1583261606196,1583261611196,1583261616196,1583261621196,1583261626196,1583261631196]}
{"metric":{"__name__":"go_threads","job":"vmagent","instance":"localhost:8429"},"values":[10,10,10,10,10,10,10,10,10,10,10],"timestamps":[1583261582875,1583261587875,1583261592875,1583261597875,1583261602875,1583261607875,1583261612875,1583261617875,1583261622875,1583261627875,1583261632875]}
```

Could you minimize the real `prometheus.yml` file contents from production, so the issue is still reproducible, and post this config here?
