### ISSUE TITLE
vmagent scrape targets prometheus federate, metrics  up disappeared

### ISSUE THREAD

**Issue by Yifengzis** [VictoriaMetrics/VictoriaMetrics#3557]
# ./vmagent-prod -version
vmagent-20221220-225543-tags-v1.85.3-0-gf443fad56

vmagent scrape targets prometheus federate, metrics  up disappeared
for example: 
up{instance="localhost:9090", job="prometheus"}

However, it is normal to write remotely on the Prometheus Agent. [prometheus-2.41.0]

![image](https://user-images.githubusercontent.com/43021839/209825949-10a7df26-75de-4778-a63a-ae3aa8449577.png)

**Comment by dmitryk-dk** [comment]
Hi @Yifengzis ! Can you check it on `graph` tab and enable `Disable cache`?

**Comment by Yifengzis** [comment]
> Hi @Yifengzis ! Can you check it on `graph` tab and enable `Disable cache`?
vmagent scrape targets prometheus federate, metrics "up" disappeared
![image](https://user-images.githubusercontent.com/43021839/209912429-b7fb649a-ad2e-4cce-9e5d-d3d5ebd5d2ed.png)

**Comment by dmitryk-dk** [comment]
Hi @Yifengzis ! So when you disable cache you metrics become visible?

**Comment by Yifengzis** [comment]
> metrics

Metrics  is not visible.

**Comment by dmitryk-dk** [comment]
Can you check logs of the vmalert and share them if there is something wroong? Also can you export data with `api/v/1/export` with that is more than 30 minutes?

**Comment by Yifengzis** [comment]
> Can you check logs of the vmalert and share them if there is something wroong? Also can you export data with `api/v/1/export` with that is more than 30 minutes?

**I'm sorry, my English is not very good!**

####  "VMagent" remote write has the following indicators less than "PrometheusAgent"

up{instance="localhost:9100",job="node_exporter"} 0
up{instance="prometheus-server:19090",job="prometheus"} 1

#### See the following figure:
![image](https://user-images.githubusercontent.com/43021839/209959725-73ac9fdd-b56b-4634-ac21-60696ec527da.png)

**Comment by Yifengzis** [comment]
@dmitryk-dk 

The exported data and test cases have been emailed to you. Please check

#### vmagent/config/prometheus.yml 

```yaml
$ cat vmagent/config/prometheus.yml 
global:
  scrape_interval: 15s
  external_labels:
    source: vmagent

scrape_configs:
  - job_name: "federate"
    scrape_interval: 15s
    honor_labels: true
    metrics_path: "/federate"
    params:
      match[]:
        - '{__name__!=""}'
    static_configs:
      - targets:
          - prometheus-server:19090
```

#### prometheus-agent/config/prometheus.yml

```yam
$ cat prometheus-agent/config/prometheus.yml 
global:
  scrape_interval: 15s
  evaluation_interval: 15s
  external_labels:
    source: prometheus-agent

scrape_configs:
  - job_name: "federate"
    scrape_interval: 15s
    honor_labels: true
    metrics_path: "/federate"
    params:
      match[]:
        - '{__name__!=""}'
    static_configs:
      - targets:
          - prometheus-server:19090

remote_write:
  - url: http://victoriametrics:8428/api/v1/write
```

#### prometheus-server/config/prometheus.yml

```yaml
global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: "prometheus"
    static_configs:
      - targets: 
        - prometheus-server:19090

  - job_name: "node_exporter"
    static_configs:
      - targets: 
        - localhost:9100
```

#### test_docker-compose.yml

```yaml
version: '3.9'

services: 
  victoriametrics: 
    container_name: victoriametrics
    image: victoriametrics/victoria-metrics:v1.85.3
    restart: always
    hostname: victoriametrics
    command:
      - "--storageDataPath=/storage"
      - "--httpListenAddr=:8428"
    volumes:
      - /etc/localtime:/etc/localtime:ro
      #- ./victoriametrics/data:/storage
    ports:
      - 8428:8428
    networks:
      - vm_net

  vmagent:
    container_name: vmagent
    image: victoriametrics/vmagent:v1.85.3
    restart: always
    hostname: vmagent
    command:
      - "--httpListenAddr=:8429"
      - "--promscrape.config=/etc/prometheus/prometheus.yml"
      - "--remoteWrite.url=http://victoriametrics:8428/api/v1/write"
    depends_on:
      - "victoriametrics"
    volumes:
      #- ./vmagent/data:/vmagent-remotewrite-data
      - ./vmagent/config:/etc/prometheus
    ports:
      - 8429:8429
    networks:
      - vm_net

  prometheus-agent:
    container_name: prometheus-agent
    image: prom/prometheus:v2.41.0
    restart: always
    hostname: prometheus-agent
    command:
      - --web.listen-address=:9090
      - --config.file=/prometheus/config/prometheus.yml
      - --enable-feature=agent
      - --storage.agent.path=/prometheus/data-agent
    volumes:
      - /etc/localtime:/etc/localtime:ro
      #- ./prometheus-agent/data:/prometheus/data-agent
      - ./prometheus-agent/config:/prometheus/config
    ports:
      - 9090:9090
    networks:
      - vm_net

  prometheus-server: 
    container_name: prometheus-server
    image: prom/prometheus:v2.41.0
    restart: always
    hostname: prometheus-server
    command:
      - --web.listen-address=:19090
      - --config.file=/prometheus/config/prometheus.yml
      - --storage.tsdb.path=/prometheus/data
    volumes:
      - /etc/localtime:/etc/localtime:ro
      #- ./prometheus-server/data:/prometheus/data
      - ./prometheus-server/config:/prometheus/config
    ports:
      - 19090:19090
    networks:
      - vm_net

networks:
  vm_net:
```
