### ISSUE TITLE
Different metrics value between prometheus and VictoriaMetrics

### ISSUE THREAD

**Issue by anufrievIl** [VictoriaMetrics/VictoriaMetrics#3560]
**Describe the bug**
Different metric value between prometheus and VictoriaMetrics.
We have Prometheus running in 1 replica using a kubernetes operator that sends metrics via remote_write to the VictoriaMetrics cluster. The problem is only observed with 1 metric node_nf_conntrack_entries. 
Victoriametrics:
<img width="1878" alt="Screenshot 2022-12-28 at 19 36 52" src="https://user-images.githubusercontent.com/114412627/209836875-4bccfdf9-70f0-4020-889f-3c6748fe89c3.png">

Prometheus:
<img width="1886" alt="Screenshot 2022-12-28 at 19 41 00" src="https://user-images.githubusercontent.com/114412627/209836904-1b5ccfee-371b-46e4-8909-a383d7162b35.png">

**Prometheus config**
```
global:
  scrape_interval: 30s
  scrape_timeout: 10s
  evaluation_interval: 30s
remote_write:
- url: https://some_url/insert/0/prometheus/
  remote_timeout: 30s
  write_relabel_configs:
  - source_labels: [__name__]
    separator: ;
    regex: (.*)
    target_label: kubernetes
    replacement: some-kubernetes
    action: replace
  - source_labels: [__name__]
    separator: ;
    regex: (.*)
    target_label: project_name
    replacement: some-project
    action: replace
  - source_labels: [job]
    separator: ;
    regex: kubelet|custom-kong-.*|custom-otel-.*|node-exporter|custom-argocd-.*
    replacement: $1
    action: keep
  follow_redirects: true
  enable_http2: true
  queue_config:
    capacity: 2500
    max_shards: 200
    min_shards: 1
    max_samples_per_send: 500
    batch_send_deadline: 5s
    min_backoff: 30ms
    max_backoff: 5s
  metadata_config:
    send: true
    send_interval: 1m
    max_samples_per_send: 500
```

**VictoriaMetrics config**
Storage:
```
      -dedup.minScrapeInterval=30s
      -httpListenAddr=:8482
      -retentionPeriod=1
      -search.maxUniqueTimeseries=100000000
      -storageDataPath=/vm-data
      -vminsertAddr=:8400
      -vmselectAddr=:8401
```
Select:
```
      -cacheDataPath=/select-cache
      -dedup.minScrapeInterval=30s
      -httpListenAddr=:8481
      -storageNode=vmstorage-metrics-cluster-0.vmstorage-metrics-cluster.vm-cluster:8401,vmstorage-metrics-cluster-1.vmstorage-metrics-cluster.vm-cluster:8401,vmstorage-metrics-cluster-2.vmstorage-metrics-cluster.vm-cluster:8401,vmstorage-metrics-cluster-3.vmstorage-metrics-cluster.vm-cluster:8401,vmstorage-metrics-cluster-4.vmstorage-metrics-cluster.vm-cluster:8401,vmstorage-metrics-cluster-5.vmstorage-metrics-cluster.vm-cluster:8401,vmstorage-metrics-cluster-6.vmstorage-metrics-cluster.vm-cluster:8401,vmstorage-metrics-cluster-7.vmstorage-metrics-cluster.vm-cluster:8401,vmstorage-metrics-cluster-8.vmstorage-metrics-cluster.vm-cluster:8401,vmstorage-metrics-cluster-9.vmstorage-metrics-cluster.vm-cluster:8401,vmstorage-metrics-cluster-10.vmstorage-metrics-cluster.vm-cluster:8401,vmstorage-metrics-cluster-11.vmstorage-metrics-cluster.vm-cluster:8401,vmstorage-metrics-cluster-12.vmstorage-metrics-cluster.vm-cluster:8401,vmstorage-metrics-cluster-13.vmstorage-metrics-cluster.vm-cluster:8401,vmstorage-metrics-cluster-14.vmstorage-metrics-cluster.vm-cluster:8401,vmstorage-metrics-cluster-15.vmstorage-metrics-cluster.vm-cluster:8401,vmstorage-metrics-cluster-16.vmstorage-metrics-cluster.vm-cluster:8401,vmstorage-metrics-cluster-17.vmstorage-metrics-cluster.vm-cluster:8401,vmstorage-metrics-cluster-18.vmstorage-metrics-cluster.vm-cluster:8401,vmstorage-metrics-cluster-19.vmstorage-metrics-cluster.vm-cluster:8401
```

Insert:
```
      -httpListenAddr=:8480
      -replicationFactor=3
      -storageNode=vmstorage-metrics-cluster-0.vmstorage-metrics-cluster.vm-cluster:8400,vmstorage-metrics-cluster-1.vmstorage-metrics-cluster.vm-cluster:8400,vmstorage-metrics-cluster-2.vmstorage-metrics-cluster.vm-cluster:8400,vmstorage-metrics-cluster-3.vmstorage-metrics-cluster.vm-cluster:8400,vmstorage-metrics-cluster-4.vmstorage-metrics-cluster.vm-cluster:8400,vmstorage-metrics-cluster-5.vmstorage-metrics-cluster.vm-cluster:8400,vmstorage-metrics-cluster-6.vmstorage-metrics-cluster.vm-cluster:8400,vmstorage-metrics-cluster-7.vmstorage-metrics-cluster.vm-cluster:8400,vmstorage-metrics-cluster-8.vmstorage-metrics-cluster.vm-cluster:8400,vmstorage-metrics-cluster-9.vmstorage-metrics-cluster.vm-cluster:8400,vmstorage-metrics-cluster-10.vmstorage-metrics-cluster.vm-cluster:8400,vmstorage-metrics-cluster-11.vmstorage-metrics-cluster.vm-cluster:8400,vmstorage-metrics-cluster-12.vmstorage-metrics-cluster.vm-cluster:8400,vmstorage-metrics-cluster-13.vmstorage-metrics-cluster.vm-cluster:8400,vmstorage-metrics-cluster-14.vmstorage-metrics-cluster.vm-cluster:8400,vmstorage-metrics-cluster-15.vmstorage-metrics-cluster.vm-cluster:8400,vmstorage-metrics-cluster-16.vmstorage-metrics-cluster.vm-cluster:8400,vmstorage-metrics-cluster-17.vmstorage-metrics-cluster.vm-cluster:8400,vmstorage-metrics-cluster-18.vmstorage-metrics-cluster.vm-cluster:8400,vmstorage-metrics-cluster-19.vmstorage-metrics-cluster.vm-cluster:8400
```
**Logs**
There are no errors or warnings in the logs

**Version**
VictoriaMetrics - v1.85.3-cluster
Prometheus - 2.37.0
