### ISSUE TITLE
Wrong vmagent query with dockerswarm_sd_configs filters

### ISSUE THREAD

**Issue by fannyfan414** [VictoriaMetrics/VictoriaMetrics#3579]
**Describe the bug**
I use docker swarm and try to migrate to VM from Prometheus (as full replacement) with **dockerswarm_sd_configs** [filters](https://docs.victoriametrics.com/sd_configs.html#dockerswarm_sd_configs), but vmagent stop working if i specify any filters. Without filters vmagent is working, but prometheus working with filters too.

**To Reproduce**
My docker-compose.yml file
```
version: '3.8'
  vmagent:
    image: victoriametrics/vmagent:v1.85.3
    expose:
      - 8429
    volumes:
      - monitoring_vmagent_data:/vmagentdata
      - /var/run/docker.sock:/var/run/docker.sock:ro
    configs:
      - source: monitoring_prometheus_config
        target: /etc/prometheus/prometheus.yml
    command:
      - "--promscrape.config=/etc/prometheus/prometheus.yml"
      - "--promscrape.config.strictParse=false"
      - "--remoteWrite.url=http://victoriametrics:8428/api/v1/write"
    networks:
      - monitoring_network
    restart: always
```

My prometheus.yml file
```
  - job_name: 'swarm_task_exporter'
    scrape_interval: 15s
    dockerswarm_sd_configs:
      - host: unix:///var/run/docker.sock
        role: tasks
        filters:
          - name: "desired-state"
            values: ["running"]
```

**Expected behavior**
If i connect to docker container and using curl create request, everything is ok
`curl --silent -XGET --unix-socket /run/docker.sock http://localhost/services?filters%5Bdesired-state%5D%5B0%5D=running`
But vmagent generate wrong request if i specify any filters

**Logs**
`error	VictoriaMetrics/lib/promscrape/config.go:1007	skipping dockerswarm_sd_config targets for job_name "swarm_task_exporter" because of error: cannot query dockerswarm api for services: unexpected status code returned from "http:///services?filters=%7B%22desired-state%22%3A%7B%22running%22%3Atrue%7D%7D": 400; expecting 200; response body: "{\"message\":\"Invalid filter 'desired-state'\"}\n`"

The logs show that there is a request for 

> http:///services?filters=%7B%22desired-state%22%3A%7B%22running%22%3Atrue%7D%7D

If you decode the parameters, you get 'filters' like this: `{"desired-state":{"running":true}}`
The correct parameters should be 'filters': `{"desired-state": "running"}`

**Version**
Swarm 20.10.22
vmagent v1.85.3

**Comment by valyala** [comment]
This issue has been fixed too in the [v1.79.7 LTS release](https://github.com/VictoriaMetrics/VictoriaMetrics/releases/tag/v1.79.7).

**Comment by fannyfan414** [comment]
@valyala @zekker6  Only partially fixed :)

Generation of query parameters now works correctly, but the request goes to the **wrong url**
In yml file i specify role: **tasks** 
```
  - job_name: 'swarm_task_exporter'
    scrape_interval: 15s
    dockerswarm_sd_configs:
      - host: unix:///var/run/docker.sock
        role: tasks
        filters:
          - name: "desired-state"
            values: ["running"]
```

so request should go to

>  unix/**tasks**?filters=%7B%22desired-state%22%3A%5B%22running%22%5D%7D

But now vmagent create request to 

> unix/**services**?filters=%7B%22desired-state%22%3A%5B%22running%22%5D%7D

 and return error because **services** don't really have such a filter, while **tasks** [do](https://docs.docker.com/engine/api/v1.41/#tag/Task/operation/TaskList)

>error	VictoriaMetrics/lib/promscrape/config.go:1039	skipping dockerswarm_sd_config targets for job_name "swarm_task_exporter" because of error: cannot query dockerswarm api for services: unexpected status code returned from "http://unix/services?filters=%7B%22desired-state%22%3A%5B%22running%22%5D%7D": 400; expecting 200; response body: "{\"message\":\"Invalid filter 'desired-state'\"}\n"

**Comment by zekker6** [comment]
Hi @fannyfan414, thank you for the report.

This issue was related to the label discovery for the tasks and have been fixed at https://github.com/VictoriaMetrics/VictoriaMetrics/pull/3632

In the meantime, you can build vmagent from sources by using instruction [here]( https://github.com/VictoriaMetrics/VictoriaMetrics#how-to-build-from-sources)
Or use pre-built docker image: `victoriametrics/vmagent:heads-fix-dockerswarm-discovery-filters-0-gf1c98e190`

**Comment by valyala** [comment]
The bugfix has been merged in the commit 8537533beb92a72c110b3c13e84fba2b25580637 . This commit will be included in the next release.

**Comment by fannyfan414** [comment]
Hi @zekker6 , thanks for fixing, in `version victoriametrics/vmagent:heads-fix-dockerswarm-discovery-filters-0-gf1c98e190` query is correct. But I found another bug or discrepancy with prometheus on the same topic.

I have 2 nodes(servers): redis + redis_exporter on each node. And third node for monitoring.

**Redis exporter** connected to 2 dockerswarm networks - **monitoring_network** and **redis_network**.
**Vmagent** connected to 1 network - **monitoring_network**

My docker-compose.yml
```
version: '3.8'
networks:
  redis_network:
    external:
      name: redis_network
  monitoring_network:
    external:
      name: monitoring_network

services:
  redis_exporter:
    image: oliver006/redis_exporter:v1.45.0
    expose:
      - 9121
#   Hostname important for prometheus metrics
    hostname: "{{.Service.Name}}.{{.Task.Slot}}"
    restart: unless-stopped
    networks:
      - redis_network
      - monitoring_network
    deploy:
      mode: replicated
      replicas: 2
        max_replicas_per_node: 1
        constraints:
          - "node.labels.node_group==redis"
      labels:
        - metrics_port=9121
        - metrics_path=/metrics
        
  vmagent:
    image: victoriametrics/vmagent:heads-fix-dockerswarm-discovery-filters-0-gf1c98e190
    expose:
      - 8429
    volumes:
      - monitoring_vmagent_data:/vmagentdata
      - /var/run/docker.sock:/var/run/docker.sock:ro
    configs:
      - source: monitoring_prometheus_config
        target: /etc/prometheus/prometheus.yml
    command:
      - "--promscrape.config=/etc/prometheus/prometheus.yml"
      - "--promscrape.config.strictParse=false"
      - "--remoteWrite.url=http://victoriametrics:8428/api/v1/write"
    networks:
      - monitoring_network
    restart: always
    deploy:
      mode: replicated
      replicas: 1
      placement:
        max_replicas_per_node: 1
        constraints:
          - "node.labels.node_group==monitoring"
```

Since the redis_exporter container is connected to **2 networks** (monitoring_network and redis_network), it has **two different** IP addresses for each network.

Docker gives Prometheus and vmagent through dockerwarm_sd_configs **all IPs from all networks**, but they can only access containers that are on the **monitoring_network**.

Therefore, I ask prometheus and vmagent to access metrics **not by IP**, but by **hostname** = docker service name + replica index number. It can be seen here **hostname** = {{.Service.Name}}.{{.Task.Slot}} and add labels to **metrics port and path**
```
services:
  redis_exporter:
    image: oliver006/redis_exporter:v1.45.0
    expose:
      - 9121
# Specify hostname
    hostname: "{{.Service.Name}}.{{.Task.Slot}}"
    deploy:
      ....
# Add labels for scrape config
      labels:
        - metrics_port=9121
        - metrics_path=/metrics
```

Therefore I use **relabel_configs** to change **__address__**
```
  - job_name: 'swarm_task_exporter'
    scrape_interval: 15s
    dockerswarm_sd_configs:
      - host: unix:///var/run/docker.sock
        role: tasks
        filters:
          - name: "desired-state"
            values: ["running"]
          - name: "service"
            values: [
              "redis_redis_exporter"
            ]
    relabel_configs:
      # Remove port from "__address__"
      - action: replace
        target_label: __address__
        source_labels:
          - __address__
        regex: ([^:]+)(?::\d+)?
        replacement: $1
      # Generate address from swarm container as "service_name.task_slot"
      - action: replace
        target_label: swarm_container_address
        source_labels:
          - __meta_dockerswarm_service_name
          - __meta_dockerswarm_task_slot
        separator: .
      # Remove task_slot=0 for global replicates containers
      - action: replace
        target_label: swarm_container_address
        source_labels:
          - swarm_container_address
          - __address__
        regex: (.*)\.[0];(.*)
        replacement: $2
      # Replace "__address__" as "swarm_container_address"
      - action: replace
        target_label: __address__
        source_labels:
          - swarm_container_address
          - __meta_dockerswarm_service_label_metrics_port
        separator: ":"
      # Replace metrics_path as label "metrics_path"
      - action: replace
        target_label: __metrics_path__
        source_labels:
          - __meta_dockerswarm_service_label_metrics_path
        regex: (.+)
```

If I open **prometheus UI** service-discovery I see **2 active targets** with __address__="redis_exporter.2:9121" and _address__="redis_redis_exporter.1:9121"

If open **vmagent UI** service-discovery, i see swarm_task_exporter (2/6 active) - 2 up and 4 dropped and **__address__** is **not changed** after relabelling: 
• active __address__="10.0.9.229:80" and __address__="10.0.19.32:80"
• dropped __address__="10.0.19.29:80", __address__="10.0.19.32:80", __address__="10.0.9.229:80", __address__="10.0.9.230:80"

And every scrape_interval i got error in vmagent log because **__address__ is not relabeled**:
> error	VictoriaMetrics/lib/promscrape/scraper.go:364	skipping duplicate scrape target with identical labels; endpoint=http://redis_exporter.1:9121/metrics, labels={instance="my",job="swarm_task_exporter",swarm_container_address="redis_exporter.1"}; make sure service discovery and relabeling is set up properly; see also https://docs.victoriametrics.com/vmagent.html#troubleshooting; original labels for target1: {__address__="10.0.9.230:80",__meta_dockerswarm_network_id="ule7l71hf291dtzqc7e0a4jfa",__meta_dockerswarm_network_ingress="false",__meta_dockerswarm_network_internal="false",__meta_dockerswarm_network_name="monitoring_network",__meta_dockerswarm_network_scope="swarm",__meta_dockerswarm_node_availability="active",__meta_dockerswarm_node_engine_version="20.10.22",__meta_dockerswarm_node_manager_leader="false",__meta_dockerswarm_node_manager_reachability="reachable",__meta_dockerswarm_node_platform_architecture="x86_64",__meta_dockerswarm_node_platform_os="linux",__meta_dockerswarm_node_role="manager",__meta_dockerswarm_node_status="ready",__meta_dockerswarm_service_id="xxah5tpto4kjbfour35c8piif",__meta_dockerswarm_service_label_com_docker_stack_image="oliver006/redis_exporter:v1.45.0",__meta_dockerswarm_service_label_metrics_path="/metrics",__meta_dockerswarm_service_label_metrics_port="9121",__meta_dockerswarm_service_mode="replicated",__meta_dockerswarm_service_name="redis_exporter",__meta_dockerswarm_service_task_container_hostname="{{.Service.Name}}.{{.Task.Slot}}",__meta_dockerswarm_service_task_container_image="oliver006/redis_exporter:v1.45.0@sha256:b3e847f29ae66fefcaf991e2ccee04b03e57314aab14abadfc87b0eed4453e65",__meta_dockerswarm_service_updating_status="completed",__meta_dockerswarm_task_container_id="a102c38f383d2331344ba9e1254174b75bc764a4c48f81d960b4d5d41aa7b502",__meta_dockerswarm_task_desired_state="running",__meta_dockerswarm_task_id="wf6d35lcmyr30bx9zxdbx4ppj",__meta_dockerswarm_task_slot="1",__meta_dockerswarm_task_state="running",__metrics_path__="/metrics",__scheme__="http",__scrape_interval__="15s",__scrape_timeout__="10s",job="swarm_task_exporter"}; original labels for target2: {__address__="10.0.19.32:80",__meta_dockerswarm_network_id="s8w9wn2j6t8qhfyvl5v8b1ls2",__meta_dockerswarm_network_ingress="false",__meta_dockerswarm_network_internal="false",__meta_dockerswarm_network_name="redis_network",__meta_dockerswarm_network_scope="swarm",__meta_dockerswarm_node_availability="active",__meta_dockerswarm_node_engine_version="20.10.22",__meta_dockerswarm_node_manager_leader="false",__meta_dockerswarm_node_manager_reachability="reachable",__meta_dockerswarm_node_platform_architecture="x86_64",__meta_dockerswarm_node_platform_os="linux",__meta_dockerswarm_node_role="manager",__meta_dockerswarm_node_status="ready",__meta_dockerswarm_service_id="xxah5tpto4kjbfour35c8piif",__meta_dockerswarm_service_label_com_docker_stack_image="oliver006/redis_exporter:v1.45.0",__meta_dockerswarm_service_label_metrics_path="/metrics",__meta_dockerswarm_service_label_metrics_port="9121",__meta_dockerswarm_service_mode="replicated",__meta_dockerswarm_service_name="redis_exporter",__meta_dockerswarm_service_task_container_hostname="{{.Service.Name}}.{{.Task.Slot}}",__meta_dockerswarm_service_task_container_image="oliver006/redis_exporter:v1.45.0@sha256:b3e847f29ae66fefcaf991e2ccee04b03e57314aab14abadfc87b0eed4453e65",__meta_dockerswarm_service_updating_status="completed",__meta_dockerswarm_task_container_id="a102c38f383d2331344ba9e1254174b75bc764a4c48f81d960b4d5d41aa7b502",__meta_dockerswarm_task_desired_state="running",__meta_dockerswarm_task_id="wf6d35lcmyr30bx9zxdbx4ppj",__meta_dockerswarm_task_slot="1",__meta_dockerswarm_task_state="running",__metrics_path__="/metrics",__scheme__="http",__scrape_interval__="15s",__scrape_timeout__="10s",job="swarm_task_exporter"}
