### ISSUE TITLE
VMAlert getting lots of false-positive alerting rules in firing state during victoria metric upgrade

### ISSUE THREAD

**Issue by vvxxvvxx** [VictoriaMetrics/VictoriaMetrics#3603]
### Describe the bug

During our Victoria metrics upgrade from v1.85.0 to v1.85.3, we received many many alerts fired and then resolved. port-forward the vmalert pod port 8080, then check `http://localhost:8080/api/v1/alerts` during the upgrade, we see many such alerts in `firing` or `pending` state. take one for instance, we see this alert in `firing` state from vmalert `http://localhost:8080/api/v1/alerts`,  but from grafana, we zoom in to the active time `"activeAt":"2023-01-05T07:20:51.360488633Z"`, the result is empty using the same expression to query.
```
{"state":"firing","name":"OneAlertName","value":"0.24514073","labels":{"alertgroup":"rmi-c-one.alert-rules","alertname":"OneAlertName","labelone":"valueone"},"annotations":{"description":"description one."},"activeAt":"2023-01-05T07:20:51.360488633Z","id":"10228092876742993754","rule_id":"15250005940471308886","group_id":"15790235838190933201","expression":"our expression\n","source":"http://vmalert-skr-0-68b986d888-x4bbb:8080/vmalert/alert?group_id=15790235838190933201\u0026alert_id=10228092876742993754","restored":false}
```
From grafana:
![image](https://user-images.githubusercontent.com/48271609/210751114-81ee49f2-f8ad-45c3-882d-6ee80a9114a3.png)

![image](https://user-images.githubusercontent.com/48271609/210747548-e38ca7b5-a136-42e0-8816-501206cb4ac1.png)

This is the same for all those fired and soon resolved alerts. From Grafana, none of them met the condition to fire the alert, but from vmalert, we see those alerts shown up.

This issue happened during the upgrade not only from v1.85.0 to v1.85.3, but also happened during the upgrade from v1.79.3 to v1.83.1, and from v1.83.1 to v1.84.0, from v1.84.0 to 1.85.0. and these are all the upgrades we performed.
Every time of upgrade listed above, there will be many many alerts fired and then resolved soon. and after all of them got resolved (alert flood), it became quiet again.. 
We suspect some partial or wrong/inconsistent data returned by vmstorage during rolling update, can you please help further check why this happened during every time of upgrade?

### To Reproduce

Perform victoria metrics version upgrade.

### Version

this issue happened during our victoria metrics upgrade from v1.79.3 to v1.83.1, and from v1.83.1 to v1.84.0, from v1.84.0 to 1.85.0, from v1.85.0 to v1.85.3. And these are all the upgrades we performed.

**Comment by vvxxvvxx** [comment]
Hi @zekker6 , below are the args for vmalert.
```
      containers:
      - args:
        - -datasource.maxIdleConnections=600
        - -datasource.url=http://vmselect-one-ilb.onenamespace.svc:8481/select/0/prometheus
        - -evaluationInterval=60s
        - -httpListenAddr=:8080
        - -notifier.url=http://vmalertmanager-one.onenamespace.svc:9093
        - -remoteRead.url=http://vmselect-one-ilb.onenamespace.svc:8481/select/0/prometheus
        - -remoteWrite.url=http://vminsert-one.onenamespace.svc:8480/insert/0/prometheus
        - -rule="/etc/vmalert/config/vm-one-0-rulefiles-0/*.yaml"
        - -rule="/etc/vmalert/config/vm-one-0-rulefiles-1/*.yaml"
        - -rule="/etc/vmalert/config/vm-one-0-rulefiles-10/*.yaml"
        - -rule="/etc/vmalert/config/vm-one-0-rulefiles-11/*.yaml"
        - -rule="/etc/vmalert/config/vm-one-0-rulefiles-12/*.yaml"
        - -rule="/etc/vmalert/config/vm-one-0-rulefiles-13/*.yaml"
        - -rule="/etc/vmalert/config/vm-one-0-rulefiles-14/*.yaml"
        - -rule="/etc/vmalert/config/vm-one-0-rulefiles-15/*.yaml"
        - -rule="/etc/vmalert/config/vm-one-0-rulefiles-16/*.yaml"
        - -rule="/etc/vmalert/config/vm-one-0-rulefiles-17/*.yaml"
        - -rule="/etc/vmalert/config/vm-one-0-rulefiles-18/*.yaml"
        - -rule="/etc/vmalert/config/vm-one-0-rulefiles-19/*.yaml"
        - -rule="/etc/vmalert/config/vm-one-0-rulefiles-2/*.yaml"
        - -rule="/etc/vmalert/config/vm-one-0-rulefiles-20/*.yaml"
        - -rule="/etc/vmalert/config/vm-one-0-rulefiles-21/*.yaml"
        - -rule="/etc/vmalert/config/vm-one-0-rulefiles-22/*.yaml"
        - -rule="/etc/vmalert/config/vm-one-0-rulefiles-23/*.yaml"
        - -rule="/etc/vmalert/config/vm-one-0-rulefiles-24/*.yaml"
        - -rule="/etc/vmalert/config/vm-one-0-rulefiles-25/*.yaml"
        - -rule="/etc/vmalert/config/vm-one-0-rulefiles-3/*.yaml"
        - -rule="/etc/vmalert/config/vm-one-0-rulefiles-4/*.yaml"
        - -rule="/etc/vmalert/config/vm-one-0-rulefiles-5/*.yaml"
        - -rule="/etc/vmalert/config/vm-one-0-rulefiles-6/*.yaml"
        - -rule="/etc/vmalert/config/vm-one-0-rulefiles-7/*.yaml"
        - -rule="/etc/vmalert/config/vm-one-0-rulefiles-8/*.yaml"
        - -rule="/etc/vmalert/config/vm-one-0-rulefiles-9/*.yaml"
        image: victoriametrics/vmalert:v1.85.3
```
