### ISSUE TITLE
vmagent: labels from `external_labels` cannot be overwriten by `scrape_configs.labels`

### ISSUE THREAD

**Issue by Allineer** [VictoriaMetrics/VictoriaMetrics#366]
**Describe the bug**

```
VictoriaMetrics/lib/promscrape/scraper.go:61	cannot parse `static_configs` from "/dev/null/targets.yaml": error when parsing `scrape_config` #1: error when parsing `static_config` #1: cannot merge labels for `static_configs` target for `job_name` "some-job": label `"awesome": "yyy"` clashes with the previously set label with value "xxx"
```

**To Reproduce**

```
global:
  external_labels:
    awesome: foo

scrape_configs:
  - job_name: some-job
    static_configs:
      - targets: ["127.0.0.1:1111"]
        labels:
          awesome: "bar"
      - targets: ["127.0.0.1:2222"]
        labels:
          awesome: "baz"
  - job_name: another-job
    static_configs:
      - targets: ["127.0.0.1:3333", 127.0.0.1:4444"]
```

**Expected behavior**

В качестве значения метки `awesome` используются следующие значения в порядке убывания приоритета:

1. `scrape_configs.static_configs.<job>.<targets>.labels.awesome` - т.к. оно явно указано для таргета;
2. `global.external_labels.awesome` - глобальная метка же;

В моем примере, я рассчитывал получить следующие значения метки `awesome` для каждого target:

- `127.0.0.1:1111 => bar`
- `127.0.0.1:2222 => baz`
- `127.0.0.1:3333 => foo`
- `127.0.0.1:4444 => foo`

Но что-то пошло не так.

Собственно, вопрос: это так задумано, что значение метки из `external_labels` нельзя перезаписать в таргете или это таки баг?

Спасибо!

**Version**

```
vmagent-20200303-194035-tags-v1.34.2-0-g0b1e877a
```
