### ISSUE TITLE
Series limit applied at vmagent, but churn rate is high

### ISSUE THREAD

**Issue by blesswinsamuel** [VictoriaMetrics/VictoriaMetrics#3660]
### Describe the bug

When I use series limit to limit the series ingested into victoriametrics, the automatic metrics generated by vmagent shows that new series are being dropped (`scrape_series_limit_samples_dropped`), which is expected. But, checking the victoriametrics grafana dashboard, it shows a high churn rate, which suggests that even though vmagent shows the series as dropped, they are ingested into victoriametrics. I expect the samples shown by vmagent as dropped should not be ingested into victoriametrics.

I used avalanche (https://github.com/prometheus-community/avalanche) to run this test.

#### Start victoriametrics:

```bash
./victoria-metrics-prod
```

#### Start avalanche:

```bash
git clone https://github.com/prometheus-community/avalanche.git
cd avalanche
go run cmd/avalanche.go --metric-count=500 --series-count=30 --port=9101
```

#### Start vmagent with seriesLimitPerTarget setting:

scrape-config.yaml
```yaml
global:
  scrape_interval: 30s
  scrape_timeout: 10s
scrape_configs:
  - job_name: 'vmagent'
    scrape_interval: 30s
    static_configs:
      - targets:
        - 'localhost:8429'
        labels:
          pod: vmagent-pod
  - job_name: 'victoriametrics'
    scrape_interval: 30s
    static_configs:
      - targets:
        - 'localhost:8428'
        labels:
          pod: victoriametrics-pod
  - job_name: 'avalanche'
    scrape_interval: 30s
    static_configs:
      - targets:
        - 'localhost:9101'
        labels:
          pod: avalanche-pod

```

```bash
./vmagent-prod -remoteWrite.url "http://localhost:8428/api/v1/write" -promscrape.config /tmp/scrape-config.yaml -promscrape.seriesLimitPerTarget 5000 -promscrape.streamParse=true
```

### Version

```
❯ ./vmutils-darwin-amd64-v1.86.1/vmagent-prod --version
vmagent-20230111-093903-tags-v1.86.1-0-g351fc152e
```

```
❯ ./victoria-metrics-prod --version
victoria-metrics-20230111-093558-tags-v1.86.1-0-g351fc152e
```

### Logs

Not relevant to this issue.

### Screenshots

The automatic metrics generated by vmagent show that samples are being dropped (this is as expected because avalanche is generating completely new series every minute):

![image](https://user-images.githubusercontent.com/815723/212753941-b8a8ac6d-4c0b-435c-b4e9-689bae683ba3.png)

The churn rate panel in VictoriaMetrics cluster grafana dashboard is consistently high and new series over 24h is increasing:

<img width="1443" alt="image" src="https://user-images.githubusercontent.com/815723/212756181-ceb45476-5b5a-44a9-ad74-50a3a12d3e4b.png">

Here, churn rate = 250 series/sec = 250x60 series/min = 15,000 series/min
The number of series generated by Avalanche for every scrape (based on the above configuration) is 500x30=15,000 samples. The [default configuration](https://github.com/prometheus-community/avalanche/blob/fcf69f4d65ecfd7e88614270866f77a24dee7edd/cmd/avalanche.go#L40) of avalanche is to generate entirely new series every 60s. So, looking at the churn rate, none of the series is being dropped by vmagent. 

I expect the churn rate to be close to 0 here since all the new metrics emitted by avalanche should be dropped by vmagent.

### Used command-line flags

Mentioned under the "To Reproduce" section.
