### ISSUE TITLE
vmagent: support for the yaml aliases in targets and relabeling configs

### ISSUE THREAD

**Issue by Allineer** [VictoriaMetrics/VictoriaMetrics#367]
**Is your feature request related to a problem? Please describe.**

При описании scrape targets, а именно блоков `*relabel_configs`, а так же файлов конфигурации, которые указываются в параметрах `remoteWrite.relabelConfig` и `remoteWrite.urlRelabelConfig` иногда приходится использовать один и тот же блок конфигурации несколько раз. 

Например: удаление непромаркированных метрик в конце каждого блока `metric_relabel_configs` следующим образом:

```
      # drop metrics without a mark label
      - source_labels: [__keep]
        regex: true
        action: keep

      # remove the mark label itself
      - regex: __keep
        action: labeldrop
```

На самом деле, примеров может быть много и это - один из нескольких, с которыми столкнулся я.

**Describe the solution you'd like**

Первое что приходит на ум в таком случае - использовать описанный в [спецификации YAML](https://yaml.org/spec/1.2/spec.html#id2767222) подход "Alias Nodes", "Node Anchors" и описанный в [черновике спецификации](https://yaml.org/type/merge.html), но поддерживаемый многими реализациями библиотек принцип "объединения" или "наследования" блоков следующим образом:

1. Где-то в начале файла конфигурации объявляем:

```
common-block-of-something: &anchor1
      # drop metrics without a mark label
      - source_labels: [__keep]
        regex: true
        action: keep

      # remove the mark label itself
      - regex: __keep
        action: labeldrop
```

в этом примере, `&anchor1` - "метка" для содержимого блока `common-block-of-something`.

2. Отмечаем места в тексте конфигурации, куда есть смысл вставить наш блок:

```
  - job_name: some-job
    static_configs:
      - targets: ["127.0.0.1:1111"]

    metric_relabel_configs:
      ...
      <<: *anchor1
```

3. В итоге, при парcинге файла конфигурации предыдущий пример воспринимается vmagent'ом в следующем виде:

```
  - job_name: some-job
    static_configs:
      - targets: ["127.0.0.1:1111"]

    metric_relabel_configs:
      ...
      # drop metrics without a mark label
      - source_labels: [__keep]
        regex: true
        action: keep

      # remove the mark label itself
      - regex: __keep
        action: labeldrop
```

Собственно, это только одна из удобных возможностей YAML.

Проверялось и не работает на версии
```
vmagent-20200303-194035-tags-v1.34.2-0-g0b1e877a
```

**Comment by valyala** [comment]
`vmagent` uses https://github.com/go-yaml/yaml package for parsing YAML files. This package supports anchors, tags and map merging according to [these docs](https://github.com/go-yaml/yaml#compatibility). The following yaml file works as expected (i.e. adds `foo="bar"` label to all the scraped metrics) when passed to `-promscrape.config` command-line arg for `vmagent`:

```yml
global:
  scrape_interval: 5s

relabel: &anchor1
- target_label: foo
  replacement: bar

scrape_configs:
- job_name: vmagent
  relabel_configs: *anchor1
  static_configs:
  - targets:
    - localhost:8429
```

Could you provide an exact YAML example, which doesn't work as expected?

**Comment by Allineer** [comment]
@valyala,
example config:

```
example: &example
      - source_labels: [__name__]
        regex: (up|scrape_duration_seconds|scrape_samples_scraped|scrape_samples_post_metric_relabeling)
        replacement: true
        target_label: __keep

      - source_labels: [__keep]
        regex: true
        action: keep

      - regex: __keep
        action: labeldrop

global:
  scrape_interval: 60s

scrape_configs:
  - job_name: node
    static_configs:
      - targets: ["127.0.0.1:9100"]

    metric_relabel_configs:
      - source_labels: [__name__]
        regex: node_cpu_seconds_total
        replacement: true
        target_label: __keep

      - source_labels: [__name__]
        regex: ^node_load\d+$
        replacement: true
        target_label: __keep

      <<: *example
```

Expected result:

```
global:
  scrape_interval: 60s

scrape_configs:
  - job_name: node
    static_configs:
      - targets: ["127.0.0.1:9100"]

    metric_relabel_configs:
      - source_labels: [__name__]
        regex: node_cpu_seconds_total
        replacement: true
        target_label: __keep

      - source_labels: [__name__]
        regex: ^node_load\d+$
        replacement: true
        target_label: __keep

      - source_labels: [__name__]
        regex: (up|scrape_duration_seconds|scrape_samples_scraped|scrape_samples_post_metric_relabeling)
        replacement: true
        target_label: __keep

      - source_labels: [__keep]
        regex: true
        action: keep

      - regex: __keep
        action: labeldrop
```

Hm. But I see this message in logs:

```
2020-03-13T05:21:59.257Z        fatal   VictoriaMetrics/lib/promscrape/scraper.go:57    cannot read "/dev/null/targets.yaml": cannot parse Prometheus config from "/dev/null/targets.yaml": cannot unmarshal data: yaml: line 32: did not find expected '-' indicator
```

What am I doing wrong?
