### ISSUE TITLE
bug? hot reload alerting rule would not cause origin alert recover

### ISSUE THREAD

**Issue by Howie59** [VictoriaMetrics/VictoriaMetrics#3712]
### Describe the bug

i run agent keep collects metrics `test` (value is 20) and report to vm cluster, and the metrics can be queried.
and i set one alerting rule:
```
groups:
  - name: alerts
    rules:
      - alert: testMetrics1
        expr: test > 10
        labels:
          severity: page
```
this rule would cause alerts.

then i changed the expr to `test > 30` 
```
groups:
  - name: alerts
    rules:
      - alert: testMetrics1
        expr: test > 30
        labels:
          severity: page
```
and trigger vmalert hot reloading, then change reporting metrics value to 5.
the newer alert can not be firing, and the previous alert can not be recover(but previous rule is not exist)

### To Reproduce

as described.

### Version

latest

### Logs

no related log

### Additional information

promtheus related code:
https://github.com/prometheus/prometheus/blob/aeecf6854f9daa69c337ba1b406afb83bcaae4f3/rules/manager.go#L1036

use name and lables as unique key.
```
	for fi, fromRule := range from.rules {
		nameAndLabels := nameAndLabels(fromRule)
		l := ruleMap[nameAndLabels]
		ruleMap[nameAndLabels] = append(l, fi)
	}

	for i, rule := range g.rules {
		nameAndLabels := nameAndLabels(rule)
		indexes := ruleMap[nameAndLabels]
		if len(indexes) == 0 {
			continue
		}
		fi := indexes[0]
		g.seriesInPreviousEval[i] = from.seriesInPreviousEval[fi]
		ruleMap[nameAndLabels] = indexes[1:]

		ar, ok := rule.(*AlertingRule)
		if !ok {
			continue
		}
		far, ok := from.rules[fi].(*AlertingRule)
		if !ok {
			continue
		}

		for fp, a := range far.active {
			ar.active[fp] = a
		}
	}

func nameAndLabels(rule Rule) string {
	return rule.Name() + rule.Labels().String()
}
```

but in vmalert, it added expr as unique id.

https://github.com/VictoriaMetrics/VictoriaMetrics/blob/6588fcbfca35fd65fd2262bf3c0200d9f9da0b8a/app/vmalert/config/config.go#L169
