### ISSUE TITLE
vmstorage configuration to minimize storage spikes

### ISSUE THREAD

**Issue by akamensky** [VictoriaMetrics/VictoriaMetrics#3743]
We are moving away from Prometheus to clustered VM, which appears to work better in terms of horizontal scaling, performance and redundancy.

However, I noticed `vmstorage` regularly will create temporary data that consumes large amount of storage. We are still ingesting data (the first data didn't reach retention limit yet). But we already see those periodic spikes consuming double the storage for some time (graph shows single node, but it happens across all of them) :

![image](https://user-images.githubusercontent.com/985805/216186080-33f258fa-bda8-4263-a9cd-4096f0a478f9.png)

Is there anything we are missing configuration wise on vmstorage that would avoid those spikes or make them much smaller?

The concern here is that we are on physical server setup and the storage is obviously limited there, the data retention is setup based on projection of vmstorage using ~80% of total disk space, but if it will be spiking up to double, we will run out of disk space (and not clear what happens then? crash?)

The setup is: vmagent (w/ prometheus scraping configs) -> nginx -> 3x vminsert (configured to replicate to 2 nodes) -> 3x vmstorage <- 3x vmselect <- nginx <- Grafana. All this running on Docker using official images from Docker Hub.

vmstorage configuration:

```yaml
  vmstorage:
    image: "victoriametrics/vmstorage:v1.86.2-cluster"
    network_mode: "host"
    volumes:
      - "/data/vmstorage:/storage"
    command:
      - "--storageDataPath=/storage"
      - "--retentionPeriod=XXd"
      - "--dedup.minScrapeInterval=15s"
      - "--memory.allowedPercent=10"
    restart: "always"
```
