### ISSUE TITLE
Vmalert did not correctly output the description information of annotations in the modified and reloaded rules

### ISSUE THREAD

**Issue by zxlxgd** [VictoriaMetrics/VictoriaMetrics#3752]
**i have a rule like this:**
```
groups:
- interval: 1m
  name: '1621111827309125634'
  rules:
  - alert: '1621111827313319938'
    annotations:
      summary: test
      description: test ：{{$labels.instance}} test：#fh#{{printf "%.3f" .Value}}#fh#
    expr: status{xHawk_collector_id='1621109568134221826',xHawk_user_space_id='1615264993068036099'}==1.0
    for: 0m
    labels:
      collectorId: 1621109568134221826
      levelName: WARN
      silence: 5m
  tenant: '468036099'
```
When the alarm is triggered, the alarm content is normal: test ：localhost test：1.0

**When I modify the description of annotations in rule and call the reload interface, the alarm content is still the original, not the modified description information**

### Version

vmalert-20220801-082124-tags-v1.79.1-enterprise-0-gb429b90e7
