### ISSUE TITLE
VictoriaMetrics can't capture spikes.

### ISSUE THREAD

**Issue by huytran-tiki** [VictoriaMetrics/VictoriaMetrics#376]
**Describe the bug**
Hi everyone, I have a question,  I comparing 2 data source.
The left is local Prometheus and right is Remote write data source.
As you guys can see, the Victoria Metrics data source can't capture spikes like the local prometheus.
I wonder if it's remote write config from Prometheus or  Victoria Metrics config cause this ?
<img width="1379" alt="Screen Shot 2020-03-19 at 09 58 53" src="https://user-images.githubusercontent.com/45550471/77031586-9a3e9f80-69d4-11ea-93be-1dcf6c1dc170.png">

Prometheus query: 
`
sum(rate(arcturus_core_kafka_lag_time_sum[1m]) / rate(arcturus_core_kafka_lag_time_count[1m]))
`
**To Reproduce**
This is my prometheus remote write config and I'm using Victoria metrics Cluster Version.
remote_write:
```
- url: http://x.x.x.x:8480/insert/0/prometheus
  remote_timeout: 30s
  queue_config:
    capacity: 60000
    max_shards: 20
    min_shards: 1
    max_samples_per_send: 10000
    batch_send_deadline: 5s
    min_backoff: 30ms
    max_backoff: 100ms
```
**Expected behavior**

VictoriaMetrics can capture spikes like Prometheus.

**Version**
Helm Chart at 
https://github.com/VictoriaMetrics/helm-charts/tree/master/charts/victoria-metrics-cluster
[](url)
