### ISSUE TITLE
vmalert: Check rules during -dryRun

### ISSUE THREAD

**Issue by Mykyta-Kostyshen** [VictoriaMetrics/VictoriaMetrics#3801]
### Is your feature request related to a problem? Please describe

vmalert doesn't check metricsQL expressions for validity when running it against rules with `vmalert -dryRun`

### Describe the solution you'd like

Syntax checks of expressions in rules during `vmalert -dryRun` akin to how `promtool check rules` or `mimirtool rules check` do it.

**Comment by zekker6** [comment]
Hi @Mykyta-Kostyshen 
`vmalert -dryRun`  already parses expressions uses for alerts and returns an error in case of parsing failure. For example running it for the following rule:
```
      - alert: PersistentQueueIsDroppingData
        expr: notsum(increase(vm_persistentqueue_bytes_dropped_total[5m])) by (job, instance) > 0
        for: 10m
        labels:
          severity: critical
        annotations:
          dashboard: "http://localhost:3000/d/G7Z9GzMGz?viewPanel=49&var-instance={{ $labels.instance }}"
          summary: "Instance {{ $labels.instance }} is dropping data from persistent queue"
          description: "Vmagent dropped {{ $value | humanize1024 }} from persistent queue
              on instance {{ $labels.instance }} for the last 10m."
```
Produces:
```
VictoriaMetrics/app/vmalert/main.go:101    failed to parse ["./deployment/docker/alerts-*.yml"]: errors(1): invalid group "vmagent" in file "deployment/docker/alerts-vmagent.yml": invalid expression for rule "vmagent"."PersistentQueueIsDroppingData": bad prometheus expr: "notsum(increase(vm_persistentqueue_bytes_dropped_total[5m])) by (job, instance) > 0", err: unparsed data left: "by (job, instance) > 0"
```
If it doesn't work for some specific rule feel free to share it and we will check.
