### ISSUE TITLE
Victoria loses data points when receive metrics from prometheus via remote_write

### ISSUE THREAD

**Issue by thunderbird86** [VictoriaMetrics/VictoriaMetrics#3849]
### Describe the bug

I have 2 Prometheus in k8s cluster for HA. Both of them have `remote_write: federated-victoria.example.com:8480/insert/1/prometheus/`
Here is Prometheus config files
```
global:
  scrape_interval: 15s
  scrape_timeout: 10s
  evaluation_interval: 15s
  external_labels:
    datacenter: us
remote_write:
  - url: http://federated-victoria-cluster.example.com:8480/insert/01234/prometheus/
```

VMSelect and VMStorage has `dedup.minScrapeInterval: 15s`

### To Reproduce

Do a query  e.g. 

container_cpu_user_seconds_total{namespace="prometheus", container="prometheus"} with datasource 

### Version

vminsert-20230118-202834-tags-v1.86.2-cluster-0-g069042653

### Logs

Nothing in logs
VMSelect has some errors due to wrong queries or exciting the limit, not related to our query
VMInsert no erros
VMStorage has only merge messages

### Screenshots

here is query in Prometheus 
<img width="1640" alt="image" src="https://user-images.githubusercontent.com/11559172/220398722-c57fb6f2-40fe-4f25-bad7-b6c376de7d31.png">

And the same query in VM
<img width="1645" alt="image" src="https://user-images.githubusercontent.com/11559172/220398875-8c63e1bb-b203-46d9-ba76-f7356aec1276.png">

### Additional information

This issue not related only particular pod or namespace.  Here is for  container_network_receive_packets_total{namespace="foo-bar"}

<img width="1648" alt="image" src="https://user-images.githubusercontent.com/11559172/220401529-261d7d87-bf85-42e5-ae17-234287ae9696.png">

No pattern for lost datapoints not found

Cluster 3 VMInsert 3VMStorage 2VMSelect
