### ISSUE TITLE
Unexpected gaps when plotting time series in Grafana

### ISSUE THREAD

**Issue by crossoverJie** [VictoriaMetrics/VictoriaMetrics#3878]
### Describe the bug

When I use VictoriaMetrics to collect cAdvisor data, there are many metrics that intermittently lose; but when I use Prometheus to collect the same data source, there is no data loss.

### To Reproduce

```yaml
        - job_name: nodeScrape/monitoring/cadvisor-scrape/0
          scrape_interval: 15s
          scrape_timeout: 15s
          scheme: https
          bearer_token_file: /var/run/secrets/kubernetes.io/serviceaccount/token
          tls_config:
            insecure_skip_verify: true
          relabel_configs:
            - source_labels: [ __meta_kubernetes_node_name ]
              target_label: node
            - target_label: job
              replacement: monitoring/cadvisor-scrape
            - source_labels: [ __meta_kubernetes_node_name ]
              separator: ;
              target_label: __address__
              regex: (.*)
              replacement: kubernetes.default.svc:443
              action: replace
            - source_labels: [ __meta_kubernetes_node_name ]
              separator: ;
              target_label: __metrics_path__
              regex: (.+)
              replacement: /api/v1/nodes/${1}/proxy/metrics/cadvisor
              action: replace
            - regex: eks_tke_cloud_*
              action: labeldrop
            - regex: kube_node_labels
              action: drop_metrics
          kubernetes_sd_configs:
            - role: node
              kubeconfig_file: ""
```

Start VictoriaMetrics and wait for about 2~5 minutes, check the data and find different degrees of loss.

### Version

victoria-metrics-20230224-083626-heads-master-0-gc080443fe-dirty-273ebc97

> Any version, including the latest master branch.

### Logs

No errors or warnings in the logs.

### Screenshots

<img width="2218" alt="image" src="https://user-images.githubusercontent.com/15684156/221612048-a29a9db6-6235-424e-b7f6-850c1af00909.png">

<img width="2219" alt="image" src="https://user-images.githubusercontent.com/15684156/221612516-c92e4942-e941-40c4-9bb1-8e6c35b452b6.png">
<img width="2462" alt="image" src="https://user-images.githubusercontent.com/15684156/221612856-969d056b-dae3-41b1-ba53-1bfa3ef68020.png">

### Used command-line flags

`--retentionPeriod=3d  -promscrape.config=scrape.yml --envflag.enable=true --envflag.prefix=VM_ --loggerFormat=json`

### Additional information

Currently, only `cAdvisor` data has been found to be lost, and the Metrics data exposed by Java applications themselves have not been lost.
