### ISSUE TITLE
Add relabel waring log

### ISSUE THREAD

**Issue by crossoverJie** [VictoriaMetrics/VictoriaMetrics#3945]
### Is your feature request related to a problem? Please describe

```yaml
relabel_configs:
  - source_labels: [ __name__ ]
    regex: 'istio_request_bytes_sum'
    action: drop
```
This is an invalid configuration. Everything is normal after modifying it according to the documentation, but for developers who are not familiar with `metric_relabel_configs` and `relabel_configs`, it may take a lot of time to troubleshoot.

```yaml
metric_relabel_configs:
  - source_labels: [ __name__ ]
    regex: 'istio_request_bytes_sum'
    action: drop
```

### Describe the solution you'd like

When the relabel configuration is invalid, I hope there are some warning logs to facilitate troubleshooting.

https://github.com/VictoriaMetrics/VictoriaMetrics/blob/c0c3dc02cf856a3050889a15535b5a8b96700694/lib/promrelabel/relabel.go#L319-L336

When applying the `relabel_configs` configuration, if `drop` is equal to false, log relevant warning messages.

At the same time, provide relevant suggestions, such as switching to `metric_relabel_configs` configuration.
