### ISSUE TITLE
How use proxy_url with environment variable

### ISSUE THREAD

**Issue by adelbot** [VictoriaMetrics/VictoriaMetrics#3999]
### Is your question request related to a specific component?

vmagent

### Describe the question in detail

Hi,

I use this config :

proxy_url: https://%{PROXY}

So, PROXY is the variable with the url of proxy.

It’s ok with the first LTS version.
But i have a syntax error with the last LTS.

is it a regression ?
how use environment variable for proxu_url in yaml config ?

Tks

### Troubleshooting docs

- [X] General - https://docs.victoriametrics.com/Troubleshooting.html
- [X] vmagent - https://docs.victoriametrics.com/vmagent.html#troubleshooting
- [ ] vmalert - https://docs.victoriametrics.com/vmalert.html#troubleshooting

**Comment by Amper** [comment]
@adelbot What kind of error did you get?

I've checked that config with the last version of VM:

```yaml
scrape_configs:
  - job_name: test
    proxy_url: http://%{PROXY}
    static_configs:
      - targets:
          - foo.bar.com
          - bar.baz.com
```

and it's work.
