### ISSUE TITLE
"<no value>" after templating

### ISSUE THREAD

**Issue by Z9n2JktHlZDmlhSvqc9X2MmL3BwQG7tk** [VictoriaMetrics/VictoriaMetrics#4012]
### Is your feature request related to a problem? Please describe

When I use label name that does not exist in the expression result I get `<no value>` label value in alert.

Test alerting rule
```yaml
groups:
  - name: test
    rules:
      - alert: qqq
        expr: 1
        labels:
          alert: problem_only
          host: '{{ $labels.host }}'
#          host_display: '{{ if ne $labels.host "" }}{{ $labels.host }}{{ else }}label host is empty{{ end }}'
          host_display: '{{ if and (ne $labels.host "") (ne $labels.host nil) }}{{ $labels.host }}{{ else }}label host is empty{{ end }}'
        annotations:
          problem: 'just a test'
```

![image](https://user-images.githubusercontent.com/22332263/227735258-b8e5701c-06a9-41f6-813a-3be916d8188d.png)

Prometheus was converting `nil` to an empty string, so I could use `if ne $labels.host ""`, but now I need to add an extra `nil` check to all affected alerting rules. It is not so convenient. And what's more, it's not so obvious to check label value against `nil` (first I tried to check `if ne $labels.host "<no value>"`).

### Describe the solution you'd like

Propose to convert non-existent label values to an empty string.
What do you think ?

### Additional information

Version: victoria-metrics-20221126-045002-tags-v1.84.0-0-gad105147d
Type: single node
