### ISSUE TITLE
Grafana Compact URL Deprecation

### ISSUE THREAD

**Issue by pgassmann** [VictoriaMetrics/VictoriaMetrics#4019]
### Describe the bug

with the current external.alert.source from the docs, grafana returns a deprecation warning.

> **Compact URL Deprecation Notice**
> The URL that brought you here was a compact URL - this format will soon be deprecated. Please replace the URL previously saved with the URL available now.
* Upstream [Grafana Deprecation issue](https://github.com/grafana/grafana/pull/44385)
* Upstream [Removal Issue](https://github.com/grafana/grafana/pull/49350) (just merged)

vmalert Documentation: https://github.com/hatemosphere/VictoriaMetrics/blob/master/app/vmalert/README.md :

> For example, link to Grafana: `-external.alert.source='explore?orgId=1&left=["now-1h","now","VictoriaMetrics",{"expr":{{$expr|jsonEscape|queryEscape}} },{"mode":"Metrics"},{"ui":[true,true,true,"none"]}]'`

Correct URL with the new key-value format:
`-external.alert.source=explore?orgId=1&left={"datasource":"VictoraMetrics","queries":[{"expr":{{.Expr|jsonEscape|queryEscape}},"refId":"A"}],"range":{"from":"now-24h","to":"now"}}`

also using `.Expr` instead of `$expr`, which is safe to use in docker-compose (`$expr` is interpolated)

The url is also configured in [docker-compose.yml](https://github.com/VictoriaMetrics/VictoriaMetrics/blob/master/deployment/docker/docker-compose.yml)

### To Reproduce

* configure vmalert with the example from the documentation
* click on Source link in Alertmanager
* See Deprecation warning

![grafik](https://user-images.githubusercontent.com/460192/227988050-3f66557c-3f76-4a5f-bfef-5572f42d1a2e.png)

### Version

/vmalert-prod --version
vmalert-20230228-020104-tags-v1.88.1-0-g95e117342

### Used command-line flags

from docker-compose.yml:

```
  vmalert:
    container_name: vmalert
    image: victoriametrics/vmalert:v1.88.1
    depends_on:
      - "victoriametrics"
      # - "alertmanager"
    expose:
      - 8880
    ports:
      - 127.0.0.3:8880:8880
    volumes:
      - type: bind
        source: ./rules
        target: /etc/alerts
        read_only: true
    command:
      - '-http.pathPrefix=/vmalert'
      - '-datasource.url=http://victoriametrics:8428/'
      - '-remoteRead.url=http://victoriametrics:8428/'
      - '-remoteWrite.url=http://victoriametrics:8428/'
      - '-evaluationInterval=1m'
      - '-notifier.url=https://alertmanager.example.com:443/'
      - '-notifier.basicAuth.username=vmalert'
      - '-notifier.basicAuth.password=asdf'
      - '-rule=/etc/alerts/*.yml'
      # display source of alerts in grafana
      - '-external.url=https://grafana.example.com'
      # deprecated
      # - '-external.alert.source=explore?orgId=1&left=["now-1h","now","VictoriaMetrics",{"expr":"{{$$expr|quotesEscape|crlfEscape|pathEscape}}"}]'
      # fixed:
      - '-external.alert.source=explore?orgId=1&left={"datasource":"VictoriaMetrics","queries":[{"expr":{{.Expr|jsonEscape|queryEscape}},"refId":"A"}],"range":{"from":"now-24h","to":"now"}}'
      - '-external.label=alertsource=VictoriaMetrics'
    networks:
      - vm_net
    restart: always
```
