### ISSUE TITLE
VMUI returns "Unexpected token" error in VM cluster v1.83.1

### ISSUE THREAD

**Issue by marksugar** [VictoriaMetrics/VictoriaMetrics#4026]
### Is your question request related to a specific component?

vmselect:v1.83.1-cluster

### Describe the question in detail

I manually installed the cluster with the following component versions:
```
vmselect:v1.83.1-cluster
vminsert:v1.83.1-cluster
vmstorage:v1.84.0-cluster
vmagent:v1.84.0
```

Three vmstorage units are deployed in the node in docker-compose respectively

use  grafana dashboard work properly

ingress is configured on vmselect:v1.83.1-cluster.   The page is VMUI

vmselect:v1.83.1-cluster. Some configurations are as follows

```
.................
        app: vmselect
    spec:
      containers:
      - args:
        - --cacheDataPath=/cache
        - --dedup.minScrapeInterval=1ms
        - --httpListenAddr=:8481
        - --envflag.enable=true
        - --envflag.prefix=VM_
        - --loggerFormat=json
        - --storageNode="192.168.15.136:8401"
        - --storageNode="192.168.15.156:8401"
        - --storageNode="192.168.15.137:8401"
        - --vmalert.proxyURL=http://vmalert:8080
        image: victoriametrics/vmselect:v1.83.1-cluster
        imagePullPolicy: IfNotPresent
        livenessProbe:
          failureThreshold: 10
          httpGet:
            path: /health
            port: 8481
            scheme: HTTP
          periodSeconds: 5
............
```
http://vm.domain.com/select/0/vmui/  Unable to query Page prompt：
```
SyntaxError: Unexpected token '<', "
is not valid JSON
```

Am I missing something? How should I configure it

thanks
<img width="719" alt="20230328172413" src="https://user-images.githubusercontent.com/21120630/228192819-2976c147-7cb6-4566-8917-a15336609cf9.png">

### Troubleshooting docs

- [ ] General - https://docs.victoriametrics.com/Troubleshooting.html
- [ ] vmagent - https://docs.victoriametrics.com/vmagent.html#troubleshooting
- [ ] vmalert - https://docs.victoriametrics.com/vmalert.html#troubleshooting

**Comment by hagen1778** [comment]
Hello! Does "Custom panel" tab returns you an error as well?
Can you check your browser NetworkTab to see what exactly VMUI gets in response when the error occurs?
Out of curiosity, I just tried running [cluster env](https://github.com/VictoriaMetrics/VictoriaMetrics/blob/master/deployment/docker/docker-compose-cluster.yml) with 1.83.1 tag and it works as expected.

**Comment by marksugar** [comment]
> Hello! Does "Custom panel" tab returns you an error as well? Can you check your browser NetworkTab to see what exactly VMUI gets in response when the error occurs? Out of curiosity, I just tried running [cluster env](https://github.com/VictoriaMetrics/VictoriaMetrics/blob/master/deployment/docker/docker-compose-cluster.yml) with 1.83.1 tag and it works as expected.


@hagen1778  hello 
When I use F12 ： http://vm.domain.com/select/0/prometheus/api/v1/label/__name__/values 404

default server URL:  http://vm.domain.com/select/0/prometheus

**Comment by hagen1778** [comment]
> ingress is configured on vmselect:v1.83.1-cluster. The page is VMUI

Could you please show your ingress config?

**Comment by marksugar** [comment]
> > ingress is configured on vmselect:v1.83.1-cluster. The page is VMUI
> 
> Could you please show your ingress config?

ingress-nginx is associated with select pod
```
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: vmselect-ui
  namespace: vm-mon
spec:
  ingressClassName: nginx
  rules:
  - host: vm.monitor.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: vmselect
            port:
              number: 8481
```

just tried to create a new vmselect-ui pod with the following configuration
```
    spec:
      containers:
      - args:
        - --dedup.minScrapeInterval=1ms
        - --httpListenAddr=:8481
        - --envflag.enable=true
        - --envflag.prefix=VM_
        - --loggerFormat=json
        - --storageNode="192.168.15.136:8401"
        - --storageNode="192.168.15.156:8401"
        - --storageNode="192.168.15.137:8401"
        - --selectNode="vmselect:8481"
        image: victoriametrics/vmselect:v1.83.1-cluster
        imagePullPolicy: IfNotPresent

```
Added '--selectNode="vmselect:8481" to my configuration and selectNode doesn't work properly when pointing to itself.

I created the same vmselect and renamed vmselect-UI, with --selectNode pointing to vmselect:8481

It's ok now

thank you  @hagen1778
