### ISSUE TITLE
Can you please provide information on Victoria metrics component similar to " Prometheus Adapter "

### ISSUE THREAD

**Issue by HalaharviPedda** [VictoriaMetrics/VictoriaMetrics#4028]
### Is your question request related to a specific component?

I am looking for similar component like "Prometheus Adapter " to make metrics available to K8s custom metrics API.
Or please provide any alternative way using Victoria Metrics to make custom metrics available to k8s custom metric API.

Need this information to create/configure "Custom Metrics Pipeline" using Victoria Metrics (Similar to https://github.com/intel/platform-aware-scheduling/blob/master/telemetry-aware-scheduling/docs/custom-metrics.md )

### Describe the question in detail

I am looking for similar component like "Prometheus Adapter " to make metrics available to K8s custom metrics API.
Or please provide any alternative way using Victoria Metrics to make customer metrics available to k8s custom metric API.

Need this information to create/configure "Custom Metrics Pipeline" using Victoria Metrics (Similar to https://github.com/intel/platform-aware-scheduling/blob/master/telemetry-aware-scheduling/docs/custom-metrics.md )

**Comment by hagen1778** [comment]
Hello!

VictoriaMetrics doesn't provide component similar to "Prometheus Adapter".
But, according to https://github.com/kubernetes-sigs/prometheus-adapter/blob/master/docs/walkthrough.md
you can use original "Prometheus Adapter". The project Readme states that Adapter communicates with Prometheus via API. Since VM is compliant with Prometheus API - Adapter will be able to communicate with it as just as it was communicating with Prometheus.

**Comment by b-a-t** [comment]
IMHO there is no need for any additional VM adaptor, as the original one just utilizes Prometheus-like queries to get appropriate triggers.

You can(almost) safely use VM, specifying the querying endpoint of it in the appropriate parameter:
```yaml
# Example from: https://webera.blog/how-to-scale-gitlab-runners-into-kubernetes-using-hpa-based-on-external-metrics-throughout-16adfd996f08
# https://github.com/helm/charts/blob/master/stable/prometheus-adapter/values.yaml
prometheus-adapter:
  # Url to access prometheus
  prometheus:
    url: http://vmsingle-vm-stack.monitoring.svc.cluster.local
    port: 8429
    path: /
  rules:
    default: false
    custom: []
    # Mounts a configMap with pre-generated rules for use. Overrides the
    # default, custom, external and resource entries
    existing:
    external:
      # External metric for Gitlab Runner: Devops Group
      - seriesQuery: 'gitlab_runner_jobs{job="gitlab-runner/gitlab-runner"}'
        resources:
          template: <<.Resource>>
        name:
          matches: "gitlab_runner_jobs"
          as: "gitlab_runner_jobs"
        metricsQuery: sum(gitlab_runner_jobs{job="gitlab-runner/gitlab-runner"})
```
