### ISSUE TITLE
Grow small parts & huge IO 

### ISSUE THREAD

**Issue by nevlkv** [VictoriaMetrics/VictoriaMetrics#4046]
### Describe the bug

vm 1.89.1

On one of the instance vmstorage started grow small parts, and huge IO on node

![image](https://user-images.githubusercontent.com/46656585/229032614-96681f16-0170-446f-b9fd-9721b399bc3f.png)

small merges  
![image](https://user-images.githubusercontent.com/46656585/229033070-3ba3cf30-dc2b-4b94-b11c-4e38643a32c0.png)

![image](https://user-images.githubusercontent.com/46656585/229032787-7b4a988a-062d-4fd3-a343-84be729ae9cf.png)

Restart pod resolve

### To Reproduce

restart problem pod

### Version

1.89.1

**Comment by nevlkv** [comment]
30 min after restart

![image](https://user-images.githubusercontent.com/46656585/229033843-96133faa-d078-427b-ac87-e0d6a1e47de1.png)

![image](https://user-images.githubusercontent.com/46656585/229034027-86f5f2c7-9f31-4355-9b4c-16c4534a0328.png)

slow selects

![image](https://user-images.githubusercontent.com/46656585/229034310-c75ea009-12b1-4fac-acf5-5c94b3c39d4b.png)

**Comment by nevlkv** [comment]
same state 
![image](https://user-images.githubusercontent.com/46656585/229068661-f73935e1-5e9c-4fc5-9cd4-3bfc82b54005.png)
file:///tmp/prof.tgz

**Comment by nevlkv** [comment]
12h

slow queries stoped when disable vmselect  in balancer 

![image](https://user-images.githubusercontent.com/46656585/229090919-187ac4a1-ddc0-43aa-a132-d8a8b016e8a3.png)
![image](https://user-images.githubusercontent.com/46656585/229091081-26d5fd07-9d9e-4dfd-8539-9ab207f263dd.png)

**Comment by nevlkv** [comment]
logs:
```
{"ts":"2023-03-31T09:42:45.804Z","level":"info","caller":"VictoriaMetrics/lib/storage/partition.go:1302","msg":"starting final dedup for partition /storage/data/big/2023_02 using requiredDedupInterval=300000 ms, since the partition has smaller actualDedupInterval=15000 ms"}

```

and again

same node

![image](https://user-images.githubusercontent.com/46656585/229121304-0582adef-7902-4b47-aca1-c477ad17a293.png)

**Comment by nevlkv** [comment]
Pods on failed storage node could not finish downsampling, another pods works fine

![изображение](https://user-images.githubusercontent.com/46656585/229209567-2301a63c-dad3-43ac-96d5-0a24cbafae3d.png)

**Comment by nevlkv** [comment]
vmstorage args

```
      containers:
      - args:
        - --retentionPeriod=16w
        - --storageDataPath=/storage
        - --bigMergeConcurrency=2
        - --downsampling.period=7d:15s,30d:5m,180d:1h
        - --envflag.enable=true
        - --envflag.prefix=VM_
        - --eula=true
        - --loggerFormat=json
        - --retentionFilter={namespace=~"(any-prod|any-dev)"}:7d
        - --search.maxUniqueTimeseries=5000000
        image: victoriametrics/vmstorage:v1.89.1-enterprise-cluster
        ```
