### ISSUE TITLE
Stream aggregation type last, does not modify timestamp like other aggregation types

### ISSUE THREAD

**Issue by ihard** [VictoriaMetrics/VictoriaMetrics#4077]
### Describe the bug

When sending graphite metrics and using last type aggregation, the timestamp remains unchanged
it is expected to be aligned to the specified time interval

### To Reproduce

```
echo "server.info.test 1 $(date +%s)" | nc -w 1 127.0.0.1 2003 
curl -s http://127.0.0.1:8481/select/0/prometheus/api/v1/export -d 'match[]={__name__="server.info.test"}' |  json_pp
{
   "metric" : {
      "__name__" : "server.info.test"
   },
   "timestamps" : [
      1680691161000,
      1680691461000,
      1680691523000,
   ],
   "values" : [
      1,
      1,
      1
   ]
}
```

```
cat docker-compose.yml
---

version: "3.7"
services:
  vmagent:
    container_name: vmagent
    image: 'victoriametrics/vmagent:v1.89.1'
    network_mode: host
    restart: always
    user: 'nobody'
    volumes:
      - './stream-60s.yml:/etc/vmagent/stream-60s.yml:ro'
    command:
      - '--graphiteListenAddr=:2003'
      - '--httpListenAddr=:8429'
      - '--remoteWrite.url=http://127.0.0.1:9586/insert/multitenant/prometheus'
      - '--remoteWrite.streamAggr.config=/etc/vmagent/stream-60s.yml'
```

```
- interval: 1m
  outputs: [last]
  output_relabel_configs:
    - source_labels: [ __name__ ]
      target_label: __name__
      regex: "(.+):.+"
```

### Version

vmagent:v1.89.1

### Used command-line flags

      - '--graphiteListenAddr=:2003'
      - '--httpListenAddr=:8429'
      - '--remoteWrite.url=http://127.0.0.1:9586/insert/multitenant/prometheus'
      - '--remoteWrite.streamAggr.config=/etc/vmagent/stream-60s.yml'
