### ISSUE TITLE
vmauth: add ability to proxy requests for unauthorized users

### ISSUE THREAD

**Issue by valyala** [VictoriaMetrics/VictoriaMetrics#4083]
### Is your feature request related to a problem? Please describe

Currently [vmauth](https://docs.victoriametrics.com/vmauth.html) allows proxying requests only for authorized users. Sometimes it is needed to provide access to VictoriaMetrics components without authorization. For example, if the authorization is performed by some additional auth proxy sitting in front of `vmauth`, or if VictoriaMetrics playground should be exposed to unauthorized users in the Internet.

### Describe the solution you'd like

It would be great if `vmauth` could provide the ability to configure access to VictoriaMetrics components for unauthorized users.

For example, if a separate `unauthorized_user` section is provided in the file pointed by `-auth.config` with the contents similar to a single `users` section, then `vmauth` could proxy unauthorized requests according to the provided `unauthorized_user` section:

```yml
unauthorized_user:
  url_map:
  - src_paths:
    - /api/v1/query
    - /api/v1/query_range
    url_prefix:
    - http://vmselect1:8481/select/0/prometheus
    - http://vmselect2:8481/select/0/prometheus
  - src_paths:
    - /api/v1/write
    url_prefix:
    - http://vminsert1:8480/insert/0/prometheus
    - http://vminsert2:8480/insert/0/prometheus
```

### Describe alternatives you've considered

An alternative is to use `nginx` or similar service for proxying and load-balancing unauthorized requests among VictoriaMetrics serivces.
