### ISSUE TITLE
Missing targets with kubernetes_sd_configs

### ISSUE THREAD

**Issue by thunderbird86** [VictoriaMetrics/VictoriaMetrics#4087]
### Describe the bug

I've scrape rule for prometheus 

```
- job_name: somejob
  scheme: https
  tls_config:
    insecure_skip_verify: true
  kubernetes_sd_configs:
    - role: endpoints
  relabel_configs:
  - source_labels: [__meta_kubernetes_endpoints_name]
    action: keep
    regex: '^foobar.*'
  - source_labels: [__meta_kubernetes_endpoint_port_name]
    action: keep
    regex: http-control
```

##Here is result in prometheus 

[somejob (5/5 up)]

```
https://10.11.69.84:3801/metrics | UP | instance="10.11.69.84:3801"job="somejob" | 10.151s ago | 3.018ms |  
https://10.21.191.179:3801/metrics | UP | instance="10.21.191.179:3801"job="somejob" | 8.37s ago | 6.964ms |  
https://10.11.69.104:3801/metrics | UP | instance="10.11.69.104:3801"job="somejob" | 14.702s ago | 2.492ms |  
https://10.11.69.75:3801/metrics | UP | instance="10.11.69.75:3801"job="somejob" | 11.23s ago | 2.756ms |  
https://10.21.191.172:3801/metrics | UP | instance="10.21.191.172:3801"job="somejob" | 2.946s ago | 137.937ms
```

##And here is vmagent 

[somejob (2/2 up)]
```
https://10.11.69.104:3801/metrics (response)	UP	{instance="10.11.69.104:5001", job="somejob"} target metrics	29	0	12251ms ago	3ms	159	
https://10.21.191.172:3801/metrics (response)	UP	{instance="10.21.191.172:5001", job="somejob"} target metrics	29	0	2542ms ago	4ms	159	
```
##And here is pod in K8s 

```
kubectl -n my_ns  get po  -o wide | grep foobar
foobar-557b9fdc68-rkps9                    1/1     Running   0          30h     10.11.69.84    
foobar-557b9fdc68-vl454                    1/1     Running   0          30h     10.21.191.179  
foobar-barfoo-57234b8bd9-2cxxh             1/1     Running   0          21d     10.11.69.75    
foobar-barfoo-57234b8bd9-9xwc9             1/1     Running   0          21d     10.11.69.104    
foobar-barfoo-57234b8bd9-pltwv             1/1     Running   0          21d     10.21.191.172  
```

There was the error in logs 

`skipping duplicate scrape target with identical labels` for following pods

skipping duplicate scrape target with identical labels; endpoint=https://10.11.69.84:3801/metrics
skipping duplicate scrape target with identical labels; endpoint=https://10.21.191.179:3801/metrics
skipping duplicate scrape target with identical labels; endpoint=https://10.11.69.75:3801/metrics
skipping duplicate scrape target with identical labels; endpoint=https://10.27.49.136:3801/metrics

### To Reproduce

Not all targets has this issue. 

### Version

vmagent-20230326-001857-tags-v1.87.4-0-g87769b36d

### Used command-line flags

  - -remoteWrite.tmpDataPath=/tmpData
  - -promscrape.config=/etc/config/scrape.yaml
  - -promscrape.cluster.membersCount=2
  - -promscrape.cluster.replicationFactor=1
  - -promscrape.cluster.memberNum=$(POD_NAME)
  - -envflag.enable=true
  - -envflag.prefix=VM_
  - -loggerFormat=json
