### ISSUE TITLE
VMoperator not able to detect vmstaticscrape.

### ISSUE THREAD

**Issue by Aditya1523** [VictoriaMetrics/VictoriaMetrics#4090]
### Is your question request related to a specific component?

VMStaticScrape

### Describe the question in detail

I am getting node-exporter metrics inside a virtual machine (port: 9100) and I want to create a dashboard in Grafana through that metrics. So I am using private IP as a target to get those metrics by using VMStaticScrape, but not able to do so.
I am attaching yaml file as a reference:
```
apiVersion: operator.victoriametrics.com/v1beta1
kind: VMStaticScrape
metadata:
  name: node-exp
  namespace: monitor
spec:
  jobName: node-exp
  targetEndpoints:
    - path: /metrics
      port: '9100'
      targets:
        - 10.20.110.222 
```
What can be modified in this yaml?
FYI: static scrape is created 
![image](https://user-images.githubusercontent.com/113169558/230565858-54ea863e-8a57-48a5-af35-3c2b699edaff.png)

Vmoperator is logging that there are no static scrapes
`{"level":"info","ts":1680843117.1032467,"logger":"factory","msg":"selected StaticScrapes","staticScrapes":"","namespace":"monitoring-system","vmagent":"vmagent"}`

### Troubleshooting docs

- [ ] General - https://docs.victoriametrics.com/Troubleshooting.html
- [ ] vmagent - https://docs.victoriametrics.com/vmagent.html#troubleshooting
- [ ] vmalert - https://docs.victoriametrics.com/vmalert.html#troubleshooting

**Comment by f41gh7** [comment]
Hello, it's likely that `VMAgent` doesn't have proper selector config.

 Make sure, that it's configured via two options:
1) selectAllByDefault: true
```yaml
kind: VMAgent
spec:
 selectAllBydefault: true
```
2) staticScrapeSelector and staticScrapeNamespaceSelector
```yaml
kind: VMAgent
spec:
  staticScrapeNamespaceSelector: {}
  staticScrapeSelector: []
```

related doc https://docs.victoriametrics.com/operator/quick-start.html#object-selectors
