### ISSUE TITLE
Vmagent: Pass get parameters from ingestion url to remotewrite url

### ISSUE THREAD

**Issue by proffust** [VictoriaMetrics/VictoriaMetrics#4096]
### Is your feature request related to a problem? Please describe

Write metrics to different kafka topics

### Describe the solution you'd like

pass get parameters from metrics record url to parameters for remote write url

For example I write metrics to vmagent over influx protocol with url http://vmagent/write?db=test
I want write this metrics to influx_test topic, metrics written over remote write protocol with url http://vmagent/api/v1/write?db=test1 to kafka topic promremotewrite_test1
I think, good realisation is remotewriteTemplated parameters, when I can use get parameters from ingestion url by name and protocol name
For my example is remoteWriteTemplated.url=kafka://localhost:9092/?topic={proto}_{db}

**Comment by f41gh7** [comment]
It requires significant changes at `vmagent` data model. Currently collected metric blocks grouped by remoteWrite url and send via batches. Templated url parameters requires grouping batches by some attributes. It makes complicated storing and sending metric blocks.


 As alternative solution, I could suggest label based routing. It's simple and powerful approach for metrics routing. You have to create remoteWrite url per exist db variable:
`--remoteWrite.url=kafka://localhost:9092/?topic=metrics_db1,kafka://localhost:9092/?topic=metrics_db2,kafka://localhost:9092/?topic=metrics_db3`

 And attach routing rule for it 
```yaml
# relabel_config_db1.yaml
- action: keep
  source_labels: [db]
  regex: "^db1$"
- action: labeldrop
    regex: "db"
# relabel_config_db2.yaml
- action: keep
  source_labels: [db]
  regex: "^db2$"
- action: labeldrop
    regex: "db"
# relabel_config_db2.yaml
- action: keep
  source_labels: [db]
  regex: "^db3$"
- action: labeldrop
    regex: "db"
```
 And pass it to as args for `vmagent`: `--remoteWrite.urlRelabelConfig=relabel_config_db1.yaml,relabel_config_db2.yaml,relabel_config_db3.yaml`


 At producer add database as label for routing: `http://vmagent/write?extra_label=db=db1`
