### ISSUE TITLE
Write-only user with vmauth not working

### ISSUE THREAD

**Issue by reactpro** [VictoriaMetrics/VictoriaMetrics#4108]
### Is your question request related to a specific component?

VictoriaMetrics single-node, vmauth

### Describe the question in detail

Hi, i'm trying to create write-only user for **VictoriaMetrics** single-node with **vmauth**. 

**vmauth config:**
(VM_USER for full access, VM_WRITE_USER for write-only access)
```
users:
- username: '%{VM_USER}'
  password: '%{VM_PASSWORD}'
  url_prefix: "http://victoria-metrics-server:8428"
- username: '${VM_WRITE_USER}'
  password: '${VM_WRITE_PASSWORD}'
  url_map:
  - src_paths: ["/api/v1/write"]
    url_prefix: "http://victoria-metrics-server:8428"
```
After that I try to send data from **vmagent** with VM_WRITE_* basic auth credentials, and I get an error `cannot find the provided auth token \"Basic ***\" in config`. 

How can i fix this? Or multiple users with different permissions properly works only in cluster version(write to insert node, read from select node)?

### Troubleshooting docs

- [X] General - https://docs.victoriametrics.com/Troubleshooting.html
- [X] vmagent - https://docs.victoriametrics.com/vmagent.html#troubleshooting
- [X] vmalert - https://docs.victoriametrics.com/vmalert.html#troubleshooting
