### ISSUE TITLE
Performance issues in 1.90.0

### ISSUE THREAD

**Issue by akamensky** [VictoriaMetrics/VictoriaMetrics#4113]
### Describe the bug

When upgrading from 1.89.1 to 1.90.0 there is very big hit on VM cluster.

Upgrade was done by simply updating docker images, no configuration/flags were changed.

Runtime flags:

- vmstorage `--storageDataPath=/storage --retentionPeriod=90d --dedup.minScrapeInterval=15s`
- vmselect `--storageNode=redacted01:8401 --storageNode=redacted02:8401 --storageNode=redacted03:8401 --dedup.minScrapeInterval=15s`

The symptoms:

- Queries are timing out
- vmstorage log entries `2023-04-11T02:08:02.179Z	error	VictoriaMetrics/lib/vmselectapi/server.go:214	cannot process vmselect conn 10.2.43.236:60804: cannot process vmselect request: cannot execute "search_v7": search error: error when searching for tagFilters=[{AccountID=0,ProjectID=0,__name__="kafka_controller_kafkacontroller_activecontrollercount",service="kafka"}] on the time range [2023-04-11T01:54:00Z..2023-04-11T02:04:00Z]: deadline exceeded`
- vmstorage log entries `2023-04-11T02:09:43.464Z	error	VictoriaMetrics/lib/vmselectapi/server.go:214	cannot process vmselect conn 10.2.43.84:37086: cannot flush compressed buffers: cannot flush internal buffer to the underlying writer: write tcp4 10.2.43.84:8401->10.2.43.84:37086: write: broken pipe`
- vmstorage constantly closes connections to vminsert (log entries "accept vminsert conn" and "processing vminsert conn" every couple of minutes)
- vmselect essentially logs every query as "slow query"
- Resource usage in all services dropped to minimal (as in it is hardly using any CPU/RAM)

Each server vmstorage/vmselect/vminsert node has more than enough resources (20 cores/40 thread Intel Xeon CPU + 256 GB RAM + SATA3 SSD storage). The resource allocation did not change, only software was updated.

### To Reproduce

- Upgrade 1.89.1 to 1.90.0 on active cluster (as in cluster has constant ingest rate and constant queries)
- Observe

### Version

```vmstorage-20230407-011619-tags-v1.90.0-cluster-0-g64cf8fe49```

### Logs

See above

### Screenshots

![image](https://user-images.githubusercontent.com/985805/231043483-e6c463bb-eb7d-438d-9603-6453319559a4.png)

**Comment by valyala** [comment]
@akamensky , thanks for the bugreport!

Try running `vmstorage` without the `-dedup.minScrapeInterval` command-line flag and check whether this helps resolving performance issues at v1.90.0 .

As for the downgrade to v1.89.1, `vmstorage v1.90.0` cannot be easily downgraded because of changed on-disk naming for parts as [documented in the changelog](https://docs.victoriametrics.com/CHANGELOG.html#v1900).

The following downgrade options exist though:

1. To [restore](https://docs.victoriametrics.com/vmrestore.html) the data from the last [backup](https://docs.victoriametrics.com/vmbackup.html) made just before the upgrade.
1. To manually change new part names to the previous naming scheme before starting `vmstorage` prior to v1.90.0 . VictoriaMetrics stores two types of parts:
    1. `indexdb` parts are stored inside `<-storageDataPath>/indexdb/<partition>` folders
    2. `data` parts are stored inside `<-storageDataPath>/data/{small,big}/<partition>` folders

`indexdb` part directories had the following names prior to v1.90.0:

`<itemsCount>_<blocksCount>_<16ByteRandHex>`

Now they have `<16ByteRandHex>` names. It is possible to manually re-construct the previous names for `indexdb` part directories by looking up the `<itemsCount>` and `<blocksCount>` values at `metadata.json` file located inside the corresponding part directory.

`data` part directories had the following names prior to v1.90.0:

`<rowsCount>_<blocksCount>_<minTimestamp>_<maxTimestamp>_<16ByteRandHex>`

Now they have `<16ByteRandHex>` names. It is possible to manually re-construct the previous names for `data` part directories by looking up the `<rowsCount>`, `<blocksCount>`, `<minTimestamp>` and `<maxTimestamp>` values at `metadata.json` file located inside the corresponding part directory. Note that `<minTimestamp>` and `<maxTimestamp>` values must be converted from unix timestamp milliseconds to `YYYYMMDDHHmmSS.xxx` format before using them in part directory names. The `xxx` is the last three digits from the corresponding timestamp value stored in the `metadata.json`.


@dmitryk-dk , could you try reproducing the performance degradation issue at `vmstorage` v1.90.0 and then fix the root cause of the issue?

**Comment by akamensky** [comment]
Not sure if that is helpful at all, it appears the most frequent error message in the log is:

```
2023-04-11T03:24:35.574Z	error	VictoriaMetrics/lib/vmselectapi/server.go:214	cannot process vmselect conn 10.2.43.84:42064: cannot flush compressed buffers: cannot flush internal buffer to the underlying writer: write tcp4 10.2.43.84:8401->10.2.43.84:42064: write: broken pipe
```

**Comment by akamensky** [comment]
FYI as a mitigation of this, we rolled back to 1.89.1 with moving data to another directory and starting vmstorage data anew.

I will attempt to backfill the data using vmctl over native protocol. Hopefully that works.

**Comment by akamensky** [comment]
@dmitryk-dk did you mean this dashboard for the cluster? That is on the day of upgrade, the upgrade was done around 10 AM. We are still running backfill from old data (1.90.0) to new install (1.89.1), which I don't want to overload accidentally. I can try to load Grafana VM dashboard once that is done, which should have more details I guess.

![image](https://user-images.githubusercontent.com/985805/231608519-30bc24aa-23cb-4b4e-9c9d-46be67916d72.png)

**Comment by akamensky** [comment]
@dmitryk-dk I just found something that is odd, while looking at one of the nodes:

![image](https://user-images.githubusercontent.com/985805/231611566-4a1ff152-e028-4095-96f4-7fbc76be3258.png)

This node is running 2 vmstorage processes at the moment:

- top process is 1.90.0 -- only running vmselect queries now (for backfill to 1.89.1)
- bottom process is 1.89.1 -- running vminsert for normal data ingest, vmselect for user queries AND vminsert for backfill.

The CPU usage difference is completely expected (since 1.89.1 is doing a lot more work), but memory usage for whatever reason on 1.90.0 is much higher even though it does not do almost anything.

**Comment by dmitryk-dk** [comment]
HI @akamensky ! Thank you for your information. 
Do you have VictoriMetrics grafana dashboards? If yes, can you create screens from the troubleshooting section for v1.90.0 and the storage section?
If you have a working v1.90.0, can you generate profiles for vmstorage and vmselect? Profiles can help to check where the bottleneck can be.

**Comment by dmitryk-dk** [comment]
Hi @akamensky ! I have tried reproducing the problem with our data but have yet to be successful. I tried different scenarios with migration from v1.89.1 to v1.90.0 and couldn't find any performance degradation. Could you share some part of the data which you have, and it can help to reproduce the problem? It would also be helpful if you could check the merge process when you discover the performance degradation and share that information with us.

**Comment by akamensky** [comment]
@dmitryk-dk Unfortunately we don't have the 1.90 setup anymore as the data was backfilled in 1.89.1 and we needed the disk space for that.

Our setup where the issue was seen:

* 3 physical servers with 2x Intel(R) Xeon(R) Gold 6138 CPU each with 256 GB RAM and 2x sata3 SSD in RAID1 configuration
* 2 of the servers are:
  * Centos 7.5
  * docker-ce-18.09.6-3
* 1 server is:
  * Fedora 36
  * moby-engine-20.10.20-1
* docker-compose installed on all 3 hosts and vm{storage,insert,select} are running off of docker-compose configurations as below
* a number of vmagents that send metrics to haproxy that then LBs requests across vminsert nodes
* metrics ingestion rate `sum(rate(vm_vminsert_metrics_read_total{job="victoriametrics"}))` = 228404
* active series in last hour `sum(max_over_time(vm_cache_entries{job="victoriametrics",type="storage/hour_metric_ids"}[1h]))` = 3252947

vmstorage docker-compose.yml:

```yaml
version: '3.5'
services:
  vmstorage:
    image: "victoriametrics/vmstorage:v1.89.1-cluster"
    network_mode: "host"
   # ulimits only set for F36 as the default is too low there
    ulimits:
      nofile: 10485760
    volumes:
      - "/data/vmstorage:/storage"
    command:
      - "--storageDataPath=/storage"
      - "--retentionPeriod=90d"
      - "--dedup.minScrapeInterval=15s"
      - "--memory.allowedPercent=10"
    restart: "always"
```

vminsert docker-compose.yml:

```yaml
version: '3.5'
services:
  vminsert:
    image: "victoriametrics/vminsert:v1.89.1-cluster"
    network_mode: "host"
    command:
      - "--storageNode=host1:8400"
      - "--storageNode=host2:8400"
      - "--storageNode=host3:8400"
      - "--replicationFactor=2"
      - "--memory.allowedPercent=10"
    restart: "always"
```

vmselect docker-compose.yml:

```yaml
version: '3.5'
services:
  vmselect:
    image: "victoriametrics/vmselect:v1.89.1-cluster"
    network_mode: "host"
    command:
      - "--storageNode=host1:8401"
      - "--storageNode=host2:8401"
      - "--storageNode=host3:8401"
      - "--dedup.minScrapeInterval=15s"
      - "--memory.allowedPercent=10"
    restart: "always"
```
