### ISSUE TITLE
In the case of multi-tenancy, compared with single-tenant, the data set to be retrieved when querying data will be smaller, and the efficiency should be higher, but why is it not actually improved?

### ISSUE THREAD

**Issue by luzejia** [VictoriaMetrics/VictoriaMetrics#4129]
### Is your question request related to a specific component?

vmagent，vminsert，vmstorage，vmselect

### Describe the question in detail

I deployed two vm clusters with the same machine configuration.
One of them is written in single-tenant mode, and the other is written in multi-tenant mode:

The scrape configuration of the two clusters is as follows,:

single-tenant mode:
```
global:
  scrape_interval: 2s

scrape_configs:
  - job_name: test_object_group_1
    static_configs:
      - targets: ['x.x.x.x:9100']
      - targets: ['x.x.x.x:9100']
      - targets: ['x.x.x.x:9100']
      - targets: ['x.x.x.x:9100']
  - job_name: test_object_group_2
    static_configs:
      - targets: ['x.x.x.x:9100']
      - targets: ['x.x.x.x:9100']
      - targets: ['x.x.x.x:9100']
      - targets: ['x.x.x.x:9100']
...
...
```

multi-tenant mode:
```
global:
  scrape_interval: 2s

scrape_configs:
  - job_name: test_mutli_tenant_object_group_1
    static_configs:
      - targets: ['x.x.x.x:9100']
      - targets: ['x.x.x.x:9100']
      - targets: ['x.x.x.x:9100']
      - targets: ['x.x.x.x:9100']
    relabel_configs:
    - target_label: "vm_account_id"
      replacement: "1"
    - target_label: "vm_project_id"
      replacement: "1"
  - job_name: test_mutli_tenant_object_group_2
    static_configs:
      - targets: ['x.x.x.x:9100']
      - targets: ['x.x.x.x:9100']
      - targets: ['x.x.x.x:9100']
      - targets: ['x.x.x.x:9100']
    relabel_configs:
    - target_label: "vm_account_id"
      replacement: "2"
    - target_label: "vm_project_id"
      replacement: "2"
...
...
```

Querying the data of the same job on two clusters, it seems that in the multi-tenant mode, the performance has not improved:
(Repeated multiple comparisons, the time is about the same)

single-tenant mode:
```
time curl  http://cluster-1-vmselect-ip:8481/select/0/prometheus/api/v1/query_range -d 'query=avalanche_metric_mmmmm_0_0{job="test_object_group_1"}' -d 'start=-8h' -d 'step=5s' > /dev/null
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 79.0M    0 79.0M  100    77  85.8M     83 --:--:-- --:--:-- --:--:-- 85.7M

real	0m0.927s
user	0m0.013s
sys	0m0.025s
```

multi-tenant mode:
```
time curl  http://cluster-2-vmselect-ip:8481/select/1:1/prometheus/api/v1/query_range -d  'query=avalanche_metric_mmmmm_0_0{job="test_mutli_tenant_object_group_1"}' -d 'start=-8h' -d 'step=5s' > /dev/null
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 79.0M    0 79.0M  100    90  82.9M     94 --:--:-- --:--:-- --:--:-- 82.8M

real	0m0.960s
user	0m0.009s
sys	0m0.032s
```

my problem is as follows:
1、In the multi-tenant mode, data is stored independently by different tenants, so when retrieving data, the searched data set is smaller and the performance should be higher
2、If I divide the data into x tenants, the time to query the data of a tenant should be 1/x compared to the single-tenant mode, because the data set to be searched in the single-tenant mode is x times that in the multi-tenant mode

Is my understanding of the data in the multi-tenant mode wrong or my testing method is wrong? I hope to get a detailed answer about whether the performance in the multi-tenant mode has improved and why

### Troubleshooting docs

- [ ] General - https://docs.victoriametrics.com/Troubleshooting.html
- [ ] vmagent - https://docs.victoriametrics.com/vmagent.html#troubleshooting
- [ ] vmalert - https://docs.victoriametrics.com/vmalert.html#troubleshooting
