### ISSUE TITLE
Questions about the comparison of single-tenant and multi-tenant query performance

### ISSUE THREAD

**Issue by luzejia** [VictoriaMetrics/VictoriaMetrics#4153]
### Is your question request related to a specific component?

vmagent，vminsert，vmstorage，vmselect

### Describe the question in detail

I deployed two vm clusters with the same machine configuration.
One of them is written in single-tenant mode, and the other is written in multi-tenant mode:

The scrape configuration of the two clusters is as follows,:

single-tenant mode:
```
global:
  scrape_interval: 2s

scrape_configs:
  - job_name: test_object_group_1
    static_configs:
      - targets: ['x.x.x.x:9100']
      - targets: ['x.x.x.x:9100']
      - targets: ['x.x.x.x:9100']
      - targets: ['x.x.x.x:9100']
  - job_name: test_object_group_2
    static_configs:
      - targets: ['x.x.x.x:9100']
      - targets: ['x.x.x.x:9100']
      - targets: ['x.x.x.x:9100']
      - targets: ['x.x.x.x:9100']
...
...
```

multi-tenant mode:
```
global:
  scrape_interval: 2s

scrape_configs:
  - job_name: test_mutli_tenant_object_group_1
    static_configs:
      - targets: ['x.x.x.x:9100']
      - targets: ['x.x.x.x:9100']
      - targets: ['x.x.x.x:9100']
      - targets: ['x.x.x.x:9100']
    relabel_configs:
    - target_label: "vm_account_id"
      replacement: "1"
    - target_label: "vm_project_id"
      replacement: "1"
  - job_name: test_mutli_tenant_object_group_2
    static_configs:
      - targets: ['x.x.x.x:9100']
      - targets: ['x.x.x.x:9100']
      - targets: ['x.x.x.x:9100']
      - targets: ['x.x.x.x:9100']
    relabel_configs:
    - target_label: "vm_account_id"
      replacement: "2"
    - target_label: "vm_project_id"
      replacement: "2"
...
...
```

Here, the single-tenant and multi-tenant collection jobs have different names, but the collected objects are the same to ensure that the metrics data is the same.

Querying the data of the same job on two clusters, it seems that in the multi-tenant mode, the performance has not improved:
(Repeated multiple comparisons, the time is about the same)

In the case of collecting the same number of series, there is almost no difference in performance between the two, but the cardinality under the two tenants is very different. The cardinality of a single-tenant vm cluster is much larger than that of a multi-tenant vm cluster, but the performance has not improved.

vm cluster with single-tenant:
<img width="1408" alt="image" src="https://user-images.githubusercontent.com/52991866/233080724-49787b8a-5ed7-489e-b09e-7ce1f455409d.png">

<img width="1365" alt="image" src="https://user-images.githubusercontent.com/52991866/233080484-d4285f6a-8bbc-4201-898b-a704c433b20b.png">

vm cluster with multi-tenant:
<img width="1428" alt="image" src="https://user-images.githubusercontent.com/52991866/233080906-6de3255d-8785-4dc4-b614-183bf490ba28.png">

<img width="1393" alt="image" src="https://user-images.githubusercontent.com/52991866/233080615-6d9d9c7a-4a86-47a2-a8e8-d8e3fe31a4fd.png">

Under single-tenant, all data is in one tenant. Under multi-tenant, the data is divided into 8 tenants for storage, so the number of series in single-tenant is 8 times that of a single tenant in multi-tenant.
Querying data in a single tenant and querying the same data in a tenant in a multi-tenant, it seems that there is no great performance improvement between the two cases.

### Troubleshooting docs

- [ ] General - https://docs.victoriametrics.com/Troubleshooting.html
- [ ] vmagent - https://docs.victoriametrics.com/vmagent.html#troubleshooting
- [ ] vmalert - https://docs.victoriametrics.com/vmalert.html#troubleshooting
