### ISSUE TITLE
cluster version graphite multitenancy

### ISSUE THREAD

**Issue by Razikus** [VictoriaMetrics/VictoriaMetrics#4161]
### Is your question request related to a specific component?

Hello i have a question about vmselect and vmagent and how to realize the graphite multitenancy?

I couldnt find anything in the documentation

### Describe the question in detail

Hello i have a question about vmselect and vmagent and how to realize the graphite multitenancy?

I couldnt find anything in the documentation

### Troubleshooting docs

- [X] General - https://docs.victoriametrics.com/Troubleshooting.html
- [X] vmagent - https://docs.victoriametrics.com/vmagent.html#troubleshooting
- [X] vmalert - https://docs.victoriametrics.com/vmalert.html#troubleshooting

**Comment by zekker6** [comment]
Hello @Razikus 

In order to use [multitenancy](https://docs.victoriametrics.com/vmagent.html#multitenancy) at vmagent with `-remoteWrite.multitenantURL` you need to use relabeling to create  `__tenant_id__` label containing tenant id, just the same as for another ingestion protocols.
 You can use [graphite specific](https://docs.victoriametrics.com/vmagent.html#graphite-relabeling) or [regular](https://docs.victoriametrics.com/vmagent.html#relabeling) relabeling to do this. For example, for regular relabeling it will be similar to:
```
  relabel_configs:
  - target_label: __tenant_id__
    replacement: "1"
```

**Comment by Razikus** [comment]
thank you 
name me dumb but i dont really understand this

what i want to achieve is that i have for example metric blabla.xxxx
what i want is that for example i can prefix this metric with 0 or 1 or 2 and this would be sent into proper tenant

Is that achievable with relabeling?

is there any example?

**Comment by zekker6** [comment]
For this you can use the following rule:
```
- action: graphite
  match: "*.*.xxxx"
  labels:
    __name__: "${2}_xxxx"
    __tenant_id__: "$1"
```

It will extract part before the first dot as `__tenant_id__`, the second part as a part of name suffixed by `xxxx`.
You can also use ` __name__: "${2}_${3}` to build metric name based on second and third values splitted by the dots.

**Comment by zekker6** [comment]
Unfortunately, this won't work as `*` cannot match value containing `.`.
You need to create several rules with a number of `*.` items same as metrics you need to ingest:
```
- action: graphite
  match: "*.*"
  labels:
    __name__: "${2}"
    __tenant_id__: "$1"

- action: graphite
  match: "*.*.*"
  labels:
    __name__: "${2}_${3)"
    __tenant_id__: "$1"

# etc
```
