### ISSUE TITLE
Streaming aggregation calculation discrepancy with simple series reduction

### ISSUE THREAD

**Issue by mbrancato** [VictoriaMetrics/VictoriaMetrics#4170]
### Describe the bug

Using the VMAgent streaming aggregation, calculations of simple `sum()` values and compared with the `total` aggregation do not align.

I'm most closely following the example here:
https://docs.victoriametrics.com/stream-aggregation.html#reducing-the-number-of-stored-series

I expect these values from `node-exporter` to all be the same, collected every 30 seconds. This is a minimal example showing the problem, not my specific use-case. Here the `instance` label refers to a single cluster node.

1. `node_cpu_seconds_total{instance="10.128.0.127:9100", mode="idle", cpu="0"}`
2. `sum(node_cpu_seconds_total{instance="10.128.0.127:9100", mode="idle", cpu="0"})`
3. `node_cpu_seconds_total:30s_without_pod_total{instance="10.128.0.127:9100", mode="idle", cpu="0"}`

In the case of number 3, I expect it to produce a new data point every 30 seconds, based on the interval description:
```
# The aggregated stats is sent to remote storage once per interval.
```

An example of the resulting values using an instant query with grafana, where query 3 == "C" here:
<img width="383" alt="image" src="https://user-images.githubusercontent.com/8493275/233794648-05473f99-368f-4e35-98f8-9c38f2a28d5a.png">

Queries 1 and 2 are the same, but query 3 does not seem to be a `sum()` of the current values of the metric it is based on.

### To Reproduce

I used node-exporter and the following streaming aggregation config:

```yaml
      streamAggrConfig:
        keepInput: true
        rules:
          - match: '{__name__=~"node_.+"}'
            interval: "30s"
            outputs: ["total","increase"]
            without: ["pod"]
```

### Version

```
spec:
  image:
    tag: v1.90.0
```
