### ISSUE TITLE
Consul service discovery filters

### ISSUE THREAD

**Issue by f41gh7** [VictoriaMetrics/VictoriaMetrics#4183]
### Is your feature request related to a problem? Please describe

 Since v1.14, consul supports new filtering features for API requests https://github.com/hashicorp/consul/issues/9422

https://developer.hashicorp.com/consul/api-docs/features/filtering

 It implements advanced server-side filter which reduce amount of traffic between consul server and discovery client.

### Describe the solution you'd like

 Introduce new config option - `filter`.

```yaml
# promscrape.yaml
scrape_configs:
  - job_name: consul-targets
     consul_sd_configs:
     - filter:  'dc-1 in ServiceTags or dc-2 in ServiceTags and NodeMeta Is Not Empty' 
```

### Describe alternatives you've considered

 Use [relabel_configs](https://docs.victoriametrics.com/relabeling.html) for filtering, but it's not flexible and consumes additional resources.
