### ISSUE TITLE
sd_k8s: Add  pod name in error log

### ISSUE THREAD

**Issue by korjavin** [VictoriaMetrics/VictoriaMetrics#420]
**Describe the bug**
vmagent with sd_k8s

**To Reproduce**
Start vmagent with config:
```
    - job_name: 'kubernetes-pods'
      kubernetes_sd_configs:
      - role: pod
```
on a cluster with many pods.

 Please add pod name to error log. 

It's hard to find them in a big cluster. In a message like this it's not clear what was the pod.

```
2020-04-15T22:32:32.512Z	error	VictoriaMetrics/lib/promscrape/scrapework.go:127	error when scraping "http://10.8.3.60:6060/metrics" from job "kubernetes-pods": unexpected status code returned when scraping "http://10.8.3.60:6060/metrics": 404; expecting 200; response body: "404 page not found\n"
```

2. 
**Version**
v1.34.8

**Comment by valyala** [comment]
@korjavin , thanks for the feature request! There is a temporary workaround - to add relabeling rules, which move pod name to `pod_name` label, then navigate to `http://vmagent-host:8429/targets` page and locate the `pod_name` for the failing pod. The following config should work:

```
    - job_name: 'kubernetes-pods'
      kubernetes_sd_configs:
      - role: pod
      relabel_configs:
      - source_labels: [__meta_kubernetes_pod_name]
        target_label: pod_name
```

**Comment by valyala** [comment]
The commit 600490131f43151a7e74f4cff21e1331cb8c90a4 adds logging for all the labels for the target on scrape error. It will be included in the next release.

**Comment by valyala** [comment]
VictoriaMetrics logs all the labels associated with the scrape target on scrape errors starting from `v1.34.9`. Typical scrape config for Kubernetes pods copy [`__meta_kubernetes_pod_name`](https://docs.victoriametrics.com/sd_configs/#kubernetes_sd_configs) label to `pod` label for the particular target with the following [relabeling](https://docs.victoriametrics.com/vmagent/#relabeling) rule:

```yaml
scrape_configs:
- kubernetes_sd_configs:
  - role: pod
  relabel_configs:
  - target_label: pod
    source_labels: [__meta_kubernetes_pod_name]
```

In the case if `pod` label isn't added to scrape target labels, then the original pod can be found via `http://vmagent:8429/targets` page, and then the original pod name can be found by clicking on the target labels.

Closing the feature request as obsolete.
