### ISSUE TITLE
Is there a way to change the behavior that consul_sd will establish a tcp connection for each object of consul, which increases the network pressure

### ISSUE THREAD

**Issue by luzejia** [VictoriaMetrics/VictoriaMetrics#4202]
### Is your question request related to a specific component?

vmagent

### Describe the question in detail

I have 8 consuls, each consul has 13000 objects, all consuls have a total of about 100000 objects.I have 8 vmagents deployed in cluster mode with -promscrape.cluster.replicationFactor=2 to jointly undertake the collection of these 100,000 objects.

The number of collected objects shared by each vmagent is as follows:
```
[root@~]# curl 127.0.0.1:8429/targets | grep "("
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
job=consul-1 (3284/3284 up)
job=consul-2 (3246/3246 up)
job=consul-3 (3233/3233 up)
job=consul-4 (3267/3267 up)
job=consul-5 (3191/3191 up)
job=consul-6 (3227/3227 up)
job=consul-7 (3296/3296 up)
job=consul-8 (3207/3207 up)
100 7023k    0 7023k    0     0  70.7M      0 --:--:-- --:--:-- --:--:-- 70.7M
```

But in fact, vmagent will establish a connection for each object in consul, regardless of whether the object is collected by him or not.100k connections established for 100k objects
```
[root@ ~]# netstat -atnpl | grep 8500 | wc -l
104276
```

my vmagent scrap config:
```
global:
  scrape_interval: 10s
scrape_configs:
  - job_name: "consul-1"
    consul_sd_configs:
    - server: 'x.x.x.x:8500'
      services: []
    relabel_configs:
    - source_labels: [__meta_consul_service_id]
      target_label: id
    - action: labelmap
      regex: __meta_consul_service_metadata_(.*)
      replacement: $1
    - source_labels: [__meta_consul_service]
      regex: '^consul$'
      action: drop
  - job_name: "consul-2"
  ...
  ...
  - job_name: "consul-3"
  ...
  ...
```

my problem is as follows:
1、Is it possible to establish fewer connections and watch more objects per connection
2、Can vmagent only establish a connection with consul for each object allocated to itself, instead of establishing a connection for all objects in consul, regardless of whether it is allocated to him for collection

Because this behavior increases the network pressure, when the number of objects in consul is large, if the number of vmagents is expanded, each vmagent is only responsible for a small part of the objects, but it has to establish a full connection with consul, which increases significantly pressure on consul

### Troubleshooting docs

- [ ] General - https://docs.victoriametrics.com/Troubleshooting.html
- [ ] vmagent - https://docs.victoriametrics.com/vmagent.html#troubleshooting
- [ ] vmalert - https://docs.victoriametrics.com/vmalert.html#troubleshooting
