### ISSUE TITLE
VM Operator's VMAgent basicAuth username and password decoded from kubernetes secrets contains leading and trailing commas

### ISSUE THREAD

**Issue by whitehatbuds** [VictoriaMetrics/VictoriaMetrics#4210]
### Describe the bug

VMAgent basicAuth username and password decoded from kubernetes secrets contains leading and trailing commas

In the kubernetes secret under data.username  The value is encoded in base64 as 

QUtMVE16VmlaalpoWVdVeFlUUTRORFJsTUdFMVpqVTBPV000WW1abE56ZzJOamM= 
When decoded it returns 
AKLTMzViZjZhYWUxYTQ4NDRlMGE1ZjU0OWM4YmZlNzg2Njc

However when starting up vmagent, I notice in the logs the value was decoded as 
2023-04-27T05:58:40.682Z	info	VictoriaMetrics/lib/logger/flag.go:20	flag "remoteWrite.basicAuth.username"=",AKLTMzViZjZhYWUxYTQ4NDRlMGE1ZjU0OWM4YmZlNzg2Njc,,"

### To Reproduce

Im running VMAgent Version "v1.79.3" created from Victoria Metrics Operator.

```
VMAgent YAMLTemplate uses
  remoteWrite:
  - url: "http://...."
     basicAuth:
      password:
        key: signedkey
        name: influxdb
      username:
        key: username
        name: influxdb
```
Kubernetes Secret Yaml
```
apiVersion: v1
data:
  signedkey: something==
  username: QUtMVE16VmlaalpoWVdVeFlUUTRORFJsTUdFMVpqVTBPV000WW1abE56ZzJOamM=
kind: Secret
metadata:
  name: influxdb
  namespace: victoria-metrics
type: Opaque
```

![image](https://user-images.githubusercontent.com/73067032/234777390-10db9fbe-ed2b-4471-a568-2df492705b59.png)

"vmagent-20220830-103737-tags-v1.79.3-0-g56d7f3e37"

### Version

vmagent-20220830-103737-tags-v1.79.3-0-g56d7f3e37

### Logs

![image](https://user-images.githubusercontent.com/73067032/234777683-d499927f-316b-48a8-89c5-f7f2eb0fdfe0.png)
