### ISSUE TITLE
[vmauth ent + vmgateway] Reading JWT token params from custom destination

### ISSUE THREAD

**Issue by tenmozes** [VictoriaMetrics/VictoriaMetrics#4240]
### Is your feature request related to a problem? Please describe

We need to add an option to read VM-related params from the custom destination, the current payload is fixed, and this creates additional overhead for setup  

### Describe the solution you'd like

Add customization like 

```
request_params:
  username: request.auth.claims.username
   account_id: request.auth.claims.vm_access.tenant_id.account_id
   project_id: request.headers[X-VM-Project-ID]
  cluster_id: request.headers[X-VM-Cluster-ID]
```
