### ISSUE TITLE
VMAgent sharding and streaming aggregation causes duplicate series data and does not summarize correctly

### ISSUE THREAD

**Issue by mbrancato** [VictoriaMetrics/VictoriaMetrics#4247]
### Describe the bug

When doing sharding of vmagent with streaming aggregation enabled, there is no differentiation between vmagent shards.

For example, say there is a metric `requests_total` which should be aggregated to `requests_total:30s_without_instance_total`. Each shard will output `requests_total:30s_without_instance_total` with no labels to differentiate the series.

An example of what this ends up doing with 4 shards is this.

Two graphs, one using aggregation, the other using the original data. Both delivered by vmagent shards.

`sum(rate(input_events:30s_without_instance_pod_total[1m]))` vs `sum(rate(input_events[1m]))`
![image](https://user-images.githubusercontent.com/8493275/235751309-bf822c2b-cb5d-4a9f-8bae-9335eb9a7e17.png)
![image](https://user-images.githubusercontent.com/8493275/235751361-477479ca-d128-4b85-9678-da0bb26f1f77.png)

The sharded aggregation rate calculation always puts out these "Charlie Brown" shaped graphs.

A workaround to this is to add a label to each shard, I did this with the following:
`--remoteWrite.label=vmagent=%{HOSTNAME}`

After that, the original and aggregated data are aligned:
![image](https://user-images.githubusercontent.com/8493275/235751696-4255c960-0c90-41af-baff-1d0e9c328c34.png)

### To Reproduce

```yaml
apiVersion: operator.victoriametrics.com/v1beta1
kind: VMAgent
metadata:
  name: vmagent
  namespace: monitoring
spec:
  image:
    tag: v1.90.0
  selectAllByDefault: true
  scrapeInterval: "30s"
  replicaCount: 1
  shardCount: 4
  logFormat: json
  resources:
    requests:
      cpu: "2.5"
      memory: "3Gi"
  extraArgs:
    # remoteWrite.label: "vmagent=%{HOSTNAME}"
  remoteWrite:
    - url: "http://my_vm/insert/0/prometheus/api/v1/write"
      sendTimeout: "2m"
      streamAggrConfig:
        keepInput: false
        rules:
          - match: '{__name__=~"input_.+"}'
            interval: "30s"
            outputs: ["total","sum_samples"]
            without: ["pod", "instance"]
```

### Version

`v1.90.0`
