### ISSUE TITLE
vmagent does not use proper defaults

### ISSUE THREAD

**Issue by afoninsky** [VictoriaMetrics/VictoriaMetrics#427]
**Describe the bug**
According to https://prometheus.io/docs/prometheus/latest/configuration/configuration/#kubernetes_sd_config
```
# The API server addresses. If left empty, Prometheus is assumed to run inside
# of the cluster and will discover API servers automatically and use the pod's
# CA certificate and bearer token file at /var/run/secrets/kubernetes.io/serviceaccount/.
[ api_server: <host> ]

```
vmagent should discover api_server url and tokens if launched in kubernetes. Instead in tries to connect to localhost.

**To Reproduce**
Launch kubernetes discovery config without specified api server, ex.:
```
    - job_name: alb-vm-histogram
      kubernetes_sd_configs:
        - role: endpoints
          # api_server: https://kubernetes.default.svc.cluster.local:443
          scheme: https
          tls_config:
            ca_file: /var/run/secrets/kubernetes.io/serviceaccount/ca.crt
          bearer_token_file: /var/run/secrets/kubernetes.io/serviceaccount/token
      relabel_configs:
        - source_labels: [__meta_kubernetes_endpoints_name]
          regex: lambda
          action: keep
        - source_labels: [__meta_kubernetes_endpoint_port_name]
          regex: http
          action: keep
```

**Expected behavior**
vmagent should discover api_server url and tokens if launched in kubernetes. Instead in tries to connect to localhost.

**Version**
vmagent v1.34.9
