### ISSUE TITLE
Incorrect metrics relabel behavior

### ISSUE THREAD

**Issue by dmitryk-dk** [VictoriaMetrics/VictoriaMetrics#4284]
### Describe the bug

When you try to use the Metrics relable debug feature via `/metric-relabel-debug` with non Prometheus exposition format it returns unexpected results.

### To Reproduce

Use [play](https://play.victoriametrics.com/select/accounting/1/6a716b0f-38bc-4856-90ce-448fd713e3fe/metric-relabel-debug?relabel_configs=-+target_label%3A+status_OB%0D%0A++replacement%3A+status%0D%0A-+target_label%3A+status_OL%0D%0A++replacement%3A+status%0D%0A-+action%3A+labeldrop%0D%0A++regex%3A+%22status_.*%22&metric=%7B%22__name__%22%3A%22upsd_time_left_ns%22%2C%22host%22%3A%22myhost%22%2C+status_OB%3D%22true%22%7D) as example.

In this example, uses next relabel config: 
```yaml
- target_label: status_OB
  replacement: status
- target_label: status_OL
  replacement: status
- action: labeldrop
  regex: "status_.*"
```
And labels for relabeling:
`{"__name__":"upsd_time_left_ns","host":"myhost", status_OB="true"}`

When we apply this relabeling example we got
`{"__name__":"upsd_time_left_ns","host":"myhost", status_OB="true"}` metric after relabeling
but expecting
`upsd_time_left_ns{host="myhost"}`

### Version

victoria-metrics-20230510-080436-tags-v1.90.0-0-gb5d18c0d2
