### ISSUE TITLE
Abnormal recording rule

### ISSUE THREAD

**Issue by LeonYanghaha** [VictoriaMetrics/VictoriaMetrics#4326]
### Is your question request related to a specific component?

vmalert

### Describe the question in detail

The record rule has been set in vmalert, and the version of vmalert is 1.79.8. In Grafana, the ```kube_ pod_ container_ status_ restarts_ total{id="1028"}``` can query relevant data
```
groups:
- interval: 30s
  name: k8s.rules
  rules:
  - expr: kube_pod_container_status_restarts_total{pod=~"open-api.*"}
    labels:
      app: admin
      id: 1028
    record: kube_pod_container_status_restarts_total
```

There are two questions.

1.There is an error message on the "http://ip:port/vmalert/groups" page of vmalert，and there are also similar error logs in the logs。I have seen the [relevant discussion](https://github.com/VictoriaMetrics/VictoriaMetrics/issues/1293), but it has been a long time. My question is: Does the community have a plan to fix this bug ?

```
Error: result contains metrics with the same labelset after applying rule labels
```

2.  I use the results of the recording rule as the alert rule, as follows. However, every 5 minutes, an alert generated, which is contrary to the fact that the pod did not restart. I am very confused about why
```
  - alert: "k8s-pod-restart"
    expr:  changes(kube_pod_container_status_restarts_total{pod=~"open-api.*"}[5m]) > 0
    for: 30s
    labels:
      team: "admin_team"
    annotations:
      summary: "[{{$labels.env_id}}]pod-restart"
``` 

### Troubleshooting docs

- [X] General - https://docs.victoriametrics.com/Troubleshooting.html
- [x] vmalert - https://docs.victoriametrics.com/vmalert.html#troubleshooting
- [x] vmagent - https://docs.victoriametrics.com/vmagent.html#troubleshooting
