### ISSUE TITLE
VMselect 1.91.0 the number of matching timeseries exceeds 50000

### ISSUE THREAD

**Issue by ihard** [VictoriaMetrics/VictoriaMetrics#4339]
### Describe the bug

Send request /select/0/graphite/tags/autoComplete/tags?expr=instance%3Dmetric-server-1&from=1684859400&limit=5000&until=1684863035
No answer and error in log

### To Reproduce

curl -s "127.1:8481/select/0/graphite/tags/autoComplete/tags?expr=instance%3Dmetric-server-1&from=1684859400&limit=5000&until=1684863035"

### Version

vmselect-20230518-213038-tags-v1.91.0-cluster-0-g93f934eae

### Logs

2023-05-23T22:10:47.429+0300	warn	VictoriaMetrics/app/vmselect/main.go:608	remoteAddr: "127.0.0.1:21548", X-Forwarded-For: "10.10.0.10, 127.0.0.1, 127.0.0.1"; requestURI: /select/0/graphite/tags/autoComplete/tags?expr=instance%3Dmetric-server-1&from=1684859400&limit=5000&until=1684863035; cannot fetch metric names for "accountID=0, projectID=0, filters=[{instance=\"metric-server-1\"}], timeRange=[1970-01-01T00:00:00Z..2023-05-23T19:10:47.42Z]": cannot fetch metric names from vmstorage nodes: cannot search metric names on vmstorage 10.225.88.102:8693: cannot execute funcName="searchMetricNames_v3" on vmstorage "10.225.88.102:8693": error when searching for metricIDs in the current indexdb: the number of matching timeseries exceeds 50000; either narrow down the search or increase -search.max* command-line flag values at vmselect; see https://docs.victoriametrics.com/#resource-usage-limits

### Used command-line flags

```
---

version: "3.7"
services:
  vmselect:
    container_name: vmselect
    image: 'victoriametrics/vmselect:v1.91.0-cluster'
    network_mode: host
    restart: always
    user: 'nobody'
    mem_limit: 80g
    command:
      - '--httpListenAddr=:8481'
      - '--storageNode=10.223.88.101:8673'
      - '--storageNode=10.223.88.101:8683'
      - '--storageNode=10.223.88.101:8693'
      - '--storageNode=10.223.88.102:8673'
      - '--storageNode=10.223.88.102:8683'
      - '--storageNode=10.223.88.102:8693'
      - '--storageNode=10.225.88.101:8673'
      - '--storageNode=10.225.88.101:8683'
      - '--storageNode=10.225.88.101:8693'
      - '--storageNode=10.225.88.102:8673'
      - '--storageNode=10.225.88.102:8683'
      - '--storageNode=10.225.88.102:8693'
      - '--dedup.minScrapeInterval=10s'
      - '--replicationFactor=2'
      - '--search.maxUniqueTimeseries=30000000'
      - '--search.maxSamplesPerSeries=10000000'
      - '--search.maxSamplesPerQuery=10000000'
      - '--search.maxPointsPerTimeseries=1000000'
      - '--search.maxPointsSubqueryPerTimeseries=10000000'
      - '--search.maxSeriesPerAggrFunc=10000000'
      - '--search.maxSeries=30000000'
      - '--search.maxGraphiteSeries=30000000'
      - '--search.maxQueueDuration=60s'
      - '--search.maxConcurrentRequests=2000'

  vminsert-short-term:
    container_name: vminsert-short-term
    image: 'victoriametrics/vminsert:v1.91.0-cluster'
    network_mode: host
    restart: always
    user: 'nobody'
    mem_limit: 2g
    command:
      - '--httpListenAddr=:8571'
      - '--storageNode=10.225.88.101:8672'
  vminsert-long-term-1:
    container_name: vminsert-long-term-1
    image: 'victoriametrics/vminsert:v1.91.0-cluster'
    network_mode: host
    restart: always
    user: 'nobody'
    mem_limit: 2g
    command:
      - '--httpListenAddr=:8581'
      - '--storageNode=10.225.88.101:8682'
  vminsert-long-term-2:
    container_name: vminsert-long-term-2
    image: 'victoriametrics/vminsert:v1.91.0-cluster'
    network_mode: host
    restart: always
    user: 'nobody'
    mem_limit: 2g
    command:
      - '--httpListenAddr=:8591'
      - '--storageNode=10.225.88.101:8692'

  vmstorage-short-term:
    container_name: vmstorage-short-term
    image: 'victoriametrics/vmstorage:v1.91.0-cluster'
    network_mode: host
    restart: always
    user: 'nobody'
    mem_limit: 30g
    volumes:
      - '/storage/vm/short/data:/vmstorage-data'
    command:
      - '--vminsertAddr=:8672'
      - '--vmselectAddr=:8673'
      - '--httpListenAddr=:8671'
      - '--search.maxUniqueTimeseries=30000000'
      - '--search.maxQueueDuration=60s'
      - '--search.maxConcurrentRequests=3000'
      - '--search.maxTagKeys=1000000'
      - '--search.maxTagValues=1000000'
      - '--search.maxTagValueSuffixesPerSearch=1000000'
      - '--storageDataPath=/vmstorage-data'
      - '--retentionPeriod=3d'
      - '--dedup.minScrapeInterval=10s'
  vmstorage-long-term-1:
    container_name: vmstorage-long-term-1
    image: 'victoriametrics/vmstorage:v1.91.0-cluster'
    network_mode: host
    restart: always
    user: 'nobody'
    mem_limit: 30g
    volumes:
      - '/storage/vm/long/1/data:/vmstorage-data'
    command:
      - '--vminsertAddr=:8682'
      - '--vmselectAddr=:8683'
      - '--httpListenAddr=:8681'
      - '--search.maxUniqueTimeseries=30000000'
      - '--search.maxQueueDuration=60s'
      - '--search.maxConcurrentRequests=3000'
      - '--search.maxTagKeys=1000000'
      - '--search.maxTagValues=1000000'
      - '--search.maxTagValueSuffixesPerSearch=1000000'
      - '--storageDataPath=/vmstorage-data'
      - '--retentionPeriod=90d'
      - '--dedup.minScrapeInterval=10m'
  vmstorage-long-term-2:
    container_name: vmstorage-long-term-2
    image: 'victoriametrics/vmstorage:v1.91.0-cluster'
    network_mode: host
    restart: always
    user: 'nobody'
    mem_limit: 60g
    volumes:
      - '/storage/vm/long/2/data:/vmstorage-data'
    command:
      - '--vminsertAddr=:8692'
      - '--vmselectAddr=:8693'
      - '--httpListenAddr=:8691'
      - '--search.maxUniqueTimeseries=30000000'
      - '--search.maxQueueDuration=60s'
      - '--search.maxConcurrentRequests=3000'
      - '--search.maxTagKeys=1000000'
      - '--search.maxTagValues=1000000'
      - '--search.maxTagValueSuffixesPerSearch=1000000'
      - '--storageDataPath=/vmstorage-data'
      - '--retentionPeriod=2000d'
      - '--dedup.minScrapeInterval=60m'

```
