### ISSUE TITLE
Add basic authentication support on vmauth's backend target paths

### ISSUE THREAD

**Issue by mohammadkhavari** [VictoriaMetrics/VictoriaMetrics#4361]
### Is your feature request related to a problem? Please describe

Currently, vmauth does not support authentication behind its backend paths. in some use cases, whether the backend targets are on the same isolated network or not, targets may need authentication.

### Describe the solution you'd like

AuthConfig can change to support this feature by altering url_prefix entries:

### Curent configuration:
```
- username: "user"
  password: "***"
  url_prefix:
  - "http://host1:8429/"
  - "http://host2:8429/"
  - "http://host3:8429/"
```

### Possible solutions:
```
- username: "user"
  password: "***"
  url_prefix:
  - url: "http://host1:8429/"
    basic_auth:
      username: "backed_user"
      password: "***"
  - url: "http://host2:8429/"
  - url: "http://host3:8429/"
```

or maybe add a new field for backends that requires authorization (if the previous alternative can break backward compatibility):
```
- username: "user"
  password: "***"
  authorized_url_prefix:
  - url: "http://host1:8429/"
    basic_auth:
      username: "user"
      password: "***"
  url_prefix:
  - "http://host2:8429/"
  -  "http://host3:8429/"
 ```

### Additional information

This topic has been discussed on the victoriametrics telegram group. we agreed to create a feature request to find the proper config change and then I'll send a pull request.

**Comment by mohammadkhavari** [comment]
As I investigate the code the first solution can be implemented without breaking backward compatibilityhttps://github.com/VictoriaMetrics/VictoriaMetrics/blob/51cea6cad41ec03cb4db41337271a3ac5b8c3da1/app/vmauth/auth_config.go#L199.

**Comment by mohammadkhavari** [comment]
[Here](https://github.com/mohammadkhavari/VictoriaMetrics/tree/vmauth-backend-authentication) I have added a naive code for the first proposed configuration format, If you agree with this configuration I'll refactor the code, tests, and update documentation.

**Comment by Amper** [comment]
Hi @mohammadkhavari.
Sorry for delay. We were discussing this issue in the team and we came to the conclusion that implementation in this form would be superfluous. 
We think it would be enough to add the ability to specify headers for each of the backends (for each url prefix entry), it is more flexible and allows you to pass the authorization token in any format.
What do you think about it?
If you want, you can send a PR or we can do it ourselves.

**Comment by mohammadkhavari** [comment]
Hey there
It can be better to add any header to url_prefixes.
But there's a concern that is not directly related to this issue, and it was related to further developments on victoriametrics operator and VMUser CRD. Considering security concerns I wanted to prevent adding plain credential authentication in the VMUser manifests, and after releasing this issue on vmauth I want to make an additional issue on the operator to support backend authentications by secrets like vmagents remotewrite url secrets:
```
kind: VMUser
  spec.targetRefs.paths[0].static:
    - url: http://host:8480/
      basicAuth:
      password:
        key: password
        name: secretname
      username:
        key: username
        name: cluster-vmagent-remotewrite-auth
```

Do you anticipate this kind of change on the headers also, that we can insert the header value from a secret? that the operator read the basicauth from secret and translate it to a header on vmauth configuration?

**Comment by f41gh7** [comment]
Related issue at operator repo was created. It must solve current issue with backend authorization at kubernetes.

**Comment by serrrios** [comment]
What about vmauth installed in the monolith?

**Comment by zekker6** [comment]
Starting from vmauth version [v1.94.0](https://docs.victoriametrics.com/changelog_2023/#v1940) it is possible to [override headers](https://docs.victoriametrics.com/vmauth/#modifying-http-headers) which are passed to the upstream which allows using any authentication token format.
For example, to proxy request to endpoint protected with basic auth it is possible to use the following configuration:
```
unauthorized_user:
  url_prefix: "http://backend:1234/"
  headers:
  - "Authorization: Basic BASE64_ENCODED_VALUE"
```

@hagen1778 Should we close this one as completed, or it's better to keep it open until there will be an option to provide basic auth credentials via config directly?
