### ISSUE TITLE
streaming aggr: support defining `keepInput` per aggregation Job

### ISSUE THREAD

**Issue by zekker6** [VictoriaMetrics/VictoriaMetrics#4383]
### Is your feature request related to a problem? Please describe

Currently, in case there are different aggregation jobs some of which require `keepInput` to be enabled it is required to place those into separate config files and enable `keepInput` for the whole file.
This becomes hard to manage in case jobs are grouped per logical units and also grouped by `keepInput` requirement after that.

### Describe the solution you'd like

It would be great if it would be possible to define `keepInput` on aggregation job level:
```
  # match is an optional filter for incoming samples to aggregate.
  # It can contain arbitrary Prometheus series selector
  # according to https://docs.victoriametrics.com/keyConcepts.html#filtering .
  # If match isn't set, then all the incoming samples are aggregated.
- match: 'http_request_duration_seconds_bucket{env=~"prod|staging"}'

  # interval is the interval for the aggregation.
  # The aggregated stats is sent to remote storage once per interval.
  interval: 1m

  # without is an optional list of labels, which must be removed from the output aggregation.
  # See https://docs.victoriametrics.com/stream-aggregation.html#aggregating-by-labels
  without: [instance]

  # by is an optional list of labels, which must be preserved in the output aggregation.
  # See https://docs.victoriametrics.com/stream-aggregation.html#aggregating-by-labels
  # by: [job, vmrange]

  # outputs is the list of aggregations to perform on the input data.
  # See https://docs.victoriametrics.com/stream-aggregation.html#aggregation-outputs
  outputs: [total]
  

  # optional, allows to override keepInput value defined for configuration file
  # overrides value defined for configuration file if there is any
  keepInput: false

  # input_relabel_configs is an optional relabeling rules,
  # which are applied to the incoming samples after they pass the match filter
  # and before being aggregated.
  # See https://docs.victoriametrics.com/stream-aggregation.html#relabeling
  input_relabel_configs:
  - target_label: vmaggr
    replacement: before

  # output_relabel_configs is an optional relabeling rules,
  # which are applied to the aggregated output metrics.
  output_relabel_configs:
  - target_label: vmaggr
    replacement: after



```

### Describe alternatives you've considered

Specifying this on per-file level and splitting aggregation jobs into files based on this.
