### ISSUE TITLE
vmalert: adding `time()` to labels prevent alerts from triggering

### ISSUE THREAD

**Issue by DaazKu** [VictoriaMetrics/VictoriaMetrics#4444]
### Describe the bug

I'm trying to create a proper link to victoriametrics like so `victoriametrics/vmui/?#/?g0.expr={{ $expr|queryEscape }}&g0.range_input=1h&g0.end_input={{ $activeAt.Format ("2006-01-02T15:04:05") | queryEscape }}` but we do not have access to `$activaAt` in labels https://github.com/VictoriaMetrics/VictoriaMetrics/issues/3379

I tried to get the current time with `'{{ query "time()" | first | value }}'`

Unfortunately I never get the alert in alertmanager and I can't figure out where it breaks.
Querying a metric like `up` works.

### To Reproduce

Create a rule like so:
```
    - alert: ThisOneWorks
      expr: 1==1
      for: 1s
      labels:
        query: '{{ query "time()" | first | value }}'
```

The alert never shows up in alertmanager. No errors in `vmagent` logs.

### Version

- vmagent: v1.91.2
- victoria-metrics-server: v1.91.0
- alertmanager: v0.25.0
