### ISSUE TITLE
Query returns JSON.parse error unless I place a specific label fiter first or last in query

### ISSUE THREAD

**Issue by djfinnoy** [VictoriaMetrics/VictoriaMetrics#4527]
### Describe the bug

I noticed some strange behavior when querying some metrics from our own bespoke applications.

This query throws an error in the UI: `SyntaxError: JSON.parse: unexpected character at line 1 column 1 of the JSON data`
```
backend_event_total{app="account-engine", event="account.update.moneybag", status="fail"}
```

If I put the `event` label last (or first), it works:
```
backend_event_total{app="account-engine", status="fail", event="account.update.moneybag"}
```

I have tried every combination, and I guarantee that it is not cause by a typo.
The error will be thrown for any combination of label filters where `event` is not in the first or last spot.

Via Grafana explore, I can swap between Victoria and Prometheus as a datasource, and verify that the query works with Prometheus, and fails with Victoria if `event` is not first or last. (We are running Victoria and Prometheus in parallel right now because we are transitioning.)

Perhaps it's an issue that occurs because the `event` string always contains words separated by dots?

### To Reproduce

Create some metrics matching the queries above, and query them with the `event` label in different positions.

### Version

```
apiVersion: v2
name: victoriametrics
version: 0.1.0
dependencies:
  - name: victoria-metrics-single
    version: 0.8.63
    repository: https://victoriametrics.github.io/helm-charts/
  - name: victoria-metrics-agent
    version: 0.8.40
    repository: https://victoriametrics.github.io/helm-charts/
  - name: victoria-metrics-auth
    version: 0.2.83
    repository: https://victoriametrics.github.io/helm-charts/
  - name: victoria-metrics-alert
    version: 0.6.3
    repository: https://victoriametrics.github.io/helm-charts/
```

### Logs

The following entries appear when the query fails when called via Grafana. There are no log entries from when it fails in the VM UI.

```
{ts":"2023-06-26T18:04:30.781Z","level":"warn","caller":"VictoriaMetrics/app/vmselect/main.go:288","msg":"error in \"/api/v1/query_range\": missing `query` arg"}

{"ts":"2023-06-26T18:05:30.750Z","level":"warn","caller":"VictoriaMetrics/app/vmselect/main.go:279","msg":"error in \"/api/v1/query\": missing `query` arg"}

{"ts":"2023-06-26T18:06:50.863Z","level":"warn","caller":"VictoriaMetrics/app/vmselect/main.go:288","msg":"error in \"/api/v1/query_range\": missing `query` arg"}

{"ts":"2023-06-26T18:07:26.108Z","level":"warn","caller":"VictoriaMetrics/app/vmselect/main.go:288","msg":"error in \"/api/v1/query_range\": missing `query` arg"}

{"ts":"2023-06-26T18:08:14.080Z","level":"warn","caller":"VictoriaMetrics/app/vmselect/main.go:288","msg":"error in \"/api/v1/query_range\": missing `query` arg"}

{"ts":"2023-06-26T18:27:56.465Z","level":"warn","caller":"VictoriaMetrics/app/vmselect/main.go:288","msg":"error in \"/api/v1/query_range\": missing `query` arg"}

{"ts":"2023-06-26T18:27:58.214Z","level":"warn","caller":"VictoriaMetrics/app/vmselect/main.go:288","msg":"error in \"/api/v1/query_range\": missing `query` arg"}

{"ts":"2023-06-26T18:28:02.599Z","level":"warn","caller":"VictoriaMetrics/app/vmselect/main.go:279","msg":"error in \"/api/v1/query\": missing `query` arg"}

{"ts":"2023-06-26T18:33:31.373Z","level":"warn","caller":"VictoriaMetrics/app/vmselect/main.go:288","msg":"error in \"/api/v1/query_range\": missing `query` arg"}

{"ts":"2023-06-26T18:34:27.655Z","level":"warn","caller":"VictoriaMetrics/app/vmselect/main.go:288","msg":"error in \"/api/v1/query_range\": missing `query` arg"}

{"ts":"2023-06-26T18:46:56.806Z","level":"warn","caller":"VictoriaMetrics/app/vmselect/main.go:288","msg":"error in \"/api/v1/query_range\": missing `query` arg"}

{"ts":"2023-06-26T18:47:23.795Z","level":"warn","caller":"VictoriaMetrics/app/vmselect/main.go:279","msg":"error in \"/api/v1/query\": missing `query` arg"}
```

### Screenshots

![image](https://github.com/VictoriaMetrics/VictoriaMetrics/assets/37372205/6ec82bdb-9144-4821-bbf3-53ba21483e09)

![image](https://github.com/VictoriaMetrics/VictoriaMetrics/assets/37372205/2015090e-021a-4b07-b8a8-8e773b01fa43)
