### ISSUE TITLE
Vmagent Metric relabel config acts weird

### ISSUE THREAD

**Issue by Ram-97** [VictoriaMetrics/VictoriaMetrics#4654]
Trying to keep fixed number of le buckets from vmagent.

Vmagent Config:
```
      metric_relabel_configs:
        - source_labels: [__name__]
          regex: .*bucket.*
          action: keep
        - source_labels: [le]
          regex: (0.01|0.05|0.1|0.25|0.5|1.0|2.0|5.0|10.0|30.0|.*Inf)
          action: keep
```

Target Response:
```
http_request_duration_seconds_bucket{code="200",handler="/aaa/health",method="GET",service="",le="1"} 174
http_request_duration_seconds_bucket{code="200",handler="/aaa/health",method="GET",service="",le="2.5"} 174
http_request_duration_seconds_bucket{code="200",handler="/aaa/health",method="GET",service="",le="5"} 174
http_response_size_bytes_bucket{code="200",handler="/aaa/health",method="GET",service="",le="100"} 174
http_response_size_bytes_bucket{code="200",handler="/aaa/health",method="GET",service="",le="1000"} 174
http_response_size_bytes_bucket{code="200",handler="/aaa/health",method="GET",service="",le="10000"} 174
http_response_size_bytes_bucket{code="200",handler="/aaa/health",method="GET",service="",le="100000"} 174
http_response_size_bytes_bucket{code="200",handler="/aaa/health",method="GET",service="",le="1e+06"} 174
http_response_size_bytes_bucket{code="200",handler="/aaa/health",method="GET",service="",le="1e+07"} 174
http_response_size_bytes_bucket{code="200",handler="/aaa/health",method="GET",service="",le="1e+08"} 174
http_response_size_bytes_bucket{code="200",handler="/aaa/health",method="GET",service="",le="1e+09"} 174
```

Scrapped metrics for above config:
```
http_request_duration_seconds_bucket{code="200",handler="/aaa/health",method="GET",service="",le="1"} 174
http_request_duration_seconds_bucket{code="200",handler="/aaa/health",method="GET",service="",le="2.5"} 174
http_request_duration_seconds_bucket{code="200",handler="/aaa/health",method="GET",service="",le="5"} 174
http_response_size_bytes_bucket{code="200",handler="/aaa/health",method="GET",service="",le="100"} 174
http_response_size_bytes_bucket{code="200",handler="/aaa/health",method="GET",service="",le="1000"} 174
```

Expected Scrapped metrics:
```
http_request_duration_seconds_bucket{code="200",handler="/aaa/health",method="GET",service="",le="1"} 174
http_request_duration_seconds_bucket{code="200",handler="/aaa/health",method="GET",service="",le="2.5"} 174
http_request_duration_seconds_bucket{code="200",handler="/aaa/health",method="GET",service="",le="5"} 174
```

Can someone help me to understand, how **http_response_size_bytes_bucket** metric also gets scrapped.

Vmagent version: **v1.83.1**

**Comment by Amper** [comment]
Hi @Ram-97.
There are two problems in this config:
1. Label values are strings so "1" and "1.0" are not the same things, i.e. `le="5"` can't be matched with `...|5.0|...`.
2. In the regexp template, the `.` character must be escaped, otherwise it will mean "any character"

You can rewrite you config with something like that:
```
      metric_relabel_configs:
        - source_labels: [__name__]
          regex: .*bucket.*
          action: keep
        - source_labels: [le]
          regex: '(0\.01|0\.05|0\.1|0\.25|0\.5|1\.0|1|2\.0|2|5\.0|5|10\.0|10|30\.0|30|.*Inf)'
          action: keep
```

or like that:

```
      metric_relabel_configs:
        - source_labels: [__name__]
          regex: .*bucket.*
          action: keep
        - source_labels: [le]
          regex: 
            - 0\.01
            - 0\.05
            - 0\.1
            - 0\.25
            - 0\.5
            - 1\.0
            - 1
            - 2\.0
            - 2
            - 5\.0
            - 5
            - 10\.0
            - 10
            - 30\.0
            - 30
            - .*Inf
          action: keep
```

or like that:

```
      metric_relabel_configs:
        - source_labels: [__name__]
          regex: .*bucket.*
          action: keep
        - source_labels: [le]
          if: '{le=~"(0\\.01|0\\.05|0\\.1|0\\.25|0\\.5|1\\.0|1|2\\.0|2|5\\.0|5|10\\.0|10|30\\.0|30|.*Inf)"}'
          action: keep
```

or like that (with the next release version):

```
      metric_relabel_configs:
        - source_labels: [__name__]
          regex: .*bucket.*
          action: keep
        - source_labels: [le]
          if: '{le="0.01" or le="0.05" or le="0.1" or le="0.25" or le="0.5" or le="1.0" or le="1" or le="2.0" or le="2" or le="5.0" or le="5" or le="10.0" or le="10" or le="30.0" or le="30" or le=~".*Inf"}'
          action: keep
```
