### ISSUE TITLE
incorrect display of volume status

### ISSUE THREAD

**Issue by Nello-Angelo** [VictoriaMetrics/VictoriaMetrics#4739]
### Describe the bug

incorrect display of volume status. in the clustered version of the installation of victoria metrics, the size of the volumes is displayed with larger or smaller values, but the same state is displayed correctly in victoria metrics single. I have incorrect display of volume status only in cluster version

### To Reproduce

install victoria metrics chart like cluster and use for display this dashboards
https://grafana.com/grafana/dashboards/13646-kubernetes-persistent-volumes/

### Version

the latest

### Logs

no logs

### Screenshots

![Screenshot_11](https://github.com/VictoriaMetrics/VictoriaMetrics/assets/82488489/f230f2c7-dd70-45e1-9850-efded2c6982b)
![Screenshot_5](https://github.com/VictoriaMetrics/VictoriaMetrics/assets/82488489/ac845ee0-6e4b-456d-90d4-ea5bac107a73)
![Screenshot_8](https://github.com/VictoriaMetrics/VictoriaMetrics/assets/82488489/d74951d2-faf6-4c28-b8b0-3f1182641a5f)

these screens was made in cluster version

**Comment by Nello-Angelo** [comment]
I thought to solve the problem by increasing the number of each component to 3 and the replication factor to 3 too, but it did not help

**Comment by Amper** [comment]
Hey @Nello-Angelo.

- Could you show please `kubelet_volume_stats_capacity_bytes` without aggregation?
- Do you have [dedublication configured](https://docs.victoriametrics.com/Cluster-VictoriaMetrics.html#deduplication)?

**Comment by Nello-Angelo** [comment]
```
vmcluster:
  enabled: true
  annotations: {}
  # spec for VMSingle crd
  # https://docs.victoriametrics.com/operator/api.html#vmclusterspec
  # https://docs.victoriametrics.com/Cluster-VictoriaMetrics.html#architecture-overview
  # https://docs.victoriametrics.com/Cluster-VictoriaMetrics.html#list-of-command-line-flags
  spec:
    retentionPeriod: "30"
    replicationFactor: 3
    vmstorage:
      nodeSelector:
        worker-node: infra        
      tolerations:
      - key: type
        value: svc
        effect: NoSchedule
      image:
        tag: v1.92.1-cluster
      extraArgs:
        search.maxUniqueTimeseries: "100000000"
        dedup.minScrapeInterval: 15s
      replicaCount: 3
      storageDataPath: "/vm-data"
      storage:
        volumeClaimTemplate:
          spec:
            storageClassName: nfs-svc-01
            resources:
              requests:
                storage: 100Gi
      resources:
        limits:
          cpu: "5"
          memory: 5Gi
        requests:
          cpu: 1
          memory: "500Mi"
    vmselect:
      nodeSelector:
        worker-node: infra
      tolerations:
      - key: type
        value: svc
        effect: NoSchedule
      image:
        tag: v1.92.1-cluster
      replicaCount: 3
      cacheMountPath: "/select-cache"
      extraArgs:
        search.maxUniqueTimeseries: "100000000"
        dedup.minScrapeInterval: 15s
      storage:
        volumeClaimTemplate:
          spec:
            storageClassName: nfs-svc-01
            resources:
              requests:
                storage: 100Gi
      resources:
         limits:
           cpu: "5"
           memory: "5Gi"
         requests:
           cpu: 1
           memory: "500Mi"
    vminsert:
      nodeSelector:
        worker-node: infra 
      tolerations:
      - key: type
        value: svc
        effect: NoSchedule
      image:
        tag: v1.92.1-cluster
      replicaCount: 3
      extraArgs: {}
      resources:
         limits:
          cpu: "5"
          memory: 5Gi
         requests:
          cpu: 1
          memory: "500Mi"
```

```
vmagent:
  enabled: true
  annotations: {}
  # https://docs.victoriametrics.com/operator/api.html#vmagentremotewritespec
  # defined spec will be added to the remoteWrite configuration of VMAgent
  additionalRemoteWrites:
    []
    #- url: http://some-remote-write/api/v1/write
  # spec for VMAgent crd
  # https://docs.victoriametrics.com/operator/api.html#vmagentspec
  spec:
    nodeSelector:
      worker-node: infra
    tolerations:
    - key: type
      value: svc
      effect: NoSchedule
    selectAllByDefault: true
    image:
      tag: v1.92.1
    #remoteWrite:
    #  - url: http://some.write.url.ru/api/v1/write
    remoteWriteSettings:
      label:
        cluster_name: kubernetes
        env: prod
    resources:
      limits:
        cpu: 3
        memory: 5Gi
      requests:
        cpu: 1
        memory: 200Mi
    scrapeInterval: 15s
    externalLabels: ~
    extraArgs:
      promscrape.streamParse: "true"
```
