### ISSUE TITLE
Istio ingress gateway pods are not discovered

### ISSUE THREAD

**Issue by andrew-shevchyk** [VictoriaMetrics/VictoriaMetrics#4765]
### Is your question request related to a specific component?

vmagent

### Describe the question in detail

I started using Istio Ingress Gateway however after some time I noticed that its metrics are not available in VM Select UI.

The pods have all required annotations:
```
apiVersion: v1
kind: Pod
metadata:
  annotations:
    ...
    prometheus.io/path: /stats/prometheus
    prometheus.io/port: "15020"
    prometheus.io/scrape: "true"
labels:
    istio.io/rev: default
    service.istio.io/canonical-name: istio-ingressgateway-internal
    service.istio.io/canonical-revision: latest
    sidecar.istio.io/inject: "true"
  name: istio-ingressgateway-internal-7b794d8cfd-qgcr2
  namespace: istio-ingress-internal
spec:
...
```
but for some reason the pods are not included into the vmagent's Targets list.
During investigation I deployed nginx to the same namespace and to the same nodes where Istio GW was running and nginx's pods were discovered and scraped.

Do you have any ideas what can be done next?

### Troubleshooting docs

- [ ] General - https://docs.victoriametrics.com/Troubleshooting.html
- [X] vmagent - https://docs.victoriametrics.com/vmagent.html#troubleshooting
- [ ] vmalert - https://docs.victoriametrics.com/vmalert.html#troubleshooting
