### ISSUE TITLE
Migrating absence of metric query from Prometheus to vmalert/victoriametrics

### ISSUE THREAD

**Issue by j1t3ndr6** [VictoriaMetrics/VictoriaMetrics#4787]
### Is your question request related to a specific component?

Victoriametrics, vmalert

### Describe the question in detail

I am in process of migrating from Prometheus to victoriametrics and in old setup, Prometheus scrapes data at regular intervals and execute a rate query to find absence of a metrics(no data for metric). The rule is as follows:
```
  - alert: no_data_metric_alert
    expr: rate(site_result_time[3m]) == 0
    for: 5m
    labels:
      site_id: '{{$labels.site_id}}_no_data_metric'
      alertType: No Data Alert
```
This works fine in current setup of Prometheus as even when there is no new data, the last know data is returned in every scrape, so the **rate** query works.

However when using **vmalert** with **victoriametrics**, the **rate query** is not working as there is no data for the metric and as vmalert uses instant queries. I tried using **absent** and **absent_over_time** queries for vmalert, but in these case, the queries are not returning the series/labels, due to which I am not able to figure out which site has no data. Also tried **lag** and **count_over_time**. But none of these work when the data is absent for more than the duration as we get empty result.

Is there any alternate way or workaround to solve this using vmalert?

### Troubleshooting docs

- [X] General - https://docs.victoriametrics.com/Troubleshooting.html
- [ ] vmagent - https://docs.victoriametrics.com/vmagent.html#troubleshooting
- [X] vmalert - https://docs.victoriametrics.com/vmalert.html#troubleshooting
