### ISSUE TITLE
vmalert: add ability to customize `external.url` command line flag

### ISSUE THREAD

**Issue by dmitryk-dk** [VictoriaMetrics/VictoriaMetrics#4793]
### Is your feature request related to a problem? Please describe

Each customer or user who works with a multitenant setup should have the possibility to change `external.url` flag. It will help correctly define the source URL in the alerts per tenant, and this improvement can enable to use of labels to build the correct URL per tenant. 

### Describe the solution you'd like

It would be great if `external.url` supports templating like `external.alert.source` does. 
For example, if an alerting rule, we have those fields
```
          labels:
            severity: critical
            explore: "https://127.0.0.1:3000/explore?path
            dashboard: 'https://127.0.0.1:3000/path'
```
We can define in `external.url` dashboard URL  {{$$labels.dashboard}}.
