### ISSUE TITLE
vmauth: context canceled.

### ISSUE THREAD

**Issue by hasanawad94** [VictoriaMetrics/VictoriaMetrics#4794]
### Is your question request related to a specific component?

vmauth

### Describe the question in detail

Trying out VMauth and Prometheus before committing to it.
I did a barebones setup where I have a Prometheus scraping some job and I want its remote write to go through VMauth with username and password.

I see that it's getting through VMauth to VMinsert but sometimes VMauth logs:

> cannot proxy the request to vminsert:8480/vminsert/insert/0/prometheus/api/v1/write context canceled.

Is this happening cause of some random network timeouts that can be fixed with some sort of flag adjustment, or should I be worried?

VMauth config:
```
users:
    - username: "cluster-select-account-123"
       password: "pass"
       url_prefix: "http://vminsert:8480/insert/0/prometheus"
```

Prometheus config:

```
remoteWrite:
   - url: http://victoria-metrics-auth:8427/api/v1/write
     basicAuth:
       username:
         key: username
         name: vm-auth-secret
       password:
         key: password
         name: vm-auth-secret
```

### Troubleshooting docs

- [X] General - https://docs.victoriametrics.com/Troubleshooting.html
- [X] vmagent - https://docs.victoriametrics.com/vmagent.html#troubleshooting
- [X] vmalert - https://docs.victoriametrics.com/vmalert.html#troubleshooting
