### ISSUE TITLE
vmauth: How can I remove x-server-hostname header in vmauth response

### ISSUE THREAD

**Issue by rightly** [VictoriaMetrics/VictoriaMetrics#4825]
### Is your question request related to a specific component?

vmauth v1.91.3

### Describe the question in detail

How can I remove x-server-hostname header in vmauth response? (for security)

### Troubleshooting docs

- [ ] General - https://docs.victoriametrics.com/Troubleshooting.html
- [ ] vmagent - https://docs.victoriametrics.com/vmagent.html#troubleshooting
- [ ] vmalert - https://docs.victoriametrics.com/vmalert.html#troubleshooting

**Comment by rightly** [comment]
@Amper 
Thank you for your positive review.
If it is added as a feature later, we will use it.

**Comment by valyala** [comment]
The commit b18eed34274dbd6fda0497afe43bb3b7e500edd0 adds ability to manipulate (set and/or remove) response headers in [vmauth](https://docs.victoriametrics.com/vmauth.html) via `response_headers` configuration option. Response headers are removed when specifying an empty header value. For example, the `X-Server-Hostname` response header is removed in the response to the user `foo` by specifying the following `response_headers` section:

```yaml
users:
- username: "foo"
  password: "***"
  response_headers:
  - "X-Server-Hostname:"
```

It is also possible to override response headers or to set new response headers. For example, the following `-auth.config` overrides `X-Server-Hostname` response header to `foobar`, and additionally sets `Foo` response header to `xxx` value:

```yaml
users:
- username: "foo"
  password: "***"
  response_headers:
  - "X-Server-Hostname: foobar"
  - "Foo: xxx"
```

This commit will be included in the next release. In the mean time it is possible to build `vmauth` from this commit according to [these docs](https://docs.victoriametrics.com/vmauth.html#how-to-build-from-sources) and verify whether it works as expected.
