### ISSUE TITLE
CPU and RAM surge when the vmstore component starts deleting indexdb 

### ISSUE THREAD

**Issue by ScmTble** [VictoriaMetrics/VictoriaMetrics#4873]
### Describe the bug

Using Victoria single ，CPU and RAM surge when the vmstore component starts deleting indexdb ，Vmui is unable to perform queries

### To Reproduce
``` yaml
apiVersion: apps/v1
kind: StatefulSet
metadata:
  namespace: monitoring
  labels:
    app: victoria-single
  name: victoria-single
spec:
  serviceName: victoria-single
  selector:
    matchLabels:
      app: victoria-single
  replicas: 1
  podManagementPolicy: OrderedReady
  template:
    metadata:
      labels:
        app: victoria-single
    spec:
      automountServiceAccountToken: true
      containers:
        - name: victoria-single
          image: "victoriametrics/victoria-metrics:v1.93.0"
          imagePullPolicy: "IfNotPresent"
          args:
            - "--retentionPeriod=1d"
            - "--storageDataPath=/storage"
            - -promscrape.config=/scrapeconfig/scrape.yml
            - --envflag.enable=true
            - --envflag.prefix=VM_
            - --loggerFormat=json
          ports:
            - name: http
              containerPort: 8428
          livenessProbe:
            failureThreshold: 10
            httpGet:
              path: /health
              port: 8428
              scheme: HTTP
            initialDelaySeconds: 30
            periodSeconds: 30
            timeoutSeconds: 5
          readinessProbe:
            failureThreshold: 3
            httpGet:
              path: /health
              port: http
            initialDelaySeconds: 5
            periodSeconds: 15
            timeoutSeconds: 5
          resources: {}
          volumeMounts:
            - name: server-volume
              mountPath: /storage
              subPath:
            - name: scrapeconfig
              mountPath: /scrapeconfig
      terminationGracePeriodSeconds: 60
      volumes:
        - name: scrapeconfig
          configMap:
            name: victoria-single-scrapeconfig
  volumeClaimTemplates:
    - metadata:
        name: server-volume
      spec:
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: "8Gi"
```

### Version

victoria-metrics-20230812-215739-tags-v1.93.0-0-g59f7d810c9

### Logs

<img width="1581" alt="image" src="https://github.com/VictoriaMetrics/VictoriaMetrics/assets/56188521/e5e634ad-4bad-4ae8-ac5c-ece7cb356432">

### Screenshots

<img width="1857" alt="image" src="https://github.com/VictoriaMetrics/VictoriaMetrics/assets/56188521/9fa44942-3b08-4a9c-9380-53d150f0ddf7">

### Used command-line flags

- "--retentionPeriod=1d"
