### ISSUE TITLE
vmauth: add an ability to specify {reload|flags|metrics|ppro}AuthKey via external Kubernetes Secret

### ISSUE THREAD

**Issue by arseny-zinchenko** [VictoriaMetrics/VictoriaMetrics#4881]
### Describe the solution you'd like

Currently, in the `victoria-metrics-auth` Helm chart v ~0.3.3 the only way to specify an AuthKey for an endpoint is to hardcode it to the `values.yaml`:

```
  extraArgs:
    reloadAuthKey: password
    flagsAuthKey: password
    metricsAuthKey: password
    pprofAuthKey: password
```

Would be great to add a way to set a Secrets's name:

```
  extraArgs:
    reloadAuthKey: 
      secretName: vmauth-config-secret
    flagsAuthKey: 
      secretName: vmauth-config-secret
    metricsAuthKey:
      secretName: vmauth-config-secret
    pprofAuthKey:
      secretName: vmauth-config-secret
```

And have set keys in a Secret like:

```
apiVersion: v1
kind: Secret
metadata:
  name: vmauth-config-secret
stringData:
 reloadKey: password
 flagsKey: password
 metricsKey: password
 pprofKey: password
```

**Comment by f41gh7** [comment]
Hello,

  It must be already possible with env vars.

```
apiVersion: v1
kind: Secret
metadata:
  name: vmauth-config-secret
stringData:
 reloadKey: password
 flagsKey: password
 metricsKey: password
 pprofKey: password
---
env:
- name: VM_reloadAuthKey
  valueFrom:
    secretKeyRef:
      key:  reloadKey
      secret: vmauth-config-secret
```

 https://docs.victoriametrics.com/#environment-variables
