### ISSUE TITLE
Chained `if` conditions for relabeling not supported in vmagent CRD

### ISSUE THREAD

**Issue by towolf** [VictoriaMetrics/VictoriaMetrics#4888]
### Describe the bug

In the code for `IfExpression` it states that two mode are supported, a single string matcher and a chained mode with an array of conditions which are combined with OR:

https://github.com/VictoriaMetrics/VictoriaMetrics/blob/master/lib/promrelabel/if_expression.go#L13-L23

However the CRD for vmagent does not support this: 
![image](https://github.com/VictoriaMetrics/VictoriaMetrics/assets/345210/956e1253-9fe2-47ea-83ac-9c1477e7c73c)

We would like to use a chained config to avoid a gnarly regex matcher, like this:

```yaml
          inlineUrlRelabelConfig:
            - if:
                # Limit metrics sent to the central obs cluster to this set (keep)
                - '{job=~"(kube-etcd|agones.+|node-exporter|apiserver)"}'
                # Also pass on the metrics from recording rules created by
                # kube-prometheus-stack and vmstack to make the multi-cluster k-p-s
                # dashboards work
                - '{__name__=~"(cluster:namespace|cluster:node_cpu|cluster_quantile:|code_resource:|instance:|instance_device:|namespace_cpu:|namespace_memory:|namespace_workload_pod:|node_namespace_pod_container).+"}'
              action: keep
            - if:
                # Drop excessively noisy apiserver buckets.
                - '{__name__="apiserver_request_duration_seconds_bucket"}'
                - '{__name__="apiserver_request_slo_duration_seconds_bucket"}'
              action: drop



### To Reproduce

Add a relabel config like this to the vmagent CR:

```yaml
if:
 - 'foo{bar="baz"}'
 - '{x=~"y"}'
 ```

### Version

`image: docker.io/victoriametrics/vmagent:v1.93.0`
