### ISSUE TITLE
vmalert: how to let vmalert using more resources (CPU, MEM) to descrease the evalutaion time

### ISSUE THREAD

**Issue by tantm3** [VictoriaMetrics/VictoriaMetrics#4926]
### Is your question request related to a specific component?

Related to the VMAlert component
More information:
- Using VictoriaMetrics Cluster versions, deploy in K8s env
- Version: v1.87.6

### Describe the question in detail

Hi everyone,
I am in the process of benchmarking the VMAlert component to know the performance of it.
My benchmark steps are:
-  Deploy a VMAlert pod (resources limit: 1CPU x 1GB MEM) to K8s that have only one alarm expression:
```
groups:
- interval: 60s
  name: benchmark-0
  rules:
  - alert: Benchmark alarm 0 test % change values
    annotations:
      summary: 'Benchmark alarm 0 {{ $labels.hostname }} has increase {{ $value }}% > 80% for 2m'
    expr: (avg(avg_over_time(benchmark_alarm_200[2m])) by (hostname) - avg(avg_over_time(benchmark_alarm_200[2m] offset 5m)) by (hostname))/(avg(avg_over_time(benchmark_alarm_200[2m] offset 5m)) by (hostname))*100 >= 0
    for: 2m
    labels:
      severity: benchmark
``` 
- And then start to send metric `benchmark_alarm_200` with 100 hostname tags.
- I followed the Grafana dashboard for VMAlert and saw that the `avg evaluation duration` is ~100ms
![benchmark-1](https://github.com/VictoriaMetrics/VictoriaMetrics/assets/112939454/a4e764db-a979-4297-9f8b-a5ac3be83791)
- After that, I increased the hostname tags from 100 to 200 and saw that the ` avg evaluation duration` is ~200ms 
![benchmark-2](https://github.com/VictoriaMetrics/VictoriaMetrics/assets/112939454/d34dc2ec-9e3f-4e74-9386-afb7365315c2)

I think it totally makes sense about the increment of the evaluation time, but I don't know why VMAlert did not use more resources to decrease the evaluation time, because when I looked at the resources chart from VMAlert, I saw that it used dramatically low CPU and Memory:

![cpu](https://github.com/VictoriaMetrics/VictoriaMetrics/assets/112939454/0aa72bac-c3b3-4457-9b39-79fc45e2cc7c)
![memory](https://github.com/VictoriaMetrics/VictoriaMetrics/assets/112939454/73fe660b-e7db-44b2-8088-9b350920d488)

So, Is there a configuration that I could use to tune the performance of the VMAlert component?
Thanks for your time reading my question!

### Troubleshooting docs

- [X] General - https://docs.victoriametrics.com/Troubleshooting.html
- [ ] vmagent - https://docs.victoriametrics.com/vmagent.html#troubleshooting
- [X] vmalert - https://docs.victoriametrics.com/vmalert.html#troubleshooting
