### ISSUE TITLE
[vmagent] consul_sd filter does't work correctly

### ISSUE THREAD

**Issue by iceman2077** [VictoriaMetrics/VictoriaMetrics#4930]
### Describe the bug

When I configure consul_sd filter, I expect that as a target in the job, I will get only services that have certain metadata.
But after applying I got all the targets from the consul.

### To Reproduce

Configuratiom

```
scrape_configs:
- job_name: vmagent-consul
  honor_labels: true
  consul_sd_configs:
  - server: consul-consul-server.consul.svc.cluster.local:8500
    token: <secret>
    datacenter: ""
    username: ""
    password: null
    filter: ServiceMeta.app == test_app
```

### Version

victoriametrics/vmagent:v1.92.0
consul_version: 1.16.0

### Logs

2023-08-31T12:08:56.672Z [TRACE] agent.server: rpc_server_call: method=Coordinate.Update errored=false request_type=write rpc_type=net/rpc leader=true target_datacenter=dc1 locality=local
2023-08-31T12:08:56.692Z [INFO]  agent.http: Request cancelled: method=GET url="/v1/health/service/node_exporter?dc=dc1&stale&index=3216531&wait=525s" from=10.0.116.147:33248 error="context canceled"
2023-08-31T12:08:56.692Z [INFO]  agent.http: Request cancelled: method=GET url="/v1/health/service/node_exporter?dc=dc1&stale&index=3216531&wait=525s" from=10.0.116.147:55436 error="context canceled"
2023-08-31T12:08:56.692Z [DEBUG] agent.http: Request finished: method=GET url="/v1/health/service/node_exporter?dc=dc1&stale&index=3216531&wait=525s" from=10.0.116.147:55436 latency=24.087541412s
2023-08-31T12:08:56.692Z [DEBUG] agent.http: Request finished: method=GET url="/v1/health/service/node_exporter?dc=dc1&stale&index=3216531&wait=525s" from=10.0.116.147:33248 latency=24.190756679s
2023-08-31T12:08:56.693Z [INFO]  agent.http: Request cancelled: method=GET url="/v1/health/service/consul?dc=dc1&stale&index=3213441&wait=525s" from=10.0.116.147:46716 error="context canceled"
2023-08-31T12:08:56.693Z [DEBUG] agent.http: Request finished: method=GET url="/v1/health/service/consul?dc=dc1&stale&index=3213441&wait=525s" from=10.0.116.147:46716 latency=4m52.688781498s
2023-08-31T12:08:58.283Z [DEBUG] agent.http: Request finished: method=GET url=/v1/agent/self from=10.0.115.136:39232 latency=1.191386ms
2023-08-31T12:08:58.290Z [TRACE] agent.server: rpc_server_call: method=Catalog.ListServices errored=false request_type=read rpc_type=net/rpc leader=true allow_stale=true blocking=false target_datacenter=dc1 locality=local
2023-08-31T12:08:58.293Z [DEBUG] agent.http: Request finished: method=GET url="/v1/health/service/consul?dc=dc1&stale&index=0&wait=525s" from=10.0.115.136:39248 latency="282.049µs"
2023-08-31T12:08:58.294Z [TRACE] agent.server: rpc_server_call: method=Health.ServiceNodes errored=false request_type=read rpc_type=net/rpc leader=true allow_stale=true blocking=false target_datacenter=dc1 locality=local
2023-08-31T12:08:58.304Z [DEBUG] agent.http: Request finished: method=GET url="/v1/health/service/node_exporter?dc=dc1&stale&index=0&wait=525s" from=10.0.115.136:39262 latency=6.008033ms
2023-08-31T12:08:58.319Z [DEBUG] agent.http: Request finished: method=GET url=/v1/agent/self from=10.0.115.136:39266 latency=1.235829ms
2023-08-31T12:08:58.403Z [TRACE] agent.server: rpc_server_call: method=Catalog.ListServices errored=false request_type=read rpc_type=net/rpc leader=true allow_stale=true blocking=false target_datacenter=dc1 locality=local
2023-08-31T12:08:58.403Z [DEBUG] agent.http: Request finished: method=GET url="/v1/catalog/services?dc=dc1&stale&filter=ServiceMeta.app+%3D%3D+test_app&index=0&wait=525s" from=10.0.115.136:39280 latency="737.823µs"
2023-08-31T12:08:58.410Z [TRACE] agent.server: rpc_server_call: method=Health.ServiceNodes errored=false request_type=read rpc_type=net/rpc leader=true allow_stale=true blocking=false target_datacenter=dc1 locality=local
2023-08-31T12:08:58.412Z [DEBUG] agent.http: Request finished: method=GET url="/v1/health/service/node_exporter?dc=dc1&stale&index=0&wait=525s" from=10.0.115.136:39280 latency=2.764755ms
2023-08-31T12:08:58.902Z [TRACE] agent.server: rpc_server_call: method=Status.Leader errored=false request_type=read rpc_type=net/rpc leader=true allow_stale=false blocking=false target_datacenter=dc1 locality=local
2023-08-31T12:08:58.902Z [DEBUG] agent.http: Request finished: method=GET url=/v1/status/leader from=127.0.0.1:33810 latency="119.862µs"

### Additional information

In the consul logs I can see that it receives requests with filter and without it.

**Comment by iceman2077** [comment]
yes, it returns only required targets, that fit this filter 
this is response:
```
{
  "node_exporter": [
    "node=kafka-003",
    "node=kafka-001",
    "app=test_app",
    "node=kafka-002"
  ]
}
```
but I don't know why it returns this "app=test_app"

**Comment by zekker6** [comment]
@iceman2077 vmagent fetches this list of services with applied filters and then watches list of targets matched by those services.
Could you verify that these services are matching only required targets that you expect to see?

**Comment by iceman2077** [comment]
As far as I can see it returns a list of tags( not services ) from the services that match this filter.
I deleted this tag("app=test_app") from the service and I got this list
```
{
  "node_exporter": [
    "node=kafka-001",
    "node=kafka-002",
    "node=kafka-003"
  ]
}
```

**Comment by zekker6** [comment]
@iceman2077 Response format here is:
```
{
  "service_name": [
    "tag1",
    "tag2"
  ]
}
```

**Comment by iceman2077** [comment]
Yes, this is what I get on this request

**Comment by zekker6** [comment]
@iceman2077 Does this service match only targets that you expect vmagent to discover as well?
vmagent discovers this service and fetches all nodes which are registered for this service.

**Comment by iceman2077** [comment]
Yes, it returns only the services that I expect

**Comment by zekker6** [comment]
@iceman2077 But does those services include only nodes which you expect to be the targets?

**Comment by iceman2077** [comment]
yes

**Comment by zekker6** [comment]
@iceman2077 In this case I'm not sure if I understand what is not matching your expectation.
Based on provided logs:
vmagent discovered services with the supplied filter
```
 2023-08-31T12:08:58.403Z [DEBUG] agent.http: Request finished: method=GET url="/v1/catalog/services?dc=dc1&stale&filter=ServiceMeta.app+%3D%3D+test_app&index=0&wait=525s" from=10.0.115.136:39280 latency="737.823µs"
```
and pulled list of targets for this service:
```
 2023-08-31T12:08:58.412Z [DEBUG] agent.http: Request finished: method=GET url="/v1/health/service/node_exporter?dc=dc1&stale&index=0&wait=525s" from=10.0.115.136:39280 latency=2.764755ms
```

Could you elaborate on what is mismatching your expectation here?

**Comment by iceman2077** [comment]
This request is correct,
I expect to get only filtered services to the job target list, but I get a list of all services from consul

**Comment by iceman2077** [comment]
config
```
global:
  scrape_interval: 30s
  external_labels:
    prometheus: monitoring/vmagent-consul
scrape_configs:
- job_name: vmagent-consul
  honor_labels: true
  headers:
  - 'Authorization: Basic xxx'
  relabel_configs:
  - source_labels: [__meta_consul_tags]
    target_label: hostname
    regex: .*,hostname=([^,]+),.*
    replacement: ${1}
  - source_labels: [__meta_consul_tags]
    target_label: environment
    regex: .*,environment=([^,]+),.*
    replacement: ${1}
  - source_labels: [__meta_consul_tags]
    target_label: instance
    regex: .*,instance=([^,]+),.*
    replacement: ${1}
  - source_labels: [__meta_consul_tags]
    target_label: cluster
    regex: .*,cluster=([^,]+),.*
    replacement: ${1}
  - source_labels: [__meta_consul_tags]
    target_label: node
    regex: .*,node=([^,]+),.*
    replacement: ${1}
  - source_labels: [__meta_consul_tags]
    target_label: service
    regex: .*,service=([^,]+),.*
    replacement: ${1}
  consul_sd_configs:
  - server: consul-server.consul.svc.cluster.local:8500
    token: <secret>
    datacenter: ""
    username: ""
    password: null
    services:
    - node_exporter
    filter: ServiceMeta.app == test_app
    ```
    
    list of discovered targets
    ```
    job=vmagent-consul (17/20 up)
	state=up, endpoint=http://172.30.10.1:9100/metrics, labels={instance="172.30.10.1:9100",job="vmagent-consul",node="node-1",service="node_exporter"}, scrapes_total=10952, scrapes_failed=0, last_scrape=11726ms ago, scrape_duration=44ms, samples_scraped=1306, error=
	state=up, endpoint=http://172.30.10.2:9100/metrics, labels={instance="172.30.10.2:9100",job="vmagent-consul",node="node-2",service="node_exporter"}, scrapes_total=10951, scrapes_failed=0, last_scrape=23455ms ago, scrape_duration=43ms, samples_scraped=1306, error=
	state=up, endpoint=http://172.30.10.3:9100/metrics, labels={instance="172.30.10.3:9100",job="vmagent-consul",node="node-3",service="node_exporter"}, scrapes_total=10952, scrapes_failed=0, last_scrape=8552ms ago, scrape_duration=43ms, samples_scraped=1306, error=
	state=up, endpoint=http://172.30.11.1:9100/metrics, labels={instance="172.30.11.1:9100",job="vmagent-consul",node="node-prod-1",service="node_exporter"}, scrapes_total=10952, scrapes_failed=0, last_scrape=13874ms ago, scrape_duration=56ms, samples_scraped=1311, error=
	state=up, endpoint=http://172.30.11.2:9100/metrics, labels={instance="172.30.11.2:9100",job="vmagent-consul",node="node-prod-2",service="node_exporter"}, scrapes_total=10952, scrapes_failed=0, last_scrape=16211ms ago, scrape_duration=50ms, samples_scraped=1306, error=
	state=up, endpoint=http://172.30.11.3:9100/metrics, labels={instance="172.30.11.3:9100",job="vmagent-consul",node="node-prod-3",service="node_exporter"}, scrapes_total=10951, scrapes_failed=0, last_scrape=23357ms ago, scrape_duration=59ms, samples_scraped=1306, error=
	state=up, endpoint=http://172.30.12.1:9100/metrics, labels={instance="172.30.12.1:9100",job="vmagent-consul",node="node-stage-1",service="node_exporter"}, scrapes_total=10951, scrapes_failed=0, last_scrape=23793ms ago, scrape_duration=41ms, samples_scraped=1306, error=
	state=up, endpoint=http://172.30.12.2:9100/metrics, labels={instance="172.30.12.2:9100",job="vmagent-consul",node="node-stage-2",service="node_exporter"}, scrapes_total=10952, scrapes_failed=0, last_scrape=8404ms ago, scrape_duration=44ms, samples_scraped=1306, error=
	state=up, endpoint=http://172.30.12.3:9100/metrics, labels={instance="172.30.12.3:9100",job="vmagent-consul",node="node-stage-3",service="node_exporter"}, scrapes_total=10951, scrapes_failed=0, last_scrape=28805ms ago, scrape_duration=39ms, samples_scraped=1306, error=
	state=up, endpoint=http://172.30.13.1:9100/metrics, labels={instance="172.30.13.1:9100",job="vmagent-consul",node="node-ls-1",service="node_exporter"}, scrapes_total=10951, scrapes_failed=0, last_scrape=23126ms ago, scrape_duration=36ms, samples_scraped=1306, error=
	state=up, endpoint=http://172.30.13.2:9100/metrics, labels={instance="172.30.13.2:9100",job="vmagent-consul",node="node-ls-2",service="node_exporter"}, scrapes_total=10952, scrapes_failed=0, last_scrape=2957ms ago, scrape_duration=48ms, samples_scraped=1306, error=
	state=up, endpoint=http://172.30.13.3:9100/metrics, labels={instance="172.30.13.3:9100",job="vmagent-consul",node="node-ls-3",service="node_exporter"}, scrapes_total=10951, scrapes_failed=0, last_scrape=20917ms ago, scrape_duration=49ms, samples_scraped=1306, error=
	state=down, endpoint=http://172.30.11.116:9100/metrics, labels={instance="172.30.11:9100",job="vmagent-consul",node="kafka-001"}, scrapes_total=10241, scrapes_failed=10241, last_scrape=5598ms ago, scrape_duration=7ms, samples_scraped=0, error=unexpected status code returned when scraping "http://172.30.11.116:9100/metrics": 401; expecting 200; response body: "Unauthorized\n"
	state=down, endpoint=http://172.30.11.163:9100/metrics, labels={instance="172.30.11.163:9100",job="vmagent-consul",node="kafka-003"}, scrapes_total=10951, scrapes_failed=10951, last_scrape=28736ms ago, scrape_duration=1ms, samples_scraped=0, error=unexpected status code returned when scraping "http://172.30.11.163:9100/metrics": 401; expecting 200; response body: "Unauthorized\n"
	state=down, endpoint=http://172.30.11.12:9100/metrics, labels={instance="172.30.11.12:9100",job="vmagent-consul",node="kafka-002"}, scrapes_total=10951, scrapes_failed=10951, last_scrape=29677ms ago, scrape_duration=1ms, samples_scraped=0, error=unexpected status code returned when scraping "http://172.30.11.12:9100/metrics": 401; expecting 200; response body: "Unauthorized\n"
	state=up, endpoint=http://172.30.36.32:9100/metrics, labels={instance="172.30.36.32:9100",job="vmagent-consul",node="nginx-001"}, scrapes_total=10952, scrapes_failed=0, last_scrape=5974ms ago, scrape_duration=493ms, samples_scraped=3065, error=
	state=up, endpoint=http://172.30.37.81:9100/metrics, labels={instance="172.30.37.81:9100",job="vmagent-consul",node="redis-1"}, scrapes_total=10952, scrapes_failed=0, last_scrape=15655ms ago, scrape_duration=156ms, samples_scraped=2346, error=
	state=up, endpoint=http://172.30.37.84:9100/metrics, labels={instance="172.30.37.84:9100",job="vmagent-consul",node="redis-2"}, scrapes_total=10952, scrapes_failed=0, last_scrape=6361ms ago, scrape_duration=82ms, samples_scraped=2342, error=
	state=up, endpoint=http://172.30.37.85:9100/metrics, labels={instance="172.30.37.85:9100",job="vmagent-consul",node="redis-3"}, scrapes_total=10951, scrapes_failed=0, last_scrape=28660ms ago, scrape_duration=99ms, samples_scraped=2343, error=
	state=up, endpoint=http://172.30.37.175:9100/metrics, labels={instance="172.30.37.175:9100",job="vmagent-consul",node="nginx-test"}, scrapes_total=10951, scrapes_failed=0, last_scrape=23457ms ago, scrape_duration=456ms, samples_scraped=3065, error=
```
services:
we have 1 service by name:
node_exporter
and under this service, we have 20 instances:
```
node="node-1"
node="node-2"
node="node-3"
node="node-prod-1"
node="node-prod-2"
node="node-prod-3"
node="node-stage-1"
node="node-stage-2"
node="node-stage-3"
node="node-ls-1"
node="node-ls-2"
node="node-ls-3"
node="kafka-001"
node="kafka-003"
node="kafka-002"
node="nginx-001"
node="redis-1"
node="redis-2"
node="redis-3"
node="nginx-test"
```
