### ISSUE TITLE
Data lost when one of HA prometheus shutdown

### ISSUE THREAD

**Issue by AEGQ** [VictoriaMetrics/VictoriaMetrics#496]
**Describe the bug**
data lost when one of HA prometheus shutdown

**To Reproduce**
HA prometheus with  two replicas and same remote_write，stop one of them。

**Expected behavior**
no data lost  when one of HA prometheus shutdown or  restart.

**Screenshots**
![image](https://user-images.githubusercontent.com/16302289/82138288-f21d4980-9851-11ea-84b0-dd1c47339dbd.png)

**Version**

HA prometheus with  two replicas:  
```
prom/prometheus:v2.18.1
```
VM: 
```
# docker run --rm -it victoriametrics/vmselect:v1.35.3-cluster -version
vmselect-20200507-203608-tags-v1.35.3-cluster-0-g657c3e3f
# docker run --rm -it victoriametrics/vminsert:v1.35.3-cluster -version
vminsert-20200507-203324-tags-v1.35.3-cluster-0-g657c3e3f
# docker run --rm -it victoriametrics/vmstorage:v1.35.3-cluster -version
vmstorage-20200507-203853-tags-v1.35.3-cluster-0-g657c3e3f

```

**Used command-line flags**
vminsert:
```
        - --storageNode=victoria-metrics-cluster-vmstorage-0.victoria-metrics-cluster-vmstorage.monitoring.svc.cluster.local:8400
        - --storageNode=victoria-metrics-cluster-vmstorage-1.victoria-metrics-cluster-vmstorage.monitoring.svc.cluster.local:8400
        - --storageNode=victoria-metrics-cluster-vmstorage-2.victoria-metrics-cluster-vmstorage.monitoring.svc.cluster.local:8400
```

vmselect:
```
        - --cacheDataPath=/cache
        - --storageNode=victoria-metrics-cluster-vmstorage-0.victoria-metrics-cluster-vmstorage.monitoring.svc.cluster.local:8401
        - --storageNode=victoria-metrics-cluster-vmstorage-1.victoria-metrics-cluster-vmstorage.monitoring.svc.cluster.local:8401
        - --storageNode=victoria-metrics-cluster-vmstorage-2.victoria-metrics-cluster-vmstorage.monitoring.svc.cluster.local:8401
        - --dedup.minScrapeInterval=60s
```

vmstorage:
```
        - --retentionPeriod=1
        - --storageDataPath=/storage
        - --dedup.minScrapeInterval=60s
```

HA prometheus with  two replicas and same remote_write:
```
remote_write:
- url: http://victoria-metrics-cluster-vminsert:8480/insert/0/prometheus
  remote_timeout: 30s
  queue_config:
    capacity: 500
    max_shards: 1000
    min_shards: 1
    max_samples_per_send: 100
    batch_send_deadline: 5s
    min_backoff: 30ms
    max_backoff: 100ms
```
