### ISSUE TITLE
Some metrics are lost and I don't know how to debug it

### ISSUE THREAD

**Issue by lapo-luchini** [VictoriaMetrics/VictoriaMetrics#4972]
### Is your question request related to a specific component?

I don't know where the data is lost, I can't find any error and would like guidance on how to proceed on my debug.

### Describe the question in detail

I have a central single-node Victoria Metrics and a few decentralized `vmagent`s.
I have some values that are scraped correctly but cannot be found in the database with a query.

```mermaid
graph TD;
  vmagent1 --> vmauth;
  vmagent2 --> vmauth;
  vmagent3 --> vmauth;
  vmauth --> victoria-metrics;
```

This happens across different metrics in different scrapes, I will take one just as an example, but I have found no common rules among the "lost" metrics; they are all around (and rare enough, but still bothersome/alarming).

On http://vmagent1:8429/targets I can see:

| Endpoint | State | Labels | Debug relabeling | Scrapes | Errors | Last Scrape | Duration | Samples | Last error |
| -| -| - | - | - | - | - | - | - | - |
| http://vmagent1:9100/metrics (response) | UP | {instance="vmagent1:9100", job="node_exporter"} | target metrics | 887 | 0 | 12372ms ago | 4ms | 185

And the number of values seems to be correct:
```sh
% xh http://localhost:9100/metrics | egrep -cv '^#'
185
```

The server's `vmagent.log` reports no errors in writing and I get updated values for most of those 185 values. But… `count({datacenter="DC1",job="node_exporter"})` returns 122 (in internal `/vmui` and also in Grafana Explorer).

The `job` label is added by `vmagent` scraping rules:

```yaml
- job_name: 'node_exporter'
  static_configs:
  - targets:
    - vmagent1:9100
```

The `datacenter` label is forced by `vmauth`:

```yaml
users:

- username: "user1"
  password: "pass1"
  url_map:
  - src_paths: ["/api/v1/write"]
    url_prefix: "http://localhost:8428?extra_label=datacenter=DC1"
```

A missing metric is one I noticed because is used in Grafana to populate pop-ups in the upper-left corner, and that is `node_uname_info`, it just doesn't show up (and it is among the 185 scraped by connecting to node_exporter's :9100 output).

### Troubleshooting docs

- [x] General - https://docs.victoriametrics.com/Troubleshooting.html
- [x] vmagent - https://docs.victoriametrics.com/vmagent.html#troubleshooting
- [x] vmalert - https://docs.victoriametrics.com/vmalert.html#troubleshooting
