### ISSUE TITLE
When k8s deployment uses statefulset to deploy vmagent, how to keep the number of replicas consistent with promscrape.cluster.membersCount？

### ISSUE THREAD

**Issue by luzejia** [VictoriaMetrics/VictoriaMetrics#5026]
### Is your question request related to a specific component?

vmagent

### Describe the question in detail

I encountered a problem:

When I expand the number of instances of vmagent's statefulset, the value of promscrape.cluster.membersCount in the startup parameters of vmagent cluster mode will not change accordingly, which will cause collection exceptions.

like this: when we modify replicas, the --promscrape.cluster.membersCount will not change. when we inadvertently adjust the value of replicas but do not adjust --promscrape.cluster.membersCount, it will cause collection exceptions.
```
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: vmagent
  labels:
    app: vmagent
spec:
  serviceName: vmagent
  replicas: 8
  selector:
    matchLabels:
      app: vmagent
  template:
    metadata:
      labels:
        app: vmagent

    spec:
      serviceAccountName: vmagent
      containers:
      - image: victoriametrics/vmagent:v1.92.1
        name: vmagent
        args:
        - --promscrape.cluster.membersCount=4
        ...
        ...
```

### Troubleshooting docs

- [ ] General - https://docs.victoriametrics.com/Troubleshooting.html
- [ ] vmagent - https://docs.victoriametrics.com/vmagent.html#troubleshooting
- [ ] vmalert - https://docs.victoriametrics.com/vmalert.html#troubleshooting
