### ISSUE TITLE
Spontaneously, random vmstorage of VM cluster start to failing answers (or answer with low speed) for vminsert/vmselect

### ISSUE THREAD

**Issue by ruslanboyarsky** [VictoriaMetrics/VictoriaMetrics#5045]
### Is your question request related to a specific component?

1. vmstorage

## Description
Hi, 
Looks like we observe similar issue in our VM cluster (v1.87.6-cluster). 

Spontaneously, random vmstorage node of our VM cluster start to have the following symptoms:
1. LA is grown:  ` value > 100` 
2. we see a lot of open connects. `ss -nar | wc -l  > 40000`
3. amount of gorouting is grown:  `> 40000`
4. Open TCP connections of vmstorage is grown as well
The node starts to slow process any incoming requests and in results, inserts start to process incoming requests slowly. As result, throughput of out VM cluster is degraded
   
![image](https://github.com/VictoriaMetrics/VictoriaMetrics/assets/112613645/c3095d6b-14a2-4351-b7bd-c9fda9f49705)
![image](https://github.com/VictoriaMetrics/VictoriaMetrics/assets/112613645/e48bb4e3-b809-4862-8734-c0652fc28858)

As well, I've collected cpu and goroutins profiles:
[pprof.zip](https://github.com/VictoriaMetrics/VictoriaMetrics/files/12688539/pprof.zip)

Let me know if you need more info from my side

## How to reproduce
There is no steps how to reproduce. It's spontaneous incident

## Our symptoms similar with  tickets 
https://github.com/VictoriaMetrics/VictoriaMetrics/issues/2211
https://github.com/VictoriaMetrics/VictoriaMetrics/issues/5043

## Our configuration overview
- 5 vmstorage
```
    command:
      - -envflag.enable=false
      - -storageDataPath=/vmstorage-data
      - -httpListenAddr=0.0.0.0:8482
      - -vminsertAddr=0.0.0.0:8400
      - -vmselectAddr=0.0.0.0:8401
      - -dedup.minScrapeInterval=30s
      - -retentionPeriod=30d
      - -loggerLevel=INFO
      - -memory.allowedPercent=50
      - -precisionBits=64
      - -search.maxTagKeys=20000
      - -search.maxTagValues=20000
      ....
    mem_limit: 220g
    network_mode: host
```
- 5 vminsert
```
      - -envflag.enable=false
      - -relabelConfig=/sage-relabel.yml
      - -storageNode=node-1:8400
      - -storageNode=node-1:8400
      - -storageNode=node-1:8400
      - -storageNode=node-1:8400
      - -storageNode=node-1:8400
      - -httpListenAddr=0.0.0.0:8480
      - -opentsdbListenAddr=0.0.0.0:4242
      - -dropSamplesOnOverload=False
      - -disableRerouting=True
      - -loggerLevel=INFO
      - -memory.allowedPercent=50
      - -replicationFactor=2
      - -maxConcurrentInserts=32
      - -maxInsertRequestSize=67108864
```
- 30 small vmselects

## Actions that we already tried
1. We tried to set smallMergeConcurrency=1 and bigMergeConcurrency=1 on vmstorage - no results, issue continue occurring

### Troubleshooting docs

- [X] General - https://docs.victoriametrics.com/Troubleshooting.html
- [X] vmagent - https://docs.victoriametrics.com/vmagent.html#troubleshooting
- [X] vmalert - https://docs.victoriametrics.com/vmalert.html#troubleshooting
