### ISSUE TITLE
VM Agent metric_relabel_configs not work properly

### ISSUE THREAD

**Issue by valdis932** [VictoriaMetrics/VictoriaMetrics#5084]
### Describe the bug

metric_relabel_configs not work properly with targets on file_sd discovery ( may be with more sd )

### To Reproduce

Config for drop high cardinality metrics from targets based on file_sd discovery. Metrics don't change
```
  - job_name: some_job
    scrape_interval: 60s
    scrape_timeout: 55s
    static_configs:
      - targets:
	    - host_from_sd_1
	    - host_from_sd_2
	    - host_from_sd_3
    metric_relabel_configs:
    - if: '{__name__=~"some_metric_.+"}'
      action: drop  
```

Config with static targets works as expected
```
  - job_name: some_job
    scrape_interval: 60s
    scrape_timeout: 55s
    static_configs:
      - targets:
	    - host_from_sd_1
	    - host_from_sd_2
	    - host_from_sd_3
    metric_relabel_configs:
    - if: '{__name__=~"some_metric_.+"}'
      action: drop  
```

But in Prometheus v2.44.0 metric_relabel_configs with file_sd works correctly
```
  - job_name: some_job
    scrape_interval: 60s
    scrape_timeout: 55s
    file_sd_configs:
      - files:
          - /file1.yml
          - /file2.yml
          - /file3.yml
    metric_relabel_configs: 
    - source_labels: [__name__] 
      regex: some_metric_.+
      action: drop
```

### Version

build version: vmagent-20230919-042301-tags-v1.93.5-0-g3efbb0af2b

### Logs

nothing
