### ISSUE TITLE
Vmagent is incompatible with konnectivity

### ISSUE THREAD

**Issue by steeling** [VictoriaMetrics/VictoriaMetrics#5109]
### Describe the bug

[Konnectivity server only supports CONNECT passthrough proxying](https://github.com/kubernetes-sigs/apiserver-network-proxy/blob/master/pkg/server/tunnel.go#L46)

VMAgent specifically only uses http CONNECT when the destination scheme is HTTPS. When the destination scheme is HTTP, it sends a GET request. 

VMAgent cites the reason as this [wikipedia article](https://en.wikipedia.org/wiki/Proxy_server#Web_proxy_servers), but there is nothing that stipulates HTTP CONNECT can't be used to forward to a non-tls destination.

We should have a mechanism to control the form of proxying, outside of vmagent attempting to infer by the destination scheme.

### To Reproduce

```
global:
  # default scrape interval if not specified in each individual scrape config.
  scrape_interval: 5s
  scrape_timeout: 10s
scrape_configs:
  # pick up any additional scrape configs place in this dir.
  - job_name: example
    follow_redirects: false
    scheme: http
    metrics_path: /metrics
    static_configs:
      - targets:
        - example.com
    proxy_url: https://localhost:8099
    proxy_tls_config:
      insecure_skip_verify: true
```

Use vmagent with the above config. Change the scheme to http, or https, and notice that the forwarded request is sent as a GET for HTTP, and as a CONNECT for HTTPS.

### Version

vmagent-20230812-125753-heads-public-single-node-0-g05f109ad58-dirty-719a1a40

### Additional information

You can see the code where this occurs [here](https://github.com/VictoriaMetrics/VictoriaMetrics/blob/master/lib/promscrape/client.go#L116) and [here](https://github.com/VictoriaMetrics/VictoriaMetrics/blob/master/lib/proxy/proxy.go#L138).
