### ISSUE TITLE
VictoriaLogs::cannot add rows into storage in read-only mode

### ISSUE THREAD

**Issue by tripitakav** [VictoriaMetrics/VictoriaMetrics#5112]
### Describe the bug

![image](https://github.com/VictoriaMetrics/VictoriaMetrics/assets/73687556/13bd98f5-4791-4c57-b5b7-d01f7b651d4a)

![image](https://github.com/VictoriaMetrics/VictoriaMetrics/assets/73687556/4bd2bc5c-33fd-4df8-b9c1-b1b98e573f44)

### To Reproduce

```yaml
apiVersion: apps/v1
kind: StatefulSet
metadata:
  labels:
    app: vmlog
  name: vmlog
  namespace: ops
spec:
  serviceName: vmlog
  selector:
    matchLabels:
      app: vmlog
  replicas: 1
  template:
    metadata:
      labels:
        app: vmlog
    spec:
      containers:
        - name: vmlog
          image: "docker.io/victoriametrics/victoria-logs:v0.4.0-victorialogs"
          imagePullPolicy: "IfNotPresent"
          args:
            - "--storageDataPath=/storage"
            - --retentionPeriod=4w
          ports:
            - name: http
              containerPort: 9428
          resources:
            limits:
              cpu: "2"
              memory: 10000Mi
            requests:
              cpu: 500m
              memory: 3000Mi
          volumeMounts:
            - name: vmlog-volume
              mountPath: /storage
      terminationGracePeriodSeconds: 60
  updateStrategy:
    type: RollingUpdate
  volumeClaimTemplates:
    - metadata:
        labels:
          app: vmlog-volume
        name: vmlog-volume
      spec:
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 500Gi
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: vmlog
  name: vmlog
  namespace: ops
spec:
  clusterIP: None
  ports:
    - port: 9428
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app: vmlog
```

### Version

docker.io/victoriametrics/victoria-logs:v0.4.0-victorialogs
