### ISSUE TITLE
Global case insensitive flag

### ISSUE THREAD

**Issue by nevlkv** [VictoriaMetrics/VictoriaMetrics#5133]
### Is your feature request related to a problem? Please describe

When in relabel_configs nedes case insensitive comparisions i add `(?i)` in regexps 

ex:
```
      relabel_configs:
      - source_labels: [__meta_kubernetes_pod_annotation_prometheus_io_scrape]
        action: keep
        regex: (?i)true
```

### Describe the solution you'd like

If defined global flag for vmagent case.insensitive  `(?i)` may be omit

### Additional information

defaults = undefined case.insensitive
