### ISSUE TITLE
support opentelemetry collector?

### ISSUE THREAD

**Issue by tqangxl** [VictoriaMetrics/VictoriaMetrics#5142]
### Is your feature request related to a problem? Please describe

support opentelemetry collector?
https://github.com/open-telemetry/opentelemetry-collector-contrib

### Describe the solution you'd like
get win  os metrics and windows eventlog
support opentelemetry collector

**Comment by AsoTora** [comment]
Since this is open i will +1 on that. The protocol is supported but not really obvious which exporter to use.

Currently I'm trying the [otlphttp](https://github.com/open-telemetry/opentelemetry-collector/blob/main/exporter/otlphttpexporter/README.md) but no luck. 

Collector version: `0.90.1 installed with helm chart v 0.76.0`
Victoriametrics version: `vminsert-20231212-224941-tags-v1.96.0-cluster-0-gd59ee93d0`

otel-collector yaml:
```yaml
config:
  exporters:
    debug: {}
    otlphttp:
      metrics_endpoint: http://********:8480/insert/opentelemetry/api/v1/push
      compression: none

  processors:
    batch: {}
    # If set to null, will be overridden with values based on k8s resource limits
    memory_limiter: null
    transform:
      error_mode: ignore
      log_statements: 
      - context: log
        statements:
          - set(resource.attributes.environment, "development") 
  receivers:
    otlp:
      protocols:
        grpc:
          endpoint: ${env:MY_POD_IP}:4317
        http:
          endpoint: ${env:MY_POD_IP}:4318
    prometheus:
      config:
        scrape_configs:
          - job_name: opentelemetry-collector
            scrape_interval: 10s
            static_configs:
              - targets:
                  - ${env:MY_POD_IP}:8888
  service:
    telemetry:
      metrics:
        address: ${env:MY_POD_IP}:8888
    extensions:
      - health_check
      - memory_ballast
    pipelines:
      logs:
        exporters: [debug]
        processors: [memory_limiter, batch, transform]
        receivers: [otlp]
      metrics:
        exporters: [debug, otlphttp]
        processors: [memory_limiter, batch]
        receivers: [otlp, prometheus]
      traces:
        exporters: [debug]
        processors: [memory_limiter, batch]
        receivers: [otlp]
```

**Comment by hagen1778** [comment]
Hello @AsoTora !

Have you checked vminsert logs? It looks like you're missing tenant data in the vminsert URL - see details here https://docs.victoriametrics.com/Cluster-VictoriaMetrics.html#url-format

Try updating your config to the following:
```
otlphttp:
      metrics_endpoint: http://********:8480/insert/0/opentelemetry/api/v1/push
```
where `0` is an arbitrary tenant ID.

**Comment by AsoTora** [comment]
@hagen1778 lmao, i compeltely missed this! Now its up and running! 

<img width="1771" alt="image" src="https://github.com/VictoriaMetrics/VictoriaMetrics/assets/36507055/2fc2322c-4b76-4387-b6c1-242e264faa95">

Which closes this issue, the solution is to use the **otlphttp exporter** from the [default repo:](https://github.com/open-telemetry/opentelemetry-collector/blob/main/exporter/otlphttpexporter/README.md), like this:

```yaml
config:
  exporters:
    debug: {}
    otlphttp:
      metrics_endpoint: http://********:8480/insert/0/opentelemetry/api/v1/push

  processors:
    batch: {}
    memory_limiter: null

  receivers:
    otlp:
      protocols:
        grpc:
        HTTP:

    pipelines:
      logs:
        exporters: [debug]
        processors: [memory_limiter, batch]
        receivers: [otlp]
      metrics:
        exporters: [debug, otlphttp]
        processors: [memory_limiter, batch]
        receivers: [otlp, prometheus]
      traces:
        exporters: [debug]
        processors: [memory_limiter, batch]
        receivers: [otlp]
```
