### ISSUE TITLE
vmalert: support extra labels param in notifier config

### ISSUE THREAD

**Issue by f41gh7** [VictoriaMetrics/VictoriaMetrics#5184]
### Describe the bug

 Currently, there is no way to configure pathPrefix for `static_configs` notifier configuration file. It supports only `targets` section, but it also must support `labels`.

current config
```yaml
static_configs:
  - targets:
      - localhost:9093
      - localhost:9095
```

correct config:
```yaml
static_configs:
  - targets:
      - localhost:9093
      - localhost:9095
     labels:
         __alerts_path__: "/some/value"
        __scheme__: "http"
```

### To Reproduce

 Start vmalert multiple targets at static_configs.

### Version

any version

**Comment by valyala** [comment]
An alternative solution is to add support for specifying full http or https urls inside `targets` list. This is already implemented in `vmagent` - see f9df0cae16438beeb8245a95bc11406a0bd44842

**Comment by valyala** [comment]
`vmalert` supports full urls inside `targets` list at `static_configs` [notifier config file](https://docs.victoriametrics.com/vmalert.html#notifier-configuration-file) since [v1.95.0](https://docs.victoriametrics.com/CHANGELOG.html). For example:

```yml
static_configs:
  - targets:
      - http://localhost:9093/some/path
      - https://localhost:9095/another/path?some_query_args
```

Closing the feature request as done then.
