### ISSUE TITLE
VMAGENT with PROXY and HTTPS

### ISSUE THREAD

**Issue by adelbot** [VictoriaMetrics/VictoriaMetrics#5199]
### Describe the bug

when i scraping https exporters with proxy configuration : 

with tcpdump i saw : 

CONNECT xxxxxxx:9128 HTTP/1.1
Host: xxxxxx
Proxy-Authorization: Basic xxxx

But many time, i receive : 

CONNECT xxxx.net.intra.laposte.fr:9128 HTTP/1.1
Host: xxxx:9128
User-Agent: Go-http-client/1.1

and 

HTTP/1.1 407 Proxy Authentication Required.

It seems that the authentication is not send in all the scrap.

### To Reproduce

Config: 

- job_name: xxxx                                                   
  honor_timestamps: true                                                        
  disable_keepalive: false
  scrape_interval: 60s
  scrape_timeout: 45s
  proxy_url: http://xxxxxxx                                               
  proxy_basic_auth:                                                    
    username: %{W2_-PROXY_USER}                                            
    password: %{W2_-PROXY_PASSWORD}
  metrics_path: /metrics/array                                                    
  static_configs:                                                               
  - targets: [ 'xxxxxx.net.intra.laposte.fr:9128' ]                                   
    l

### Version

/vmagent-prod  --version
vmagent-20231016-215832-tags-v1.93.6-0-g445e4b1c7

### Logs

annot read data: cannot scrape "https://sssss:9128/metrics/array?endpoint=sssss": Get "https://ssssss:9128/metrics/array?endpoint=sssss": Proxy Authentication Required

**Comment by dmitryk-dk** [comment]
Hi @adelbot ! I have tested your configuration. Here is all steps:
1. I used node exporter to generate metrics
`./node_exporter --web.config.file=web.yml --web.listen-address=0.0.0.0:9100`

web.yml
```yaml
tls_server_config:
  cert_file: node_exporter.crt
  key_file: node_exporter.key
```

I used squid as forward-proxy and here is it config
```
http_port 3128

auth_param basic program /usr/lib/squid3/basic_ncsa_auth /etc/squid/password
auth_param basic realm proxy
acl authenticated proxy_auth REQUIRED
http_access allow authenticated
```
3. Made config for vmagent
test.yml
```yaml
scrape_configs:
  - job_name: 'https-target'
    honor_timestamps: true
    disable_keepalive: false
    scrape_interval: 1s
    scrape_timeout: 1s
    proxy_url: http://localhost:3128
    proxy_basic_auth:
      username: user
      password: user
    metrics_path: /metrics
    tls_config:
      insecure_skip_verify: true
    static_configs:
      - targets: [ "https://192.168.0.13:9100" ]
```
      
<img width="1680" alt="Screenshot 2023-10-20 at 10 39 20" src="https://github.com/VictoriaMetrics/VictoriaMetrics/assets/12189570/656da7eb-350c-4d4e-81da-4db6920084db">
As you can see it works well without any problems.

Can you check that you added all scrape targets, that they work well, and you do not misconfigure anything?
