### ISSUE TITLE
vm-agent 1.94.0 fails to discover targets

### ISSUE THREAD

**Issue by mindw** [VictoriaMetrics/VictoriaMetrics#5216]
### Describe the bug

Valid targets previous discovered by 1.93.4 aren't discovered by 1.94.0.

Also, `kubernetes_sd_configs` role = endpoint fails to add service labels (very likely to be related).
```
        kubernetes_sd_configs:
        - role: endpoints
```

### To Reproduce

The target should have a history of not being discovered. For example, it was missing annotations or some labels.

Deploy kube-state-metrics chart into metrics namespace
```
helm install -n monitoring kube-state-metrics --create-namespace prometheus-community/kube-state-metrics
```
add a static discovery rule
```
      - job_name: kube-state-metrics
        honor_labels: true
        kubernetes_sd_configs:
        - role: endpoints
        relabel_configs:
        - action: keep
          source_labels:
          - __meta_kubernetes_namespace
          - __meta_kubernetes_ednpoint_label_app
          - __meta_kubernetes_endpoint_port_name
          regex: monitoring;kube-state-metrics;http
        - target_label: endpoint
          replacement: http-metrics
        metric_relabel_configs:
        - action: labeldrop
          regex: (instance|endpoint)
        - action: drop
          source_labels: [__name__, secret]
          regex: 'kube_secret_.+;.+\.v\d+'
```
The kube-state-metrics target should list 0 discovered targets.
add a custom label:
```
helm diff upgrade -n monitoring kube-state-metrics prometheus-community/kube-state-metrics --set customLabels.foo=kube-state-metrics
```
Discovered targets should still be 0
Downgrade to 1.93.6.
Discovered targets should still be 1

### Version

`docker.io/victoriametrics/victoria-metrics:v1.94.0`

### Logs

didn't see anything relevant.

### Screenshots

1.94.0
![image](https://github.com/VictoriaMetrics/VictoriaMetrics/assets/578872/28c888b8-74ef-4294-ad42-88ea624712ad)
1.93.6
![image](https://github.com/VictoriaMetrics/VictoriaMetrics/assets/578872/d1a46e06-9706-4dff-887b-44266d9a8846)

### Used command-line flags

```
-envflag.enable="true"
-envflag.prefix="VM_"
-http.connTimeout="12h0m0s"
-http.idleConnTimeout="5m0s"
-loggerFormat="json"
-promscrape.config="/scrapeconfig/scrape.yml"
-promscrape.configCheckInterval="1m0s"
-retentionPeriod="8d"
-search.disableAutoCacheReset="true"
-storageDataPath="/storage"
-vmalert.proxyURL="http://victoria-metrics-alerts-server:8880
```

### Additional information

Possible cause of trouble - https://github.com/VictoriaMetrics/VictoriaMetrics/commit/00685b627f8fb353adb0f892f99a0e4c9e071991
and
https://github.com/VictoriaMetrics/VictoriaMetrics/issues/4855
