### ISSUE TITLE
vmauth: When using unauthorized_user, browsers never receive Www-Authenticate response header

### ISSUE THREAD

**Issue by ful09003** [VictoriaMetrics/VictoriaMetrics#5236]
### Describe the bug

When [configuring](https://docs.victoriametrics.com/vmauth.html#auth-config) vmauth with `unauthorized_user`, it becomes impossible to perform basic auth using a browser. Without `unauthorized_user` configured at all, browsers are prompted for basic auth (expected) as we can see from these response headers:

```
> GET /vmselect/select/0 HTTP/1.1
> Host: localhost:8427
> User-Agent: curl/8.1.2
> Accept: */*
>
< HTTP/1.1 401 Unauthorized
< Content-Type: text/plain; charset=utf-8
< Vary: Accept-Encoding
< Www-Authenticate: Basic realm="Restricted"
< X-Content-Type-Options: nosniff
< X-Server-Hostname: 21f4e617ca3f
< Date: Wed, 25 Oct 2023 14:09:46 GMT
< Content-Length: 39
<
missing `Authorization` request header
```

With `unauthorized_user` specified in vmauth config, browsers are never sent back the `Www-Authenticate` header, as every request is routed/treated as though it's an `unauthorized_user`:

```
> GET /vmselect/select/0 HTTP/1.1
> Host: localhost:8427
> User-Agent: curl/8.1.2
> Accept: */*
>
< HTTP/1.1 400 Bad Request
< Content-Type: text/plain; charset=utf-8
< Vary: Accept-Encoding
< X-Content-Type-Options: nosniff
< X-Server-Hostname: 21f4e617ca3f
< Date: Wed, 25 Oct 2023 14:10:12 GMT
< Content-Length: 103
<
remoteAddr: "172.18.0.1:33468"; requestURI: /vmselect/select/0; missing route for "/vmselect/select/0"
```

This is a bug to us, because we desire many vmselect paths such as `/vmui` protected by vmauth requiring basic auth, but also have certain paths (such as vmselect `/metrics`) not require any auth by using `unauthorized_user`. Due to missing response headers, we cannot satisfy this use case.

### To Reproduce

In short, any existing vmauth deployment using basic auth and `unauthorized_user` should be able to replicate this.
The following docker-compose deployment should also demonstrate the issue:

Named e.g. `docker-compose-vmauth.yml`:
```
version: '3.0'
services:
  # VictoriaMetrics Components
  # Adapted from https://github.com/VictoriaMetrics/VictoriaMetrics/blob/cluster/deployment/docker/docker-compose.yml
  vmauth101:
    container_name: vmauth101
    image: victoriametrics/vmauth:v1.93.6
    depends_on:
      - "vmselect101"
    volumes:
      - "./confs/vmauth.yml:/config.yml:ro"
    command:
      - '-auth.config=/config.yml'
    ports:
      - "8427:8427"
  vmselect101:
    container_name: vmselect101
    image: victoriametrics/vmselect:v1.93.6-cluster
    command:
      - '--http.pathPrefix=/vmselect'
      - '--storageNode=vmstorage101:8401'
      - '--storageNode=vmstorage102:8401'
    ports:
      - "8481:8481"
```

and this named e.g. `confs/vmauth.yml`:
```
users:
  - username: "admin"
    password: "ayo"
    url_map:
      - src_paths:
        - "/vmui"
        - "/vmui/.*"
        url_prefix: "http://vmselect101:8481/vmselect/select/0"

# Allow health checks and scrapers to access to metrics endpoint without authorization
#unauthorized_user:
#  url_map:
#    - src_paths:
#        - "/vmselect/metrics"
#      url_prefix:
#        - "http://vmselect101:8481"
```

1) `docker-compose -f docker-compose-vmauth.yml up`
2) Observe that with `unauthorized_user` commented out in the vmauth config, private/incognito browser or cURL to `http://localhost:8427/vmui` prompts for basic auth (**desired behavior**)
3) Ctrl+C to stop docker-compose
4) Uncomment `unauthorized_user` section
5) `docker-compose -f docker-compose-vmauth.yml up`
6) Observe that with `unauthorized_user` uncommented, private/incognito browser or cURL to `http://localhost:8427/vmui` no longer prompts for basic auth, and immediately rejects the request (**undesired behavior**)

### Version

```
vmauth-20230919-042335-tags-v1.93.5-0-g3efbb0af2b
```

### Logs

Nothing too much, from browser/cURL when the undesired behavior occurs:

```
remoteAddr: "172.18.0.1:44990"; requestURI: /vmui; missing route for "/vmui"
```

### Additional information

This should be fixed up by https://github.com/VictoriaMetrics/VictoriaMetrics/pull/5234, I was too slow in opening this bug first 😄
