### ISSUE TITLE
Drop long lived constant counters(e.g. zero rate ingress paths) at scrape time or by stream agg.

### ISSUE THREAD

**Issue by Sin4wd** [VictoriaMetrics/VictoriaMetrics#5288]
### Is your feature request related to a problem? Please describe

We are facing a problem with our scraped metrics from nginx and traefik ingress gateways. The number of time series exported is growing over time, unless we restart some pods. This is because some rarely used combination of labels are touched once in a while, yet multiple constant counter series remains until the next restart.
I understand that it's better for the application endpoints to let those long lived constant counters go away but It's nice to have the ability to limit these to prevent fluctuation in the storage.
I provide a simple example of such fluctuation on one of our traefik deployments:
```
sum by (job) (scrape_samples_scraped{job="traefik-metrics"})
```
![Screenshot 2023-11-05 at 1 29 45 PM](https://github.com/VictoriaMetrics/VictoriaMetrics/assets/30809018/c68c0a51-a00a-4e85-8923-cf0dad79b982)
```
sum(rate(vm_rows_inserted_total{job=~"vmsingle-vmsingle"}[2m])) by (type) > 0
```
![Screenshot 2023-11-05 at 1 47 41 PM](https://github.com/VictoriaMetrics/VictoriaMetrics/assets/30809018/26cc7274-9093-46f5-b515-920ef35dbc84)

The problem here is that usually these ingress metrics are the heaviest metrics of ours and handling such variation needs at least 2x-10x reserved ingestion capacity(cpu/memory) on the victoriametrics for some useless metrics.

### Describe the solution you'd like

There might be a way to drop some timeseries in the stream aggregation time based on a threshold.
for example:
- dropping those with 15m_increase <= 0
```
- match: 'traefik_router_requests_total'
  interval: 15m
  outputs: []
  drop:
    operator: le
    value: 0
```
- dropping those with 5m_increase <= 0 for 15m
```
- match: 'traefik_router_requests_total'
  interval: 5m
  outputs: []
  drop:
    operator: le
    value: 0
    for: 15m
```

### Describe alternatives you've considered

I have none.
