### ISSUE TITLE
Relabelling for __name__ with custom prefix

### ISSUE THREAD

**Issue by thunderbird86** [VictoriaMetrics/VictoriaMetrics#5294]
### Is your question request related to a specific component?

Vmagent

### Describe the question in detail

I want to update scrape metric names with annotation, if added. E.g.

```YAML
apiVersion: v1
kind: Service
metadata:
  name: foo-bar-enhanced
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/path: "/enhanced"
    prometheus.io/port: "9042"
    prometheus.io/name_prefix: "foo_bar_"
```  

So I've created relabeling rule 
```YAML
 - job_name: kubernetes-pods
    kubernetes_sd_configs:
      - role: pod
    relabel_configs:
      ... 
      - source_labels:
          - __meta_kubernetes_pod_annotation_prometheus_io_name_prefix
        target_label: name_prefix
    metric_relabel_configs:
      - action: replace
        source_labels:
          - __name__
          - name_prefix
        target_label: __name__
        separator: ""
        replacement: "${2}${1}"
 ```
 
here is static configuration

```YAML
- job_name: kubernetes-pods
  kubernetes_sd_configs:
    - role: pod
  metric_relabel_configs:
    - source_labels: [ __name__ ]
      target_label: __name__
      regex: '(.*)'
      action: replace
      replacement: foo_bar_${1}
```
And here is VMAgent debug interface looks like with static configuration

<img width="1726" alt="image" src="https://github.com/VictoriaMetrics/VictoriaMetrics/assets/11559172/1279102f-da68-42b2-a955-4fac814d131a">

And from annotation:
<img width="1720" alt="image" src="https://github.com/VictoriaMetrics/VictoriaMetrics/assets/11559172/7cacfa29-d24e-4d2a-9dbe-4cde4ebf1e93">

The results look similar, but if I use an annotation case, I have no metrics...

Is this a bug or it supposed to be like that ?

### Troubleshooting docs

- [X] General - https://docs.victoriametrics.com/Troubleshooting.html
- [X] vmagent - https://docs.victoriametrics.com/vmagent.html#troubleshooting
- [X] vmalert - https://docs.victoriametrics.com/vmalert.html#troubleshooting
