### ISSUE TITLE
Some Prom Queries not working

### ISSUE THREAD

**Issue by Sam-Sundar** [VictoriaMetrics/VictoriaMetrics#5309]
### Is your question request related to a specific component?

vmagent

### Describe the question in detail

Hey Team,

We're running Prom and VM side by side and one thing i noticed is, istio's queries are failing in VM but same queries are working well in Prom. Later found that it's due to single config the query fails. 

`histogram_quantile(0.50, sum(irate(istio_request_duration_milliseconds_bucket{reporter="source",destination_workload=~"grafana", destination_workload_namespace=~"grafana",account=~"",cluster=~"TestApps"}[5m])) by (le)) / 1000`

The above query gives output when the datasource is Prometheus. 

![image](https://github.com/VictoriaMetrics/VictoriaMetrics/assets/83000807/9697606e-d07b-4680-8e32-536914e401bb)

same query, but with VM

![image](https://github.com/VictoriaMetrics/VictoriaMetrics/assets/83000807/b761d76b-0cbc-4d6a-b8f1-fa504b5659e7)

and one weird thing we noticed is, when we remove `cluster=~"TestApps"` from the query, VM is giving result. 

![image](https://github.com/VictoriaMetrics/VictoriaMetrics/assets/83000807/45683bea-fafb-4a6a-84ae-745c375fde71)

What might be the issue ? We also have added `cluster` as an external label in our scrapeConfig
```
  prometheus.yaml: |-
    global:
      scrape_interval: 30s
      scrape_timeout: 60s
      external_labels:
        cloud: gcp
        cluster: TestApps
```

Also attaching the istio servicemonitors which we're using. 
```
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: prometheus-oper-istio-controlplane
  namespace: monitoring
  labels:
    release: prometheus
spec:
  jobLabel: istio
  selector:
    matchExpressions:
      - {key: istio, operator: In, values: [mixer,pilot,galley,citadel,sidecar-injector]}
  namespaceSelector:
    any: true
  endpoints:
  - port: http-monitoring
    interval: 15s
  - port: http-policy-monitoring
    interval: 15s
```
```
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: prometheus-oper-istio-dataplane
  namespace: monitoring
  labels:
    monitoring: istio-dataplane
    release: prometheus
spec:
  selector:
    matchExpressions:
      - {key: istio-prometheus-ignore, operator: DoesNotExist}
  namespaceSelector:
    any: true
  jobLabel: envoy-stats
  endpoints:
  - path: /stats/prometheus
    targetPort: http-envoy-prom
    interval: 15s
    relabelings:
    - sourceLabels: [__meta_kubernetes_pod_container_port_name]
      action: keep
      regex: '.*-envoy-prom'
    - action: labelmap
      regex: "__meta_kubernetes_pod_label_(.+)"
    - sourceLabels: [__meta_kubernetes_namespace]
      action: replace
      targetLabel: namespace
    - sourceLabels: [__meta_kubernetes_pod_name]
      action: replace
      targetLabel: pod_name
```
```
apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: envoy-stats-monitor
  namespace: istio-system
  labels:
    monitoring: istio-proxies
    release: istio
spec:
  selector:
    matchExpressions:
    - {key: istio-prometheus-ignore, operator: DoesNotExist}
  namespaceSelector:
    any: true
  jobLabel: envoy-stats
  podMetricsEndpoints:
  - path: /stats/prometheus
    interval: 15s
    relabelings:
    - action: keep
      sourceLabels: [__meta_kubernetes_pod_container_name]
      regex: "istio-proxy"
    - action: keep
      sourceLabels: [__meta_kubernetes_pod_annotationpresent_prometheus_io_scrape]
    - sourceLabels: [__address__, __meta_kubernetes_pod_annotation_prometheus_io_port]
      action: replace
      regex: ([^:]+)(?::\d+)?;(\d+)
      replacement: $1:$2
      targetLabel: __address__
    - action: labeldrop
      regex: "__meta_kubernetes_pod_label_(.+)"
    - sourceLabels: [__meta_kubernetes_namespace]
      action: replace
      targetLabel: namespace
    - sourceLabels: [__meta_kubernetes_pod_name]
      action: replace
      targetLabel: pod_name
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: istio-component-monitor
  namespace: istio-system
  labels:
    monitoring: istio-components
    release: istio
spec:
  jobLabel: istio
  targetLabels: [app]
  selector:
    matchExpressions:
    - {key: istio, operator: In, values: [pilot]}
  namespaceSelector:
    any: true
  endpoints:
  - port: http-monitoring
    interval: 15s
```          

Scrape config is below (Copied from Prometheus instance and attaching to VM as ExtraScrapeConfig)
```yaml
    - job_name: prometheus-oper-istio-controlplane
      honor_labels: false
      kubernetes_sd_configs:
      - role: endpoints
      scrape_interval: 15s
      relabel_configs:
      - source_labels:
        - job
        target_label: __tmp_prometheus_job_name
      - action: keep
        source_labels:
        - __meta_kubernetes_service_label_istio
        - __meta_kubernetes_service_labelpresent_istio
        regex: (mixer|pilot|galley|citadel|sidecar-injector);true
      - action: keep
        source_labels:
        - __meta_kubernetes_endpoint_port_name
        regex: http-monitoring
      - source_labels:
        - __meta_kubernetes_endpoint_address_target_kind
        - __meta_kubernetes_endpoint_address_target_name
        separator: ;
        regex: Node;(.*)
        replacement: ${1}
        target_label: node
      - source_labels:
        - __meta_kubernetes_endpoint_address_target_kind
        - __meta_kubernetes_endpoint_address_target_name
        separator: ;
        regex: Pod;(.*)
        replacement: ${1}
        target_label: pod
      - source_labels:
        - __meta_kubernetes_namespace
        target_label: namespace
      - source_labels:
        - __meta_kubernetes_service_name
        target_label: service
      - source_labels:
        - __meta_kubernetes_pod_name
        target_label: pod
      - source_labels:
        - __meta_kubernetes_pod_container_name
        target_label: container
      - source_labels:
        - __meta_kubernetes_service_name
        target_label: job
        replacement: ${1}
      - source_labels:
        - __meta_kubernetes_service_label_istio
        target_label: job
        regex: (.+)
        replacement: ${1}
      - target_label: endpoint
        replacement: http-monitoring
      - source_labels:
        - __address__
        target_label: __tmp_hash
        modulus: 1
        action: hashmod
      - source_labels:
        - __tmp_hash
        regex: 0
        action: keep
      metric_relabel_configs: []
    - job_name: prometheus-oper-istio-controlplane/1
      honor_labels: false
      kubernetes_sd_configs:
      - role: endpoints
      scrape_interval: 15s
      relabel_configs:
      - source_labels:
        - job
        target_label: __tmp_prometheus_job_name
      - action: keep
        source_labels:
        - __meta_kubernetes_service_label_istio
        - __meta_kubernetes_service_labelpresent_istio
        regex: (mixer|pilot|galley|citadel|sidecar-injector);true
      - action: keep
        source_labels:
        - __meta_kubernetes_endpoint_port_name
        regex: http-policy-monitoring
      - source_labels:
        - __meta_kubernetes_endpoint_address_target_kind
        - __meta_kubernetes_endpoint_address_target_name
        separator: ;
        regex: Node;(.*)
        replacement: ${1}
        target_label: node
      - source_labels:
        - __meta_kubernetes_endpoint_address_target_kind
        - __meta_kubernetes_endpoint_address_target_name
        separator: ;
        regex: Pod;(.*)
        replacement: ${1}
        target_label: pod
      - source_labels:
        - __meta_kubernetes_namespace
        target_label: namespace
      - source_labels:
        - __meta_kubernetes_service_name
        target_label: service
      - source_labels:
        - __meta_kubernetes_pod_name
        target_label: pod
      - source_labels:
        - __meta_kubernetes_pod_container_name
        target_label: container
      - source_labels:
        - __meta_kubernetes_service_name
        target_label: job
        replacement: ${1}
      - source_labels:
        - __meta_kubernetes_service_label_istio
        target_label: job
        regex: (.+)
        replacement: ${1}
      - target_label: endpoint
        replacement: http-policy-monitoring
      - source_labels:
        - __address__
        target_label: __tmp_hash
        modulus: 1
        action: hashmod
      - source_labels:
        - __tmp_hash
        regex: 0
        action: keep
      metric_relabel_configs: []
    - job_name: prometheus-oper-istio-dataplane
      honor_labels: false
      kubernetes_sd_configs:
      - role: endpoints
      scrape_interval: 15s
      metrics_path: /stats/prometheus
      relabel_configs:
      - source_labels:
        - job
        target_label: __tmp_prometheus_job_name
      - action: drop
        source_labels:
        - __meta_kubernetes_service_labelpresent_istio_prometheus_ignore
        regex: "true"
      - action: keep
        source_labels:
        - __meta_kubernetes_pod_container_port_name
        regex: http-envoy-prom
      - source_labels:
        - __meta_kubernetes_endpoint_address_target_kind
        - __meta_kubernetes_endpoint_address_target_name
        separator: ;
        regex: Node;(.*)
        replacement: ${1}
        target_label: node
      - source_labels:
        - __meta_kubernetes_endpoint_address_target_kind
        - __meta_kubernetes_endpoint_address_target_name
        separator: ;
        regex: Pod;(.*)
        replacement: ${1}
        target_label: pod
      - source_labels:
        - __meta_kubernetes_namespace
        target_label: namespace
      - source_labels:
        - __meta_kubernetes_service_name
        target_label: service
      - source_labels:
        - __meta_kubernetes_pod_name
        target_label: pod
      - source_labels:
        - __meta_kubernetes_pod_container_name
        target_label: container
      - source_labels:
        - __meta_kubernetes_service_name
        target_label: job
        replacement: ${1}
      - source_labels:
        - __meta_kubernetes_service_label_envoy_stats
        target_label: job
        regex: (.+)
        replacement: ${1}
      - target_label: endpoint
        replacement: http-envoy-prom
      - source_labels:
        - __meta_kubernetes_pod_container_port_name
        regex: .*-envoy-prom
        action: keep
      - regex: __meta_kubernetes_pod_label_(.+)
        action: labelmap
      - source_labels:
        - __meta_kubernetes_namespace
        target_label: namespace
        action: replace
      - source_labels:
        - __meta_kubernetes_pod_name
        target_label: pod_name
        action: replace
      - source_labels:
        - __address__
        target_label: __tmp_hash
        modulus: 1
        action: hashmod
      - source_labels:
        - __tmp_hash
        regex: 0
        action: keep
      metric_relabel_configs: []
```

PS: Other queries are working without any issues with Cluster label in VM, only issue with Istio's queries. 
![image](https://github.com/VictoriaMetrics/VictoriaMetrics/assets/83000807/a192918e-fe38-4822-aa48-76ab80850900)

### Troubleshooting docs

- [X] General - https://docs.victoriametrics.com/Troubleshooting.html
- [X] vmagent - https://docs.victoriametrics.com/vmagent.html#troubleshooting
- [ ] vmalert - https://docs.victoriametrics.com/vmalert.html#troubleshooting
