### ISSUE TITLE
[VictoriaLogs] Add a new data ingestion protocol for telegraf http output plugin

### ISSUE THREAD

**Issue by EricDele** [VictoriaMetrics/VictoriaMetrics#5310]
### Is your feature request related to a problem? Please describe

We uses telegraf to collect metrics for VictoriaMetrics.
In telegraf there is a tail input plugin that can do the log collector and uses grok pattern to identify the right part of a log file to create great json key/value for unstructured log files
To avoid installing another log collector tool I have tried to use telegraf http output plugin for sending log content to VictoriaLogs without success

### Describe the solution you'd like

Solution could be :

- Adapt VictoriaLogs to accept the http output payload
- Create a specific plugin output in telegraf for VictoriaLogs
- Other one I don't have in my mind

### Describe alternatives you've considered

Tried to send the payload that is like this :
```json
{
    "fields": [
        {
            "date": "2022-07-19 15:27:47,646",
            "loglevel": "WARN",
            "class": "java.lang.NoClassDefFoundError",
            "msg": "my error message"
        }
    ],
    "tags": {
        "env": "prod",
        "cluster": "clustername",
        "host": "hostname",
        "service": "hbase",
        "role": "regionserver"
    },
    "timestamp": 1699602071
}
```

Have tried to acces fields globaly (array) or by field name and for stream filed to access tags by name in the VictoriaLogs url but did not works

/insert/jsonline?_stream_fields=tags&_msg_field=fields.msg&_time_field=fields.date
/insert/jsonline?_stream_fields=tags.env,tags.cluster,tags.host,tags.service,tags.role&_msg_field=fields.msg&_time_field=fields.date

Could be great to just specify an url like the following one for ingest all key/values below the entry point : 
/insert/jsonline?_stream_fields=tags&_msg_field=fields&_time_field=fields.date

Could generate

**Comment by tenmozes** [comment]
related pull request - https://github.com/VictoriaMetrics/VictoriaMetrics/pull/6443

**Comment by tiny-pangolin** [comment]
along with the elastic output support you can use the loki output as well. I'm currently using it with the following config

```toml
[[outputs.loki]]
  domain = "https://vl.example.com"
  endpoint = "/insert/loki/api/v1/push?_msg_field=docker_log.msg&_time_field=@timestamp&_stream_fields=log_source,metric_type,appname,host,hostname,Cached,Upstream,dest_port,dest_ip,src_ip,src_port,event_type,path,resp_code,severity)"
  namepass = ["syslog","tail","exec*"]
  gzip_request = true
  sanitize_label_names = true
  insecure_skip_verify = true
```

please note you will need to change  the `domain` option, you can change the stream_fields query parameter in the url to fit your use case. The [loki output plugin docs](https://github.com/influxdata/telegraf/tree/master/plugins/outputs/loki) also specify how to specify headers and basic auth if that is needed in your setup.
