### ISSUE TITLE
[VMNodeScrape] Custom label using relabelConfigs not appear in the output metric

### ISSUE THREAD

**Issue by tantm3** [VictoriaMetrics/VictoriaMetrics#5350]
### Is your question request related to a specific component?

Related Component:
VMOperator: victoriametrics/operator:v0.39.1
VMAgent: victoriametrics/vmagent:v1.93.1

### Describe the question in detail

Hi everyone!

I currently have the k8s stack for monitoring the k8s cluster.
I tried to enable the kubelet advisor metrics using this config:
```
apiVersion: operator.victoriametrics.com/v1beta1
kind: VMNodeScrape
metadata:
  labels:
    app: vmnodescrapes-cadvisor-custom
  name: vmnodescrapes-cadvisor-custom
  namespace: monitoring
spec:
  scheme: "https"
  honorLabels: true
  honorTimestamps: false
  tlsConfig:
    insecureSkipVerify: true
    caFile: "/var/run/secrets/kubernetes.io/serviceaccount/ca.crt"
  bearerTokenFile: "/var/run/secrets/kubernetes.io/serviceaccount/token"
  metricRelabelConfigs:
  - action: labeldrop
    regex: (uid)
  - action: labeldrop
    regex: (id|name)
  - action: drop
    regex: (rest_client_request_duration_seconds_bucket|rest_client_request_duration_seconds_sum|rest_client_request_duration_seconds_count)
    source_labels:
    - __name__
  relabelConfigs:
    - action: labelmap
      regex: __meta_kubernetes_node_label_(.+)
    - targetLabel: __address__
      replacement: kubernetes.default.svc:443
    - sourceLabels: [__meta_kubernetes_node_name]
      regex: (.+)
      targetLabel: __metrics_path__
      replacement: /api/v1/nodes/$1/proxy/metrics/cadvisor
    - targetLabel: product
      replacement: dev-test
```
I want to add the `product label`  using the relabelConfig (shown in the config block above).
In the metric relabel debug tab, I saw that the product label has been added to the output label:

![image](https://github.com/VictoriaMetrics/VictoriaMetrics/assets/112939454/95a34588-589a-4c0e-b2c1-eb37370eb59a)

But, when I explored the metric from Grafana, I could not get metrics with the product label

![image](https://github.com/VictoriaMetrics/VictoriaMetrics/assets/112939454/7f3e6f46-ea82-491c-9df1-9520ae3b7502)

It returns an empty result and the metric has the product label:
 
![image](https://github.com/VictoriaMetrics/VictoriaMetrics/assets/112939454/43c9bedb-8905-4853-8ba1-60e2e6b91a7d)

Thanks for your time reading my question!

### Troubleshooting docs

- [ ] General - https://docs.victoriametrics.com/Troubleshooting.html
- [ ] vmagent - https://docs.victoriametrics.com/vmagent.html#troubleshooting
- [ ] vmalert - https://docs.victoriametrics.com/vmalert.html#troubleshooting
