### ISSUE TITLE
Error while startup when using image.repository, image.tag, image.pullPolicy in spec in CRDs like VMAuth, VMAgent

### ISSUE THREAD

**Issue by jamshidyerzakov** [VictoriaMetrics/VictoriaMetrics#5352]
### Describe the bug

When I added image.tag, image.repository, image.pullPolicy in CRD VMAuth or VMAgent - it didn't start. I expect it to start without any problem while using image versioning. 

### To Reproduce

Create VMAuth CRD with image in spec.

```
apiVersion: operator.victoriametrics.com/v1beta1
kind: VMAuth
metadata:
  name: proxytest
  namespace: vm
spec:
  image:
    repository: victoriametrics/victoria-metrics
    tag: v1.95.1
    pullPolicy: IfNotPresent
  podMetadata:
    labels:
      component: vmauth
  selectAllByDefault: true
  replicaCount: 1
  ```

### Version

Version v1.95.1

### Logs

```
flag provided but not defined: -auth.config

victoria-metrics is a time series database and monitoring solution.

See the docs at https://docs.victoriametrics.com/

Run "/victoria-metrics-prod -help" in order to see the description for all the available flags
```

**Comment by zekker6** [comment]
Hello @jamshidyerzakov 

You've used image repository for [VictoriaMetrics single-node](https://hub.docker.com/r/victoriametrics/victoria-metrics) instead of `vmauth` [own repository](https://hub.docker.com/r/victoriametrics/vmauth).
In order to fix this you need to use `vmauth` repository:

```
apiVersion: operator.victoriametrics.com/v1beta1
kind: VMAuth
metadata:
  name: proxytest
  namespace: vm
spec:
  image:
    repository: victoriametrics/vmauth
    tag: v1.95.1
    pullPolicy: IfNotPresent
  podMetadata:
    labels:
      component: vmauth
  selectAllByDefault: true
  replicaCount: 1

```
