### ISSUE TITLE
Why .Alert.0.GeneratorURL is empty ?

### ISSUE THREAD

**Issue by icy** [VictoriaMetrics/VictoriaMetrics#5353]
### Is your question request related to a specific component?

vmalert, version v1.93.7
alert-manager, v0.26.0

### Describe the question in detail

In the slack message, I expect to see a button to `.GeneratorURL` but the field seem to be empty, and on Slack channel I couldn't find a link to original source of the alert.

### alertmanager configuration

I'm using the following `alertmanager` configuration

```
---
apiVersion: operator.victoriametrics.com/v1beta1
kind: VMAlertmanager
spec:
  replicaCount: 2
  selectAllByDefault: true
  externalURL: "https://mydomain.com/"
  templates:
  - key: slack.gotmpl
    name: awesome
  configSecret: vmalertmanager
  image:
    repository: prom/alertmanager
    tag: v0.26.0
    pullPolicy: IfNotPresent

```

### configSecret for alertmanager

```
global:
  resolve_timeout: 5m
templates: ['/etc/vm/templates/**/*.gotmpl']
route:
  group_wait: 30s
  group_interval: 100000m
  repeat_interval: 100000m
  receiver: 'slack_data-alert'
  group_by:
  - k8s_cluster
  - alertname
  - namespace
  - job
receivers:
- name: 'slack_data-alert'
  slack_configs:
  - channel: '#data-alert'
    send_resolved: true
    color: '{{ template "slack.color" . }}'
    title: '{{ template "slack.title" . }}'
    text: '{{ template "slack.text" . }}'
    actions:
    - type: button
      text: 'Runbook :green_book:'
      url: '{{ (index .Alerts 0).Annotations.runbook_url }}'
    - type: button
      text: 'Query :mag:'
      url: '{{ (index .Alerts 0).GeneratorURL }}'
    - type: button
      text: 'Dashboard :chart_with_upwards_trend:'
      url: '{{ (index .Alerts 0).Annotations.dashboard_url }}'
    - type: button
      text: 'Silence :no_bell:'
      url: '{{ template "__alert_silence_link" . }}'
```

## Vmalert configuration

```
## Doc: https://docs.victoriametrics.com/vmalert.html
## Doc: https://docs.victoriametrics.com/operator/resources/vmalert.html?highlight=VMAlert
---
apiVersion: operator.victoriametrics.com/v1beta1
kind: VMAlert
spec:
  evaluationInterval: "30s"
  selectAllByDefault: true
  # replicaCount: 2
  datasource:
    url: "http://vmselect-myname.metrics.svc.cluster.local:8481/select/0/prometheus"
  remoteRead:
    url: "http://vmselect-myname.metrics.svc.cluster.local:8481/select/0/prometheus"
  remoteWrite:
    url: "http://vminsert-myname.metrics.svc.cluster.local:8480/insert/0/prometheus"
  notifier:
    url: "http://vmalertmanager-myname.metrics.svc.cluster.local:9093"
  # for accessing to vmalert via vmauth with path prefix
  extraArgs:
    http.pathPrefix: /vmalert
  image:
    repository: victoriametrics/vmalert
    tag: v1.93.7
    pullPolicy: IfNotPresent

```

### Troubleshooting docs

- [x] General - https://docs.victoriametrics.com/Troubleshooting.html
- [X] vmagent - https://docs.victoriametrics.com/vmagent.html#troubleshooting
- [X] vmalert - https://docs.victoriametrics.com/vmalert.html#troubleshooting
