### ISSUE TITLE
Question on vmalert: what does alert "for: 0 " mean?

### ISSUE THREAD

**Issue by linrl3** [VictoriaMetrics/VictoriaMetrics#5360]
### Is your question request related to a specific component?

vmalert

### Describe the question in detail

The description comes from vmalert Readme https://github.com/VictoriaMetrics/VictoriaMetrics/blob/master/app/vmalert/README.md#configuration: 
`
Sometimes, it is not clear why some specific alert fired or didn't fire. It is very important to remember, that alerts with for: 0 fire immediately when their expression becomes true. And alerts with for > 0 will fire only after multiple consecutive evaluations, and at each evaluation their expression must be true. If at least one evaluation becomes false, then alert's state resets to the initial state.
`
My question if what is "for: 0" and "for > 0" mean here? It is a configuration for vmalert?

### Troubleshooting docs

- [ ] General - https://docs.victoriametrics.com/Troubleshooting.html
- [ ] vmagent - https://docs.victoriametrics.com/vmagent.html#troubleshooting
- [X] vmalert - https://docs.victoriametrics.com/vmalert.html#troubleshooting

**Comment by zekker6** [comment]
Hi @linrl3, yes, that is a part for configuration for each alert. For example:
```
groups:
- name: example
  rules:
  - alert: HighRequestLatency
    expr: my_metric > 0.5
    for: 10m
    labels:
      severity: page
    annotations:
      summary: High request latency
```

This alert defines `for: 10m`, the idea is that alert will not fire immediately once `my_metric > 0.5` will become true but will become "pending" and only after this expression will be true for 10m consecutively alert will become "firing".
