### ISSUE TITLE
Allow duplicate names of alerts in rule files

### ISSUE THREAD

**Issue by PavelKolobaev** [VictoriaMetrics/VictoriaMetrics#538]
**Describe the bug**
Allow duplicate names of alerts in rule files

**To Reproduce**
```
helm install stable/prometheus-operator
for f in `kubectl get prometheusrules.monitoring.coreos.com -o name`; do kubectl -n monitoring get prometheusrules.monitoring.coreos.com `basename $f` -o yaml > `basename $f`.yaml ; done
```
Clean files (delete strings from top to specs)
```
./vmalert-prod -remoteRead.url="http://127.0.0.1:8428" -notifier.url="http://127.0.0.1:9093" -datasource.url="http://127.0.0.1:8428" -rule="./*.yaml"
```

**Expected behavior**

We want replace vmalert in operator-prometheus. For backward compatibility need same behavior

**Version**
The line returned when passing `--version` command line flag to binary. For example:
```
./vmalert-prod --version
vmalert-20200605-191106-tags-v1.37.0-0-g69a647b0d
```

**Comment by wf1nder** [comment]
BTW, sometimes you need to have records with same name, but with different label set:
```
- record: some_metric_name:rate1h
    expr: source_metric_name_rate1h offset 2d
    labels:
      offset: 2d
- record: some_metric_name:rate1h
    expr: source_metric_name_rate1h offset 3d
    labels:
      offset: 3d
```
Despite that records have same name, actually this is not duplicates because they will return metrics with different label set.
