### ISSUE TITLE
VMSTORAGE being unable to create lock file

### ISSUE THREAD

**Issue by brandshaide** [VictoriaMetrics/VictoriaMetrics#5404]
### Is your question request related to a specific component?

vmstorage

### Describe the question in detail

I'm deploying VM with the provided Helm Charts and vmstorage is failing with a CrashLoopBackoff (see error message below). I've been configuring prometheus `remote_write` URL in order digest data to VM. 

```
{"ts":"2023-11-28T10:41:01.277Z","level":"panic","caller":"VictoriaMetrics/lib/fs/fs.go:366","msg":"FATAL: cannot create lock file: cannot create lock file \"/storage/flock.lock\": open /storage/flock.lock: permission denied; make sure a single process has exclusive access to \"/storage\""}
```

### Troubleshooting docs

- [X] General - https://docs.victoriametrics.com/Troubleshooting.html
- [X] vmagent - https://docs.victoriametrics.com/vmagent.html#troubleshooting
- [X] vmalert - https://docs.victoriametrics.com/vmalert.html#troubleshooting

**Comment by f41gh7** [comment]
Hello, 
 Possible reasons of this issue:
1) helm chart configured with replicas > 1 and read-write-many storage. It's not supported case, for HA it's recommended to use vmcluster.
2) securityContext changed. By default, helm chart doesn't set any securityContext related fields. If it was modified, it's necessary to manually adjust folder persmissions for configured user (or via initContainer).

**Comment by brandshaide** [comment]
>     2. securityContext changed. By default, helm chart doesn't set any securityContext related fields. If it was modified, it's necessary to manually adjust folder persmissions for configured user (or via initContainer).

@f41gh7 thanks a lot for your help, I'd have expected those adapted `securityContext` to actually work: 

```
securityContext:
  runAsUser: 1000
  runAsGroup: 1000
  fsGroup: 1000
  runAsNonRoot: true 
  allowPrivilegeEscalation: false 
  seccompProfile:
    type: RuntimeDefault
```

**Comment by brandshaide** [comment]
```
initContainers: 
  - name: permission
    image: library/alpine
     securityContext: 
        runAsUser: 1000
        runAsGroup: 1000
        fsGroup: 1000
        capabilities: 
          add: ["CHOWN"]
        seccompProfile: 
           type: RuntimeDefault 
        readOnlyFilesystem: false
        runAsNonRoot: true
        allowPrivilegeEscalation: false 
        command:  
        - sh 
        - -c
        - | 
        - chown 1000:1000 /storage
     volumeMounts:
     -  name: vmstorage-volume
     -  mountPath: /storage
 ```
 But facing 

```
permission chown: /storage: Operation not permitted
```
