### ISSUE TITLE
VMAgent does not attach bearer_token when following redirects

### ISSUE THREAD

**Issue by ptimofee** [VictoriaMetrics/VictoriaMetrics#5425]
### Describe the bug

VMAgent does not attach bearer_token when following redirects.

There's another issue about [broken redirects](https://github.com/VictoriaMetrics/VictoriaMetrics/issues/1945), but I also discovered that vmagent does not (re)attach bearer_token even if you make redirects work.

The only case when vmagent DOES attach bearer token is if the endpoint redirects to itself, but to different port.

### To Reproduce

Spawn web server like nginx on HOST1 (`apt install nginx` on fresh ubuntu 22.04), add this config
```
cat /etc/nginx/conf.d/test.conf
server {
 listen      8000;
 return      307 http://<HOST2>:8000$request_uri;
}
```
Restart nginx with `systemctl restart nginx`

Spawn any tool to see traffic on HOST2 (ubuntu 22.04):
```
nc -k -l 8000
```

Ask vmagent to scrape HOST1:8000 with any bearer_token:
```
- job_name: test-scrape
  scrape_interval: 15s
  scrape_timeout: 15s
  metrics_path: /metrics
  honor_labels: true
  honor_timestamps: true
  scheme: http
  bearer_token: MYTOKEN
  static_configs:
  - targets:
    - <HOST2>:8000
  stream_parse: true
```

Verify there is no Authorization header in nc output on HOST2

### Version

v1.93.4
