### ISSUE TITLE
count_over_time and other aggregation functions returns wrong result for subquery range vector

### ISSUE THREAD

**Issue by maksimr** [VictoriaMetrics/VictoriaMetrics#5452]
### Describe the bug

Subquery return range vector with 3 samples if apply `count_over_time` it returns only 2 samples, discarding last sample. The same result for other agg. functions like `sum_over_time` etc

### To Reproduce

1. Create a service which returns metrics

```javascript
require('http').createServer(function(req, res) {
  if (req.url === '/metrics') {
    const metricName = 'foo';
    const metricType = 'gauge';
    const metricValue = new Date().getSeconds();
    const metricTimestamp = new Date().getTime();
    console.log(`(${metricValue},${metricTimestamp / 1000})`);
    res.writeHead(200, { 'Content-Type': 'text/plain' });
    res.write(`# TYPE ${metricName} ${metricType}\n`);
    res.end(`${metricName} ${metricValue} ${metricTimestamp}\n`);
    return;
  }
  res.writeHead(404, { 'Content-Type': 'text/plain' });
  res.end('Not found\n');
}).listen(3000, () => console.log(new Date(), 'Listening on port 3000'));
```

2. Add prometheus.yaml
```yaml
global:
  scrape_interval:     15s
  external_labels:
    monitor: 'codelab-monitor'

scrape_configs:
  - job_name: 'test'
    scrape_interval: 1s
    honor_timestamps: true
    static_configs:
      - targets: ['localhost:3000']
```

3. Run service `node ./index.js`
4. Run victoria metrics
```bash
./victoria-metrics-prod -promscrape.config=./prometheus.yml
```
5. Open `http://localhost:8428/vmui`
6. Type query `foo[2s:1s]` - this should return 3 samples
7. Type query `count_over_time(foo[2s:1s])` for the same evaluation timestamp

ER: 3
AR: 2

### Version

victoria-metrics-20231116-193603-tags-v1.95.1-0-g354563393

### Screenshots

<img width="1440" alt="image" src="https://github.com/VictoriaMetrics/VictoriaMetrics/assets/616193/d4f7bf98-6f04-4d99-bc3c-1e7f484a06fa">
<img width="1427" alt="image" src="https://github.com/VictoriaMetrics/VictoriaMetrics/assets/616193/6a412b2b-d59c-4052-ab82-dfdcf9c92b4e">
