### ISSUE TITLE
vmalert fails to start with "cannot parse configuration file"

### ISSUE THREAD

**Issue by antoinedeschenes** [VictoriaMetrics/VictoriaMetrics#5478]
### Describe the bug

Some invalid rules sometimes get through vmoperator as per https://github.com/VictoriaMetrics/operator/issues/820

If these alert rules get provisioned while the vmalert pod is already running, the `vmalert_config_last_reload_errors_total` counter gets incremented and there's a log output showing a `cannot parse configuration file: failed to parse` error, but the pod continues to run.

If the vmalert pod is restarted for some reason, the replacement pod will fail to start and get stuck in a CrashLoopBackOff until the problem VMRule resource is deleted. 

I'd expect the vmalert process to notify about invalid alerting rules in logs and metrics while still starting successfully.

### To Reproduce

1. Set up an invalid VMRule passing through Operator validation

```yaml
apiVersion: operator.victoriametrics.com/v1beta1
kind: VMRule
metadata:
  name: foo-alerts
  namespace: bar
spec:
  groups:
    - name: foo-alerts
      rules:
        - alert: FooError
          annotations:
            summary: Foo error {{ $type }}
            description: |-
              Foo error {{ $type }}
              VALUE = {{ $value }}
          expr: up{} == 1
          for: 5m
```

2. Observe config reload errors on the existing vmalert pod, which continues to run successfully.
3. Restart the vmalert pod. It will CrashLookBackOff and won't start until the offending rule is deleted.

### Version

/ # ./vmalert-prod --version
vmalert-20231101-225523-tags-v1.93.7-0-g6177975aa

### Logs

```
{
  "ts": "2023-12-15T15:52:33.414Z",
  "level": "fatal",
  "caller": "VictoriaMetrics/app/vmalert/main.go:176",
  "msg": "cannot parse configuration file: failed to parse [/etc/vmalert/config/vm-vmstack-rulefiles-0/*.yaml /etc/vmalert/config/vm-vmstack-rulefiles-1/*.yaml]: errors(1): invalid group \"foo-alerts\" in file \"/etc/vmalert/config/vm-vmstack-rulefiles-0/bar-foo-alerts.yaml\": invalid annotations for rule \"foo-alerts\".\"FooError\": errors(2): key \"description\", template \"Foo error {{ $type }}\\nVALUE = {{ $value }}\": error parsing annotation template: template: :1: undefined variable \"$type\"\nkey \"summary\", template \"Foo error {{ $type }}\": error parsing annotation template: template: :1: undefined variable \"$type\""
}
```

### Used command-line flags

```
-datasource.url="secret"
-evaluationInterval="5m0s"
-external.alert.source="explore?orgId=1&left=%7B%22datasource%22%3A%22VictoriaMetrics%22%2C%22queries%22%3A%5B%7B%22expr%22%3A{{$expr|jsonEscape|queryEscape}}%2C%22refId%22%3A%22A%22%7D%5D%2C%22range%22%3A%7B%22from%22%3A%22now-1h%22%2C%22to%22%3A%22now%22%7D%7D"
-external.label="cluster=foo-cluster"
-external.url="https://grafana.example.com/"
-httpListenAddr=":8080"
-loggerFormat="json"
-loggerLevel="WARN"
-notifier.url="secret"
-remoteRead.url="secret"
-remoteWrite.disablePathAppend="true"
-remoteWrite.url="secret"
-rule="/etc/vmalert/config/vm-vmstack-rulefiles-0/*.yaml"
-rule.resendDelay="4m30s"
```
