### ISSUE TITLE
vmagent: how to send metrics to mulitple grafana cloud instances ? (multitenant)

### ISSUE THREAD

**Issue by LeoHnvl** [VictoriaMetrics/VictoriaMetrics#5500]
### Is your question request related to a specific component?

vmagent

### Describe the question in detail

Hello my friends,

I actually have 2 vmagent scraping different targets with multitenancy relabelling (vm_account_id, vm_project_id) which I need to send to different grafana cloud instances. Since I can't use the remote_write protocol in my prometheus configuration file (https://docs.victoriametrics.com/vmagent.html#unsupported-prometheus-config-sections)

How can I achieve that using the command-line flags ? Should I use the relabel anyway ?

```
scrape_configs:
  - job_name: example_1                      <----- this target needs to be sent to grafana cloud 1st instance
    dns_sd_configs:
      - names: ['tasks.victoria_vmagent']
        type: 'A'
        port: 8429
    relabel_configs:
      - target_label: "vm_account_id"
        replacement: 12488

  - job_name: example_2                      <----- this target needs to be sent to grafana cloud 2nd instance
    dns_sd_configs:
      - names: ['tasks.victoria_vminsert']
        type: 'A'
        port: 8480
    relabel_configs:
      - target_label: "vm_account_id"
        replacement: 148769
```

### Troubleshooting docs

- [X] General - https://docs.victoriametrics.com/Troubleshooting.html
- [X] vmagent - https://docs.victoriametrics.com/vmagent.html#troubleshooting
- [x] vmalert - https://docs.victoriametrics.com/vmalert.html#troubleshooting
