### ISSUE TITLE
vmauth additional per user metrics for SLO/SLI calculation. User metric labels.

### ISSUE THREAD

**Issue by f41gh7** [VictoriaMetrics/VictoriaMetrics#5565]
### Is your feature request related to a problem? Please describe

 Currently, vmauth exposes:
`vmauth_user_requests_total`
`vmauth_user_request_duration_seconds`
`vmauth_user_concurrent_requests_limit_reached_total`

 It's not enough to calculate service level. 

 Also, those metrics have only `username` as label. It's hard to aggregate given metrics and requires to encode additional into name label. 

### Describe the solution you'd like

 It'd be great to expose request errors metric, when request to all backends failed (retry doesn't count as error for this case). 

 Proposed name - `vmauth_user_requests_errors_total`

It allows to calculate error budget for services behind vmauth.

 In addition, it'd be great to have configurable labels for per user metrics.

```yaml
users:
- username: tenant1
  password: "***"
  name: dev-1
 # vmauth_user_requests_total{username="dev-1", users_group="dev",users_backend_location="dc-0"}
 # vmauth_user_requests_errors_total{username="dev-1", users_group="dev",users_backend_location="dc-0"}
  metricLabels:
  - users_group="dev"
  - users_backend_location="dc-0"
  url_map:
  - src_paths:
    - "/api/v1/write"
    url_prefix: "http://vminsert-backend-dc-0:8480/insert/1/prometheus/"
- username: accounting-access-1
  password: "***"
  name: accountant-1
  metricLabels:
  - users_group="accounting"
  - users_backend_location="dc-15"
  url_map:
  - src_paths:
    - "/api/v1/write"
    url_prefix: "http://vminsert-dc-1:8480/insert/1/prometheus/"
- username: accounting-access-2
  password: "***"
  name: accountant-2
  metricLabels:
  - users_group="accounting"
  - users_backend_location="dc-15"
  url_map:
  - src_paths:
    - "/api/v1/write"
    url_prefix: "http://vminsert-dc-1:8480/insert/1/prometheus/"
```
