### ISSUE TITLE
latency of using vector to collect logs from k8s pods to victorialogs

### ISSUE THREAD

**Issue by code1704** [VictoriaMetrics/VictoriaMetrics#5572]
### Is your question request related to a specific component?

victorialogs

### Describe the question in detail

It takes 30s to 1m to get logs from victorialogs. Any suggest to get realtime log?

```
      victorialogs:
        type: elasticsearch
        inputs:
          - task_logs_transform
        api_version: auto
        healthcheck:
          enabled: false
        mode: bulk
        bulk:
          index: hellovl
        endpoints:
          - 'http://**.**.svc.cluster.local:9428/insert/elasticsearch/'
        tls:
          verify_certificate: false
          verify_hostname: false
        ..
```

### Troubleshooting docs

- [ ] General - https://docs.victoriametrics.com/Troubleshooting.html
- [ ] vmagent - https://docs.victoriametrics.com/vmagent.html#troubleshooting
- [ ] vmalert - https://docs.victoriametrics.com/vmalert.html#troubleshooting
