### ISSUE TITLE
Required 'compute.zones.list' permission for project

### ISSUE THREAD

**Issue by igorhrcek** [VictoriaMetrics/VictoriaMetrics#5597]
### Is your question request related to a specific component?

vmagent

### Describe the question in detail

I have the following vmagent configuration:
```
    vmagent:
      enabled: true
      spec:
        image:
          # renovate: datasource=docker depName=victoriametrics/vmagent
          tag: v1.90.0
        replicaCount: 1
        extraArgs:
          promscrape.maxScrapeSize: "56777216"
        nodeSelector:
          component: "services"
        resources:
          requests:
            cpu: "150m"
            memory: "75Mi"
          limits:
            cpu: "1"
            memory: "1Gi"
        externalLabels:
          cluster: "production"
          environment: "prod"
        inlineScrapeConfig: |
          - job_name: node_gce
            honor_labels: true
            scrape_interval: 5s
            gce_sd_configs:
              - zone: "europe-west4-a"
                project: xyz
                port: 9100
                filter: (name ne .*.dev.*) (name ne gke.*)
            relabel_configs:
              - source_labels: [__meta_gce_instance_name]
                target_label: instance
              - source_labels: [__meta_gce_label_environment]
                target_label: environment
              - source_labels: [__meta_gce_label_type]
                target_label: instance_type
              - source_labels: [instance]
                regex: "gke.*"
                action: drop
```

For this scrape job I am constantly getting the following error:
```
│ vmagent 2024-01-10T20:42:08.215Z    error    VictoriaMetrics/lib/promscrape/discovery/gce/instance.go:46    cannot collect instances from zone "europe-west4-a": cannot obtain instances: unexpected status code for "https://compute.goo │
│ gleapis.com/compute/v1/projects/xxx/zones/europe-west4-b/instances?filter=%28name+ne+.%2A.dev.%2A%29+%28name+ne+gke.%2A%29"; got 403; want 200; response body: "{\n  \"error\": {\n    \"code\": 403,\n    \"message\": \"Required  │
│ 'compute.instances.list' permission for 'projects/xxx'\",\n    \"errors\": [\n      {\n        \"message\": \"Required 'compute.instances.list' permission for 'projects/xxx'\",\n        \"domain\": \"global\",\n        \" │
│ reason\": \"forbidden\"\n      }\n    ]\n  }\n}\n"                                                                                                                                                                                        │```

VictoriaMetrics was deployed using victoria-metrics-k8s-stack helm chart. The `serviceAccount` is set to `enabled` in configuration and I am unsure who exactly is missing this permission nor how to fix this issue? 

### Troubleshooting docs

- [X] General - https://docs.victoriametrics.com/Troubleshooting.html
- [X] vmagent - https://docs.victoriametrics.com/vmagent.html#troubleshooting
- [X] vmalert - https://docs.victoriametrics.com/vmalert.html#troubleshooting

**Comment by zekker6** [comment]
Hello @igorhrcek 

This error means that vmagent was not able to execute `compute.instances.list` for `projects/xxx` via GCP API.

In order to solve this you need to create a service account in k8s and link it with GCP service account which has permissions to perform such API calls by using [Workload Identity configuration](https://cloud.google.com/kubernetes-engine/docs/concepts/workload-identity).
After that you need to modify vmagent spec to use this custom service account:
```
    vmagent:
      enabled: true
      spec:
        image:
          # renovate: datasource=docker depName=victoriametrics/vmagent
          tag: v1.90.0
        replicaCount: 1
        extraArgs:
          promscrape.maxScrapeSize: "56777216"
        nodeSelector:
          component: "services"
        serviceAccountName: "{CUSTOM_SERVICE_ACCOUNT_NAME}"
        resources:
          requests:
            cpu: "150m"
            memory: "75Mi"
          limits:
            cpu: "1"
            memory: "1Gi"
        externalLabels:
          cluster: "production"
          environment: "prod"
        inlineScrapeConfig: |
          - job_name: node_gce
            honor_labels: true
            scrape_interval: 5s
            gce_sd_configs:
              - zone: "europe-west4-a"
                project: xyz
                port: 9100
                filter: (name ne .*.dev.*) (name ne gke.*)
            relabel_configs:
              - source_labels: [__meta_gce_instance_name]
                target_label: instance
              - source_labels: [__meta_gce_label_environment]
                target_label: environment
              - source_labels: [__meta_gce_label_type]
                target_label: instance_type
              - source_labels: [instance]
                regex: "gke.*"
                action: drop
```
