### ISSUE TITLE
load balancer for vmagent

### ISSUE THREAD

**Issue by sudheer552** [VictoriaMetrics/VictoriaMetrics#5599]
### Is your question request related to a specific component?

vmagent

### Describe the question in detail

how can we bring up loadbalancer for vmagent.

### Troubleshooting docs

- [ ] General - https://docs.victoriametrics.com/Troubleshooting.html
- [ ] vmagent - https://docs.victoriametrics.com/vmagent.html#troubleshooting
- [ ] vmalert - https://docs.victoriametrics.com/vmalert.html#troubleshooting

**Comment by sudheer552** [comment]
we are trying to deploy it with vmagent / vmooperator crd but not able to create a load balancer.

**Comment by sudheer552** [comment]
```
apiVersion: operator.victoriametrics.com/v1beta1
kind: VMAgent
metadata:
  name: vmtest-cluster
spec:
  selectAllByDefault: true
  replicaCount: 2
  remoteWrite:
    - url: "http://xxxx:8480/insert/0/prometheus/api/v1/write"
    - url: "https://xxxx/prometheus/api/v1/write"
      urlRelabelConfig:
        name: "configmap-vmagent-env"
        key: "vmagent.env.yaml"
    - url: "[http://XXXXXXX:80/api/v1/write](http://xxxxxxx/api/v1/write)"
      urlRelabelConfig:
        name: "configmap-vmagent-env"
        key: "vmagent.env.yaml"
  volumeMounts:
  - name: grafana-ca-cert
    mountPath: /etc/ssl/certs/cert.pem
    subPath: cert.pem
  - name: grafana-ca-cert
    mountPath: /etc/ssl/certs/certs2.pem
    subPath: certs2.pem
  volumes:
  - name: ca-cert
      name: configmap-ca-cert
```
not able to create service spec within the above crd as below.

    service:
      enabled: true
      type: LoadBalancer
      servicePort: 8429
      ports:
        - name: https
          port: 443
          protocol: TCP
          targetPort: 8429
      annotations:
        service.beta.kubernetes.io/aws-load-balancer-internal: 'true'
        service.beta.kubernetes.io/aws-load-balancer-type: 'nlb'
        service.beta.kubernetes.io/aws-load-balancer-backend-protocol: 'tcp'
        service.beta.kubernetes.io/aws-load-balancer-cross-zone-load-balancing-enabled: 'true'
        service.beta.kubernetes.io/aws-load-balancer-subnets: 'xxx
        service.beta.kubernetes.io/aws-load-balancer-ssl-negotiation-policy: 'ELBSecurityPolicy-TLS-1-2-2017-01'
        service.beta.kubernetes.io/aws-load-balancer-ssl-cert: 'xxx'
        
        
      We are planning to remote_write metrics to vmagent loadbalancer URL.

**Comment by sudheer552** [comment]
vmagent-vmtest-cluster                      ClusterIP   x.x.x.x   <none>        8429/TCP   2d
vmagent-vmtest-cluster-additional-service   ClusterIP   x.x.x.x   <none>        8429/TCP   2d

**Comment by zekker6** [comment]
@sudheer552 It seems like there is an unexpected `service` key added in the manifest at `spec.serviceSpec.service`. An expected format is:
```
apiVersion: operator.victoriametrics.com/v1beta1
kind: VMAgent
metadata:
  name: vmtest-cluster
spec:
  selectAllByDefault: true
  replicaCount: 2
  serviceSpec:
    spec:
      type: LoadBalancer
      servicePort: 8429
      ports:
        - name: https
          port: 443
          protocol: TCP
          targetPort: 8429
      annotations:
        service.beta.kubernetes.io/aws-load-balancer-internal: 'true'
        service.beta.kubernetes.io/aws-load-balancer-type: 'nlb'
        service.beta.kubernetes.io/aws-load-balancer-backend-protocol: 'tcp'
        service.beta.kubernetes.io/aws-load-balancer-cross-zone-load-balancing-enabled: 'true'
        service.beta.kubernetes.io/aws-load-balancer-subnets: 'xxx'
        service.beta.kubernetes.io/aws-load-balancer-ssl-negotiation-policy: 'ELBSecurityPolicy-TLS-1-2-2017-01'
        service.beta.kubernetes.io/aws-load-balancer-ssl-cert: 'xxx'
        service.beta.kubernetes.io/aws-load-balancer-ssl-ports: '443'
  remoteWrite:
    - url: "http://vminsert-vmtest-cluster.vm.svc.cluster.local:8480/insert/0/prometheus/api/v1/write"
    - url: "https://prometheus-server1/prometheus/api/v1/write"
      urlRelabelConfig:
        name: "configmap-vmagent-env"
        key: "vmagent.env.yaml"
    - url: "[http://prometheus-server2.prometheus-vm.svc.cluster.local:80/api/v1/write](http://prometheus-server2.prometheus-vm.svc.cluster.local/api/v1/write)"
      urlRelabelConfig:
        name: "configmap-vmagent-env"
        key: "vmagent.env.yaml"
```
