### ISSUE TITLE
vmctl: Migration Imports huge data but all the data doesn't show up.

### ISSUE THREAD

**Issue by shivtej-opsverse** [VictoriaMetrics/VictoriaMetrics#5601]
### Is your question request related to a specific component?

vmctl

### Describe the question in detail

I am trying to migrate my data from `vmsingle` to `vmcluster`. Currently Trying with 4 days of data for validation.
Both `vmsingle` and `vmcluster` are running in a gke cluster in the same namespace.
Following is the job i am using:

```
apiVersion: batch/v1
kind: Job
metadata:
  name: vmctl-migrate-data
  namespace: acme-phi-observe
spec:
  template:
    spec:
      containers:
      - name: vmctl
        image: victoriametrics/vmctl:latest
        args:
          - vm-native
          - --vm-native-filter-time-start=2023-12-16T00:00:00Z
          - --vm-native-filter-time-end=2023-12-18T00:00:00Z
          - --vm-native-step-interval=hour
          - --vm-native-src-addr=http://<vmsingle-svc-name>:8429
          - --vm-native-dst-addr=http://<vminsert-svc-name>:8480/insert/0/prometheus
          - --vm-native-filter-match={__name__!=""}
          - --vm-native-disable-retries=True
        resources:
          limits:
            cpu: '1'
            memory: 1Gi
          requests:
            cpu: 100m
            memory: 100Mi
      restartPolicy: Never
  backoffLimit: 2
``` 
Following is the log output of the job

```
2024/01/10 17:34:27 Import finished!
2024/01/10 17:34:27 VictoriaMetrics importer stats:
  time spent while importing: 9h23m42.595781842s;
  total bytes: 343.5 GB;
  bytes/s: 10.2 MB;
  requests: 48;
  requests retries: 0;
2024/01/10 17:34:27 Total time: 9h23m42.600763487s

```

The strange thing is when i check the vmsingle pvc i see only 261 Gigs of data but the import shows `343.5 GB`
Note that this is the total sapce used.
The data for 2 days should be even lesser than this.
```
➜  ~ kubectl exec --tty --stdin <vmsingle-pod-name>   -- df -h
Defaulted container "vmsingle" out of: vmsingle, vmbackup
Filesystem                Size      Used Available Use% Mounted on
overlay                  94.3G      7.3G     87.0G   8% /
tmpfs                    64.0M         0     64.0M   0% /dev
tmpfs                     3.9G         0      3.9G   0% /sys/fs/cgroup
/dev/sdb                344.3G    261.9G     82.4G  76% /victoria-metrics-data
/dev/sda1                94.3G      7.3G     87.0G   8% /etc/hosts
/dev/sda1                94.3G      7.3G     87.0G   8% /dev/termination-log
/dev/sda1                94.3G      7.3G     87.0G   8% /etc/hostname
/dev/sda1                94.3G      7.3G     87.0G   8% /etc/resolv.conf
shm                      64.0M         0     64.0M   0% /dev/shm
tmpfs                     5.9G     12.0K      5.9G   0% /run/secrets/kubernetes.io/serviceaccount
tmpfs                     3.9G         0      3.9G   0% /proc/acpi
tmpfs                    64.0M         0     64.0M   0% /proc/kcore
tmpfs                    64.0M         0     64.0M   0% /proc/keys
tmpfs                    64.0M         0     64.0M   0% /proc/timer_list
tmpfs                     3.9G         0      3.9G   0% /proc/scsi
tmpfs                     3.9G         0      3.9G   0% /sys/firmware

```
And after the migration the pvc doesn't seem to have above said data (343.5 GB)

```
➜  ~ kubectl exec --tty --stdin <vmstorage-0>    -- df -h
Filesystem                Size      Used Available Use% Mounted on
overlay                  94.3G      3.5G     90.7G   4% /
tmpfs                    64.0M         0     64.0M   0% /dev
/dev/sdb                246.0G    587.1M    245.4G   0% /vm-data
/dev/sda1                94.3G      3.5G     90.7G   4% /etc/hosts
/dev/sda1                94.3G      3.5G     90.7G   4% /dev/termination-log
/dev/sda1                94.3G      3.5G     90.7G   4% /etc/hostname
/dev/sda1                94.3G      3.5G     90.7G   4% /etc/resolv.conf
shm                      64.0M         0     64.0M   0% /dev/shm
tmpfs                     1.5G     12.0K      1.5G   0% /run/secrets/kubernetes.io/serviceaccount
tmpfs                     1.9G         0      1.9G   0% /proc/acpi
tmpfs                    64.0M         0     64.0M   0% /proc/kcore
tmpfs                    64.0M         0     64.0M   0% /proc/keys
tmpfs                    64.0M         0     64.0M   0% /proc/timer_list
tmpfs                     1.9G         0      1.9G   0% /proc/scsi
tmpfs                     1.9G         0      1.9G   0% /sys/firmware
➜  ~ kubectl exec --tty --stdin <vmstorage-1>    -- df -h
Filesystem                Size      Used Available Use% Mounted on
overlay                  94.3G      7.6G     86.6G   8% /
tmpfs                    64.0M         0     64.0M   0% /dev
/dev/sdb                246.0G    531.5M    245.4G   0% /vm-data
/dev/sda1                94.3G      7.6G     86.6G   8% /etc/hosts
/dev/sda1                94.3G      7.6G     86.6G   8% /dev/termination-log
/dev/sda1                94.3G      7.6G     86.6G   8% /etc/hostname
/dev/sda1                94.3G      7.6G     86.6G   8% /etc/resolv.conf
shm                      64.0M         0     64.0M   0% /dev/shm
tmpfs                     1.5G     12.0K      1.5G   0% /run/secrets/kubernetes.io/serviceaccount
tmpfs                     3.9G         0      3.9G   0% /proc/acpi
tmpfs                    64.0M         0     64.0M   0% /proc/kcore
tmpfs                    64.0M         0     64.0M   0% /proc/keys
tmpfs                    64.0M         0     64.0M   0% /proc/timer_list
tmpfs                     3.9G         0      3.9G   0% /proc/scsi
tmpfs                     3.9G         0      3.9G   0% /sys/firmware
```

On top all this the data for two days doesn't seem to be migrated completely (Find image below)
![Comparison](https://github.com/VictoriaMetrics/VictoriaMetrics/assets/98976553/6edfec1d-70f1-4814-9038-2ff62834c716)

Please Let me Know If i am going wrong somewhere.

### Troubleshooting docs

- [X] General - https://docs.victoriametrics.com/Troubleshooting.html
- [X] vmagent - https://docs.victoriametrics.com/vmagent.html#troubleshooting
- [X] vmalert - https://docs.victoriametrics.com/vmalert.html#troubleshooting
