### ISSUE TITLE
How to understand the vmSelect parameter maxSamplesPerQuery 

### ISSUE THREAD

**Issue by whc9527** [VictoriaMetrics/VictoriaMetrics#5613]
### Is your question request related to a specific component?

vmselect

### Describe the question in detail

Deploy with helm mode, The deployment command is helm upgrade --install algo vm/victoria-metrics-cluster -n hawkeye-algo --version 0.11.8 -f victoriaMetrics/example.yaml
vmSelect options in example.yaml:

```
  extraArgs:
    envflag.enable: "true"
    envflag.prefix: VM_
    loggerFormat: json
    replicationFactor: 3
    dedup.minScrapeInterval: 240s
    search.maxSamplesPerQuery: "30000000"
    search.maxQueryDuration: 10m
    search.logSlowQueryDuration: 30s
```

vmStorage options in example.yaml:

```
extraArgs:
envflag.enable: "true"
envflag.prefix: VM_
loggerFormat: json
# https://docs.victoriametrics.com/Cluster-VictoriaMetrics.html#cluster-availability
dedup.minScrapeInterval: 4m
search.maxConcurrentRequests: 2000
http.connTimeout: 10m
http.idleConnTimeout: 10m
```

Question:
I developed a program that reads data from promehteus' /fedration interface every 4 minutes and writes it to victoriaMetrics

**Query A: count(dsp_rt_merger_juno_sum{region="ali_vg"})**
In Thanos:
![image](https://github.com/VictoriaMetrics/VictoriaMetrics/assets/17898805/9484565b-6a94-4fea-bb74-931bf7ec823f)

In victoriaMetrics:
![image](https://github.com/VictoriaMetrics/VictoriaMetrics/assets/17898805/308e194c-df76-4c4f-9859-b634e1dd464b)

**Query B: count(dsp_rt_merger_juno_sum{region="ali_vg", instance="172.21.8.170:10002"})**
In victoriaMetrics
![image](https://github.com/VictoriaMetrics/VictoriaMetrics/assets/17898805/59f198cc-6618-42de-b4d0-f17afd8e2643)

To Query A, due to search in victoriaMetrics. MaxSamplesPerQuery parameters restrictions cause vmselect cannot complete the request. With Query B, 12 hours of data can be queried. I now have two questions

Question 1:
Does increasing maxSamplesPerQuery for vmselect stress the vmstorage, for example, does it cause the vmstorage oom

Question 2:
Data is 4 min written to vmstorage once, dsp_rt_merger_juno_sum {region = "ali_vg"} article if according to the highest at the time of 10 w data, search. MaxSamplesPerQuery: The "30000000 "configuration supports data query ranges much larger than 12 hours

### Troubleshooting docs

- [ ] General - https://docs.victoriametrics.com/Troubleshooting.html
- [ ] vmagent - https://docs.victoriametrics.com/vmagent.html#troubleshooting
- [ ] vmalert - https://docs.victoriametrics.com/vmalert.html#troubleshooting
