### ISSUE TITLE
How to configure Victoria Metrics as datasource in Grafana Cloud?

### ISSUE THREAD

**Issue by evertonspader-tomtom** [VictoriaMetrics/VictoriaMetrics#5624]
### Is your question request related to a specific component?

VictoriaMetrics and vmselect

### Describe the question in detail

Since Victoria Metrics data source plugin for Grafana is not signed and Grafana Cloud doesn't accept unsigned plugins to be connected, I have to connect the VM datasource via Prometheus type.

I am, therefore, struggling to get the configuration right. I've seen [this issue](https://github.com/VictoriaMetrics/helm-charts/issues/80) but it didn't help me much.

I have already tried:
```
https://<vmselect-endpoint>:8481
https://<vmselect-endpoint>:8481/select/0/prometheus
```

But the error is always the same:

```
Post "https://<vmselect-endpoint>:8481/select/0:0/prometheus/api/v1/query": dial tcp <IP>:8481: i/o timeout - There was an error returned querying the Prometheus API.
```

I can visit https://<vmselect-endpoint> in a browser and I see and HTML page like the one below so I know the URL is valid:
```
vmselect - a component of VictoriaMetrics cluster
[docs](https://docs.victoriametrics.com/Cluster-VictoriaMetrics.html)
```

What is the correct URL or configuration that I should use? 

### Troubleshooting docs

- [ ] General - https://docs.victoriametrics.com/Troubleshooting.html
- [ ] vmagent - https://docs.victoriametrics.com/vmagent.html#troubleshooting
- [ ] vmalert - https://docs.victoriametrics.com/vmalert.html#troubleshooting

**Comment by Haleygo** [comment]
Hello!
`https://<vmselect-endpoint>:8481/select/0/prometheus` should work for grafana datasource, can you check if grafana cloud can access `<IP>:8481`?
I tested it with our [playground](https://play.victoriametrics.com/) address `https://play.victoriametrics.com/select/accounting/1/6a716b0f-38bc-4856-90ce-448fd713e3fe/prometheus` and it works.
<img width="1926" alt="image" src="https://github.com/VictoriaMetrics/VictoriaMetrics/assets/39937150/c98dbd75-a54b-4ab2-9e54-c4c768fc1941">
<img width="1897" alt="image" src="https://github.com/VictoriaMetrics/VictoriaMetrics/assets/39937150/aecfe238-8c15-44e4-81e5-168ba4bcf64c">

**Comment by evertonspader-tomtom** [comment]
The only way I got it to work was using the port 443. I don't think anyone has added any values that changed the port.

**Comment by hagen1778** [comment]
Sorry for the assigns mess. I thought it is related to VM Cloud(

@evertonspader-tomtom is your vmselect exposed on :443 port?

**Comment by evertonspader-tomtom** [comment]
@hagen1778 not really. This is the default configuration deployed from the k8s-stack helm chart.
```
apiVersion: v1
kind: Service
metadata:
  annotations:
    meta.helm.sh/release-name: victoria-metrics-k8s-stack
    meta.helm.sh/release-namespace: monitoring
  finalizers:
  - apps.victoriametrics.com/finalizer
  labels:
    app.kubernetes.io/component: monitoring
    app.kubernetes.io/instance: victoria-metrics-k8s-stack
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: vmselect
    app.kubernetes.io/version: v1.94.0
    helm.sh/chart: victoria-metrics-k8s-stack-0.18.5
    managed-by: vm-operator
  name: vmselect-victoria-metrics-k8s-stack
  namespace: monitoring
 spec:
  clusterIP: None
  clusterIPs:
  - None
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - name: http
    port: 8481
    protocol: TCP
    targetPort: 8481
  selector:
    app.kubernetes.io/component: monitoring
    app.kubernetes.io/instance: victoria-metrics-k8s-stack
    app.kubernetes.io/name: vmselect
    managed-by: vm-operator
  sessionAffinity: None
  type: ClusterIP
```

```
apiVersion: apps/v1
kind: StatefulSet
metadata:
  annotations:
    meta.helm.sh/release-name: victoria-metrics-k8s-stack
    meta.helm.sh/release-namespace: monitoring-ha
  finalizers:
  - apps.victoriametrics.com/finalizer
  generation: 1
  labels:
    app.kubernetes.io/component: monitoring
    app.kubernetes.io/instance: victoria-metrics-k8s-stack
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: vmselect
    app.kubernetes.io/version: v1.94.0
    helm.sh/chart: victoria-metrics-k8s-stack-0.18.5
    managed-by: vm-operator
  name: vmselect-victoria-metrics-k8s-stack
  namespace: monitoring-ha
  ownerReferences:
  - apiVersion: operator.victoriametrics.com/v1beta1
    blockOwnerDeletion: true
    controller: true
    kind: VMCluster
    name: victoria-metrics-k8s-stack
spec:
  persistentVolumeClaimRetentionPolicy:
    whenDeleted: Retain
    whenScaled: Retain
  podManagementPolicy: Parallel
  replicas: 2
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app.kubernetes.io/component: monitoring
      app.kubernetes.io/instance: victoria-metrics-k8s-stack
      app.kubernetes.io/name: vmselect
      managed-by: vm-operator
  serviceName: vmselect-victoria-metrics-k8s-stack
  template:
    metadata:
      labels:
        app.kubernetes.io/component: monitoring
        app.kubernetes.io/instance: victoria-metrics-k8s-stack
        app.kubernetes.io/name: vmselect
        managed-by: vm-operator
    spec:
      containers:
      - args:
        - -cacheDataPath=/select-cache
        - -dedup.minScrapeInterval=1ms
        - -httpListenAddr=:8481
        - -selectNode=vmselect-victoria-metrics-k8s-stack-0.vmselect-victoria-metrics-k8s-stack.monitoring-ha:8481,vmselect-victoria-metrics-k8s-stack-1.vmselect-victoria-metrics-k8s-stack.monitoring-ha:8481
        - -storageNode=vmstorage-victoria-metrics-k8s-stack-0.vmstorage-victoria-metrics-k8s-stack.monitoring-ha:8401,vmstorage-victoria-metrics-k8s-stack-1.vmstorage-victoria-metrics-k8s-stack.monitoring-ha:8401
        - -vmalert.proxyURL=http://vmalert-victoria-metrics-k8s-stack.monitoring-ha.svc:8080
        image: stormv3.azurecr.io/victoriametrics/vmselect:v1.94.0-cluster
        imagePullPolicy: IfNotPresent
        livenessProbe:
          failureThreshold: 10
          httpGet:
            path: /health
            port: 8481
            scheme: HTTP
          periodSeconds: 5
          successThreshold: 1
          timeoutSeconds: 5
        name: vmselect
        ports:
        - containerPort: 8481
          name: http
          protocol: TCP
        readinessProbe:
          failureThreshold: 10
          httpGet:
            path: /health
            port: 8481
            scheme: HTTP
          periodSeconds: 5
          successThreshold: 1
          timeoutSeconds: 5
        resources:
          limits:
            cpu: 500m
            memory: 1000Mi
          requests:
            cpu: 100m
            memory: 500Mi
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: FallbackToLogsOnError
        volumeMounts:
        - mountPath: /select-cache
          name: vmselect-cachedir
      dnsPolicy: ClusterFirst
      imagePullSecrets:
      - name: ref-arch-default
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      serviceAccount: vmcluster-victoria-metrics-k8s-stack
      serviceAccountName: vmcluster-victoria-metrics-k8s-stack
      terminationGracePeriodSeconds: 30
```
