### ISSUE TITLE
Support environment variables in streaming aggregation configs

### ISSUE THREAD

**Issue by ehuzii** [VictoriaMetrics/VictoriaMetrics#5669]
### Describe the solution you'd like

judging by the documentation, you implemented convenient use of variables in config files. and I noticed that variables do not work in streaming aggregation configurations. 
For example my config: 
```
- match:
  - '{__name__=~".+_workers_count"}'
  interval: 30s
  outputs:
  - sum_samples
  output_relabel_configs:
  - target_label: vmagent
    replacement: '%{HOSTNAME}'
```
I get the following metric: 
`test_metrics_dev_all_jobs_workers_count:30s_sum_samples{project="Test",vmagent="%{HOSTNAME}"}`
