### ISSUE TITLE
vmalert: support using different tenants for reading and writing rule results

### ISSUE THREAD

**Issue by zekker6** [VictoriaMetrics/VictoriaMetrics#5779]
### Is your feature request related to a problem? Please describe

There is a use case where it is required to read data from different tenants and write into another tenant.
This allows to aggregate info from multiple tenants into one to provide a "global view" over those tenants.

### Describe the solution you'd like

It would be great to support supplying different tenant IDs for reading and writing the results. For example:
```
groups:
- name: example # read and write with 123
  tenant: "123"
  rules:
    # Rules for accountID=123

- name: example2 # Read from 456:789, but write into tenant 1000
  tenant: "456:789"
  tenant_write: "1000"
  rules:
    # Rules for accountID=456, projectID=789
```

### Describe alternatives you've considered

There is no alternative as of right now because enabling `-clusterMode` forces URLs to use multi-tenancy for both reads and writes.

**Comment by zekker6** [comment]
Related: https://github.com/VictoriaMetrics/VictoriaMetrics/issues/5693

**Comment by hagen1778** [comment]
> - name: example2 # Read from 456:789, but write into tenant 1000
  tenant: "456:789"
  tenant_write: "1000"

I think we can try extending the `tenant` field to make it easier to read:
```
groups:
- name: example # read and write with 123
  tenant: "123" // requests to datasource.url, remoteRead.url and remoteWrite.url

- name: example2 # Read from 456:789, but write into tenant 1000
  tenant: 
      read: "456:789" // requests to datasource.url
      write:  "1000"     // requests to remoteWrite.url and remoteRead.url
```

With this config, it will be possible to configure an alerting rule that reads from one tenant and writes to another tenant. 
However, please remember that:
> The results of alerting and recording rules contain vm_account_id and vm_project_id labels if -clusterMode is enabled. These labels can be used during [templating](https://docs.victoriametrics.com/vmalert/#templating), and help to identify to which account or project the triggered alert or produced recording belongs.


-------------------

If vmalert needs to read from many sources but forward results to only one source - try the following workaround:
1. Setup vmalert in `clusterMode` and configure `tenant` field accordingly, so vmalert could read data from many tenants
2. Setup vmauth which would accept all **writes** from vmalert
3. Configure vmauth to strip information about `tenant` from accepted requests and forward to one specific tenant.

With this setup vmalert will try to read from tenant A and push results to tenant A, but vmauth will intercept writes and redirect them to tenant C.
