### ISSUE TITLE
How to output logs from ilotail to Victorialogs

### ISSUE THREAD

**Issue by ktpktr0** [VictoriaMetrics/VictoriaMetrics#5823]
### Describe the bug

I tried using ilogtail to collect logs and output them to Victorialogs, using both Elasticsearch and Loki formats, but neither of them worked

### To Reproduce

ilogtail config:
```
enable: true
inputs:
  - Type: input_file
    FilePaths:
      - /var/log/*/*.log
flushers:
  - Type: flusher_elasticsearch
    Addresses:
      - "http://victorialogs:9428/insert/elasticsearch/"
    #Index: default
    #Authentication:
    #  PlainText:
    #    Username: user
    #    Password: 123456
    HTTPConfig:
        MaxIdleConnsPerHost: 10
        ResponseHeaderTimeout: Second
```

### Version

docker.io/victoriametrics/victoria-logs:v0.4.2-victorialogs

### Logs

No specific log output
