### ISSUE TITLE
Scraping: allow hiding parameters

### ISSUE THREAD

**Issue by lapo-luchini** [VictoriaMetrics/VictoriaMetrics#5825]
### Is your feature request related to a problem? Please describe

When adding query args parameters in a scrape, they show up in `/targets` web UI:
![image](https://github.com/VictoriaMetrics/VictoriaMetrics/assets/420454/c55e0dcb-d788-4bd1-98d9-1f5af67b785f)

### Describe the solution you'd like

I'd like to be able to specify in the config with parameters are to be hidden.
e.g.:

```yaml
  - job_name: 'vmauth'
    scheme: https
    params:
      authKey: ['secretPassword']
    params.hide: ['authKey'] # just an example
    static_configs:
    - targets:
      - 127.0.0.1:8427
```

### Describe alternatives you've considered

Another solution could be to enable `vmauth -metricsAuthKey` to be sent as a header instead of a query arg.
