### ISSUE TITLE
vmagent issue: skipping duplicate scrape target with identical labels

### ISSUE THREAD

**Issue by genseb13011** [VictoriaMetrics/VictoriaMetrics#5826]
### Is your question request related to a specific component?

vmagent

### Describe the question in detail

Hi,

I'm facing scraping issue that I can't deal with.

My vmagent floods with below kind of error messages

```
vmagent 2024-02-19T12:21:56.407Z    error    VictoriaMetrics/lib/promscrape/scraper.go:369    skipping duplicate scrape target with identical labels; endpoint=http://10.0.84.30:8482/metrics, labels={container="vmstorage",instance="10.0.84.30:8482",job="observability/global-pod-scraping",namespace="observability",pod="vmstorage-victoriametrics-cluster-0"}; make sure service discovery and relabeling is set up properly; see also https://docs.victoriametrics.com/vmagent.html#troubleshooting; 
original labels for target1: 
{__address__="10.0.84.30:8482",__meta_kubernetes_namespace="observability",__meta_kubernetes_pod_annotation_cni_projectcalico_org_containerID="ba9bfb811bfd067e622201682406e8954d728b2ff8c0a25d0bd545fcddad03cf",__meta_kubernetes_pod_annotation_cni_projectcalico_org_podIP="10.0.84.30/32",__meta_kubernetes_pod_annotation_cni_projectcalico_org_podIPs="10.0.84.30/32",__meta_kubernetes_pod_annotation_prometheus_io_path="/metrics",__meta_kubernetes_pod_annotation_prometheus_io_port="8482",__meta_kubern.._by="true",__meta_kubernetes_pod_labelpresent_statefulset_kubernetes_io_pod_name="true",__meta_kubernetes_pod_name="vmstorage-victoriametrics-cluster-0",__meta_kubernetes_pod_node_name="k8s-master-2.progect.ovh",__meta_kubernetes_pod_phase="Running",__meta_kubernetes_pod_ready="true",__meta_kubernetes_pod_uid="c249d991-6445-42db-9969-6df5c11b6c63",__metrics_path__="/metrics",__scheme__="http",__scrape_interval__="30s",__scrape_timeout__="10s",job="podScrape/observability/global-pod-scraping/0"}
; original labels for target2: 
{__address__="10.0.84.30:8401",__meta_kubernetes_namespace="observability",__meta_kubernetes_pod_annotation_cni_projectcalico_org_containerID="ba9bfb811bfd067e622201682406e8954d728b2ff8c0a25d0bd545fcddad03cf",__meta_kubernetes_pod_annotation_cni_projectcalico_org_podIP="10.0.84.30/32",__meta_kubernetes_pod_annotation_cni_projectcalico_org_podIPs="10.0.84.30/32",__meta_kubernetes_pod_annotation_prometheus_io_path="/metrics",__meta_kubernetes_pod_annotation_prometheus_io_port="8482",__meta_kubern.._by="true",__meta_kubernetes_pod_labelpresent_statefulset_kubernetes_io_pod_name="true",__meta_kubernetes_pod_name="vmstorage-victoriametrics-cluster-0",__meta_kubernetes_pod_node_name="k8s-master-2.progect.ovh",__meta_kubernetes_pod_phase="Running",__meta_kubernetes_pod_ready="true",__meta_kubernetes_pod_uid="c249d991-6445-42db-9969-6df5c11b6c63",__metrics_path__="/metrics",__scheme__="http",__scrape_interval__="30s",__scrape_timeout__="10s",job="podScrape/observability/global-pod-scraping/0"}
```
The only thing that seems to change between target 1 and 2 is the port in `__address__`

The weird thing is that target one is well using the required port (8482) but not the target 2 (8401)

Here my vmagent declaration

```
apiVersion: operator.victoriametrics.com/v1beta1
kind: VMAgent
metadata:
  name: vmagent
spec:
  selectAllByDefault: false
  podScrapeSelector:
    matchLabels:
      name: global-pod-scraping
  vmAgentExternalLabelName: vmagent_ha
  remoteWrite:
    - url: "http://vminsert-victoriametrics-cluster.observability:8480/insert/0/prometheus/api/v1/write"
  # Replication:
  scrapeInterval: 30s
  replicaCount: 2
  # Stateful configuration
  statefulMode: true
  statefulStorage:
    volumeClaimTemplate:
      spec:
        storageClassName: "longhorn-retain"
        resources:
            requests:
              storage: 1Gi
```

Here my VMPodScrape configuration

```
apiVersion: operator.victoriametrics.com/v1beta1
kind: VMPodScrape
metadata:
  name: global-pod-scraping
  labels:
    name: global-pod-scraping
spec:
  podMetricsEndpoints:
    - scheme: http
      relabelConfigs:
        - sourceLabels:
            [__meta_kubernetes_pod_annotation_prometheus_io_scrape]
          action: keep
          regex: "true"
        - sourceLabels:
            [__meta_kubernetes_pod_annotation_prometheus_io_scheme]
          action: replace
          targetLabel: __scheme__
          regex: (https?)
        - sourceLabels:
            [__meta_kubernetes_pod_annotation_prometheus_io_path]
          action: replace
          targetLabel: __metrics_path__
          regex: (.+)
        - sourceLabels:
            [
                __address__,
                __meta_kubernetes_pod_annotation_prometheus_io_port,
            ]
          action: replace
          targetLabel: __address__
          regex: ([^:]+)(?::\d+)?;(\d+)
          replacement: $1:$2
  selector: {}
  namespaceSelector:
    any: true
```

Here my VMCluster configuration

```
# vmcluster.yaml
apiVersion: operator.victoriametrics.com/v1beta1
kind: VMCluster
metadata:
  name: victoriametrics-cluster
spec:
  retentionPeriod: "7"
  replicationFactor: 2
  vmstorage:
    replicaCount: 3
    extraArgs:
      dedup.minScrapeInterval: 30s
      storage.minFreeDiskSpaceBytes: 2GiB
    storageDataPath: "/vm-data"
    storage:
      volumeClaimTemplate:
        spec:
          storageClassName: "longhorn-retain"
          resources:
            requests:
              storage: "10Gi"
    podMetadata:
      annotations:
        prometheus.io/port: "8482"
        prometheus.io/scheme: http
        prometheus.io/scrape: "true"
        prometheus.io/path: "/metrics"
  vmselect:
    replicaCount: 2
    extraArgs:
      dedup.minScrapeInterval: 30s
    cacheMountPath: "/select-cache"
    storage:
      volumeClaimTemplate:
        spec:
          storageClassName: "longhorn-retain"
          resources:
            requests:
              storage: "1Gi"
    podMetadata:
      annotations:
        prometheus.io/port: "8481"
        prometheus.io/scheme: http
        prometheus.io/scrape: "true"
        prometheus.io/path: "/metrics"
  vminsert:
    replicaCount: 2
    podMetadata:
      annotations:
        prometheus.io/port: "8480"
        prometheus.io/scheme: http
        prometheus.io/scrape: "true"
        prometheus.io/path: "/metrics"
```

Thanks for your help and advices.

Seb

### Troubleshooting docs

- [ ] General - https://docs.victoriametrics.com/Troubleshooting.html
- [X] vmagent - https://docs.victoriametrics.com/vmagent.html#troubleshooting
- [ ] vmalert - https://docs.victoriametrics.com/vmalert.html#troubleshooting

**Comment by hagen1778** [comment]
Hey @genseb13011! Have you looked at https://docs.victoriametrics.com/vmagent/#troubleshooting mentioned in the error message?
> if you see skipping duplicate scrape target with identical labels errors when scraping Kubernetes pods, then it is likely these pods listen to multiple ports or they use an init container. These errors can either be fixed or suppressed with the -promscrape.suppressDuplicateScrapeTargetErrors command-line flag. 

The following relabeling rule may be added to relabel_configs section in order to filter out pods with unneeded ports:
```yaml
- action: keep_if_equal
  source_labels: [__meta_kubernetes_pod_annotation_prometheus_io_port, __meta_kubernetes_pod_container_port_number]
```

The following relabeling rule may be added to relabel_configs section in order to filter out init container pods:
```yaml
- action: drop
  source_labels: [__meta_kubernetes_pod_container_init]
  regex: true
```
