### ISSUE TITLE
VMAgent/VMAuth should be able to use ENV variables in config files

### ISSUE THREAD

**Issue by to4kin** [VictoriaMetrics/VictoriaMetrics#583]
**Is your feature request related to a problem? Please describe.**
VMAgent and VMAuth have a *.yaml config files for configuration. Via these files, you can provide security information like username/password for authentication and so on. We store these files in git, but it's not a good idea to store sensitive data in git, so we need another solution on how to provide secure data to the vmagent/vmauth

**Describe the solution you'd like**
A better way is to add the ability to use environment variables in yaml config files, for example:
VMAuth:
```
config.yml: |-
    users:
      - username: "${VM_SELECT_USERNAME}"
        password: "${VM_SELECT_PASSWORD}"
        url_prefix: "http://vmselect.{{ $.Release.Namespace }}:8481/select/0/prometheus"
```

VMAgent:
```
scrape.yml: |-
    scrape_configs:
      - job_name: 'eureka-discovery'
        metrics_path: '/actuator/prometheus'

        consul_sd_configs:
        - server: {{ .Values.vmagent.consul_sd.server }}
          tag_separator: ','
          allow_stale: true
          username: ${EUREKA_USERNAME}
          password: ${EUREKA_PASSWORD}

        relabel_configs:
        ...
```

**Describe alternatives you've considered**
At this moment we have a workaround, we use sed before start the container to update the data inside config files:
```
sed -i.bak 's@${VM_SELECT_USERNAME}@'"${VM_SELECT_USERNAME}"'@' /etc/config/config.yml
```

**Comment by valyala** [comment]
Note that environment vars may clash with [regexp capturing groups](https://golang.org/pkg/regexp/#Regexp.Expand) in [relabeling rules](https://prometheus.io/docs/prometheus/latest/configuration/configuration/#relabel_config). For example, `replacement` value will be substituted with an empty string if ENV vars like  `${ENV_VAR_NAME}` are substituted with their values:
```yml
- source_labels: [foo]
  regex: "foo(.*)"
  replacement: "${1}"
```

Probably we need implementing additional syntax
