### ISSUE TITLE
vmauth URLMap add query param

### ISSUE THREAD

**Issue by laurentL** [VictoriaMetrics/VictoriaMetrics#5878]
### Is your feature request related to a problem? Please describe

when migrating from influx to victoriametrics, data is ingested with a query parameter 'db' representing the influx database.
It is not possible to have DB-based routing.

### Describe the solution you'd like

The proposal is to add a `src_query_args` option to the `url_map` object to enable this.
For example:

```yaml
users:
- username: usr_name
  password: password
  url_map:
  - src_paths:
    - "/write"
    src_query_args:
    - "db=mydb"
    url_prefix: "http://localhost:8428"
```

**Comment by valyala** [comment]
The commit 61d1af805008276739960df59887b6c3b540d9eb adds support for [query-args](https://en.wikipedia.org/wiki/Query_string)-based routing of incoming requests via `src_query_args` option at `url_map` in [vmauth](https://docs.victoriametrics.com/vmauth/) - see [these docs](https://docs.victoriametrics.com/vmauth/#generic-http-proxy-for-different-backends) for more details. This commit will be included in the next release. In the mean time it is possible to verify this functionality by building `vmauth` from the given commit according to [these docs](https://docs.victoriametrics.com/vmauth/#how-to-build-from-sources).

**Comment by valyala** [comment]
FYI, the commit fa23fb6c373c91acbbf568f1924cb054481405f6 simplifies configuring the `src_query_args`. Instead of:

```yaml
src_query_args:
- name: db
  value: foo
```

It is simplified to:

```yaml
src_query_args:
- "db=foo"
```
