### ISSUE TITLE
[vmagent] Possible Memory Leak

### ISSUE THREAD

**Issue by jiekun** [VictoriaMetrics/VictoriaMetrics#5884]
### Describe the bug

After deploying `vmagent` for a week, we observed that the memory usage of this component is kept increasing (slowly).

![image](https://github.com/VictoriaMetrics/VictoriaMetrics/assets/30280396/4dcbe915-3c09-4b66-aa7d-8b4370b98ecc)

According to the advice of community member, we captured pprof for the latest status:
![image](https://github.com/VictoriaMetrics/VictoriaMetrics/assets/30280396/ee138af8-aa0e-41be-891e-ae7fe9b0bb35)

Last week, we also captured pprof of the `vmagent` who run for just a few hours:
![image](https://github.com/VictoriaMetrics/VictoriaMetrics/assets/30280396/c2e820a8-ec11-47ee-a438-adc4b0a3f1ee)

Also, the **original** pprof files are provided as follow:
https://drive.google.com/file/d/1UfGxKsyN8IehGIWTnnApx7spwJGsUnRo/view?usp=sharing
https://drive.google.com/file/d/1gDwSFOdw2a0WTemxICc2prG_6hvPD5iw/view?usp=sharing

According to the pprof result, the memory usage of `getScrapeWorkObjectsForLabels` function is increasing. However, the app/deployment total count on this cluster has not increased during the last week. And the memory increment is very slow and stable, which is more like a memory leak, instead of a workload increment.

### To Reproduce

Running `vmagent` for a week.

### Version

The version of `vmagent` is `v1.98.0`.

We have our setup yaml file:
```yaml
apiVersion: operator.victoriametrics.com/v1beta1
kind: VMAgent
metadata:
  name: ***********
spec:
  image:
    tag: "v1.98.0"
    pullPolicy: IfNotPresent
  resources:
    requests:
      memory: 4Gi
      cpu: 2
    limits:
      memory: 8Gi
      cpu: 4
  selectAllByDefault: true
  replicaCount: 1
  scrapeInterval: 30s
  scrapeTimeout: 25s
  shardCount: 1
  externalLabels:
    cluster: ***********
  remoteWrite:
    - url: "http://****************/insert/0/prometheus/api/v1/write"
  extraArgs:
    promscrape.maxDroppedTargets: "9000000"
    promscrape.maxScrapeSize: "100MB"
    memory.allowedBytes: "1024MB"
```

### Additional information

Please advice if other info could help. I will try to get it asap.
