### ISSUE TITLE
The benefits of replacing VMAgent with node_exporter as a drop-in replacement

### ISSUE THREAD

**Issue by Angel0r** [VictoriaMetrics/VictoriaMetrics#5887]
### Is your question request related to a specific component?

vmagent

### Describe the question in detail

Hey,

Is there any benefit of replacing node_exporter with only vmagent?
Α benefit could be that we use a unified system meaning that we have fewer components that lead to less maintenance.
But do we gain any other benefit than that? 

/Angelos

### Troubleshooting docs

- [X] General - https://docs.victoriametrics.com/Troubleshooting.html
- [X] vmagent - https://docs.victoriametrics.com/vmagent.html#troubleshooting
- [X] vmalert - https://docs.victoriametrics.com/vmalert.html#troubleshooting

**Comment by Haleygo** [comment]
Hello!
I don't quite understand the meaning of "replacing node_exporter with only vmagent", could you elaborate more?
As vmagent scrapes metrics from different targets like node_exporter, but can't collect metrics from hosts directly.

**Comment by Angel0r** [comment]
Hey @Haleygo,
Thanks for the fast response!
Oh, you are right! This is a misunderstanding from me then since the documentation says a drop-in replacement for prometheus not for node_exporter. However, this misunderstanding made me test things in my `victoria-metrics-k8s-stack` where I disabled the `prometheus-node-exporter` and still scraping metrics.
So how did this work? What am I missing?

/Angelos

**Comment by Angel0r** [comment]
The VMServicescrape is enabled though. Does this do the scraping work instead of node_exporter?

**Comment by Haleygo** [comment]
>where I disabled the prometheus-node-exporter and still scraping metrics

Are those metrics coming from node-exporter or other jobs? You can check it on http://vmagent:8429/targets page or quering `up{job="node-exporter"}` in [vmui](https://docs.victoriametrics.com/single-server-victoriametrics/#vmui).
If there are metrics from node-exporter, did you installed the service before with other chart? How did you disable prometheus-node-exporter in `victoria-metrics-k8s-stack`, could you share the values you use?

**Comment by Angel0r** [comment]
I use Grafana for visualising the metrics. Since my lab cluster is down now I will try to deploy fast again and let you know about the `vmagent:8429/targets`.

No, I have not installed node exporter at all in the k8s cluster.
I disabled it by setting prometheus-node-exporter to false:
```yaml
  prometheus-node-exporter:
      enabled: false
```
My values:
```yaml
  values:
    storageClassName: ontap

    # -- victoria-metrics-operator dependency chart configuration.
    # -- For possible values refer to https://github.com/VictoriaMetrics/helm-charts/tree/master/charts/victoria-metrics-operator#parameters
    # -- also checkout here possible ENV variables to configure operator behaviour https://docs.victoriametrics.com/operator/vars.html
    victoria-metrics-operator:
      enabled: true
      operator:
        # -- By default, operator converts prometheus-operator objects.
        disable_prometheus_converter: true

    serviceAccount:
      # -- Specifies whether a service account should be created
      create: true

    ## -- Create default rules for monitoring the cluster
    defaultRules:
      create: true
      rules:
        # Enabled Rules
        etcd: true
        general: true
        k8s: true
        kubeApiserver: true
        kubeApiserverAvailability: true
        kubeApiserverBurnrate: true
        kubeApiserverHistogram: true
        kubeApiserverSlos: true
        kubelet: true
        kubePrometheusGeneral: true
        kubePrometheusNodeRecording: true
        kubernetesApps: true
        kubernetesResources: true
        kubernetesStorage: true
        kubernetesSystem: true
        kubeScheduler: true
        kubeStateMetrics: true
        network: true
        node: true
        vmagent: true
        vmcluster: true
        vmhealth: true
        alertmanager: true
        # Disabled Rules
        #! Disable vmsingle since we are using the cluster version
        vmsingle: false

      # -- Runbook url prefix for default rules
      runbookUrl: https://runbooks.prometheus-operator.dev/runbooks

      # Disabled VMRules
      disabled: {}

      ## Reduce app namespace alert scope
      appNamespacesTarget: ".*"

      # -- Labels for default rules
      labels: {}
      # -- Annotations for default rules
      annotations: {}

      # -- Additional labels for PrometheusRule alerts
      additionalRuleLabels: {}

      # -- Optional HTTP URL parameters added to each rule request
      params: {}

    ## -- Create default dashboards
    defaultDashboardsEnabled: true

    ## -- Create experimental dashboards
    experimentalDashboardsEnabled: true

    ## -- Create dashboards as CRDs (reuqires grafana-operator to be installed)
    grafanaOperatorDashboardsFormat:
      enabled: false

    # Provide custom recording or alerting rules to be deployed into the cluster.
    additionalVictoriaMetricsMap:
    #    rule-name:
    #     groups:
    #     - name: my_group
    #       rules:
    #       - record: my_record
    #         expr: 100 * my_record

    externalVM:
      read:
        url: ""
        # bearerTokenSecret:
        #   name: dbaas-read-access-token
        #   key: bearerToken

    ##############
    vmcluster:
      #! Enable vmcluster
      enabled: true
      annotations: {}
      # spec for VMCluster crd
      # https://docs.victoriametrics.com/operator/api.html#vmclusterspec
      spec:
        retentionPeriod: "12" #! One year
        replicationFactor: 2
        vmstorage:
          replicaCount: 2
          storageDataPath: "/vm-data"
          storage:
            volumeClaimTemplate:
              spec:
                resources:
                  requests:
                    storage: 50Gi
          resources:
            requests:
              cpu: 1
              memory: 4Gi
            limits:
              memory: 4Gi
        vmselect:
          replicaCount: 2
          cacheMountPath: "/select-cache"
          extraArgs: {}
          storage:
            volumeClaimTemplate:
              spec:
                resources:
                  requests:
                    storage: 2Gi
          # Big amount of resources are recommended
          # https://github.com/VictoriaMetrics/VictoriaMetrics/issues/649#issuecomment-663182727
          resources:
            limits:
              memory: 1Gi
            requests:
              cpu: 1
              memory: 1Gi
        vminsert:
          replicaCount: 2
          extraArgs: {}
          resources:
            limits:
              memory: 1Gi
            requests:
              cpu: 0.5
              memory: 1Gi

    alertmanager:
      enabled: true
      annotations: {}
      # spec for VMAlertmanager crd
      # https://docs.victoriametrics.com/operator/api.html#vmalertmanagerspec
      spec:
        selectAllByDefault: true
        externalURL: ""
        routePrefix: /

      # better alert templates for slack
      # source https://gist.github.com/milesbxf/e2744fc90e9c41b47aa47925f8ff6512
      #! No need of monzotemplate
      monzoTemplate:
        enabled: false

      # extra alert templates
      templateFiles:
        {}
        # template_1.tmpl: |-
        #   {{ define "hello" -}}
        #   hello, Victoria!
        #   {{- end }}
        # template_2.tmpl: ""

    vmalert:
      annotations: {}
      enabled: true

      # Controls whether VMAlert should use VMAgent or VMInsert as a target for remotewrite
      #! Enable remoteWriteVMAgent so it gather metrics
      remoteWriteVMAgent: true
      # spec for VMAlert crd
      # https://docs.victoriametrics.com/operator/api.html#vmalertspec
      spec:
        selectAllByDefault: true
        evaluationInterval: 15s

        # External labels to add to all generated recording rules and alerts
        externalLabels: {}

      # extra vmalert annotation templates
      templateFiles:
        {}
        # template_1.tmpl: |-
        #   {{ define "hello" -}}
        #   hello, Victoria!
        #   {{- end }}
        # template_2.tmpl: ""
      ingress:
        enabled: false

    vmagent:
      enabled: true
      annotations: {}
      # https://docs.victoriametrics.com/operator/api.html#vmagentremotewritespec
      # defined spec will be added to the remoteWrite configuration of VMAgent
      additionalRemoteWrites:
        []
        #- url: http://some-remote-write/api/v1/write
      # spec for VMAgent crd
      # https://docs.victoriametrics.com/operator/api.html#vmagentspec
      spec:
        selectAllByDefault: true
        scrapeInterval: 20s
        # vmAgentExternalLabelName: cluster
        externalLabels:
          cluster: cluster-name
        extraArgs:
          promscrape.streamParse: "true"
        #! Add stream_parse so it handle large amount of metrics
        #! https://docs.victoriametrics.com/vmagent/#scrape_config-enhancements
        #! https://github.com/VictoriaMetrics/VictoriaMetrics/issues/1017#issuecomment-830575634
        scrape_configs:
          stream_parse: true
        resources:
          requests:
            memory: 1Gi   # Set the memory request
          limits:
            memory: 1Gi   # Set the memory limit
        # scrapeTimeout: 20s
      ingress:
        enabled: false

    #################################################
    ###              dependencies               #####
    #################################################
    # Grafana dependency chart configuration. For possible values refer to https://github.com/grafana/helm-charts/tree/main/charts/grafana#configuration
    grafana:
      enabled: true
      ## all values for grafana helm chart can be specified here
      sidecar:
        datasources:
          enabled: true
          initDatasources: true
          createVMReplicasDatasources: false
          # JSON options for VM datasources
          # See https://grafana.com/docs/grafana/latest/administration/provisioning/#json-data
          jsonData: {}
          #  timeInterval: "1m"
        dashboards:
          additionalDashboardLabels: {}
          additionalDashboardAnnotations: {}
          enabled: true
          multicluster: false

      ## ForceDeployDatasource Create datasource configmap even if grafana deployment has been disabled
      forceDeployDatasource: false

      ## Configure additional grafana datasources (passed through tpl)
      ## ref: http://docs.grafana.org/administration/provisioning/#datasources
      #! Add Loki datasource
      additionalDataSources:
        - name: Loki
          type: loki
          url: http://loki-gateway.logs-and-monitoring
          jsonData:
            timeout: 60
            maxLines: 1000
      # - name: prometheus-sample
      #   access: proxy
      #   basicAuth: true
      #   basicAuthPassword: pass
      #   basicAuthUser: daco
      #   editable: false
      #   jsonData:
      #       tlsSkipVerify: true
      #   orgId: 1
      #   type: prometheus
      #   url: https://{{ printf "%s-prometheus.svc" .Release.Name }}:9090
      #   version: 1

      dashboardProviders:
        dashboardproviders.yaml:
          apiVersion: 1
          providers:
            - name: "default"
              orgId: 1
              folder: ""
              type: file
              disableDeletion: false
              editable: true
              options:
                path: /var/lib/grafana/dashboards/default

      dashboards:
        default:
          nodeexporter:
            gnetId: 1860
            revision: 22
            datasource: VictoriaMetrics

      defaultDashboardsTimezone: utc
      persistence:
        enabled: true
        type: pvc
        size: 1Gi
        storageClassName: ontap-snap

      # Enabling VictoriaMetrics Datasource in Grafana. See more details here: https://github.com/VictoriaMetrics/grafana-datasource/blob/main/README.md#victoriametrics-datasource-for-grafana
      # Note that Grafana will need internet access to install the datasource plugin.
      # Uncomment the block below, if you want to enable VictoriaMetrics Datasource in Grafana:
      #! Enable VictoriaMetrics Datasource
      plugins:
        - "https://github.com/VictoriaMetrics/grafana-datasource/releases/download/v0.5.0/victoriametrics-datasource-v0.5.0.zip;victoriametrics-datasource"
      grafana.ini:
        plugins:
          # Why VictoriaMetrics datasource is unsigned: https://github.com/VictoriaMetrics/grafana-datasource/blob/main/README.md#why-victoriametrics-datasource-is-unsigned
          allow_loading_unsigned_plugins: victoriametrics-datasource

      # Change datasource type in dashboards from Prometheus to VictoriaMetrics.
      # you can use `victoriametrics-datasource` instead of `prometheus` if enabled VictoriaMetrics Datasource above
      # defaultDatasourceType: "prometheus"

      ingress:
        enabled: false

      vmServiceScrape:
        # wheter we should create a service scrape resource for grafana
        enabled: true

    # prometheus-node-exporter dependency chart configuration. For possible values refer to https://github.com/prometheus-community/helm-charts/blob/main/charts/prometheus-node-exporter/values.yaml

    prometheus-node-exporter:
      enabled: false

    # kube-state-metrics dependency chart configuration. For possible values refer to https://github.com/prometheus-community/helm-charts/blob/main/charts/kube-state-metrics/values.yaml
    kube-state-metrics:
      enabled: true

    #################################################
    ###              Service Monitors           #####
    #################################################
    ## Component scraping the kubelets
    kubelet:
      enabled: true

    # -- Component scraping the kube api server
    kubeApiServer:
      enabled: true

    # -- Component scraping the kube controller manager
    kubeControllerManager:
      enabled: true

    # -Component scraping kubeDns. Use either this or coreDns
    kubeDns:
      enabled: false

    ## Component scraping etcd
    ##

    kubeEtcd:
      enabled: false

    ## Component scraping kube scheduler
    ##
    kubeScheduler:
      enabled: true

    ## Component scraping kube proxy
    ##
    kubeProxy:
      enabled: true
```
