### ISSUE TITLE
Support sending logs to syslog directly

### ISSUE THREAD

**Issue by chalapat** [VictoriaMetrics/VictoriaMetrics#5903]
### Is your feature request related to a problem? Please describe

Currently VM component logs would be written to console in k8s environment. Underlying caas layer will read these container logs and send it to logging backend.  Privileges are required for user to configure these logs to go different backend. If caas layer is brought by product then these would run with root user. 
In our company we have a requirement where in a component can directly send to remote syslog server and from their logs can be forwarded to different logging backends.

This request is to support sending logs to syslog directly.

### Describe the solution you'd like

By default logging would be to console.  User will enable the feature by giving other parameters (syslog host, facility, tls parameters etc..)

### Describe alternatives you've considered

Redirect logs to a file and use fluentd/fluent bit to forward the logs to syslog. This adds extra sidecar to solution

**Comment by f41gh7** [comment]
I don't like that idea.  It's better to delegate logs collections to the OS components and use centralized logs pipeline. For example, it could be achieved with journald or rsyslog. k8s has a lot of solutions for it as well.

 For the same reason, VictoriaMetrics doesn't support writting logs into file destination. It over-complicates log management system inside VictoriaMetrics components.  And it doesn't solve any real problems.

Beside that, we already had a 3 different PRs with attempts to implement it. All have it's own issues and comprises. 

> In our company we have a requirement where in a component can directly send to remote syslog server and from their logs can be forwarded to different logging backends.

 It's possible to overcome this requirement with side-car container, that shares emptyDir volume. For example:

```yaml
apiVersion: v1
kind: Pod
metadata:
  name: app-with-syslog
spec:
  volumes:
    - name: logs
      emptyDir: {}
    - name: fluentbit-config
      configMap:
        name: fluentbit-config
  containers:
    - name: app
      image: victoriametrics/victoria-metrics:v1.143.0
      command:
        - /bin/sh
        - -c
        - |
          /victoria-metrics 2>&1 | tee -a /logs/app.log
      volumeMounts:
        - name: logs
          mountPath: /logs
    - name: syslog-sidecar
      image: fluent/fluent-bit
      volumeMounts:
        - name: logs
          mountPath: /logs
        - name: fluentbit-config
          mountPath: /fluent-bit/etc/
```
