### ISSUE TITLE
vmsingle is deployed eventhough is set to false

### ISSUE THREAD

**Issue by Angel0r** [VictoriaMetrics/VictoriaMetrics#5915]
### Describe the bug

I am using victoria-metrics-k8s-stack. I have disabled vmsingle and enabled the vmcluster. However, even though the vmsingle is disabled, it is still deployed by Helm.

```
kubectl describe helmrelease victoria-metrics-k8s-stack
```
```yaml
Name:         victoria-metrics-k8s-stack
Namespace:    logs-and-monitoring
Labels:       kustomize.toolkit.fluxcd.io/name=monitoring
              kustomize.toolkit.fluxcd.io/namespace=flux-system
Annotations:  <none>
API Version:  helm.toolkit.fluxcd.io/v2beta2
Kind:         HelmRelease
Metadata:
  Creation Timestamp:  2024-03-04T09:00:59Z
  Finalizers:
    finalizers.fluxcd.io
  Generation:        1
  Resource Version:  6277544
  UID:               491a94d6-1d02-4c93-b455-4b98b84fa8fc
Spec:
  Chart:
    Spec:
      Chart:               victoria-metrics-k8s-stack
      Reconcile Strategy:  ChartVersion
      Source Ref:
        Kind:   HelmRepository
        Name:   victoria-metrics-k8s-stack
      Version:  0.19.2
  Interval:     24h
  Upgrade:
    Crds:  CreateReplace
  Values:
    Additional Victoria Metrics Map:  <nil>
    Alertmanager:
      Annotations:
      Enabled:  true
      Monzo Template:
        Enabled:  false
      Spec:
        External URL:           
        Route Prefix:           /
        Select All By Default:  true
      Template Files:
    Default Dashboards Enabled:  true
    Default Rules:
      Additional Rule Labels:
      Annotations:
      App Namespaces Target:  .*
      Create:                 true
      Disabled:
      Labels:
      Params:
      Rules:
        Alertmanager:                    true
        Etcd:                            true
        General:                         true
        k8s:                             true
        Kube Apiserver:                  true
        Kube Apiserver Availability:     true
        Kube Apiserver Burnrate:         true
        Kube Apiserver Histogram:        true
        Kube Apiserver Slos:             true
        Kube Prometheus General:         true
        Kube Prometheus Node Recording:  true
        Kube Scheduler:                  true
        Kube State Metrics:              true
        Kubelet:                         true
        Kubernetes Apps:                 true
        Kubernetes Resources:            true
        Kubernetes Storage:              true
        Kubernetes System:               true
        Network:                         true
        Node:                            true
        Vmagent:                         true
        Vmcluster:                       true
        Vmhealth:                        true
        Vmsingle:                        false
      Runbook URL:                       https://runbooks.prometheus-operator.dev/runbooks
    Experimental Dashboards Enabled:     true
    External VM:
      Read:
        URL:  
    Grafana:
      Additional Data Sources:
    .
    .
    .
    Vmcluster:
      Annotations:
      Enabled:  true
      Spec:
        Replication Factor:  2
        Retention Period:    12
        Vminsert:
          Extra Args:
          Replica Count:  2
          Resources:
            Limits:
              Memory:  1Gi
            Requests:
              Cpu:     0.5
              Memory:  1Gi
        Vmselect:
          Cache Mount Path:  /select-cache
          Extra Args:
          Replica Count:  2
          Resources:
            Limits:
              Memory:  1Gi
            Requests:
              Cpu:     1
              Memory:  1Gi
          Storage:
            Volume Claim Template:
              Spec:
                Resources:
                  Requests:
                    Storage:  2Gi
        Vmstorage:
          Replica Count:  2
          Resources:
            Limits:
              Memory:  4Gi
            Requests:
              Cpu:     1
              Memory:  4Gi
          Storage:
            Volume Claim Template:
              Spec:
                Resources:
                  Requests:
                    Storage:  50Gi
          Storage Data Path:  /vm-data
    Vmsingle:
      Enable:  false
    .
    .
    .
```
```shell
kubectl get pods
```
```shell
victoria-metrics-k8s-stack-grafana-74d68d8487-f9dwt               2/2     Running   0          142m
victoria-metrics-k8s-stack-kube-state-metrics-84cb75b868-qrzwb    1/1     Running   0          142m
victoria-metrics-k8s-stack-victoria-metrics-operator-7b994x2kzz   1/1     Running   0          142m
vmagent-victoria-metrics-k8s-stack-6877488566-h764d               2/2     Running   0          142m
vmalert-victoria-metrics-k8s-stack-dc84d48d6-qscb4                2/2     Running   0          142m
vmalertmanager-victoria-metrics-k8s-stack-0                       2/2     Running   0          142m
vminsert-victoria-metrics-k8s-stack-56444c558f-f22x8              1/1     Running   0          142m
vminsert-victoria-metrics-k8s-stack-56444c558f-zchpp              1/1     Running   0          142m
vmselect-victoria-metrics-k8s-stack-0                             1/1     Running   0          142m
vmselect-victoria-metrics-k8s-stack-1                             1/1     Running   0          142m
vmsingle-victoria-metrics-k8s-stack-7959b8c4d9-fhktg              1/1     Running   0          142m
vmstorage-victoria-metrics-k8s-stack-0                            1/1     Running   0          142m
vmstorage-victoria-metrics-k8s-stack-1                            1/1     Running   0          142m
```

### To Reproduce

In [values.yaml](https://github.com/VictoriaMetrics/helm-charts/blob/master/charts/victoria-metrics-k8s-stack/values.yaml) Enable vmcluster
```yaml
vmcluster:
  enabled: true
```
and disable vmsingle:
```yaml
vmsingle:
  annotations: {}
  enabled: false
```
The `vmcluster` will be created along with the `vmsingle`.

### Version

Chart version(victoria-metrics-k8s-stack): 0.19.3

Application version(VictoriMetrics): v1.98.0
