### ISSUE TITLE
vmagent: custom host header no longer set when scraping

### ISSUE THREAD

**Issue by fholzer** [VictoriaMetrics/VictoriaMetrics#5969]
### Describe the bug

Until v1.97.0 it was possible to override the host header when scraping by specifying below in the job definition.
```
  - job_name: 'test'
    headers:
    - "host: host_test"
    static_configs:
      - targets: ['10.0.0.1:8082']
```

I was able to pinpoint the commit that caused this to break to f97355d9fb16877c23f8a84188fb4940d8d5637e using git bisect.

### To Reproduce

Specify a host header like shown above on vmagent version v1.96.0 and see that it is sent to the target. Do the same on v1.97.0 and see that it using the host part of the target instead of the hots header specified.

### Version

vmagent-20240313-220227-tags-v1.97.0-0-gfcc8b14f8

### Logs

not relevant
