### ISSUE TITLE
standard dashboard work incompletly

### ISSUE THREAD

**Issue by didlawowo** [VictoriaMetrics/VictoriaMetrics#5999]
### Describe the bug

i'm using helm with vm K8s stack chart
grafana come with dashboard but some are not working correctly

<img width="1847" alt="image" src="https://github.com/VictoriaMetrics/VictoriaMetrics/assets/12622760/97356f95-2951-4fa1-b3e3-c5070f46c016">

<img width="1847" alt="image" src="https://github.com/VictoriaMetrics/VictoriaMetrics/assets/12622760/6ee73f99-da58-457d-9637-5219a041fed2">

### To Reproduce

just install stack k8s

### Version

latest

**Comment by dmitryk-dk** [comment]
Hi @didlawowo ! What of the dashboard are you using? 
VictoriaMetrics has its dashboards, and you can find them [here](https://grafana.com/orgs/victoriametrics/dashboards).

**Comment by dmitryk-dk** [comment]
If you want to use this dashboard you should check the metrics which are used in that dashboard and probably correct them

**Comment by didlawowo** [comment]
i'm using dashboard provided by the k8s vm stack

**Comment by dmitryk-dk** [comment]
> i'm using dashboard provided by the k8s vm stack

In the k8s stack, VictoriaMetrics exposes the dashboards that I shared before. As far as I can see from the domain you are using tailscale. So I think you should check which stack you are using

**Comment by dmitryk-dk** [comment]
Hi @didlawowo ! I reproduces your bug, need to check how to fix it

**Comment by dmitryk-dk** [comment]
Hi @didlawowo ! Can you check the vmagent on your installation? It will show you where is the problem with scrapes targets. If you fix it you should see all information into your dashboards.
<img width="2525" alt="Screenshot 2024-03-25 at 12 47 10" src="https://github.com/VictoriaMetrics/VictoriaMetrics/assets/12189570/a8e046f4-35d4-4262-ae09-f71aa24c597d">

**Comment by didlawowo** [comment]
thx you but could be more specific ? i'm not sure to understand

**Comment by didlawowo** [comment]
> > i'm using dashboard provided by the k8s vm stack
> 
> In the k8s stack, VictoriaMetrics exposes the dashboards that I shared before. As far as I can see from the domain you are using tailscale. So I think you should check which stack you are using

the tailscale service its just for exposing. no impact

**Comment by dmitryk-dk** [comment]
> thx you but could be more specific ? i'm not sure to understand

Hi! We found a bug, and the dashboard should be updated. It happens because some kubernetes setup may missing `image` or `container` label
https://github.com/dotdc/grafana-dashboards-kubernetes/issues/18#issuecomment-1218059507

As a small workaround you can install you kubelet with next configuration and check what the panels will have no data.

```
kubelet:
  spec:
    # drop high cardinality label and useless metrics for cadvisor and kubelet
    metricRelabelConfigs:
      - action: labeldrop
        regex: (uid)
      - action: labeldrop
        regex: (id|name)
      - action: drop
        source_labels: [__name__]
        regex: (rest_client_request_duration_seconds_bucket|rest_client_request_duration_seconds_sum|rest_client_request_duration_seconds_count)
      - target_label: image
        replacement: placeholder
```
