### ISSUE TITLE
VMagent - scraping 

### ISSUE THREAD

**Issue by genseb13011** [VictoriaMetrics/VictoriaMetrics#6003]
### Is your question request related to a specific component?

vmagent

### Describe the question in detail

Hi,

I'm in a test environment and I'd like vmagent to be able to scrape scheme https metrics even if certificate is not validated.

Is there any way to do it? 

I've tried to add "insecure_skip_verify: true" in my VMPodScrape yaml declaration but it is not working.

Thanks for your help

Seb.

### Troubleshooting docs

- [x] General - https://docs.victoriametrics.com/Troubleshooting.html
- [x] vmagent - https://docs.victoriametrics.com/vmagent.html#troubleshooting
- [x] vmalert - https://docs.victoriametrics.com/vmalert.html#troubleshooting

**Comment by Amper** [comment]
Hey @genseb13011.
Something like that should work:

```
apiVersion: operator.victoriametrics.com/v1beta1
kind: VMServiceScrape
metadata:
  name: some-name
  namespace: some-ns
spec:
  namespaceSelector:
    matchNames:
    - some-ns
  selector:
    matchLabels:
      kubernetes.io/name: some-svc
  endpoints:
  - port: 443
    scheme: https
    tlsConfig:
      insecureSkipVerify: true
```

Doesn't it work for you?

**Comment by genseb13011** [comment]
Thanks for your answer.

I'm using VMPodScrape kind.

It has been solved by place the tlsConfig under the podMetricsEndpoints 

```
apiVersion: operator.victoriametrics.com/v1beta1
kind: VMPodScrape
metadata:
  name: global-pod-scraping
  labels:
    name: global-pod-scraping
spec:
  podMetricsEndpoints:
    - scheme: http
      relabelConfigs:
      [...]
      tlsConfig:
        insecureSkipVerify: true
  selector: {}
  namespaceSelector:
    any: true
```
Seb.
