### ISSUE TITLE
VMAlertmanager + msteams_config?

### ISSUE THREAD

**Issue by strowi** [VictoriaMetrics/VictoriaMetrics#6007]
### Is your question request related to a specific component?

Hi,

thank you guys for VictoriaMetrics! Have been following for a while.
since alertmanager has integrated msteams-webhook support, i was wondering if sth. like this will find it's way into VMAlertmanager? 

regards,
strowi

### Describe the question in detail

Not much more details to add.. prometheus-alertmanager supports this https://prometheus.io/docs/alerting/latest/configuration/#msteams_config

### Troubleshooting docs

- [X] General - https://docs.victoriametrics.com/Troubleshooting.html
- [X] vmagent - https://docs.victoriametrics.com/vmagent.html#troubleshooting
- [X] vmalert - https://docs.victoriametrics.com/vmalert.html#troubleshooting

**Comment by hagen1778** [comment]
@Amper @Haleygo could you please take a look? Is this request related to operator project?

**Comment by Haleygo** [comment]
Hello @strowi ,
operator supports `msteams_config`  since [v0.40.0](https://github.com/VictoriaMetrics/operator/releases/tag/v0.40.0), please update the vmalertmanager CRD to the latest version and let me know if that is not working.
>[vmoperator](https://github.com/VictoriaMetrics/operator/blob/v0.40.0/README.md): add CRD support for discord_configs, msteams_configs, sns_configs and webex_configs receiver types in [VMAlertmanagerConfig](https://docs.victoriametrics.com/operator/resources/vmalertmanagerconfig.html). See https://github.com/VictoriaMetrics/operator/issues/808

**Comment by strowi** [comment]
Thx for the reply @Haleygo not sure how i missed that. 
Currently using the helm-chart `vm/victoria-metrics-operator	0.29.3       	0.42.3`  i tried the following which should work according to my understanding:

```yaml
---
apiVersion: operator.victoriametrics.com/v1beta1
kind: VMAlertmanagerConfig
metadata:
  labels:
    config: test
  name: vmalertmanagerconfig-0
spec:
  route:
    receiver: "null"
    routes:
      - receiver: "msteams-test"
  receivers:
  - name: "null"
  - name: msteams-test
    msteams_configs:
      - webhook_url: 'https://test'
        send_resolved: true
---
apiVersion: operator.victoriametrics.com/v1beta1
kind: VMAlertmanager
metadata:
  name: test
spec:
  configSelector:
    matchLabels:
      config: test
```

While i can apply this, VMAlertmanager seems to fail with:

```
vmalertmanager-test-0 alertmanager
vmalertmanager-test-0 config-reloader
[vmalertmanager-test-0 config-reloader] 2024/03/26 09:22:38 Watching directory: "/etc/alertmanager/config"
[vmalertmanager-test-0 alertmanager] ts=2024-03-26T09:22:41.272Z caller=main.go:240 level=info msg="Starting Alertmanager" version="(version=0.25.0, branch=HEAD, revision=258fab7cdd551f2cf251ed0348f0ad7289aee789)"
[vmalertmanager-test-0 alertmanager] ts=2024-03-26T09:22:41.272Z caller=main.go:241 level=info build_context="(go=go1.19.4, user=root@abe866dd5717, date=20221222-14:51:36)"
[vmalertmanager-test-0 alertmanager] ts=2024-03-26T09:22:42.173Z caller=coordinator.go:113 level=info component=configuration msg="Loading configuration file" file=/etc/alertmanager/config/alertmanager.yaml
[vmalertmanager-test-0 alertmanager] ts=2024-03-26T09:22:42.173Z caller=coordinator.go:118 level=error component=configuration msg="Loading configuration file failed" file=/etc/alertmanager/config/alertmanager.yaml err="yaml: unmarshal errors:\n  line 14: field msteams_configs not found in type config.plain"
```

Am i missing something?
