### ISSUE TITLE
VMStorage does not purge indexdb per retentionPeriod setting

### ISSUE THREAD

**Issue by zhangluva** [VictoriaMetrics/VictoriaMetrics#6026]
### Describe the bug

We have multiple VMClusters when retentionPeriod set to `55d`. The expectation is that the old data gets purged on daily basis and always keeps at least 55 days data, possibly 56 days.
Few months after the clusters were up, the alerts started firing off on low disk space. When we check the disk utilization graphs, we can see that the space for data files `storage/file` does drop a little every day while the indexdb space keeps growing up.
As shown on the screenshot below, we have
vmstorage version = v1.98.0
retentionPeriod = 55d
test performed date = Mar 26, 2024
oldest indexdb file = Jan 21, 2024 - from 65 days ago
files in the folder are opened by vmstorage process.

![Screenshot 2024-03-26 at 4 01 27 PM](https://github.com/VictoriaMetrics/VictoriaMetrics/assets/91473238/a3fad80b-098d-4144-9c20-241eb329a2e4)

This particular cluster has been up for almost a year, and for testing purpose, I manually deleted indexdb files, that's why the oldest was from Jan 21. The other cluster had this to the date when the cluster was up.

When querying the metrics, the data only goes back to the defined retentionPeriod, see below. This confirms that the data got deleted.
<img width="1759" alt="Screenshot 2024-03-26 at 4 21 51 PM" src="https://github.com/VictoriaMetrics/VictoriaMetrics/assets/91473238/3a555403-f90c-46b7-bbd7-21ffc8139931">

### To Reproduce

Using the helm chart to install the cluster. The user defined values file is below.
Helm repo: https://victoriametrics.github.io/helm-charts
Chart: victoria-metrics-k8s-stack
Version: 0.19.3 
```
alertmanager:
  spec:
    configSecret: alertmanager-notification
    resources:
      requests:
        cpu: 300m
        memory: 200M
    securityContext:
      fsGroup: 65534
      runAsGroup: 65534
      runAsUser: 65534
    storage:
      volumeClaimTemplate:
        spec:
          resources:
            requests:
              storage: 1Gi
coreDns:
  enabled: true
  service:
    enabled: true
    port: 9153
    selector:
      k8s-app: kube-dns
    targetPort: metrics
  spec:
    endpoints:
    - bearerTokenFile: /var/run/secrets/kubernetes.io/serviceaccount/token
      port: http-metrics
defaultRules:
  disabled:
    DiskRunsOutOfSpace: true
    TooHighChurnRate: true
    TooManyScrapeErrors: true
  rules:
    vmhealth: false
grafana:
  enabled: false
kube-state-metrics:
  metricLabelsAllowlist:
  - namespaces=[organization]
  - deployments=[org.identifier,org.primary_key]
  resources:
    requests:
      cpu: 200m
      memory: 1Gi
kubeControllerManager:
  enabled: false
kubeEtcd:
  enabled: false
kubeScheduler:
  enabled: false
prometheus-node-exporter:
  vmServiceScrape:
    spec:
      endpoints:
      - metricRelabelConfigs:
        - action: drop
          regex: (/var/lib/kubelet/pods|/run/containerd).+
          sourceLabels:
          - mountpoint
        port: metrics
      jobLabel: jobLabel
      selector:
        matchLabels:
          app.kubernetes.io/name: prometheus-node-exporter
victoria-metrics-operator:
  operator:
    disable_prometheus_converter: false
vmagent:
  spec:
    externalLabels:
      cluster: test-cluster
    extraArgs:
      promscrape.maxScrapeSize: 400MB
      remoteWrite.label: k8s_cluster=test-cluster
    resources:
      requests:
        cpu: 3500m
        memory: 3Gi
vmalert:
  spec:
    resources:
      limits:
        cpu: 1500m
        memory: 1.5Gi
      requests:
        cpu: 800m
        memory: 1Gi
vmcluster:
  enabled: true
  spec:
    replicationFactor: 2
    retentionPeriod: 55d
    vminsert:
      extraArgs:
        disableRerouting: "true"
        dropSamplesOnOverload: "false"
        insert.maxQueueDuration: 2m
        maxConcurrentInserts: "24"
        maxLabelsPerTimeseries: "200"
      replicaCount: 8
      resources:
        requests:
          cpu: 500m
          memory: 1Gi
    vmselect:
      extraArgs:
        search.maxQueueDuration: 120s
        search.maxSeries: "600000"
      replicaCount: 6
      resources:
        requests:
          cpu: 700m
          memory: 1Gi
    vmstorage:
      extraArgs:
        insert.maxQueueDuration: 2m
        maxConcurrentInserts: "50"
        search.maxQueueDuration: 60s
      replicaCount: 6
      resources:
        requests:
          cpu: "2"
          memory: 7Gi
      storage:
        volumeClaimTemplate:
          spec:
            resources:
              requests:
                storage: 300Gi
vmsingle:
  enabled: false

```

### Version

```
/ # /vmstorage-prod -version
vmstorage-20240214-142306-tags-v1.98.0-cluster-0-g06da06dac
```

### Logs

No warning/error logs related to the storage

### Used command-line flags

```
 /vmstorage-prod -dedup.minScrapeInterval=1ms -httpListenAddr=:8482 -retentionPeriod=55d -retentionTimezoneOffset=20h -storageDataPath=/vm-data -vminsertAddr=:8400 -vmselectAddr=:8401
```
