### ISSUE TITLE
VMAlert: Doesn't Restore the State of an Alert

### ISSUE THREAD

**Issue by ricoberger** [VictoriaMetrics/VictoriaMetrics#6030]
### Describe the bug

When the VMAlert Pods are restarted it doesn't restore the state of all alerts, so that the alert is resolved and shortly after that fired again, which leads to a lot of noise in our alerting.

For some alerts we see the following log line after restarting VMAlert which indicates that the alert was restored:

```
{"ts":"2024-03-27T09:12:53.426Z","level":"info","caller":"VictoriaMetrics/app/vmalert/rule/alerting.go:650","msg":"alert \"PolicyFail\" (3934976720075504824) restored to state at 2024-03-15 13:08:00 +0000 UTC"}
```

For some of our other alerts the state isn't restored. The alert has the same id before and after the restart when checking the `/api/v1/alerts`, but the `restored` property is always `false`:

<details>
  <summary>Before the Restart</summary>

```json
  {
    "state": "firing",
    "name": "ClickHouseReplicatedPartFailedFetches",
    "value": "6850",
    "labels": {
      "alertgroup": "ClickHouseOperatorRules",
      "alertname": "ClickHouseReplicatedPartFailedFetches",
      "app": "clickhouse-logging",
      "chi": "clickhouse-logging",
      "container": "metrics-exporter",
      "endpoint": "http-metrics",
      "exported_namespace": "clickhouse-operator",
      "hostname": "chi-clickhouse-logging-replicated-11-0.logging.svc.cluster.local",
      "instance": "10.244.27.65:8888",
      "job": "clickhouse-operator-metrics",
      "kustomize_toolkit_fluxcd_io_name": "logging",
      "kustomize_toolkit_fluxcd_io_namespace": "flux-system",
      "namespace": "logging",
      "pod": "clickhouse-operator-78bbb494d9-ghz72",
      "prometheus": "monitoring/vmagent",
      "service": "clickhouse-operator-metrics",
      "severity": "error",
      "staffbase_cluster": "de1",
      "staffbase_env": "prod",
      "staffbase_region": "de1"
    },
    "annotations": {
      "message": "Increased ReplicatedPartFailedFetches on logging/chi-clickhouse-logging-replicated-11-0.logging.svc.cluster.local",
      "runbook": "`clickhouse-server` increase ReplicatedPartFailedFetches in `system.events` table. It mean server was failed to download data part from replica of a ReplicatedMergeTree table.\n\nPlease check following things:\n\n- connections between clickhouse-server pod and his replicas (see remote_server section in /etc/clickhouse-server/)\n- logs on clickhouse-server pods\n\n```shell\nkubectl exec -n logging pod/$(kubectl get pods -n logging | grep $( echo chi-clickhouse-logging-replicated-11-0.logging.svc.cluster.local | cut -d '.' -f 1) | cut -d \" \" -f 1) -- cat /var/log/clickhouse-server/*.err.log | less\n```\n\nYou can also check the errors via clickhouse-client to find infos about broken parts:\n\n```\nkubectl exec -it chi-clickhouse-logging-replicated-9-0-0 -- clickhouse-client --query='select * from system.errors FORMAT Vertical'\n```\n"
    },
    "activeAt": "2024-03-26T09:51:00Z",
    "id": "5876269309472376322",
    "rule_id": "3127900475971149131",
    "group_id": "5110194310687678757",
    "expression": "increase(chi_clickhouse_event_ReplicatedPartFailedFetches[1m]) > 0",
    "source": "http://vmalert-vmalert-d55787cdb-p2tlw:8080/vmalert/alert?group_id=5110194310687678757&alert_id=5876269309472376322",
    "restored": false,
    "stabilizing": false
  }
```

</details>

<details>
  <summary>After the Restart</summary>

```json
  {
    "state": "firing",
    "name": "ClickHouseReplicatedPartFailedFetches",
    "value": "6473",
    "labels": {
      "alertgroup": "ClickHouseOperatorRules",
      "alertname": "ClickHouseReplicatedPartFailedFetches",
      "app": "clickhouse-logging",
      "chi": "clickhouse-logging",
      "container": "metrics-exporter",
      "endpoint": "http-metrics",
      "exported_namespace": "clickhouse-operator",
      "hostname": "chi-clickhouse-logging-replicated-11-0.logging.svc.cluster.local",
      "instance": "10.244.27.65:8888",
      "job": "clickhouse-operator-metrics",
      "kustomize_toolkit_fluxcd_io_name": "logging",
      "kustomize_toolkit_fluxcd_io_namespace": "flux-system",
      "namespace": "logging",
      "pod": "clickhouse-operator-78bbb494d9-ghz72",
      "prometheus": "monitoring/vmagent",
      "service": "clickhouse-operator-metrics",
      "severity": "error",
      "staffbase_cluster": "de1",
      "staffbase_env": "prod",
      "staffbase_region": "de1"
    },
    "annotations": {
      "message": "Increased ReplicatedPartFailedFetches on logging/chi-clickhouse-logging-replicated-11-0.logging.svc.cluster.local",
      "runbook": "`clickhouse-server` increase ReplicatedPartFailedFetches in `system.events` table. It mean server was failed to download data part from replica of a ReplicatedMergeTree table.\n\nPlease check following things:\n\n- connections between clickhouse-server pod and his replicas (see remote_server section in /etc/clickhouse-server/)\n- logs on clickhouse-server pods\n\n```shell\nkubectl exec -n logging pod/$(kubectl get pods -n logging | grep $( echo chi-clickhouse-logging-replicated-11-0.logging.svc.cluster.local | cut -d '.' -f 1) | cut -d \" \" -f 1) -- cat /var/log/clickhouse-server/*.err.log | less\n```\n\nYou can also check the errors via clickhouse-client to find infos about broken parts:\n\n```\nkubectl exec -it chi-clickhouse-logging-replicated-9-0-0 -- clickhouse-client --query='select * from system.errors FORMAT Vertical'\n```\n"
    },
    "activeAt": "2024-03-27T08:48:00Z",
    "id": "5876269309472376322",
    "rule_id": "3127900475971149131",
    "group_id": "5110194310687678757",
    "expression": "increase(chi_clickhouse_event_ReplicatedPartFailedFetches[1m]) > 0",
    "source": "http://vmalert-vmalert-d55787cdb-6wzdq:8080/vmalert/alert?group_id=5110194310687678757&alert_id=5876269309472376322",
    "restored": false,
    "stabilizing": false
  }
```

</details>

The `last_over_time(ALERTS_FOR_STATE{alertname="ClickHouseReplicatedPartFailedFetches", namespace="logging"}[1h])` metric looks as follows:

<img width="1780" alt="Bildschirmfoto 2024-03-27 um 10 51 50" src="https://github.com/VictoriaMetrics/VictoriaMetrics/assets/18552168/30342a68-5067-4b8f-8311-1248b2c67546">

If there are more / other information required please let me know.

### To Reproduce

We are using the following configuration for VMAlert and VMAlertmanager. I also added one of the affected VMRules as example.

To reproduce the problem VMAlert must be restarted.

<details>
  <summary>VMAlert Configuration</summary>

```yaml
---
apiVersion: operator.victoriametrics.com/v1beta1
kind: VMAlert
metadata:
  name: vmalert
  namespace: monitoring
spec:
  image:
    repository: <REGISTRY>/sb-images-dockerhub-proxy/victoriametrics/vmalert
    tag: v1.99.0
  imagePullSecrets:
    - name: staffbase-artifactory
  datasource:
    url: http://vmselect-vmcluster.monitoring.svc.cluster.local:8481/select/0/prometheus
  externalLabels:
    staffbase_cluster: "${staffbase_cluster_fullname}"
    staffbase_env: "${staffbase_cluster_env}"
    staffbase_region: "${staffbase_cluster_region}"
  livenessProbe:
    failureThreshold: 15
  logFormat: json
  logLevel: INFO
  notifiers:
    - url: http://vmalertmanager-vmalertmanager-0.vmalertmanager-vmalertmanager.monitoring.svc.cluster.local:9093
    - url: http://vmalertmanager-vmalertmanager-1.vmalertmanager-vmalertmanager.monitoring.svc.cluster.local:9093
    - url: http://vmalertmanager-vmalertmanager-2.vmalertmanager-vmalertmanager.monitoring.svc.cluster.local:9093
  podDisruptionBudget:
    maxUnavailable: 1
  podMetadata:
    annotations:
      sidecar.istio.io/proxyCPU: "100m"
      sidecar.istio.io/proxyMemory: "512Mi"
      sidecar.istio.io/proxyMemoryLimit: "512Mi"
    labels:
      app: vmalert
  remoteRead:
    url: http://vmselect-vmcluster.monitoring.svc.cluster.local:8481/select/0/prometheus
  remoteWrite:
    url: http://vminsert-vmcluster.monitoring.svc.cluster.local:8480/insert/0/prometheus
  replicaCount: 3
  ruleSelector: {}
  securityContext:
    runAsNonRoot: true
    runAsUser: 65534
    seccompProfile:
      type: RuntimeDefault
  topologySpreadConstraints:
    - maxSkew: 1
      topologyKey: kubernetes.io/hostname
      whenUnsatisfiable: ScheduleAnyway
      labelSelector:
        matchLabels:
          app: vmalert
    - maxSkew: 1
      topologyKey: topology.kubernetes.io/zone
      whenUnsatisfiable: ScheduleAnyway
      labelSelector:
        matchLabels:
          app: vmalert
```

</details>

<details>
  <summary>VMAlertmanager Configuration</summary>

```yaml
---
apiVersion: operator.victoriametrics.com/v1beta1
kind: VMAlertmanager
metadata:
  name: vmalertmanager
  namespace: monitoring
spec:
  image:
    repository: <REGISTRY>/sb-images-quay-proxy/prometheus/alertmanager
    tag: v0.27.0
  imagePullSecrets:
    - name: staffbase-artifactory
  configSecret: vmalertmanager
  configSelector: {}
  configNamespaceSelector: {}
  logFormat: json
  logLevel: info
  livenessProbe:
    failureThreshold: 15
  podDisruptionBudget:
    maxUnavailable: 1
  podMetadata:
    labels:
      app: vmalertmanager
    annotations:
      sidecar.istio.io/proxyCPU: "100m"
      sidecar.istio.io/proxyMemory: "512Mi"
      sidecar.istio.io/proxyMemoryLimit: "512Mi"
      traffic.sidecar.istio.io/includeInboundPorts: "*"
      traffic.sidecar.istio.io/excludeOutboundPorts: "9094"
      traffic.sidecar.istio.io/excludeInboundPorts: "9094"
  replicaCount: 3
  resources:
    limits:
      memory: 64Mi
    requests:
      cpu: 50m
      memory: 64Mi
  securityContext:
    runAsNonRoot: true
    runAsUser: 65534
    fsGroup: 65534
    seccompProfile:
      type: RuntimeDefault
  topologySpreadConstraints:
    - maxSkew: 1
      topologyKey: kubernetes.io/hostname
      whenUnsatisfiable: ScheduleAnyway
      labelSelector:
        matchLabels:
          app: vmalertmanager
    - maxSkew: 1
      topologyKey: topology.kubernetes.io/zone
      whenUnsatisfiable: ScheduleAnyway
      labelSelector:
        matchLabels:
          app: vmalertmanager
  storage:
    volumeClaimTemplate:
      spec:
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 5Gi
        storageClassName: managed-premium
```

</details>

<details>
  <summary>VMRule</summary>

```yaml
---
apiVersion: operator.victoriametrics.com/v1beta1
kind: VMRule
metadata:
  labels:
    kustomize.toolkit.fluxcd.io/substitute: disabled
  name: clickhouse-alert-rules
  namespace: monitoring
spec:
  groups:
    - name: ClickHouseOperatorRules
      rules:
        - alert: ClickHouseReplicatedPartFailedFetches
          expr: increase(chi_clickhouse_event_ReplicatedPartFailedFetches[1m]) > 0
          for: 5m
          labels:
            namespace: "{{ $labels.exported_namespace }}"
            severity: error
          annotations:
            message: "Increased ReplicatedPartFailedFetches on {{ $labels.exported_namespace }}/{{ $labels.hostname }}"
            runbook: |
              `clickhouse-server` increase ReplicatedPartFailedFetches in `system.events` table. It mean server was failed to download data part from replica of a ReplicatedMergeTree table.

              Please check following things:

              - connections between clickhouse-server pod and his replicas (see remote_server section in /etc/clickhouse-server/)
              - logs on clickhouse-server pods

              ```shell
              kubectl exec -n {{ $labels.exported_namespace }} pod/$(kubectl get pods -n {{ $labels.exported_namespace }} | grep $( echo {{ $labels.hostname }} | cut -d '.' -f 1) | cut -d " " -f 1) -- cat /var/log/clickhouse-server/*.err.log | less
              ```

              You can also check the errors via clickhouse-client to find infos about broken parts:

              ```
              kubectl exec -it chi-clickhouse-logging-replicated-9-0-0 -- clickhouse-client --query='select * from system.errors FORMAT Vertical'
              ```
```

</details>


### Version

vmalert-20240301-013716-tags-v1.99.0-0-g9cd4b0537

### Logs

_No response_

### Screenshots

_No response_

### Used command-line flags

```sh
/vmalert-prod -datasource.url=http://vmselect-vmcluster.monitoring.svc.cluster.local:8481/select/0/prometheus -external.label=staffbase_cluster=de1 -external.label=staffbase_env=prod -external.label=staffbase_region=de1 -httpListenAddr=:8080 -loggerFormat=json -loggerLevel=INFO -notifier.url=http://vmalertmanager-vmalertmanager-0.vmalertmanager-vmalertmanager.monitoring.svc.cluster.local:9093,http://vmalertmanager-vmalertmanager-1.vmalertmanager-vmalertmanager.monitoring.svc.cluster.local:9093,http://vmalertmanager-vmalertmanager-2.vmalertmanager-vmalertmanager.monitoring.svc.cluster.local:9093 -remoteRead.url=http://vmselect-vmcluster.monitoring.svc.cluster.local:8481/select/0/prometheus -remoteWrite.url=http://vminsert-vmcluster.monitoring.svc.cluster.local:8480/insert/0/prometheus -rule="/etc/vmalert/config/vm-vmalert-rulefiles-0/*.yaml"
```
