### ISSUE TITLE
Can the memory of vmstorage be reduced?

### ISSUE THREAD

**Issue by githubeto** [VictoriaMetrics/VictoriaMetrics#6075]
### Is your question request related to a specific component?

vmstorage, active_time_series

### Describe the question in detail

I installed it using the victoria-metrics-k8s-stack.
The app version is v1.97.1.

I have confirmed that the TooHighMemoryUsage alert is being triggered for the VmStorage component on the management cluster. As per the metrics below, it is evident that the memory usage is fluctuating around 80%.

![image](https://github.com/VictoriaMetrics/VictoriaMetrics/assets/122009205/2e0d6648-893e-4ab6-b079-040f49772e6a)

Currently, for the VmStorage component, the request/limit is set as follows:

```
    vmstorage:
      extraArgs:
        search.maxUniqueTimeseries: "10000000"
      image:
        tag: v1.95.1-cluster
      priorityClassName: cluster-medium
      replicaCount: 3
      resources:
        limits:
          memory: 7125Mi
        requests:
          cpu: 1097m
          memory: 7125Mi
```

Additionally, I checked the Cardinality Explorer on the management cluster. The value of Total Series was 6,219,599. 
The required amount of memory for vmstorage is approximately 11GB if it is calculated as 2 * active_time_series * 1KB.
However, we are considering reducing this value.

https://github.com/VictoriaMetrics/VictoriaMetrics/issues/1069

To reduce the amount of memory (number of TimeSeries), I checked "Labels with the highest number of series". However, I believe that the labels positioned at the top are essential labels. Even if we remove the lower-level labels, would it not have any effect on reducing the memory usage?

![image](https://github.com/VictoriaMetrics/VictoriaMetrics/assets/122009205/832bbb66-1a40-4094-81eb-ab8a0162441f)

Is increasing the memory limit of VMStorage to 11GB the only option? Please advise.

### Troubleshooting docs

- [X] General - https://docs.victoriametrics.com/Troubleshooting.html
- [X] vmagent - https://docs.victoriametrics.com/vmagent.html#troubleshooting
- [X] vmalert - https://docs.victoriametrics.com/vmalert.html#troubleshooting
