### ISSUE TITLE
vmagent relable metrics

### ISSUE THREAD

**Issue by zentkhv** [VictoriaMetrics/VictoriaMetrics#6080]
### Describe the bug

Im trying to filter only one metric by name with: https://docs.victoriametrics.com/relabeling/#how-to-drop-metrics-during-scrape

But my config drops only metrics that are up to the chosen metric and those that after are keeped. Its the same problem with add label: https://stackoverflow.com/questions/78290191/victoriametrics-vm-agent-relable-metrics-pattern 
How can i keep only one metric?
Looks like bug.

### To Reproduce

My config:
```

global:
  scrape_interval: 60s
  scrape_timeout: 60s
  external_labels:
    server_name: vmagent

scrape_configs:
  - job_name: "kafka_exporter"
    file_sd_configs:
    - files:
      - kafka_exporter.yml
    metric_relabel_configs:
      - if: '{__name__!~"kafka_consumergroup_lag_sum"}'
        action: drop

```

### Version

vmagent-20230406-062410-tags-v1.87.5

**Comment by jiekun** [comment]
Hi!

May I ask if you've tried:
```yaml
  # current config
  - if: '{name!~"kafka_consumergroup_lag_sum"}'
  # have you tried this one?
  - if: '{__name__=~"kafka_consumergroup_lag_sum"}'
```

Please paste your config within a code block so that it could be formatted correctly and potentially easier to solve.

Also I saw some test case in this repo which might be helpful:

https://github.com/VictoriaMetrics/VictoriaMetrics/blob/83216e956c86707abf6424018d13e57f66ac393b/lib/promrelabel/relabel_test.go#L1075

```
- action: drop
  if: '{__name__!~"smth"}' 
```

**Comment by zentkhv** [comment]
@jiekun , shure. "name" was sintax error. Im using:
`  - if: '{__name__!~"kafka_consumergroup_lag_sum"}'`

This one doesnt help:
```
- action: drop
  if: '{__name__!~"kafka_consumergroup_lag_sum"}' 
```

**Comment by jiekun** [comment]
Okie, could you check the debugging page for this metric to see how the relabel config work and paste some screenshots here

**Comment by zentkhv** [comment]
![vm](https://github.com/VictoriaMetrics/VictoriaMetrics/assets/70746340/3fbef8bb-815e-4292-b32e-5bdbd52d1ccf)
@jiekun , thats it?

**Comment by jiekun** [comment]
cmiiw, you intend to drop metrics whose `__name__` is **not equal** to `kafka_consumergroup_lag_sum`. But the `kafka_consumergroup_lag_sum` is **dropped** and other metrics are **preserved**?

**Comment by zentkhv** [comment]
@jiekun, no. Metrics up to `kafka_consumergroup_lag_sum` realy drop as expected, but metrics after it are also preserved (it is not expocted). Expected to preserved only one metric with name `kafka_consumergroup_lag_sum`.

**Comment by jiekun** [comment]
I tried the configuration myself and the relabel result should be like:

![image](https://github.com/VictoriaMetrics/VictoriaMetrics/assets/30280396/543faf2c-35e3-4c44-a1e2-b55084335ad0)
![image](https://github.com/VictoriaMetrics/VictoriaMetrics/assets/30280396/212b97a1-69b1-4174-a497-754e0a3c988e)

You can debug on other metrics to see if they are dropped (but somehow preserved in real-world usage). and see if vm maintainers have other suggestion for ya ^_^

**Comment by zentkhv** [comment]
@jiekun, other metrics is filtering like on second image

**Comment by f41gh7** [comment]
Looks strange. 

 Could you try a  bit more simple example for it:

```yaml
    metric_relabel_configs:
    - source_labels: [__name__]
      action: keep
      regex: '^kafka_consumergroup_lag_sum$'
```
