### ISSUE TITLE
Question about vmagent 1.93.5 and memory usage with "last" streaming aggregation function

### ISSUE THREAD

**Issue by akhileshmalavalli** [VictoriaMetrics/VictoriaMetrics#6190]
### Is your question request related to a specific component?

vmagent 1.93.5

### Describe the question in detail

I have previously seen a discussion about resource usage and streaming aggregation, as referenced [here](https://github.com/VictoriaMetrics/VictoriaMetrics/issues/5898). My current question is specific to vmagent 1.93.5 and `last` streaming aggregation function with the config show below:
```
- match: <List of metrics to match - around 50>
  interval: 1m
  outputs: [last]
  output_relabel_configs:
  - source_labels: [__name__]
    target_label: __name__
    regex: "(.+):.+"
```

### Issue Description
When using the configuration above, I've observed an increase in memory usage by about 30% to 40%. I understand the general memory requirements associated with streaming aggregation as described in this [question](https://github.com/VictoriaMetrics/VictoriaMetrics/issues/5898). However, I'm puzzled about the memory usage with the `last` function. This function, to my understanding, should not require retaining data in memory for calculations like the `avg` function would. Therefore, I would expect the memory consumption for `last` to be less compared to other aggregation functions.

### Questions
* Why does the `last` function result in a significant memory usage increase, despite its apparent simplicity and no need for historical data retention?

Thank you in advance for your insights!

### Troubleshooting docs

- [ ] General - https://docs.victoriametrics.com/troubleshooting/
- [X] vmagent - https://docs.victoriametrics.com/vmagent/#troubleshooting
- [ ] vmalert - https://docs.victoriametrics.com/vmalert/#troubleshooting
