### ISSUE TITLE
vmagent job flapping up/down with no errors

### ISSUE THREAD

**Issue by k0nstantinv** [VictoriaMetrics/VictoriaMetrics#6203]
### Is your question request related to a specific component?

vmagent

### Describe the question in detail

Vicotriametics cluster 1.96

Victoriametrics vmagent 1.96
clusterized 6 member vmagent

```
vmagent:
  enabled: true
  replicaCount: 1
  shardCount: 6
  scrapeInterval: 30s
  spec:
    image:
      tag: v1.96.0
    updateStrategy: Recreate
    extraArgs:
      loggerFormat: json
      promscrape.cluster.name: prod-euno1-devpl-0
      promscrape.disableCompression: "false"
      promscrape.discovery.concurrency: "200"
      promscrape.maxDroppedTargets: "5000"
      promscrape.maxScrapeSize: 4GB
      promscrape.noStaleMarkers: "true"
      promscrape.streamParse: "true"
      promscrape.suppressScrapeErrors: "true"
      remoteWrite.maxBlockSize: 200MB
      remoteWrite.maxRowsPerBlock: "11000"
      remoteWrite.queues: "170"
      remoteWrite.tlsInsecureSkipVerify: "true"
    externalLabels:
      cluster: prod-euno1-devpl-0
    nodeSelector:
      dedicated-to: victoriametrics
    tolerations:
    - effect: NoSchedule
      key: dedicated-to
      operator: Equal
      value: victoriametrics
    affinity:
      podAntiAffinity:
        requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchExpressions:
                - key: app.kubernetes.io/name
                  operator: In
                  values:
                    - vmagent
            topologyKey: kubernetes.io/hostname
    resources:
      limits:
        cpu: 5100m
        memory: 7Gi
      requests:
        cpu: 2100m
        memory: 4Gi
  ingress:
    enabled: false
  additionalScrapeConfigs: |
    - job_name: opencost
      honor_labels: true
      scrape_interval: 1m
      scrape_timeout: 10s
      metrics_path: /metrics
      scheme: http
      dns_sd_configs:
      - names:
        - opencost.opencost
        type: 'A'
        port: 9003
```

everything seems to be fine, but built-in dashboard always shows `vmagent` job is flapping up/down
![image](https://github.com/VictoriaMetrics/VictoriaMetrics/assets/31267902/22320594-e60b-4e5a-9828-bde8d690c886)

this yellow bars on the graph represent this query `up{job="vmagent-vm-stack"}`

and VMUI really shows this job goes up and down every time
![image](https://github.com/VictoriaMetrics/VictoriaMetrics/assets/31267902/74b8505b-2094-47c2-b2ac-71cc288a03b8)

 but I completely can't find the reason. There are no pod/container restarts at all
 ```
 $ k -n monitoring get pods -o wide | grep vmagent
vmagent-vm-stack-0-955dfdb6c-4lfk6                 2/2     Running   0               61m     10.33.91.209     ip-10-105-149-218.eu-north-1.compute.internal   <none>           <none>
vmagent-vm-stack-1-7db4f47479-c5c26                2/2     Running   0               64m     10.33.85.121     ip-10-105-153-69.eu-north-1.compute.internal    <none>           <none>
vmagent-vm-stack-2-68c6548d75-dnfp7                2/2     Running   0               35m     10.33.105.61     ip-10-105-179-11.eu-north-1.compute.internal    <none>           <none>
vmagent-vm-stack-3-57745d6b67-l9thn                2/2     Running   0               45m     10.33.96.213     ip-10-105-179-85.eu-north-1.compute.internal    <none>           <none>
vmagent-vm-stack-4-586b756895-wz9pw                2/2     Running   0               40m     10.33.101.169    ip-10-105-152-189.eu-north-1.compute.internal   <none>           <none>
vmagent-vm-stack-5-544d5b9dc-wrk6x                 2/2     Running   0               5d1h    10.33.222.245    ip-10-105-178-188.eu-north-1.compute.internal   <none>           <none>
 ```
 and pods don't even have any errors
 ```
 $ k -n monitoring logs -f vmagent-vm-stack-3-57745d6b67-l9thn vmagent | grep -v info
 (empty)
^C
 ```
 
 Please, help me to debug 

### Troubleshooting docs

- [X] General - https://docs.victoriametrics.com/troubleshooting/
- [X] vmagent - https://docs.victoriametrics.com/vmagent/#troubleshooting
- [X] vmalert - https://docs.victoriametrics.com/vmalert/#troubleshooting
