### ISSUE TITLE
vmagent panic on remoteWrite.streamAggr.dedupInterval

### ISSUE THREAD

**Issue by alexintech** [VictoriaMetrics/VictoriaMetrics#6205]
### Describe the bug

vmagent crashes periodically when the `-remoteWrite.streamAggr.dedupInterval="0s,120s"` flag set.

### To Reproduce

vmagent configured with `remoteWrite.streamAggr.dedupInterval` configuration:
```
apiVersion: operator.victoriametrics.com/v1beta1
kind: VMAgent
metadata:
  name: vmagent-multi-retention
  namespace: victoria-metrics
spec:
  image:
    tag: v1.101.0
  selectAllByDefault: true
  replicaCount: 1
  scrapeInterval: 20s
  scrapeTimeout: 10s
  externalLabels:
    cluster: mycluster
  extraArgs:
    promscrape.streamParse: 'true'
    remoteWrite.streamAggr.dedupInterval: "0s,120s"
  statefulMode: true
  statefulStorage:
    volumeClaimTemplate:
      spec:
        resources:
          requests:
            storage: 20Gi
  remoteWrite:
    - url: "http://vminsert-vmcluster-retention-1m.victoria-metrics.svc:8480/insert/0/prometheus/api/v1/write"
    - url: "http://vminsert-vmcluster-retention-3m.victoria-metrics.svc:8480/insert/0/prometheus/api/v1/write"
```

### Version

./vmagent-prod --version
vmagent-20240425-145801-tags-v1.101.0-0-g5334f0c2c

### Logs

```
panic: runtime error: index out of range [6] with length 0

goroutine 15146 [running]:
github.com/VictoriaMetrics/VictoriaMetrics/app/vmagent/remotewrite.(*writeRequest).copyTimeSeries(0xc000000008, 0xc004a236e0, 0xc000a796e8)
	github.com/VictoriaMetrics/VictoriaMetrics/app/vmagent/remotewrite/pendingseries.go:207 +0x6a9
github.com/VictoriaMetrics/VictoriaMetrics/app/vmagent/remotewrite.(*writeRequest).tryPush(0xc000000008, {0xc000a72008, 0x283, 0xc0004f8820?})
	github.com/VictoriaMetrics/VictoriaMetrics/app/vmagent/remotewrite/pendingseries.go:192 +0x6d
github.com/VictoriaMetrics/VictoriaMetrics/app/vmagent/remotewrite.(*pendingSeries).TryPush(0xc000000000, {0xc000a72008?, 0x40c025?, 0x10?})
	github.com/VictoriaMetrics/VictoriaMetrics/app/vmagent/remotewrite/pendingseries.go:64 +0x67
github.com/VictoriaMetrics/VictoriaMetrics/app/vmagent/remotewrite.(*remoteWriteCtx).tryPushInternal(0x8?, {0xc000a72008?, 0x0?, 0xc00013c510?})
	github.com/VictoriaMetrics/VictoriaMetrics/app/vmagent/remotewrite/remotewrite.go:1015 +0x1c5
github.com/VictoriaMetrics/VictoriaMetrics/app/vmagent/remotewrite.(*remoteWriteCtx).TryPush(0xc000099b60, {0xc000a72008?, 0x10a20?, 0xc0000a3950?})
	github.com/VictoriaMetrics/VictoriaMetrics/app/vmagent/remotewrite/remotewrite.go:957 +0x605
github.com/VictoriaMetrics/VictoriaMetrics/app/vmagent/remotewrite.tryPushBlockToRemoteStorages.func1(0xc00117aeac?)
	github.com/VictoriaMetrics/VictoriaMetrics/app/vmagent/remotewrite/remotewrite.go:593 +0x65
created by github.com/VictoriaMetrics/VictoriaMetrics/app/vmagent/remotewrite.tryPushBlockToRemoteStorages in goroutine 49
	github.com/VictoriaMetrics/VictoriaMetrics/app/vmagent/remotewrite/remotewrite.go:591 +0xea
```

### Used command-line flags

command-line flags
-httpListenAddr=":8429"
-promscrape.config="/etc/vmagent/config_out/vmagent.env.yaml"
-promscrape.streamParse="true"
-remoteWrite.maxDiskUsagePerURL="1073741824"
-remoteWrite.streamAggr.dedupInterval="0s,2m0s"
-remoteWrite.tmpDataPath="/vmagent_pq/vmagent-remotewrite-data"
-remoteWrite.url="secret"
