### ISSUE TITLE
vmagent panic crash when more than one remoteWrite.url

### ISSUE THREAD

**Issue by gmwiku** [VictoriaMetrics/VictoriaMetrics#6285]
### Describe the bug

I use latest vmagent docker release () and all (a few) instances using single remoteWrite.url work stable, but one using two remoteWrite.url is crashing.
I suppose all recent (last week) releases are affected.

### To Reproduce

part of docker-compose.yml:
```
  vmagent:

    image: victoriametrics/vmagent
    container_name: vmagent
    restart: unless-stopped
    networks:
      - network_victoriametrics
    volumes:
      - "./vmagent-config:/vmagent-config"
    command: -influxTrimTimestamp=1000ms -remoteWrite.url=http://victoriametrics:8428/api/v1/write -remoteWrite.significantFigures=6 -remoteWrite.urlRelabelConfig=/vmagent-config/relabel.yml -remoteWrite.streamAggr.config=/vmagent-config/vmaggr_none.yml -remoteWrite.url=http://victoriametrics-5m:8428/api/v1/write -remoteWrite.significantFigures=6 -remoteWrite.urlRelabelConfig=/vmagent-config/relabel.yml -remoteWrite.streamAggr.config=/vmagent-config/vmaggr_5m_avg.yml
```

### Version

```
build version: vmagent-20240514-114434-heads-aggregators-global-0-g1e88578a7
```
```
victoriametrics/vmagent            latest    ebf6ce47cbe9   35 hours ago    24.8MB
```

### Logs

```
2024-05-15T22:40:00.006Z  panic   VictoriaMetrics/lib/promutils/labelscompressor.go:102   BUG: unexpected non-empty tail left; len(tail)=15; tail=08B6128D12EC7AAB12BB09BE120309
 panic: BUG: unexpected non-empty tail left; len(tail)=15; tail=08B6128D12EC7AAB12BB09BE120309
 
 goroutine 18669 [running]:
 github.com/VictoriaMetrics/VictoriaMetrics/lib/logger.logMessage({0xa59a63, 0x5}, {0xc001216a20, 0x56}, 0x4)
   github.com/VictoriaMetrics/VictoriaMetrics/lib/logger/logger.go:301 +0xa74
 github.com/VictoriaMetrics/VictoriaMetrics/lib/logger.logLevelSkipframes(0x1, {0xa59a63, 0x5}, {0xa85a42?, 0xc0000cbd20?}, {0xc0000cbd38?, 0x2000?, 0x0?})
   github.com/VictoriaMetrics/VictoriaMetrics/lib/logger/logger.go:141 +0x1a5
 github.com/VictoriaMetrics/VictoriaMetrics/lib/logger.logLevel(...)
   github.com/VictoriaMetrics/VictoriaMetrics/lib/logger/logger.go:133
 github.com/VictoriaMetrics/VictoriaMetrics/lib/logger.Panicf(...)
   github.com/VictoriaMetrics/VictoriaMetrics/lib/logger/logger.go:129
 github.com/VictoriaMetrics/VictoriaMetrics/lib/promutils.(*LabelsCompressor).Decompress(0x11168c0, {0x0, 0x0, 0x0}, {0xc002c74331, 0x10, 0x10})
   github.com/VictoriaMetrics/VictoriaMetrics/lib/promutils/labelscompressor.go:102 +0x1a5
 github.com/VictoriaMetrics/VictoriaMetrics/lib/streamaggr.decompressLabels(...)
   github.com/VictoriaMetrics/VictoriaMetrics/lib/streamaggr/streamaggr.go:865
 github.com/VictoriaMetrics/VictoriaMetrics/lib/streamaggr.(*flushCtx).appendSeries(0xc000d46a80, {0xc002c74331?, 0xc002caa9c0?}, {0xa592dd, 0x3}, 0x18f7e699218, 0x0)
   github.com/VictoriaMetrics/VictoriaMetrics/lib/streamaggr/streamaggr.go:1040 +0x94
 github.com/VictoriaMetrics/VictoriaMetrics/lib/streamaggr.(*avgAggrState).flushState.func1({0x9aca40, 0xc002caa9c0}, {0x99b660?, 0xc002bd89e0})
   github.com/VictoriaMetrics/VictoriaMetrics/lib/streamaggr/avg.go:81 +0x165
 sync.(*Map).Range(0xc0002bb140?, 0xc0008bff38)
   sync/map.go:477 +0x1f8
 github.com/VictoriaMetrics/VictoriaMetrics/lib/streamaggr.(*avgAggrState).flushState(0xc0000b8ee0?, 0x0?, 0x0?)
   github.com/VictoriaMetrics/VictoriaMetrics/lib/streamaggr/avg.go:65 +0x5c
 github.com/VictoriaMetrics/VictoriaMetrics/lib/streamaggr.(*aggregator).flush.func1({0xbda378, 0xc0002bb140})
   github.com/VictoriaMetrics/VictoriaMetrics/lib/streamaggr/streamaggr.go:758 +0x8d
 created by github.com/VictoriaMetrics/VictoriaMetrics/lib/streamaggr.(*aggregator).flush in goroutine 101
   github.com/VictoriaMetrics/VictoriaMetrics/lib/streamaggr/streamaggr.go:751 +0x105
```
