### ISSUE TITLE
how to use stream aggregation on prom style histograms

### ISSUE THREAD

**Issue by steeling** [VictoriaMetrics/VictoriaMetrics#6319]
### Is your question request related to a specific component?

vmagent

### Describe the question in detail

For prom-style histograms (with labels "le=.05", etc), how can I generate quantiles using stream aggregation?

I'm trying something like

```yaml
- match: '{__name__=~".+_buckets"}'
  interval: 10m
  outputs: ["quantiles(0.50, 0.75, 0.9, 0.95, 0.99)"]
```

which isn't working

### Troubleshooting docs

- [ ] General - https://docs.victoriametrics.com/troubleshooting/
- [X] vmagent - https://docs.victoriametrics.com/vmagent/#troubleshooting
- [ ] vmalert - https://docs.victoriametrics.com/vmalert/#troubleshooting
