### ISSUE TITLE
vmalert: add rules backfilling API

### ISSUE THREAD

**Issue by Haleygo** [VictoriaMetrics/VictoriaMetrics#6328]
### Is your feature request related to a problem? Please describe

vmalert supports alerting and recording [rules backfilling (aka replay)](https://docs.victoriametrics.com/vmalert/#rules-backfilling) as a cli-tool, and exits immediately after work is done. It provides a interface like this to display the execution progress.
<img width="721" alt="image" src="https://github.com/VictoriaMetrics/VictoriaMetrics/assets/39937150/4ce08690-848c-4426-906c-06e72fef7bbe">

We normally recommend to use jobs like in K8s to perform replay operations. But sometimes, user who manages rules doesn't have permission to create k8s resources or don't want to have extra code to manage those jobs.

### Describe the solution you'd like

1. Adding /replay API in vmalert, which accepts rule files, replay.timeFrom and replay.timeTo timestamps, performs backfilling like replay mode.
   * Pros: avoid using external jobs
   * Cons: 
     * replay operation could be pretty expensive when rule expression returns tons of time series, in this case, vmalert requires extra resources apart from the normal usage. Those resources can be hard to estimate and wasted after replay.
     And when replay is executing with normal rule evaluations, it could delay normal rule evaluations or crash vmalert for reason like OOM.
     * replay can take long to finish, user can't tell when it's gonna finish.
2. Adding replay options to [rule group](https://docs.victoriametrics.com/vmalert/#groups), vmalert will replay recording rules when this group starts for the first time[options only valid for recording rules, we check results from datasource for {replayFrom, replayTo} first, to know if rule has been replayed).
   ```
   ##The name of the group. Must be unique within a file.
   name: 
   
   ##replay it when start this group for the first time
   replay: true
   replayFrom: 2024-05-11T07:21:43Z
   replayTo: 2024-05-11T07:21:43Z
   replayInterval: 1d
   ```
   * Pros: easy to use
   * Cons: easy to overuse, and has same resource problems as adding /replay API.
