### ISSUE TITLE
vmauth: default httpserver incorrectly exposed

### ISSUE THREAD

**Issue by f41gh7** [VictoriaMetrics/VictoriaMetrics#6468]
### Describe the bug

 vmauth returns own responses for built-in http routes, such as`/metrics`, `/debug/pprof` and other. 

Authorization header ignored for those routes.

 It confuses, because users expect target backend response instead of vmauth response.

### To Reproduce

With given configuration file:

```yaml
unauthorized_user:
  # vmsingle route
 url_prefix: http://localhost:8428
```
Launch vmauth without any further service. Try to execute following requests:

- request for localhost:8428/metrics is success (expected to fail).
- request for localhost:8428/api/v1/query - backend error.

### Version

any version
