### ISSUE TITLE
vmagent using k8s endpoint role for pod role jobs

### ISSUE THREAD

**Issue by dctrwatson** [VictoriaMetrics/VictoriaMetrics#6472]
### Describe the bug

We have a kubernetes cluster with over 1000 nodes so we use VMPodScrape to scrape node-exporter. However, vmagent is complaining about endpoint not being compatible.

### To Reproduce

try to scrape >1000 pods:
```yaml
apiVersion: operator.victoriametrics.com/v1beta1
kind: VMPodScrape
metadata:
  name: kube-prometheus-stack-prometheus-node-exporter
  namespace: monitoring
spec:
  attach_metadata:
    node: false
  jobLabel: jobLabel
  namespaceSelector:
    matchNames:
    - monitoring
  podMetricsEndpoints:
  - attach_metadata: {}
    filterRunning: true
    follow_redirects: false
    honorLabels: true
    honorTimestamps: true
    path: /metrics
    port: http-metrics
    relabelConfigs:
    - action: replace
      regex:
      - (.*)
      replacement: $1
      sourceLabels:
      - __meta_kubernetes_pod_node_name
      targetLabel: instance
    scheme: http
  selector:
    matchLabels:
      app.kubernetes.io/instance: kube-prometheus-stack
      app.kubernetes.io/name: prometheus-node-exporter
```

### Version

vmagent-20240425-145801-tags-v1.101.0-0-g5334f0c2c

### Logs

VictoriaMetrics/lib/promscrape/discovery/kubernetes/endpoints.go:112	the number of targets for "role: endpoints" "monitoring/kube-prometheus-stack-prometheus-node-exporter" exceeds 1000 and has been truncated; please use "role: endpointslice" instead

### Used command-line flags

-envflag.enable=true
-http.shutdownDelay=30s
-httpListenAddr=:8429
-promscrape.config=/etc/vmagent/config_out/vmagent.env.yaml
-promscrape.dropOriginalLabels=true
-promscrape.kubernetes.attachNodeMetadataAll=true
-promscrape.maxScrapeSize=256MiB
-promscrape.streamParse=true
-promscrape.suppressScrapeErrorsDelay=60s

### Additional information

from `/config`:
```
- job_name: podScrape/monitoring/kube-prometheus-stack-prometheus-node-exporter/0
  metrics_path: /metrics
  honor_labels: true
  honor_timestamps: true
  scheme: http
  follow_redirects: false
  relabel_configs:
  - action: drop
    source_labels: [__meta_kubernetes_pod_phase]
    regex: (Failed|Succeeded)
  - action: keep
    source_labels: [__meta_kubernetes_pod_label_app_kubernetes_io_instance]
    regex: kube-prometheus-stack
  - action: keep
    source_labels: [__meta_kubernetes_pod_label_app_kubernetes_io_name]
    regex: prometheus-node-exporter
  - action: keep
    source_labels: [__meta_kubernetes_pod_container_port_name]
    regex: http-metrics
  - source_labels: [__meta_kubernetes_namespace]
    target_label: namespace
  - source_labels: [__meta_kubernetes_pod_container_name]
    target_label: container
  - source_labels: [__meta_kubernetes_pod_name]
    target_label: pod
  - target_label: job
    replacement: monitoring/kube-prometheus-stack-prometheus-node-exporter
  - source_labels: [__meta_kubernetes_pod_label_jobLabel]
    target_label: job
    regex: (.+)
    replacement: ${1}
  - target_label: endpoint
    replacement: http-metrics
  - action: replace
    source_labels: [__meta_kubernetes_pod_node_name]
    target_label: instance
    regex: (.*)
    replacement: $1
  kubernetes_sd_configs:
  - role: pod
    namespaces:
      own_namespace: false
      names:
      - monitoring
    selectors:
    - role: pod
      label: app.kubernetes.io/instance=kube-prometheus-stack,app.kubernetes.io/name=prometheus-node-exporter
      field: ""
```

**Comment by f41gh7** [comment]
Hello, it's not possible to use `VMPodScrape` with matching rule exceeds 1000 pods.

 It's recommended to switch for `VMServiceScrape`, it supports `discoveryRole` configuration:

https://docs.victoriametrics.com/operator/api/#vmservicescrapespec

```yaml
apiVersion: operator.victoriametrics.com/v1beta1
kind: VMServiceScrape
metadata:
  name: example-service-target
spec:
  discoveryRole: endpointslices
```

**Comment by dctrwatson** [comment]
> Hello, it's not possible to use `VMPodScrape` with matching rule exceeds 1000 pods.

Oh, I see. This using PodMonitor because prometheus-operator doesn't support endpointslices.

> It's recommended to switch for `VMServiceScrape`, it supports `discoveryRole` configuration:

Good to know this limitation doesn't exist with vmoperator!

Thanks!

**Comment by dctrwatson** [comment]
> It's recommended to switch for `VMServiceScrape`, it supports `discoveryRole` configuration:

So vmagents are still logging the same warning even after switching back to `VMServiceScrape` using `endpointslices`:
```
warn	VictoriaMetrics/lib/promscrape/discovery/kubernetes/endpoints.go:112	the number of targets for "role: endpoints" "monitoring/kube-prometheus-stack-prometheus-node-exporter" exceeds 1000 and has been truncated; please use "role: endpointslice" instead
``

**Comment by f41gh7** [comment]
> > It's recommended to switch for `VMServiceScrape`, it supports `discoveryRole` configuration:
> 
> So vmagents are still logging the same warning even after switching back to `VMServiceScrape` using `endpointslices`:
> 
> > warn	VictoriaMetrics/lib/promscrape/discovery/kubernetes/endpoints.go:112	the number of targets for "role: endpoints" "monitoring/kube-prometheus-stack-prometheus-node-exporter" exceeds 1000 and has been truncated; please use "role: endpointslice" instead

Could it be old `VMPodscrape` object? As far as I remember, endpoint for `VMPodscrape` and `VMServiceScrape` could have the same name at configuration file ( it's concatenation of namespace + object name).

**Comment by dctrwatson** [comment]
> Could it be old `VMPodscrape` object? As far as I remember, endpoint for `VMPodscrape` and `VMServiceScrape` could have the same name at configuration file ( it's concatenation of namespace + object name).

The only config for node-exporter in vmagent's `/config` is:
```
- job_name: serviceScrape/monitoring/kube-prometheus-stack-prometheus-node-exporter/0
  metrics_path: /metrics
  honor_labels: true
  honor_timestamps: true
  scheme: http
  follow_redirects: false
  relabel_configs:
  - action: keep
    source_labels: [__meta_kubernetes_service_label_app_kubernetes_io_instance]
    regex: kube-prometheus-stack
  - action: keep
    source_labels: [__meta_kubernetes_service_label_app_kubernetes_io_name]
    regex: prometheus-node-exporter
  - action: keep
    source_labels: [__meta_kubernetes_endpointslice_port_name]
    regex: http-metrics
  - source_labels: [__meta_kubernetes_endpointslice_address_target_kind, __meta_kubernetes_endpointslice_address_target_name]
    separator: ;
    target_label: node
    regex: Node;(.*)
    replacement: ${1}
  - source_labels: [__meta_kubernetes_endpointslice_address_target_kind, __meta_kubernetes_endpointslice_address_target_name]
    separator: ;
    target_label: pod
    regex: Pod;(.*)
    replacement: ${1}
  - source_labels: [__meta_kubernetes_pod_name]
    target_label: pod
  - source_labels: [__meta_kubernetes_namespace]
    target_label: namespace
  - source_labels: [__meta_kubernetes_service_name]
    target_label: service
  - source_labels: [__meta_kubernetes_service_name]
    target_label: job
    replacement: ${1}
  - source_labels: [__meta_kubernetes_service_label_jobLabel]
    target_label: job
    regex: (.+)
    replacement: ${1}
  - target_label: endpoint
    replacement: http-metrics
  - action: replace
    source_labels: [__meta_kubernetes_pod_node_name]
    target_label: instance
    regex: (.*)
    replacement: $1
  kubernetes_sd_configs:
  - role: endpointslices
    namespaces:
      own_namespace: false
      names:
      - monitoring
```
