### ISSUE TITLE
Different authorization for different targets, via relabel

### ISSUE THREAD

**Issue by lapo-luchini** [VictoriaMetrics/VictoriaMetrics#6493]
### Is your feature request related to a problem? Please describe

It wold be nice to allow overriding ahtorization (in my case "bearer", but maybe in general) on a per-target basis instead of forcing that only at the job level, as it is cumbersome to have whole different jobs with different names for identical jobs with different targets.

```
- job_name: 'syncthing'
  authorization: # sarebbe solo per cyberone
    type: Bearer
    credentials: bearer1 # would need to use "bearer2" for "host2"
  static_configs: 
  - targets:
    - host1:8384
  - targets:
    - host2:8384
```

### Describe the solution you'd like

```
- job_name: 'syncthing'
  authorization: # sarebbe solo per cyberone
    type: Bearer
  static_configs: 
  - targets:
    - host1:8384
    labels:
      __authorization_bearer__: bearer1
  - targets:
    - host2:8384
    labels:
      __authorization_bearer__: bearer2
```

### Additional information

I guess support should be added [around here](https://github.com/VictoriaMetrics/VictoriaMetrics/blob/6a7c7ae3912a1ab038655e0172fd696fef6cb2ec/lib/promscrape/config.go#L1231).
