### ISSUE TITLE
vmalert-tool: process won't exit when no rule is defined under group

### ISSUE THREAD

**Issue by Haleygo** [VictoriaMetrics/VictoriaMetrics#6500]
### Is your feature request related to a problem? Please describe

Run `./vmalert-tool unittest -files  .test1.yaml"
with test1.yaml
```
rule_files:
  - rules.yaml

evaluation_interval: 1m

tests:
  - interval: 1m
    name: "basic test"
    input_series:
      - series: "test"
        values: "_x5 1x5 _ stale"

    alert_rule_test:
      - eval_time: 1m
        groupname: group1
        alertname: SameAlertNameWithDifferentGroup
        exp_alerts: []
```
and rules.yaml
```
groups:
  - name: group1
    rules: []
```
and process won't exit.

### Describe the solution you'd like

vmalert-tool exits normally.
