### ISSUE TITLE
How to optimize the cross AZ traffic cost of vmagent in AWS eks clusters

### ISSUE THREAD

**Issue by tripitakav** [VictoriaMetrics/VictoriaMetrics#6516]
### Describe the question in detail

We deploy multiple copies of vmgent with statefullset. When vm collects kubernetes pod metrics, it incurs a large amount of cross az traffic costs. Is there any way to make a certain az pod only collected by the vmagent of that az.

### Troubleshooting docs

- [X] General - https://docs.victoriametrics.com/troubleshooting/
- [X] vmagent - https://docs.victoriametrics.com/vmagent/#troubleshooting
- [X] vmalert - https://docs.victoriametrics.com/vmalert/#troubleshooting

**Comment by Haleygo** [comment]
Hello!
If you have AZ label like `topology.kubernetes.io/zone: {zone-name}` set on all of the pods, and vmagent pod has it's located `zone-name` as environment variable, [relabel_config ](https://docs.victoriametrics.com/vmagent/#relabeling)could work
```
- job_name: xxx
  - relabelConfigs:
    - action: keep
      regex: "%{zone-name}"   // vmagent will read this ENV when running, and drop targets that not match with the label value
      source_labels:
      - topology.kubernetes.io/zone
```
And ofc, vmagent needs to be spread on each AZ using [topologySpreadConstraints](https://kubernetes.io/docs/concepts/scheduling-eviction/topology-spread-constraints/).
