### ISSUE TITLE
Node metrics not displayed

### ISSUE THREAD

**Issue by fabricesemti80** [VictoriaMetrics/VictoriaMetrics#6595]
### Describe the bug

I am in the process of replacing Prometheus with VictoriaMetrics in our company stack.
I ported over the `prometheus.yml`, and all working fine, except that from Linux targets I do not seem to get node metrics.

I can confirm with `curl` that the nodes are reachable and expose data. I have also set Prometheus up, to scrape the same target, and that returns the data fine.

Picking a random node of ours:

```sh
808fsemti@dc1prom01:~$ curl http://prodcache203:9100/metrics | grep "node_"
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0# HELP node_arp_entries ARP entries by device
# TYPE node_arp_entries gauge
node_arp_entries{device="ens160"} 117
# HELP node_boot_time_seconds Node boot time, in unixtime.
# TYPE node_boot_time_seconds gauge
node_boot_time_seconds 1.701941774e+09
# HELP node_context_switches_total Total number of context switches.
# TYPE node_context_switches_total counter
node_context_switches_total 3.12896769138e+11
# HELP node_cpu_guest_seconds_total Seconds the cpus spent in guests (VMs) for each mode.
# TYPE node_cpu_guest_seconds_total counter
node_cpu_guest_seconds_total{cpu="0",mode="nice"} 0
node_cpu_guest_seconds_total{cpu="0",mode="user"} 0
node_cpu_guest_seconds_total{cpu="1",mode="nice"} 0
node_cpu_guest_seconds_total{cpu="1",mode="user"} 0
node_cpu_guest_seconds_total{cpu="2",mode="nice"} 0
node_cpu_guest_seconds_total{cpu="2",mode="user"} 0
node_cpu_guest_seconds_total{cpu="3",mode="nice"} 0
node_cpu_guest_seconds_total{cpu="3",mode="user"} 0
node_cpu_guest_seconds_total{cpu="4",mode="nice"} 0
node_cpu_guest_seconds_total{cpu="4",mode="user"} 0
node_cpu_guest_seconds_total{cpu="5",mode="nice"} 0
node_cpu_guest_seconds_total{cpu="5",mode="user"} 0
node_cpu_guest_seconds_total{cpu="6",mode="nice"} 0
node_cpu_guest_seconds_total{cpu="6",mode="user"} 0
node_cpu_guest_seconds_total{cpu="7",mode="nice"} 0
node_cpu_guest_seconds_total{cpu="7",mode="user"} 0
# HELP node_cpu_seconds_total Seconds the cpus spent in each mode.
# TYPE node_cpu_seconds_total counter
node_cpu_seconds_total{cpu="0",mode="idle"} 1.699169016e+07
node_cpu_seconds_total{cpu="0",mode="iowait"} 18.56
node_cpu_seconds_total{cpu="0",mode="irq"} 0
node_cpu_seconds_total{cpu="0",mode="nice"} 61.91
node_cpu_seconds_total{cpu="0",mode="softirq"} 265336.03
node_cpu_seconds_total{cpu="0",mode="steal"} 0
node_cpu_seconds_total{cpu="0",mode="system"} 631036.34
node_cpu_seconds_total{cpu="0",mode="user"} 236162.89
node_cpu_seconds_total{cpu="1",mode="idle"} 1.693468142e+07
node_cpu_seconds_total{cpu="1",mode="iowait"} 17.96
node_cpu_seconds_total{cpu="1",mode="irq"} 0
node_cpu_seconds_total{cpu="1",mode="nice"} 138.83
node_cpu_seconds_total{cpu="1",mode="softirq"} 183793.69
node_cpu_seconds_total{cpu="1",mode="steal"} 0
node_cpu_seconds_total{cpu="1",mode="system"} 679311.09
node_cpu_seconds_total{cpu="1",mode="user"} 253927.54
node_cpu_seconds_total{cpu="2",mode="idle"} 1.690401079e+07
node_cpu_seconds_total{cpu="2",mode="iowait"} 18.05
node_cpu_seconds_total{cpu="2",mode="irq"} 0
node_cpu_seconds_total{cpu="2",mode="nice"} 172.3
node_cpu_seconds_total{cpu="2",mode="softirq"} 166494.94
node_cpu_seconds_total{cpu="2",mode="steal"} 0
node_cpu_seconds_total{cpu="2",mode="system"} 697342.61
node_cpu_seconds_total{cpu="2",mode="user"} 259296.14
node_cpu_seconds_total{cpu="3",mode="idle"} 1.689007297e+07
node_cpu_seconds_total{cpu="3",mode="iowait"} 17.41
node_cpu_seconds_total{cpu="3",mode="irq"} 0
node_cpu_seconds_total{cpu="3",mode="nice"} 121.86
node_cpu_seconds_total{cpu="3",mode="softirq"} 157094.57
node_cpu_seconds_total{cpu="3",mode="steal"} 0
node_cpu_seconds_total{cpu="3",mode="system"} 710928.92
node_cpu_seconds_total{cpu="3",mode="user"} 263292.52
node_cpu_seconds_total{cpu="4",mode="idle"} 1.688118078e+07
node_cpu_seconds_total{cpu="4",mode="iowait"} 16.59
node_cpu_seconds_total{cpu="4",mode="irq"} 0
node_cpu_seconds_total{cpu="4",mode="nice"} 108.17
node_cpu_seconds_total{cpu="4",mode="softirq"} 152741.09
node_cpu_seconds_total{cpu="4",mode="steal"} 0
node_cpu_seconds_total{cpu="4",mode="system"} 718227.82
node_cpu_seconds_total{cpu="4",mode="user"} 266258.68
node_cpu_seconds_total{cpu="5",mode="idle"} 1.686205258e+07
node_cpu_seconds_total{cpu="5",mode="iowait"} 16.53
node_cpu_seconds_total{cpu="5",mode="irq"} 0
node_cpu_seconds_total{cpu="5",mode="nice"} 118.81
node_cpu_seconds_total{cpu="5",mode="softirq"} 151703.3
node_cpu_seconds_total{cpu="5",mode="steal"} 0
node_cpu_seconds_total{cpu="5",mode="system"} 732993.64
node_cpu_seconds_total{cpu="5",mode="user"} 269653.52
node_cpu_seconds_total{cpu="6",mode="idle"} 1.68536636e+07
node_cpu_seconds_total{cpu="6",mode="iowait"} 16.16
node_cpu_seconds_total{cpu="6",mode="irq"} 0
node_cpu_seconds_total{cpu="6",mode="nice"} 121.37
node_cpu_seconds_total{cpu="6",mode="softirq"} 146565.81
node_cpu_seconds_total{cpu="6",mode="steal"} 0
node_cpu_seconds_total{cpu="6",mode="system"} 743255.58
node_cpu_seconds_total{cpu="6",mode="user"} 273767.63
node_cpu_seconds_total{cpu="7",mode="idle"} 1.684431186e+07
node_cpu_seconds_total{cpu="7",mode="iowait"} 16.93
node_cpu_seconds_total{cpu="7",mode="irq"} 0
node_cpu_seconds_total{cpu="7",mode="nice"} 85.63
node_cpu_seconds_total{cpu="7",mode="softirq"} 146443.44
node_cpu_seconds_total{cpu="7",mode="steal"} 0
node_cpu_seconds_total{cpu="7",mode="system"} 748589.7
node_cpu_seconds_total{cpu="7",mode="user"} 275890.74
# HELP node_disk_io_now The number of I/Os currently in progress.
# TYPE node_disk_io_now gauge
node_disk_io_now{device="dm-0"} 0
node_disk_io_now{device="dm-1"} 0
node_disk_io_now{device="dm-2"} 0
node_disk_io_now{device="dm-3"} 0
node_disk_io_now{device="sda"} 0
node_disk_io_now{device="sdb"} 0
# HELP node_disk_io_time_seconds_total Total seconds spent doing I/Os.
# TYPE node_disk_io_time_seconds_total counter
....
```

This node in Prometheus returns the expected metrics:

![image](https://github.com/VictoriaMetrics/VictoriaMetrics/assets/37410363/09db5755-1666-4193-b11c-85ee2aacac5f)

The same metrics are not returned in VM:

![image](https://github.com/VictoriaMetrics/VictoriaMetrics/assets/37410363/8be9607a-6e9e-4cad-8ad4-897c6a49e246)

### To Reproduce

Deploy VictoriaMetrics with the latest.

My prometheus config:

```yaml
cat /srv/VictoriMetrics/deployment/docker/prometheus.yml

global:

# ------------------------------------------------------------------------------------------------ #
#                                          GLOBAL SETTINGS                                         #
# ------------------------------------------------------------------------------------------------ #

  scrape_interval:     15s # By default, scrape targets every 15 seconds.

scrape_configs:

  - job_name: 'vmagent'
    static_configs:
      - targets: ['vmagent:8429']
  - job_name: 'vmalert'
    static_configs:
      - targets: ['vmalert:8880']
  - job_name: 'victoriametrics'
    static_configs:
      - targets: ['victoriametrics:8428']

...
  ...  # NOTE: omited other jobs as they are not relevant ...
...

  - job_name: windows_prod_connect
    relabel_configs:
      - source_labels: [__address__]
        target_label: instance
    scrape_interval: 30s
    static_configs:
    - targets: ["dc1conapi01p.gb.sportingindex.com:9182","dc1conapi02p.gb.sportingindex.com:9182","dc1conapi03p.gb.sportingindex.com:9182",.... ]
  
...
  ...  # NOTE: omited other jobs as they are not relevant ...
...

  - job_name: linux_prod_connect
    scrape_interval: 30s
    static_configs:
    - targets: ["prodcache203:9100","prodcache204:9100","prodcache205:9100","prodcache206:9100","prodamqp202:9100","prodamqp203:9100","prodamqp204:9100","prodamqp205:9100","prodamqp206:9100","prodamqp207:9100","prodamqp208:9100","prodamqp209:9100","prodamqp210:9100","dc1rmq06p:9100","dc1rmq07p:9100"]

  - job_name: vsphere
    scrape_interval: 30s
    static_configs:
    - targets: ["10.13.36.69:9272"]
808fsemti@dc1prom01:~$
```

### Version

```
/ #  ./victoria-metrics-prod --version
victoria-metrics-20240425-145715-tags-v1.101.0-0-g5334f0c2c
```
