### ISSUE TITLE
VictoriaLogs does not correctly handle ANSI escape sequences

### ISSUE THREAD

**Issue by pgassmann** [VictoriaMetrics/VictoriaMetrics#6614]
#### Summary:
VictoriaLogs does not correctly handle ANSI escape sequences (e.g., color codes) in log messages, leading to escape sequences being displayed in the output rather than being interpreted for color formatting. This behavior contrasts with Loki, which correctly interprets these sequences for color display.

#### Description:
When querying logs that contain ANSI escape sequences (e.g., `\x1b[34m` for blue text) via VictoriaLogs, the escape sequences are returned as-is within the JSON response. This can cause issues with JSON parsing and display the raw escape sequences instead of formatted text.

In contrast, querying the same logs via Loki correctly interprets the ANSI escape sequences, displaying the logs with the intended color formatting. This issue impacts readability and usability when working with logs containing ANSI escape sequences.

#### Steps to Reproduce:
1. Store log messages containing ANSI escape sequences in both Loki and VictoriaLogs.
2. Query the logs from Loki and VictoriaLogs using the provided curl commands.
3. Observe the difference in how the ANSI escape sequences are handled.

#### Expected Behavior:
VictoriaLogs should correctly handle ANSI escape sequences in log messages, either by:
1. Interpreting the escape sequences for color display (as Loki does).
2. Ensuring the JSON remains valid and escape sequences are properly encoded.

#### Actual Behavior:
VictoriaLogs returns the ANSI escape sequences as raw text within the JSON response, which can cause JSON parsing issues and displays the escape sequences instead of interpreting them for color formatting.

##### Loki Query Command:
```sh
curl -G -s "$LOKI_ADDR/loki/api/v1/query_range" \
    -u "$LOKI_USERNAME:$LOKI_PASSWORD" \
    -H "Content-Type: application/json" \
    --data-urlencode 'query={host=~"devarch01",category="dockerlogs",compose_service=~"mqdt"}' \
    --data-urlencode 'limit=2' | jq .
```

##### Loki Query Output:
```json
{
  "status": "success",
  "data": {
    "resultType": "streams",
    "result": [
      {
        "stream": {
          "category": "dockerlogs",
          "compose_project": "project-dev",
          "compose_service": "serviceA",
          "container_id": "container_id_1",
          "container_name": "project-dev_serviceA_1",
          "forwarder": "promtail",
          "host": "devarch01",
          "instance": "devarch01.example.com",
          "job": "docker",
          "source": "stdout",
          "source_type": "stdout",
          "stream": "stdout"
        },
        "values": [
          [
            "timestamp1",
            "\u001b[34mINFO \u001b[0m ServiceA.ClassA.methodA - Active subscriptions: 123"
          ]
        ]
      }
    ]
  }
}
```

##### VictoriaLogs Query Command:
```sh
curl -X POST "$VICTORIALOGS_ADDR/select/logsql/query" \
    -u "$VICTORIALOGS_USER:$VICTORIALOGS_PASSWORD" \
    -H "Content-Type: application/x-www-form-urlencoded" \
    --data-urlencode 'query=host: devarch01 AND compose_service: serviceA' \
    --data-urlencode 'limit=2'
```

##### VictoriaLogs Query Output:
```json
{
  "_time": "2024-07-09T12:48:52.174020662Z",
  "_stream_id": "stream_id_1",
  "_stream": "{category=\"dockerlogs\",compose_project=\"project-dev\",compose_service=\"serviceA\",container_name=\"project-dev_serviceA_1\",host=\"devarch01\",instance=\"devarch01.example.com\",job=\"docker\"}",
  "_msg": "\u200b[09-07-2024 12:48:52.173] [parallel-1] \x1b[34mINFO \x1b[0m \x1b[36mServiceA.ClassA.methodA\x1b[0m - Active subscriptions: 123",
  "category": "dockerlogs",
  "compose_project": "project-dev",
  "compose_service": "serviceA",
  "container_id": "container_id_1",
  "container_name": "project-dev_serviceA_1",
  "forwarder": "promtail",
  "host": "devarch01",
  "instance": "devarch01.example.com",
  "job": "docker",
  "source": "stdout",
  "source_type": "stdout",
  "stream": "stdout"
}
```

### Additional Information:
- Logs with ANSI escape sequences are common in applications that provide color-coded output for better readability.
- Proper handling of these escape sequences is crucial for maintaining the usability and readability of log messages in log management systems.

#### Suggested Fix:
- Ensure that VictoriaLogs properly interprets and handles ANSI escape sequences in log messages.
- Maintain valid JSON encoding and optionally provide a mechanism to render the escape sequences as formatted text in supported interfaces.

By addressing this issue, VictoriaLogs can provide a more consistent and user-friendly experience when managing and viewing logs with ANSI escape sequences.

### To Reproduce

1. Store log messages containing ANSI escape sequences in both Loki and VictoriaLogs.
2. Query the logs from Loki and VictoriaLogs using the provided curl commands.
3. Observe the difference in how the ANSI escape sequences are handled.

### Version

$ docker compose exec victorialogs /victoria-logs-prod --version
victoria-logs-20240701-234442-tags-v0.27.0-victorialogs-0-gd506e47c5a

### Used command-line flags

    command:
      - '-storageDataPath=/vlogs-storage'
      - '-httpListenAddr=:9428'
      - '-retentionPeriod=1y'
      - '-retention.maxDiskSpaceUsageBytes=10TiB'

### Additional information

also in grafana, the logs through loki are displayed in color, where from victorialogs, the escape sequence is shown.

The logs are ingested to loki and victorialogs using two speparate promtail instances with the same configuration:

```yaml
  - docker_sd_configs:
    - host: unix:///var/run/docker.sock
      refresh_interval: 5s
    job_name: docker
    pipeline_stages:
    - multiline:
        firstline: ^\x{200B}
        max_wait_time: 1s
    - drop:
        drop_counter_reason: line_too_old
        older_than: 48h
    relabel_configs:
    - action: replace
      replacement: ${1}
      source_labels:
      - __meta_docker_container_label_com_docker_compose_container_number
      target_label: compose_container_number
    - action: replace
      replacement: ${1}
      source_labels:
      - __meta_docker_container_label_com_docker_compose_project
      target_label: compose_project
    - action: replace
      replacement: ${1}
      source_labels:
      - __meta_docker_container_label_com_docker_compose_project_working_dir
      target_label: compose_project_working_dir
    - action: replace
      replacement: ${1}
      source_labels:
      - __meta_docker_container_label_com_docker_compose_oneoff
      target_label: compose_oneoff
    - action: replace
      replacement: ${1}
      source_labels:
      - __meta_docker_container_label_com_docker_compose_service
      target_label: compose_service
    - action: replace
      source_labels:
      - __meta_docker_container_id
      target_label: container_id
    - action: replace
      regex: /(.*)
      source_labels:
      - __meta_docker_container_name
      target_label: container_name
    - action: replace
      source_labels:
      - __meta_docker_container_log_stream
      target_label: stream
    - action: replace
      source_labels:
      - __meta_docker_container_log_stream
      target_label: source
    - action: replace
      source_labels:
      - __meta_docker_container_log_stream
      target_label: source_type
    - replacement: dockerlogs
      target_label: category
    - replacement: docker
      target_label: job
```
