### ISSUE TITLE
add Marathon service discovery to promscrape

### ISSUE THREAD

**Issue by DuraCHYo** [VictoriaMetrics/VictoriaMetrics#6642]
### Is your feature request related to a problem? Please describe

When replacing monitoring from Prometheus to Victoria Metrics, I cannot read the metrics of applications running in Mesos-Marathon due to the lack of Marathon service discovery. Because of this, the use of Victoria Metrics is limited

### Describe the solution you'd like

Add Marathon SD, for example like in Prometheus/Prometheus repo

### Describe alternatives you've considered

I tried to use the static_scrape configuration, but it didn't help

**Comment by jiekun** [comment]
Hi @DuraCHYo. I'm assigning this issue to myself for now. However, please note that the priority of implement it highly depends on how many users need it. 

For other users who come across this issue, if you also require support for this feature, please feel free to comment or give it a thumbs up.

**Comment by solaris-ventus** [comment]
Yes, it wasn't bad )

**Comment by solaris-ventus** [comment]
As far as I understand, it's not that difficult, you need to add support for mesos-labels, and so it's something close to http_sd_config

**Comment by jiekun** [comment]
Hi. I'd like to ping users who up-voted this feature and see if there is a volunteer who can help test the Marathon service discovery in the `feature/marathon-sd` branch: https://github.com/VictoriaMetrics/VictoriaMetrics/pull/7251

@DuraCHYo @edaniil @Kat10Pas, and @solaris-ventus 

You can now:
- Build it from the `feature/marathon-sd` branch. See: https://docs.victoriametrics.com/#how-to-build-from-sources.
- Request a test image/binary. Please let me know if you need help.

Any feedback is greatly appreciated. Thanks!

**Comment by DuraCHYo** [comment]
@jiekun 
Hi! Thank you so much for adding the Marathon service discovery. I've knocked down the source version. But after applying my configuration, I get only 1 instance of the server where the application is running. Is there something incorrectly written in my scrape config?
![image](https://github.com/user-attachments/assets/05ac6384-a558-4eb7-9e52-bd97a514fa4d)

- job_name: 'marathon-apps'
    marathon_sd_configs:
      - servers: ['http://server1:8080','http://server2:8080','http://server3:8080']
    relabel_configs:
      - source_labels: ['__meta_marathon_app_label_prometheus']
        regex: enabled
        separator:
        action: keep
      - source_labels: ['__meta_marathon_port_index']
        regex: 0
        separator:
        action: keep
      - source_labels: ['__meta_marathon_app_label_prometheus_path']
        target_label: '__metrics_path__'
      - source_labels: ['__meta_marathon_app']
        target_label: 'application'
      - source_labels: ['address']
        target_label: 'instance'
        separator: ':'
        regex: '(.*):(.*)'
      - source_labels: ['__meta_marathon_task']
        target_label: 'mesos_task_id'

**Comment by jiekun** [comment]
@DuraCHYo Hi!

Thanks for the quick test, very appreciated.

In your case, server1/2/3 contains different applications, right? And you want to discover all applications distributed on 3 servers?

**Comment by DuraCHYo** [comment]
@jiekun 
Sorry, that was miss config from my side. I fixed this by removing `regex: enabled` from first relabel_configs
Everything looks great!

**Comment by jiekun** [comment]
Sounds cool. Please don't hesitate to provide feedback on any issues you encounter in the future. We still need to review it before it can be released in the upcoming version.

**Comment by DuraCHYo** [comment]
@jiekun 
Hi! I started checking deeply and found some strange problem.
I have a query
`sum by (application, method, uri, status) (max_over_time(http_server_requests_seconds_count{instance=~"ufrapp8", uri!~"/admin/.*|/actuator/.*",job="marathon-apps-ufrapp"}[60m]) - min_over_time(http_server_requests_seconds_count{instance=~"ufrapp8", uri!~"/admin/.*|/actuator/.*",job="marathon-apps-ufrapp"}[60m]))`
that uses remote write from Prometheus. In it, I get a response of 204 time series, which is correct and coincides with the operation of the application and at the same time there is query from Victoria Metrics Single
`sum by (application, method, uri, status) (max_over_time(http_server_requests_seconds_count{instance=~"ufrapp8", uri!~"/admin/.*|/actuator/.*",job="vms-marathon-apps-ufrapp"}[60m]) - min_over_time(http_server_requests_seconds_count{instance=~"ufrapp8", uri!~"/admin/.*|/actuator/.*",job="vms-marathon-apps-ufrapp"}[60m])) `
which returns only 94 time series. The scrape config configuration is absolutely identical to 
```
 - job_name: 'vms-marathon-apps-ufrapp'
    metrics_path: /actuator/prometheus
    marathon_sd_configs:
       - servers: ['http://server1:8080','http://server2:8080','http://server3:8080']
         refresh_interval: 10s
    relabel_configs:
      - source_labels: ['__meta_marathon_app_label_prometheus']
        regex: enabled
        separator:
        action: keep
      - source_labels: ['__meta_marathon_port_index']
        regex: 0
        separator:
        action: keep
      - source_labels: ['__meta_marathon_app_label_prometheus_path']
        target_label: '__metrics_path__'
      - source_labels: ['__meta_marathon_app']
        target_label: 'application'
      - source_labels: ['address']
        target_label: 'instance'
        separator: ':'
        regex: '(.*):(.*)'
      - source_labels: ['__meta_marathon_task']
        target_label: 'mesos_task_id'
```
Prometheus and Victoria Metrics are on the same virtual machine. In the same subnet. Marathon Endpoints are the same. The applications are single.
The problem was not with regex
Answer to your question upper:
"In your case, server1/2/3 contains different applications, right? And you want to discover all applications distributed on 3 servers?" - The 1/2/3 server is the quorum of the marathon masters. I have an application running on ufrapp1-9 agent servers. Metrics are returned from all containers by port. For example, the application is running on ufrapp1, ufrapp3, ufrapp5, ufrapp6 servers. He has an endpoint /admin/prometheus in the labels. I'm substituting this label via relabel_configs in metrics_path. Victoria Metrics Single sees this app

**Comment by DuraCHYo** [comment]
![image](https://github.com/user-attachments/assets/174fe87c-25f3-4eb8-b7c1-93cfd22cc5e8)
![image](https://github.com/user-attachments/assets/f19c4492-4733-4cba-a70f-f3da8fd9941b)
![image](https://github.com/user-attachments/assets/a08d67a0-e70b-4f03-a26a-9d76edc4549c)

**Comment by DuraCHYo** [comment]
![image](https://github.com/user-attachments/assets/62fa5d25-c908-411a-bfce-a7f911a9edb3)
![image](https://github.com/user-attachments/assets/cbb4f90c-df08-4c1b-aed6-286a28674724)
![image](https://github.com/user-attachments/assets/e3c58971-2d25-4c0d-97ed-872acc0c2bd9)

**Comment by jiekun** [comment]
Hi. I could not provide a specific answer to the question. Do you have access to the Prometheus/VictoriaMetrics web UI? I would recommend investigating it from top to button step by step:
1. Check the service discovery result on the web UI. How many (active) targets did you get in Prometheus/VictoriaMetrics? Are they consistent?
2. Compare the scrape result for each target. This is optional since it's less likely to be different, except for some network issues. You've mentioned that Prometheus and VictoriaMetrics are deployed on the same VM.
3. Pick one target and check the relabeling by debugging. The VictoriaMetrics web UI provides a debug page for you to visualize the relabeling process: [Relabel Debug Page](https://docs.victoriametrics.com/vmagent/#relabel-debug).

On the other hand, check from button to top:
1. Compare and find one missing time series in Prometheus/VictoriaMetrics.
2. Check in Prometheus/VictoriaMetrics and see why it's not being scraped.

**Comment by jiekun** [comment]
Hi. I'd like to have more [test](https://github.com/VictoriaMetrics/VictoriaMetrics/issues/6642#issuecomment-2410290239) and feedback regarding this service discovery before we could review and merge it. 

If you are looking for this feature, feel free to comment.

**Comment by DuraCHYo** [comment]
@jiekun 
Hello. I'll provide you some feedback with screenshots as soon as possible. I still have a problem with service discovery from marathon. In VMAgent I have an 1100 targets, but in Prometheus I have around 1400. I use the same Configs at all. Give me a couple of days, please :)

**Comment by DuraCHYo** [comment]
@jiekun
I have a difference in the number of active targets between Prometheus and VictoriaMetrics Single. In Prometheus, I have 775 active targets out of 1579, while in VM Single, there are only 711 out of 1352. 
In the logs of the components, I don't see any errors, warnings, or anything else.
I use the same configuration from the same directory with the same owners and access rules. The names are different because it's easier to debug.
I am stuck investigating the problem and don't understand what the issue is. I've tried using the same CPU limits, RAM requests, and HDD usage, but it hasn't helped.
I use Prometheus v2.45.5 and self-builded image from VMSingle repo. Maybe the problem with it? Can you share me an image builded and tested by you?
Thanks for your reply. I appreciate that!
Screenshots:
![photo_2024-12-01_22-31-01](https://github.com/user-attachments/assets/a92797b0-8839-414d-8b0d-1a2ba32f5aeb)
![photo_2024-12-01_22-28-42](https://github.com/user-attachments/assets/951035f0-2070-4ba2-a7da-5d04efb37c92)

Config:
```
- job_name: 'prometheus-marathon-apps-ufrapp'
    marathon_sd_configs:
       - servers: ['http://ufrmesosm1:8080','http://ufrmesosm2:8080','http://ufrmesosm3:8080']
    relabel_configs:
      - source_labels: ['__meta_marathon_app_label_prometheus']
        regex: .*
        action: keep
      - source_labels: ['__meta_marathon_port_index']
        regex: .*
        action: keep
      - source_labels: ['__meta_marathon_app_label_prometheus_path']
        target_label: '__metrics_path__'
      - source_labels: ['__meta_marathon_app']
        target_label: 'application'
      - source_labels: ['address']
        target_label: 'instance'
        separator: ':'
        regex: '(.*):(.*)'
      - source_labels: ['address']
        regex: '.*ufrapplocal.*'
        action: drop
      - source_labels: ['address']
        regex: '.*maplapp.*'
        action: drop
      - source_labels: ['address']
        regex: '.*esiaaccnext.*'
        action: drop
```
