### ISSUE TITLE
 Query duration becomes very big when a storage node down

### ISSUE THREAD

**Issue by chn-lee-yumi** [VictoriaMetrics/VictoriaMetrics#667]
**Describe the bug**
 Query duration becomes very big when a storage node down. Usually it is several tens ms, but it becomes **4 seconds** (which is the value I configure in Grafana datasource `Query timeout`) when a storage node down. If I recovery the down node, the query duration becomes normal.

**To Reproduce**
I use cluster version with three storage node. `vminsert` is configured with `replicationFactor=2`. Then shutdown one of the three storage nodes (`vmstorage`).

**Expected behavior**
Query duration should the same as all storage is up.

**Screenshots**
![screenshot](https://user-images.githubusercontent.com/20398519/89198437-cd7a7780-d5df-11ea-96be-ab14dc559320.jpg)

**Version**
Use docker image.
```
build version: vmselect-20200730-180303-tags-v1.39.2-cluster-0-g29bbab0ec
```

**Used command-line flags**
```
  vmselect:
    container_name: vmselect
    image: victoriametrics/vmselect
    network_mode: bridge
    depends_on:
      - "vmstorage"
    command:
      - '-storageNode=10.214.18.174:8401'
      - '-dedup.minScrapeInterval=1ms'
      - '-storageNode=10.214.18.175:8401'
      - '-dedup.minScrapeInterval=1ms'
      - '-storageNode=10.214.18.173:8401'
      - '-dedup.minScrapeInterval=1ms'
    ports:
      - 8481:8481
    restart: always
```

**Additional context**
Grafana datasource configuration:
![image](https://user-images.githubusercontent.com/20398519/89199613-61990e80-d5e1-11ea-8921-4a9e018e1749.png)
Grafana VictoriaMetrics Cluster Panel:
![image](https://user-images.githubusercontent.com/20398519/89200338-732ee600-d5e2-11ea-8ee2-cf526aba7833.png)
![image](https://user-images.githubusercontent.com/20398519/89200515-b5f0be00-d5e2-11ea-9a4b-73e21bcc0840.png)
