### ISSUE TITLE
Add retention filters to VictoriaLogs

### ISSUE THREAD

**Issue by muffl0n** [VictoriaMetrics/VictoriaMetrics#6709]
### Is your feature request related to a problem? Please describe

Add retention filters to VictoriaLogs to enable different retentions for specified filters. Similar to how it's possible for VictoriaMetrics or Loki.

### Describe the solution you'd like

- VictoriaMetrics: https://docs.victoriametrics.com/#retention-filters
- Loki:
    ```
   loki: 
     limits_config: 
       ... 
       retention_period: 30d 
       retention_stream: 
         - selector: '{namespace="kube-system"}' 
           period: 1d
   ```
    https://grafana.com/docs/loki/latest/operations/storage/retention/#configuring-the-retention-period

### Additional information

See also https://www.reddit.com/r/sre/comments/1ea3taz/victorialogs_single_server_is_ready_to_use_but_we/leorhxa/
