### ISSUE TITLE
VMalert do not fire the alert to alertmanager

### ISSUE THREAD

**Issue by w6m6** [VictoriaMetrics/VictoriaMetrics#671]
**Describe the bug**
we setup a cluster of victoria metrics,  and use vmalert connecting to the cluster to fire a simple rule for testing. 
but we find that the event will never be sent to alert manager, although the rule could be triggered.
Any ideas? thx a lot. 

**Expected behavior**

** the rule defined.**
```
groups:
  - name: comp.vmutils
    rules:
      - alert: "component_is_down"
        expr: up{} == 0
        for: 2m
        labels:
          severity: "SE"
        annotations:
          summary: "Component is Down，IP: {{ $labels.ip }} "
          description: "Service type:{{ $labels.catalog }}。"
```

** the result of /api/v1/alerts**
```
{"data":{"alerts":[{"id":"4215318268030143312","name":"component_is_down","group_id":"14741780637041053963","expression":"up{} == 0","state":"pending","value":"0e+00","labels":{"app":"platform","catalog":"system","dc":"ks","idc":"ks","instance":"172.25.124.146:9100","ip":"172.25.124.146","job":"node","service":"node","severity":"SE","src_ip":"ks_145","vmcluster":"ks"},"annotations":{"description":"Service type:system。","summary":"Component is Down，IP: 172.25.124.146 "},"activeAt":"2020-08-05T21:39:48.000676284+08:00"}]},"status":"success"}
```

** the startup scripts of vmalert**
```
/usr/local/vmutils/vmalert-prod \
-httpListenAddr :8830 \
-rule=/usr/local/vmutils/vmrules/alert/*.yaml \
-rule=/usr/local/vmutils/vmrules/record/*.yaml \
-evaluationInterval=5s \
-datasource.url=http://tp-prd-idc-victoria.vip.tp.local:8480/select/0/prometheus/ \
-notifier.url="http://172.25.124.55:9093" \
-remoteRead.url=http://tp-prd-idc-victoria.vip.tp.local:8480/select/0/prometheus/ \
-remoteWrite.url=http://tp-prd-idc-victoria.vip.tp.local:8480/insert/0/prometheus/ \
-external.label=vmcluster=ks \
-loggerLevel=INFO -loggerFormat=json -loggerOutput=stdout
```

**Version**
The line returned when passing `--version` command line flag to binary. For example:
```
$ ./vmalert-prod --version
vmalert-20200730-173332-tags-v1.39.2-0-ge7959094f
```
