### ISSUE TITLE
metrics loss of vmcluster

### ISSUE THREAD

**Issue by gz3i** [VictoriaMetrics/VictoriaMetrics#6734]
### Describe the bug

vmagent can collect the discovered target normally, but after the target is written to vminsert remotely, the indicator cannot be found in vmselect. The parameters have been checked, the cluster service and collector are normal, and no special error is reported in the service log. Here is my cluster configuration and the configuration of vmagent:

vmcluster.yaml
```yaml
apiVersion: operator.victoriametrics.com/v1beta1
kind: VMCluster
metadata:
  name: vmcluster
  namespace: vmoperator
spec:
  replicationFactor: 1
  retentionPeriod: "90d"
  vmstorage:
    replicaCount: 1
    resources:
      requests:
        cpu: '1'
        memory: '2000Mi'
      limits:
        cpu: '2'
        memory: '4000Mi'
    image:
      repository: victoriametrics/vmstorage
      tag: v1.101.0-cluster
      pullPolicy: IfNotPresent
    storage:
      volumeClaimTemplate:
          spec:
            accessModes:
              - ReadWriteOnce
            resources:
              requests:
                storage: 300G
            storageClassName: hdd
    storageDataPath: /data/vm-data
  vmselect:
    replicaCount: 1
    resources:
      requests:
        cpu: '1'
        memory: '1000Mi'
      limits:
        cpu: '2'
        memory: '2000Mi'
    image:
      repository: victoriametrics/vmselect
      tag: v1.101.0-cluster
      pullPolicy: IfNotPresent
    cacheMountPath: /cache
    storage:
      volumeClaimTemplate:
          spec:
            accessModes:
              - ReadWriteOnce
            resources:
              requests:
                storage: 300G
            storageClassName: hdd
  vminsert:
    replicaCount: 2
    resources:
      requests:
        cpu: '1'
        memory: '1024Mi'
      limits:
        cpu: '2'
        memory: '2048Mi'
    image:
      repository: victoriametrics/vminsert
      tag: v1.101.0-cluster
      pullPolicy: IfNotPresent
    extraArgs:
      maxLabelsPerTimeseries: "2000"
```
vmagent.yaml
```yaml
apiVersion: operator.victoriametrics.com/v1beta1
kind: VMAgent
metadata:
  name: vmagent
  namespace: vmoperator
spec:
  scrapeInterval: 30s
  externalLabels:
    cluster: test
  serviceScrapeNamespaceSelector: {}
  podScrapeNamespaceSelector: {}
  podScrapeSelector: {}
  serviceScrapeSelector: {}
  nodeScrapeSelector: {}
  nodeScrapeNamespaceSelector: {}
  staticScrapeSelector: {}
  staticScrapeNamespaceSelector: {}
  replicaCount: 1
  resources:
    requests:
      cpu: '0.5'
      memory: '512Mi'
    limits:
      cpu: '2'
      memory: '2048Mi'
  extraArgs:
    promscrape.maxDroppedTargets: '50000'
    promscrape.maxScrapeSize: "1677721600"
  remoteWrite: 
    - url: "https://xxxxx/insert/0/prometheus/api/v1/write"   # 数据写入的地址
  remoteWriteSettings:
    tmpDataPath: "/tmp/vmagent-remotewrite-data"
```

### To Reproduce

![image](https://github.com/user-attachments/assets/5199265a-b874-4556-a964-4b4006a99523)
![image](https://github.com/user-attachments/assets/9b11d706-d745-4574-a7b8-df6f42a477aa)
![image](https://github.com/user-attachments/assets/11b48e80-e9b9-46a6-81f9-7c4a1c52352d)

### Version

vminsert-20240425-150412-tags-v1.101.0-cluster-0-g310d100ed
vmselect-20240425-150446-tags-v1.101.0-cluster-0-g310d100ed
vmstorage-20240425-150523-tags-v1.101.0-cluster-0-g310d100ed
vmagent-20240425-145801-tags-v1.101.0-0-g5334f0c2c

### Logs

vminsert:
![image](https://github.com/user-attachments/assets/14d8fd75-e7d0-4c45-977e-f5b3c9b646f0)

vmselect:
![image](https://github.com/user-attachments/assets/8a8c7ec1-1a27-4a97-954a-d86e7291ca4b)

vmstorage:
![image](https://github.com/user-attachments/assets/51af3c48-2657-4158-ab85-278c19452968)

vmagent:
![image](https://github.com/user-attachments/assets/c86ef09e-7374-4839-ae33-4130dc68e43d)

### Used command-line flags

vmagent:
```
/vmagent-prod-httpListenAddr=:8429-promscrape.config=/etc/vmagent/config_out/vmagent.env.yaml-promscrape.maxDroppedTargets=50000-promscrape.maxScrapeSize=1677721600-remoteWrite.maxDiskUsagePerURL=1073741824-remoteWrite.tmpDataPath=/tmp/vmagent-remotewrite-data-remoteWrite.url=https://xxxxx/insert/0/prometheus/api/v1/write
```

vmstorage:
```
/vmstorage-prod-httpListenAddr=:8482-retentionPeriod=90d-storageDataPath=/data/vm-data-vminsertAddr=:8400-vmselectAddr=:8401/
```

vmselect:
```
/vmselect-prod-cacheDataPath=/cache-httpListenAddr=:8481-selectNode=vmselect-vmcluster-0.vmselect-vmcluster.vmoperator:8481-storageNode=vmstorage-vmcluster-0.vmstorage-vmcluster.vmoperator:8401/
```
vminsert:
```
/vminsert-prod-httpListenAddr=:8480-maxLabelsPerTimeseries=2000-replicationFactor=1-storageNode=vmstorage-vmcluster-0.vmstorage-vmcluster.vmoperator:8400/
```
### Additional information

Online environment, very urgent，Hope for a quick response
