### ISSUE TITLE
Running victoriametric and vmagent as nomad job

### ISSUE THREAD

**Issue by Gautam3AI** [VictoriaMetrics/VictoriaMetrics#6778]
### Is your question request related to a specific component?

Victoriametric, vmagnet, nomad

### Describe the question in detail

I am trying to run victoriametric job and vmagent as a single job and using nomad's lifecycle stanza to execute both tasks (victoriametric & vmagent) in order.

```bash
job "combined" {
  datacenters = ["dc1"]
  type        = "service"

  group "victoriametrics" {
    count = 1

    volume "victoriametrics" {
      type      = "host"
      read_only = false
      source    = "victoriametrics"
    }

    network {
      mode = "bridge"

      port "vicky-http" {
        static = 8428
        to = 8428
      }
      port "vmagent-http" {
        static = 8429
        to = 8429
      }
    }

    task "victoriametrics" {
      lifecycle{
        hook = "prestart"
        sidecar = true
      }

      driver = "docker"

      service {
        name     = "vicky-web"
        provider = "nomad"
        port     = "vicky-http"
        tags = [
          "victoriametrics",
          "web",
          "traefik.enable=true",
          "traefik.http.routers.victoriametric-http.rule=PathPrefix(`/victoria-metric`)",
          "traefik.http.routers.victoriametric-http.priority=10"
        ]
      }

      volume_mount {
        volume      = "victoriametrics"
        destination = "/storage"
        read_only   = false
      }

      config {
        image = "victoriametrics/victoria-metrics:latest"
        ports = ["vicky-http"]
        args = [
          "--storageDataPath=/storage",
          "--retentionPeriod=1d",
          "--httpListenAddr=:8428"
        ]
      }

      resources {
        cpu    = 256
        memory = 300
      }
    }

    task "vmagent" {
      driver = "docker"

      config {
        image = "victoriametrics/vmagent:latest"
        args = [
          "--promscrape.config=$${NOMAD_TASK_DIR}/prometheus.yml",
          "--remoteWrite.url=${VICTORIAMETRICS_ADDR}"
        ]
      }

      template {
        data        = file(abspath("./../configs/prometheus.tpl.yml"))
        destination = "$${NOMAD_TASK_DIR}/prometheus.yml"
        change_mode = "restart"
      }

      template {
        data = <<EOF
{{- range nomadService "vicky-web" }}
  VICTORIAMETRICS_ADDR=http://{{ .Address }}:{{ .Port }}/api/v1/write
{{ end -}}
EOF

        destination = "local/env"
        env         = true
      }


      resources {
        cpu    = 256
        memory = 300
      }
    }
  }
}
```

prometheus.tpl.yml
```yaml
global:
  scrape_interval: 10s
  external_labels:
    env: "dev"
    cluster: "local"

scrape_configs:
  - job_name: "nomad-agent"
    metrics_path: "/v1/metrics?format=prometheus"
    static_configs:
      - targets: ["http://<private-ip-address>:4646"]
        labels:
          role: agent
    relabel_configs:
      - source_labels: [__address__]
        regex: "([^:]+):.+"
        target_label: "hostname"
        replacement: "nomad-agent-$1"
```

But I am getting an error in task vmagnet
```bash
2024-08-06T16:04:50.693Z	warn	VictoriaMetrics/app/vmagent/remotewrite/client.go:416	couldn't send a block with size 20907 bytes to "1:secret-url": Post "http://192.168.1.6:8428/api/v1/write": dial tcp4 192.168.1.6:8428: i/o timeout; re-sending the block in 8.283 seconds
```
I tried setting --remoteWrite.sendTimeout=2m in the arg command of the vmagnet task but I am getting same thing still.

**It works fine when victoriametric and vmagnet are running as seperate jobs but vmagnet throws above error when jobs run together.**
Any help how to fix this.

### Troubleshooting docs

- [x] General - https://docs.victoriametrics.com/troubleshooting/
- [x] vmagent - https://docs.victoriametrics.com/vmagent/#troubleshooting
- [x] vmalert - https://docs.victoriametrics.com/vmalert/#troubleshooting
