### ISSUE TITLE
azure_sd_configs error: cannot list virtual machines: unexpected nextLink host

### ISSUE THREAD

**Issue by zoltan-keller** [VictoriaMetrics/VictoriaMetrics#6784]
### Describe the bug

Out of 4 subscriptions setup identically, in two azure SD fails with below error message. VMagent is running in gardener managed k8s cluster and has access to all subscriptions configured.

### To Reproduce

Use following scrape config:

```
  - job_name: 'azure-sd'
    scheme: https
    tls_config:
      ca_file: /etc/ssl/certs/ca.crt
    follow_redirects: false
    basic_auth:
      username: xxxx
      password: xxxx
    azure_sd_configs:
        - client_id: xxxxx-xxxxx-xxxx
          client_secret: xxxxx-xxxxx-xxxx
          subscription_id: xxxx-xxxx-xxxx
          tenant_id: xxxxx-xxxxx-xxxx
          resource_group: rg-test1
```

### Version

```
~ $ ./vmagent-prod --version
vmagent-20240425-145801-tags-v1.101.0-0-g5334f0c2c
```

### Logs

```
{"ts":"2024-08-08T15:11:26.442Z","level":"error","caller":"VictoriaMetrics/lib/promscrape/config.go:774","msg":"skipping azure_sd_config targets for job_name=azure-sd because of error: cannot list virtual machines: unexpected nextLink host \"management.azure.com\", expecting \"https://management.azure.com\""}
```

### Used command-line flags

```
  httpListenAddr=:8429
  remoteWrite.tlsCAFile="/etc/ssl/certs/ca.crt"
  promscrape.config=/config/scrape.yml
  promscrape.suppressScrapeErrors
  promscrape.suppressDuplicateScrapeTargetErrors
  remoteWrite.showURL
  remoteWrite.tmpDataPath=/tmpData
  remoteWrite.basicAuth.username=xxxx
  remoteWrite.basicAuth.passwordFile=yyyy
  remoteWrite.url=https://xxxxx
  promscrape.maxScrapeSize: "70MiB"
  remoteWrite.maxDiskUsagePerURL: "5GiB"
  envflag.enable: "true"
  envflag.prefix: VM_
  loggerFormat: json
  promscrape.openstackSDCheckInterval: "10m"
  promscrape.httpSDCheckInterval: "10m"
  promscrape.noStaleMarkers: "true"          
```
