### ISSUE TITLE
Can't scrape metrics with consul SD

### ISSUE THREAD

**Issue by bmgeek** [VictoriaMetrics/VictoriaMetrics#6852]
### Is your question request related to a specific component?

vmagent

### Describe the question in detail

We move from Prometheus to VM and have a some problems with scrape metrics from consul.

Our working scrapeconfig in prometheus:

```
- job_name: 'our-metrics'
  metrics_path: '/actuator/prometheus'
  consul_sd_configs:
      - server: 'consul-1:8500'
        token: 'token'
  basic_auth:
      username: 'admin'   
      password: 'password'
```

I trying to put this config to VMAgent inlineScrapeConfig and VMScrapeConfig, but VMAgent doesn't want to find / scrape metrics. We have 0 searched services in the targets.

VMAgent inlineScrapeConfig:

```
- job_name: 'our-metrics'
  metrics_path: '/actuator/prometheus'
  consul_sd_configs:
      - server: 'consul-1:8500'
        token: 'token'
        datacenter: 'dc'
  basic_auth:
      username: 'admin'   
      password: 'password'
```

VMScrapeConfig (i have two variants):

```
- job_name: scrapeConfig/victoriametrics/our-test
  scrape_interval: 1m0s
  scrape_timeout: 15s
  metrics_path: /actuator/prometheus
  basic_auth:
    username: admin
    password: <secret>
  authorization:
    type: X-Consul-Token
    credentials: <secret>
  consul_sd_configs:
  - server: consul-1:8500
    token: null
    datacenter: dc
    username: ""
    password: null

- job_name: our-metrics
  metrics_path: /actuator/prometheus
  basic_auth:
    username: admin
    password: <secret>
  consul_sd_configs:
  - server: consul-1:8500
    token: <secret>
    datacenter: dc
    scheme: http
    username: ""
    password: null
```

And I tried different configs, but already I have 0 targets from consul.

Curl request for take a services:

`curl http://consul:8500/v1/catalog/services -H "X-Consul-Token: token"`

### Troubleshooting docs

- [X] General - https://docs.victoriametrics.com/troubleshooting/
- [X] vmagent - https://docs.victoriametrics.com/vmagent/#troubleshooting
- [X] vmalert - https://docs.victoriametrics.com/vmalert/#troubleshooting

**Comment by Amper** [comment]
@bmgeek do you have any errors in vmagent logs?

**Comment by bmgeek** [comment]
> @bmgeek do you have any errors in vmagent logs?

No =( I have only this message:

`started Consul service watcher for "http://consul:8500"`

I'm looking at the code and don't understand why I got errors if I didn't set a **datacenter** parameter:

`skipping consul_sd_config targets for job_name=scrapeConfig/victoriametrics/our-test because of error: cannot get API config: cannot obtain consul datacenter: cannot query consul agent info: unexpected status code returned from "http://consul:8500/v1/agent/self": 403; expecting 200; response body: "Permission denied"`

But if **datacenter** is set then OK.

If I do a curl request then I get OK response:

`{"Config":{"Datacenter":"dev","NodeName":"consul","NodeID":"0a6cc7e9-5daa-d4c8...`

I'm looking at the code and parse should happen =) - https://github.com/VictoriaMetrics/VictoriaMetrics/blob/master/lib/promscrape/discovery/consul/api.go#L150

**Comment by Amper** [comment]
> I'm looking at the code and don't understand why I got errors if I didn't set a datacenter parameter:

If the datacenter isn't specified, then it is read it from API `/v1/agent/self`, but looks like your account doesn't have permission `agent:read`.

**Comment by bmgeek** [comment]
Perhaps I’m throwing the key wrong?
I tried different variants:

```
kind: VMScrapeConfig
spec:
  bearer_token_secret::
    key: token
    name: consul-sd
  consulSDConfigs:
    ...

kind: VMScrapeConfig
spec:
  consulSDConfigs:
    - server: consul:8500
      tokenRef:
        name: consul-sd
        key: token

kind: VMAgent
spec:
  inlineScrapeConfig: |
      consul_sd_configs:
      - server: consul:8500
         token: token
```

I have token with all privileges
