### ISSUE TITLE
VMAgent can't parse valid Prometheus config

### ISSUE THREAD

**Issue by paradisfm** [VictoriaMetrics/VictoriaMetrics#6860]
### Describe the bug

 Trying to use Blackbox Exporter in order to do HTTP and gRPC probes on pods in a given cluster. However, despite my module configuration appearing correct, I receive errors that the vmagent "cannot unmarshal Prometheus line [x]" for any given line in the configuration - there's an "unparsed tail left after parsing float64 from [value]. In addition, for lines like modules: , http_2xx: , and grpc: , it wants a value there for some reason. I don't see any reason in the code why this would be the case. Please look into this. 

### To Reproduce

```
modules:
      http_2xx:
        prober: http
        timeout: 70s
        http:
          valid_http_versions: 
          - HTTP/1.0
          - HTTP/1.1
          - HTTP/2.0
          valid_status_codes: 
          - 200
          - 400
          - 401
          - 403
          - 404
          - 504
          fail_if_ssl: false
          method: GET
          follow_redirects: true
          preferred_ip_protocol: ip4
          tls_config:
            ca_file: /etc/ssl/certs/blackbox_http/ca.crt
            insecure_skip_verify: true
      grpc:
        prober: grpc
        timeout: 70s
        grpc:
          tls: true
          preferred_ip_protocol: ip4
          ip_protocol_fallback: true
          tls_config:
            ca_file: /etc/ssl/certs/blackbox_http/ca.crt
            insecure_skip_verify: true
```

### Version

v1.95.1

### Screenshots

![Screenshot 2024-08-21 at 4 09 52 PM](https://github.com/user-attachments/assets/974d445b-b0fb-4dec-be55-81af186cde9d)

**Comment by hagen1778** [comment]
Hey @paradisfm!
Looks like you're trying to use [blackbox-exporter config](https://github.com/prometheus/blackbox_exporter/blob/master/CONFIGURATION.md) as [scrape config](https://prometheus.io/docs/prometheus/latest/configuration/configuration/). 
vmagent doesn't support Blackbox configuration and doesn't provide functionality like blackbox exporter. If you want to **scrape** blackbox exporter with vmagent then you need to configure vmagent with [Prometheus config](https://github.com/prometheus/blackbox_exporter?tab=readme-ov-file#prometheus-configuration).

**Comment by f41gh7** [comment]
You have invalid query param - `debug: "true"`.  Remove it and configuration will work as expected.

 Enabled debug returns probe debug instead of metrics response.

**Comment by f41gh7** [comment]
related article https://www.robustperception.io/debugging-blackbox-exporter-failures/

**Comment by paradisfm** [comment]
Sure, I have the below TLS configuration (I removed it previously because it didn't work, but tried again using mounted files rather than a secret)
```
  podMetricsEndpoints:
    tlsConfig:
      caFile: /etc/ssl/certs/ca.crt
      certFile: /etc/ssl/certs/tls.crt
      keyFile: /etc/ssl/certs/tls.key
```
The VMAgent returns logs of this form: `error when scraping https://blackbox-exporter-prometheus-blackbox-exporter.victoria-metrics.svc.cluster.local:9115/probe?module=http_2xx&target=[target]:
dial tcp4 x.x.x.x:9115: connect: connection refused`

On the Blackbox side, it returns EOF for each probe.
