### ISSUE TITLE
Possible regression when using metric_relabel_configs in versions > victoriametrics/vmagent:v1.99.0

### ISSUE THREAD

**Issue by crafty-ua** [VictoriaMetrics/VictoriaMetrics#6911]
### Describe the bug

Noticed that if vmagent gets stuck in reading config loop(?) while trying to load config that includes "metric_relabel_configs" in job definitions. 

### To Reproduce

Define a consul_sd_configs job that utilizes metric_relabel_configs config option. That should cause vmagent process to get into some kind of infinite loop while reading the config file
```
# 8< -----
    consul_sd_configs:
      - datacenter: 'default'
        server: 'consul.service.dyn.local:8501'
        scheme: 'https'
        tags:
          - prometheus.scraper=vm
          - prometheus.pool=${instance.dc}
          - prometheus.scrape_scheme=${scheme}
          - prometheus.scrape_interval=${interval}

    relabel_configs:
      - target_label: '__scheme__'
        replacement: '${scheme}'
    metric_relabel_configs: []
 ```

### Version

/ # ./vmagent-prod --version
vmagent-20240301-013655-tags-v1.99.0-0-g9cd4b053

### Logs

24-08-29T17:20:49.542Z	info	VictoriaMetrics/lib/persistentqueue/fastqueue.go:66	opened fast persistent queue at "vmagent-remotewrite-data/persistent-queue/1_740D3DF6745F8423" with maxInmemoryBlocks=644, it contains 0 pending bytes
2024-08-29T17:20:49.561Z	info	VictoriaMetrics/app/vmagent/remotewrite/client.go:166	the remote storage at "1:secret-url" doesn't support VictoriaMetrics remote write protocol. Switching to Prometheus remote write protocol. See https://docs.victoriametrics.com/vmagent.html#victoriametrics-remote-write-protocol
2024-08-29T17:20:49.561Z	info	VictoriaMetrics/app/vmagent/remotewrite/client.go:202	initialized client for -remoteWrite.url="1:secret-url"
2024-08-29T17:20:49.561Z	info	VictoriaMetrics/app/vmagent/main.go:152	started vmagent in 0.023 seconds
2024-08-29T17:20:49.561Z	info	VictoriaMetrics/lib/httpserver/httpserver.go:118	starting server at http://127.0.0.1:25992/
2024-08-29T17:20:49.561Z	info	VictoriaMetrics/lib/httpserver/httpserver.go:119	pprof handlers are exposed at http://127.0.0.1:25992/debug/pprof/
2024-08-29T17:20:49.561Z	info	VictoriaMetrics/lib/promscrape/scraper.go:113	reading scrape configs from "/local/prometheus.yml"
# No output after this line combined with max CPU load of docker container
