### ISSUE TITLE
Metrics data is getting dropped at vminsert when we send from Opentelemtry

### ISSUE THREAD

**Issue by Shindek77** [VictoriaMetrics/VictoriaMetrics#6939]
### Is your question request related to a specific component?

vminsert

### Describe the question in detail

Actually we are sending metrics from Opentelemetry to VictoriaMetrics using pipelines as follow.
But few metrics are getting dropped at vminsert with below Errors.

Please help what is issue behind it and we can fix it as need it urgently.
```
exporters:
  prometheusremotewrite/vm-tenant-1400:
    endpoint: http://victoria-metrics-cluster-vminsert.metrics-ns.svc.cluster.local:8480/insert/1400/prometheus
    resource_to_telemetry_conversion:
      enabled: true
    tls:
      insecure: true
pipelines:
  metrics/tenant-1400:
    exporters:
    - prometheusremotewrite/vm-tenant-1400
    processors:
    - batch
    receivers:
    - forward/eventhub
```
    
Errors:
Vminsert logs: 
{"ts":"2024-09-04T09:26:14.942Z","level":"warn","caller":"VictoriaMetrics/app/vminsert/main.go:253","msg":"remoteAddr: \"127.0.0.6:51309\"; requestURI: /insert/1400/prometheus; cannot read compressed request in 18 seconds: unexpected EOF"}
{"ts":"2024-09-04T09:26:14.943Z","level":"warn","caller":"VictoriaMetrics/app/vminsert/main.go:253","msg":"remoteAddr: \"127.0.0.6:41425\"; requestURI: /insert/1400/prometheus; cannot read compressed request in 18 seconds: unexpected EOF"}

On opentelemetry logs:
2024-09-05T04:24:30.758Z	error	exporterhelper/queue_sender.go:101	Exporting failed. Dropping data.	{"kind": "exporter", "data_type": "metrics", "name": "prometheusremotewrite/vm-tenant-1400", "error": "Permanent error: Permanent error: context deadline exceeded; Permanent error: Permanent error: context deadline exceeded; Permanent error: Permanent error: context deadline exceeded; Permanent error: Permanent error: context deadline exceeded; Permanent error: Permanent error: context deadline exceeded; Permanent error: Permanent error: context deadline exceeded; Permanent error: Permanent error: context deadline exceeded; Permanent error: Permanent error: context deadline exceeded", "errorCauses": [{"error": "Permanent error: Permanent error: context deadline exceeded"}, {"error": "Permanent error: Permanent error: context deadline exceeded"}, {"error": "Permanent error: Permanent error: context deadline exceeded"}, {"error": "Permanent error: Permanent error: context deadline exceeded"}, {"error": "Permanent error: Permanent error: context deadline exceeded"}, {"error": "Permanent error: Permanent error: context deadline exceeded"}, {"error": "Permanent error: Permanent error: context deadline exceeded"}, {"error": "Permanent error: Permanent error: context deadline exceeded"}], "dropped_items": 5805}
go.opentelemetry.io/collector/exporter/exporterhelper.newQueueSender.func1
	go.opentelemetry.io/collector/exporter@v0.102.1/exporterhelper/queue_sender.go:101
go.opentelemetry.io/collector/exporter/internal/queue.(*boundedMemoryQueue[...]).Consume
	go.opentelemetry.io/collector/exporter@v0.102.1/internal/queue/bounded_memory_queue.go:52
go.opentelemetry.io/collector/exporter/internal/queue.(*Consumers[...]).Start.func1
	go.opentelemetry.io/collector/exporter@v0.102.1/internal/queue/consumers.go:43

### Troubleshooting docs

- [X] General - https://docs.victoriametrics.com/troubleshooting/
- [X] vmagent - https://docs.victoriametrics.com/vmagent/#troubleshooting
- [X] vmalert - https://docs.victoriametrics.com/vmalert/#troubleshooting
