### ISSUE TITLE
Victorialogs: searching keyword inside ansi color wrapper is not return as expected

### ISSUE THREAD

**Issue by hieuhtr** [VictoriaMetrics/VictoriaMetrics#6950]
### Describe the bug

This kind of filter sometime return value, but sometime return nothing
```
_stream:{environment="production", container_name="api"} "DEBUG"
_stream:{environment="production", container_name="api"} "INFO"
```

By using `~`, it's always working, but search with `~` is take more time
```
_stream:{environment="production", container_name="api"} ~"DEBUG"
_stream:{environment="production", container_name="api"} ~"INFO"
```

Is there any different between `\u001b[32mDEBUG\u001b[0;39m` and `\u001b[32m INFO\u001b[0;39m` ?

### Search with DEBUG
<img width="609" alt="Screenshot 2024-09-06 at 10 55 16" src="https://github.com/user-attachments/assets/d7928e2a-a915-431a-a096-d0fe9ae10dd4">

### Search with INFO
<img width="619" alt="Screenshot 2024-09-06 at 11 14 27" src="https://github.com/user-attachments/assets/1fab145f-a7c3-4671-9136-a06333394702">

### To Reproduce

Raw log from output JSON
```
"_msg": "\u001b[2m2024-09-06 04:02:21.373\u001b[0;39m \u001b[32mDEBUG\u001b[0;39m \u001b[2muser: uri:\u001b[0;39m \u001b[2m[ XNIO-2 task-16]\u001b[0;39m \u001b[36m.p.CustomUserDetailsByNameServiceWrapper\u001b[0;39m .....
```

```
"_msg": "\u001b[2m2024-09-05 23:15:12.447\u001b[0;39m \u001b[32m INFO\u001b[0;39m \u001b[2muser: uri:\u001b[0;39m \u001b[2m[    uaa-task-51]\u001b[0;39m \u001b[36mc.l.uaa.user.AccountService             \u001b[0;39m \u001b[2m:\u001b[0;39m Reset failed password attempts for user admin@gmail.com"
```

### Version

```
image: docker.io/victoriametrics/victoria-logs:v0.28.0-victorialogs
    restart: always
    command:
      - "--storageDataPath=/vlogs"
      - "--retentionPeriod=1y"
      - "--httpListenAddr=:9428"
      - "--search.maxQueryDuration=300s"
```
