### ISSUE TITLE
Username should not be mandatory when using API key

### ISSUE THREAD

**Issue by Nemric** [VictoriaMetrics/VictoriaMetrics#6956]
### Is your feature request related to a problem? Please describe

In a vmagent job config I have to add a username arg :
``` yaml
    basic_auth:
      username: fakeusername
      password: xxxxxxxxxxxxxxxx
 ```

### Describe the solution you'd like

I'd like to only use password arg without error :
`skipping `scrape_config` for job_name=JOBNAME because of error: cannot parse auth config for `job_name` "JOBNAME": missing `username` and `username_file` in `basic_auth` section`
``` yaml
    basic_auth:
      password: xxxxxxxxxxxxxxxx
 ```
 
 Of course, it works well with a fake username, but it looks bad in config files as username is not used ^^

**Comment by tiny-pangolin** [comment]
Is there a reason for using http basic instead of a bearer token if you are just using a password to authenticate to VMAuth? 

https://docs.victoriametrics.com/vmauth/#bearer-token-auth-proxy

**Comment by Nemric** [comment]
Hi, Yes, I did follow this Docs https://github.com/louislam/uptime-kuma/wiki/API-Keys#authenticating-using-an-api-key
I didn't give a try to bearer token ...

**Comment by freshpr** [comment]
Workaround for other people stumbling on this. Just make username a space. Seems to work for me
    basic_auth:
      username: ' '
      password: 'mytoken'

**Comment by makasim** [comment]
Seems like Prometheus supports basic_auth with empty username.  I tried config:

```
scrape_configs:
- job_name: gh10189
  basic_auth:
    username: ""
    password: "foobar"
  static_configs:
  - targets:
    - 127.0.0.1:8080
```

and got only pass in auth header:

```
--- request ---
GET /metrics HTTP/1.1
Host: 127.0.0.1:8080
Accept: application/openmetrics-text;version=1.0.0;escaping=allow-utf-8;q=0.6,application/openmetrics-text;version=0.0.1;q=0.5,text/plain;version=1.0.0;escaping=allow-utf-8;q=0.4,text/plain;version=0.0.4;q=0.3,*/*;q=0.2
Accept-Encoding: gzip
Authorization: Basic OmZvb2Jhcg==
User-Agent: Prometheus/3.10.0
X-Prometheus-Scrape-Timeout-Seconds: 1
```

Such behavior should be supported by VM. Marking the issue as `prom-compatiblity`.
