### ISSUE TITLE
Add global relabeling_configs for scrapping 

### ISSUE THREAD

**Issue by f41gh7** [VictoriaMetrics/VictoriaMetrics#6966]
### Is your feature request related to a problem? Please describe

 It'd be great to have an option to define global target discovery [relabeling](https://docs.victoriametrics.com/vmagent/#relabeling) configuration. 

 It should be attached to each scrape configuration job and to be executed before relabeling config defined at job level.

### Describe the solution you'd like

 Configuration example:

```yaml
# config.yaml
# ./bin/vmagent --promscrape.config=config.yaml
global:
  relabel_configs:
    - if: '{__meta_kubernetes_pod_label_component!=""}'
       action: labeldrop
       regex: "foo_bar_.*"
scrape_configs:
- job_name: k8s-pods
  kubernetes_sd_configs:
  - role: pod
     relabel_configs:
     - source_labels: [__meta_kubernetes_pod_label_component]
       regex: foo_bar_.*
       target_label: should_not_exist
```

### Describe alternatives you've considered

 As workaround, it's possible to implement that with any templating tool, like helm or ansible jinja2.
