### ISSUE TITLE
vmalert-tool-prod almost always takes at least 3 seconds.

### ISSUE THREAD

**Issue by shric** [VictoriaMetrics/VictoriaMetrics#6970]
### Describe the bug

When I run `vmalert-tool-prod unittest --files foo.alerts.test.yml`, it almost always takes a little over 3 seconds.

I think this is due to a race condition while waiting for the http server to be ready at https://github.com/VictoriaMetrics/VictoriaMetrics/blob/master/app/vmalert-tool/unittest/unittest.go#L253

3 seconds is a very long time if we're running unit tests across dozens or hundreds of alerting rule files.

Can it be made to either spin faster on checking if the http server is ready, or use some kind of waiting/signalling logic.

### To Reproduce

`foo.alerts.yml`:
```
---
groups:
  - name: "a"
    rules:
      - alert: "d"
        expr: "up == 0"
        for: "1m"
```
`foo.alerts.test.yml`:
```
---
rule_files:
  - "foo.alerts.yml"
evaluation_interval: "1m"
tests:
  - interval: "1m"
    input_series:
      - series: 'up{job="foo"}'
        values: "0 1 0"
    alert_rule_test:
      - eval_time: "3m"
        groupname: "a"
        alertname: "d"
        exp_alerts:
          - exp_labels:
              job: "foo"
```
Then:
```
vmalert-tool-prod unittest --files foo.alerts.test.yml
Unit Testing:  foo.alerts.test.yml
  SUCCESS
2024/09/10 13:32:46 Total time: 3.114143469s
```
The total time should not be more than 3 seconds, ideally.

### Version

```
$ ~/vmalert-tool-prod --version
vmalert-tool version vmalert-tool-20240828-135301-tags-v1.103.0-0-g5aeb759df9
2024/09/10 17:47:45 Total time: 538.869µs
```

### Logs

N/A, see "to reproduce"

### Screenshots

N/A, see "to reproduce"

### Used command-line flags

```
vmalert-tool-prod unittest --files foo.alerts.test.yml
```
