### ISSUE TITLE
Misleading documentation for calculating disk space for persistence queue

### ISSUE THREAD

**Issue by leandregagnonlewis** [VictoriaMetrics/VictoriaMetrics#7055]
### Describe the bug

I have followed the steps described in [this section of the documentation ](https://docs.victoriametrics.com/vmagent/index.html#calculating-disk-space-for-persistence-queue) to calculate the size needed for the persistent queue in VMAgents during one hour. I used this query specifically:
```
sum(rate(vmagent_remotewrite_bytes_sent_total[1h])) by(instance,url) * 1h / 1GB
```
In my case the queue should need approximately 1 GB. Then I have tested it and the results are not what I expected. The 1GB queue was filled in less than 30 minutes. 

I guess this could be explained by that there is compression applied to the data before writing it to the remote storage. But then this section of the documentation should be removed, or even better if you could provide us with a correct way for calculating the size needed by taking account that the queued data is uncompressed.

### To Reproduce

Upated my VMAgent config by adding those wrong destination urls
```
vmagent:
  spec:
    remoteWrite:
    - url: ...  # first three urls are real VM remote storage
    - url: ...
    - url: ...
    - url: https://1.wrong.url
    - url: https://2.wrong.url
 
    extraArgs:
      # syntax: "s1,s2,s3,...,sn", should be multiples of 500MB, 0 means unlimited, order is the same as remoteWrite URLs
      remoteWrite.maxDiskUsagePerURL: "0,0,0,500MB,1GB"
```

### Version

victoriametrics/operator:v0.46.4

### Screenshots

Estimated queue size using documented query: 
![image](https://github.com/user-attachments/assets/c4f7bd4d-1655-436c-a0da-b9a3ff11edd0)

Queue size graph. Test deployment was made at 15:10. Yellow line is for a 1GB queue. green line is for a 500MB queue. Take into account that I have 3 replicas of VMAgents so actual queue size is obtained by dividing by 3.
![image](https://github.com/user-attachments/assets/745e45ad-e9f3-4c8d-99ff-afdea0775ec8)
