### ISSUE TITLE
custom dedupInterval

### ISSUE THREAD

**Issue by chownxx** [VictoriaMetrics/VictoriaMetrics#7057]
### Is your question request related to a specific component?

VMAgent

### Describe the question in detail

Is t possible to apply custom dedupInterval for each remoteWrite target in a VMAgent resource in Kubernetes?

### Troubleshooting docs

- [ ] General - https://docs.victoriametrics.com/troubleshooting/
- [ ] vmagent - https://docs.victoriametrics.com/vmagent/#troubleshooting
- [ ] vmalert - https://docs.victoriametrics.com/vmalert/#troubleshooting

**Comment by AndrewChubatiuk** [comment]
hey @chownxx 
it can be set like this
```
apiVersion: operator.victoriametrics.com/v1beta1
kind: VMAgent
metadata:
  name: sample
spec:
  remoteWrite:
    - url: "http://url1.example.com:8429/api/v1/write"
       streamAggrConfig:
         dedupInterval: 2m
    - url: "http://url2.example.com:8429/api/v1/write"
       streamAggrConfig:
         dedupInterval: 4m
```
