### ISSUE TITLE
Can't understand how i can drop metrics

### ISSUE THREAD

**Issue by bmgeek** [VictoriaMetrics/VictoriaMetrics#7077]
### Is your question request related to a specific component?

vmagent

### Describe the question in detail

Hello!)

I have RabbitMQ in the k8s cluster and have a VMServiceScrape with spec:

```
spec:
  attach_metadata: {}
  endpoints:
    - attach_metadata: {}
      interval: 45s
      metricRelabelConfigs:
        - action: labeldrop
          regex: vhost
      path: >-
        /metrics/detailed?&family=queue_metrics&family=channel_queue_exchange_metrics&family=channel_exchange_metrics&family=queue_coarse_metrics
      port: metrics
  jobLabel: ''
  selector:
    matchLabels:
      app.kubernetes.io/instance: rabbitmq
      app.kubernetes.io/name: rabbitmq
```

I tried to drop metrics with relabelConfigs but I had failed. I tried different ways to reduce couple metrics. Example, I would like to drop this metric - **rabbitmq_detailed_queue_messages_ram**, I tried these expressions:

```
      relabelConfigs:
        - action: drop_metrics
          regex: rabbitmq_detailed_queue_messages_ram

      relabelConfigs:
        - action: drop
          source_labels: [__name__]
          regex: rabbitmq_detailed_queue_messages_ram

      relabelConfigs:
        - action: drop
          source_labels: [__name__]
          regex: ^rabbitmq_detailed_queue_messages_ram$

### This isn't working - any metric doesn't scrape
      relabelConfigs:
        - action: keep_metrics
          regex: first_metric|second_metric

      relabelConfigs:
         - if: '{__name__=~"rabbitmq_detailed_queue_messages_ram"}'
            action: drop
```

Also I tried to drop labels from target (in the relabelConfigs section) and I had failed too.
BUT! In the metricRelabelConfigs section all expr work good.

Also on the target-relabel-debug and metric-relabel-debug pages all are good.

I have last version v1.103.0

### Troubleshooting docs

- [X] General - https://docs.victoriametrics.com/troubleshooting/
- [X] vmagent - https://docs.victoriametrics.com/vmagent/#troubleshooting
- [X] vmalert - https://docs.victoriametrics.com/vmalert/#troubleshooting

**Comment by f41gh7** [comment]
Hello, 

 `metricRelabelConfigs` evaluates at metrics scapped from application. It's possible to drop `rabbitmq_detailed_queue_messages_ram` and other application with it.

`relabelConfigs`  evaluates only with service discovery labels ( aka `__meta_kubernetes_service...` and so on).

 For your case, you have to use `metricRelabelConfigs`. 

 Related docs https://www.robustperception.io/relabel_configs-vs-metric_relabel_configs/

**Comment by jiekun** [comment]
(Mistakenly labelled by @jiekun . Punishment served.)

I'm closing this issue as answered. Please feel free to re-open it if you have more question on relabeling.

**Comment by bmgeek** [comment]
> Hello,
> 
> `metricRelabelConfigs` evaluates at metrics scapped from application. It's possible to drop `rabbitmq_detailed_queue_messages_ram` and other application with it.
> 
> `relabelConfigs` evaluates only with service discovery labels ( aka `__meta_kubernetes_service...` and so on).
> 
> For your case, you have to use `metricRelabelConfigs`.
> 
> Related docs https://www.robustperception.io/relabel_configs-vs-metric_relabel_configs/

yep, but you have metric label - __name__=~"rabbitmq_detailed_queue_messages_ram"

**Comment by jiekun** [comment]
@bmgeek Hi. I can't get you by `but you have metric label ...`

```yaml
      ### This isn't working - any metric doesn't scrape
      relabelConfigs:
        - action: keep_metrics
          regex: first_metric|second_metric

      relabelConfigs:
         - if: '{__name__=~"rabbitmq_detailed_queue_messages_ram"}'
            action: drop
```

During service discovery, this label `__name__` is not exist yet. service discovery only collect labels like `__meta_kubernetes_service...`. No item carries the `__name__` label, so all service discovery target is dropped, and no metrics will be scraped.

**Comment by bmgeek** [comment]
So bad.
Thank you. I thought about it (

**Comment by Gakhramanzode** [comment]
@bmgeek you can use metricRelabelConfigs section https://docs.victoriametrics.com/operator/api/#relabelconfig like this:
```yaml
apiVersion: operator.victoriametrics.com/v1beta1
kind: VMServiceScrape
...
spec:
  endpoints:
  - honorLabels: true
    interval: 15s
    metricRelabelConfigs:
    - action: labeldrop
      if: '{__name__="http_request_duration_seconds"}'
      regex: (.*)
```
