### ISSUE TITLE
VMAgent authorization error

### ISSUE THREAD

**Issue by juliocleal14** [VictoriaMetrics/VictoriaMetrics#7089]
### Is your question request related to a specific component?

vmagent

### Describe the question in detail

We are using the vmagent in cluster mode in the `v1.100.1` and everything is working with 'authorization'.

When I try to update to `v1.102.0` or `v1.103.0` I start to receive this error:

```
Endpoint	State	Labels	Debug relabeling	Scrapes	Errors	Last Scrape	Duration	Last Scrape Size	Samples	Last error
http://<ip>:<port>/metrics (response)	DOWN	
{label_1="value_1", label_2="value_2"}
"http://<ip>:<port>/metrics": Get "http://<ip>:<port>/metrics": net/http: invalid header field value for "Authorization"
```

I use the 'bearer' configuration in the 'job' configuration.

My job configuration is:

```
- job_name: 'job-name'
    kubernetes_sd_configs:
    - role: pod
    scheme: https
    honor_labels: true
    sample_limit: 600000
    bearer_token_file: /path/bearer_token
    tls_config:
      insecure_skip_verify:  true
      cert_file: /path/cert.pem
      key_file: /path/key.pem
```

Did something change in these versions that I need to update my configuration?

I tried to find some change in the release notes but I could not.

### Troubleshooting docs

- [X] General - https://docs.victoriametrics.com/troubleshooting/
- [X] vmagent - https://docs.victoriametrics.com/vmagent/#troubleshooting
- [X] vmalert - https://docs.victoriametrics.com/vmalert/#troubleshooting
