### ISSUE TITLE
Staleness_interval for Streaming aggregation does not work corect?

### ISSUE THREAD

**Issue by mrsanuk** [VictoriaMetrics/VictoriaMetrics#7116]
### Is your question request related to a specific component?

vmagent

### Describe the question in detail

We have few types of job that generate metrics push it to vmagent with streaming aggregation and vmagent writes to the prometheus, one runs every 10 min, second once a hour. To avoid no data in prometheus we setted up staleness_interval. 
Our config:
```
      streamaggr.yml: |
        - match: 
          - report_counter
          interval: 2m
          outputs: ["total"]
          without: ["job"]
          staleness_interval: 70m
          keep_metric_names: true
          flush_on_shutdown: true
```
Problem only that first metric after vmgent start I can see only after staleness_interval, if it 70 min, 70 min will be no data in prometheus, if 15 min then 15 min no data,  if 1 day then 1 day nodata. After that everything works fine. Is it a bug or expected behavior?

### Troubleshooting docs

- [ ] General - https://docs.victoriametrics.com/troubleshooting/
- [X] vmagent - https://docs.victoriametrics.com/vmagent/#troubleshooting
- [ ] vmalert - https://docs.victoriametrics.com/vmalert/#troubleshooting
