### ISSUE TITLE
vmagent job dissapears when adding basic auth

### ISSUE THREAD

**Issue by freshpr** [VictoriaMetrics/VictoriaMetrics#7145]
### Describe the bug

When I add basic_auth to a job in prometheus config file and restart vmagent, it doesn't detect the job anymore.
    basic_auth:
      username: something
      password: something

### To Reproduce
```yaml
global:
  scrape_interval: 30s

scrape_configs:
  - job_name: 'test'
    static_configs:
      - targets: ['127.0.0.1:8080']
    basic_auth:
      username: something
      password: something
```

### Version

vmagent-20240214-141141-tags-v1.98.0-0-gbaaa88001
