### ISSUE TITLE
where to set " extraScrapeConfigs" in charts/victoria-metrics-k8s-stack values file

### ISSUE THREAD

**Issue by manju369** [VictoriaMetrics/VictoriaMetrics#7153]
### Is your question request related to a specific component?

On helm values of "charts/victoria-metrics-k8s-stack"

### Describe the question in detail

I am using VictoriaMetrics from past month with servicemonitors and podmonitors enabled, but we also want to monitor some external services like powerdns , which is emitting metrics at 'https://dummypowerdns.com/metrics'

I tried to set ` extraScrapeConfigs` under 'vmagent` and also at `vmagent.spec` section , but no luck yet. "powerdns" job_name is not getting listed in target section at all.

Any idea , why this could be. please help me on this

```yaml
 extraScrapeConfigs:
 - job_name: 'powerdns'
   static_configs:
   - targets: ["https://dummypowerdns.com/metrics"]
```

### Troubleshooting docs

- [X] General - https://docs.victoriametrics.com/troubleshooting/
- [X] vmagent - https://docs.victoriametrics.com/vmagent/#troubleshooting
- [ ] vmalert - https://docs.victoriametrics.com/vmalert/#troubleshooting
