### ISSUE TITLE
`streamAggr.config` don't work in vmagent chart?

### ISSUE THREAD

**Issue by XMingG99** [VictoriaMetrics/VictoriaMetrics#7239]
### Describe the bug

I had confided vmagent's helm chart like this:
```
remoteWrite:
- url: http://vmcluster-victoria-metrics-cluster-vminsert.obs.svc:8480/insert/0/prometheus
  streamAggr.config: 
   - match: 'test_metric'
      interval: 5s
      by: [instid]
      outputs: [max]
```

and when I deploy the chart, I got this in `vmagent-victoria-metrics-agent-rw` ConfigMap:
```
# Source: victoria-metrics-agent/templates/configmap.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: vmagent-victoria-metrics-agent-rw
  namespace: obs
  labels:
    helm.sh/chart: victoria-metrics-agent-0.14.0
    app.kubernetes.io/name: victoria-metrics-agent
    app.kubernetes.io/instance: vmagent
    app.kubernetes.io/version: "v1.104.0"
    app.kubernetes.io/managed-by: Helm
data: 
  0-streamAggr.config.yaml: |-
    - by:
      - instid
      interval: 5s
      match: test_metric
      outputs:
      - max
```

which pod is work fine, but I can't get aggregated metrics  in vmselect, even I can't get raw metrics in vmselect.

and I can't get any error in pod's log

by the way, other components is work fine, if I don't config aggregation rule, I can find raw metrics in vmselect

### To Reproduce

no

### Version

chart version:  0.14.0
vmagent image version: v1.104.0
