### ISSUE TITLE
Native sidecars (k8s 1.29 feature) are not discoverable

### ISSUE THREAD

**Issue by rifler** [VictoriaMetrics/VictoriaMetrics#7287]
### Describe the bug

Hello!
We run a bunch of microservices in eks under istio mesh (v1.20), each in separate namespace with label `istio-injection=enabled` and VictoriaMetricsStack in `vm-monitoring` namespace. To simplify, let's say there is one microservice called `nodejs-trivial` living in `nodejs-trivial-testing` k8s namespace (provided as deployment).

### Background about istio:
Istio injects `istio-proxy` container to each pod, via webhook afaik, under namespace with label `istio-injection=enabled`. This container exposes it's custom metrics (like `istio_requests_total` and others) at `http://[pod_ip]:15090/stats/prometheus`. Port has name `http-envoy-prom` in container's spec.

By and large it works fine, except istio can't be used with Jobs since it never finishes. There some awkward workarounds like explicitly calling istio's `/quitquitquit` endpoint at the end of main container's lifecycle.

### Native sidecars:
It was k8s limitation and fortunately k8s team introduced new feature called "native sidecars" or just "sidecars" afaik in 1.28 and it went to "beta" in 1.29 and was enabled in EKS 1.29. Technically it implies that such a sidecar goes not under `containers` but `initContainers` with special field `restartPolicy: Always` and remains running throughout pod's lifetime. Such sidecar must have startup and readiness probes and it affects pod's `Running` status.

Related links about sidecars:
- https://kubernetes.io/blog/2023/08/25/native-sidecar-containers/
- https://kubernetes.io/docs/concepts/workloads/pods/sidecar-containers/
- https://istio.io/latest/blog/2023/native-sidecars/

### The problem:
After enabling this feature in Istio via setting `ENABLE_NATIVE_SIDECARS=true` env variable in istiod deployment and restarting `nodejs-trivial` app deployment everything went as expected - `istio-proxy` was injected to `initContainers`, app was working and accepting requests and so on.
Except one thing - istio-proxy's metrics endpoint disappeared from VM's targets and now is not observable.

<details>
  <summary>Old pod spec (before `ENABLE_NATIVE_SIDECARS=true`)</summary>

```yaml
apiVersion: v1
kind: Pod
metadata:
  annotations:
    prometheus.io/path: /stats/prometheus
    prometheus.io/port: "15020"
    prometheus.io/scrape: "true"
  labels:
    app: nodejs-trivial
    env: testing
    security.istio.io/tlsMode: istio
    service.istio.io/canonical-name: nodejs-trivial
    service.istio.io/canonical-revision: latest
  name: nodejs-trivial-testing-f45f4dcc-4b9r4
  namespace: nodejs-trivial-testing
spec:
  containers:
    - name: istio-proxy
      image: istio/proxyv2:1.20.8
      imagePullPolicy: IfNotPresent
      args:
        - proxy
        - sidecar
        - --domain
        - $(POD_NAMESPACE).svc.cluster.local
        - --proxyLogLevel=warning
        - --proxyComponentLogLevel=misc:error
        - --log_output_level=default:info
      ports:
        - containerPort: 15090
          name: http-envoy-prom
          protocol: TCP
```
</details>

<details>
  <summary>Screenshot from https://agent-vm/targets before problem</summary>

![2024-10-17_20-04-11](https://github.com/user-attachments/assets/faef579f-02ac-4257-b159-ebb765d21a5a)
</details>

<details>
  <summary>New pod spec</summary>

```yaml
apiVersion: v1
kind: Pod
metadata:
  annotations:
    prometheus.io/path: /stats/prometheus
    prometheus.io/port: "15020"
    prometheus.io/scrape: "true"
  labels:
    app: nodejs-trivial
    env: testing
    security.istio.io/tlsMode: istio
    service.istio.io/canonical-name: nodejs-trivial
    service.istio.io/canonical-revision: latest
  name: nodejs-trivial-testing-d779965ff-jtrps
  namespace: nodejs-trivial-testing
spec:
  initContainers:
    - name: istio-proxy
      image: istio/proxyv2:1.20.8
      imagePullPolicy: IfNotPresent
      restartPolicy: Always
      args:
        - proxy
        - sidecar
        - --domain
        - $(POD_NAMESPACE).svc.cluster.local
        - --proxyLogLevel=warning
        - --proxyComponentLogLevel=misc:error
        - --log_output_level=default:info
      ports:
        - containerPort: 15090
          name: http-envoy-prom
          protocol: TCP
  containers: []
```
</details>

<details>
  <summary>Service in nodejs-trivial namespace (wasn't changed)</summary>

```yaml
apiVersion: v1
kind: Service
metadata:
  annotations:
    service.kubernetes.io/topology-mode: Auto
  labels:
    app: nodejs-trivial
    env: testing
  name: nodejs-trivial-service-testing
  namespace: nodejs-trivial-testing
spec:
  clusterIP: fdf3:9cd8:f41c::8572
  clusterIPs:
    - fdf3:9cd8:f41c::8572
  internalTrafficPolicy: Cluster
  ipFamilies:
    - IPv6
  ipFamilyPolicy: SingleStack
  ports:
    - name: http
      port: 80
      protocol: TCP
      targetPort: http
  selector:
    app: nodejs-trivial
  sessionAffinity: None
  type: ClusterIP
```
</details>

<details>
  <summary>ServiceMonitor in istio-system namespace</summary>

```yaml
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  labels:
    monitoring: istio-dataplane
    release: prometheus-stack
  name: prometheus-oper-istio-dataplane
  namespace: istio-system
spec:
  endpoints:
    - interval: 15s
      metricRelabelings:
        - action: keep
          regex: ^(istio_requests_total|istio_request_duration_milliseconds_bucket)$
          sourceLabels:
            - __name__
      path: /stats/prometheus
      relabelings:
        - action: keep
          regex: .*-envoy-prom
          sourceLabels:
            - __meta_kubernetes_pod_container_port_name
        - action: labelmap
          regex: __meta_kubernetes_pod_label_(.+)
        - action: replace
          sourceLabels:
            - __meta_kubernetes_namespace
          targetLabel: namespace
        - action: replace
          sourceLabels:
            - __meta_kubernetes_pod_name
          targetLabel: pod_name
      targetPort: http-envoy-prom
  jobLabel: envoy-stats
  namespaceSelector:
    any: true
  selector:
    matchExpressions:
      - key: istio-prometheus-ignore
        operator: NotIn
        values:
          - "true"
      - key: prometheus.io/service-monitor
        operator: NotIn
        values:
          - "false"
```
</details>

### Some investigations
- Port 15090 was never declared in Service, but VM was still able to discover it before native sidecar was enabled and can't after
- Istio adds annotations `prometheus.io/path`, `prometheus.io/port` and `prometheus.io/scrape`, but it's always been that way and has not been a problem
- I can curl both service `http://svc_name.namespace.svc.cluster.local:15090/stats/prometheus` and each pod's `http://[pod ip]:15090/stats/prometheus`

For now I'm guessing that VM doesn't pay attention to initContainers and skip them during service discovery, but it is only assumption

### To Reproduce

Set `ENABLE_NATIVE_SIDECARS=true` env in istiod deployment

### Version

helm `victoria-metrics-k8s-stack@0.27.5`
