### ISSUE TITLE
Vmauth missing route for VictoriaLogs

### ISSUE THREAD

**Issue by nulldoot2k** [VictoriaMetrics/VictoriaMetrics#7295]
### Is your question request related to a specific component?

Can not query victorialogs via VMAuth

### Describe the question in detail

I meet error when i try query from victorialogs via proxy (vmauth)
this is comand line query
```
curl -u <username>:<passwd> http://vmauth:8247/select/logsql/query -d 'query=* | limit 5'
```
Then error: **`remoteAddr: "10.X.94.112:50252"; requestURI: /select/logsql/query?query=%2A+%7C+limit+5; missing route for "/select/logsql/query"`**

This is config `vmauth.conf`
```
users:
  - username: "<username>"
    password: "<password>"
    max_concurrent_requests: 1280
    url_map:
      - src_paths:
          - "/select/.*"
        url_prefix:
          - "http://victorialogs1:9428"
          - "http://victorialogs2:9429"
      - src_paths:
          - "/insert/.*"
        url_prefix:
          - "http://victorialogs1:9428"
          - "http://victorialogs2:9429"
```
On Grafana when i add datasource and query then error because --> vmauth

![image](https://github.com/user-attachments/assets/6ed8d42f-4b9c-43de-b759-0c5f9f4439da)

Thanks a lot!

### Troubleshooting docs

- [X] General - https://docs.victoriametrics.com/troubleshooting/
- [ ] vmagent - https://docs.victoriametrics.com/vmagent/#troubleshooting
- [ ] vmalert - https://docs.victoriametrics.com/vmalert/#troubleshooting
