### ISSUE TITLE
[vmagent]Prefer endpointslice when scraping k8s endpoints

### ISSUE THREAD

**Issue by xiaozongyang** [VictoriaMetrics/VictoriaMetrics#7311]
### Is your feature request related to a problem? Please describe

Now we have several big endpoints whose pods are bigger than 1K, the biggest is about 4K+. And we got warn logs printed by vmagent like `warn	VictoriaMetrics/lib/promscrape/discovery/kubernetes/endpoints.go:112	the number of targets for "role: endpoints" "balabalabala" exceeds 1000 and has been truncated; please use "role: endpointslice" instead`. 

As the logs described, some pods of the endpoints are truncated, their metrics are missed.

### Describe the solution you'd like

Add a new bool flag to vmagent, like `-promscrape.kubernetes.preferEndpointSlice`
- if it's set to true, the vmagent will discover targets by EndpointSlice instead of Endpoints
- if it's set to false, the vmagent will discover targets by Endpoints, just like now

### Describe alternatives you've considered

1. Modify existing `VMServiceScrape` CRDS, add `discoveryRole: endpointslice` one by one
2. Modfy `VMScrapeConfig`, change `k8s_sd_confg.role` from `endpoints` to `endpointslice`

**Comment by xiaozongyang** [comment]
ping @jiekun

**Comment by Haleygo** [comment]
Hi @xiaozongyang ,
>Describe alternatives you've considered
>1. Modify existing VMServiceScrape CRDS, add discoveryRole: endpointslice one by one

What's the problem with this solution? 
Replacing `Role: endpoint` to `Role: endpointslice` should be easy to operate on user's side, and you can just change it for all the scrape configs if you want.
But since `endpoint` is still a valid role in both K8s and Prometheus eco as `endpointslice`, and they generate different [meta labels](https://docs.victoriametrics.com/sd_configs/?highlight=__meta_kubernetes_endpoints_name#kubernetes_sd_configs) which can be used in relabel_configs, I don't think it's a good idea to make vmagent changing it inexplicitly.

**Comment by xiaozongyang** [comment]
1. We have more than 100 VMScrapeService with discoverRole field omitted, it's a big work to replace them one by one
2. Now vmagent only print a warn log if meet this exceeding issue. It's not easy to found out if some endpoints are truncated and their metrics are lost. I think it's much bettere if there is an error metric about this and we can set an alert rule.
3. We can know some metrics are lost by looking these warn logs, but we cant' find lost data back. If we use endpointslice instead of endpoints, we will never lost any metrics data due to truncation.

**Comment by halohsu** [comment]
My solution to this problem is to bypass the Service provided by Node Exporter:

```yaml
apiVersion: operator.victoriametrics.com/v1beta1
kind: VMAgent
metadata:
  name: "node-exporter"
  namespace: "victoriametrics"
spec:
  tolerations: 
  - effect: NoSchedule
    key: node-role.kubernetes.io/control-plane
    operator: Exists
  affinity: 
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
          - matchExpressions:
              - key: victoriametrics.com/vmagent
                operator: Exists
  resources:
    limits:
      memory: 8Gi
      cpu: 4
    requests:
      memory: 128Mi
      cpu: 200m
  replicaCount: 2
  scrapeInterval: 1m
  minScrapeInterval: 10s
  maxScrapeInterval: 5m
  scrapeTimeout: 35s
  remoteWrite:
  - url: "http://vminsert:8480/insert/0/prometheus/api/v1/write"
    tlsConfig:
      insecureSkipVerify: true
  selectAllByDefault: false
  # serviceScrapeNamespaceSelector:
  #   matchLabels:
  #     name: victoriametrics
  # serviceScrapeSelector:
  #   matchLabels:
  #     name: node-exporter
  nodeScrapeNamespaceSelector:
    matchLabels:
      name: victoriametrics
  nodeScrapeSelector:
    matchLabels:
      name: node-exporter
---
apiVersion: operator.victoriametrics.com/v1beta1
kind: VMNodeScrape
metadata:
  name: node-exporter
  namespace: victoriametrics
  labels:
    name: node-exporter
spec:
  scheme: "http"
  port: "9100"
  path: /metrics
  max_scrape_size: '512MB'
  tlsConfig:
    insecureSkipVerify: true
  #   caFile: "/var/run/secrets/kubernetes.io/serviceaccount/ca.crt"
  # bearerTokenFile: "/var/run/secrets/kubernetes.io/serviceaccount/token"
```

When the number of physical machines exceeds 1,000, the metrics capture of Kubelet (including cAdvisor) and Node Exporter should use `VMNodeScrape` instead of `VMServiceScrape`.
