### ISSUE TITLE
VMAUTH: Is there a way to send basic auth for each backend ?

### ISSUE THREAD

**Issue by dvnscr** [VictoriaMetrics/VictoriaMetrics#7318]
### Is your question request related to a specific component?

vmauth

### Describe the question in detail

suppose there are several targets, i.e.:
```
url_prefix:
  - target1
  - target2
  - target3
```
Each target has its own username and password.
Is there a way to set basic auth for each target separately ?

### Troubleshooting docs

- [X] General - https://docs.victoriametrics.com/troubleshooting/
- [X] vmagent - https://docs.victoriametrics.com/vmagent/#troubleshooting
- [X] vmalert - https://docs.victoriametrics.com/vmalert/#troubleshooting

**Comment by jiekun** [comment]
Hi. If you are talking about receiving request with different basic auth header and route them according to those header:
```yaml
users:
- username: foo
  password: bar
  url_prefix: "http://victoria-metrics:8428/"
- username: foo-2
  password: bar-2
  url_prefix: "http://victoria-metrics-2:8429/"
```
You can refer to https://docs.victoriametrics.com/vmauth/#basic-auth-proxy for more detail and example.

---
Or, if you are talking about routing your request to different target according to the request path, request host, ... and set basic auth header for them:
```yaml
unauthorized_user:
  url_map:
  - src_paths: ["/api/v1/write"]
    url_prefix: "http://vminsert:8480/insert/42/prometheus"
    headers:
    - "X-Scope-OrgID: abc"
  - src_paths: ["/api/v1/read"]
    url_prefix: "http://vmselect:9999/select/0/prometheus"
    headers:
    - "Authorization: Basic am9obkBleGFtcGxlLmNvbTphYmMxMjM="
```

You can refer to https://docs.victoriametrics.com/vmauth/#routing for more detail and example.

**Comment by dvnscr** [comment]
I am looking per-target possibility, but those targets have different credentials. I saw that it was requested in this issue #4361 , but i am not sure how it was implemented. The end result would be something like:
```
url_prefix:
  - url: "http://host1:8429/"
    headers:
  - url: "http://host2:8429/"
     headers:
```

**Comment by jiekun** [comment]
Hi @dvnscr, could you please provide a more detailed description of your requests and targets?

I'd like to divide your question into several parts:
- How would you prefer to route your request? Is it based on the host, path, or HTTP header?
- Does your request contain a basic authentication header?
- When forwarding your request, do you expect `vmauth` to add/modify/carry the original basic authentication header to the target?

In the issue you mentioned, it seems it's already supported. You can see the example by zekker6 and my previous comment. So I'm not sure if I understand your question correctly. You could provide an example, like, what header the original request is carrying, what path you want it to be forwarded, and what header you want the forwarded request carry?

**Comment by dvnscr** [comment]
> Hi @dvnscr, could you please provide a more detailed description of your requests and targets?
> 
> I'd like to divide your question into several parts:
> 
>     * How would you prefer to route your request? Is it based on the host, path, or HTTP header?
> 
>     * Does your request contain a basic authentication header?
> 
>     * When forwarding your request, do you expect `vmauth` to add/modify/carry the original basic authentication header to the target?
> 
> 
> In the issue you mentioned, it seems it's already supported. You can see the example by zekker6 and my previous comment. So I'm not sure if I understand your question correctly. You could provide an example, like, what header the original request is carrying, what path you want it to be forwarded, and what header you want the forwarded request carry?

Hi,

- Does not really matter at this point, lets suppose it would be routed based on the path
- No
- Yes, add Basic auth header per target

zekker6 example shows with one target. So lets take this example:
```
unauthorized_user:
  url_prefix: "http://backend:1234/"
  headers:
  - "Authorization: Basic BASE64_ENCODED_VALUE"
```

If url_prefix has more than one backend , how to enumarate "headers" against different url_prefix backends ?

I have tried configuring it as mohammadkhavari was proposing, i.e.
```
- username: "user"
  password: "***"
  url_prefix:
  - url: "http://host1:8429/"
    basic_auth:
      username: "backed_user"
      password: "***"
  - url: "http://host2:8429/"
    basic_auth:
      username: "backend2_user"
      password: "*******"
```

But it does not work like this, i have also tried to:
```
unauthorized_user:
  url_prefix: 
  - "http://backend:1234/"
      headers: "Authorization: Basic encodedUserPw"
  - "http://backend2:1515/"
      headers: "Authorization: Basic encodedBackend2UserPw"
```

Does not work either.

**Comment by jiekun** [comment]
Hi. vmauth only support setting header for **different route**

```yaml
unauthorized_user:
  url_map:
  - src_hosts:
    - "app1\\.my-host\\.com"
    - url_prefix: "http://vminsert:8480/insert/42/prometheus"
    headers:
    - "Authorization: Basic am9obkBleGFtcGxlLmNvbTphYmMxMjM="
  - src_hosts:
    - "app2\\.my-host\\.com"
    - url_prefix: "http://vmselect:99999/select/2/prometheus"
    headers:
    - "Authorization: Basic chjsf123BleGFtcGxlLmNvbs1sdxy82kask="
```

And if you want to do load balancing to multiple target and set different auth header for each of them, it's not supported yet.

**Comment by jiekun** [comment]
Let me convert this issue into a feature request. We could re-check it if more people upvote.

**Comment by pgassmann** [comment]
I would also like to configure basic auth for certain backends. 

Our use case: Connect **victorialogs vmalert** via vmauth to a separate **victoriametrics** server for recording rules, alert state persistence and alerts based on the recording rule metrics.

The deployment example for victorialogs contain a vmauth instance to route requests based on their types: https://github.com/VictoriaMetrics/VictoriaMetrics/blob/master/deployment/docker/auth-vl-single.yml

I would like to host victorialogs on a separate server and https domain than the victoriametrics instance.

The Docs for [vmauth states in the Security Section](https://docs.victoriametrics.com/victoriametrics/vmauth/#security), that it assumes a secure private network between vmauth and the backends. Which is not the case in our setup (on hetzner servers)

My current workaround is to configure victoriametrics backend directly on vmalert for remoteRead and remoteWrite. This has the limitation, that i cannot configure metric alerts on the same instance as the recording rules.

docker-compose.yml extract

```yaml
services:
  victorialogs:
    image: victoriametrics/victoria-logs:v1.21.0-victorialogs
    ports:
      - 127.0.0.4:9428:9428
    expose:
      - 9428
    volumes:
      - type: bind
        source: '/container/victorialogs/vlogs-storage'
        target: /vlogs-storage
        read_only: false
    command:
      - '-storageDataPath=/vlogs-storage'
      - '-httpListenAddr=:9428'
      - '-retentionPeriod=1y'
      - '-retention.maxDiskSpaceUsageBytes=10TiB'
      # - '-logNewStreams'
      # - '-loggerLevel INFO' # Minimum level of errors to log. Possible values: INFO, WARN, ERROR, FATAL, PANIC (default "INFO")
    healthcheck:
      test: ["CMD", "wget", "-qO/dev/null", "http://127.0.0.1:9428/health"]
      interval: 30s
      timeout: 5s
      retries: 3
    networks:
      - vm_net
      - webproxy
    restart: always
    ulimits:
      nproc: 65535
      nofile:
        soft: 65535
        hard: 65535

  # vmalert for victorialogs: https://docs.victoriametrics.com/victorialogs/vmalert
  vmalert:
    image: victoriametrics/vmalert:v1.116.0
    depends_on:
      - "victorialogs"
      # - "alertmanager"
    expose:
      - 8880
    ports:
      - 127.0.0.4:8880:8880
    volumes:
      - type: bind
        source: ./rules
        target: /etc/alerts
        read_only: true
    command:
      - '-http.pathPrefix=/vmalert'
      - '-datasource.url=http://victorialogs:9428/'

      - '-remoteWrite.url=https://metrics-test.example.com'
      - '-remoteWrite.basicAuth.username=victorialogs'
      - '-remoteWrite.basicAuth.password=asdf'
      - '-remoteRead.url=https://metrics-test.example.com'
      - '-remoteRead.basicAuth.username=victorialogs'
      - '-remoteRead.basicAuth.password=asdf'

      - '-rule.defaultRuleType=vlogs'
      - '-evaluationInterval=1m'

      - '-notifier.url=https://alertmanager-test.example.com'
      - '-notifier.basicAuth.username=victorialogs'
      - '-notifier.basicAuth.password=asdf'

      - '-rule=/etc/alerts/*.yml'
      # display source of alerts in grafana
      - '-external.url=https://victorialogs-test.example.com'
      - '-external.alert.source=select/vmui/#/?g0.expr={{.Expr|queryEscape}}'
      - '-external.label=alertsource=victorialogs-test.example.com'
      - '-external.label=alerttype=vlogs'
    networks:
      - vm_net
    restart: always
    healthcheck:
      test: ["CMD", "wget", "-qO/dev/null", "http://127.0.0.1:8880/vmalert/health"]
      interval: 30s
      timeout: 5s
      retries: 3
```
