### ISSUE TITLE
VL multi-tenant support for Grafana plugin

### ISSUE THREAD

**Issue by tschlaepfer** [VictoriaMetrics/VictoriaMetrics#7349]
### Is your feature request related to a problem? Please describe

Victoria Logs support multi-tenancy, however I have not found a way to query the multi-tenant logs with the Grafana plugin for VL (v0.6.1)

### Describe the solution you'd like

In my limited understanding, adding the ability to define custom headers per VL datasource would allow to search for the tenant-specific logs in Grafana. 
![Screenshot 2024-10-25 at 09 10 25](https://github.com/user-attachments/assets/11703554-279f-456f-a71b-ccd26fefdaf0)

**Comment by jackmachine3d** [comment]
Hi, I was also looking for how to add this. I did it by adding grafana/provisioning/datasources/vm.yml to the configuration
``` yaml
apiVersion: 1
datasources:
    # <string, required> Name of the VictoriaLogs datasource
    # displayed in Grafana panels and queries.
  - name: VictoriaLogs
    # <string, required> Sets the data source type.
    type: victorialogs-datasource
    # <string, required> Sets the access mode, either
    # proxy or direct (Server or Browser in the UI).
    access: proxy
    # <string> Sets URL for sending queries to VictoriaLogs server.
    # see https://docs.victoriametrics.com/victorialogs/querying/
    url: http://localhost9428
    # <string> Sets the pre-selected datasource for new panels.
    # You can set only one default data source per organization.
    isDefault: true
    jsonData:
      httpHeaderName1: 'AccountID'
      httpHeaderName2: 'ProjectID'
    secureJsonData:
      httpHeaderValue1: '1'
      httpHeaderValue2: '8094'
```
