### ISSUE TITLE
Victoria logs doesn't accept messages to loki endpoint from vector (got 3 want 2)

### ISSUE THREAD

**Issue by foi** [VictoriaMetrics/VictoriaMetrics#7367]
### Describe the bug

OS: debian 12 on both sides
vector: 0.42.0

vector config
```
sources:
  journald_source:
    type: journald
sinks:
  vlogs:
    type: "loki"
    endpoint: "http://192.168.131.1:9428/insert/loki/"
    inputs:
      - journald_source
    compression: gzip
    path: /api/v1/push?_msg_field=message.message&_time_field=timestamp&_stream_fields=source
    encoding:
      codec: json
    labels:
      source: vector
      hostname: hostname.com
```

victoria-logs: victoria-logs-20241018-003631-tags-v0.37.0-victorialogs-0-g14e33d93e 

### To Reproduce

configure vector as recommended here: https://docs.victoriametrics.com/victorialogs/data-ingestion/vector/#loki

### Version

victoria-logs-20241018-003631-tags-v0.37.0-victorialogs-0-g14e33d93ef

### Logs

```
2024-10-24T16:50:18.630Z        warn        VictoriaMetrics/app/vlinsert/loki/loki_json.go:59        remoteAddr: "192.168.131.8:50174"; requestURI: /insert/loki/api/v1/push?_msg_field=message.message&_time_field=timestamp&_stream_fields=source; cannot parse Loki json request: unexpected number of values in `values` item array "[\"1729788617154031000\",\"{\\\"PRIORITY\\\":\\\"5\\\",\\\"SYSLOG_FACILITY\\\":\\\"10\\\",\\\"SYSLOG_IDENTIFIER\\\":\\\"sshd\\\",\\\"SYSLOG_PID\\\":\\\"121545\\\",\\\"SYSLOG_TIMESTAMP\\\":\\\"Oct 24 19:50:17 \\\",\\\"_BOOT_ID\\\":\\\"7dfe733550a24090af3f65ee528f9776\\\",\\\"_CAP_EFFECTIVE\\\":\\\"1ffffffffff\\\",\\\"_CMDLINE\\\":\\\"\\\\\\\"sshd: root [priv]\\\\\\\"\\\",\\\"_COMM\\\":\\\"sshd\\\",\\\"_EXE\\\":\\\"/usr/sbin/sshd\\\",\\\"_GID\\\":\\\"0\\\",\\\"_MACHINE_ID\\\":\\\"4b3a2faa6d9f49db8eef80663f099eca\\\",\\\"_PID\\\":\\\"121545\\\",\\\"_RUNTIME_SCOPE\\\":\\\"system\\\",\\\"_SELINUX_CONTEXT\\\":\\\"unconfined\\\\n\\\",\\\"_SOURCE_REALTIME_TIMESTAMP\\\":\\\"1729788617154031\\\",\\\"_SYSTEMD_CGROUP\\\":\\\"/system.slice/ssh.service\\\",\\\"_SYSTEMD_INVOCATION_ID\\\":\\\"ddfbc72dc22f41c4b677b75f49eac611\\\",\\\"_SYSTEMD_SLICE\\\":\\\"system.slice\\\",\\\"_SYSTEMD_UNIT\\\":\\\"ssh.service\\\",\\\"_TRANSPORT\\\":\\\"syslog\\\",\\\"_UID\\\":\\\"0\\\",\\\"__MONOTONIC_TIMESTAMP\\\":\\\"732240420381\\\",\\\"__REALTIME_TIMESTAMP\\\":\\\"1729788617154064\\\",\\\"host\\\":\\\"hostname.com\\\",\\\"message\\\":\\\"pam_unix(sshd:auth): authentication failure; logname= uid=0 euid=0 tty=ssh ruser= rhost=99.62.214.218  user=root\\\",\\\"source_type\\\":\\\"journald\\\"}\",{}]"; got 3 want 2
```

### Used command-line flags

-retentionPeriod="30d"
