### ISSUE TITLE
Docker image tag latest pulls version 1.18.11

### ISSUE THREAD

**Issue by 00Asgaroth00** [VictoriaMetrics/VictoriaMetrics#74]
Hi,

When pulling the "latest" tag from hub.docker.com for victoriametrics, version 1.18.11 is the version reported by victoriametrics within the container.

I have tried to pull using tag name "v1.20.2", but docker complains saying that the manifest does not exist.

Am I doing something wrong, or, is there something amiss with docker hub?

Here is a snippet of my docker-compose.yaml that pull v1.18.11 when using the latest tag:

```
services:
  victoria_metrics:
    image: valyala/victoria-metrics:latest
    container_name: vitoria_metrics
    hostname: victoria
    restart: always
    command:
      - '--httpListenAddr=:8428'
      - '-retentionPeriod=12'
      - '-memory.allowedPercent=10'
    ports:
      - 8428:8428
    volumes: 
      - /data/monitoring/victoria_metrics:/victoria-metrics-data
    networks:
      - monitoring 
```

EDIT:

Looking at docker images output it looks like the latest tag's image was built 2 weeks ago:

```
# docker images
REPOSITORY                 TAG                 IMAGE ID            CREATED             SIZE
valyala/victoria-metrics   latest              8c56ce650ffa        2 weeks ago         11.8MB
```
