### ISSUE TITLE
vmalert-tool: test_group interval does not default to evaluation_interval

### ISSUE THREAD

**Issue by dctrwatson** [VictoriaMetrics/VictoriaMetrics#7425]
### Describe the bug

If the `test_group` does not define `interval`, the `input_series`'s values equation is not evaluated at the interval, instead every sample is equal to the final value of the equation

### To Reproduce

```
tests:
  - name: no_interval
    input_series:
      - series: 'requests_total{}'
        values: '0+60x5'

    metricsql_expr_test:
      - expr: requests_total
        eval_time: 1m
        exp_samples:
          - labels: 'requests_total{}'
            value: 60
      - expr: requests_total
        eval_time: 2m
        exp_samples:
          - labels: 'requests_total{}'
            value: 120
      - expr: requests_total
        eval_time: 3m
        exp_samples:
          - labels: 'requests_total{}'
            value: 180
      - expr: requests_total
        eval_time: 4m
        exp_samples:
          - labels: 'requests_total{}'
            value: 240
      - expr: requests_total
        eval_time: 5m
        exp_samples:
          - labels: 'requests_total{}'
            value: 300
```

### Version

`vmalert-tool version vmalert-tool-20241002-113505-tags-v1.104.0-0-g0d4f4b8f7d`
