### ISSUE TITLE
How can I query the unit of stored data?

### ISSUE THREAD

**Issue by moreamazingnick** [VictoriaMetrics/VictoriaMetrics#7426]
### Is your question request related to a specific component?

VictoriaMetrics, InfluxDB1

### Describe the question in detail

I use Icinga2 and the Influxdb1writer to write performance data into victoriametrics. that works pretty well except that I loose the unit of the stored data, or maybe I just cant find it.
```
system_basics_filesystem_value{db="icinga2",hostname="mypc",metric="/_space_free",service="check_system_basics_filesystem"}
min: 125,979,000,000 median: 126,009,000,000 max: 126,159,000,000
```
There is also something like this:
```
system_basics_filesystem_unit{db="icinga2",hostname="mypc",metric="/_space_free",service="check_system_basics_filesystem"}
min: 0 median: 0 max: 0 
```
The Icinga2 writes the following using their InfluxDBWriter feature:
```
[2024-11-04 20:57:19 +0000] debug/InfluxdbWriter: Checkable 'mypc!check_system_basics_filesystem' adds to metric list:'system_basics_filesystem,hostname=mypc,service=check_system_basics_filesystem,metric=/_space_free max=469827207168,min=0,unit="bytes",value=125976592384 1730753839'. 
```
Is it somehow possible to get the unit as a label?

Best Regards 
Nicolas

### Troubleshooting docs

- [ ] General - https://docs.victoriametrics.com/troubleshooting/
- [ ] vmagent - https://docs.victoriametrics.com/vmagent/#troubleshooting
- [ ] vmalert - https://docs.victoriametrics.com/vmalert/#troubleshooting

**Comment by tiny-pangolin** [comment]
VictoriaMetrics does not have a way of storing string values so they get converted to metrics that store a value of zero. To fix this, The unit should be set as a tag/label instead of a field/value. It would be best if this can be done in the Icingia settings otherwise you can use a collector like telegraf to make this change for you. I have included an example config below

```toml
[[inputs.influxdb_listener]]
  service_address = "0.0.0.0:8186"
[[processors.converter]]
  [processors.converter.fields]
    tag = ["unit"]
[[outputs.influxdb]]
  urls = ["http://victoriametrics.local:8428"]
  database = "icingia"
  skip_database_creation = true
  exclude_retention_policy_tag = true
  content_encoding = "gzip"
  insecure_skip_verify = true
```
