### ISSUE TITLE
How can I drop metric with VMAgent centrally?

### ISSUE THREAD

**Issue by dongho-jung** [VictoriaMetrics/VictoriaMetrics#7453]
### Is your question request related to a specific component?

vmagent

### Describe the question in detail

```
apiVersion: operator.victoriametrics.com/v1beta1
kind: VMPodScrape
metadata:
  name: gha-rs-listener-metrics
spec:
  podMetricsEndpoints:
    - metricRelabelConfigs:
        - action: drop
          regex: gha_job_(startup|execution)_duration_seconds_bucket
          sourceLabels:
            - __name__
      path: /metrics
      port: metrics
  selector:
    matchLabels:
      app.kubernetes.io/component: runner-scale-set-listener
```

For each scrape resource, it is possible to use metricRelabelConfigs like above to ensure certain metrics are not collected.

However, I would like to centrally control whether certain metrics are collected or not.

So, I wanted to control this by passing it to VMAgent through a ConfigMap, but when I checked [the documentation](https://docs.victoriametrics.com/operator/resources/vmagent/) and `kubectl explain`, I could see the relabelConfig field, but it seems like there’s no metricRelabelConfigs field.

Is it correct to assume that metric collection cannot be centrally controlled?

### Troubleshooting docs

- [ ] General - https://docs.victoriametrics.com/troubleshooting/
- [X] vmagent - https://docs.victoriametrics.com/vmagent/#troubleshooting
- [ ] vmalert - https://docs.victoriametrics.com/vmalert/#troubleshooting
