### ISSUE TITLE
Is there /api/v1/targets in cluster version?

### ISSUE THREAD

**Issue by dongho-jung** [VictoriaMetrics/VictoriaMetrics#7454]
### Is your question request related to a specific component?

VictoriaMetrics Cluster Version

### Describe the question in detail

In the single version, there was a page in the browser where targets were organized, but it seems like I can't see it in the cluster version.

Even in the documentation, there’s information about /api/v1/targets in [the single version](https://docs.victoriametrics.com/single-server-victoriametrics/#prometheus-querying-api-usage), but I don’t see anything related to it in [the cluster version](https://docs.victoriametrics.com/cluster-victoriametrics/).

In the cluster version, how can I find out which targets are currently being collected, their status, and other relevant information?

### Troubleshooting docs

- [X] General - https://docs.victoriametrics.com/troubleshooting/
- [ ] vmagent - https://docs.victoriametrics.com/vmagent/#troubleshooting
- [ ] vmalert - https://docs.victoriametrics.com/vmalert/#troubleshooting

**Comment by jiekun** [comment]
Hi. The answer is no.

The targets page is available for components that provide service discovery capabilities. VMCluster does not have this feature, so this page is not available for it. Also, in VictoriaMetrics Single Node, this page shows the targets discovered by itself, not aggregating all targets discovered by vmagent.

**Comment by dongho-jung** [comment]
Thank you for the advice. After adding the ingress for the agent as follows, it’s now showing up well.

```yaml
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    alb.ingress.kubernetes.io/listen-ports: '[{"HTTPS": 443}]'
    alb.ingress.kubernetes.io/target-type: ip
    nginx.ingress.kubernetes.io/rewrite-target: /$1
  name: victoria-metrics-agent
spec:
  ingressClassName: nginx-private
  rules:
    - host: ...
      http:
        paths:
          - backend:
              service:
                name: vmagent-vmagent
                port:
                  name: http
            path: /agent/(.*)
            pathType: ImplementationSpecific
```

<img width="1728" alt="image" src="https://github.com/user-attachments/assets/c9048b58-81de-4b7d-be92-1c3e6ac61616">
