### ISSUE TITLE
Support vlogs as type in VMRuleSpec

### ISSUE THREAD

**Issue by recht** [VictoriaMetrics/VictoriaMetrics#7460]
### Describe the bug

vmalert now supports vlogs as rule type, but it's not possible to create a `VMRule` that uses that type

### To Reproduce

Try to apply this:
```
apiVersion: operator.victoriametrics.com/v1beta1
kind: VMRule
metadata:
  name: errors
  namespace: victoria
spec:
  groups:
    - name: vlogs
      type: vlogs
      rules:
        - record: bw_log_errors
          expr: level:error|stats by (k8s.namespace.name) count() as errors
```

### Version

0.49.0

**Comment by f41gh7** [comment]
It should be fixed at operator upstream and will be the part of upcoming bugifx release https://github.com/VictoriaMetrics/operator/commit/504694483c40e688106ab74f56e3876b71c8d852

 Current workaround is to disable `VMRule` validation:

```yaml
apiVersion: operator.victoriametrics.com/v1beta1
kind: VMRule
metadata:
  name: errors
  namespace: victoria
  annotations:
   operator.victoriametrics.com/skip-validation : "true"
spec:
  groups:
    - name: vlogs
      type: vlogs
      rules:
        - record: bw_log_errors
          expr: level:error|stats by (k8s.namespace.name) count() as errors
```
