### ISSUE TITLE
Support for Kubernetes Service Discovery in vmalert for Alertmanager integration

### ISSUE THREAD

**Issue by abolfazlyarian** [VictoriaMetrics/VictoriaMetrics#7501]
### Is your feature request related to a problem? Please describe

I am currently using Prometheus in my Kubernetes cluster for monitoring, and I am planning to migrate to VictoriaMetrics in the cluster version. In my previous setup, I utilized Kubernetes service discovery to connect Prometheus to Alertmanager, as shown in the configuration below:
```
alerting:
  alertmanagers:
    - kubernetes_sd_configs:
        - role: endpoints
          namespaces:
            names:
              - {{ .Release.Namespace }}
      relabel_configs:
        - source_labels: [__meta_kubernetes_pod_annotation_prometheus_io_job]
          regex: alertmanager
          action: keep
```
In this setup, Prometheus could dynamically discover and connect to Alertmanager instances running in the same namespace. However, I found that vmalert does not currently support Kubernetes service discovery (only DNS and Consul discovery are available).

Thank you!

### Describe the solution you'd like

Please consider adding Kubernetes service discovery support in vmalert for Alertmanager integration. This would allow a more seamless transition for users migrating from Prometheus to VictoriaMetrics and enable dynamic endpoint discovery without relying on DNS or Consul.

### Describe alternatives you've considered

If Kubernetes service discovery cannot be added, I would appreciate any recommended workaround to achieve similar functionality in vmalert without using the DNS or Consul approaches.

### Contribution Interest:
I am interested in contributing to this feature and would appreciate any guidance on where to start or specific aspects to focus on.

**Comment by Haleygo** [comment]
Hi @abolfazlyarian ,
It's possible to add Kubernetes SD in vmalert like vmagent or vmsingle, but that would would increase dependencies and complexity(making vmalert to listen to K8s API server and process responses). Prometheus can achieve this easier since it have both scraping and alerting inside single binary.
The current workround is, managing [vmalertmanager](https://docs.victoriametrics.com/operator/api/#vmalertmanager) and [vmalert](https://docs.victoriametrics.com/operator/api/#vmalert) via vm-operator, which discovers all avaliable alertmanager pods as vmalert's notifiers. For instance, below vmalert will have two alertmanager pods as its notifiers:
```
apiVersion: operator.victoriametrics.com/v1beta1
kind: VMAlert
metadata:
  name: example-vmalert
spec:
  replicaCount: 1
  notifiers:
  - selector:
      labelSelector:
        matchLabels:
          env: dev       // the label of wanted vmalertmanager

---
apiVersion: operator.victoriametrics.com/v1beta1
kind: VMAlertmanager
metadata:
  name: example-alertmanager
  labels:
    env: dev            // add label for vmalertmanager
spec:
  replicaCount: 2
  configSecret: alertmanager-config
```
