### ISSUE TITLE
vmauth: inconsistent inheritence of root configuration options

### ISSUE THREAD

**Issue by zekker6** [VictoriaMetrics/VictoriaMetrics#7519]
### Describe the bug

The following configuration of vmauth defines `drop_src_path_prefix_parts` configuration option on the root level:
```
users:
- url_map:
  - url_prefix:
    - http://am-0:9093/
    src_paths:
    - /am-0/.*
  - url_prefix:
    - http://am-1:9093/
    src_paths:
    - /am-1/.*
  - url_prefix:
    - http://am-2:9093/
    src_paths:
    - /am-2/.*
  name: test
  drop_src_path_prefix_parts: 1
  username: test
  password: test
```

But this option will not be used in `url_map` items. 
Adding `url_prefix` to the root configuration changes this so that all root configuration options are now inherited.
See: https://github.com/VictoriaMetrics/VictoriaMetrics/blob/cb76ff5c56ed7f6eb9b63c29e21606e6e3c1f576/app/vmauth/auth_config.go#L864-L886

It would be great to make it consistent by not depending on whether `url_prefix` is defined. Root options should always be inherited by `url_map` items.

### To Reproduce

Use the following configuration:
```
users:
- url_map:
  - url_prefix:
    - http://am-0:9093/
    src_paths:
    - /am-0/.*
  - url_prefix:
    - http://am-1:9093/
    src_paths:
    - /am-1/.*
  - url_prefix:
    - http://am-2:9093/
    src_paths:
    - /am-2/.*
  name: test
  drop_src_path_prefix_parts: 1
  username: test
  password: test
```

### Version

v1.106.0
