### ISSUE TITLE
Inconsitent behaviour for unauthorized_user section

### ISSUE THREAD

**Issue by f41gh7** [VictoriaMetrics/VictoriaMetrics#7543]
### Describe the bug

 Currently, it's not possible to use vmauth as generic proxy service as documentation describes. vmauth acts differently if request contains `Authorization` headers and always enforces valid header value.

 It's expected if `unauthorized_user` is defined, all failed to authorize requests must be routed to this config.  

### To Reproduce

 Copy config from docs:
```yaml
unauthorized_user:
  url_prefix:
  - "http://app-instance-1/"
  - "http://app-instance-2/"
  - "http://app-instance-3/"
```

 make request and observe expected error
```
curl localhost:8427/some
# cannot proxy the request error
```

Add authorization to the request and vmauth returns unexpected unathorized response
```
curl 'http://XX@localhost:8427/some'
# 401 unathorized
```

### Version

 any version
