### ISSUE TITLE
[VictoriaLogs] Unable to set root of event to _msg field using elasticsearch Vector sink

### ISSUE THREAD

**Issue by alexeynl** [VictoriaMetrics/VictoriaMetrics#7553]
### Is your question request related to a specific component?

victorialogs

### Describe the question in detail

I'm using Vector to ingest events to Victoria logs.
I need the whole event (json message) is set to _msg field. This is Vector config i tried

```
sinks:
  test-sink:
    inputs:
      - test-input
    type: elasticsearch
    endpoints:
      - http://victorialogs.test:9428/insert/elasticsearch/
    mode: bulk
    api_version: v8
    healthcheck:
      enabled: false
    query:
      extra_fields: "hostname=some-server,app_name=vector,proc_id=sink"
      _stream_fields: hostname,app_name,proc_id
```
in this case i have:

_"missing _msg field; see https://docs.victoriametrics.com/victorialogs/keyconcepts/#message-field"_

in **_msg** field.

This is Vector config works as i want:

```
sinks:
  test-sink:
    type: "loki"
    endpoint: "http://victorialogs.test:9428"
    inputs:
      - test-input
    compression: gzip
    path: "/insert/loki/api/v1/push?_msg_field=&_time_field=0&_stream_fields=hostname,app_name,proc_id"
    healthcheck:
      enabled: false
    encoding:
      codec: json
    labels:
      hostname: "some-server"
      app_name: "vector"
      proc_id: "sink"
```

Is this possible to set root of event to victorialogs **_msg** field using elasticsearch sink type?

### Troubleshooting docs

- [ ] General - https://docs.victoriametrics.com/troubleshooting/
- [ ] vmagent - https://docs.victoriametrics.com/vmagent/#troubleshooting
- [ ] vmalert - https://docs.victoriametrics.com/vmalert/#troubleshooting

**Comment by AndrewChubatiuk** [comment]
hey @alexeynl 
you can use `VL-Msg-Field` header instead of `_msg` query arg
please check our victoria-logs-single helm chart
we're using elasticsearch sink there
https://github.com/VictoriaMetrics/helm-charts/blob/master/charts/victoria-logs-single/values.yaml

**Comment by alexeynl** [comment]
> regarding elasticsearch output you need to set `_msg=message` or `VL-MsgField: message`

I have tried both as following:

```
sinks:
  test-sink:
    inputs:
      - test-input
    type: elasticsearch
    endpoints:
      - http://victorialogs.test:9428/insert/elasticsearch/
    mode: bulk
    api_version: v8
    healthcheck:
      enabled: false
    query:
      extra_fields: "hostname=some-server,app_name=vector,proc_id=sink"
      _msg_field: message
      _stream_fields: hostname,app_name,proc_id
```
```
sinks:
  test-sink:
    inputs:
      - test-input
    type: elasticsearch
    endpoints:
      - http://victorialogs.test:9428/insert/elasticsearch/
    mode: bulk
    api_version: v8
    healthcheck:
      enabled: false
    query:
      extra_fields: "hostname=some-server,app_name=vector,proc_id=sink"
      _msg_field: message
    request:
      headers:
        VL-Msg-Field: message
```

But in this case victorialogs set **_msg** field to value of **message** field of input json message.

I need whole json in _msg field.
