### ISSUE TITLE
Can multiple vmstorage nodes use the same (NFS) directory?

### ISSUE THREAD

**Issue by LHB6540** [VictoriaMetrics/VictoriaMetrics#7594]
### Is your question request related to a specific component?

vmstorage

### Describe the question in detail

I deployed vmc using helm. I found that multiple vmstorage pods were mounted with the same pv created by pvc. The storageclass type corresponding to my pvc is NFS. I checked NFS and did not find any subdirectories distinguished by vmstorage nodes. Multiple vmstorages use the same directory for storage. Is this allowed? I am worried whether this will affect its normal operation.

### Troubleshooting docs

- [ ] General - https://docs.victoriametrics.com/troubleshooting/
- [ ] vmagent - https://docs.victoriametrics.com/vmagent/#troubleshooting
- [ ] vmalert - https://docs.victoriametrics.com/vmalert/#troubleshooting

**Comment by tiny-pangolin** [comment]
Each vmstorage pod should have it's own PVC can you share your values.yml file so we can see if it's a configuration issue or a bug in the helm chart?

**Comment by LHB6540** [comment]
> Each vmstorage pod should have it's own PVC can you share your values.yml file so we can see if it's a configuration issue or a bug in the helm chart?

Here is the app environment:
Chart version: 0.11.12
Chart app version: 1.97.1
values.yaml:
```
...
vmstorage:
...
  persistentVolume:  
    enabled: true
    name: vmstorage-volume
    accessModes:
      - ReadWriteOnce
    existingClaim: "vmstorage-pvc"
    mountPath: /storage
    size: 100Gi
    subPath: ""
...
```

Here is the k8s environment:
k8s version: 1.30.0
existingClaim: vmstorage-pvc

After getting your reply, I clearly confirmed that each pod should use its own pvc or should use different directories. I tried to read templates/vmstorage.yaml. I think I have figured out what happened.After changing the configuration file to the following, it created a pvc for each pod for mounting as expected.
```
...
vmstorage:
...
  persistentVolume:  
    enabled: true
    name: vmstorage-volume
    accessModes:
      - ReadWriteOnce
    existingClaim: ""
    mountPath: /storage
    storageClass: "cfs"
    size: 100Gi
    subPath: ""
...
```

Let me explain why I use existingClaim instead of storageClass in values.yaml. I haven't read templates/vmstorage.yaml before. I think this configuration will: bind a pvc (pre-bind or automatically create a pv) for mounting, and when mounting, use different subdirectories for each pod, similar to subPathExpr.
In fact, according to the content of templates/vmstorage.yaml. Because existingClaim is defined, volumeClaimTemplates will not be rendered.
```
  {{- if and $app.persistentVolume.enabled (not $app.persistentVolume.existingClaim) }}
  volumeClaimTemplates:
  ...
  {{- end }}
```
And .Values.vmstorage.persistentVolume.existingClaim will be used to declare a volume named vmstorage-volume. This name corresponds to .Values.vmstorage.persistentVolume.name. And is used for volumeMount of container vmstorage.
```
      volumes:
        {{- with $app.extraVolumes }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
        {{- if or (not $app.persistentVolume.enabled) $app.persistentVolume.existingClaim }}
        - name: vmstorage-volume
          {{- if $app.persistentVolume.enabled }}
          persistentVolumeClaim: 
            claimName: {{ $app.persistentVolume.existingClaim }}
          {{- else }}
          emptyDir: {{ toYaml $app.emptyDir | nindent 12 }}
          {{- end }}
        {{- end }}
        {{- include "vm.license.volume" . | nindent 8 }}
      {{- end }}
```
```
      containers:
        - name: vmstorage
          volumeMounts:
            {{- with $app.persistentVolume }}
            - name: {{ .name }}
              mountPath: {{ .mountPath }}
              {{- with .subPath }}
              subPath: {{ . }}
              {{- end }}
            {{- end }}
```

I don't know if this design is reasonable. If the configuration allows users to use existing pvc instead of storageClass, should we consider using pvc as persistentVolume and distinguishing the mount path for each pod when mounting to avoid the situation where all pods share the same directory of a volume?
