### ISSUE TITLE
vmalert with `rule.resendDelay=24h` still resends notifcation after restart

### ISSUE THREAD

**Issue by nil-netai** [VictoriaMetrics/VictoriaMetrics#7600]
### Is your question request related to a specific component?

Vmalert

### Describe the question in detail

I have configured Victoria-Metrics Single node version and VMalert in server. i use remoteRead and remoteWrite flags but but after restarting vmalert resend notification of same alert.

### Troubleshooting docs

- [ ] General - https://docs.victoriametrics.com/troubleshooting/
- [ ] vmagent - https://docs.victoriametrics.com/vmagent/#troubleshooting
- [X] vmalert - https://docs.victoriametrics.com/vmalert/#troubleshooting

**Comment by Haleygo** [comment]
Could you provide more details about the issue? Specifically, what is your alert rule (is there a non-zero for value), how can it be reproduced, and what is the expected behavior?
Based on the current information, I would say it's expected:
if your rule is continuously firing, vmalert will send notification to notifier(usually alertmanager) in every iteration(group_interval), and it's notifier's responsibility to manage notification frequency to users. (In [alertmanager](https://prometheus.io/docs/alerting/latest/configuration/), there is option like `repeat_interval`).
And when you restart vmalert, if the rule is still firing, new vmalert would also send notification to notifier.

**Comment by nil-netai** [comment]
this my alert_rule
```
groups:
- name: NetAnalytics
  rules:
  - alert: Network element offline
    annotations:
      alert_id: 129
      metrics_name: ping
    expr: ping{customer_id="2", instance="46"} == 0
    labels:
      severity: Critical
      type: Alert

```
this will fire alert when ping metrics for instance 46 when become be 0.
