### ISSUE TITLE
Azure SD Config targets entire subscription and not only the specified resource_group

### ISSUE THREAD

**Issue by shanoor** [VictoriaMetrics/VictoriaMetrics#7630]
### Describe the bug

I'm trying to scrape metrics from Azure VM using `azure_sd_configs` but I noticed the `resource_group` config is ignored and victoria-agent tries to scrape VM in the entire subscription and ends up with hundreds of scrape target error. The same config works as expected with Prometheus.

### To Reproduce

- Have two or more Azure resource groups containing virtual machines
- Use a config like below to target one resource group :
    ```
    extraScrapeConfigs:
      - job_name: scrape-metrics-vm
        azure_sd_configs:
          - authentication_method: ManagedIdentity
            environment: AzurePublicCloud
            subscription_id: xxxxxxxxxxxxxxxxxxxxxxxxxx
            resource_group: RG001
            port: 9182
        relabel_configs:
          - source_labels: [__meta_azure_machine_location]
            target_label: location
          - source_labels: [__meta_azure_machine_name]
            target_label: vm_name
          - source_labels: [__meta_azure_machine_os_type]
            target_label: os_type
          - source_labels: [__meta_azure_machine_private_ip]
            target_label: private_ip
          - source_labels: [__meta_azure_machine_resource_group]
            target_label: resource_group
          - source_labels: [__meta_azure_subscription_id]
            target_label: subscription_id
    ```
- you can check in victoria-agent's ui that all VM of the subscription are targeted not just the ones in the specified resource_group.

### Version

vmagent-20241115-224452-tags-v1.106.1-0-g4b74baf696
