### ISSUE TITLE
Add the ability for vlogs recording rules to send to the same tenant in victoriametrics

### ISSUE THREAD

**Issue by tiny-pangolin** [VictoriaMetrics/VictoriaMetrics#7656]
### Is your feature request related to a problem? Please describe

Currently, there is not a way to route vlogs recording rules to a specific tenant in VictoriaMetrics

### Describe the solution you'd like

I would like to be able to run Victorialogs rules across multiple tenants and have those results land in Victoriametrics in the same tenant. 

In the example below, the rules from `VictorialogsRecordingTenant1` would land in tenant 0:1 in VictoriaMetrics and the rules from `VictorialogsRecordingTenant2` would land in 0:2 in VictoriaMetrics

```yaml
groups:
  - name: VictorialogsRecordingTenant1
    interval: 1m
    type: vlogs
    headers:
      - "AccountID: 0"
      - "ProjectID: 1"
    rules:
      - record: httpRequestCount
        expr: 'tags.path:/var/log/httpd OR tags.path:/var/log/nginx | stats by (tags.host) count() requests'
        annotations:
          descriptions: "Nginx or HTTPD requests"
groups:
  - name: VictorialogsRecordingTenant2
    interval: 1m
    type: vlogs
    headers:
      - "AccountID: 0"
      - "ProjectID: 2"
      - record: httpRequestCount
        expr: 'tags.path:/var/log/httpd OR tags.path:/var/log/nginx | stats by (tags.host) count() requests'
        annotations:
          descriptions: "Nginx or HTTPD requests"
```

### Describe alternatives you've considered

run a dedicated vmalert per tenant, but this would require multiple vmalert instances and might not work well when using VMAlert + VMRule using VMOperator

**Comment by Haleygo** [comment]
Results from both rules will be written to the default tenant0 in VictoriaMetrics, since two products require tenantID differently:
In [VictoriaLogs](https://docs.victoriametrics.com/victorialogs/#multitenancy): the AccountID and ProjectID fields are set during [data ingestion](https://docs.victoriametrics.com/victorialogs/data-ingestion/) and [querying](https://docs.victoriametrics.com/victorialogs/querying/) via AccountID and ProjectID request headers.
In [VictoriaMetrics](https://docs.victoriametrics.com/cluster-victoriametrics/#multitenancy): the AccountID and ProjectID  are included in request URLs for writes and reads or specified through labels.
By default, vmalert writes results to the tenant specified in `-remotewrite.url`. 
To change that, using vminsert multitenant endpoint as `-remotewrite.url=http://vminsert:8480/insert/multitenant/prometheus` and specify the tenantID under rule labels, for instance:
```
groups:
  - name: VictorialogsRecordingTenant1
    type: vlogs
    headers:
      - "AccountID: 0"
      - "ProjectID: 1"
    labels:
      vm_account_id: 0
      vm_project_id: 1    
    rules:
      - record: httpRequestCount
        expr: 'tags.path:/var/log/httpd OR tags.path:/var/log/nginx | stats by (tags.host) count() requests'
  - name: VictorialogsRecordingTenant2
    type: vlogs
    headers:
      - "AccountID: 0"
      - "ProjectID: 2"
    labels:
      vm_account_id: 0
      vm_project_id: 2
    rules: 
    - record: httpRequestCount
        expr: 'tags.path:/var/log/httpd OR tags.path:/var/log/nginx | stats by (tags.host) count() requests'
```
