### ISSUE TITLE
scrapeConfigSelectors don't work as expected.

### ISSUE THREAD

**Issue by chownxx** [VictoriaMetrics/VictoriaMetrics#7687]
### Is your question request related to a specific component?

vmagent

### Describe the question in detail

hey!

We are moving from Prometheus to VictoriaMetrics and have encountered some odd things related to ScrapeConfig.

We have namespaces `victoria-components` and `monitoring`. There are ScrapeConfigs deployed in the monitoring namespace and vmagents deployed in the victoria-components namespace. We want the vmagents to reference the ScrapeConfigs in the monitoring namespace and use scrapeConfigSelector and scrapeConfigNamespaceSelector for this, but we are facing some strange behavior.

When only the `scrapeConfigNamespaceSelector` is specified, vmagent looks for all scrapeConfigs in all namespaces, regardless of the condition we use.

for example, this still will match scrapeConfigs from default namespaces

```yaml
scrapeConfigNamespaceSelector:
  matchExpressions:
  - key: name
    operator: NotIn
    values:
    - default
 ```
However, if we add scrapeConfigSelector  to our scrapeConfigNamespaceSelector like this:

```yaml
scrapeConfigSelector:
  matchExpressions: []
```
or this:

```yaml
scrapeConfigSelector:
  matchExpressions:
  - key: foo
    operator: NotIn
    values:
    - boo
```    
vmagent will only look for `scrapeConfigs` specified in its namespace, regardless of whether there are other scrapeConfigs that match our condition.

What can lead to this behavior? 
btw we have same for prometheus and all works as expected

### Troubleshooting docs

- [ ] General - https://docs.victoriametrics.com/troubleshooting/
- [X] vmagent - https://docs.victoriametrics.com/vmagent/#troubleshooting
- [ ] vmalert - https://docs.victoriametrics.com/vmalert/#troubleshooting

**Comment by f41gh7** [comment]
@Haleygo could you please take a look? It seems to be a bug

**Comment by Haleygo** [comment]
Hi @chownxx ,
>When only the scrapeConfigNamespaceSelector is specified, vmagent looks for all scrapeConfigs in all namespaces, regardless of the condition we use.

Yes, That's a bug, must be fixed in https://github.com/VictoriaMetrics/operator/pull/1174, the `scrapeConfigNamespaceSelector` should limit the selected namespace.

>vmagent will only look for scrapeConfigs specified in its namespace, regardless of whether there are other scrapeConfigs that match our condition.

yep, that's expected. If `scrapeConfigSelector` is defined, only objects under the  vmagent's namespace are counted. 
To change that, you need to specify `scrapeConfigNamespaceSelector` to match multiple namespaces too. 
For detailed match rules, see [this doc](https://docs.victoriametrics.com/operator/resources/vmagent/#scraping). 
>Following rules are applied:
>
> If ...NamespaceSelector and ...Selector both undefined, then by default select nothing. With option set - spec.selectAllByDefault: true, select all objects of given type.
> If ...NamespaceSelector defined, ...Selector undefined, then all objects are matching at namespaces for given ...NamespaceSelector.
> If ...NamespaceSelector undefined, ...Selector defined, then all objects at VMAgent’s namespaces are matching for given ...Selector.
> If ...NamespaceSelector and ...Selector both defined, then only objects at namespaces matched ...NamespaceSelector for given ...Selector are matching.

**Comment by chownxx** [comment]
HI @Haleygo, thanks for your response 

Sorry for the misunderstanding
>vmagent will only look for scrapeConfigs specified in its namespace, regardless of whether there are other scrapeConfigs that match our condition.

I meant that even if they work in combination and `scrapeConfigNamespaceSelector` is configured to look at all namespaces, specifying `scrapeConfigSelector` will limit the scope to its own namespace , regardless of whether there are other scrapeConfigs that match our condition.

```yaml
scrapeConfigNamespaceSelector: {}

scrapeConfigSelector:
  matchExpressions:
  - key: foo
    operator: NotIn
    values:
    - boo
  ```

**Comment by Haleygo** [comment]
The general rule is: you need to add `scrapeConfigNamespaceSelector` to match multiple namespaces specifically if `scrapeConfigSelector` is used, for instance
```
scrapeConfigNamespaceSelector:
  matchExpressions:
  - key: kubernetes.io/name
    operator: NotIn
    values:
    - test       // all namespace apart from test are selected
scrapeConfigSelector:
  matchExpressions:
  - key: foo
    operator: NotIn
    values:
    - boo
```
>If ...NamespaceSelector undefined, ...Selector defined, then all objects at VMAgent’s namespaces are matching for given ...Selector.

**Comment by chownxx** [comment]
yep, i understand this, i said that when both of them are defined:

```yaml
scrapeConfigNamespaceSelector:
  matchExpressions:
  - key: name
    operator: NotIn
    values:
    - default
scrapeConfigSelector:
  matchExpressions:
  - key: foo
    operator: NotIn
    values:
    - fake
  ```
The scope is limited to its namespace only. I've just double-checked it

i have two VMScrapeConfigs

![image](https://github.com/user-attachments/assets/aa5b5cd9-dfea-4419-b8e5-1add986f281d)

bar has label `bar: foo`

foo-boo has label `foo:boo`

vmagent config:

![image](https://github.com/user-attachments/assets/257affe9-f974-4bc0-9d1c-568a9debbd0b)

And it only sees scrapeConfig in its namespace, i.e., metrics-infrastructure, and not in the monitoring namespace.
