### ISSUE TITLE
How to replace the _time label with  own label in VictoriaLogs?

### ISSUE THREAD

**Issue by jackmachine3d** [VictoriaMetrics/VictoriaMetrics#7757]
### Is your question request related to a specific component?

VictoriaLogs

### Describe the question in detail

I use data injection Promtail to collect logs. I also do the processing and use of the regular expression for parsing
```
    pipeline_stages:
    - regex:
        expression: ^(?P<timestamp>\d{4}\.\d{2}\.\d{2} \d{2}:\d{2}:\d{2}\.\d{3}) \[P:(?P<process_id>\d+)\] \[T:(?P<thread_id>\d+)\] \[(?P<log_level>info|error)\] (?P<log>.+)
    - timestamp:
        source: timestamp
        format: 2006.01.02 03:04:05.000
    - labels:
        timestamp:
        process_id:
        thread_id:
        log_level:
        log:
 ```
The logs are parsed correctly, I see labels in VictoriaLogs. But I can't figure out how to make sure that my timestamp label is used by default?

### Troubleshooting docs

- [X] General - https://docs.victoriametrics.com/troubleshooting/
- [X] vmagent - https://docs.victoriametrics.com/vmagent/#troubleshooting
- [X] vmalert - https://docs.victoriametrics.com/vmalert/#troubleshooting
