### ISSUE TITLE
vmalert: duplicate label name __name__ when pushing to thanos receive

### ISSUE THREAD

**Issue by h4wkmoon** [VictoriaMetrics/VictoriaMetrics#7796]
### Describe the bug

Hi, 

We are in the process for migrating to VM. Currently, Thanos has to stay. 
Therefore, we configured vmagent to push metrics to Thanos Receive, like this : 

```yaml
  remoteWrite:
  - url: http://thanos-receive:19291/api/v1/receive
```
Every now and then, Thanos Receive gives the following errors:

`duplicate labels in the label set\" lset=\"labels:<name:\\\"__name__\\\" value:\\\"ALERTS\\\" > labels:<name:\\\"__name__\\\" value:\\\"ALERTS_FOR_STATE\\\" > labels:<name:\\\"alertgroup\\\" value:\\\"thanos-receive\\\" > labels:<name:\\\"alertname\\\" value:\\\"ThanosReceiveNoUpload\\\" > labels:<name:\\\"alertstate\\\" value:\\\"pending\\\" > labels:<name:\\\"instance\\\" value:\\\"172.18.9.147:10902\\\" > labels:<name:\\\"severity\\\" value:\\\"critical\\\" >`

As you can see, in this label set, there are 2 labels with name __name__: ALERTS and ALERTS_FOR_STATE.
I don't really care about these metrics going to Thanos, or not. I use it for long-term metrics storage (for now). 

I'm more annoyed by the 2 victoria metrics alerts this situation triggers : 
* TooManylog, because vmagent receives errors from thanos receive
* RemoteWrite-something-something-dropped: as vmagent receices errors, it drops the data, as expected.

I tried to drop the metric ALERTS_FOR_STATE like this:

```yaml
  remoteWrite:                                                                                                                                 
  - inlineUrlRelabelConfig:                                                                                                                    
    - action: drop                                                                                                                             
      regex: ALERTS_FOR_STATE                                                                                                                  
      source_labels:                                                                                                                           
      - __name__                                                                                                                               
    url: http://thanos-receive:19291/api/v1/receive   
```
This code does not seem to have any effect.

Is there a way to make these erros go away by avoiding the label duplication, or droping the metrics ?

vmalert version v1.106.1

### To Reproduce

* Configure vmalert, vmagent as described. Nothing fancy.
* Generate alerts (Standard metrics are ok)
* see the errors

### Version

vmalert version v1.106.1
installed on kubernetes by the helm chart and the operator.

I'll try v1.97.1 & v1.107.0

### Used command-line flags

  containers:                                                                                                                                  
  - args:                                                                                                                                      
    - -datasource.url=http://vmselect-main.monitoring.svc.cluster.local.:8481/select/0/prometheus                                              
    - -evaluationInterval=15s                                                                                                                  
    - -external.alert.source=select/0/vmui/#/?g0.expr={{$expr|queryEscape}}                                                                    
    - -external.url=https://victoriametrics.blabla                                                     
    - -http.pathPrefix=/                                                                                                                       
    - -httpListenAddr=:8080                                                                                                                    
    - -notifier.url=http://vmalertmanager-kube-vm-stack-0.vmalertmanager-kube-vm-stack.monitoring.svc.cluster.local.:9093,http://vmalertmanager
-kube-vm-stack-1.vmalertmanager-kube-vm-stack.monitoring.svc.cluster.local.:9093,http://vmalertmanager-kube-vm-stack-2.vmalertmanager-kube-vm-s
tack.monitoring.svc.cluster.local.:9093                                                                                                        
    - -remoteRead.url=http://vmselect-main.monitoring.svc.cluster.local.:8481/select/0/prometheus                                              
    - -remoteWrite.disablePathAppend=true                                                                                                      
    - -remoteWrite.url=http://vmagent-kube-vm-stack.monitoring.svc.cluster.local.:8429/api/v1/write                                            
    - -rule="/etc/vmalert/config/vm-kube-vm-stack-rulefiles-0/*.yaml"                                                                          
    image: onecaas.azurecr.io/victoriametrics/vmalert:v1.97.1
