### ISSUE TITLE
docker swarm discovery incorrectly adds service labels to the tasks

### ISSUE THREAD

**Issue by f41gh7** [VictoriaMetrics/VictoriaMetrics#7800]
### Describe the bug

  Discovery process  doesn't add for `service` metadata labels for the `role: tasks` at `dockerswarm_sd_configs`.  

 Expected output:
```
__meta_dockerswarm_node_role="manager"
__meta_dockerswarm_node_status="ready"
__meta_dockerswarm_service_id="some"
__meta_dockerswarm_service_mode="replicated"
__meta_dockerswarm_service_name="some"
__meta_dockerswarm_task_container_id="some"
__meta_dockerswarm_task_desired_state="running"
```

 Current output:
```
__meta_dockerswarm_node_role="manager"
__meta_dockerswarm_node_status="ready"
__meta_dockerswarm_task_container_id="22f81affa3514940efe7cd7ea409f52839f652f0b596bb25e3cef9aab43c605b"
__meta_dockerswarm_task_desired_state="running"
```

 Missing labels: 
```
__meta_dockerswarm_service_id
__meta_dockerswarm_service_mode
__meta_dockerswarm_service_name
```

### To Reproduce

 Create the following promscrape config:
```yaml
- job_name: "docker_swarm_tasks"
    scheme: "http"
    metrics_path: "/metrics"
    dockerswarm_sd_configs:
    - host: http:/swarm:2375/
      role: tasks
```

### Version

 all versions
