### ISSUE TITLE
VictoriaLogs not using localtime in docker

### ISSUE THREAD

**Issue by sangyye** [VictoriaMetrics/VictoriaMetrics#7816]
### Is your question request related to a specific component?

VictoriaLogs

### Describe the question in detail

Hello,
I have a question or maybe I don’t understand how VictoriaLogs works.
Currently I run VictoriaLogs in docker on my VM to ingest all other logs via rsyslog. This works fine and I started with version 1.0.0. I updated to the latest version today and I noticed that in the vmui the Timestamp in Group look fine but in Tableview they are one hour behind. I was baffled because I set everything on my localtime zone that is Europe/Berlin. So I checked and noticed that the _time field was in UTC, I confirmed it with calling the api via curl, I’m pretty sure they appeared all in my local time before. I’m not sure what happened, the changelog didn’t mention anything and I’m pretty sure as I have set it up 2 weeks ago it was working all in my localtime.

I’m not sure if I just misunderstood the settings or if something is not working correctly? So if somebody could nudge me in the correct direction or has an idea what I’m doing wrong that would be very helpful.
Thanks a lot.

my server time:
```
$ timedatectl
               Local time: Thu 2024-12-12 22:44:34 CET
           Universal time: Thu 2024-12-12 21:44:34 UTC
                 RTC time: Thu 2024-12-12 21:44:34
                Time zone: Europe/Berlin (CET, +0100)
System clock synchronized: yes
              NTP service: active
          RTC in local TZ: no
``` 
Time in docker container
```
$ docker exec -it victorialogs /bin/sh
/ # date
Thu Dec 12 21:47:06 UTC 2024
/ #  
``` 
my config:
```
services:
  victorialogs:
    image: docker.io/victoriametrics/victoria-logs:v1.3.2-victorialogs
    container_name: victorialogs
    command:
      - -syslog.listenAddr.tcp=0.0.0.0:29514
      - -syslog.timezone=Europe/Berlin
      - -syslog.extraFields.tcp='{"source":"syslog"}'
      - -retention.maxDiskSpaceUsageBytes=5GiB
      - -retentionPeriod=1y
      - -loggerTimezone=Europe/Berlin
    volumes:
      - ./vl-data/:/victoria-logs-data
    ports:
      - "127.0.0.1:29514:29514"
      - "127.0.0.1:9428:9428"  
``` 

### Troubleshooting docs

- [X] General - https://docs.victoriametrics.com/troubleshooting/
- [ ] vmagent - https://docs.victoriametrics.com/vmagent/#troubleshooting
- [ ] vmalert - https://docs.victoriametrics.com/vmalert/#troubleshooting

**Comment by tiny-pangolin** [comment]
does the issue still occur if you add to your compose file?
```
environment:
  - TZ=Europe/Berlin
 ```

**Comment by sangyye** [comment]
Hey, thanks for asking, I just tested it and it still doesn’t work like I expect.
```

services:
  victorialogs:
    image: docker.io/victoriametrics/victoria-logs:v1.3.2-victorialogs
    container_name: victorialogs
    environment:
      - TZ=Europe/Berlin
    command:
      - -syslog.listenAddr.tcp=0.0.0.0:29514
      - -syslog.timezone=Europe/Berlin
      - -syslog.extraFields.tcp='{"source":"syslog"}'
      - -retention.maxDiskSpaceUsageBytes=5GiB
      - -retentionPeriod=1y
      - -loggerTimezone=Europe/Berlin
    volumes:
      - ./vl-data/:/victoria-logs-data
    ports:
      - "127.0.0.1:29514:29514"
      - "127.0.0.1:9428:9428"  # <Host Port>:<Container Port>
``` 
And if I enter the container still UTC
```
$ docker exec -it victorialogs /bin/sh
/ # date
Fri Dec 13 15:17:12 UTC 2024
/ #  
``` 
In vmui I can still see that it is saved in UTC and in the Group view it is adding the one hour:
![IMG_0663](https://github.com/user-attachments/assets/0f3ce50d-cd19-4ab3-852f-b76578c87040)
But in tableview it only shows the UTC like if I use curl directly. And I think that wasn’t like this in version 1.0.0 (but I might be wrong about this)
![IMG_0664](https://github.com/user-attachments/assets/6e0cc93c-82c5-429d-ba43-2bae40d93f82)
