### ISSUE TITLE
Pushing logs with vector.dev

### ISSUE THREAD

**Issue by arseny-zinchenko** [VictoriaMetrics/VictoriaMetrics#7824]
### Is your question request related to a specific component?

VictoriaLogs

### Describe the question in detail

I'm trying to add a `sink` to vector.dev with the following config:

```
  sinks:
    test_vector_vmlogs:
      type: loki
      inputs:
        - test_vector_s3
      endpoint: http://atlas-victoriametrics-victoria-logs-single-server:9428/insert/loki/api/v1/push
      encoding:
        codec: json
      labels:
        cluster: test
```

But Vector fails with the following error:

```
2024-12-13T15:04:35.200895Z ERROR vector::topology::builder: msg="Healthcheck failed." error=A non-successful status returned: 400 Bad Request component_kind="sink" component_type="loki" component_id=test_vector_vmlogs
2024-12-13T15:05:27.608386Z ERROR sink{component_kind="sink" component_id=test_vector_vmlogs component_type=loki}:request{request_id=1}: vector::sinks::util::retries: Non-retriable error; dropping the request. error=Server responded with an error: 400 Bad Request internal_log_rate_limit=true
```

Also, tried to set `endpoint: http://atlas-victoriametrics-victoria-logs-single-server:9428`, but got the same error.
If `endpoint` is set as `endpoint: http://atlas-victoriametrics-loki-gateway:80`, it's working.

### Troubleshooting docs

- [ ] General - https://docs.victoriametrics.com/troubleshooting/
- [ ] vmagent - https://docs.victoriametrics.com/vmagent/#troubleshooting
- [ ] vmalert - https://docs.victoriametrics.com/vmalert/#troubleshooting
