### ISSUE TITLE
vmrestore creates unexpected subdirectory structure in cluster mode

### ISSUE THREAD

**Issue by nicacioliveira** [VictoriaMetrics/VictoriaMetrics#7841]
### Describe the bug

When using vmrestore in a VictoriaMetrics cluster setup, there's an issue with the directory structure of restored data. The restore process maintains the backup path structure inside the destination directory, which creates an unnecessary nested directory structure.

## Additional Context
- This issue only occurs in cluster mode where each vmstorage node requires its own backup directory
- The current behavior forces us to add extra steps in the restore process to fix the directory structure
- A possible solution would be to have vmrestore strip the vmstorage node directory name while maintaining the internal backup structure

## Environment
- VictoriaMetrics Cluster
- Using vmbackup/vmrestore v1.100.1
- Kubernetes with VictoriaMetrics Operator

## Current Behavior
When running vmrestore in a cluster environment, where each vmstorage node has its own backup directory in S3, the restore process creates an unexpected nested directory structure.

For example, with this backup structure in S3:
```plaintext
s3://bucket/backups/
  ├── vmstorage-0/
  │   ├── data/
  │   ├── indexdb/
  │   └── metadata/
  ├── vmstorage-1/
  └── vmstorage-2/
```

When restoring using vmrestore:
```sh
/vmrestore-prod \
    -src="s3://bucket/backups/vmstorage-0" \
    -storageDataPath="/vm-data" \
    -skipBackupCompleteCheck
```

The resulting structure becomes:
```plaintext
/vm-data/
  └── vmstorage-0/
      ├── data/
      ├── indexdb/
      └── metadata/
```

## Expected Behavior
The expected structure should be:
```plaintext
/vm-data/
  ├── data/
  ├── indexdb/
  └── metadata/
```

## Reproduction Steps
1. Set up a VictoriaMetrics cluster with multiple vmstorage nodes using the VictoriaMetrics Operator
2. Configure the backup process in the VMCluster CR:
```yaml
spec:
  vmstorage:
    backup:
      enabled: true
      image: vmbackup:v1.100.1
      backupDst: "s3://bucket/backups"
```

3. After backup is created, try to restore using vmrestore in an initContainer:
```yaml
spec:
  vmstorage:
    initContainers:
      - name: vmrestore
        image: vmrestore:v1.100.1
        volumeMounts:
          - name: vmstorage-db
            mountPath: /vm-data
        command:
          - /vmrestore-prod
          - -src=s3://bucket/backups/vmstorage-0
          - -storageDataPath=/vm-data
          - -skipBackupCompleteCheck
```

## Current Workaround
Currently, we need to move files in the initContainer after restoring:
```sh
mv /vm-data/vmstorage-0/* /vm-data/
rmdir /vm-data/vmstorage-0
```

### Version

v1.100.1
