### ISSUE TITLE
Old Kubernetes SD endpoints are still "discovered" and scraped despite no longer existing

### ISSUE THREAD

**Issue by gravese** [VictoriaMetrics/VictoriaMetrics#7851]
### Is your question request related to a specific component?

vmagent

### Describe the question in detail

I use kubernetes eks cluster，When I restarted kube-state-metrics, I found that vmgent will scraped old no longer existing kube-state-metrics endpoint, resulting in the capture of pod metrics that had already occurred before, such as oomkilled and restart. Why is this?

```yaml
 - job_name: 'kubernetes-service-endpoints'
      stream_parse: true
      kubernetes_sd_configs:
      - role: endpoints
      relabel_configs:
      - source_labels: [__meta_kubernetes_service_annotation_prometheus_io_scrape]
        action: keep
        regex: true
      - source_labels: [__meta_kubernetes_service_annotation_prometheus_io_scheme]
        action: replace
        target_label: __scheme__
        regex: (https?)
      - source_labels: [__meta_kubernetes_service_annotation_prometheus_io_path]
        action: replace
        target_label: __metrics_path__
        regex: (.+)
      - source_labels: [__address__, __meta_kubernetes_service_annotation_prometheus_io_port]
        action: replace
        target_label: __address__
        regex: ([^:]+)(?::\d+)?;(\d+)
        replacement: $1:$2
      - action: labelmap
        regex: __meta_kubernetes_service_label_(.+)
      metric_relabel_configs:
      # - regex: uid
      #   action: labeldrop
      # - regex: container_id
      #   action: labeldrop
      # - regex: image
      #   action: labeldrop
      # - regex: image_id
      #   action: labeldrop
      # - regex: label_pod_template_hash
      #   action: labeldrop
      # - regex: instance
      #   action: labeldrop
      # - regex: app
      #   action: labeldrop          
      - source_labels: [__name__]
        regex: '(kube_pod_container_status_waiting_reason|kube_pod_container_status_terminated_reason)'
        action: drop
```

### Troubleshooting docs

- [ ] General - https://docs.victoriametrics.com/troubleshooting/
- [ ] vmagent - https://docs.victoriametrics.com/vmagent/#troubleshooting
- [ ] vmalert - https://docs.victoriametrics.com/vmalert/#troubleshooting

**Comment by Haleygo** [comment]
Hi,
>resulting in the capture of pod metrics that had already occurred before, such as oomkilled and restart. 

If those pods still have endpoints, vmagent will discover and scrape them. To scrape only running pods, you can add a relabel config:
```
relabel_configs:
- source_labels: [__meta_kubernetes_pod_ready]
  action: keep
  regex: true
```
