### ISSUE TITLE
vmagent target relabel produce wrong value

### ISSUE THREAD

**Issue by xiaozongyang** [VictoriaMetrics/VictoriaMetrics#7858]
### Describe the bug

We deploy vmagent in k8s, and there are two type pods in the k8s cluster, i.e. long-running service and short-lived jobs. When the job pod finished, its status turned into `Completed` but the pod isn't deleted, and its IP was re-allocated to another service pod. So we got two pods with same IP, one is the completed job pod and the other is the running service pod.

Vmagent scrape metric samples from the running service pod every 15s, but when generating a new label pod by relabling from k8s meta, we got two values.

Following are the detailed information,

- orignal metric samples exported by the service pod
```
arh_managed_card_total{card_type="all_IDP_card_count"} 1
arh_managed_card_total{card_type="all_arh_managed_card_count"} 2
arh_managed_card_total{card_type="arh_stream_used_count_sum"} 3
arh_managed_card_total{card_type="bad_card_count"} 4
```
- query result returned from the vmselect
<img width="1664" alt="Clipboard_Screenshot_1734443456" src="https://github.com/user-attachments/assets/5171a096-f921-4b6a-9e3e-ae99d3e87e7d" />

- relabel config
```yaml
  - source_labels:
    - __meta_kubernetes_pod_name
    target_label: pod
```

### To Reproduce

1. run a k8s job and wait it finished
2. start a new pod with same IP
3. scrape by vmagent and relabel pod from 

### Version

`vmagent-20240301-013655-tags-v1.99.0-0-g9cd4b0537`

### Used command-line flags

`/vmagent-prod -httpListenAddr=:8429 -memory.allowedPercent=80 -promscrape.config=/etc/vmagent/config_out/vmagent.env.yaml -promscrape.maxScrapeSize=500000000 -promscrape.seriesLimitPerTarget=1000000 -promscrape.streamParse=true -remoteWrite.maxDiskUsagePerURL=1073741824 -remoteWrite.tmpDataPath=/vmagent_pq/vmagent-remotewrite-data -remoteWrite.url=http://vm-victoria-metrics-cluster-vminsert.mon-sys.svc:8480/insert/0/prometheus -promscrape.cluster.membersCount=10 -promscrape.cluster.memberNum=0`

**Comment by zekker6** [comment]
Hello @xiaozongyang, could you please share your discovery and relabeling configuration for these targets?
This will help to reproduce an issue for testing.

**Comment by xiaozongyang** [comment]
@zekker6 
The config from vmagnet is pasted here
```yaml
- job_name: serviceScrape/prom02/app-metric/0
  scrape_interval: 15s
  metrics_path: /metrics
  relabel_configs:
  - action: keep
    source_labels: [__meta_kubernetes_service_label_type]
    regex: app
  - action: keep
    source_labels: [__meta_kubernetes_endpoint_port_name]
    regex: app-metric
  - source_labels: [__meta_kubernetes_endpoint_address_target_kind, __meta_kubernetes_endpoint_address_target_name]
    separator: ;
    target_label: node
    regex: Node;(.*)
    replacement: ${1}
  - source_labels: [__meta_kubernetes_endpoint_address_target_kind, __meta_kubernetes_endpoint_address_target_name]
    separator: ;
    target_label: pod
    regex: Pod;(.*)
    replacement: ${1}
  - source_labels: [__meta_kubernetes_pod_name]
    target_label: pod
  - source_labels: [__meta_kubernetes_pod_container_name]
    target_label: container
  - source_labels: [__meta_kubernetes_namespace]
    target_label: namespace
  - source_labels: [__meta_kubernetes_service_name]
    target_label: service
  - source_labels: [__meta_kubernetes_service_name]
    target_label: job
    replacement: ${1}
  - source_labels: [__meta_kubernetes_service_label_type]
    target_label: job
    regex: (.+)
    replacement: ${1}
  - target_label: endpoint
    replacement: app-metric
  - action: replace
    source_labels: [__meta_kubernetes_pod_label_app]
    target_label: application
  - action: replace
    source_labels: [__meta_kubernetes_pod_label_idp_infra_xaminim_com_app]
    target_label: app
  - action: replace
    source_labels: [__meta_kubernetes_pod_label_idp_infra_xaminim_com_release]
    target_label: release
  - action: replace
    source_labels: [__meta_kubernetes_pod_label_idp_infra_xaminim_com_lane]
    target_label: lane
  metric_relabel_configs:
  - action: drop
    source_labels: [__name__]
    regex: create_state
  - action: drop
    source_labels: [__name__]
    regex: ads_tts_latency_bucket
  - action: drop
    source_labels: [__name__]
    regex: chunk_text_latency_bucket
  - action: drop
    source_labels: [__name__]
    regex: chunk_audio_latency_bucket
  - action: drop
    source_labels: [__name__]
    regex: redis_store_latency_bucket
  - action: drop
    source_labels: [__name__]
    regex: msg_consume_latency_bucket
  - action: drop
    source_labels: [__name__]
    regex: msg_consume_latency_bucket
  - action: drop
    source_labels: [__name__]
    regex: redis_recv_latency_bucket
  - action: drop
    source_labels: [__name__]
    regex: redis_msg_size_bucket
  - action: drop
    source_labels: [__name__]
    regex: algeng_load_balance_expire_time_count
  - action: drop
    source_labels: [__name__]
    regex: img_valve_latency_bucket
  kubernetes_sd_configs:
  - role: endpoints
```
