### ISSUE TITLE
How to scrape k3s etcd metrics?

### ISSUE THREAD

**Issue by maaft** [VictoriaMetrics/VictoriaMetrics#7877]
### Describe the question in detail

I setup k3s etcd metrics scraping with this config (k8s-stack):
```yaml
       kubeEtcd:
          endpoints: # controlplane IPs
          - 10.253.0.101
          - 10.254.0.101
          - 10.255.0.101
          vmScrape:
            spec:
              endpoints:
              - bearerTokenFile: /var/run/secrets/kubernetes.io/serviceaccount/token
                port: http-metrics
                scheme: https
                tlsConfig:
                  caFile: /var/run/secrets/kubernetes.io/serviceaccount/ca.crt
                  insecureSkipVerify: true
                metricRelabelConfigs:
                - sourceLabels: [ "__name__" ]
                  regex: "(etcd|grpc|rest_client|process|go)_(.+)"
                  action: keep
```

![image](https://github.com/user-attachments/assets/b5e6b71b-d1b2-4b6c-9cc2-1c2d2bcc2996)

But the vmagent cannot scrape these endpoint since some certificate is missing. Not sure if this is k3s related or vm related. But i don't find any ressources that help me.

What certificate is k3s requiring? And how can I supply the correct certificate?

All other k3s metrics are correctly scraped by the way. Only etcd seems to make issues.

Example for a working config for kubeProxy:
```yaml
        kubeProxy:
          endpoints:
          - 10.253.0.101
          - 10.254.0.101
          - 10.255.0.101
          vmScrape:
            spec:
              endpoints:
              - bearerTokenFile: /var/run/secrets/kubernetes.io/serviceaccount/token
                port: http-metrics
                scheme: https
                tlsConfig:
                  caFile: /var/run/secrets/kubernetes.io/serviceaccount/ca.crt
                  insecureSkipVerify: true
                metricRelabelConfigs:
                - sourceLabels: [ "__name__" ]
                  regex: "(kubeproxy|rest_client|process|go)_(.+)"
                  action: keep
```

### Troubleshooting docs

- [ ] General - https://docs.victoriametrics.com/troubleshooting/
- [X] vmagent - https://docs.victoriametrics.com/vmagent/#troubleshooting
- [ ] vmalert - https://docs.victoriametrics.com/vmalert/#troubleshooting
