### ISSUE TITLE
The image of the initcontainer config-reloader in Vmagent is set as a configurable item in the air gap environment

### ISSUE THREAD

**Issue by JaeGerW2016** [VictoriaMetrics/VictoriaMetrics#7942]
### Describe the bug

vmagent cannot connect to the Internet during the deployment process, resulting in failure to pull the initcontainer config-reloader image prompt: Init: ErrImagePull

### To Reproduce

```
root@mynode # kubectl logs vmagent-vmagent-select-all-7468fdf797-g4fkf
Defaulted container "config-reloader" out of: config-reloader, vmagent, config-init (init)
Error from server (BadRequest): container "config-reloader" in pod "vmagent-vmagent-select-all-7468fdf797-g4fkf" is waiting to start: PodInitializing
```

### Version

v1.108.1

**Comment by f41gh7** [comment]
Hello, could you please attach more detailed log with error? Which image Kubernetes cannot pull?

 Operator supports global and local overrides for container images: 

https://docs.victoriametrics.com/operator/vars/index.html

**Comment by JaeGerW2016** [comment]
When I enable custom env parameters `VM_CUSTOMCONFIGRELOADERIMAGE` in deployment, vmagent still reports the same error : `Init:ImagePullBackOff`


`vm-vmagent.yaml`
```
apiVersion: operator.victoriametrics.com/v1beta1
kind: VMAgent
metadata:
  name: vmagent-select-all
spec:
  # ...
  selectAllByDefault: true
  image:
    repository: privateimagerepository/vmagent
    tag: v1.108.1
    pullPolicy: IfNotPresent
  remoteWrite:
    - url: "http://vmsingle-victoria-metrics-single-server.vm-single.svc:8429/api/v1/write"
```


`victoriametrics-operator-deployment.yaml`  

```
...
# Source: victoria-metrics-operator/templates/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: victoria-metrics-operator
  namespace: vm-single
  labels: 
    app.kubernetes.io/instance: victoria-metrics-operator
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: victoria-metrics-operator
    app.kubernetes.io/version: v0.51.2
    helm.sh/chart: victoria-metrics-operator-0.40.2
spec:
  replicas: 1
  selector:
    matchLabels: 
      app.kubernetes.io/instance: victoria-metrics-operator
      app.kubernetes.io/name: victoria-metrics-operator
  template:
    metadata:
      labels: 
        app.kubernetes.io/instance: victoria-metrics-operator
        app.kubernetes.io/managed-by: Helm
        app.kubernetes.io/name: victoria-metrics-operator
    spec:
      automountServiceAccountToken: true
      securityContext: 
        {}
      serviceAccountName: victoria-metrics-operator
      containers:
        - name: operator
          image: privateimagerepository/victoria-metrics-operator:v0.51.2
          imagePullPolicy: IfNotPresent
          env:
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: OPERATOR_NAME
              value: victoria-metrics-operator
            - name: VM_ENABLEDPROMETHEUSCONVERTEROWNERREFERENCES
              value: "false"
            - name: VM_CUSTOMCONFIGRELOADERIMAGE
              value: "privateimagerepository/operator:config-reloader-v0.51.2"
...

```

`kubectl logs vmagent-xxx`

```
root@worknode /opt/victoria-metrics-single # kubectl logs vmagent-vmagent-select-all-7468fdf797-q7cf5
Defaulted container "config-reloader" out of: config-reloader, vmagent, config-init (init)
Error from server (BadRequest): container "config-reloader" in pod "vmagent-vmagent-select-all-7468fdf797-q7cf5" is waiting to start: PodInitializing
```
