### ISSUE TITLE
Grafana 9 cannot retrieve monitoring data through vmselect

### ISSUE THREAD

**Issue by leon0306** [VictoriaMetrics/VictoriaMetrics#7951]
### Is your question request related to a specific component?

vmselect, vminsert, grafana, prometheus

### Describe the question in detail

In my environment, as shown in the diagram, I have deployed the relevant monitoring components. I can retrieve monitoring data from the Prometheus backend using Grafana normally, but I am unable to get data from vmselect.

![image](https://github.com/user-attachments/assets/48c52ad9-f0b7-4a11-b9b6-3b4db7b925a6)

vmclusterVersion: 1.102.1
promethues: 2.40.7
grafana: 9.0.1

This is the configuration for the monitoring section regarding vmcluster.
```
prometheus:
  enabled: true
  remoteWrite:
  - url: "http://vm-cluster-vminsert.kube-system:8480/insert/0/prometheus"
grafana:
  enabled: true
  datasourceUrl: "http://vm-cluster-vmselect.kube-system:8481/select/0/promethues"
```

vmselect logs:
![image](https://github.com/user-attachments/assets/4036bd07-177b-496f-904b-b63aa1062848)

`unsupported path requested` mean for what? how can i resolve this?

![image](https://github.com/user-attachments/assets/eaf48887-8465-4aa3-9d78-222d2d0e4bbf)
![image](https://github.com/user-attachments/assets/e4fe0490-66f5-4b6e-8c9f-00e0efdd8386)

### Troubleshooting docs

- [X] General - https://docs.victoriametrics.com/troubleshooting/
- [ ] vmagent - https://docs.victoriametrics.com/vmagent/#troubleshooting
- [ ] vmalert - https://docs.victoriametrics.com/vmalert/#troubleshooting
