### ISSUE TITLE
[VMagent] Clash of  VMagent auto-metrics with multiple metrics_path on the same port in service/podMonitor discovery

### ISSUE THREAD

**Issue by DmitrySafonov** [VictoriaMetrics/VictoriaMetrics#8000]
### Describe the bug

When using ServiceMonitor/PodMonitor discovery for metrics collection, a clash can occur for vmagent auto-metrics if a single monitor is configured with multiple endpoints that share the same port but use different metrics_path values.

 By default, the metrics_path label is not added to the final metrics, causing the label set (`instance`, `job`, `endpoint`, etc.) to be identical for different paths. 
Before relabeling, jobs have different names by endpoint (e.g., `job1/0`, `job1/2`, …, `job1/n`), but they are relabeled—according to the Prometheus Operator specification—as namespace/name for PodMonitors or service_name for ServiceMonitors. 

As a result, vmagent auto-metrics (such as `up` or `series_added`) overwrite each other, leading to incorrect or confusing values.

### To Reproduce

1) Configure  service/pod monitor discovery to scrape a single service/pod that:
   Exposes the same port.
   Has different metrics_path values (e.g., /metrics and /internal-metrics).
   Has different metrics samples count in endpoints
2) Ensure that metrics_path is not explicitly included as a label in your config (i.e., it’s not added by default).
3) Inspect the collected metrics and observe that they clash and overwrite each other.

### Version

victoria metrics cluster v1.104.0

**Comment by DmitrySafonov** [comment]
I can propose a solution:

```diff
diff --git a/lib/promscrape/scrapework.go b/lib/promscrape/scrapework.go
index 0774dba50..2636f8467 100644
--- a/lib/promscrape/scrapework.go
+++ b/lib/promscrape/scrapework.go
@@ -847,31 +847,37 @@ func isAutoMetric(s string) bool {
 }
 
 func (sw *scrapeWork) addAutoMetrics(am *autoMetrics, wc *writeRequestCtx, timestamp int64) {
-	sw.addAutoTimeseries(wc, "scrape_duration_seconds", am.scrapeDurationSeconds, timestamp)
-	sw.addAutoTimeseries(wc, "scrape_response_size_bytes", float64(am.scrapeResponseSize), timestamp)
+	autoTags := []parser.Tag(nil)
+	metricsPath := sw.Config.Labels.Get("__metrics_path__")
+	if len(metricsPath) > 0 {
+		autoTags = []parser.Tag{{Key: "metrics_path", Value: metricsPath}}
+	}
+
+	sw.addAutoTimeseries(wc, "scrape_duration_seconds", am.scrapeDurationSeconds, timestamp, autoTags)
+	sw.addAutoTimeseries(wc, "scrape_response_size_bytes", float64(am.scrapeResponseSize), timestamp, autoTags)
 	if sampleLimit := sw.Config.SampleLimit; sampleLimit > 0 {
 		// Expose scrape_samples_limit metric if sample_limit config is set for the target.
 		// See https://github.com/VictoriaMetrics/operator/issues/497
-		sw.addAutoTimeseries(wc, "scrape_samples_limit", float64(sampleLimit), timestamp)
+		sw.addAutoTimeseries(wc, "scrape_samples_limit", float64(sampleLimit), timestamp, autoTags)
 	}
-	sw.addAutoTimeseries(wc, "scrape_samples_post_metric_relabeling", float64(am.samplesPostRelabeling), timestamp)
-	sw.addAutoTimeseries(wc, "scrape_samples_scraped", float64(am.samplesScraped), timestamp)
-	sw.addAutoTimeseries(wc, "scrape_series_added", float64(am.seriesAdded), timestamp)
+	sw.addAutoTimeseries(wc, "scrape_samples_post_metric_relabeling", float64(am.samplesPostRelabeling), timestamp, autoTags)
+	sw.addAutoTimeseries(wc, "scrape_samples_scraped", float64(am.samplesScraped), timestamp, autoTags)
+	sw.addAutoTimeseries(wc, "scrape_series_added", float64(am.seriesAdded), timestamp, autoTags)
 	if sl := sw.seriesLimiter; sl != nil {
-		sw.addAutoTimeseries(wc, "scrape_series_current", float64(sl.CurrentItems()), timestamp)
-		sw.addAutoTimeseries(wc, "scrape_series_limit_samples_dropped", float64(am.seriesLimitSamplesDropped), timestamp)
-		sw.addAutoTimeseries(wc, "scrape_series_limit", float64(sl.MaxItems()), timestamp)
+		sw.addAutoTimeseries(wc, "scrape_series_current", float64(sl.CurrentItems()), timestamp, autoTags)
+		sw.addAutoTimeseries(wc, "scrape_series_limit_samples_dropped", float64(am.seriesLimitSamplesDropped), timestamp, autoTags)
+		sw.addAutoTimeseries(wc, "scrape_series_limit", float64(sl.MaxItems()), timestamp, autoTags)
 	}
-	sw.addAutoTimeseries(wc, "scrape_timeout_seconds", sw.Config.ScrapeTimeout.Seconds(), timestamp)
-	sw.addAutoTimeseries(wc, "up", float64(am.up), timestamp)
+	sw.addAutoTimeseries(wc, "scrape_timeout_seconds", sw.Config.ScrapeTimeout.Seconds(), timestamp, autoTags)
+	sw.addAutoTimeseries(wc, "up", float64(am.up), timestamp, autoTags)
 }
 
 // addAutoTimeseries adds automatically generated time series with the given name, value and timestamp.
 //
 // See https://prometheus.io/docs/concepts/jobs_instances/#automatically-generated-labels-and-time-series
-func (sw *scrapeWork) addAutoTimeseries(wc *writeRequestCtx, name string, value float64, timestamp int64) {
+func (sw *scrapeWork) addAutoTimeseries(wc *writeRequestCtx, name string, value float64, timestamp int64, autoTags []parser.Tag) {
 	sw.tmpRow.Metric = name
-	sw.tmpRow.Tags = nil
+	sw.tmpRow.Tags = autoTags
 	sw.tmpRow.Value = value
 	sw.tmpRow.Timestamp = timestamp
 	sw.addRowToTimeseries(wc, &sw.tmpRow, timestamp, false)

```

But it contradicts the [Prometheus contract](https://prometheus.io/docs/concepts/jobs_instances/#automatically-generated-labels-and-time-series) for auto-metrics.

**Comment by f41gh7** [comment]
Hello, I don't think this issue is related to the vmagent itself. The problem is with operator and how it builds `job` label. 

 The most efficient solution is to to add a an additional relabel config for this particular jobs, that explicitly adds some suffix to the job.

 Consider the following example:


```yaml
apiVersion: operator.victoriametrics.com/v1beta1
kind: VMServiceScrape
metadata:
  name: example-relabel-metrics
  namespace: default
spec:
  endpoints:
    - path: /metrics
      port: http
    - path: /v1/metrics
      port: http
      relabel_configs:
        - source_labels: [job]
          target_label: job
          replacement: ${1}-extra-suffix
          regex: (.+)
  namespaceSelector: {}
  selector:
    matchLabels:
      app.kubernetes.io/component: monitoring
      app.kubernetes.io/instance: example-vmagent
      app.kubernetes.io/name: vmagent
      managed-by: vm-operator
```

 As an alternative, it's possible to create a global relabeling config, that adds an artifical label from `__metrics_path__` variable:

```yaml
apiVersion: operator.victoriametrics.com/v1beta1
kind: VMAgent
metadata:
  name: example-relabel-path
  namespace: default
spec:
  serviceScrapeRelabelTemplate:
  - source_labels: [__metrics_path__]
    target_label: metrics_source_path
  podScrapeRelabelTemplate:
  - source_labels: [__metrics_path__]
    target_label: metrics_source_path
```

 I don't think that proposed solution with changes to the vmagent itself is good. It will trigger new timeseries creation for each scrapped target and it also breaks compatibility with Prometheus auto timeseries format.
