### ISSUE TITLE
Missing metrics from ArgoCD

### ISSUE THREAD

**Issue by esn89** [VictoriaMetrics/VictoriaMetrics#8006]
### Describe the bug

When I follow the creation of metrics endpoint from [here](https://argo-cd.readthedocs.io/en/stable/operator-manual/metrics/)

Along with a scrape config:

```yaml
apiVersion: v1
data:
  scrape.yml: |
    global:
      scrape_interval: 15s
    scrape_configs:
    - job_name: argocd-metrics
      metrics_path: /metrics
      static_configs:
      - targets:
        - argocd-application-controller-metrics.argocd.svc.cluster.local:8082
    - job_name: argocd-repo-server
      metrics_path: /metrics
      static_configs:
      - targets:
        - argocd-repo-server-metrics.argocd.svc.cluster.local:8084
    - job_name: argocd-server-metrics
      metrics_path: /metrics
      static_configs:
      - targets:
        - argocd-server-metrics.argocd.svc.cluster.local:8083
    - job_name: argocd-applicationset
      metrics_path: /metrics
      static_configs:
      - targets:
        - argocd-applicationset-controller-metrics.argocd.svc.cluster.local:8080
kind: ConfigMap
metadata:
  name: victoria-metrics-single-server-scrapeconfig
  namespace: vm
```

I am not getting the full picture of the clusters that I have hooked up to ArgoCD (around 60 or so).

VictoriaMetrics only reports 24, when I port forward the service and curl:

`kubectl port-forward svc/argocd-application-controller-metrics -n argocd 8082:8082` and did a grep:

```
curl localhost:8082/metrics | grep argocd_cluster_info | wc -l
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  416k    0  416k    0     0   9.8M      0 --:--:-- --:--:-- --:--:--  9.9M
24
```

And on the metrics explorer dashboard, it only shows 10, but also shows that a few days ago, it had +56 more.  But somehow somewhere, they disappeared:

[image](https://imgur.com/a/59yfCav)

Version of VictoriaMetrics I am using it: 1.108.1

### To Reproduce

scrape config:

```yaml
apiVersion: v1
data:
  scrape.yml: |
    global:
      scrape_interval: 15s
    scrape_configs:
    - job_name: argocd-metrics
      metrics_path: /metrics
      static_configs:
      - targets:
        - argocd-application-controller-metrics.argocd.svc.cluster.local:8082
    - job_name: argocd-repo-server
      metrics_path: /metrics
      static_configs:
      - targets:
        - argocd-repo-server-metrics.argocd.svc.cluster.local:8084
    - job_name: argocd-server-metrics
      metrics_path: /metrics
      static_configs:
      - targets:
        - argocd-server-metrics.argocd.svc.cluster.local:8083
    - job_name: argocd-applicationset
      metrics_path: /metrics
      static_configs:
      - targets:
        - argocd-applicationset-controller-metrics.argocd.svc.cluster.local:8080
kind: ConfigMap
metadata:
  name: victoria-metrics-single-server-scrapeconfig
  namespace: vm
```

Deploy ArgoCD with metrics enabled:

```yaml
  source:
    chart: argo-cd
    repoURL: https://argoproj.github.io/argo-helm
    targetRevision: 7.6.12
    helm:
          params:
          - name: controller.metrics.enabled
             value: "true"
          - name: server.metrics.enabled
             value: "true"
          - name: repoServer.metrics.enabled
             value: "true"
          - name: applicationSet.metrics.enabled
             value: "true"
 ```

Make sure the endpoints are up:

 ```
 kubectl get svc -n argocd | grep metrics
argocd-application-controller-metrics      ClusterIP   172.21.42.224   <none>        8082/TCP            3d6h
argocd-applicationset-controller-metrics   ClusterIP   172.21.35.4     <none>        8080/TCP            3d5h
argocd-repo-server-metrics                 ClusterIP   172.21.42.97    <none>        8084/TCP            3d5h
argocd-server-metrics                      ClusterIP   172.21.40.68    <none>        8083/TCP            3d5h
```

Then explore the metric of `argocd_cluster_info`

### Version

v1.108.1
