### ISSUE TITLE
Proposal vmalert: log scrape errors with level `warning`.

### ISSUE THREAD

**Issue by zbindenren** [VictoriaMetrics/VictoriaMetrics#803]
**Is your feature request related to a problem? Please describe.**
Currently we have setup the following alerts for victoria mertrics:

```yaml
...
      - alert: VictoriaMetricsLogErrors
        expr: increase(vm_log_messages_total{level="error",app_version!=""}[5m]) > 0
        labels:
          priority: P2
        annotations:
          description: Something went wrong. Check VictoriaMetrics logs.
          summary: "VictoriaMetrics logging too many errors."
...
```

This worked pretty well until we deployed vmagent on our kubernetes clusters. Since there are some users configuring wrong ports or metric endpoints on their deployment, the above alert is triggered, because vmagent logs scrape errors with level `error`.

**Describe the solution you'd like**
It would be great if scrape errors get logged with level `warning` (or `info` if `warning` level does not exist). Remote write errors should still be logged with level `error`.

**Describe alternatives you've considered**
Currently we disabled alerts for all vmagents. But doing so we do not see wrong configured remote_write endpoints and other important errors.

I am willing to create a pull request if this gets accepted.
