### ISSUE TITLE
Potential Memory Leak in VMAgent v1.105 / v1.108

### ISSUE THREAD

**Issue by vhajdukd** [VictoriaMetrics/VictoriaMetrics#8036]
### Describe the bug

We observe container memory to increase over time (days) in case of vmagent component. Gathered data to help with investigation, pod is running only vmagent container and we use official vmagent image in version 1.105.

helm-chart: 0.14.7
image-tag: v1.105.0

Gathered pprof, pmap, metrics, cgroup mem-in-use, config (there was a small delay between them):
![Image](https://github.com/user-attachments/assets/61bad915-d2c5-4041-acf4-a9fa888bfb99)

pmap
<img width="1496" alt="Image" src="https://github.com/user-attachments/assets/3ab3e541-d732-430f-acc3-afe7d39984c8" />

rss usage over time
<img width="1473" alt="Image" src="https://github.com/user-attachments/assets/f442b718-e44d-4ab3-acdb-3e493f48cd4c" />

mem over time by container
<img width="1473" alt="Image" src="https://github.com/user-attachments/assets/5d9de04a-9e11-403e-8c6e-a47e429657b3" />

cgroup mem
<img width="705" alt="Image" src="https://github.com/user-attachments/assets/6538d1f1-e30e-4dda-9ebc-f7f96bf73954" />

chart config (few things redacted due to confidentiality):
```
image:
  tag: v1.105.0
fullnameOverride: vmagent-scrape

replicaCount: 3

statefulSet:
  enabled: true
  clusterMode: true

serviceAccount:
  create: true
  annotations:
    eks.amazonaws.com/role-arn: <<REDACTED>>
  name: vmagent-scrape

service:
  enabled: true
  annotations:
    prometheus.io/scrape: 'true'
    prometheus.io/port: '8429'
  labels: {}
  type: NodePort

ingress:
  enabled: false

resources:
  limits:
    cpu: 400m
    memory: 450Mi
  requests:
    cpu: 240m
    memory: 280Mi
    ephemeral-storage: 4Gi

rbac:
  create: true
  pspEnabled: true

podDisruptionBudget:
  enabled: true
  minAvailable: 40%
  selector:
    matchLabels:
      app.kubernetes.io/instance: vmagent-scrape

affinity:
  podAntiAffinity:
    preferredDuringSchedulingIgnoredDuringExecution:
      - weight: 100
        podAffinityTerm:
          labelSelector:
            matchLabels:
              app.kubernetes.io/instance: vmagent-scrape
          topologyKey: kubernetes.io/hostname
topologySpreadConstraints:
  - maxSkew: 1
    topologyKey: topology.kubernetes.io/zone
    whenUnsatisfiable: ScheduleAnyway
    labelSelector:
      matchLabels:
        app.kubernetes.io/instance: vmagent-scrape

remoteWrite:
  - url: <<REDACTED>>

extraArgs:
  remoteWrite.disableOnDiskQueue: true
  remoteWrite.dropSamplesOnOverload: true
  loggerLevel: WARN
  promscrape.streamParse: true
  promscrape.suppressScrapeErrors: true
  promscrape.suppressDuplicateScrapeTargetErrors: true
  loggerErrorsPerSecondLimit: 20
  promscrape.discovery.concurrency: 200
  promscrape.maxDroppedTargets: 100000

config:
  global:
    scrape_interval: 30s
    scrape_timeout: 10s
  scrape_configs:
    - job_name: kubernetes-nodes
      kubernetes_sd_configs:
        - role: node
      scheme: https
      tls_config:
        ca_file: /var/run/secrets/kubernetes.io/serviceaccount/ca.crt
      bearer_token_file: /var/run/secrets/kubernetes.io/serviceaccount/token

      relabel_configs:
        - action: labelmap
          regex: __meta_kubernetes_node_label_(.+)
        - target_label: __address__
          replacement: kubernetes.default.svc:443
        - source_labels: [__meta_kubernetes_node_name]
          regex: (.+)
          target_label: __metrics_path__
          replacement: /api/v1/nodes/${1}/proxy/metrics
        - action: replace
          replacement: $1
          source_labels:
            - __meta_kubernetes_node_label_kubernetes_io_hostname
          target_label: hostname

      metric_relabel_configs:
        - action: labelmap
          regex: exported_(.+)
        - regex: k8s_io_cloud_provider_aws|failure_domain_beta_kubernetes_io_.*|kubernetes_io_hostname|topology_kubernetes_.*|beta_kubernetes_.*
          action: labeldrop

    - job_name: kubernetes-pods
      kubernetes_sd_configs:
        - role: pod

      relabel_configs:
        - action: drop
          source_labels: [__meta_kubernetes_pod_container_init]
          regex: true
        - action: keep_if_equal
          source_labels: [__meta_kubernetes_pod_annotation_prometheus_io_port, __meta_kubernetes_pod_container_port_number]
        - source_labels: [__meta_kubernetes_pod_annotation_prometheus_io_scrape]
          action: keep
          regex: true
        - source_labels: [__meta_kubernetes_pod_annotation_prometheus_io_path]
          action: replace
          target_label: __metrics_path__
          regex: (.+)
        - source_labels:
            [__address__, __meta_kubernetes_pod_annotation_prometheus_io_port]
          action: replace
          regex: ([^:]+)(?::\d+)?;(\d+)
          replacement: $1:$2
          target_label: __address__
        - action: labelmap
          regex: __meta_kubernetes_pod_label_(.+)
        - source_labels: [__meta_kubernetes_pod_name]
          target_label: pod
        - source_labels: [__meta_kubernetes_pod_container_name]
          target_label: container
        - source_labels: [__meta_kubernetes_namespace]
          target_label: namespace
        - source_labels: [__meta_kubernetes_pod_name]
          action: replace
          target_label: kubernetes_pod_name
        - source_labels: [__meta_kubernetes_pod_node_name]
          action: replace
          target_label: hostname

      metric_relabel_configs:
        - action: labelmap
          regex: exported_(.+)
        - source_labels: [__name__]
          regex: tf_upbound_io_ProviderConfig.*|aws_upbound_io_ProviderConfig.*
          action: drop
        - action: labeldrop
          regex: label_.*
          if: '{app_kubernetes_io_name="x-metrics"}'

    - job_name: kubernetes-kubelet
      scheme: https
      tls_config:
        ca_file: /var/run/secrets/kubernetes.io/serviceaccount/ca.crt
      bearer_token_file: /var/run/secrets/kubernetes.io/serviceaccount/token
      kubernetes_sd_configs:
        - role: node
      relabel_configs:
        - action: labelmap
          regex: __meta_kubernetes_node_label_(.+)
        - target_label: __address__
          replacement: kubernetes.default.svc.cluster.local:443
        - source_labels: [__meta_kubernetes_node_name]
          regex: (.+)
          target_label: __metrics_path__
          replacement: /api/v1/nodes/${1}/proxy/metrics
        - source_labels: [__meta_kubernetes_node_name]
          action: replace
          target_label: hostname

      metric_relabel_configs:
        - action: labelmap
          regex: exported_(.+)

    - job_name: kubernetes-cadvisor

      scheme: https

      tls_config:
        ca_file: /var/run/secrets/kubernetes.io/serviceaccount/ca.crt
      bearer_token_file: /var/run/secrets/kubernetes.io/serviceaccount/token

      kubernetes_sd_configs:
        - role: node

      relabel_configs:
        - action: labelmap
          regex: __meta_kubernetes_node_label_(.+)
        - target_label: __address__
          replacement: kubernetes.default.svc:443
        - source_labels: [__meta_kubernetes_node_name]
          regex: (.+)
          target_label: __metrics_path__
          replacement: /api/v1/nodes/${1}/proxy/metrics/cadvisor
        - source_labels: [__meta_kubernetes_node_name]
          action: replace
          target_label: hostname

      metric_relabel_configs:
        - action: labelmap
          regex: exported_(.+)
        - regex: k8s_io_cloud_provider_aws|failure_domain_beta_kubernetes_io_.*|kubernetes_io_hostname|topology_kubernetes_.*|beta_kubernetes_.*
          action: labeldrop

    - job_name: kubernetes-service-endpoints

      kubernetes_sd_configs:
        - role: endpoints

      relabel_configs:
        - source_labels: [__meta_kubernetes_service_annotation_kubectl_kubernetes_io_last_applied_configuration]
          action: replace
          replacement: ""
          target_label: __annotation
        - source_labels: [__meta_kubernetes_service_annotation_prometheus_io_scrape]
          action: keep
          regex: true
        - source_labels: [__meta_kubernetes_service_annotation_prometheus_io_scheme]
          action: replace
          target_label: __scheme__
          regex: (https?)
        - source_labels: [__meta_kubernetes_service_annotation_prometheus_io_path]
          action: replace
          target_label: __metrics_path__
          regex: (.+)
        - source_labels: [__address__, __meta_kubernetes_service_annotation_prometheus_io_port]
          action: replace
          target_label: __address__
          regex: ([^:]+)(?::\d+)?;(\d+)
          replacement: $1:$2
        - action: labelmap
          regex: __meta_kubernetes_service_label_(.+)
        - source_labels: [__meta_kubernetes_namespace]
          action: replace
          target_label: namespace
        - source_labels: [__meta_kubernetes_service_name]
          action: replace
          target_label: kubernetes_name
        - source_labels: [__meta_kubernetes_pod_name]
          action: replace
          target_label: kubernetes_pod_name
        - action: replace
          source_labels:
            - __meta_kubernetes_pod_node_name
            - __meta_kubernetes_endpoint_hostname
          regex: ((.*);(.*))
          replacement: $2$3
          target_label: hostname

      metric_relabel_configs:
        - action: labelmap
          regex: exported_(.+)
        - action: labelmap
          regex: node
          replacement: hostname
        - action: labeldrop
          regex: label_.*
          if: '{app_kubernetes_io_name="kube-state-metrics"}'

    - job_name: vmstorage

      metrics_path: /metrics
      scheme: http

      ec2_sd_configs:
        - region: "us-east-1"
          port: 8482
          filters:
            - name: tag:component
              values:
                - vmstorage

      relabel_configs:
        - source_labels: [__meta_ec2_availability_zone]
          action: replace
          target_label: availability_zone
        - source_labels: [__meta_ec2_instance_id]
          action: replace
          target_label: instance_id
        - source_labels: [__meta_ec2_instance_type]
          action: replace
          target_label: instance_type
        - source_labels: [__meta_ec2_private_dns_name]
          action: replace
          target_label: private_dns_name
        - source_labels: [__meta_ec2_tag_Name]
          action: replace
          target_label: name
        - source_labels: [__meta_ec2_tag_component]
          action: replace
          target_label: component
        - source_labels: [__meta_ec2_tag_purpose]
          action: replace
          target_label: purpose
```

### To Reproduce

Run vmagent in that version for few weeks and observe memory grow

### Version

vmagent-20241021-132821-tags-v1.105.0-0-g05f6ea621d

### Logs

N/A

**Comment by jiekun** [comment]
Could be relevant to https://github.com/VictoriaMetrics/VictoriaMetrics/issues/5884

**Comment by vhajdukd** [comment]
We observe the same behaviour in all of our clusters. This impacts only vmagent scraping k8s endpoints and few VMs running outside.

**Comment by Haleygo** [comment]
Hi @vhajdukd ,
Are the scrape targtes and samples stable during this period? 
```
sum(vm_promscrape_targets{job=~"$job", instance=~"$instance"}) by(job)
sum(rate(vm_promscrape_scraped_samples_sum{job=~"$job", instance=~"$instance"}[$__rate_interval])) by(job)
```
The profile looks fine to me though. Will the memory drop to a minimum after restart? If so, could you also send the profile after  restart?

> Important thing no notice is that while cgroup reports here ~ 250MIB of mem used, pprod reports only 170-180. 70-80 MIB is lost on "something".

The pprof only shows the heap memory which is used for dynamic memory allocations at runtime, while RSS memory contains more segments like anonymous memory(includes heap&stack memory), page cache.

**Comment by vhajdukd** [comment]
Hi,

We upgraded recently to 1.108.1 (last 44h), but the memory usage keeps on growing at the same pace as before:
<img width="1475" alt="Image" src="https://github.com/user-attachments/assets/a10db1ec-828b-44d7-aa6f-b5bf6042b38a" />

44h pprof:
![Image](https://github.com/user-attachments/assets/a0f3bbf5-9679-4c25-9de5-ffd482b97cf7)

**Adding also last 44h graphs, coz there is no difference in scrape targets or samples, but memory usage still grows slowly.**

Last 44h vm_promscrape_targets:
<img width="1475" alt="Image" src="https://github.com/user-attachments/assets/65c8d1be-0d0c-4f41-af28-ceb4b97caf52" />

Last 44h vm_promscrape_scraped_samples:
<img width="1475" alt="Image" src="https://github.com/user-attachments/assets/ef45eaf1-7726-46db-8894-815303c15474" />

42days (max) vm_promscrape_targets:
<img width="1475" alt="Image" src="https://github.com/user-attachments/assets/6d096486-cd28-40e5-a582-397a22526dd5" />

42days (max) vm_promscrape_scraped_samples (spikes are deployments):
<img width="1475" alt="Image" src="https://github.com/user-attachments/assets/e23f20fb-fe10-461e-a64e-d7ec8cc64f86" />

**Comment by vhajdukd** [comment]
Looking at that fluctuation around 01/21 18:00, there was a bump in targets scraped, target decreased soon after, but memory did not return to previous values. Looks like something is cached indefinitely (or so).

**Comment by f41gh7** [comment]
Can you try to set env variables `GOMEMLIMIT=280000000` (~280MB), `GOGC=100` and share results?

**Comment by vhajdukd** [comment]
> Can you try to set env variables `GOMEMLIMIT=200000000` (~200MB), `GOGC=100` and share results?

Wanned to have it running for few days before posting:

<img width="511" alt="Image" src="https://github.com/user-attachments/assets/ce1a9f13-3e89-4a27-9be8-8abee6aab7a1" />

It's running with this config for the past 42h:

<img width="1472" alt="Image" src="https://github.com/user-attachments/assets/2966fafb-de1a-4abc-8dab-8fc2a6c40c36" />

**Comment by garrington** [comment]
Hello.  I work with vhajdukd the OP of this issue.  Is there anything further we can provide to investigate this?  Please advise.  

Thanks.

**Comment by hagen1778** [comment]
> Looking at that fluctuation around 01/21 18:00, there was a bump in targets scraped, target decreased soon after, but memory did not return to previous values. Looks like something is cached indefinitely (or so).

vmagent, as many other components, maintain adjustable in-memory buffers for parsing - see more about [leveled-buffers](https://victoriametrics.com/blog/tsdb-performance-techniques-sync-pool/#leveled-bytesbuffer-pools). These buffers can grow if the workload grows or spiked. So it is expected that after the spike memory won't go away, as those buffers are still "pinned", used during scraping.

While all graphs here represent RSS memory usage of vmagent, could you please share anonymous memory usage - `process_resident_memory_anon_bytes` metric?

**Comment by garrington** [comment]
This is a graph of the last ~40 days for process_resident_memory_anon_bytes, the sudden drops are restarts:

![Image](https://github.com/user-attachments/assets/a35d02d0-6ee0-465e-ad2d-d7d6d4e286d1)

**Comment by Haleygo** [comment]
@garrington 
Are you currently testing with v1.108.0?

Could you please share two memory profiles for us to check, one from `x`, the other from `x+2days`? 
Based on your graph, the memory increased by approximately 50MB per 2days.

**Comment by hagen1778** [comment]
Hey @garrington, is this issue still relevant for you?

**Comment by hagen1778** [comment]
Closing this ticket due to lack of activity. If someone still observes signs of memory leakage - please update this ticket with your observations, vmagent configuration, screenshots of [vmagent dashboard](https://grafana.com/grafana/dashboards/12683-victoriametrics-vmagent/), and [memory profiles](https://docs.victoriametrics.com/vmagent/#profiling) to compare usage between vmagent versions.

**Comment by garrington** [comment]
Yes, this issue is still relevant and can still be observed.

![Image](https://github.com/user-attachments/assets/921fe31c-bc96-4eaa-a58f-cd380cf2030f)

**Comment by hagen1778** [comment]
Hello @garrington! Thanks for providing additional details!
Would you mind provide profiles requested in [this comment](https://github.com/VictoriaMetrics/VictoriaMetrics/issues/8036#issuecomment-2705516356)?

Overall, I would expect to not bother on memory leakage when absolute mem consumption is hundreds of MiBs. As I [said before](https://github.com/VictoriaMetrics/VictoriaMetrics/issues/8036#issuecomment-2678231853), vmagent maintains many internal buffers that can grow with time to accommodate the load. So it is very likely caused by these buffers growing.

Do you use stream aggregation? Could you please share the full list of cmd-line flags for vmselect?

Btw, in [v1.114.0](https://docs.victoriametrics.com/changelog/#v11140) vmagent got an improvement of stream parsing mode. It should reduce amount of allocations it makes. I'm strobnly recommend to try the updated version of vmagent.

**Comment by garrington** [comment]
Can you please clarify what you mean by memory profiles here: https://github.com/VictoriaMetrics/VictoriaMetrics/issues/8036#issuecomment-2705516356

Yes, we do use streaming aggregation.
I assume you meant cmd-line flags for vmagent (please let me know if this is not what you want):

```
    - args:
        - '--envflag.enable'
        - '--envflag.prefix=VM_'
        - '--httpListenAddr=:8429'
        - '--loggerErrorsPerSecondLimit=20'
        - '--loggerFormat=json'
        - '--loggerLevel=WARN'
        - '--promscrape.cluster.memberNum=$(POD_NAME)'
        - '--promscrape.cluster.membersCount=3'
        - '--promscrape.cluster.replicationFactor=1'
        - '--promscrape.config=/config/scrape/scrape.yml'
        - '--promscrape.discovery.concurrency=200'
        - '--promscrape.maxDroppedTargets=100000'
        - '--promscrape.streamParse'
        - '--promscrape.suppressDuplicateScrapeTargetErrors'
        - '--promscrape.suppressScrapeErrors'
        - '--remoteWrite.dropSamplesOnOverload'
        - '--remoteWrite.showURL'
        - '--remoteWrite.tmpDataPath=/tmpData'
        - >-
          --remoteWrite.url=<redacted>
        - >-
          --streamAggr.config=/vmagent-scrape-streaming-aggregation-conf/streaming-aggregation-conf.yaml
```

Here is the streaming aggregation config:

```
  streaming-aggregation-conf.yaml: >
    - match: '{job="kubernetes-service-endpoints",__name__=~"^kube_job_.*",
    __name__!~"^(kube_job_spec_active_deadline_seconds|kube_job_spec_parallelism|kube_job_status_completion_time|kube_job_status_start_time)$",job_name=~".+-[0-9]{8}$"}'
      interval: 30s
      outputs: [sum_samples]
      keep_metric_names: true
      input_relabel_configs:
        - target_label: job_name
          source_labels: [job_name]
          regex: (.*)-[0-9]{8}$
          replacement: ${1}
          action: replace
    - match: '{job="kubernetes-service-endpoints",__name__=~"^kube_job_.*",
    __name__!~"^(kube_job_spec_active_deadline_seconds|kube_job_spec_parallelism|kube_job_status_completion_time|kube_job_status_start_time)$",
    job_name=~".+-manual-...$"}'
      interval: 30s
      outputs: [ sum_samples ]
      keep_metric_names: true
      input_relabel_configs:
      - target_label: job_name
        source_labels: [ job_name ]
        regex: (.*)-manual-...$
        replacement: ${1}-manual
        action: replace
    - match:
    '{job="kubernetes-service-endpoints",__name__=~"^(kube_job_spec_active_deadline_seconds|kube_job_spec_parallelism|kube_job_status_completion_time|kube_job_status_start_time)$",job_name=~".+-[0-9]{8}$"}'
      interval: 30s
      outputs: [ max ]
      keep_metric_names: true
      input_relabel_configs:
      - target_label: job_name
        source_labels: [ job_name ]
        regex: (.*)-[0-9]{8}$
        replacement: ${1}
        action: replace
    - match:
    '{job="kubernetes-service-endpoints",__name__=~"^(kube_job_spec_active_deadline_seconds|kube_job_spec_parallelism|kube_job_status_completion_time|kube_job_status_start_time)$",
    job_name=~".+-manual-...$"}'
      interval: 30s
      outputs: [ max ]
      keep_metric_names: true
      input_relabel_configs:
      - target_label: job_name
        source_labels: [ job_name ]
        regex: (.*)-manual-...$
        replacement: ${1}-manual
        action: replace
```

We have upgraded to v1.114.0 in our test environment to compare the behavior.
