### ISSUE TITLE
Firing Alerts May Get Mixed Labels Due to Drop & Replace Relabeling

### ISSUE THREAD

**Issue by evkuzin** [VictoriaMetrics/VictoriaMetrics#8040]
### Describe the bug

Here is an annotation template and the final json I catch listening for tcp traffic. 
```yaml
annotations: &normal_annotations
summary: Check {{ $labels.check }} detected a failure on {{ $labels.instance |stripPort }}.
message: "{{ $labels.message }}"
check: "{{ $labels.check }}"
description: |-
            The host should be removed from production workloads and investigated.
            Services running on this host have likely been affected.
            Run `sys-check details {{ $labels.check }}` on the host and follow
            the provided runbook.
```

```
{{
  "startsAt": "2025-01-14T12:29:00-05:00",
  "generatorURL": "http://victoriametrics/select/0/vmui/#/?g0.expr=%28sys_check_condition%7Bcontact%21~%22custom-.%2B%22%7D+%3D%3D+2%29%0A++unless+on%28check%29%0A%28ALERTS%7Balertname%3D%27ManySysCheckFailures%27%2Calertstate%3D%27firing%27%7D+%3D%3D+1%29",
  "endsAt": "2025-01-14T14:24:02.163378284-05:00",
  "labels": {
    "alertname": "SysCheckFailure/sched/tag_gated",
    "check": "sched/tag_gated",
    "contact": "sched-systems",
    "hostname": "icelake",
    "instance": "icelake:9100",
    "job": "node",
    "message": "Host has banned tag",
    "monitor": "hrt",
    "sched_instance": "rcrsched",
    "severity": "host-fail",
    "virtual": "false"
  },
  "annotations": {
    "summary": "Check sched/tag_gated detected a failure on genoa.",
    "check": "sched/tag_gated",
    "description": "The host should be removed from production workloads and investigated.\nServices running on this host have likely been affected.\nRun `sys-check details sched/tag_gated` on the host and follow\nthe provided runbook.",
    "message": "Host has banned tag"
  }
}
```

As you can see there is a mess with the icelake and genoa hostnames. Highly likely a templating bug

### To Reproduce

No idea. But I see them quite often

### Version

I cought this on both 1.108 and 1.109

**Comment by evkuzin** [comment]
@Haleygo wanted to mention that I also have this setup.
```
alert_relabel_configs:
- regex: SysCheckFailure;(.*)
  replacement: ${1}/${2}
  source_labels:
  - alertname
  - check
  target_label: alertname
```

**Comment by evkuzin** [comment]
On the other hand I dont think that this relabeling messing with the final result, I also saw another alert which doesn't have any permutations to alertname but templated with wrong labels

![Image](https://github.com/user-attachments/assets/b01e7a2b-9efc-4207-8dae-24f27ced8380)

**Comment by Haleygo** [comment]
Hi @evkuzin ,
I tried to reproduce the issue but failed, I was testing with the docker-compose file [here](https://github.com/VictoriaMetrics/VictoriaMetrics/blob/test-template/deployment/docker/docker-compose.yml), which includes [an alerting rule](https://github.com/VictoriaMetrics/VictoriaMetrics/blob/e237e35c9c448281870b3c7d862753bc81f7afa3/deployment/docker/rules/alerts-health.yml#L6-L15) that triggers 3 alerts for different instances and the annotations in alertmanager message are correct.


![Image](https://github.com/user-attachments/assets/b0fa6ee9-b221-46ff-89e5-475edf118c00)

![Image](https://github.com/user-attachments/assets/f423113d-f534-4ef3-827b-a402654f9d8a)

Could you please try to reproduce the issue with the above example?
Does the alert for host `genoa` have the correct message templated?

**Comment by evkuzin** [comment]
Will do. Thx for working on it!

**Comment by evkuzin** [comment]
Hey @Haleygo I've been running additional vmalert pointing to real prod metrics to catch that case, but for 4 days I have had no luck. 
When we experienced this we were 100% sure that this was vmalert because, at the time of the event, I crafted a tiny Python server to listen to the 9093 port. I added it as an additional alert manager in the vmalert config. The Python code was parsing data, checking for alert names where we saw discrepancies and printed whole json in case it was wrong. 
After a small amount of time, we did an analysis and saw alerts from 267 unique hosts mixed with bad annotations. If we had run it for longer I'm pretty sure we would have collected all 267 * 267, but since it was hurting production we stopped quite soon and moved that execution back to Prometheus (our architecture consists of Prometheus stack and Victoriametrics as remote write target and we are gradually moving all functionality to it at the moment). At that time it was 19566 alerts with mixed annotations. 
I'm posting just to be on the same page that we 100% saw it(and also so you would have a better picture), but unfortunately, we cannot replicate it. Maybe it will happen again when we move traffic back. For now, if you don't mind I'll keep the issue open and update later when we are ready to test this alert on the VM stack again.

**Comment by Haleygo** [comment]
@evkuzin thank you for all the tests!
Let me double-check the code and test it with a high volume of alerts. And ofc, feel free to post any updates you see!

**Comment by evkuzin** [comment]
This failed again today when we moved this specific alert back from Prometheus to vmalert. 
I will work on reproducing again, hope I can make it. Just to clarify the scale - the total number of alerts firing is close to 12k and this particular rule is producing 1.2k alerts.

**Comment by evkuzin** [comment]
@Haleygo 

I can reproduce the issue now! 🎉 
took me a while to figure it out though!

This is a dummy alert I came up with
```yaml
groups:
- name: test-rules
  rules:
  - alert: TestFailure
    annotations: 
      file: '{{ $labels.file }}'
      summary: Check {{ $labels.file }} detected a failure on {{ $labels.instance |stripPort }}.
    expr: node_textfile_mtime_seconds
```

What I did to catch this:
I spin up a test vmalert with the same version as production. 
```
 /usr/bin/vmalert-prod --version
vmalert-20250114-121303-tags-v1.109.0-0-g7a7f188133
```
Pointed it to the same production data and added all alerting rules.
In the vmalert config I pointed it to my simple python script:

```python
#!/usr/bin/env python3
from flask import Flask, request
import json
from loguru import logger
import logging
import sys

app = Flask(__name__)

logging.basicConfig(
    filename="/tmp/server.log",
    level=logging.INFO,
    format="%(asctime)s - %(levelname)s - %(message)s",
)
logger.remove()
logger.add(sys.stderr, level="INFO")


@app.route("/api/v2/alerts", methods=["POST"])
def handle_post_request():
    data = request.get_data()
    res = json.loads(data.decode("utf-8"))
    stats = {}

    for alert in res:
        alertname = alert.get("labels", {}).get("alertname")
        stats[alertname] = stats.get(alertname, {"total": 0, "failed": 0})
        stats[alertname]["total"] += 1
        hostname = alert.get("labels", {}).get("instance").split(":")[0]
        summary = alert.get("annotations", {}).get("summary", "")
        if hostname not in summary:
            logger.error(f"{hostname} mismatch '{summary.split()[-1]}'")
            logger.error(alert)
            stats[alertname]["failed"] += 1
    for alertname, stat in stats.items():
        if stat["failed"] > 0:
            logger.error(f"{alertname} failed: {stat['failed']} total: {stat['total']}")
    logger.info(f"Received {len(stats)} alerts")
    return "OK"


if __name__ == "__main__":
    app.run(host="0.0.0.0", port=9094)
```

This rearranging of labels starts only if there is a drop trigger in alert relabeling:

```yaml
scheme: http
static_configs:
- targets:
  - shauser-evgeny4.hudson-trading.com:9094
timeout: 10s
alert_relabel_configs:
- action: drop
  regex: .*evgeny.*
  source_labels:
  - hostname
  - instance
```

if this drop action matches a set of alerts then seems like it will drop the particular alert with some shift for labels. I cannot find any other reason.

after a python server starts I will receive plenty of messages like this:

```text
2025-02-06 06:56:02.936 | ERROR    | __main__:handle_post_request:32 - someuserinstance mismatch 'wronguserinstance.'
2025-02-06 06:56:02.936 | ERROR    | __main__:handle_post_request:33 - {'startsAt': '2025-02-06T06:45:00-05:00', 'generatorURL': 'http://vmui/select/0/vmui/#/?g0.expr=node_textfile_mtime_seconds%7Binstance%3D~%22shauser.%2A%22%7D', 'endsAt': '2025-02-06T07:00:02.360411281-05:00', 'labels': {'alertname': 'TestFailure', 'file': '/var/lib/node_exporter/textfile_collector/apt.prom', 'instance': 'someuserinstance:9100', 'job': 'node'}, 'annotations': {'summary': 'Check /var/lib/node_exporter/textfile_collector/node_info.prom detected a failure on wronguserinstance.', 'file': '/var/lib/node_exporter/textfile_collector/node_info.prom'}}
```
