### ISSUE TITLE
Failing to drop label from the metrics

### ISSUE THREAD

**Issue by ankitmunot** [VictoriaMetrics/VictoriaMetrics#8056]
### Is your question request related to a specific component?

Trying to drop the **instance** label from all the metrics except the node-exporter job.

Using the following YAML file

```
apiVersion: operator.victoriametrics.com/v1beta1
kind: VMAgent
metadata:
  finalizers:
  - apps.victoriametrics.com/finalizer
  generation: 10
  labels:
    kustomize.toolkit.fluxcd.io/name: infra
    kustomize.toolkit.fluxcd.io/namespace: flux-system
  name: vmagent-0
  namespace: monitoring-system
spec:
  affinity:
    podAntiAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
      - labelSelector:
          matchExpressions:
          - key: app.kubernetes.io/name
            operator: In
            values:
            - vmagent
        topologyKey: kubernetes.io/hostname
  containers:
  - image: artifactory.prod.hosting.auto.com/thirdparty-docker-remote/prometheus-operator/prometheus-config-reloader:v0.75.2
    name: config-reloader
    resources:
      limits:
        cpu: 200m
        memory: 500Mi
  externalLabels:
    cluster: oc-k8s-app-1-dev-use2-aks
    region: na
  extraArgs:
    envflag.enable: "true"
    envflag.prefix: VM_
    promscrape.cluster.replicationFactor: "2"
    promscrape.kubernetes.useHTTP2Client: "true"
    promscrape.kubernetesSDCheckInterval: 30s
    promscrape.maxScrapeSize: 200MB
    promscrape.noStaleMarkers: "true"
    remoteWrite.forcePromProto: "true"
    sortLabels: "true"
  image:
    repository: artifactory.prod.hosting.auto.com/thirdparty-docker-remote/victoriametrics/vmagent
    tag: v1.108.0
  imagePullSecrets:
  - name: cks-image-pull-secret-bbkbg5gh49
  initContainers:
  - image: artifactory.prod.hosting.auto.com/thirdparty-docker-remote/prometheus-operator/prometheus-config-reloader:v0.75.2
    name: config-init
  logFormat: json
  logLevel: INFO
  overrideHonorTimestamps: false
  podMetadata:
    annotations:
      cks.monitoring.com/module: monitoring
      cost.monitoring.com/component: vm-agent
      cost.monitoring.com/createdBy: vm-operator
  podScrapeNamespaceSelector: {}
  podScrapeSelector: {}
  priorityClassName: statefulset-priority-medium
  remoteWrite:
  - headers:
    - THANOS-TENANT:thanos-receive-0
    url: http://thanos-receive-0-0.thanos-receive.monitoring-system.svc.cluster.local:19291/api/v1/receive
  remoteWriteSettings:
    maxDiskUsagePerURL: 0
  replicaCount: 1
  resources:
    limits:
      cpu: 8000m
      memory: 14Gi
    requests:
      cpu: 3000m
      memory: 6Gi
  rollingUpdate:
    maxUnavailable: 1
  scrapeInterval: 30s
  securityContext:
    fsGroup: 65534
    runAsGroup: 65534
    runAsNonRoot: true
    runAsUser: 65534
  serviceScrapeNamespaceSelector: {}
  serviceScrapeSelector: {}
  shardCount: 0
  statefulMode: true
  statefulStorage:
    volumeClaimTemplate:
      spec:
        accessModes:
        - ReadWriteOnce
        resources:
          requests:
            storage: 100G
        storageClassName: disk-ssd
        volumeMode: Filesystem
  updateStrategy: RollingUpdate
status:
  observedGeneration: 10
  replicas: 1
  selector: app.kubernetes.io/component=monitoring,app.kubernetes.io/instance=vmagent-0,app.kubernetes.io/name=vmagent,managed-by=vm-operator
  updateStatus: operational
```

Tried the following relabel config but didn't work:

```
inlineRelabelConfig:
  - action: drop
    if: '{job!="node-exporter"}'
    sourceLabels: [instance]
    regex: '.*'
```

### Describe the question in detail

I am trying to drop the label using the Vmagent

### Troubleshooting docs

- [ ] General - https://docs.victoriametrics.com/troubleshooting/
- [ ] vmagent - https://docs.victoriametrics.com/vmagent/#troubleshooting
- [ ] vmalert - https://docs.victoriametrics.com/vmalert/#troubleshooting

**Comment by jiekun** [comment]
Hello! There are some small mistakes in the config:
1. `action: drop` drops all the metrics, not a label. In your case, you should try:  `action: labeldrop`, which drops labels with names matching the given regex option
2. If you are using `inlineRelabelConfig`, then `sourceLabels` is not a valid param (and it's not required when doing `labeldrop`).
3. `instance` label will be added after service discovery + relabeling, if it's missing. So `relabel_configs` cannot remove this label. You have to do it in `metric_relabel_config` in config, `-remoteWrite.relabelConfig` in cli flag or `-relabelConfig` in cli flag of vminsert.

Here's an example you can try:
```yaml
    metric_relabel_configs:
      - action: labeldrop
        if: '{job!="node-exporter"}'
        regex: "instance"
```

Please search for `metricRelabelConfig` in VMAgent API doc here: https://docs.victoriametrics.com/operator/api/index.html

And please see more details [here](https://docs.victoriametrics.com/relabeling/#how-to-remove-labels-from-targets), and note that
- **Do not remove instance and job labels, since this may result in duplicate scrape targets with identical sets of labels.**
