### ISSUE TITLE
Per-tenant VMUI authorization for VictoriaLogs

### ISSUE THREAD

**Issue by phuocpeter** [VictoriaMetrics/VictoriaMetrics#8132]
### Is your question request related to a specific component?

VictoriaLogs, vmui, vmauth

### Describe the question in detail

I'm using VictoriaLogs and want to try out multi-tenancy.

On documentation, it should be able to authorize tenant with vmauth. 
Been trying to set up the auth.yaml config without much success.

I want to enforce that each tenant can only access vmui to query logs of their own.
I read that vmui has some endpoint `/select/{tenantId}/vmui` but it feels like that is only available on VictoriaMetrics

This is what I have tried:
```yaml
users:

- username: "user1"
  password: "pass"
  dump_request_on_errors: true
  url_map:
  - src_query_args: ["accountID=100"]
    url_prefix:
    - "http://localhost:9428/select/vmui/?#/?accountID=100"  #enforce the tenant id
  
- username: "user2"
  password: "pass"
  dump_request_on_errors: true
  url_map:
  - src_query_args: ["accountID=200"]
    url_prefix:
    - "http://localhost:9428/select/vmui/?#/?accountID=200"

unauthorized_user:
  url_prefix: "http://backend/404"
```

How should I the config looks like in this case?

### Troubleshooting docs

- [ ] General - https://docs.victoriametrics.com/troubleshooting/
- [ ] vmagent - https://docs.victoriametrics.com/vmagent/#troubleshooting
- [ ] vmalert - https://docs.victoriametrics.com/vmalert/#troubleshooting

**Comment by zekker6** [comment]
@phuocpeter Multitenancy in VictoriaLogs uses headers as a source of information, see [these docs](https://docs.victoriametrics.com/victorialogs/#multitenancy). vmauth can modify request headers in order to enforce tenancy infromation, see [these docs](https://docs.victoriametrics.com/vmauth/#modifying-http-headers).

Here is an example configuration:
```
users:
  - username: "user1"
    password: "pass"
    dump_request_on_errors: true
    url_map:
      - src_paths: ["/select/.*"]
        headers:
          - "AccountID: 1"
          - "ProjectID: 0"
        url_prefix:
          - "http://localhost:9428/"

  - username: "user2"
    password: "pass"
    dump_request_on_errors: true
    url_map:
      - src_paths: ["/select/.*"]
        headers:
          - "AccountID: 2"
          - "ProjectID: 0"
        url_prefix:
          - "http://localhost:9428/"


unauthorized_user:
  url_prefix: "http://backend/404"
```

It will enforce setting `AccountID`/`ProjectID` headers to all requests forwarded to VictoriaLogs instances and will allow to proxy any `/select/.*` requessts making access read-only.
