### ISSUE TITLE
vmauth configuration

### ISSUE THREAD

**Issue by lucrus73** [VictoriaMetrics/VictoriaMetrics#8144]
### Is your question request related to a specific component?

vmauth

### Describe the question in detail

I need to configure vmauth so that the web interface (/, vmui and the like) requires Basic authentication credentials, so that common HTML browsers can easily access the web interface, while the /influx endpoints require a Bearer token authentication instead, because my client that ingests data via the /influx endpoints does not support basic auth. Is it possible to achieve this?

I've read what I believe are the relevant paragraphs of [the vmauth docs](https://docs.victoriametrics.com/vmauth/), but I don't understand how to combine things to achieve what I need.

**Comment by zekker6** [comment]
Hello @lucrus73 

Seems like you will need something similar to the following:
```
users:
  - username: "foo"
    password: "bar"
    url_map:
      - src_paths:
          - /vmui.*
          - /prometheus.*
        url_prefix:
          - "http://localhost:8428/"

  - bearer_token: "some_token"
    url_map:
      - src_paths: ["/influx.*"]
        url_prefix:
          - "http://localhost:8428/"

```

This config defines 2 users. User `foo` has access to VMUI and endpoints perfixed with `/prometheus` so that there will be access to data querying.
The second user uses `bearer_token`for authentication and only has access to endpoints starting with `/influx`.
