### ISSUE TITLE
The `eval_delay` parameter is invalid when vmalert performs aggregation

### ISSUE THREAD

**Issue by XMingG99** [VictoriaMetrics/VictoriaMetrics#8154]
### Describe the bug

My data link is as follows：

<img width="761" alt="Image" src="https://github.com/user-attachments/assets/4e15da13-0477-49b7-9090-7c6b199b2096" />
 
`my application` will print the difference between the current time and the data point time
aggregated rule like this:
```
groups:
      - name: recording-5s
        interval: 5s
        eval_offset: 0s
        eval_delay: 15s
        concurrency: 4
        rules:
          - record: test_metrics_after_vmalert
            expr: test_metrics{}
            update_entries_limit: 10000
```
As stated in document [vmaler-groups](https://docs.victoriametrics.com/vmalert/#groups), the vmalert aggregation process should be as follows:

<img width="970" alt="Image" src="https://github.com/user-attachments/assets/3a736042-c71f-4e57-b804-63a1f97c6700" />
Therefore, when `my application` receives the aggregated data point, the time difference between the current time and the aggregated data should be >=15s, but the actual situation is that the time difference is only about 5s.

I tried three versions with the same result

### To Reproduce

rule.yaml
```
groups:
      - name: recording-5s
        interval: 5s
        eval_offset: 0s
        eval_delay: 15s
        concurrency: 4
        rules:
          - record: test_metrics_after_vmalert
            expr: test_metrics{}
            update_entries_limit: 10000
```

vmalert config:
```
args:
            - -rule=/config/*.yaml
            - -datasource.url=http://vmcluster-victoria-metrics-cluster-vmselect.svc:8481/select/0/prometheus
            - -remoteRead.url=http://vmcluster-victoria-metrics-cluster-vmselect.svc:8481/select/0/prometheus
            - -remoteWrite.url=http://my-application-service.svc:8000/insert/0/prometheus
            - -envflag.enable=true
            - -envflag.prefix=VM_
            - -loggerFormat=json
```

### Version

v1.96.0
v1.104.0
v1.110.0

### Additional information

kubernetes version v1.26.1

**Comment by hagen1778** [comment]
Hello @XMingG99 ! It looks like `eval_offset` and  `eval_delay` are excluding options - see https://github.com/VictoriaMetrics/VictoriaMetrics/blob/5b18dc0214b5a0f75d2c258f4cd564aebd187cea/app/vmalert/rule/group.go#L598-L600
Using  `eval_offset` kinda promises that rule will be executed at specific second, so `eval_delay` is ignored. However, vmalert doesn't notify user in logs or in documentation about this. I also think these two settings could work together, it seems naturally to me. wdyt @Haleygo ?

**Comment by hagen1778** [comment]
@XMingG99 @Haleygo will be away for holidays for next 2w, and she's a maintainer of vmalert - I don't want to do breaking changes without her opinion. So I suggest as a workaround set a query param `latency_offset=15s` for this group - see what it is here https://docs.victoriametrics.com/keyconcepts/#query-latency

**Comment by XMingG99** [comment]
> Hello [@XMingG99](https://github.com/XMingG99) ! It looks like `eval_offset` and `eval_delay` are excluding options - see
> ...
> Using `eval_offset` kinda promises that rule will be executed at specific second, so `eval_delay` is ignored. However, vmalert doesn't notify user in logs or in documentation about this. I also think these two settings could work together, it seems naturally to me. wdyt [@Haleygo](https://github.com/Haleygo) ?
Yes, I had reviewed the code.

<img width="1716" alt="Image" src="https://github.com/user-attachments/assets/752480cf-5ce8-49ae-a661-83a35741db56" />

According to the logic of the code, if configured as follows：
```
groups:
      - name: recording-5s
        interval: 5s
        eval_offset: 0s
        eval_delay: 15s
        concurrency: 4
        rules:
          - record: test_metrics_after_vmalert
            expr: test_metrics{}
            update_entries_limit: 10000
```
If the current time is 12:00:00-12:00:04, Truncate will align the time to 12:00:00, add `evaloffset` to calculate the time as 12:00:15, and subtract `evalInterval` to obtain the time as 12:00:10. This result is also obviously incorrect because it is greater than the current time, and from the logic of the code, `evaloffset` should be less than `evalInterval`

**Comment by Haleygo** [comment]
Hi @XMingG99 ,
Like Roman mentioned, `eval_offset` and `eval_delay` are currently exclusive options, as both adjust the evaluation timestamp. For example:
```
- name: test
   interval: 1h
   eval_offset: 10m
   eval_delay: 15m
```
If the group starts at `12:05`, we adjust the timestamp to `11:10` to align with `eval_offset`, which is already smaller than `12:05 - eval_delay`, so everything is fine;
However, if the group starts at `12:15`, we adjust the timestamp to `12:10` to align with `eval_offset` while ignore the `eval_delay`, result in `12:10` being bigger than `12:15 - eval_delay`, as you observed. 
To address this case, we could further modify the timestamp to `11:10`, but this may surprise users by delaying rule evaluation results by over 1 hour(`12:15-11:10=1h5m`). 
And since the `-rule.evalDelay` flag has a default value(30s), users might be confused if they only specify `eval_offset`, but see a significant delay. For instance: 
```
- name: test
   interval: 1h
   eval_offset: 10m
```
and the group start at `12:10:10`. With the default `-rule.evalDelay`, now we use `12:10:00` for the first evaluation, and the fix will change the timestamp to `11:10:00`.
So I think this extra logic may not be beneficial, but we should warn user against using both options together.
cc @hagen1778

**Comment by Haleygo** [comment]
Regarding your rule here:
```
groups:
      - name: recording-5s
        interval: 5s
        eval_offset: 0s
        eval_delay: 15s
        concurrency: 4
```
`eval_offset: 0s` is actually unnecessary, as rule evaluation is aligned with the interval by default, making the default `eval_offset` already 0. So you can just remove the `eval_offset` and get the correct results.
