### ISSUE TITLE
Using the src_query_args parameter results in a missing route

### ISSUE THREAD

**Issue by KhafRuslan** [VictoriaMetrics/VictoriaMetrics#8163]
### Describe the bug

Using the src_query_args argument, I'm trying to limit the list of query that can be performed using a defined token. But this does not lead to the expected result. If I remove this parameter from the configuration, then I can execute this query. I tried to specify this parameter in different ways:
`src_query_args: ['query={__name__="up"}']`
 `src_query_args: ['up']`
 `src_query_args: ['query=up']` 
  `src_query_args: ['query="up"']`
  ```
src_query_args: 
- 'query=up'
```

But in all cases, the error is the same.When using the new parameter, the query also changed.

### To Reproduce

Configuration vmauth(/etc/vmauth/vmauth.yml): 
```
users:
- bearer_token: sometoken
  metric_labels:
    team: someteam
  url_map:
  - src_paths: ["/api/v1/query"]
    src_query_args: ['query={__name__="up"}']
    url_prefix:
    - "http://someserver:8481/select/0/prometheus"
```
Query:

`curl -v "http://someserver:443/api/v1/query" -d  'query={__name__="up"}'  -H "Authorization: Bearer sometoken"`

### Version

victoriametrics/vmauth:v1.110.0 

### Logs

2025-01-27T14:58:59.998Z        warn    VictoriaMetrics/app/vmauth/main.go:218  remoteAddr: "10.80.15.35:41240"; requestURI: /api/v1/query?query=%7B__name__%3D%22up%22%7D; missing route for "/api/v1/query"

### Used command-line flags

docker run -d \
           --restart=always \
           --name vmauth \
           --network=host \
           -v /etc/vmauth:/etc/vmauth victoriametrics/vmauth:v1.110.0 \
           -auth.config=/etc/vmauth/vmauth.yml \
           -httpListenAddr=":443" \
