### ISSUE TITLE
Recording rules using increase/increase (divide) show spikes (exact 1) when the cluster restarts

### ISSUE THREAD

**Issue by lujiajing1126** [VictoriaMetrics/VictoriaMetrics#8222]
### Describe the bug

I am using recording rules to pre-compute error rate in the last 5 min and then using alert rules to do a post calculation for alarms. 
For example, with the follow VMRule CRD (simplified)

```yaml
apiVersion: operator.victoriametrics.com/v1beta1
kind: VMRule
metadata:
  name: aop-backend
  namespace: xxx
spec:
  groups:
    - concurrency: 1
      interval: 60s
      name: owner-defined-rules
      rules:
      - alert: error-rate-global
          annotations:
            summary: '???? {{ $value | humanizePercentage }}'
            value: '{{ $value }}'
          expr: >-
            op:error_spans:rate5m{job="aop-backend"} > on (job, operation)
            group_left() (alarm:op_threshold:const or on (job, operation) count
            by(job, operation)(error_spans_total) * 0 + 0.25)
          labels:
            alarm: traffic
            severity: critical
```

where `op:error_spans:rate5m` metrics is generated by a recording rule,

```yaml
apiVersion: operator.victoriametrics.com/v1beta1
kind: VMRule
metadata:
  name: recording-rules
  namespace: monitoring-system
spec:
  groups:
    - concurrency: 3
      interval: 1m
      name: error-rate
      rules:
        - expr: >-
            (sum without (exception)
            (increase(error_spans_total{group="opr",exception!="None"}[5m]))) /
            (sum without (exception)
            (increase(error_spans_total{group="opr"}[5m])))
          record: 'op:error_spans:rate5m'
```

When I use operator to upgrade the VictoriaMetrics cluster, alarm reported.

![Image](https://github.com/user-attachments/assets/e87ba4d0-8f2d-4e44-866c-1f0941eaac05)

But after a while, by checking the original recording rules, it does not show any anomaly.

![Image](https://github.com/user-attachments/assets/afbe5dbe-75cc-460b-ad19-db1abbf015c1)

Actually it is less then 1.0

### To Reproduce

Cannot reproduce...

### Version

Found in 1.109.1, cluster version, deployed by VM Operator

### Additional information

https://github.com/VictoriaMetrics/VictoriaMetrics/pull/8052 (edge case 1)

I am not sure if the problem is related to these issues and pull requests.
`-search.maxStalenessInterval` is kept to the default value.

In the recording rule, the denominator is large (with `exception=None`) while the numerator (without `exception=None`) is relative small. How can the result be 1.0?
