### ISSUE TITLE
VMalert fire false alerts after restart

### ISSUE THREAD

**Issue by alexandrst88** [VictoriaMetrics/VictoriaMetrics#8225]
### Describe the bug

There is an alert:
```
    - alert: StackdriverDownWarn
      annotations:
        description: Stackdriver pod is down for 5m
        runbook_url: Check stackdriver pod
        summary: Stackdriver pod is down for 5m
      expr: |
        absent(up{container!="",job=~".*stackdriver.*"})
      for: 5m
      labels:
        severity: warning
```

During GKE cluster upgrade, one stackdriver got down and VMalert make an alert as status **PENDING**, then VMalert goes down for >= then `for` of the alert. It immediately transits it to **FIRING** state, even though stackdriver was running during VMalert restart. More info on Grafana screenshot.

### To Reproduce

It should be vmcluster, vmalert must run with `-remoteRead.url` and `-remoteWrite.url`.

Make an alert with `for: 5m`, move it to Pending state for 1-2 evaluation, then stop VMalert for 3-4 minutes and start again. It will fire immediately.

### Version

```victoriametrics/vmalert:v1.103.0```

### Screenshots

<img width="1296" alt="Image" src="https://github.com/user-attachments/assets/5e15b8cb-b04d-4a1c-8635-480762989e27" />

### Used command-line flags

```
      -datasource.queryStep=60s
      -datasource.url=http://some
      -evaluationInterval=30s
      -external.url=http://alertmanager:9093
      -httpListenAddr=:8080
      -notifier.url=http://some
      -remoteRead.url=http://some
      -remoteWrite.flushInterval=5s
      -remoteWrite.retryMaxTime=60s
      -remoteWrite.retryMinInterval=2s
      -remoteWrite.url=http://some
      -rule.maxResolveDuration=300s
      -rule="/etc/vmalert/config/vm-vmalert-rulefiles-0/*.yaml"
```
