### ISSUE TITLE
vmalert: group metrics absent after reload

### ISSUE THREAD

**Issue by zekker6** [VictoriaMetrics/VictoriaMetrics#8229]
### Describe the bug

Metrics for a specific group are disappearing when changing an interval.

### To Reproduce

1. Run a vmalert with the following config:
```yaml
groups:
  - interval: 20s
    name: issue
    rules:
      - expr: 1
        record: test
```
Run `curl  <vmalert>/metrics | grep iteration_total` and observe:
```
vmalert_iteration_total{group="issue", file="conf/vmalert-example.yml"} 1
```

2. Change interval to `20s` and check metrics again. Metrics for this group will be absent.

### Version

latest
