### ISSUE TITLE
Will reloading vmagent config cause interruptions in metric collection?

### ISSUE THREAD

**Issue by ydbdyds** [VictoriaMetrics/VictoriaMetrics#8252]
### Is your question request related to a specific component?

vmagent、vmagent

### Describe the question in detail

I am using vmoperator and vmagent. I have noticed that when I remove a large number of targets from VMServiceScrape, some series may experience interruptions. Is this expected? The core configuration of vmagent is as follows:
```
extraArgs:
  promscrape.maxScrapeSize: 1GB
  promscrape.streamParse: 'true'
replicaCount: 1
scrapeInterval: 60s
selectAllByDefault: true
shardCount: 3
statefulMode: true
```

### Troubleshooting docs

- [x] General - https://docs.victoriametrics.com/troubleshooting/
- [x] vmagent - https://docs.victoriametrics.com/vmagent/#troubleshooting
- [x] vmalert - https://docs.victoriametrics.com/vmalert/#troubleshooting
