### ISSUE TITLE
`VMAlertmanagerConfig` doing something odd with a default route and results in a config that is not usable for alerts other than those in the operator namespace

### ISSUE THREAD

**Issue by djryanj** [VictoriaMetrics/VictoriaMetrics#8285]
### Is your question request related to a specific component?

VictoriaMetrics operator related to VMAlertmanagerConfig

### Describe the question in detail

When using the `victoria-metrics-k8s-stack` helm chart with values thus:

```yaml
# a bunch of default stuff skipped for brevity
alertmanager:
  enabled: true
  useManagedConfig: true 
  config: 
    route:
      receiver: "gmail"
      group_by: ["alertgroup", "job"]
      group_wait: 30s
      group_interval: 5m
      repeat_interval: 12h
      routes:
        - matchers:
            - severity =~ "info|warning|critical"
          receiver: gmail
          continue: false
        - continue: true
          receiver: blackhole
    receivers:
      - name: gmail
        email_configs:
        - to: me@domain.com
          from: me@domain.com
          smarthost: smtp.gmail.com:587
          auth_username: me@domain.com
          auth_identity: me@domain.com
          auth_password:
            name: gmail-auth
            key: password
      - name: blackhole
```

This results in a `VMAlertmanagerConfig` thus:

```yaml
apiVersion: operator.victoriametrics.com/v1beta1
kind: VMAlertmanagerConfig
metadata:
  name: victoria-metrics-k8s-stack
  namespace: victoria-metrics-k8s-stack
spec:
  receivers:
    - email_configs:
        - auth_identity: me@domain.com
          auth_password:
            key: password
            name: gmail-auth
          auth_username: me@domain.com
          from: me@domain.com
          smarthost: smtp.gmail.com:587
          to: me@domain.com
      name: gmail
    - name: blackhole
  route:
    group_by:
      - alertgroup
      - job
    group_interval: 5m
    group_wait: 30s
    receiver: gmail
    repeat_interval: 12h
    routes:
      - continue: false
        matchers:
          - severity =~ "info|warning|critical"
        receiver: gmail
      - continue: true
        receiver: blackhole
```

So far, so good.

However, the final alertmanager.yaml config seen in the Alertmanager pod is:

```yaml
route:
  receiver: blackhole # where did this come from?
  routes:
  - routes:
    - matchers:
      - severity =~ "info|warning|critical"
      receiver: victoria-metrics-k8s-stack-victoria-metrics-k8s-stack-gmail
      continue: false
    - receiver: victoria-metrics-k8s-stack-victoria-metrics-k8s-stack-blackhole
      continue: true
    matchers:
    - namespace = "victoria-metrics-k8s-stack" # <- See below
    group_by:
    - alertgroup
    - job
    group_interval: 5m
    group_wait: 30s
    repeat_interval: 12h
    receiver: victoria-metrics-k8s-stack-victoria-metrics-k8s-stack-gmail
    continue: true
receivers:
- name: blackhole
- name: victoria-metrics-k8s-stack-victoria-metrics-k8s-stack-gmail
  email_configs:
  - auth_password: redacted
    from: me@domain.com
    to: me@domain.comm
    auth_identity: me@domain.com
    auth_username: me@domain.com
    smarthost: smtp.gmail.com:587
- name: victoria-metrics-k8s-stack-victoria-metrics-k8s-stack-blackhole
templates: []
```

The final result of this is that I have a configuration that (visually, in Grafana) looks like this:

![Image](https://github.com/user-attachments/assets/4799cf98-466c-482b-bd81-d17520aef370)

In other words, that default "blackhole" receiver is the parent, which is unexpected, _and_ the operator adding in the `namespace = "victoria-metrics-k8s-stack"` matcher to the level 1 receiver then also means that everything that is underneath of that (including the gmail config) _must_ match that label or it won't fire. Given that I have a bunch of stuff that's definitively not in that namespace, as of right now I can't get those alerts out.

So I think this might be a bug, but I also think I might not be understanding something here.

Any insights would be appreciated.

### Troubleshooting docs

- [x] General - https://docs.victoriametrics.com/troubleshooting/
- [x] vmagent - https://docs.victoriametrics.com/vmagent/#troubleshooting
- [x] vmalert - https://docs.victoriametrics.com/vmalert/#troubleshooting
