### ISSUE TITLE
Inline `secretRef` in `alertmanager.config.receivers[*].email_configs.auth_password` Helm values when `alertmanager.useManagedConfig: false` does not result in a usable configuration

### ISSUE THREAD

**Issue by djryanj** [VictoriaMetrics/VictoriaMetrics#8291]
### Describe the bug

When deploying alertmanager via `victoria-metrics-k8s-stack` Helm chart with (abbreviated) `values.yaml` thus:

```yaml
alertmanager:
  enabled: true
  useManagedConfig: false
  config: 
    route:
      receiver: "gmail"
      routes:
        - matchers:
            - severity =~ "info|warning|critical"
          receiver: gmail
          continue: false
        - continue: true
          receiver: blackhole
    receivers:
      - name: gmail
        email_configs:
        - to: me@domain.com
          from: me@domain.com
          smarthost: smtp.gmail.com:587
          auth_username: me@domain.com
          auth_identity: me@domain.com
          auth_password:
            name: gmail-auth
            key: password
      - name: blackhole
```

Assume that the secret `gmail-auth` is created correctly.

This creates the secret:

```yaml
apiVersion: v1
data:
  alertmanager.yaml: cmVjZWl2ZXJzOgotIGVtYWlsX2NvbmZpZ3M6CiAgLSBhdXRoX2lkZW50aXR5OiBtZUBkb21haW4uY29tCiAgICBhdXRoX3Bhc3N3b3JkOgogICAgICBrZXk6IHBhc3N3b3JkCiAgICAgIG5hbWU6IGdtYWlsLWF1dGgKICAgIGF1dGhfdXNlcm5hbWU6IG1lQGRvbWFpbi5jb20KICAgIGZyb206IG1lQGRvbWFpbi5jb20KICAgIHNtYXJ0aG9zdDogc210cC5nbWFpbC5jb206NTg3CiAgICB0bzogbWVAZG9tYWluLmNvbQogIG5hbWU6IGdtYWlsCi0gbmFtZTogYmxhY2tob2xlCnJvdXRlOgogIGdyb3VwX2J5OgogIC0gYWxlcnRncm91cAogIC0gam9iCiAgZ3JvdXBfaW50ZXJ2YWw6IDVtCiAgZ3JvdXBfd2FpdDogMzBzCiAgcmVjZWl2ZXI6IGdtYWlsCiAgcmVwZWF0X2ludGVydmFsOiAxMmgKICByb3V0ZXM6CiAgLSBjb250aW51ZTogZmFsc2UKICAgIG1hdGNoZXJzOgogICAgLSBzZXZlcml0eSA9fiAiaW5mb3x3YXJuaW5nfGNyaXRpY2FsIgogICAgcmVjZWl2ZXI6IGdtYWlsCiAgLSBjb250aW51ZTogdHJ1ZQogICAgcmVjZWl2ZXI6IGJsYWNraG9sZQp0ZW1wbGF0ZXM6CiAgLSAiL2V0Yy92bS9jb25maWdzLyoqLyoudG1wbCIK
kind: Secret
metadata:
  name: vmalertmanager-victoria-metrics-k8s-stack
  namespace: victoria-metrics-k8s-stack
type: Opaque
```

Decoding the base64 string above we get:

```yaml
receivers:
- email_configs:
  - auth_identity: me@domain.com
    auth_password:
      key: password  #<- this is incorrect
      name: gmail-auth
    auth_username: me@domain.com
    from: me@domain.com
    smarthost: smtp.gmail.com:587
    to: me@domain.com
  name: gmail
- name: blackhole
route:
  group_by:
  - alertgroup
  - job
  group_interval: 5m
  group_wait: 30s
  receiver: gmail
  repeat_interval: 12h
  routes:
  - continue: false
    matchers:
    - severity =~ "info|warning|critical"
    receiver: gmail
  - continue: true
    receiver: blackhole
templates:
  - "/etc/vm/configs/**/*.tmpl"
```

Which of course causes the alertmanager pod to error/crashloop:

```
level=error component=configuration msg="Loading configuration file failed" file=/etc/alertmanager/config/alertmanager.yaml err="yaml: unmarshal errors:\n  line 5: cannot unmarshal !!map into config.plain"
```

Using `alertmanager.useManagedConfig: true` in `values.yaml` works as expected.

### To Reproduce

Use the values provided above.

### Version

Helm chart version 0.36.0

### Logs

See above.
