### ISSUE TITLE
Duplicate metrics with HA pair of VMAgents

### ISSUE THREAD

**Issue by djryanj** [VictoriaMetrics/VictoriaMetrics#8309]
### Is your question request related to a specific component?

vmagent

### Describe the question in detail

When using `victoria-metrics-k8s-stack` Helm chart and setting up an HA pair of VMAgents using `values.yaml` like:

```yaml
vmcluster:
  enabled: true
  spec:
    replicationFactor: 2
    vmstorage:
      replicaCount: 2
      extraArgs:
        dedup.minScrapeInterval: 10s
    vmselect:
      replicaCount: 2
      extraArgs:
        dedup.minScrapeInterval: 10s
vmagent:
  enabled: true
  spec:
    scrapeInterval: 10s # global
    statefulMode: true # needed so that we can set up a cluster properly
    extraArgs:
      promscrape.streamParse: "true"
      promscrape.dropOriginalLabels: "false"
      promscrape.cluster.membersCount: "2"
      promscrape.cluster.replicationFactor: "2"
      envflag.enable: "true"
    extraEnvs:
      - name: promscrape_cluster_memberNum
        valueFrom:
          fieldRef:
            fieldPath: metadata.name
    replicaCount: 2
```

De-duplication doesn't seem to be happening.

For example:

![Image](https://github.com/user-attachments/assets/ae6f4669-b097-47ad-ac76-ec9189ae3c75)

I'm not really sure what I've done wrong; I have read and re-read the de-duplication docs but I just can't find what the problem is.

### Troubleshooting docs

- [x] General - https://docs.victoriametrics.com/troubleshooting/
- [x] vmagent - https://docs.victoriametrics.com/vmagent/#troubleshooting
- [x] vmalert - https://docs.victoriametrics.com/vmalert/#troubleshooting

**Comment by djryanj** [comment]
According to https://github.com/VictoriaMetrics/helm-charts/issues/298#issuecomment-2660997056, I have altered my config thus:

```yaml
vmagent:
  enabled: true
  spec:
    scrapeInterval: 10s # global
    statefulMode: true # needed so that we can set up a cluster properly
    extraArgs:
      promscrape.streamParse: "true"
      promscrape.dropOriginalLabels: "false"
    shardCount: 2
    replicaCount: 1
    affinity:
      podAntiAffinity:
        preferredDuringSchedulingIgnoredDuringExecution:
          - podAffinityTerm:
              labelSelector:
                matchLabels:
                  app.kubernetes.io/name: vmagent
              topologyKey: kubernetes.io/hostname
            weight: 100
```

Which has at least caused the scrape targets to now be showing "DROPPED (sharding)" which is an improvement: 

![Image](https://github.com/user-attachments/assets/79bfe5cd-54cf-48b6-8a95-88bf258a19d2)

However, I'm still seeing duplicate instances.
