### ISSUE TITLE
Some Targets in Service Discovery Are Not in Active State

### ISSUE THREAD

**Issue by girish-ms** [VictoriaMetrics/VictoriaMetrics#8313]
### Is your question request related to a specific component?

VictoriaMetrics Cluster, Agent, and Operator

### Describe the question in detail

I have configured VictoriaMetrics Cluster, Agent, and Operator in a Kubernetes cluster.

- All Prometheus rules, ServiceMonitors, and other configurations have been successfully ported to their VictoriaMetrics-compatible counterparts.
- I can see the targets in Service Discovery, but only a few are in an active state.

**Targets:**

<img width="593" alt="Image" src="https://github.com/user-attachments/assets/4a18e66d-5e4f-49e4-8a2a-80934fc681df" />

**vmservicescrapes:**
The STATUS and SYNC ERROR fields appear to be empty, making it difficult to troubleshoot.

<img width="808" alt="Image" src="https://github.com/user-attachments/assets/8c363f0d-461b-4d9e-9869-470e0c829ac2" />

Am I missing something in the configuration? Any help would be greatly appreciated!

### Troubleshooting docs

- [ ] General - https://docs.victoriametrics.com/troubleshooting/
- [ ] vmagent - https://docs.victoriametrics.com/vmagent/#troubleshooting
- [ ] vmalert - https://docs.victoriametrics.com/vmalert/#troubleshooting

**Comment by jiekun** [comment]
Hello. Could you provide the VMServiceScrape config for those targets? And what **Status** did you see in the service discovery page? Each service discovery targets should have a drop reason, e.g.:
- relabeling
- missing scrape URL
- duplicate
- sharding

<details>

![Image](https://github.com/user-attachments/assets/2b1184c1-a006-4817-8fa7-be2930fa4751)

</details>

Could you verify?

**Comment by girish-ms** [comment]
I could see it's dropped for relabeling

<img width="1243" alt="Image" src="https://github.com/user-attachments/assets/090408da-fce9-4cf3-b4c3-6b6a1ac9a6ac" />

VMServiceScrape configs:

kubectl get vmservicescrapes.operator.victoriametrics.com -n xxxx -o yaml

```
apiVersion: v1
items:
- apiVersion: operator.victoriametrics.com/v1beta1
  kind: VMServiceScrape
  metadata:
    labels:
      app.kubernetes.io/instance: xxxx
      app.kubernetes.io/name: xxxx
    name: xxxx
    namespace: xxxx
    ownerReferences:
    - apiVersion: monitoring.coreos.com/v1
      blockOwnerDeletion: true
      controller: true
      kind: ServiceMonitor
      name: xxxx
  spec:
    attach_metadata: {}
    endpoints:
    - attach_metadata: {}
      interval: 15s
      path: /metrics
      port: http
    namespaceSelector: {}
    selector:
      matchLabels:
        app.kubernetes.io/name: xxxx
        xxx: xxx
kind: List
metadata:
  resourceVersion:
```
