### ISSUE TITLE
vmalert: recording rule metric doesn't seem to match original

### ISSUE THREAD

**Issue by raags** [VictoriaMetrics/VictoriaMetrics#832]
**Describe the bug**
The screenshot below shows the difference in the original query, recording rule, and recording rule with a range vector of 1m.

![original v:s recording rules](https://user-images.githubusercontent.com/697714/95833164-e24e5680-0d58-11eb-9c25-a975a9cf5d40.png)

The recording rules are:
```
groups:
 - name: TestGroup
   rules:
     - record: test:node_cpu_seconds_total:no_range
       expr: >
         sum(rate(node_cpu_seconds_total{instance=~"victoriametrics01.*"}))

     - record: test:node_cpu_seconds_total:1m
       expr: >
         sum(rate(node_cpu_seconds_total{instance=~"victoriametrics01.*"}[1m]))
```

One difference is that Grafana uses `query_range` v/s `query` for recording rules. So I'm not sure how the `step` is calculated in recording rules v/s Grafana. So I added the `1m` range explicitly, but it still doesn't match.

**To Reproduce**
Add the above rules, and graph to see the difference.

**Expected behaviour**
The original and recorded metric should match. 

**Version**
The line returned when passing `--version` command line flag to binary. For example:
```
$ ./victoria-metrics-prod --version
victoria-metrics-20200929-211855-tags-v1.42.0-0-ge59de9838
```

**Used command-line flags**
```
$ /usr/local/bin/victoriametrics -loggerDisableTimestamps --storageDataPath=/var/lib/victoriametrics --selfScrapeInterval=0 --retentionPeriod=6 --memory.allowedPercent=60 --search.maxUniqueTimeseries=600000
```
```
$ /usr/local/bin/vmalert -loggerDisableTimestamps -datasource.url=http://localhost:8428 -remoteWrite.url=http://localhost:8429 -rule=/etc/victoriametrics/vmalert/*.yml -notifier.url http://locahost:9093 -evaluationInterval=1m0s
```

**Comment by hagen1778** [comment]
Hi @raags! 

> One difference is that Grafana uses query_range v/s query for recording rules.

Correct, and Grafana calculates the step value based on the panel size and your display resolution. To override the step set some value to `Min step` field below the query area.

`vmalert` execute queries via `/query` endpoint for instant results. It doesn't pass the `step` param, so VM uses the default value for it equal to `5m`.  So it is expected that `rate(metric)` (will have default 5m step) isn't the same as `rate(metric[1m])` (will have 1m step). Both won't match the expression in Grafana from your screenshot, since it is using the Grafana's defined step (which is likely seconds in this case).

**Comment by raags** [comment]
Ok - I was suspecting it was a `step` issue. However, Grafana min step is set `1min` (confirmed with query inspector), but it still doesn't match with the `rate(metric[1m])` recording rule.

**Comment by raags** [comment]
This is what I get with offset `2m`, although still not a clean match. Would this be related to the latest datapoint being not completly ingested? I'll try setting `-datasource.lookback` to `1m`.
![offset-2m](https://user-images.githubusercontent.com/697714/95844069-18460780-0d66-11eb-8f12-be629dbb3361.png)

**Comment by hagen1778** [comment]
Could you pls also update the A query by adding the `[1m]` vector and show the screenshot?

**Comment by raags** [comment]
Ok - now it's matching (after adding `-datasource.lookback`), but the original query requires an offset, why is that? My understanding of the `-datasource.lookback` is that it'll just calculate the new metric at an older data point, and not shift it.

![lookback-1m](https://user-images.githubusercontent.com/697714/95846486-192c6880-0d69-11eb-863c-56b694c33c42.png)

Also, I have another histogram that requires an offset of 2m to match:

![Screenshot 2020-10-13 at 3 27 16 PM](https://user-images.githubusercontent.com/697714/95861108-9f9f7500-0d7e-11eb-8bdb-63e6331db125.png)

The agg recording rules below has range vector of `[1m]`. Not sure why this needs 2m, while the above needs 1m.

**Comment by raags** [comment]
Also, would it also make sense to allow changing the default step in vmalert. This would enable keeping the expressions same in Grafana and recording rules. I like the optional range vector, as it simplifies things for users and just works.

**Comment by hagen1778** [comment]
> This would enable keeping the expressions same in Grafana and recording rules.

I don't see why it needs to be. Grafana is a visualisation tool with its own nuances like calculating step value based on display resolution. I don't think any datasource or other clients should do so as well.

**Comment by raags** [comment]
@hagen1778 but step changes the query itself, it's not the only visualization when its a recording rule. If I'm not mistaken, VM uses the step to set the range vector when not specified. i.e. `increase(m)` uses the step to make it `increase(m[1m])`. The implicit step means my recording rules are calculating `increase(m[5m)` which is completely different.

One appeal of VM is that Metricsql simplifies writing queries, and looks to be following a convention over configuration approach. In that vein, VMalert also should follow the same. The `5m` step seems implicit and would make sense to make it configurable and explicitly shows as part of the configuration.

**Comment by hagen1778** [comment]
I am still confused. The range vector may be omitted in MetircsQL and when someone is doing so - he relies on the VM to add it automatically. And VM does so by checking the `step` param and if it is empty - uses default value. But if someone wants to set it explicitly - he can just do it in the query by adding `[duration]` to it.  And I don't understand how it is different to adding some flag/param to `vmalert` to specify the step.

Let's get back to the question "This would enable keeping the expressions same in Grafana and recording rules.". If you omit range vector in Grafana then VM will calculate it automatically based on `step`. And if you do a zoom-in/zoom-out or open the panel on a different display - Grafana will change the `step` and displayed time series will change as well. So in order to keep "expressions the same" the one need to set the range vector explicitly in the query and not in Grafana/vmalert. It looks natural to me to communicate the range vector via query itself, because query is the only common thing between Grafana and vmalert.

**Comment by raags** [comment]
My point is in most cases you need not set the range vector because it defaults to an appropriate value. For e.g. in Grafana I set the min step as per the scrape interval, so `step` is consistent across all graphs. Same with recording rules, most likely my `[duration]` is going to be the same across all rules. I was looking for something similar in vmalert, like `--default-step`.

**Comment by raags** [comment]
This issue got digressed. @hagen1778 do you know why the offset behaviour happens explained here: https://github.com/VictoriaMetrics/VictoriaMetrics/issues/832#issuecomment-707709817

I have to add `offset 1m` in the first query, and `offset 2m` for the histogram for the recording rules to match.

**Comment by hagen1778** [comment]
Hi @raags! Could you pls check VM flag `search.latencyOffset`? I just did a test locally and it looks as expected
![image](https://user-images.githubusercontent.com/2902918/99452354-544b2a00-291b-11eb-9e30-56da95252d4e.png)
The reason for `offset 30s` is because I have `search.latencyOffset=30s` in my local setup. The flag description is following:
```
The time when data points become visible in query results after the collection. 
Too small value can result in incomplete last points for query results.
```
It is also important to mention that I have `scrapeInterval=1s` for `vmagent` (it scrapes nodeexporter and writes into VM) and  `interval: 2s` for vmalert rules group.

**Comment by raags** [comment]
@hagen1778 Got it. I have `search.latencyOffset=1m`, with `scrapeInterval=1m` and vmalert with `-evaluationInterval=1m` `-datasource.lookback=1m`. 

But why the descripancy between vmalert and grafana? Both run the same queries against VM with the same `search.latencyOffset` setting. Also even then that shouldn't offset the data point right? As per my understanding, It should **not** return the latest data point. So the calculation shoudn't change. 

If we have `[t1:v1, t2:v2, t3:v3]`, than query will return `[t1:v1, t2:v2]` (last data point not visible), but it shouldn't make it `[t1:v2, t2:v3]` (values shifted by 1m)

**Comment by hagen1778** [comment]
>  Both run the same queries against VM with the same search.latencyOffset setting. 

The difference is in the moment when query was evaluated. In Grafana you evaluate query now and it misses only datapoints in range from `now()` to `now() - search.latencyOffset`. `vmalert` evaluates queries every minute and stores results of those evaluations. So basically, the rule of "from `now()` to `now() - search.latencyOffset`" is true for every evaluation in `vmalert. For example:
```
0m	1m	2m	3m	4m	5m	6m
v1	v2	v3	v4	v5	v6	v7

Grafana rate:
	1m		2m		6m
(v2-v1)/1m	(v3-v2)/1m	...	(v6-v5)/1m

vmalert rate:
	1m		2m		6m
(v1-?)/?	(v2-v1)/1m	...	(v6-v5)/1m
```
As you see, on the moment of time `1m` `vmalert` doesn't see `v2` yet, on `2m` it doesn't see `v3` yet and so on. 
While Grafana doesn't see only the recent datapoints.

**Comment by raags** [comment]
Ah, so vmalert evaluates the latencyOffset at every 1m interval. Thanks for the explanation.

But this means recorded metrics have an offset equal to the `latencyOffset`; is that acceptable? Is there a way to fix it. The workaround is to have `-1m` offset. And the histogram I'm assuming needs 2m due to the way it's computed.

**Comment by hagen1778** [comment]
Hi @raags! The option to configure vmalert with step param was added in https://github.com/VictoriaMetrics/VictoriaMetrics/pull/1027/commits/fc8373c647c972dc64c5582f174e420779fb5730.

**Comment by raags** [comment]
Hi @hagen1778 that option solves the problem described in [this](https://github.com/VictoriaMetrics/VictoriaMetrics/issues/832#issuecomment-716341508) comment (which is helpful, but minor improvement) 

But doesn't solve the issue when using `latencyOffset`. And the `latencyOffset` cannot be less than the scrape interval. Otherwise the recording rule does not get all the data points to compute its value, since the latest scrape could be incomplete.

I think the solution here is to have another flag, that offsets `now` for vmalert, which should be set equal to `latencyOffset`. So for e.g. if the value of that is 1min, then vmalert should calculate the instant value and store for `now() - 1min` timestamp. 

Can you please reopen the ticket? It makes a difference because graphs are used for correlation - you'd look at multiple events / dashboards to check if the time matches. This will be off by a minute in this case, which is not a good experience.

**Comment by valyala** [comment]
@raags , such parameter is already supported by vmalert - this is `-datasource.lookback`. See https://github.com/VictoriaMetrics/VictoriaMetrics/issues/668 for more details.

**Comment by raags** [comment]
@valyala ok I tried with that, but it's still not working. Comparing the original with the recorded query still needs an offset. You can reproduce with he following:

**docker-compose.yml**
```
version: '2.4'
services:
  victoriametrics:
    container_name: victoriametrics
    image: victoriametrics/victoria-metrics
    ports:
      - 8428:8428
    volumes:
      - vmdata:/vmdata
    command:
      - '-storageDataPath=/vmdata'
      - '-httpListenAddr=:8428'
      - '-selfScrapeInterval=0'
      - '-search.latencyOffset=15s'
  vmagent:
    container_name: vmagent
    image: victoriametrics/vmagent
    depends_on:
      - victoriametrics
    ports:
      - 8429:8429
    volumes:
      - vmagentdata:/vmagentdata
      - ./vm.yml:/tmp/vm.yml
    command:
      - '-promscrape.config=/tmp/vm.yml'
      - '-remoteWrite.url=http://victoriametrics:8428/api/v1/write'
  vmalert:
    container_name: vmalert
    image: victoriametrics/vmalert
    depends_on:
      - victoriametrics
    volumes:
      - ./vmalert_rules.yml:/tmp/alert.rules
    command:
      - '-rule=/tmp/alert.rules'
      # dummy notifier
      - '-notifier.url=http://127.0.0.1:9093'
      - '-datasource.url=http://victoriametrics:8428'
      - '-remoteWrite.url=http://victoriametrics:8428'
      - '-datasource.queryStep=15s'
      - '-evaluationInterval=15s'
      - '-datasource.lookback=15s'
```
**vm.yml**
```
---
global:
  scrape_interval:     15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: static_scrape
    static_configs:
    - targets:
        - victoriametrics:8428
```

**alert.rules**
```
groups:
 - name: HistogramAggregations
   rules:
     - record: test:scrape_duration_seconds:15s
       expr: >
         sum(rate(scrape_duration_seconds{instance=~"victoriametrics.*"}[15s]))
```
Plotting `test:scrape_duration_seconds:15s` and `sum(rate(scrape_duration_seconds{instance=~"victoriametrics.*"}[15s]))` still requires a `15s` offset to match.
