### ISSUE TITLE
K8s: Can not get metrics from "Kube State Metrics"

### ISSUE THREAD

**Issue by soernt** [VictoriaMetrics/VictoriaMetrics#8338]
### Is your question request related to a specific component?

vmAgent

### Describe the question in detail

Hi there,

1. My setup: 
* K8s v1.32.0
* A VictoriaMetrics (v1.111.0) server is running outside of the cluster. 
* vmOperator installed via Helm chart (chart version 0.42.0) into namespace "monitoring"

2. What I want to do:
Collect K8s metrics via vmAgent and route them to the VictoraMetrics server.<br>

Setup a `VMServiceScrape` and  `VMAgent`:

```Yaml
######################################################################
apiVersion: operator.victoriametrics.com/v1beta1
kind: VMServiceScrape
metadata:
  name: kube-state-metrics-scrape
  namespace: monitoring
spec:
  jobLabel: app.kubernetes.io/name
  endpoints:
    - scheme: "http"    
      port: "8080"
      path: "/metrics"
      honorLabels: true
  
  namespaceSelector:
    matchNames:
      - monitoring
  selector:
    matchLabels:
      app.kubernetes.io/instance: kube-state-metrics
      app.kubernetes.io/name: kube-state-metrics      
---
######################################################################
apiVersion: operator.victoriametrics.com/v1beta1
kind: VMAgent
metadata:
  namespace: monitoring
  name: k8s-scraper-agent
spec:
  vmAgentExternalLabelName: vmagent_k8s_scraper
  selectAllByDefault: true
  replicaCount: 1

  scrapeInterval: 15s
  scrapeTimeout: 10s
  
  remoteWrite:
    - url: "http://kc01-infra01:8428//api/v1/write"

  resources:
    requests:
      memory: "64Mi"
      cpu: "250m"
    limits:
      memory: "128Mi"
      cpu: "500m"    
```

```Shell
kubectl get services -n monitoring
NAME                                   TYPE        CLUSTER-IP       EXTERNAL-IP   PORT(S)             AGE
kube-state-metrics                     ClusterIP   10.104.10.142    <none>        8080/TCP            2d3h
node-exporter                          ClusterIP   10.108.140.221   <none>        9100/TCP            8h
vmagent-k8s-scraper-agent              ClusterIP   10.105.56.41     <none>        8429/TCP            81m
vmoperator-victoria-metrics-operator   ClusterIP   10.96.122.45     <none>        8080/TCP,9443/TCP   140m
```

Searching for the service via the namespace and matching labels gives me the expected result:
```Shell
kubectl get services -n monitoring -l app.kubernetes.io/instance=kube-state-metrics,app.kubernetes.io/name=kube-state-metrics
NAME                 TYPE        CLUSTER-IP      EXTERNAL-IP   PORT(S)    AGE
kube-state-metrics   ClusterIP   10.104.10.142   <none>        8080/TCP   2d3h
```

3. What worked:<br>
I verified that the `kub-state-metric Service` is running by createing a port forwarding to the service to port 8080. I can navigate to http://localhost:8080/metrics the metrics gets displayed.<br><br>
Within the VictoryMetrics Server I see Metrics regarding to the `vmagent-k8s-scraper-agent`.

4. What not worked:<br>
Scraping the Metrics from `kub-state-metric Service`. I create a port forwarding to the `vmagent-k8s-scraper-agent` to port 8429. When I navigate to `http://localhost:8429/targets`, I see two active tareget:

![Image](https://github.com/user-attachments/assets/2038cb11-9c60-42cb-8e7e-3dbbfaacb441)

Can some please point me to what might go wrong, I see no hints, attemps or protocol to get an idea.

Thank you for any help :-)

### Troubleshooting docs

- [ ] General - https://docs.victoriametrics.com/troubleshooting/
- [ ] vmagent - https://docs.victoriametrics.com/vmagent/#troubleshooting
- [ ] vmalert - https://docs.victoriametrics.com/vmalert/#troubleshooting

**Comment by jiekun** [comment]
Hello. Could you check the "Discovered targets" tab on the screenshot you attached? It should have the discovered target and tell you why they are dropped.

**Comment by soernt** [comment]
Thank you for the hint.
I see that alot of items with the status: `DROPPED (relabeling)`. On each row there is a `debug` which displays some `Relabel configs`.

For example this one:

Relabel configs:
```YAML
- action: keep
  source_labels: [__meta_kubernetes_service_label_app_kubernetes_io_instance]
  regex: kube-state-metrics
- action: keep
  source_labels: [__meta_kubernetes_service_label_app_kubernetes_io_name]
  regex: kube-state-metrics
- action: keep
  source_labels: [__meta_kubernetes_endpoint_port_name]
  regex: "8080"
- source_labels: [__meta_kubernetes_endpoint_address_target_kind, __meta_kubernetes_endpoint_address_target_name]
  separator: ;
  target_label: node
  regex: Node;(.*)
  replacement: ${1}
- source_labels: [__meta_kubernetes_endpoint_address_target_kind, __meta_kubernetes_endpoint_address_target_name]
  separator: ;
  target_label: pod
  regex: Pod;(.*)
  replacement: ${1}
- source_labels: [__meta_kubernetes_pod_name]
  target_label: pod
- source_labels: [__meta_kubernetes_pod_container_name]
  target_label: container
- source_labels: [__meta_kubernetes_namespace]
  target_label: namespace
- source_labels: [__meta_kubernetes_service_name]
  target_label: service
- source_labels: [__meta_kubernetes_service_name]
  target_label: job
  replacement: ${1}
- source_labels: [__meta_kubernetes_service_label_app_kubernetes_io_name]
  target_label: job
  regex: (.+)
  replacement: ${1}
- target_label: endpoint
  replacement: "8080"
```
Labels:

```Text
{

__address__="10.244.0.177:8429",__meta_kubernetes_endpoint_address_target_kind="Pod",__meta_kubernetes_endpoint_address_target_name="vmagent-k8s-scraper-agent-758848565-jpv7k",__meta_kubernetes_endpoint_node_name="kc01-n03",__meta_kubernetes_endpoint_port_name="http",__meta_kubernetes_endpoint_port_protocol="TCP",__meta_kubernetes_endpoint_ready="true",__meta_kubernetes_endpoints_annotation_endpoints_kubernetes_io_last_change_trigger_time="2025-02-19T10:43:51Z",__meta_kubernetes_endpoints_annotationpresent_endpoints_kubernetes_io_last_change_trigger_time="true",__meta_kubernetes_endpoints_label_app_kubernetes_io_component="monitoring",__meta_kubernetes_endpoints_label_app_kubernetes_io_instance="k8s-scraper-agent",__meta_kubernetes_endpoints_label_app_kubernetes_io_name="vmagent",__meta_kubernetes_endpoints_label_managed_by="vm-operator",__meta_kubernetes_endpoints_labelpresent_app_kubernetes_io_component="true",__meta_kubernetes_endpoints_labelpresent_app_kubernetes_io_instance="true",__meta_kubernetes_endpoints_labelpresent_app_kubernetes_io_name="true",__meta_kubernetes_endpoints_labelpresent_managed_by="true",__meta_kubernetes_endpoints_name="vmagent-k8s-scraper-agent",__meta_kubernetes_namespace="monitoring",__meta_kubernetes_pod_container_image="victoriametrics/vmagent:v1.110.0",__meta_kubernetes_pod_container_init="false",__meta_kubernetes_pod_container_name="vmagent",__meta_kubernetes_pod_container_port_name="http",__meta_kubernetes_pod_container_port_number="8429",__meta_kubernetes_pod_container_port_protocol="TCP",__meta_kubernetes_pod_controller_kind="ReplicaSet",__meta_kubernetes_pod_controller_name="vmagent-k8s-scraper-agent-758848565",__meta_kubernetes_pod_host_ip="192.168.200.22",__meta_kubernetes_pod_ip="10.244.0.177",__meta_kubernetes_pod_label_app_kubernetes_io_component="monitoring",__meta_kubernetes_pod_label_app_kubernetes_io_instance="k8s-scraper-agent",__meta_kubernetes_pod_label_app_kubernetes_io_name="vmagent",__meta_kubernetes_pod_label_managed_by="vm-operator",__meta_kubernetes_pod_label_pod_template_hash="758848565",__meta_kubernetes_pod_labelpresent_app_kubernetes_io_component="true",__meta_kubernetes_pod_labelpresent_app_kubernetes_io_instance="true",__meta_kubernetes_pod_labelpresent_app_kubernetes_io_name="true",__meta_kubernetes_pod_labelpresent_managed_by="true",__meta_kubernetes_pod_labelpresent_pod_template_hash="true",__meta_kubernetes_pod_name="vmagent-k8s-scraper-agent-758848565-jpv7k",__meta_kubernetes_pod_node_name="kc01-n03",__meta_kubernetes_pod_phase="Running",__meta_kubernetes_pod_ready="true",__meta_kubernetes_pod_uid="11ec03b5-7432-461b-b745-b62dc79c6030",__meta_kubernetes_service_cluster_ip="10.111.167.225",__meta_kubernetes_service_label_app_kubernetes_io_component="monitoring",__meta_kubernetes_service_label_app_kubernetes_io_instance="k8s-scraper-agent",__meta_kubernetes_service_label_app_kubernetes_io_name="vmagent",__meta_kubernetes_service_label_managed_by="vm-operator",__meta_kubernetes_service_labelpresent_app_kubernetes_io_component="true",__meta_kubernetes_service_labelpresent_app_kubernetes_io_instance="true",__meta_kubernetes_service_labelpresent_app_kubernetes_io_name="true",__meta_kubernetes_service_labelpresent_managed_by="true",__meta_kubernetes_service_name="vmagent-k8s-scraper-agent",__meta_kubernetes_service_type="ClusterIP",__metrics_path__="/metrics",__scheme__="http",__scrape_interval__="15s",__scrape_timeout__="10s",job="serviceScrape/monitoring/kube-state-metrics-scrape/0"
__address__="10.244.0.177:8429",
__meta_kubernetes_endpoint_address_target_kind="Pod",
__meta_kubernetes_endpoint_address_target_name="vmagent-k8s-scraper-agent-758848565-jpv7k",
__meta_kubernetes_endpoint_node_name="kc01-n03",
__meta_kubernetes_endpoint_port_name="http",
__meta_kubernetes_endpoint_port_protocol="TCP",
__meta_kubernetes_endpoint_ready="true",
__meta_kubernetes_endpoints_annotation_endpoints_kubernetes_io_last_change_trigger_time="2025-02-19T10:43:51Z",
__meta_kubernetes_endpoints_annotationpresent_endpoints_kubernetes_io_last_change_trigger_time="true",
__meta_kubernetes_endpoints_label_app_kubernetes_io_component="monitoring",
__meta_kubernetes_endpoints_label_app_kubernetes_io_instance="k8s-scraper-agent",
__meta_kubernetes_endpoints_label_app_kubernetes_io_name="vmagent",
__meta_kubernetes_endpoints_label_managed_by="vm-operator",
__meta_kubernetes_endpoints_labelpresent_app_kubernetes_io_component="true",
__meta_kubernetes_endpoints_labelpresent_app_kubernetes_io_instance="true",
__meta_kubernetes_endpoints_labelpresent_app_kubernetes_io_name="true",
__meta_kubernetes_endpoints_labelpresent_managed_by="true",
__meta_kubernetes_endpoints_name="vmagent-k8s-scraper-agent",
__meta_kubernetes_namespace="monitoring",
__meta_kubernetes_pod_container_image="victoriametrics/vmagent:v1.110.0",
__meta_kubernetes_pod_container_init="false",
__meta_kubernetes_pod_container_name="vmagent",
__meta_kubernetes_pod_container_port_name="http",
__meta_kubernetes_pod_container_port_number="8429",
__meta_kubernetes_pod_container_port_protocol="TCP",
__meta_kubernetes_pod_controller_kind="ReplicaSet",
__meta_kubernetes_pod_controller_name="vmagent-k8s-scraper-agent-758848565",
__meta_kubernetes_pod_host_ip="192.168.200.22",
__meta_kubernetes_pod_ip="10.244.0.177",
__meta_kubernetes_pod_label_app_kubernetes_io_component="monitoring",
__meta_kubernetes_pod_label_app_kubernetes_io_instance="k8s-scraper-agent",
__meta_kubernetes_pod_label_app_kubernetes_io_name="vmagent",
__meta_kubernetes_pod_label_managed_by="vm-operator",
__meta_kubernetes_pod_label_pod_template_hash="758848565",
__meta_kubernetes_pod_labelpresent_app_kubernetes_io_component="true",
__meta_kubernetes_pod_labelpresent_app_kubernetes_io_instance="true",
__meta_kubernetes_pod_labelpresent_app_kubernetes_io_name="true",
__meta_kubernetes_pod_labelpresent_managed_by="true",
__meta_kubernetes_pod_labelpresent_pod_template_hash="true",
__meta_kubernetes_pod_name="vmagent-k8s-scraper-agent-758848565-jpv7k",
__meta_kubernetes_pod_node_name="kc01-n03",
__meta_kubernetes_pod_phase="Running",
__meta_kubernetes_pod_ready="true",
__meta_kubernetes_pod_uid="11ec03b5-7432-461b-b745-b62dc79c6030",
__meta_kubernetes_service_cluster_ip="10.111.167.225",
__meta_kubernetes_service_label_app_kubernetes_io_component="monitoring",
__meta_kubernetes_service_label_app_kubernetes_io_instance="k8s-scraper-agent",
__meta_kubernetes_service_label_app_kubernetes_io_name="vmagent",
__meta_kubernetes_service_label_managed_by="vm-operator",
__meta_kubernetes_service_labelpresent_app_kubernetes_io_component="true",
__meta_kubernetes_service_labelpresent_app_kubernetes_io_instance="true",
__meta_kubernetes_service_labelpresent_app_kubernetes_io_name="true",
__meta_kubernetes_service_labelpresent_managed_by="true",
__meta_kubernetes_service_name="vmagent-k8s-scraper-agent",
__meta_kubernetes_service_type="ClusterIP",
__metrics_path__="/metrics",
__scheme__="http",
__scrape_interval__="15s",
__scrape_timeout__="10s",
job="serviceScrape/monitoring/kube-state-metrics-scrape/0"
}
```

Original labels:
```Text
{
    __address__="10.244.0.177:8429",
    __meta_kubernetes_endpoint_address_target_kind="Pod",
    __meta_kubernetes_endpoint_address_target_name="vmagent-k8s-scraper-agent-758848565-jpv7k",
    __meta_kubernetes_endpoint_node_name="kc01-n03",
    __meta_kubernetes_endpoint_port_name="http",
    __meta_kubernetes_endpoint_port_protocol="TCP",
    __meta_kubernetes_endpoint_ready="true",
    __meta_kubernetes_endpoints_annotation_endpoints_kubernetes_io_last_change_trigger_time="2025-02-19T10:43:51Z",
    __meta_kubernetes_endpoints_annotationpresent_endpoints_kubernetes_io_last_change_trigger_time="true",
    __meta_kubernetes_endpoints_label_app_kubernetes_io_component="monitoring",
    __meta_kubernetes_endpoints_label_app_kubernetes_io_instance="k8s-scraper-agent",
    __meta_kubernetes_endpoints_label_app_kubernetes_io_name="vmagent",
    __meta_kubernetes_endpoints_label_managed_by="vm-operator",
    __meta_kubernetes_endpoints_labelpresent_app_kubernetes_io_component="true",
    __meta_kubernetes_endpoints_labelpresent_app_kubernetes_io_instance="true",
    __meta_kubernetes_endpoints_labelpresent_app_kubernetes_io_name="true",
    __meta_kubernetes_endpoints_labelpresent_managed_by="true",
    __meta_kubernetes_endpoints_name="vmagent-k8s-scraper-agent",
    __meta_kubernetes_namespace="monitoring",
    __meta_kubernetes_pod_container_image="victoriametrics/vmagent:v1.110.0",
    __meta_kubernetes_pod_container_init="false",
    __meta_kubernetes_pod_container_name="vmagent",
    __meta_kubernetes_pod_container_port_name="http",
    __meta_kubernetes_pod_container_port_number="8429",
    __meta_kubernetes_pod_container_port_protocol="TCP",
    __meta_kubernetes_pod_controller_kind="ReplicaSet",
    __meta_kubernetes_pod_controller_name="vmagent-k8s-scraper-agent-758848565",
    __meta_kubernetes_pod_host_ip="192.168.200.22",
    __meta_kubernetes_pod_ip="10.244.0.177",
    __meta_kubernetes_pod_label_app_kubernetes_io_component="monitoring",
    __meta_kubernetes_pod_label_app_kubernetes_io_instance="k8s-scraper-agent",
    __meta_kubernetes_pod_label_app_kubernetes_io_name="vmagent",
    __meta_kubernetes_pod_label_managed_by="vm-operator",
    __meta_kubernetes_pod_label_pod_template_hash="758848565",
    __meta_kubernetes_pod_labelpresent_app_kubernetes_io_component="true",
    __meta_kubernetes_pod_labelpresent_app_kubernetes_io_instance="true",
    __meta_kubernetes_pod_labelpresent_app_kubernetes_io_name="true",
    __meta_kubernetes_pod_labelpresent_managed_by="true",
    __meta_kubernetes_pod_labelpresent_pod_template_hash="true",
    __meta_kubernetes_pod_name="vmagent-k8s-scraper-agent-758848565-jpv7k",
    __meta_kubernetes_pod_node_name="kc01-n03",
    __meta_kubernetes_pod_phase="Running",
    __meta_kubernetes_pod_ready="true",
    __meta_kubernetes_pod_uid="11ec03b5-7432-461b-b745-b62dc79c6030",
    __meta_kubernetes_service_cluster_ip="10.111.167.225",
    __meta_kubernetes_service_label_app_kubernetes_io_component="monitoring",
    __meta_kubernetes_service_label_app_kubernetes_io_instance="k8s-scraper-agent",
    __meta_kubernetes_service_label_app_kubernetes_io_name="vmagent",
    __meta_kubernetes_service_label_managed_by="vm-operator",
    __meta_kubernetes_service_labelpresent_app_kubernetes_io_component="true",
    __meta_kubernetes_service_labelpresent_app_kubernetes_io_instance="true",
    __meta_kubernetes_service_labelpresent_app_kubernetes_io_name="true",
    __meta_kubernetes_service_labelpresent_managed_by="true",
    __meta_kubernetes_service_name="vmagent-k8s-scraper-agent",
    __meta_kubernetes_service_type="ClusterIP",
    __metrics_path__="/metrics",
    __scheme__="http",
    __scrape_interval__="15s",
    __scrape_timeout__="10s",
    job="serviceScrape/monitoring/kube-state-metrics-scrape/0"
}
```
Below that a table with steps are displayed, there is only one step:

Relabeling Rule:
```
action: keep
source_labels: [__meta_kubernetes_service_label_app_kubernetes_io_instance]
regex: kube-state-metrics
```

Input Lables (in red):
```
{__address__="10.244.0.177:8429", __meta_kubernetes_endpoint_address_target_kind="Pod", __meta_kubernetes_endpoint_address_target_name="vmagent-k8s-scraper-agent-758848565-jpv7k", __meta_kubernetes_endpoint_node_name="kc01-n03", __meta_kubernetes_endpoint_port_name="http", __meta_kubernetes_endpoint_port_protocol="TCP", __meta_kubernetes_endpoint_ready="true", __meta_kubernetes_endpoints_annotation_endpoints_kubernetes_io_last_change_trigger_time="2025-02-19T10:43:51Z", __meta_kubernetes_endpoints_annotationpresent_endpoints_kubernetes_io_last_change_trigger_time="true", __meta_kubernetes_endpoints_label_app_kubernetes_io_component="monitoring", __meta_kubernetes_endpoints_label_app_kubernetes_io_instance="k8s-scraper-agent", __meta_kubernetes_endpoints_label_app_kubernetes_io_name="vmagent", __meta_kubernetes_endpoints_label_managed_by="vm-operator", __meta_kubernetes_endpoints_labelpresent_app_kubernetes_io_component="true", __meta_kubernetes_endpoints_labelpresent_app_kubernetes_io_instance="true", __meta_kubernetes_endpoints_labelpresent_app_kubernetes_io_name="true", __meta_kubernetes_endpoints_labelpresent_managed_by="true", __meta_kubernetes_endpoints_name="vmagent-k8s-scraper-agent", __meta_kubernetes_namespace="monitoring", __meta_kubernetes_pod_container_image="victoriametrics/vmagent:v1.110.0", __meta_kubernetes_pod_container_init="false", __meta_kubernetes_pod_container_name="vmagent", __meta_kubernetes_pod_container_port_name="http", __meta_kubernetes_pod_container_port_number="8429", __meta_kubernetes_pod_container_port_protocol="TCP", __meta_kubernetes_pod_controller_kind="ReplicaSet", __meta_kubernetes_pod_controller_name="vmagent-k8s-scraper-agent-758848565", __meta_kubernetes_pod_host_ip="192.168.200.22", __meta_kubernetes_pod_ip="10.244.0.177", __meta_kubernetes_pod_label_app_kubernetes_io_component="monitoring", __meta_kubernetes_pod_label_app_kubernetes_io_instance="k8s-scraper-agent", __meta_kubernetes_pod_label_app_kubernetes_io_name="vmagent", __meta_kubernetes_pod_label_managed_by="vm-operator", __meta_kubernetes_pod_label_pod_template_hash="758848565", __meta_kubernetes_pod_labelpresent_app_kubernetes_io_component="true", __meta_kubernetes_pod_labelpresent_app_kubernetes_io_instance="true", __meta_kubernetes_pod_labelpresent_app_kubernetes_io_name="true", __meta_kubernetes_pod_labelpresent_managed_by="true", __meta_kubernetes_pod_labelpresent_pod_template_hash="true", __meta_kubernetes_pod_name="vmagent-k8s-scraper-agent-758848565-jpv7k", __meta_kubernetes_pod_node_name="kc01-n03", __meta_kubernetes_pod_phase="Running", __meta_kubernetes_pod_ready="true", __meta_kubernetes_pod_uid="11ec03b5-7432-461b-b745-b62dc79c6030", __meta_kubernetes_service_cluster_ip="10.111.167.225", __meta_kubernetes_service_label_app_kubernetes_io_component="monitoring", __meta_kubernetes_service_label_app_kubernetes_io_instance="k8s-scraper-agent", __meta_kubernetes_service_label_app_kubernetes_io_name="vmagent", __meta_kubernetes_service_label_managed_by="vm-operator", __meta_kubernetes_service_labelpresent_app_kubernetes_io_component="true", __meta_kubernetes_service_labelpresent_app_kubernetes_io_instance="true", __meta_kubernetes_service_labelpresent_app_kubernetes_io_name="true", __meta_kubernetes_service_labelpresent_managed_by="true", __meta_kubernetes_service_name="vmagent-k8s-scraper-agent", __meta_kubernetes_service_type="ClusterIP", __metrics_path__="/metrics", __scheme__="http", __scrape_interval__="15s", __scrape_timeout__="10s", job="serviceScrape/monitoring/kube-state-metrics-scrape/0"}
```
and an empty "Output labels" column.

I did not define any relabeling rules.

I have no idea what the rule does.

**Comment by jiekun** [comment]
Hi. You are already in the right direction! 

By debugging the relabeling rule, it seems this rule dropped your target:
```
action: keep
source_labels: [__meta_kubernetes_service_label_app_kubernetes_io_instance]
regex: kube-state-metrics
```

It require the `__meta_kubernetes_service_label_app_kubernetes_io_instance` label value to match `kube-state-metrics`, while the input label you have does not met the requirement:
```
__meta_kubernetes_service_label_app_kubernetes_io_instance="k8s-scraper-agent",
```

So this target is dropped.

![Image](https://github.com/user-attachments/assets/7939d941-e913-42aa-8d37-08be2ad39675)

**Comment by soernt** [comment]
Thank you for your investigation!

It sounds like that the rule is somhow defined for the "kube-state-metrics" target, but it is applied from scraped data of "k8s-scraper-agent". That sounds wrong. 

That looks like that my vmAgent delaration:

```YAML
apiVersion: operator.victoriametrics.com/v1beta1
kind: VMAgent
metadata:
  namespace: monitoring
  name: k8s-scraper-agent
spec:
  vmAgentExternalLabelName: vmagent_k8s_scraper
  selectAllByDefault: true
  replicaCount: 1

  scrapeInterval: 15s
  scrapeTimeout: 10s
  
  remoteWrite:
    - url: "http://kc01-infra01:8428//api/v1/write"

  resources:
    requests:
      memory: "64Mi"
      cpu: "250m"
    limits:
      memory: "128Mi"
      cpu: "500m"    
```
Collects targets that it should not.

The list of active targets has two items:
1. serviceScrape/monitoring/vmagent-k8s-scraper-agent/0 (1/1 up)
2. serviceScrape/monitoring/kube-state-metrics-scrape/0 (0/0 up)

So it looks like that the rule defined by target 2 is applied to data defined by target 1.

What do I need to modify within my VMAgent, that it only considers my single scrape definition:

```YAML
apiVersion: operator.victoriametrics.com/v1beta1
kind: VMServiceScrape
metadata:
  name: kube-state-metrics-scrape
  namespace: monitoring
spec:
  jobLabel: app.kubernetes.io/name
  endpoints:
    - scheme: "http"    
      port: "8080"
      path: "/metrics"
      honorLabels: true
  
  namespaceSelector:
    matchNames:
      - monitoring
  selector:
    matchLabels:
      app.kubernetes.io/instance: kube-state-metrics
      app.kubernetes.io/name: kube-state-metrics
```

**Comment by f41gh7** [comment]
First of all, you don't have `kube-state-metrics` installed.  https://github.com/kubernetes/kube-state-metrics/tree/main/examples/standard

Second,  `kube-state-metrics` may not have doesn't have `instance` label. It's recommended to check an actual service labels. https://github.com/kubernetes/kube-state-metrics/blob/main/examples/standard/service.yaml#L4

`port` should be the name of actual Service port name https://github.com/kubernetes/kube-state-metrics/blob/main/examples/standard/service.yaml#L13

 Working VMServiceScrape example for standard kube-state-metrics is:
```
apiVersion: operator.victoriametrics.com/v1beta1
kind: VMServiceScrape
metadata:
  name: kube-state-metrics-scrape
  namespace: monitoring
spec:
  endpoints:
  - honorLabels: true
    path: /metrics
    port: http-metrics
    scheme: http
  jobLabel: app.kubernetes.io/name
  namespaceSelector:
    matchNames:
    - kube-system
  selector:
    matchLabels:
      app.kubernetes.io/name: kube-state-metrics

```

And make sure, that kube-state-metrics is installed at the correct namespace.





And I also, I'd recommend to start with some predefined "monitoring distributive", like k8s-stack helm chart: https://github.com/VictoriaMetrics/helm-charts/tree/master/charts/victoria-metrics-k8s-stack
