### ISSUE TITLE
Consume metrics for prometheus adapter

### ISSUE THREAD

**Issue by nirmal20081028** [VictoriaMetrics/VictoriaMetrics#8350]
### Is your question request related to a specific component?

We have vmagent collecting and writing metrics to  vmcluster.Now we need to implement prometheus adapter to use customer metrics for hpa.In that case , what url needs to added in prometheus adapter section.
```
prometheus:
  # Value is templated
  url: <>. --> here 
  port: 
  path: ""
```
### Describe the question in detail

We have vmagent collecting and writing metrics to  vmcluster.Now we need to implement prometheus adapter to use customer metrics for hpa.In that case , what url needs to added in prometheus adapter section.
```
prometheus:
  # Value is templated
  url: <>. --> here 
  port: 
  path: ""
```
### Troubleshooting docs

- [ ] General - https://docs.victoriametrics.com/troubleshooting/
- [ ] vmagent - https://docs.victoriametrics.com/vmagent/#troubleshooting
- [ ] vmalert - https://docs.victoriametrics.com/vmalert/#troubleshooting
