### ISSUE TITLE
scrape_config RelabelConfig replace not working as expected

### ISSUE THREAD

**Issue by suiaji** [VictoriaMetrics/VictoriaMetrics#8370]
### Describe the bug

I basically wanna replace the label key `name` with the key `source` in a prometheus scrape_config:

```
scrape_configs:
- job_name: gnmic
  metrics_path: /metrics
  scrape_interval: 60s
  scrape_timeout: 10s
  static_configs:
  - targets:
    - 127.0.0.1:7890
  relabel_configs:
  - source_labels: [name]
    action: replace
    regex: (.+)
    target_label: source
    replacement: $1
```
expected output:
`gnmic_target_up{instance="127.0.0.1:7890",job="gnmic",source="test"} 1`

actual output
`gnmic_target_up{instance="127.0.0.1:7890",job="gnmic",name="test"} 1`

same result with implicit defaults:
```
relabel_configs:
  - source_labels: [name]
    target_label: source
```

both `relabel_configs` above work partially correct in VMs `metric-relabel-debug` (see screenshot below)

`gnmic_target_up{instance="127.0.0.1:7890", job="gnmic", name="test", source="test"}`

the expected `source="test"` is present, but `name="test"` is not dropped.

### To Reproduce

- change/add relabel_config
- sudo systemctl restart victoriametrics.service
- wait some time until targets were scraped
- explore metric labels with vmui

### Version

$ victoria-metrics-prod --version
victoria-metrics-20250210-142641-tags-v1.111.0-0-gee8f852a83

- single-node installation
- debian 12
-  VM ansible collection used

### Screenshots

![Image](https://github.com/user-attachments/assets/810a8ac0-25a2-4689-a55f-b1c68d6bf6b4)

### Additional information

thanks for VM!

**Comment by jiekun** [comment]
Could you try:
```
  - source_labels: [source]
    target_label: name
    replacement: $1
  - action: labeldrop
    regex: "source"
```

https://play.victoriametrics.com/select/0/vmui/#/relabeling?config=++-+source_labels%3A+%5Bsource%5D%0A++++target_label%3A+name%0A++++replacement%3A+%241%0A++-+action%3A+labeldrop%0A++++regex%3A+%22source%22&labels=gnmic_target_up%7Binstance%3D%22127.0.0.1%3A7890%22%2Cjob%3D%22gnmic%22%2Cname%3D%22test%22%2C+source%3D%22test2%22%7D

**Comment by suiaji** [comment]
Hello @jiekun ,

thanks for your help!

Other way around with source and name but that does not matter for the playground. 
Using the `labeldrop` indeed solves the problem for the `metric-relabel-debug`

```
  relabel_configs:
    - source_labels: [name]
      target_label: source
      replacement: $1
    - action: labeldrop
      regex: "name"
```

see [playground](https://play.victoriametrics.com/select/0/vmui/#/relabeling?config=++-+source_labels%3A+%5Bname%5D%0A++++target_label%3A+source%0A++++replacement%3A+%241%0A++-+action%3A+labeldrop%0A++++regex%3A+%22name%22&labels=gnmic_target_up%7Binstance%3D%22127.0.0.1%3A7890%22%2Cjob%3D%22gnmic%22%2Cname%3D%22test%22%7D)

Unfortunately it does not with the prometheus scrape config:

/etc/victoriametrics/prometheus_scrape.yaml
```
scrape_configs:
- job_name: gnmic
  metrics_path: /metrics
  scrape_interval: 60s
  scrape_timeout: 10s
  static_configs:
  - targets:
    - 127.0.0.1:7890
  relabel_configs:
    - source_labels: [name]
      target_label: source
      replacement: $1
    - action: labeldrop
      regex: "name"
```

still results in:

```
  {
    "metric": {
      "__name__": "gnmic_target_up",
      "instance": "127.0.0.1:7890",
      "job": "gnmic",
      "name": "test"
    },
    "value": [
      1740133138.183,
      "1"
    ],
    "group": 1
  },
```

As written in the initial report, the label is not changed at all.

Any ideas/hints?


PS: just to explicate: not using vmagent
