### ISSUE TITLE
vmagent: error when receiving zstd-compressed datadog metrics

### ISSUE THREAD

**Issue by hluaces** [VictoriaMetrics/VictoriaMetrics#8380]
### Describe the bug

`vmagent` v1.111.0 is rejecting payloads sent from datadog-agents that are using `zstd` as their compression strategy. Note that datadog agent versions 7.62 and above have changed their default compression strategy from `zlib` to `zstd`.

I can't pinpoint the exact error, but I've seen a fair increase of these in my logs, so they might be related:

```
2025-02-24 13:22:24 UTC | CORE | ERROR | (comp/forwarder/defaultforwarder/transaction/transaction.go:427 in internalProcess) | Error code     "400 Bad Request" received while sending transaction to "https://[REDACTED]/datadog/api/v2/series": "remoteAddr: \"[REDACTED #2]:39840, X-Forwarded-For: [REDACTED #3]]\"; requestURI: /datadog/api/v2/series; cannot unmarshal DataDog application/x-protobuf request with size 144706 bytes: cannot unmarshal next field: unknown wireType=6\n", dropping it
2025-02-24 13:22:24 UTC | CORE | ERROR | (comp/forwarder/defaultforwarder/transaction/transaction.go:427 in internalProcess) | Error code     "400 Bad Request" received while sending transaction to "https://[REDACTED]/datadog/api/v2/series": "remoteAddr: \"[REDACTED #2]:45252, X-Forwarded-For: [REDACTED #3]]\"; requestURI: /datadog/api/v2/series; cannot unmarshal DataDog application/x-protobuf request with size 6158 bytes: cannot unmarshal next field: unknown wireType=3\n", dropping it
```

These are the related releases and PRs to the datadog agent:

- https://github.com/DataDog/datadog-agent/pull/32440                                                                                     
- https://github.com/DataDog/datadog-agent/releases/tag/7.62.0  

As a workaround, I'm configuring `serializer_compressor_kind` in the agent, setting it to `zlib` (environment variable `DD_SERIALIZER_COMPRESSOR_KIND` also works).

### To Reproduce

This dockerfile sets up a sample configuration with:

- a victoria backend
- an vmagent that forwards requests to victoria
- a 7.63 datadog monitor that ships data to vmagent

Accessing the VM backend (`http://127.0.0.1:8428/vmui/`) and polling for a sample metric (e.g.: `datadog.agent.started{}`) won't show any data. Docker logs will show these errors:

```sh
dd-monitor-problem-vmagent-1   | 2025-02-24T14:05:38.659Z	warn	VictoriaMetrics/app/vmagent/main.go:387	remoteAddr: "172.26.0.4:60370"; requestURI: /datadog/api/v2/series; cannot unmarshal DataDog application/x-protobuf request with size 13038 bytes: cannot unmarshal next field: unknown wireType=3
dd-monitor-problem-datadog-1   | 2025-02-24 14:05:38 UTC | CORE | ERROR | (comp/forwarder/defaultforwarder/transaction/transaction.go:427 in internalProcess) | Error code "400 Bad Request" received while sending transaction to "http://vmagent:8429/datadog/api/v2/series": "remoteAddr: \"172.26.0.4:60370\"; requestURI: /datadog/api/v2/series; cannot unmarshal DataDog application/x-protobuf request with size 13038 bytes: cannot unmarshal next field: unknown wireType=3\n", dropping it
```

Modifying the `docker-compose.yml` file so that `DD_SERIALIZER_COMPRESSOR_KIND` is `zlib` will make it work again and the backend will receive the sample `datadog.agent.started{}` metric.

This is the dockerfile:

```yml

networks:
  vm-bug:

services:
  datadog:
    image: public.ecr.aws/datadog/agent:7.63.0
    environment:
      # This works (datadog agent <7.62 default behavior))
      #- DD_SERIALIZER_COMPRESSOR_KIND=zlib
      # This doesn't work (datadog agent >=7.62 default behavior)
      - DD_SERIALIZER_COMPRESSOR_KIND=zstd
      - DD_ENV=test
      - DD_LOGS_CONFIG_DD_URL=http://vmagent:8429/datadog
      - DD_DD_URL=http://vmagent:8429/datadog
      - DD_APM_DD_URL=http://vmagent:8429/datadog
      - DD_ENABLE_METADATA_COLLECTION=false
      - DD_ADDITIONAL_ENDPOINTS="{}"
      - DD_APM_ENABLED=false
      - DD_PROCESS_CONFIG_CONTAINER_COLLECTION_ENABLED=false
      - DD_PROCESS_CONFIG_PROCESS_DISCOVERY_ENABLED=false
      - DD_REMOTE_CONFIGURATION_ENABLED=false
      - DD_LOG_LEVEL=WARN
      - DD_API_KEY=placeholder
      - DD_SITE=datadoghq.eu
      - DD_HOSTNAME=datadog
    networks: [vm-bug]

  vmagent:
    image: victoriametrics/vmagent:v1.111.0
    environment:
      - HOSTNAME=test
    command: [
      "-envflag.enable",
      "-loggerLevel=INFO",
      "-remoteWrite.url=http://victoria:8428/api/v1/write",
    ]
    networks: [vm-bug]

  victoria:
    image: victoriametrics/victoria-metrics:v1.111.0
    command: [
      "-envflag.enable",
      "-loggerLevel=INFO",
      "-loggerJSONFields=ts:timestamp,msg:message",
    ]
    ports:
      - "127.0.0.1:8428:8428"
    networks: [vm-bug]

```

### Version

v.111.0

### Logs

```
dd-monitor-problem-datadog-1   | 2025-02-24 14:06:08 UTC | CORE | ERROR | (comp/forwarder/defaultforwarder/transaction/transaction.go:427 in internalProcess) | Error code "400 Bad Request" received while sending transaction to "http://vmagent:8429/datadog/api/v2/series": "remoteAddr: \"172.26.0.4:60370\"; requestURI: /datadog/api/v2/series; cannot unmarshal DataDog application/x-protobuf request with size 13041 bytes: cannot unmarshal next field: unknown wireType=3\n", dropping it
dd-monitor-problem-vmagent-1   | 2025-02-24T14:06:23.657Z	warn	VictoriaMetrics/app/vmagent/main.go:387	remoteAddr: "172.26.0.4:60370"; requestURI: /datadog/api/v2/series; cannot unmarshal DataDog application/x-protobuf request with size 13171 bytes: cannot unmarshal next field: unknown wireType=3
```

### Used command-line flags

See docker file above.
