### ISSUE TITLE
Incorrect handling of nested otel fields in VictoriaLogs

### ISSUE THREAD

**Issue by KJTsanaktsidis** [VictoriaMetrics/VictoriaMetrics#8384]
### Describe the bug

When importing logs to VictoriaLogs' opentelemetry endpoint, and those logs contain attributes which are nested maps, VictoriaLogs seems to only unpack the first level of this.

See this screenshot, for example

<img width="1866" alt="Image" src="https://github.com/user-attachments/assets/e2fb06ae-07eb-4a89-971a-d409f994adc3" />

The "foo" key looks correct, but the "fields2" key winds up containing the JSON representation of the OpenTelemetry attribute protobuf struct (I think that's what it is)

It _is_ able to correctly handle non-nested OpenTelemetry attributes, however.

### To Reproduce

- Start VictoriaLogs: `./victoria-logs-prod`
- Spin up an OpenTelemetry collector with the following config file:

```
# otel-config.yml
receivers:
  filelog:
    include: [ /home/kjtsanaktsidis/logz/logfile.log ]
    operators:
    - type: json_parser
exporters:
  otlphttp/logs:
    endpoint: http://localhost:9428/insert/opentelemetry/
service:
  pipelines:
    logs:
      receivers: [filelog]
      processors: []
      exporters: [otlphttp/logs]
```
-  `./otelcol-contrib --config file:otel-config.yml`
- Write a JSON log entry to that file: `echo '{"foo": "barz4", "fields2": { "what": "is this"}}' >> logfile.log`
- Navigate to the VictoriaLogs Web UI, look at the entry; notice that `fields2` is not unpacked.

### Version

```
kjtsanaktsidis@kjtsanaktsidis logz % ./victoria-logs-prod --version
victoria-logs-20250222-212123-tags-v1.13.0-victorialogs-0-gce7e408c14
```
