### ISSUE TITLE
vmagent semi-silently fails when relabeling config contains unsupported regexp

### ISSUE THREAD

**Issue by solidDoWant** [VictoriaMetrics/VictoriaMetrics#8426]
### Describe the bug

When loading scape configs with unsupported regexp, vmagent will log an error about the unsupported expression, but not add the target. This is hard to detect, because alerts for down/unavailable scraping targets will not fire.

### To Reproduce

I'm deploying VM via the k8s-stack chart. Using the chart, I am configuring the kubelet scraper values to drop certain metrics, which all begin with a prefix. I set the kublet nodescrape config to this:

```yaml
kubelet:
  vmScrapes:
    kubelet:
      enabled: true
  vmScrape:
    spec:
      relabelConfigs:
        # This is the same as the chart default, but it explicitly excludes NFD node labels,
        # and talos extension labels. These don't really provide any value, and they cause
        # cardinality to explode.
        - action: labelmap
          regex: __meta_kubernetes_node_label_(?!feature_node|extensions_talos_dev)(.+)
        - sourceLabels: [__metrics_path__]
          targetLabel: metrics_path
        - targetLabel: job
          replacement: kubelet
```

I didn't realize at the time that VM does not support negative lookaheads (`(?!feature_node)`). I then redeployed the chart, waited a bit, and manually checked a few things. The vmagent scrape target page is now missing the nodescrape metrics entirely - they're not even showing up as "failed" or "down". As a result, no alerts were triggered.

Looking at the vmagent logs, there are periodic entries matching this:

```console
2025-03-03T09:36:21.712Z	error	VictoriaMetrics/lib/promscrape/config.go:553	skipping `scrape_config` for job_name=nodeScrape/monitoring/victoria-metrics-k8s-stack-kubelet/1 because of error: cannot parse `relabel_configs` for `job_name` "nodeScrape/monitoring/victoria-metrics-k8s-stack-kubelet/1": error when parsing `relabel_config` #3: cannot parse `regex` "^(?:__meta_kubernetes_node_label_(?!feature_node|extensions_talos_dev)(.+))$": error parsing regexp: invalid or unsupported Perl syntax: `(?!`
```

This shows that while the scraper config was correctly loaded into the vmagent instance, it somewhat silently failed.

### Version

`docker.io/victoriametrics/vmagent@sha256:378930cd5415c72e0aca75c212aaf92822acc215041f168454ef8100201b3958`

### Logs

```console
2025-03-03T09:36:21.712Z	error	VictoriaMetrics/lib/promscrape/config.go:553	skipping `scrape_config` for job_name=nodeScrape/monitoring/victoria-metrics-k8s-stack-kubelet/1 because of error: cannot parse `relabel_configs` for `job_name` "nodeScrape/monitoring/victoria-metrics-k8s-stack-kubelet/1": error when parsing `relabel_config` #3: cannot parse `regex` "^(?:__meta_kubernetes_node_label_(?!feature_node|extensions_talos_dev)(.+))$": error parsing regexp: invalid or unsupported Perl syntax: `(?!`
```

### Additional information

Here's the vmnodescrape manifest that the Helm chart generated which includes the invalid regexp:
```yaml
apiVersion: operator.victoriametrics.com/v1beta1
kind: VMNodeScrape
metadata:
  annotations:
    meta.helm.sh/release-name: victoria-metrics-k8s-stack
    meta.helm.sh/release-namespace: monitoring
  generation: 2
  labels:
    app.kubernetes.io/instance: victoria-metrics-k8s-stack
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: victoria-metrics-k8s-stack
    app.kubernetes.io/version: v1.112.0
    helm.sh/chart: victoria-metrics-k8s-stack-0.38.0
    helm.toolkit.fluxcd.io/name: victoria-metrics-k8s-stack
    helm.toolkit.fluxcd.io/namespace: monitoring
  name: victoria-metrics-k8s-stack-kubelet
  namespace: monitoring
status:
  conditions:
    - lastTransitionTime: '2025-03-02T06:27:38Z'
      lastUpdateTime: '2025-03-03T09:33:44Z'
      observedGeneration: 2
      reason: ConfigParsedAndApplied
      status: 'True'
      type: >-
        victoria-metrics-k8s-stack.monitoring.vmagent.victoriametrics.com/Applied
  observedGeneration: 2
  updateStatus: operational
spec:
  bearerTokenFile: /var/run/secrets/kubernetes.io/serviceaccount/token
  honorLabels: true
  honorTimestamps: false
  interval: 30s
  metricRelabelConfigs:
    - action: labeldrop
      regex: (uid)
    - action: labeldrop
      regex: (id|name)
    - action: drop
      regex: >-
        (rest_client_request_duration_seconds_bucket|rest_client_request_duration_seconds_sum|rest_client_request_duration_seconds_count)
      source_labels:
        - __name__
  relabelConfigs:
    - action: labelmap
      regex: __meta_kubernetes_node_label_(?!feature_node|extensions_talos_dev)(.+)
    - sourceLabels:
        - __metrics_path__
      targetLabel: metrics_path
    - replacement: kubelet
      targetLabel: job
  scheme: https
  scrapeTimeout: 5s
  selector: {}
  tlsConfig:
    caFile: /var/run/secrets/kubernetes.io/serviceaccount/ca.crt
    insecureSkipVerify: true
```
