### ISSUE TITLE
Memory Allocation Issue in vmselect Despite High Provisioning

### ISSUE THREAD

**Issue by girish-ms** [VictoriaMetrics/VictoriaMetrics#8432]
### Describe the bug

Even after provisioning vmselect with sufficient memory (60Gi limit, 40Gi request, and memory.allowedPercent: 90), queries still fail due to "not enough memory" errors.

**Error Message:**
<img width="1488" alt="Image" src="https://github.com/user-attachments/assets/b676a71c-e4f0-444a-94bc-903b50004319" />

`
"not enough memory for processing rate(container_network_transmit_bytes_total{namespace!=\"\"}[1h]), which returns 2040223365 data points across 708165 time series with 2881 points in each time series; total available memory for concurrent requests: 28991029248 bytes; requested memory: 33351738840 bytes; possible solutions are: reducing the number of matching time series; increasing `step` query arg (step=30s); switching to node with more RAM; increasing -memory.allowedPercent"
`

**Current vmselect Configuration:**
```
vmselect:
  extraArgs:
    enableTCP6: false
    dedup.minScrapeInterval: 1ms
    replicationFactor: 2
    search.maxQueryDuration: 300s
    memory.allowedPercent: 90
  podAnnotations:
    prometheus.io/scrape: "true"
    prometheus.io/port: "8481"
  replicaCount: 3
  serviceMonitor:
    enabled: true
  resources:
    limits:
      memory: 60Gi
    requests:
      cpu: 10
      memory: 40Gi
```

### To Reproduce

Larger queries

### Version

Latest helm chart

**Comment by joy963** [comment]
try to increase maximum number of memory map.
```shell
sudo /usr/sbin/sysctl -w vm.max_map_count=262144
```

**Comment by girish-ms** [comment]
> sudo /usr/sbin/sysctl -w vm.max_map_count=262144

Where can I make this change? Could you please guide me?

**Comment by girish-ms** [comment]
```
/etc # echo "vm.max_map_count=262144" |tee -a /etc/sysctl.conf
vm.max_map_count=262144
/etc # sysctl -p
sysctl: error setting key 'vm.max_map_count': Read-only file system
/etc # cat sysctl.conf 
# content of this file will override /etc/sysctl.d/*
vm.max_map_count=262144
```

**Comment by func25** [comment]
`not enough memory for processing rate(container_network_transmit_bytes_total{namespace!=\"\"}[1h]), which returns 2040223365 data points across 708165 time series with 2881 points in each time series; total available memory for concurrent requests: 28991029248 bytes; requested memory: 33351738840 bytes`

This shows that:
- Your query is trying to process over 2 bil data points
- It's working with 708,165 time series, each with 2,881 points
- The query needs ~33.3GB of memory, but only ~29GB is available

Let's calculate:
- Total memory limit for vmselect pod: 60Gi ≈ 64.42GB
- Allowed memory (90%): 64.42GB 0.9 ≈ 57.98GB
- Memory for rollup queries (50% of allowed): 57.98GB / 2 ≈ 28.99GB

Your query is generating a very high cardinality result (https://docs.victoriametrics.com/faq/#what-is-high-cardinality). I'd recommend simplifying it to see if you actually need all those joins. Try reducing the rate window from 1 hour to a smaller value (5 minutes?), narrowing down the matching time series, and, as suggested in the error, increasing the `step` of your query.

**Comment by girish-ms** [comment]
> Memory for rollup queries (50% of allowed): 57.98GB / 2 ≈ 28.99GB

Could you help me understand this?  

Is there a way to configure it to fully utilize the allocated memory?

**Comment by girish-ms** [comment]
For more context, I'm evaluating alternative solutions to replace our current Thanos setup. We're running queries on larger time series datasets to assess how well it meets our requirements.

**Comment by func25** [comment]
50% is fixed and can't be changed, some mechanisms share the allowed memory.

If you need a dirty workaround (not recommended, of course), try using `memory.allowedBytes: 70Gi` instead of `allowedPercent`. The rollup memory limiter will take half of that (35Gi), which should be enough for your query that requires around 33.3Gi.

**Comment by girish-ms** [comment]
I've increased the memory to the maximum, but I'm still encountering issues. Is there anything else I can try?  

Updated resource values:  
```
  resources:
    limits:
      memory: 140Gi
    requests:
      cpu: 10
      memory: 130Gi
```

Error message:  
```
VictoriaMetrics: Unknown error during query transaction. Please check JS console logs.
```
