### ISSUE TITLE
lib/httputils: TLS parameters are ignored for URLs with scheme other than `https`

### ISSUE THREAD

**Issue by zekker6** [VictoriaMetrics/VictoriaMetrics#8494]
### Describe the bug

Using TLS related options for URLs with scheme other than `https` is not possible.

### To Reproduce

For example, running a vmalert with `static_configs`:
```
static_configs:
  - targets:
      - localhost:9093
    tls_config:
      insecure_skip_verify: true
```
And having Alertmanager with TLS enabled would lead to requests failing due to insecure certificates configuration despite using `insecure_skip_verify: true` in config.

### Version

v1.113.0
