### ISSUE TITLE
VMAlert: {{$labels.fieldname}} doesn't work in vlogs config

### ISSUE THREAD

**Issue by bubaibingfeng** [VictoriaMetrics/VictoriaMetrics#8496]
### Is your question request related to a specific component?

vmalert,victorialogs

### Describe the question in detail

Have vlogs alert rule like:
```
    groups:
    - name: LogTypeAlertGroup
      type: vlogs 
      interval: 5m
      rules:
        - alert: ToomanyErrorAuthn
          expr: 'LogType:authn | stats by (LogMeta.clientID,LogMeta.clientIP) count() as alertCount | filter alertCount:>0'
          labels:
            severity: critical
          annotations:
            summary: "Detected {{$value}} log(s) with error authn message"
            description: "In the last 5 minutes, {{ $labels.LogMeta_clientID }} from {{ $labels.LogMeta_clientIP }} create {{$value}} error authn "
```

received JSON data:
`{"receiver":"victorialogs-vmstack-logtype-alert-receiver_cmy","status":"firing","alerts":[{"status":"firing","labels":{"LogMeta_clientID":"VM-8-4-ubuntu_bench_pub_176626976_500000003","LogMeta_clientIP":"47.99.144.213","alertgroup":"LogTypeAlertGroup","alertname":"ToomanyErrorAuthn","severity":"critical","stats_result":"alertCount"},"annotations":{"description":"In the last 5 minutes,  from  create 1 error authn ","summary":"Detected 1 log(s) with error authn message"},"startsAt":"2025-03-12T16:30:00Z","endsAt":"0001-01-01T00:00:00Z","generatorURL":"http://vmalert-deployment-75f56bbbc9-z7f29:8880/vmalert/alert?group_id=15345674432308522598\u0026alert_id=6566768828816494521","fingerprint":"6430edad57dfc4d5"},{"status":"firing","labels":{"LogMeta_clientID":"mqttx_834567a9","LogMeta_clientIP":"121.41.174.170","alertgroup":"LogTypeAlertGroup","alertname":"ToomanyErrorAuthn","severity":"critical","stats_result":"alertCount"},"annotations":{"description":"In the last 5 minutes,  from  create 1 error authn ","summary":"Detected 1 log(s) with error authn message"},"startsAt":"2025-03-12T16:30:00Z","endsAt":"0001-01-01T00:00:00Z","generatorURL":"http://vmalert-deployment-75f56bbbc9-z7f29:8880/vmalert/alert?group_id=15345674432308522598\u0026alert_id=4239140249124488946","fingerprint":"9d077f56469b82ee"}],"groupLabels":{"alertname":"ToomanyErrorAuthn"},"commonLabels":{"alertgroup":"LogTypeAlertGroup","alertname":"ToomanyErrorAuthn","severity":"critical","stats_result":"alertCount"},"commonAnnotations":{"description":"In the last 5 minutes,  from  create 1 error authn ","summary":"Detected 1 log(s) with error authn message"},"externalURL":"https://vmalertmanager.cn.ompassets.mqttce.com","version":"4","groupKey":"{}/{}:{alertname=\"ToomanyErrorAuthn\"}","truncatedAlerts":0}`

i have the experience of using VictoriaMetrics and read the docs about victorialogs,but i dont know why {{ $labels.LogMeta_clientID }} didn't work in description . i change it to  {{ $labels.LogMeta.clientID }} ,but it still didn't work

my logs data like:

<img width="733" alt="Image" src="https://github.com/user-attachments/assets/7c3de39a-b58e-4fef-903b-6007ac81764a" />

### Troubleshooting docs

- [x] General - https://docs.victoriametrics.com/troubleshooting/
- [x] vmagent - https://docs.victoriametrics.com/vmagent/#troubleshooting
- [x] vmalert - https://docs.victoriametrics.com/vmalert/#troubleshooting
