### ISSUE TITLE
VMAuth: extra_filter and extra_label parameters do not work as expected

### ISSUE THREAD

**Issue by nulldoot2k** [VictoriaMetrics/VictoriaMetrics#8552]
Currently I am using vmauth to manage the user access cluster.
But due to the increasing number of tenant metrics, I find the handling here is not done well.

- Vmauth version: v1.113.0

Look at the following draw example

![Image](https://github.com/user-attachments/assets/c1b47475-9544-466e-88a0-e8c192f232f2)

To ensure that access to data and metrics does not overlap. I need to separate metrics templates by labels `regions`

For example: Endpoint [CustomerA,CustomerB,CustomerC,...]

Endpoint CustomerA: (Only users with accounts can view data belonging to the resources of regions Singapore)
- `user/pass`
- `label: [regions="sing"]`

Endpoint CustomerB: (Only users with accounts can view data belonging to the resources of regions Vietnam and Thailan)
- `user/pass`
- `label: [regions=~"vietnam|thailan"]`

Expected results: When a user accesses the grafana datasource with the CustomerB endpoint, metrics + labels belonging to CustomerB will be displayed.

Apply config vmauth recommand: https://github.com/VictoriaMetrics/VictoriaMetrics/commit/f41b36bb9a162e5cc184da5e0236e3c441776c85

```
  - username: "customerB"
    password: "passwordofcustomerB"
    max_concurrent_requests: 10
    url_map:
    - src_paths:
      - "/api/v1/query"
      - "/api/v1/query_range"
      - "/api/v1/query_exemplars"
      - "/api/v1/label/[^/]+/values"
      - "/api/v1/labels"
      - "/api/v1/rules"
      - "/api/v1/series"
      - "/api/v1/metadata"
      - "/(graph|vmui)/.*"
      url_prefix:
        - http://vmselect1:8481/select/100/prometheus?extra_filter[]={region=~"vietnam|thailan"}
        - http://vmselect2:8481/select/100/prometheus?extra_filter[]={region=~"vietnam|thailan"}
      load_balancing_policy: first_available
      retry_status_codes: [500, 502, 503]
```

Now result with datasource CustomerB show metrics all of custemer :))) incorrect

I tried `extra_label` as well, but it didn't work because the number of links with defined labels was too large.

![Image](https://github.com/user-attachments/assets/af83e36c-c616-46b6-a311-4553ed2a5a7a)

## Finally
`extra_label`: works but cannot handle large numbers.
`extra_filter`: works but the results are not accurate, not as expected.

Intended purpose: Use extra_label and extra_filter to determine the most accurate endpoint.

**Comment by nulldoot2k** [comment]
CC @jiekun  you can help me :)

**Comment by f41gh7** [comment]
Hello, `extra_filter` looks like a typo to me. According to the documentation it should be either `extra_filters[]` or `extra_filters`. 

 https://docs.victoriametrics.com/#prometheus-querying-api-enhancements

 Most probably, it will hit some limits and will require a additional resources for `label/{}/values` and `/labels` requests.

**Comment by nulldoot2k** [comment]
If I use extra_label with low metrics, the result will be displayed, if the metrics are large, it will not be able to meet.

![Image](https://github.com/user-attachments/assets/10695651-cb9a-4e30-8667-b58a39aa6828)

For example, all metrics of cluster A sent to victoriametrics are defined by job="clusterA".
If the number is large, extra_label will not meet
If the number is small, extra_label will meet.
Not to mention the time bar has an adjustment level of 1h, 6h, 1d, 2d...

**Comment by nulldoot2k** [comment]
@f41gh7 This is when I use extra_label with values ​​containing larger metrics.

![Image](https://github.com/user-attachments/assets/fb547c4c-d4b6-40d2-8673-879e0e14cb05)

It doesn't show "Metrics Browser".
But when I paste the query expression in, it still returns results, which means extra_label is working, but not showing to the user as expected.

**Comment by nulldoot2k** [comment]
For now, when i apply param: extra_labels and extra_filters[]
I see it can not handle numberic label
@f41gh7 You can help me :)

**Comment by f41gh7** [comment]
> For now, when i apply param: extra_labels and extra_filters[] I see it can not handle numberic label [@f41gh7](https://github.com/f41gh7) You can help me :)

Sorry for delay, could you please provide exact error? I assume, that it could be related to one of max unique series limits. If so, you should adjust needed limit and optionally allocate extra resource for storage.

**Comment by makasim** [comment]
@nulldoot2k just a gentle ping on this.

**Comment by makasim** [comment]
Closing due to no additional information provided. Feel free to reopen.

**Comment by nulldoot2k** [comment]
Srr, @makasim @f41gh7 , hmmm
Basically I see vmauth has the following improvements
Features:
- load_balancing_policy has added least_loaded to support evenly load sharing instead of focusing on 1 url point via first_available
- hot-reload is quite fast and does not affect much when vmauth service is running
- There are more headers in the backend when client requests

But still not good in the point of processing output for client

**Comment by nulldoot2k** [comment]
vmauth issue when using extra_filters to filter client output but can't load large number of samples

I'm using vmauth and proxy for victoirametrics cluster
vmauth configuration is as follows
```
users:
  - username: "kubernetes"
    password: "*******"
    max_concurrent_requests: 20
    url_map:
    - src_paths:
      - "/api/v1/query"
      - "/api/v1/query_range"
      - "/api/v1/query_exemplars"
      - "/api/v1/label/[^/]+/values"
      - "/api/v1/labels"
      - "/api/v1/rules"
      - "/api/v1/prettify-query?.*"
      - "/api/v1/series"
      - "/api/v1/metadata"
      - "/vmui/.*"
      url_prefix:
        - http://10.X.XX.147:8481/select/XNXX/prometheus?extra_filters[]={monitor=~"(A-k8s|B-k8s|C-k8s|D-k8s|E-k8s)",cluster_name=~"(A|B|C|D|E)"}
        - http://10.X.XX.179:8481/select/XNXX/prometheus?extra_filters[]={monitor=~"(A-k8s|B-k8s|C-k8s|D-k8s|E-k8s)",cluster_name=~"(A|B|C|D|E)"}
        - http://10.X.XX.230:8481/select/XNXX/prometheus?extra_filters[]={monitor=~"(A-k8s|B-k8s|C-k8s|D-k8s|E-k8s)",cluster_name=~"(A|B|C|D|E)"}
        - http://10.X.XX.150:8481/select/XNXX/prometheus?extra_filters[]={monitor=~"(A-k8s|B-k8s|C-k8s|D-k8s|E-k8s)",cluster_name=~"(A|B|C|D|E)"}
        - http://10.X.XX.138:8481/select/XNXX/prometheus?extra_filters[]={monitor=~"(A-k8s|B-k8s|C-k8s|D-k8s|E-k8s)",cluster_name=~"(A|B|C|D|E)"}
      retry_status_codes: [429, 502, 503, 504]
      load_balancing_policy: least_loaded
```

When the client uses grafana query via vmauth, the metrics are not displayed, but if you specify the sample sentence to query, it is still possible.
As shown in the image, this vmauth datasource is not showing metrics.
How should vmauth be optimized to show?

When Grafana opens the metrics list (for example, when selecting in the query builder box), it will call the API: `/api/v1/label/__name__/values` ​​or `/api/v1/labels` to get the entire list of label names / metric names.
vmauth will process next through extra_filters, with regex of many values `​​(in the form =~"(A|B|C|D|E)")`, VictoriaMetrics will have to merge series from many time series indexes, leading to the query `/api/v1/labels` or `/label/__name__/values` ​​becoming extremely heavy → timeout or “No metrics found”.

Each value in the labels monitor is equivalent to 80k sample metrics

The vmauth processing flow will be as follows:
- Scan all index series corresponding to that filter `(monitor=~"(A-k8s|B-k8s|C-k8s|...)", cluster_name=~"(A|B|C|...)")`;
- Get a list of distinct metric names (maybe millions);
- Merge and return.
→ If each cluster (A, B, C, D, E) has several million distinct time series → it is almost “scan the whole cluster” ⇒ timeout / empty response.

I know this should evaluate them from input, should allocate metrics, labels how reasonable to minimize output. But I was not clear in that.
I try to use the feature that vmauth has, that is: extra_labels, extra_filters
But is there any best way to handle filtering with large number for this?
@makasim @f41gh7
