### ISSUE TITLE
VM alert is not giving exact collection_timestamp

### ISSUE THREAD

**Issue by rmsh06202** [VictoriaMetrics/VictoriaMetrics#8577]
### Describe the bug

YAML file :

```yaml
groups:
 - name: memory_related_alerts
   interval: 1m # Run the rule every 1 minute
   eval_delay: 4m
   rules:
     - alert: system_memory_in_use_alert_abcfin_instance
       expr: avg(system_memory_in_use{instance='abcxxxfinaxxxncial'}) by (instance) > 1000
       debug: true
       labels:
         severity: critical
         instance: "{{ $labels.instance }}"
       annotations:
          summary: Too high connection number ({{ $value }}) for {{ $labels.instance }} at
            {{ with printf "timestamp(system_memory_in_use{instance=%q}[2m])" .Labels.instance | query }}
              {{ . | first | value | humanizeTimestamp }}
            {{ end }}
```

Note : I tried with  `printf "timestamp(system_memory_in_use{instance=%q})` and  `printf "timestamp(system_memory_in_use{instance=%q}[1m])` in all the cases it was giving incorrect Collection timestamp . Even sometimestamp it was repeating the collection timestamp with different value.

Alerts Started at '2025-03-21T03:00:00-07:00' (PDT) and the value is 1036 which is correct but the actual timestamp is incorrect .

In Summary it give 2025-03-21 09:58:12 +0000 UTC but actual timestamp is 2025-03-21 10:01:00 

First Output when alert state is firing

```
alert :  {'startsAt': '2025-03-21T03:00:00-07:00', 'generatorURL': 'http://hclient999001:8880/vmalert/alert?group_id=9290946488034777796&alert_id=9527196822280776008', 'endsAt': '2025-03-21T03:08:30.24162602-07:00', 'labels': {'alertgroup': 'memory_related_alerts', 'alertname': 'system_memory_in_use_alert_abcfin_instance', 'instance': 'abcfinancial', 'severity': 'critical'}, 'annotations': {'summary': 'Too high connection number (1036) for abcfinancial at  2025-03-21 09:58:12 +0000 UTC '}}
Received alert Name: system_memory_in_use_alert_abcfin_instance
Starts at: 2025-03-21T03:00:00-07:00
Ends at: 2025-03-21T03:08:30.24162602-07:00
Labels: {'alertgroup': 'memory_related_alerts', 'alertname': 'system_memory_in_use_alert_abcfin_instance', 'instance': 'abcfinancial', 'severity': 'critical'}
Annotations: {'summary': 'Too high connection number (1036) for abcfinancial at  2025-03-21 09:58:12 +0000 UTC '}
```

Second output:( I am not even receiving the actual timestamp it is empty)

```
alert :  {'startsAt': '2025-03-21T03:00:00-07:00', 'generatorURL': 'http://hclient999001:8880/vmalert/alert?group_id=9290946488034777796&alert_id=9527196822280776008', 'endsAt': '2025-03-21T03:09:30.256414351-07:00', 'labels': {'alertgroup': 'memory_related_alerts', 'alertname': 'system_memory_in_use_alert_abcfin_instance', 'instance': 'abcfinancial', 'severity': 'critical'}, 'annotations': {'summary': 'Too high connection number (1036) for abcfinancial at <empyt> '}}
```

### To Reproduce

```yaml
groups:
 - name: memory_related_alerts
   interval: 1m # Run the rule every 1 minute
   eval_delay: 4m
   rules:
     - alert: system_memory_in_use_alert_abcfin_instance
       expr: avg(system_memory_in_use{instance='abcxxxfinaxxxncial'}) by (instance) > 1000
       debug: true
       labels:
         severity: critical
         instance: "{{ $labels.instance }}"
       annotations:
          summary: Too high connection number ({{ $value }}) for {{ $labels.instance }} at
            {{ with printf "timestamp(system_memory_in_use{instance=%q}[2m])" .Labels.instance | query }}
              {{ . | first | value | humanizeTimestamp }}
            {{ end }}
```

Note : I tried with  `printf "timestamp(system_memory_in_use{instance=%q})` and  `printf "timestamp(system_memory_in_use{instance=%q}[1m])` in all the cases it was giving incorrect Collection timestamp . Even sometimestamp it was repeating the collection timestamp with different value.

### Version

vmalert-20250117-135518-tags-v1.109.1-0-gf73b40619a

### Screenshots

<img width="1001" alt="Image" src="https://github.com/user-attachments/assets/b378d34e-4aa2-4f6c-9e77-5078f525211a" />
