### ISSUE TITLE
how to improve performance of vm-agent remoteWrite.relabelConfig?

### ISSUE THREAD

**Issue by mrbaowei** [VictoriaMetrics/VictoriaMetrics#8583]
### Is your question request related to a specific component?

vm-agent

### Describe the question in detail

We attempted to relabel a large amount of cleaning data. We matched fields such as venue based on the SN in the data. When the remoteWrite.relabelConfig exceeded 100,000 lines, we used 64 cores for real-time cleaning, but the CPU still reached 100%. Below is a part of our rules. Is there a way to improve performance? 
```yaml
- action: replace
  if: '{client_sn = "SSPC052341208658"}'
  replacement: shanghai
  target_label: school
- action: replace
  if: '{client_sn = "SEPC052341208651"}'
  replacement: guangzhou
  target_label: school
- action: replace
  if: '{client_sn = "SPPC052341208652"}'
  replacement: guangzhou
  target_label: school
```

### Troubleshooting docs

- [x] General - https://docs.victoriametrics.com/troubleshooting/
- [x] vmagent - https://docs.victoriametrics.com/vmagent/#troubleshooting
- [x] vmalert - https://docs.victoriametrics.com/vmalert/#troubleshooting
