### ISSUE TITLE
vmui/metric-relabel-debug: incorrect parsing of metric name

### ISSUE THREAD

**Issue by zekker6** [VictoriaMetrics/VictoriaMetrics#8584]
### Describe the bug

Here are 2 sets of labels which produce different results:
- `__name__="prefix_custom_metric",service="service1"`
- `{__name__="prefix_custom_metric",service="service1"}`

### To Reproduce

Using the following set of rules:
```
- source_labels: 
  - __name__
  - service
  target_label: team
  replacement: unknown
  regex: ^prefix_.*;.*$
- source_labels: 
  - __name__
  - service
  target_label: team
  regex: ^prefix_.*;(service1|service2|service3)$
  replacement: team-test
```

Use labels as:
- `__name__="prefix_custom_metric",service="service1"` - [link](https://play.victoriametrics.com/select/0/prometheus/graph/#/relabeling?config=-+source_labels%3A+%0A++-+__name__%0A++-+service%0A++target_label%3A+team%0A++replacement%3A+unknown%0A++regex%3A+%5Eprefix_.*%3B.*%24%0A-+source_labels%3A+%0A++-+__name__%0A++-+service%0A++target_label%3A+team%0A++regex%3A+%5Eprefix_.*%3B%28service1%7Cservice2%7Cservice3%29%24%0A++replacement%3A+team-test&labels=__name__%3D%22prefix_custom_metric%22%2Cservice%3D%22service1%22)
- `{__name__="prefix_custom_metric",service="service1"}` - [link](https://play.victoriametrics.com/select/0/prometheus/graph/#/relabeling?config=-+source_labels%3A+%0A++-+__name__%0A++-+service%0A++target_label%3A+team%0A++replacement%3A+unknown%0A++regex%3A+%5Eprefix_.*%3B.*%24%0A-+source_labels%3A+%0A++-+__name__%0A++-+service%0A++target_label%3A+team%0A++regex%3A+%5Eprefix_.*%3B%28service1%7Cservice2%7Cservice3%29%24%0A++replacement%3A+team-test&labels=%7B__name__%3D%22prefix_custom_metric%22%2Cservice%3D%22service1%22%7D)

### Version

v1.114.0
