### ISSUE TITLE
EOF error on OTEL Post request to VictoriaMetrics.

### ISSUE THREAD

**Issue by somsomers** [VictoriaMetrics/VictoriaMetrics#8586]
### Is your question request related to a specific component?

VictoriaMetrics

### Describe the question in detail

I have a VM docker setup. Slightly adjusted docker stack from VM github repo.
When trying to send metrics through OTEL exporter I sometimes get an error
```
2025-03-25T10:18:15.561Z	info	internal/retry_sender.go:126	Exporting failed. Will retry the request after interval.	{"otelcol.component.id": "otlphttp/victoriametrics", "otelcol.component.kind": "Exporter", "otelcol.signal": "metrics", "error": "failed to make an HTTP request: Post \"http://domain.link:8427/opentelemetry/v1/metrics\": EOF", "interval": "4.257502655s"}
```

On the VM side there are no errors in logs. Now it all goes through vmauth,  but I did try to send it directly to VM with a same result.
It works approximately 90% of the time. 

Ingestion rate on VM server is about 300. 
CPU load i about 5% and disk load - almost idle.

VM server hardware: 2 CPU, 4GB, 120 SSD

Tried sending to docker GTLM stack and Grafana CLoud - all good, no errors.

Any thoughts on how to troubleshoot it?

OTEL exporter config:
```
receivers:
  filestats:
    include: /otelcontrib*
    initial_delay: 1s
    metrics:
      file.count:
        enabled: true
      file.mtime:
        enabled: false
      file.size:
        enabled: false

  otlp:
    protocols:
      http:
        endpoint: 0.0.0.0:4318

processors:
  batch/agent:
    send_batch_size: 2000
    timeout: 10s

exporters:
  debug:
    verbosity: detailed

  otlphttp/victoriametrics:
    compression: gzip
    encoding: proto
    endpoint: http://domain.link:8427/opentelemetry
    auth:
      authenticator: basicauth/client
    tls:
      insecure: true

extensions:
  basicauth/client:
    client_auth:
      username: oteluserin
      password: Nfrjq_Djn_Gfhjkm_Gjkexbkcz

service:
  extensions: [basicauth/client]
  pipelines:
    metrics/host:
      receivers: [filestats]
      processors: [batch/agent]
      exporters: [otlphttp/victoriametrics]
```

VM stack:
```
services:
  # Grafana instance configured with VictoriaLogs as datasource
  grafana:
    container_name: grafana
    image: grafana/grafana:11.5.0
    depends_on:
      - "victoriametrics"
      - "victorialogs"
    # ports:
      # - 3000:3000
    volumes:
      - grafanadata:/var/lib/grafana
      - ./grafana/provisioning/datasources:/etc/grafana/provisioning/datasources
      - ./grafana/provisioning/dashboards:/etc/grafana/provisioning/dashboards
      - ./grafana/dashboards/victoriametrics.json:/var/lib/grafana/dashboards/vm.json
      - ./grafana/dashboards/victorialogs.json:/var/lib/grafana/dashboards/vl.json
    environment:
      - "GF_INSTALL_PLUGINS=victoriametrics-logs-datasource"
    restart: always

  #  VictoriaLogs instance, a single process responsible for
  #  storing logs and serving read queries.
  victorialogs:
    container_name: victorialogs
    image: victoriametrics/victoria-logs:v1.15.0-victorialogs
    command:
      - "--storageDataPath=/vlogs"
      - "--httpListenAddr=:9428"
    volumes:
      - vldata:/vlogs
    # ports:
      # - "9428:9428"

  # VictoriaMetrics instance, a single process responsible for
  # scraping, storing metrics and serve read requests.
  victoriametrics:
    container_name: victoriametrics
    image: victoriametrics/victoria-metrics:v1.112.0
    # ports:
      # - 8428:8428
    volumes:
      - vmdata:/storage
      - ./victoria_metrics/prometheus-scrapers.yml:/etc/prometheus/prometheus.yml
    command:
      - "--storageDataPath=/storage"
      - "--httpListenAddr=:8428"
      - "--promscrape.config=/etc/prometheus/prometheus.yml"
    restart: always

  vmauth:
    container_name: vmauth
    image: victoriametrics/vmauth:v1.112.0
    depends_on:
      - "victoriametrics"
      - "victorialogs"
    volumes:
      - ./vmauth/auth.yml:/etc/auth.yml
    command:
      - "--auth.config=/etc/auth.yml"
    ports:
      - 8427:8427
    restart: always

  # alertmanager receives alerting notifications from vmalert
  # and distributes them according to --config.file.
  alertmanager:
    container_name: alertmanager
    image: prom/alertmanager:v0.28.0
    volumes:
      - ./alertmanager/alertmanager.yml:/config/alertmanager.yml
    command:
      - "--config.file=/config/alertmanager.yml"
    # ports:
      # - 9093:9093
    restart: always

  otel-collector:
    image: otel/opentelemetry-collector-contrib:latest
    volumes:
      - ./otel/otel-config.yaml:/etc/otel-config.yaml:ro
      - /proc:/hostfs/proc
    command: ["--config=/etc/otel-config.yaml"]
    environment:
      HOSTNAME: test_${HOSTNAME}

volumes:
  vmdata: {}
  vldata: {}
  grafanadata: {}
```

### Troubleshooting docs

- [ ] General - https://docs.victoriametrics.com/troubleshooting/
- [ ] vmagent - https://docs.victoriametrics.com/vmagent/#troubleshooting
- [ ] vmalert - https://docs.victoriametrics.com/vmalert/#troubleshooting
