### ISSUE TITLE
Extra characters '/' when using scrape_config_files configuration

### ISSUE THREAD

**Issue by kubeop** [VictoriaMetrics/VictoriaMetrics#8610]
### Is your question request related to a specific component?

vmagent

### Describe the question in detail

vmagent config:
`
promscrape.config=http://nginx.default.svc.cluster.local:8080/scrape_config/$(CLUSTER).yml
`

$(CLUSTER).yml:
```
global:
  scrape_interval: 30s
  scrape_timeout: 30s
  external_labels:
    cluster: %{CLUSTER}

scrape_config_files:
- configs/kube-apiserver.yml
- configs/kube-state-metrics.yml
```

error log: There is an extra '/' at the beginning of the URL
{"ts":"2025-03-28T09:54:00.071Z","level":"error","caller":"VictoriaMetrics/lib/promscrape/config.go:483","msg":"skipping \"/http:/nginx.default.svc.cluster.local:8080/scrape_config/configs/kube-state-metrics.yml\" at `scrape_config_files` because of error: cannot read \"/http:/nginx.default.svc.cluster.local:8080/scrape_config/configs/kube-state-metrics.yml\": open /http:/nginx.default.svc.cluster.local:8080/scrape_config/configs/kube-state-metrics.yml: no such file or directory"}

$(CLUSTER).yml:
```
global:
  scrape_interval: 30s
  scrape_timeout: 30s
  external_labels:
    cluster: %{CLUSTER}

scrape_config_files:
- configs/kube-apiserver.yml
- http:/nginx.default.svc.cluster.local:8080/scrape_config/configs/kube-state-metrics.yml
```

error log:
{"ts":"2025-03-28T10:45:12.642Z","level":"error","caller":"VictoriaMetrics/lib/promscrape/config.go:483","msg":"skipping \"/http:/nginx.default.svc.cluster.local:8080/scrape_config/http:/nginx.default.svc.cluster.local:8080/scrape_config/configs/kube-state-metrics.yml\" at `scrape_config_files` because of error: cannot read \"/http:/nginx.default.svc.cluster.local:8080/scrape_config/http:/nginx.default.svc.cluster.local:8080/scrape_config/configs/kube-state-metrics.yml\": open /http:/nginx.default.svc.cluster.local:8080/scrape_config/http:/nginx.default.svc.cluster.local:8080/scrape_config/configs/kube-state-metrics.yml: no such file or directory"}

### Troubleshooting docs

- [ ] General - https://docs.victoriametrics.com/troubleshooting/
- [x] vmagent - https://docs.victoriametrics.com/vmagent/#troubleshooting
- [ ] vmalert - https://docs.victoriametrics.com/vmalert/#troubleshooting
