### ISSUE TITLE
How custom set image/repository/registry for prometheus-node-exporter?

### ISSUE THREAD

**Issue by patsevanton** [VictoriaMetrics/VictoriaMetrics#8612]
### Is your question request related to a specific component?

victoria-metrics-k8s-stack

### Describe the question in detail

Hello! How custom set image/repository/registry for prometheus-node-exporter?
My current code:
```
---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: victoriametrics
  namespace: victoria-metrics
spec:
  url: https://victoriametrics.github.io/helm-charts/
  interval: 24h
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: victoria-metrics-k8s-stack
  namespace: victoria-metrics
spec:
  interval: 15m
  chart:
    spec:
      chart: victoria-metrics-k8s-stack
      version: 0.30.3
      sourceRef:
        kind: HelmRepository
        name: victoriametrics
        namespace: victoria-metrics
  install:
    crds: Create
  upgrade:
    crds: CreateReplace
  values:
    prometheus-node-exporter:
      enabled: true
      vmScrape:
        enabled: true
        spec:
          jobLabel: jobLabel
          selector:
            matchLabels:
              app.kubernetes.io/name: prometheus-node-exporter
          endpoints:
            - port: metrics
              metricRelabelConfigs:
                - action: drop
                  source_labels: [mountpoint]
                  regex: "/var/lib/kubelet/pods.+"
              relabelConfigs:
                - action: replace
                  sourceLabels:
                    - __meta_kubernetes_endpoint_node_name
                  targetLabel: instance

```

### Troubleshooting docs

- [x] General - https://docs.victoriametrics.com/troubleshooting/
- [ ] vmagent - https://docs.victoriametrics.com/vmagent/#troubleshooting
- [ ] vmalert - https://docs.victoriametrics.com/vmalert/#troubleshooting

**Comment by tiny-pangolin** [comment]
The k8s stack uses the promethues helm chart as a sub chart so you can add [values from that chart](https://github.com/prometheus-community/helm-charts/blob/main/charts/prometheus-node-exporter/values.yaml) under `prometheus-node-exporter.service`

**Comment by patsevanton** [comment]
Don`t work
```
helm get values -n victoria-metrics victoria-metrics-k8s-stack | grep "quay.io/prometheus/node-exporter" -B 5
prometheus-node-exporter:
  enabled: true
  service:
    image:
      registry: harbor.mos.corp
      repository: quay.io/prometheus/node-exporter
```
and
```
helm get values -n victoria-metrics victoria-metrics-k8s-stack |  grep "quay.io/prometheus/node-exporter"
      repository: quay.io/prometheus/node-exporter
```

**Comment by AndrewChubatiuk** [comment]
you need to set 'prometheus-node-exporter.image.registry' to override default registry

**Comment by patsevanton** [comment]
helm get values -n victoria-metrics victoria-metrics-k8s-stack | grep "prometheus-node-exporter:" -A 5
```
prometheus-node-exporter:
  enabled: true
  service:
    image:
      registry: harbor.corp
  vmScrape:
```

k get ds -n victoria-metrics victoria-metrics-k8s-stack-prometheus-node-exporter -o yaml | grep image
```
        image: quay.io/prometheus/node-exporter:v1.8.2
        imagePullPolicy: IfNotPresent
```

i have old version
```
      chart: victoria-metrics-k8s-stack
      version: 0.30.3
```
May be update?

**Comment by tiny-pangolin** [comment]
you can try I mispoke in my first comment and it should be directly under prometheus-node-exporter and not under prometheus-node-exporter.service

```yaml
prometheus-node-exporter:
  enabled: true
  image:
    registry: harbor.corp
```

**Comment by patsevanton** [comment]
work config:
```
    prometheus-node-exporter:
      enabled: true
      image:
        registry: harbor.corp/quay.io
```
