### ISSUE TITLE
streamaggr rate_sum panic

### ISSUE THREAD

**Issue by artemSpb96** [VictoriaMetrics/VictoriaMetrics#8634]
### Describe the bug

After enabling windows for one of our aggregators we got a panic.

### To Reproduce

Aggr config (`container_network_*` are metrics from [cadvisor](https://github.com/google/cadvisor)):
```
- name: container_network
  match: '{__name__=~"container_network_.+_total"}'
  interval: 15s
  enable_windows: true
  ignore_old_samples: true
  without: [ interface ]
  outputs: [ rate_sum ]
  output_relabel_configs:
    - target_label: __name__
      source_labels: [__name__]
      regex: '(.+)_total:.+'
      replacement: '${1}_rate_15s'
```

vmagent streamaggr config has `keepInput` option enabled.

The problem in https://github.com/VictoriaMetrics/VictoriaMetrics/blob/master/lib/streamaggr/rate.go#L139 is that sv.blue is nil. Replacing it by `state = sv.getState(av.isGreen)` solved the problem.

### Version

We have a fork of victoriametrics, which was updated to the latest streamaggr version a couple of weeks ago.

### Logs

```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x8 pc=0x1448955]

goroutine 55 [running]:
github.com/VictoriaMetrics/VictoriaMetrics/lib/streamaggr.(*rateAggrValue).flush(0xc01286f3d0, {0x69eb60?, 0xc000429840}, 0xc00a63e9a0, {0xc023759010, 0xf}, 0x0)
	o11y/monitoring/victoriametrics/lib/streamaggr/rate.go:139 +0x175
github.com/VictoriaMetrics/VictoriaMetrics/lib/streamaggr.(*aggrOutputs).flushState.func1({0x296560, 0xc01286f400}, {0x26e600?, 0xc008b02580})
	o11y/monitoring/victoriametrics/lib/streamaggr/output.go:115 +0x21a
sync.(*Map).Range(0xc0001fdd60?, 0xc000120d50)
	GOROOT/src/sync/map.go:501 +0x1f8
github.com/VictoriaMetrics/VictoriaMetrics/lib/streamaggr.(*aggrOutputs).flushState(0xc0003350e0?, 0xc0001fdd60?)
	o11y/monitoring/victoriametrics/lib/streamaggr/output.go:94 +0x4e
github.com/VictoriaMetrics/VictoriaMetrics/lib/streamaggr.(*aggregator).flush(0xc0003350e0, 0x5967f0, {0x1877f40?, 0x0?, 0x1877f40?}, 0xc0245d94a0, 0x0)
	o11y/monitoring/victoriametrics/lib/streamaggr/streamaggr.go:932 +0x13a
github.com/VictoriaMetrics/VictoriaMetrics/lib/streamaggr.(*aggregator).runFlusher(0x0?, 0x5967f0, 0x1, 0x1, 0x0)
	o11y/monitoring/victoriametrics/lib/streamaggr/streamaggr.go:852 +0x587
github.com/VictoriaMetrics/VictoriaMetrics/lib/streamaggr.newAggregator.func3()
	o11y/monitoring/victoriametrics/lib/streamaggr/streamaggr.go:712 +0x2c
created by github.com/VictoriaMetrics/VictoriaMetrics/lib/streamaggr.newAggregator in goroutine 1
	o11y/monitoring/victoriametrics/lib/streamaggr/streamaggr.go:711 +0x26c5
```
