### ISSUE TITLE
What should `_msg` be for wide event use cases?

### ISSUE THREAD

**Issue by thoughtpolice** [VictoriaMetrics/VictoriaMetrics#8640]
### Is your question request related to a specific component?

Victorialogs, specifically for wide event use cases and not just e.g. log parsing

### Describe the question in detail

The VictoriaLogs documentation makes several notes about how important the [`_msg` field is](https://docs.victoriametrics.com/victorialogs/faq/#i-want-to-ingest-logs-without-message-field-is-that-possible) to an incoming ingested log event; quoting

> Please note that the _msg field is **crucial** for VictoriaLogs, so it is highly recommended to fill it with meaningful content.

However, I don't want to really ingest logs, or it's at least a secondary concern. I want to ingest pure [wide events, AKA "structured logs"](https://jeremymorrell.dev/blog/a-practitioners-guide-to-wide-events/), and that is my primary use case for VictoriaLogs, and so I'm unsure what to do here and wanted some guidance.

I think that in the case of doing normal log processing (e.g. get your k8s logs from a cluster) what should go in this field is typically fairly obvious, because it will actually be already-stringified log messages, because existing applications are structured that way.

But let's say I'm implementing a brand-new system from the ground up and have total control over logging, only using structured logs, or I have an existing app that uses wide events that I want to point at VictoriaLogs. What should the `_msg` field be? Typically I'm writing something like the following (very hand-wavy):

```
@rest.route("/foo")
def handle_foo_request(req, ctx):
    ....
    ctx.add_event_fields(is_authenticated=is_authenticated, username=user, ...)
```

When a request comes in, a wide event is prepared by the middleware `@rest.route` API, and `ctx.add_event_fields` would just add these key/value pairs to the wide event. It would also add fields like `"route": "/foo"` automatically. Then it would get flushed at the end of the request so a single event would cover all the context of the entire request.

So: what should the `_msg` field be in a case like this? My current approach has been to actually put the request ID (a 128-bit random UUID) into this field, but I'm not sure how optimal this is. As a small side note, alternatives (let's say Honeycomb, or a home grown ClickHouse setup) don't require a `_msg` field in any way, so the data is purely unstructured, which makes this question go away.

But that brings me to the next point, I think more importantly, it is unclear what role the `_msg` field actually plays in the underlying query and storage system. In ClickHouse for example it's more explicit: you'd actually have to specify indicies or materialized views to compute things if you didn't want to rely on pure parallel scans over the underlying data (which is really tedious). I think if it was clearer how `_msg` should be interpreted, it would be easier to pick the right field: is `_msg` used to build indicies or filters? Does using a random UUID screw up index locality? If I'm only doing structured events, is it OK to leave it out? What's the cost of not having it? Will it ever be possible for `_msg` to go away or should I plan on it being there forever? Etc.

This would be a big improvement if it could be spelled out in the documentation, since this seems to an increasingly popular use case (and VictoriaLogs seems good at it, LogsQL in particular is great.)

Thanks for the time and attention; VictoriaLogs is pretty great in my experiments (and I might even contribute a patch or two down the line one day.)

### Troubleshooting docs

- [ ] General - https://docs.victoriametrics.com/troubleshooting/
- [ ] vmagent - https://docs.victoriametrics.com/vmagent/#troubleshooting
- [ ] vmalert - https://docs.victoriametrics.com/vmalert/#troubleshooting

**Comment by mtb-xt** [comment]
Similar question - what should _msg be if the logs are coming, for example, from nginx or php-fpm, and got fully parsed?

**Comment by tiny-pangolin** [comment]
Currently the message field is the only field capable of full text search and stream fields and other fields have to be searched directly.   So there are two approaches you can take.

1. send the entire structured message as the msg field and send all parsed fields to other fields. This will be the easiest to use since users can perform full text searches without knowing the fields for adhoc queries, but be able to use other fields and stream fields for dashboards and recording rules
2. pick a field that summarizes the message like a message type or leave the default message which will lead to better query performance and less storage utilization, but users will have to know the field they are trying to search.

There is an open issue to allow searching multiple fields at once #8551 so you will be able to search multiple fields at once, but this will be slower than searching the field directly.

**Comment by thoughtpolice** [comment]
Thank you! That makes a lot of sense. I also agree that for most cases, option 1 sounds good, and more importantly, we can have middleware take care of it, so users don't have to supply `_msg` (e.g. using [Vector](https://vector.dev/) to automatically take every incoming JSON log object and adding it to its own `_msg` field should be really easy.)

I think it would be very useful to have this in the public documentation, FYI.

**Comment by tiny-pangolin** [comment]
I will talk with the team about making this more visible and with more details about the tradeoffs in the meantime here is a sample vector config, and I also covered this in our recent [tech talk](https://youtu.be/KbQcAoSZEi0)

```yaml
sources:
  syslog_server:
    type: syslog
    address: 0.0.0.0:9000
    max_length: 102400
    mode: udp
    permit_origin:
      - 10.0.0.0/8
      - 127.0.0.0/8
      - 192.168.0.0/16
transforms:
  parse_syslog:
    type: remap
    inputs:
      - syslog_server
    drop_on_error: false
    drop_on_abort: false
    source: |-
      .appname = string!(.appname)
      if contains(.appname, "traefik")  {
        .fields = parse_json!(.message)
      }
      if contains(.appname, "pbs") {
        .fields = parse_grok!(.message, "UPID:%{DATA:pbs_host}:%{DATA:task_id_1}:%{DATA:task_id_2}:%{DATA:task_id_3}:%{DATA:task_id_4}:%{DATA:cmd}:%{DATA:task_path}:%{DATA:user}:%{GREEDYDATA:log_message}")
        .fields.owner = "infra"
      }
sinks:
  vlogs:
    inputs:
      - parse_syslog
    type: elasticsearch
    endpoints:
      - http://127.0.0.1:9428/insert/elasticsearch/
    api_version: v8
    compression: gzip
    healthcheck:
      enabled: false
    query:
      _msg_field: message
      _time_field: timestamp
      _stream_fields: host,container_name,appname

```
