### ISSUE TITLE
Advice needed: vmagent as a proxy - split dupe and non-dupe metrics into their respective streams.

### ISSUE THREAD

**Issue by JelleSmet-TomTom** [VictoriaMetrics/VictoriaMetrics#8662]
### Is your question request related to a specific component?

vmagent

### Describe the question in detail

We have a vmagent proxy layer that accepts metrics via remote write from
internal users and forwards them to Grafana Cloud Mimir. This proxy layer
handles a mix of metrics, some of which require deduplication and some that
do not. After tagging these metrics with various metadata for internal
processes, they are submitted to Grafana Cloud Mimir. We are encountering an
issue where metrics fail to deduplicate. The reason for this is documented
[here](https://grafana.com/docs/mimir/latest/configure/configure-high-availability-deduplication/#distributor-high-availability-ha-tracker). When submitting metrics, it is necessary to group together metrics that
require deduplication in one batch and those that do not in a separate
batch.

I had following vmagent config in mind (through Helm):
```
        remoteWrite:
          - url: https://xxxxxxxxxxxxxxx/api/prom/push
            urlRelabelConfig:
              - action: keep
                source_labels:
                  - prometheus_cluster
                  - prometheus_instance
                regex: ".+?;.+"
              - action: replace
                target_label: owner
                replacement: sre@xxxxxxxxxxxxxxxx
          - url: https://xxxxxxxxxxxxxxx/api/prom/push
            urlRelabelConfig:
              - action: drop
                source_labels:
                  - prometheus_cluster
                  - prometheus_instance
                regex: ".+?;.+"
              - action: replace
                target_label: owner
                replacement: sre@xxxxxxxxxxxxxxxx
```

This would essentially force grouping duplicate metrics and individual metrics into their respective batches.

Would the above approach be correct and satisfy the requirements explained [here](https://grafana.com/docs/mimir/latest/configure/configure-high-availability-deduplication/#distributor-high-availability-ha-tracker).?
 

### Troubleshooting docs

- [ ] General - https://docs.victoriametrics.com/troubleshooting/
- [x] vmagent - https://docs.victoriametrics.com/vmagent/#troubleshooting
- [ ] vmalert - https://docs.victoriametrics.com/vmalert/#troubleshooting
