### ISSUE TITLE
VictoriaLogs Cluster:  missing _msg field for any ingest API

### ISSUE THREAD

**Issue by gravese** [VictoriaMetrics/VictoriaMetrics#8707]
### Is your question request related to a specific component?

vector config 
```toml
[sources.kubernetes_logs]

    [transforms.parse_logs]
    type = "remap"
    inputs = ["kubernetes_logs"]
    source = """
    json_parsed, err = parse_json(.message)
    if err == null && json_parsed != null {
      .= merge!(., json_parsed)
    } else {
      nginx_log, err1 = parse_nginx_log(.message, "combined")
      if err1 == null && nginx_log != null {
        .= merge(., nginx_log)
      }
    }

    .app = .kubernetes.pod_labels.app
    .container_name = .kubernetes.container_name
    .pod_name = .kubernetes.pod_name
    .namespace = .kubernetes.pod_namespace

    log_level, err = get(., ["level"])
    if err == null && log_level != null {
      . = set!(., ["level"], log_level)
    } else {
      . = set!(., ["level"], "info")
    }

    del(.kubernetes)
    del(.file)
    del(.cost)
    del(.stream)
    del(.source_type)
    """
    [sinks.vmlog]
    type = "loki"
    inputs = ["parse_logs"]
    endpoint = "http://vlinsert.ops.svc:9481/insert/loki/"
    path = "/api/v1/push?_stream_fields=app,pod_name,container_name,namespace,level&_msg_field=message&_time_field=timestamp&disable_message_parsing=1"
    compression = "none"
    out_of_order_action = "accept"
    remove_label_fields = true
    tenant_id = "1"
    [sinks.vmlog.request]
    concurrency = 10
    rate_limit_num = 500
    retry_attempts = 3
    [sinks.vmlog.healthcheck]
    enabled = false
    [sinks.vmlog.labels]
    "app" = "{{ .app }}"
    "container_name" = "{{ .container_name }}"
    "pod_name" = "{{ .pod_name }}"
    "namespace" = "{{ .namespace }}"
    "level" = "{{ .level }}"
    [sinks.vmlog.encoding]
    codec = "raw_message"
```
vlstorage

![Image](https://github.com/user-attachments/assets/d5a0b654-67e3-43cb-9ba8-101975a260df)
vminsert

![Image](https://github.com/user-attachments/assets/e94340a1-776a-471d-999a-1a3314afb503)

### Describe the question in detail

I migrated from loki to VictoriaLogs, why does it prompt me that I don't have the msg field?

![Image](https://github.com/user-attachments/assets/114cf374-0c49-4de3-ba2b-3e86c4f0eeea)
![Image](https://github.com/user-attachments/assets/a3fd40d2-98f4-45f5-ba3f-8e236d19b5ab)

### Troubleshooting docs

- [x] General - https://docs.victoriametrics.com/troubleshooting/
- [x] vmagent - https://docs.victoriametrics.com/vmagent/#troubleshooting
- [x] vmalert - https://docs.victoriametrics.com/vmalert/#troubleshooting

**Comment by jiekun** [comment]
Hello. Could you try to provide the request data sent to VictoriaLogs? Maybe try [console sink](https://vector.dev/docs/reference/configuration/sinks/console/) so that debugging the issue could be more easier.

**Comment by gravese** [comment]
> Hello. Could you try to provide the request data sent to VictoriaLogs? Maybe try [console sink](https://vector.dev/docs/reference/configuration/sinks/console/) so that debugging the issue could be more easier.

The same configuration works fine in v1.15.0
For example, the log of one of the vector pods can be queried normally in loki, but cannot be queried in the victorialogs cluster.

![Image](https://github.com/user-attachments/assets/422d6287-d177-44d6-b7df-0d3bb0a9dbae)

![Image](https://github.com/user-attachments/assets/ad972f99-b174-4f23-bfa4-9e404402dd03)

[vlvector-29tmt.txt](https://github.com/user-attachments/files/19730364/vlvector-29tmt.txt)

**Comment by jiekun** [comment]
Hi. It's important to know what data was sent to VictoriaLogs and how the request looks like. Could you provide a request example to VictoriaLogs `/insert/loki/api/v1/push` API, or print the data via vector [console sink](https://vector.dev/docs/reference/configuration/sinks/console/)?

**Comment by gravese** [comment]
> Hi. It's important to know what data was sent to VictoriaLogs and how the request looks like. Could you provide a request example to VictoriaLogs `/insert/loki/api/v1/push` API, or print the data via vector [console sink](https://vector.dev/docs/reference/configuration/sinks/console/)?

Hi. Here is some vector console sink data

![Image](https://github.com/user-attachments/assets/2bd77f2a-f355-4a58-bbb3-dc0bdf277541)
[vector_logs.txt](https://github.com/user-attachments/files/19732677/vector_logs.txt)

**Comment by jiekun** [comment]
Thanks! If I'm not mistaken, the following URL
```
/api/v1/push?_stream_fields=app,pod_name,container_name,namespace,level&_msg_field=message&_time_field=timestamp&disable_message_parsing=1
```
expects to see the following fields in your log: `[app,pod_name,container_name,namespace,level, message, timestamp]`. And in the logs you provided, it seems that they don't have these fields. Is there something I'm missing?

**Comment by gravese** [comment]
> Thanks! If I'm not mistaken, the following URL
> 
> ```
> /api/v1/push?_stream_fields=app,pod_name,container_name,namespace,level&_msg_field=message&_time_field=timestamp&disable_message_parsing=1
> ```
> 
> expects to see the following fields in your log: `[app,pod_name,container_name,namespace,level, message, timestamp]`. And in the logs you provided, it seems that they don't have these fields. Is there something I'm missing?

Hi. This is my configuration. I use vector to collect the logs of a service and write them to both v1.15.0 and v1.18.0 clusters. I don't know why the cluster version reports missing the _msg field.
```toml
    [sinks.vmlog]
    type = "loki"
    inputs = ["parse_logs"]
    endpoint = "http://vlinsert.ops.svc:9481/insert/loki/"
    path = "/api/v1/push?_stream_fields=app,pod_name,container_name,namespace,level&_msg_field=message&_time_field=timestamp&disable_message_parsing=1"
    compression = "none"
    out_of_order_action = "accept"
    remove_label_fields = true
    tenant_id = "1"
    [sinks.vmlog.request]
    concurrency = 10
    rate_limit_num = 500
    retry_attempts = 3
    [sinks.vmlog.healthcheck]
    enabled = false
    [sinks.vmlog.labels]
    "app" = "{{ .app }}"
    "container_name" = "{{ .container_name }}"
    "pod_name" = "{{ .pod_name }}"
    "namespace" = "{{ .namespace }}"
    "level" = "{{ .level }}"
    [sinks.vmlog.encoding]
    codec = "raw_message"

    [sinks.vmlogsingle]
    type = "loki"
    inputs = ["parse_logs"]
    endpoint = "http://vmlog.ops.svc:9428/insert/loki/"
    path = "/api/v1/push?_stream_fields=app,pod_name,container_name,namespace,level&_msg_field=message&_time_field=timestamp&disable_message_parsing=1"
    compression = "none"
    out_of_order_action = "accept"
    remove_label_fields = true
    tenant_id = "1"
    [sinks.vmlogsingle.request]
    concurrency = 10
    rate_limit_num = 500
    retry_attempts = 3
    [sinks.vmlogsingle.healthcheck]
    enabled = false
    [sinks.vmlogsingle.labels]
    "app" = "{{ .app }}"
    "container_name" = "{{ .container_name }}"
    "pod_name" = "{{ .pod_name }}"
    "namespace" = "{{ .namespace }}"
    "level" = "{{ .level }}"
    [sinks.vmlogsingle.encoding]
    codec = "raw_message"
```
![Image](https://github.com/user-attachments/assets/2fe54444-2741-4d2f-8c62-b9cb5940e9dd)
![Image](https://github.com/user-attachments/assets/21543eac-0fe3-461b-929e-48db2b06187e)
