### ISSUE TITLE
vmalert introduce joinMetricsQLFilters templating function

### ISSUE THREAD

**Issue by f41gh7** [VictoriaMetrics/VictoriaMetrics#8730]
### Is your feature request related to a problem? Please describe

 Currently, there is no way to include extra_label or extra_filters to the `external.alert.source` template, if it has reference to the grafana Explore or VMUI query page.

### Describe the solution you'd like

 It'd be great to have a template function, that can parse metricsQL expression on join provided filter to it.

As an example `joinMetricsQLFilters` function adds provide filters string to the query expression

```
$expr| joinMetricsQLFilters '{cluster=~"prod|stage"}'
```

 Original query:
```
up == 0
```

should be transformed to:
```
up{cluster=~"prod|stage"} == 0
```

**Comment by Haleygo** [comment]
I don’t like this approach too much because it creates a discrepancy between the expression that vmalert executes and the one exposed in `external.alert.source`. And if we implement this, we might want it for VictoriaLogs as well. The function should be called joinFilters, allowing us to add filters for both MetricsQL and LogsQL.

But since this feature primarily benefits multitenant setups (or other customized label used to differentiate data, like `cluster` here), I propose the following workaround:
Saying there are multiple clusters and several vmalert instances sharing the same rules with different data source URLs containing `extra_label` to filter data:
```
vmalert:
            spec:
              datasource:
                url: {{ .Values.vmReadEndpoint | required "vmReadEndpoint is required" }}?extra_label=cluster={{ .Values.name }}
              remoteRead:
                url: {{ .Values.vmReadEndpoint | required "vmReadEndpoint is required" }}?extra_label=cluster={{ .Values.name }}
```
1. create a separate datasource for each cluster in Grafana, it allows you to specify query parameter in `server URL` or using `Customer query parameters`. For example, you could create a datasource called `cluster-prod` with url `http://victoriametrics:8428?extra_label=cluster=prod`.

<img width="817" alt="Image" src="https://github.com/user-attachments/assets/56bad127-dd40-4340-ace4-82f6c8c6ee13" />

2. in `external.alert.source`, replace the datasource value with the label value in alert using `'explore?orgId=1&left={"datasource":"cluster-{{$$labels.cluster}}","queries":[{"expr":{{$$expr|jsonEscape|queryEscape}},"refId":"A"}],"range":{"from":"now-1h","to":"now"}}' `.
Then, the generatorURL for an alert with the `cluster=prod` label will redirect to the `cluster-prod` datasource and return the correct results.
