### ISSUE TITLE
vmagent: Detect scrape configurations incomaptible with promscrape cluster mode

### ISSUE THREAD

**Issue by makasim** [VictoriaMetrics/VictoriaMetrics#8747]
### Is your feature request related to a problem? Please describe

When using [promscrape cluster mode](https://docs.victoriametrics.com/vmagent/#scraping-big-number-of-targets) in vmagent, it’s critical that all cluster members use **identical** scrape configurations. This is because the sharding key is computed based on the configuration content. Any differences between configs can cause inconsistent target distribution, resulting in some targets not being scraped at all.

These issues are hard to detect and debug in practice. Since we don’t control what users put into their configs, it's not feasible to fix or work around all misconfigurations automatically. Even attempting to do so would lead to partial and unreliable solutions.

The examples below will not behave correctly in cluster mode:

```yaml
# Only one vmanget would scrap itself
- job_name: local-agent
  static_configs:
  - targets: [localhost:8429]
```

```yaml
# Dynamic config using local metadata
serviceScrapeSpec:
  endpoints:
  - port: http
    relabelConfigs:
    - regex: '%{POD_IP}'
      replacement: http
      source_labels:
      - __meta_kubernetes_pod_ip
      target_label: __scheme__
```

### Describe the solution you'd like

Instead of trying to "fix" misconfigurations, we should focus on making them easier to identify. Users should be informed when their setup is incompatible with promscrape cluster mode.

Ideas:
- Log a warning if `localhost` address is detected in the configs, but only when cluster mode is enabled.
- Add a MoM alert that compares the total expected number of targets vs. the sum of targets across all cluster members. These should match.
- Add another MoM alert that counts the number of cluster members per job vs. the number of distinct config hashes across the cluster. Any mismatch indicates config divergence.
- Add a new Troubleshooting section to the docs specifically for diagnosing scraping issues in cluster mode, with actionable tips.

The ideas could be done separately, some may require exposing new metrics. 

### Describe alternatives you've considered

- https://github.com/VictoriaMetrics/VictoriaMetrics/issues/8737
- https://github.com/VictoriaMetrics/VictoriaMetrics/pull/8732
- https://github.com/VictoriaMetrics/VictoriaMetrics/issues/4200

**Comment by f41gh7** [comment]
I think, the proper fix would be to introduce new configuration option, that skips sharding for the particular job. It resolves both issues - localhost scrapping and dynamic env variables at configuration.

 I also like an idea to have alerting rule for this case. It should help to identify the problem.

 Not sure, that warning is good idea. It's better to have error instead, to help users faster identify the problem. But it requires more advanced known-ledge during config validation and it may break backward compatibility.

**Comment by makasim** [comment]
> I think, the proper fix would be to introduce new configuration option, that skips sharding for the particular job. 

For what I've learnt so far, this looks like a workaround, not a proper solution.

**Comment by Haleygo** [comment]
>Instead of trying to "fix" misconfigurations, we should focus on making them easier to identify. Users should be informed when their setup is incompatible with promscrape cluster mode.

I agree with this if we can cover all the user cases in cluster mode, so we can provide a solution for misconfigured users.

However, as I understand, we recently discovered a case that the current configuration options cannot cover:
when a user enables mTLS in Istio to secure traffic between services, vmagent also needs to make HTTPS requests and requires TLS configs to scrape all targets successfully. But the issue is, when a pod makes a request to itself using its IP, this request bypasses the Istio proxy(unless it uses localhost or the service name) and goes directly to the pod.
This leads to a failure when vmagent attempts to scrape itself(which is using pod IP) because the TLS configurations are not configured on vmagent.
That's why we have a trick in vmaget serviceScrapeSpec [here](https://github.com/VictoriaMetrics/operator/blob/master/config/examples/vmagent_istio.yaml), to change the request to HTTP when vmagent scrapes itself:
```
    endpoints:
      - path: /metrics
        port: http
        scheme: https
        # use special workaround for local endpoint scrape
        # rewrite scheme to http, if pod IP is equal to local pod IP
        # it allows to have multiple vmagent replicas with istio
        relabelConfigs:
          - source_labels: [__meta_kubernetes_pod_ip]
            regex: "%{POD_IP}"
            target_label: __scheme__
            replacement: http
```
This workaround works in normal mode, but not in cluster mode, as the target sharding hash is calculated after relabelConfigs. So above config will result in each vmagent instance having different target lists and break sharding.

@f41gh7 please correct me if I'm wrong.

---
There are two options to support this case:
1. Use an external vmagent to scrape the vmagent cluster.
2. Do not sharding `static_configs: targets: [localhost:port]` in cluster mode. This can be implemented as a new feature flag or set as the default behavior, as using `static_configs: targets: [localhost:port]` does not make sense in cluster mode.

>that skips sharding for the particular job. It resolves both issues - localhost scrapping and dynamic env variables at configuration.

I'm not sure about extending the non-sharding feature to all scrape configurations.
