### ISSUE TITLE
special character on stream labels when in "Explore" in victoriametrics-logs-datasource

### ISSUE THREAD

**Issue by enotspe** [VictoriaMetrics/VictoriaMetrics#8763]
### Describe the bug

Not really sure if this is a victoriametrics-logs-datasource or grafana issue.

I am ingesting logs via vector to victoria logs. When I add `panos.threat/content_type` to my stream labels

```
  vlogs_pan:
    inputs:
      - remap_pan
    type: http
    uri: http://localhost:9428/insert/jsonline?_stream_fields=log.syslog.appname,log.syslog.hostname,panos.device_name,panos.virtual_system,panos.type,panos.threat/content_type,network.direction&_msg_field=message&_time_field=timestamp
    compression: gzip
    encoding:
      codec: json
    framing:
      method: newline_delimited
    healthcheck:
      enabled: false
```

Then I fail to explore my logs in grafana. 

![Image](https://github.com/user-attachments/assets/475bc515-3423-4093-a607-d77c9292f862)

Data is being written into victoria logs, vmui shows logs and I can see data in grafana dashboards as well.

![Image](https://github.com/user-attachments/assets/fd47d711-aef2-4302-8434-338b6a3b4a1e)

### To Reproduce

add a label with a special charater on it, like `/` 

### Version

victoria logs 1.18.0

victoriametric-logs-datasource v0.15.0
