### ISSUE TITLE
vmagent - auth config from service discovery labels

### ISSUE THREAD

**Issue by AngleZhou** [VictoriaMetrics/VictoriaMetrics#8789]
### Is your feature request related to a problem? Please describe

I want to use config file like this:
```
global:
  scrape_interval: 1m
  scrape_timeout: 30s

scrape_configs:
- job_name: pub1
  http_sd_configs:
    - url: "http://hostname:port/collector/api/v1/prometheus?checkNodeId=1001"

  relabel_configs:
    - source_labels: [__meta_username]
      target_label: __basic_auth_username__
      action: replace
    - source_labels: [__meta_password]
      target_label: __basic_auth_password__
      action: replace
  
  basic_auth:
    username: "${__basic_auth_username__}"
    password: "${__basic_auth_password__}" 
```

But the target returns 401, which mean auth failed. 
The targets are dynamically changed, so get from http_sd_config url is the best.
But each target need a username & password basic auth, and the username and password are different from targets. So it would be good if can directly use the labels of the targets.

The relabels are successful, and when I change "${__basic_auth_username__}" to real value, the basic_auth is also successful. So the problem is: It doesn't support "${__basic_auth_username__}".

The http_sd_config url has a response like:
```
[
    {
        "targets":
        [
            "http://hostname:port/web_server/actuator/prometheus"
        ],
        "labels":
        {
        	"__meta_username": "admin",
        	"__meta_password": "admin",
            "instance": "10.106.149.79:9001",
            "job": "mqms"
        }
    }
]
```

### Describe the solution you'd like

I want http_sd_config to get dynamic targets. and the targets have labels such as "__meta_username" and "__meta_password", different targets have different username and password, which are used for basic auth. 

### Additional information

The vmagent and victoria-metrics version is: v1.115.0-0
