### ISSUE TITLE
promtail collects nginx logs and writes them, but there are errors in the UI query.

### ISSUE THREAD

**Issue by walingcc** [VictoriaMetrics/VictoriaMetrics#8822]
### Is your question request related to a specific component?

![Image](https://github.com/user-attachments/assets/67c98694-8e39-41b1-b23b-8cdeca2632e4)

### Describe the question in detail

promtail collects nginx logs and writes them, but there are errors in the UI query.

### Troubleshooting docs

- [ ] General - https://docs.victoriametrics.com/troubleshooting/
- [ ] vmagent - https://docs.victoriametrics.com/vmagent/#troubleshooting
- [ ] vmalert - https://docs.victoriametrics.com/vmalert/#troubleshooting

**Comment by vadimalekseev** [comment]
I don't have such problems, I tested with this docker-compose config:
```yaml
services:
  nginx:
    image: nginx
    ports:
      - "8080:80"
    volumes:
      - ./log:/var/log/nginx

  promtail:
    image: grafana/promtail:3.5.0
    container_name: promtail
    user: root
    volumes:
      - ./log:/var/log
      - ./promtail.yaml:/etc/promtail/config.yml

  vlogs:
    image: docker.io/victoriametrics/victoria-logs:v1.21.0-victorialogs
    ports:
      - "9428:9428"
    command:
      - -storageDataPath=/vlogs
```
`promtail.yaml`:
```yaml
server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: /tmp/positions.yaml

clients:
  - url: http://vlogs:9428/insert/loki/api/v1/push

scrape_configs:
  - job_name: nginx
    static_configs:
      - targets:
          - localhost
        labels:
          job: nginx
          __path__: /var/log/*log
```

There are no errors in the UI, all logs are displayed correctly.

Make sure you haven’t changed the nginx logger settings and you are using the latest version of VictoriaLogs.
If the above didn't help, please describe how to reproduce the problem locally, including nginx and promtail config files
