### ISSUE TITLE
Odd math on vmalert-tool execution

### ISSUE THREAD

**Issue by evkuzin** [VictoriaMetrics/VictoriaMetrics#8831]
This alert
```
groups:
- name: test.rules
  rules:
  - alert: TestAlert
    annotations:
      description: 'we got {{ $value | humanizePercentage }} of something'
      summary: very strange alert
    expr: avg_over_time(node_systemd_unit_state{name="dummy.service", state="active"}[5m]) < 0.7
    for: 5m
    labels:
      severity: info
```
with this test
```
rule_files:
- ../rules/test.rules.yml
tests:

- alert_rule_test:
  - alertname: TestAlert
    eval_time: 10m
    exp_alerts:
    - exp_annotations:
        description: 'we got 50% of something'
        summary: very strange alert
      exp_labels:
        instance: dummy
        name: dummy.service
        severity: info
        state: active
  input_series:
  - series: node_systemd_unit_state{instance="dummy", name="dummy.service",
      state="active"}
    values: 0 1 0 1 0 1 0 1 0 0 0 1 0 1 0 1 0 1 0 1
  interval: 1m
```
will produce this output:
```
/usr/bin/vmalert-tool-prod unittest --disableAlertgroupLabel --files tmp_vmalert/tests/test.tests.yml


Unit Testing:  tmp_vmalert/tests/test.tests.yml
evaluation_interval set to 1m by default
FAILED
failed to run unit test for file "tmp_vmalert/tests/test.tests.yml": 
[
    groupname: , alertname: TestAlert, time: 10m0s, 
        exp:[
            0:
              Labels:{alertname="TestAlert", instance="dummy", name="dummy.service", severity="info", state="active"}
              Annotations:{description="we got 50% of something", summary="very strange alert"}
            ], 
        got:[
            0:
              Labels:{alertname="TestAlert", instance="dummy", name="dummy.service", severity="info", state="active"}
              Annotations:{description="we got 20% of something", summary="very strange alert"}
            ] ]2025/04/28 10:30:26 unittest failed
```
Somehow it's 20%, which is, in my opinion, a bit odd. Correct me if I'm wrong, but we evaluating this interval 
0 1 0 1 0 1 0 1 0 0 0 1 0 1 0 1 0 1 0 1

We starting on 10th minute for the last 5 minutes, so this interval:
1 0 1 0 0
And this is 40%, isn't it?

And here is even more strange stuff - if you change the expression from < 0.7 to < 0.5 you are not getting any alert at all. How is this possible if it returned 20% on the previous evaluation?

```
/usr/bin/vmalert-tool-prod unittest --disableAlertgroupLabel --files tmp_vmalert/tests/sched.tests.yml


Unit Testing:  tmp_vmalert/tests/sched.tests.yml
evaluation_interval set to 1m by default
FAILED
failed to run unit test for file "tmp_vmalert/tests/sched.tests.yml": 
[
    groupname: , alertname: TestAlert, time: 10m0s, 
        exp:[
            0:
              Labels:{alertname="TestAlert", instance="dummy", name="dummy.service", severity="info", state="active"}
              Annotations:{description="we got 50% of something", summary="very strange alert"}
            ], 
        got:[] ]2025/04/28 10:36:44 unittest failed
```
