### ISSUE TITLE
Parallel HTTP Service Discovery for vmagent

### ISSUE THREAD

**Issue by hanjintao1996** [VictoriaMetrics/VictoriaMetrics#8838]
### Is your feature request related to a problem? Please describe

When the number of URLs is large (e.g., >1000), and each URL takes about 1 second to respond, the sequential service discovery in vmagent results in a total discovery time of 1000 seconds. This causes a data interruption period of at least 1000 seconds every time vmagent restarts.

Current configuration example:

```
global:
  scrape_interval: 1m
  scrape_timeout: 30s

scrape_configs:
  - job_name: 'my_http_service'
    static_configs:
      - targets:
          - 'http://example.com/endpoint1'
          - 'http://example.com/endpoint2'
          - 'http://example.com/endpoint3'
          - 'http://example.com/endpoint4'
          - 'http://example.com/endpoint5'
          - 'http://example.com/endpoint6'
          - 'http://example.com/endpoint7'
          - 'http://example.com/endpoint8'
          - 'http://example.com/endpoint9'
          - 'http://example.com/endpoint10'
          - '1000+'
```
Additionally, during the initial setup, if any URL fails, the process restarts from the beginning, which can significantly increase the loading time in a production environment.

```
func (cfg *Config) getScrapeWorkGeneric(visitConfigs func(sc *ScrapeConfig, visitor func(sdc targetLabelsGetter)), discoveryType string, prev []*ScrapeWork) []*ScrapeWork {
	swsPrevByJob := getSWSByJob(prev)
	dst := make([]*ScrapeWork, 0, len(prev))
	for _, sc := range cfg.ScrapeConfigs {
		dstLen := len(dst)
		ok := true
		visitConfigs(sc, func(sdc targetLabelsGetter) {
			if !ok {
				return
			}
			targetLabels, err := sdc.GetLabels(cfg.baseDir)
			if err != nil {
				logger.Errorf("skipping %s targets for job_name=%s because of error: %s", discoveryType, sc.swc.jobName, err)
				ok = false
				return
			}
			dst = appendScrapeWorkForTargetLabels(dst, sc.swc, targetLabels, discoveryType)
		})
		if !ok {
			dst = sc.appendPrevTargets(dst[:dstLen], swsPrevByJob, discoveryType)
		}
	}
	return dst
}
```

### Describe the solution you'd like

hope to add the ability to **concurrently** process HTTP SD requests in order to speed up the loading efficiency of this type of configuration.
If there’s consideration to optimize this kind of issue, I am willing to contribute code.

### Describe alternatives you've considered

I tried merging some HTTP requests to reduce the number of URLs, but it’s still too many overall. Additionally, I hope that at least during initialization, it can avoid restarting from scratch upon failure. Allowing partial success is better than a complete failure. :)

**Comment by jiekun** [comment]
This sounds useful, thanks for your interest. 

Would you mind having some extra introduction of the case you have, what service provider you're using, or why there're 1k+ http sd configs, etc...?

**Comment by jiekun** [comment]
Thank you @hanjintao1996 . 

@f41gh7 What do you think of:
1. Making the HTTP service discovery run in parallel?
2. Do you have any context on why vmagent breaks if one of the scrape service discoveries fails, instead of continuing with the rest?

**Comment by NiXuB86** [comment]
+1 on vmagent skipping job when one of urls is unavailable.
When ceph is deployed using cephadm it has service discovery for deployed services which get scraped by prometheus(which by default get deployed inside cluster) using http_sd, but when using external monitoring we can add all nodes manually or use http_sd which is provided by MGR service. At one point in time only one MGR instance is active, so if for example we have 3 nodes in cluster, and 2 mgr is deployed on node01 and node02 and you provide next config for vmagent:
```
- job_name: ceph
  http_sd_configs:
  - follow_redirects: false
    url: http://node01:8765/sd/prometheus/sd-config?service=mgr-prometheus
  - follow_redirects: false
    url: http://node02:8765/sd/prometheus/sd-config?service=mgr-prometheus
```
It will skip entire job:
```
skipping http_sd_config targets for job_name=ceph because of error: cannot read http_sd api response: cannot fetch "http://node01:8765/sd/prometheus/sd-config?service=mgr-prometheus": Get "http://node01:8765/sd/prometheus/sd-config?service=mgr-prometheus": dial tcp 192.168.0.11:8765: connect: connection refused
```

**Comment by makasim** [comment]
@f41gh7 what do you think about this one ?

**Comment by f41gh7** [comment]
> +1 on vmagent skipping job when one of urls is unavailable. When ceph is deployed using cephadm it has service discovery for deployed services which get scraped by prometheus(which by default get deployed inside cluster) using http_sd, but when using external monitoring we can add all nodes manually or use http_sd which is provided by MGR service. At one point in time only one MGR instance is active, so if for example we have 3 nodes in cluster, and 2 mgr is deployed on node01 and node02 and you provide next config for vmagent:
> 
> ```
> - job_name: ceph
>   http_sd_configs:
>   - follow_redirects: false
>     url: http://node01:8765/sd/prometheus/sd-config?service=mgr-prometheus
>   - follow_redirects: false
>     url: http://node02:8765/sd/prometheus/sd-config?service=mgr-prometheus
> ```
> 
> It will skip entire job:
> 
> ```
> skipping http_sd_config targets for job_name=ceph because of error: cannot read http_sd api response: cannot fetch "http://node01:8765/sd/prometheus/sd-config?service=mgr-prometheus": Get "http://node01:8765/sd/prometheus/sd-config?service=mgr-prometheus": dial tcp 192.168.0.11:8765: connect: connection refused
> ```

 It'd be great to have a different issue for that. This discovery behavior doesnt align with Prometheus. Prometheus performs discovery per each sd_configs entry.

**Comment by f41gh7** [comment]
This feature request looks valid to me. It'd be great to add concurrency option into `getScrapeWorkGeneric`. @jiekun  could you please take a look?

**Comment by NiXuB86** [comment]
@f41gh7 Created [new issue](https://github.com/VictoriaMetrics/VictoriaMetrics/issues/9375). Thanks for response

**Comment by jiekun** [comment]
It's delayed due to lack of time to review. So we'd like to bring it back to active. And we'll start chceking the pull request for this feature. Thank you!

In the mean time, the bug described [here](https://github.com/VictoriaMetrics/VictoriaMetrics/issues/8838#issuecomment-3004286951) must be fixed. Please track it with https://github.com/VictoriaMetrics/VictoriaMetrics/issues/9375

**Comment by f41gh7** [comment]
Current lib/promscrape implementation was not designed to use concurrency for scrape configuration updates.

 There are multiple possible options to optimize it:
1) always start a background polling goroutine per service discovery provider entry ( like Kubernetes and consul providers implemented).
2) use per `scrape_configs` entry concurrency - proposed at linked pull request.
3) use per `scrapeConfig` sub entries concurrency - `http_sd_configs` from issue example.

Options 2 and 3 requires changes into lib/promscrape architecture. While option 1 adds changes into each discovery provider and could cause a delay during vmagent start-up.

 It seems, that the easiest and most straightforward way is option 2, but it will require to rewrite config from:

```yaml

scrape_configs:
  - job_name: 'my_http_service'
    http_sd_configs:
      - url: 'http://example.com/sd-endpoint1'
      - url: 'http://example.com/sd-endpoint2'
      - url: 'http://example.com/sd-endpoint3'
      - url: 'http://example.com/sd-endpoint4'
      - url: 'http://example.com/sd-endpoint5'
      - url: 'http://example.com/sd-endpoint6'
      - url: 'http://example.com/sd-endpoint7'
      - url: 'http://example.com/sd-endpoint8'
      - url: 'http://example.com/sd-endpoint9'
      - url: 'http://example.com/sd-endpoint10'
      - xxxx more than 1000
 ```

```yaml

scrape_configs:
  - job_name: 'my_http_service0'
    http_sd_configs:
      - url: 'http://example.com/sd-endpoint1'
  - job_name: 'my_http_service-1'
    http_sd_configs:
      - url: 'http://example.com/sd-endpoint2'
  - job_name: 'my_http_service-2'
     http_sd_configs:
      - url: 'http://example.com/sd-endpoint3'
      - xxxx more than 1000
  ```
