### ISSUE TITLE
Incorrect handling of nested otel fields in VictoriaLogs (still!)

### ISSUE THREAD

**Issue by KJTsanaktsidis** [VictoriaMetrics/VictoriaMetrics#8862]
### Describe the bug

This is sort of a continuation of https://github.com/VictoriaMetrics/VictoriaMetrics/issues/8384. With the fix from https://github.com/VictoriaMetrics/VictoriaMetrics/pull/8387 applied, the situation is improved, but the ingestion of otel logs with nested attributes is still not what I would have expected.

<img width="812" alt="Image" src="https://github.com/user-attachments/assets/a6bd0fca-c710-4029-9a88-eb025961acd5" />

In the screenshot above, given the log `{"foo": "barz5", "fields2": { "what": "is this3"}}` received from OTLP, it no longer puts the OpenTelemetry proto `BoolValue: null, StringValue: null` etc fields in the ingested message. However, instead of having a field `fields2.what: "is this3"`, there is a field `fields2: { "what": "is this3"}`.

### To Reproduce

As per https://github.com/VictoriaMetrics/VictoriaMetrics/issues/8384

- Start VictoriaLogs: `./victoria-logs-prod`
- Spin up an OpenTelemetry collector with the following config file:

```
# otel-config.yml
receivers:
  filelog:
    include: [ /home/kjtsanaktsidis/logz/logfile.log ]
    operators:
    - type: json_parser
exporters:
  otlphttp/logs:
    endpoint: http://localhost:9428/insert/opentelemetry/
service:
  pipelines:
    logs:
      receivers: [filelog]
      processors: []
      exporters: [otlphttp/logs]
```
-  `./otelcol-contrib --config file:otel-config.yml`
- Write a JSON log entry to that file: `echo '{"foo": "barz4", "fields2": { "what": "is this"}}' >> logfile.log`
- Navigate to the VictoriaLogs Web UI, look at the entry; notice that `fields2` is not unpacked into dotted form.

### Version

```
kjtsanaktsidis@kjtsanaktsidis logz % ./victoria-logs-prod --version
victoria-logs-20250316-001841-tags-v1.17.0-victorialogs-0-g771233ebcd
```
