### ISSUE TITLE
looking for clarity in resource usage of vmselect and vmstorage

### ISSUE THREAD

**Issue by sushovan23** [VictoriaMetrics/VictoriaMetrics#8872]
### Is your question request related to a specific component?

Victoriametrics cluster, vmselect, vmstorage

### Describe the question in detail

We are running a pretty big deployment of victoria metrics cluster in k8s. 
Current version - v1.93.14. (we plan on upgrading to v1.114.0 in couple of weeks)

I have attached the grafana dashboard for providing more details on what we are seeing. 

Here is our deployment -> 
```
vminsert -> 
  extraArgs:
    envflag.enable: "true"
    envflag.prefix: VM_
    loggerFormat: json
    replicationFactor: 2
    maxLabelsPerTimeseries: 50
    maxInsertRequestSize: 335544320
  replicaCount : 50
  requests:
    cpu: 2
    memory: 1G

vmselect ->
  extraArgs:
    envflag.enable: "true"
    envflag.prefix: VM_
    loggerFormat: json
    replicationFactor: 2
    dedup.minScrapeInterval: 60s
    search.maxUniqueTimeseries: "10000000"
    search.maxSamplesPerQuery: "4000000000"
    search.maxConcurrentRequests: 48
    search.maxQueueDuration: 60s
    search.maxQueryDuration: 120s
    search.logSlowQueryDuration: 60s
    search.maxPointsPerTimeseries: 172800
replicaCount: 25
requests:
    cpu: 24
    memory: 78G

vmstorage ->
  extraArgs:
    envflag.enable: "true"
    envflag.prefix: VM_
    loggerFormat: json
    search.maxUniqueTimeseries: "10000000"
    dedup.minScrapeInterval: 60s
  requests:
    cpu: 24
    memory: 200Gi
```

We are running some lots of queries and plan on doing more queries are more alert rules will be configured in grafana. We read the documents on capacity planning that we need more vmselect nodes for doing more number of queries (horizontal queries) and then allocate more cpu/ram on each pod for heavy queries (vertical queries).

We have quite a few heavy queries which are doing 30d time range queries. What we are noticing is that these queries also increase RAM usage in vmstorage pods which I believe is due to cache which storage nodes store for each query which comes in. 

My question are :
1. If we are not planning to adding any more time series but only add more queries (both heavy and light). Do we only scale only vmselect pods? or vmstorage also needs to be scaled? 
2. I have mentioned above all the flags which we enable. Do you have any suggestions on additional flags or changing values for some of the flags which would help in running the select and storage pods in more stable manner?

Anything else do you suggest which would help us in running victoria metrics cluster with resources which we have allocated?

[vmcluster_05042025.pdf](https://github.com/user-attachments/files/20030880/vmcluster_05042025.pdf)

### Troubleshooting docs

- [x] General - https://docs.victoriametrics.com/victoriametrics/troubleshooting/
- [ ] vmagent - https://docs.victoriametrics.com/victoriametrics/vmagent/#troubleshooting
- [ ] vmalert - https://docs.victoriametrics.com/victoriametrics/vmalert/#troubleshooting
