### ISSUE TITLE
victorialogs alert not resolved

### ISSUE THREAD

**Issue by pgassmann** [VictoriaMetrics/VictoriaMetrics#8881]
### Describe the bug

I set up vmalert for vlogs for a test alert if a certain url request is found in the logs. The alert fired, but did not get resolved, even after more than 1h.

`# curl -s 127.0.0.4:8880/vmalert/api/v1/alerts | jq .`
```json
{
  "status": "success",
  "data": {
    "alerts": [
      {
        "state": "firing",
        "name": "TestAlert",
        "value": "0",
        "labels": {
          "alertgroup": "TestAlert",
          "alertname": "TestAlert",
          "alertsource": "victorialogs-test.example.com",
          "alerttype": "vlogs",
          "severity": "warning",
          "stats_result": "requests",
          "team": "ops"
        },
        "annotations": {
          "dashboard": "https://victorialogs-test.example.com/select/vmui/?#/?query=compose_project%253A+%22victorialogs%22+and+compose_service%253A+%22authproxy%22+and+%22GET+%252FTEST-ALERT%22",
          "description": "`TEST-ALERT` triggered",
          "summary": "VictoriaLogs TEST-ALERT"
        },
        "activeAt": "2025-05-06T09:11:00Z",
        "id": "9713962421882443135",
        "rule_id": "11103035684119854670",
        "group_id": "8402240643859316802",
        "expression": "compose_project: \"victorialogs\" and compose_service: \"authproxy\" and \"GET /TEST-ALERT\"\n| stats count(*) as requests\n",
        "source": "https://victorialogs-test.example.com/select/vmui/#/?g0.expr=compose_project%3A+%22victorialogs%22+and+compose_service%3A+%22authproxy%22+and+%22GET+%2FTEST-ALERT%22%0A%7C+stats+count%28%2A%29+as+requests%0A",
        "restored": false,
        "stabilizing": false
      }
    ]
  }
}
```

even with added time filter, the alert remains firing.

### To Reproduce

* I create a rule to trigger if /TEST-ALERT is requested on the victorialogs service, which is logged by the authproxy (nginx)
* curl https://victorialogs.example.com/TEST-ALERT
* Alert fires
* Wait. Alert is not resolved.

```yaml
# cat rules/vlog-alert.rules.yml
groups:
- interval: 1m
  name: TestAlert
  rules:
  - alert: TestAlert
    annotations:
      dashboard: https://victorialogs-test.example.com/select/vmui/?#/?query=compose_project%3A+%22victorialogs%22+and+compose_service%3A+%22authproxy%22+and+%22GET+%2FTEST-ALERT%22&g0.relative_time=last_1_hour
      description: '`TEST-ALERT` triggered'
      summary: VictoriaLogs TEST-ALERT
    expr: 'compose_project: "victorialogs" and compose_service: "authproxy" and "GET /TEST-ALERT"

      and _time: 10m

      | stats count(*) as requests

      '
    labels:
      alertsource: victorialogs-test.example.com
      severity: warning
      team: ops
  type: vlogs
```

### Version

```
# docker compose exec vmalert /vmalert-prod -version
vmalert-20250425-131706-tags-v1.116.0-0-g27d3fb2105

# docker compose exec victorialogs /victoria-logs-prod -version
victoria-logs-20250425-174411-tags-v1.21.0-victorialogs-0-g9d82de9385
```

### Logs

```
# docker compose logs vmalert
vmalert-1  | 2025-05-06T09:12:22.431Z	info	VictoriaMetrics/lib/logger/flag.go:12	build version: vmalert-20250425-131706-tags-v1.116.0-0-g27d3fb2105
vmalert-1  | 2025-05-06T09:12:22.431Z	info	VictoriaMetrics/lib/logger/flag.go:13	command-line flags
vmalert-1  | 2025-05-06T09:12:22.431Z	info	VictoriaMetrics/lib/logger/flag.go:20	  -datasource.url="secret"
vmalert-1  | 2025-05-06T09:12:22.431Z	info	VictoriaMetrics/lib/logger/flag.go:20	  -evaluationInterval="1m0s"
vmalert-1  | 2025-05-06T09:12:22.431Z	info	VictoriaMetrics/lib/logger/flag.go:20	  -external.alert.source="select/vmui/#/?g0.expr={{.Expr|queryEscape}}"
vmalert-1  | 2025-05-06T09:12:22.431Z	info	VictoriaMetrics/lib/logger/flag.go:20	  -external.label="alertsource=victorialogs-test.example.com,alerttype=vlogs"
vmalert-1  | 2025-05-06T09:12:22.431Z	info	VictoriaMetrics/lib/logger/flag.go:20	  -external.url="https://victorialogs-test.example.com"
vmalert-1  | 2025-05-06T09:12:22.431Z	info	VictoriaMetrics/lib/logger/flag.go:20	  -http.pathPrefix="/vmalert"
vmalert-1  | 2025-05-06T09:12:22.431Z	info	VictoriaMetrics/lib/logger/flag.go:20	  -notifier.basicAuth.password="secret"
vmalert-1  | 2025-05-06T09:12:22.431Z	info	VictoriaMetrics/lib/logger/flag.go:20	  -notifier.basicAuth.username="victorialogs-alertmanager-test"
vmalert-1  | 2025-05-06T09:12:22.431Z	info	VictoriaMetrics/lib/logger/flag.go:20	  -notifier.url="secret"
vmalert-1  | 2025-05-06T09:12:22.431Z	info	VictoriaMetrics/lib/logger/flag.go:20	  -remoteRead.basicAuth.password="secret"
vmalert-1  | 2025-05-06T09:12:22.431Z	info	VictoriaMetrics/lib/logger/flag.go:20	  -remoteRead.basicAuth.username="victorialogs-vmalert-test"
vmalert-1  | 2025-05-06T09:12:22.431Z	info	VictoriaMetrics/lib/logger/flag.go:20	  -remoteRead.url="secret"
vmalert-1  | 2025-05-06T09:12:22.431Z	info	VictoriaMetrics/lib/logger/flag.go:20	  -remoteWrite.basicAuth.password="secret"
vmalert-1  | 2025-05-06T09:12:22.431Z	info	VictoriaMetrics/lib/logger/flag.go:20	  -remoteWrite.basicAuth.username="victorialogs-vmalert-test"
vmalert-1  | 2025-05-06T09:12:22.431Z	info	VictoriaMetrics/lib/logger/flag.go:20	  -remoteWrite.url="secret"
vmalert-1  | 2025-05-06T09:12:22.431Z	info	VictoriaMetrics/lib/logger/flag.go:20	  -rule="/etc/alerts/*.yml"
vmalert-1  | 2025-05-06T09:12:22.431Z	info	VictoriaMetrics/lib/logger/flag.go:20	  -rule.defaultRuleType="vlogs"
vmalert-1  | 2025-05-06T09:12:22.435Z	info	VictoriaMetrics/app/vmalert/main.go:163	reading rules configuration file from "/etc/alerts/*.yml"
vmalert-1  | 2025-05-06T09:12:22.436Z	info	VictoriaMetrics/app/vmalert/config/log/logger.go:52	found 1 files to read from "Local FS{MatchPattern: \"/etc/alerts/*.yml\"}"
vmalert-1  | 2025-05-06T09:12:22.436Z	info	VictoriaMetrics/app/vmalert/config/log/logger.go:52	finished reading 1 files in 29.536µs from "Local FS{MatchPattern: \"/etc/alerts/*.yml\"}"
vmalert-1  | 2025-05-06T09:12:22.438Z	info	VictoriaMetrics/app/vmalert/rule/group.go:99	label "alertsource"="victorialogs-test.example.com" for rule "TestAlert"."TestAlert" overwritten with external label "alertsource"="victorialogs-test.example.com"
vmalert-1  | 2025-05-06T09:12:22.439Z	info	VictoriaMetrics/app/vmalert/rule/group.go:502	group "TestAlert" will start in 4.890307089s; interval=1m0s; eval_offset=<nil>; concurrency=1
vmalert-1  | 2025-05-06T09:12:22.439Z	info	VictoriaMetrics/lib/httpserver/httpserver.go:170	started server at http://0.0.0.0:8880/
vmalert-1  | 2025-05-06T09:12:22.439Z	info	VictoriaMetrics/lib/httpserver/httpserver.go:172	pprof handlers are exposed at http://0.0.0.0:8880/debug/pprof/
vmalert-1  | 2025-05-06T09:12:24.413Z	info	VictoriaMetrics/lib/memory/memory.go:42	limiting caches to 40392975974 bytes, leaving 26928650650 bytes to the OS according to -memory.allowedPercent=60
vmalert-1  | 2025-05-06T09:12:27.330Z	info	VictoriaMetrics/app/vmalert/rule/group.go:502	group "TestAlert" started; interval=1m0s; eval_offset=<nil>; concurrency=1
vmalert-1  | 2025-05-06T09:26:33.677Z	warn	VictoriaMetrics/lib/httpserver/httpserver.go:370	remoteAddr: "172.23.0.1:47286"; requestURI: /; missing -http.pathPrefix="/vmalert" in the requested path "/"
vmalert-1  | 2025-05-06T10:02:22.017Z	info	VictoriaMetrics/app/vmalert/main.go:353	SIGHUP received. Going to reload rules "[/etc/alerts/*.yml]" ...
vmalert-1  | 2025-05-06T10:02:22.017Z	info	VictoriaMetrics/app/vmalert/config/log/logger.go:52	found 1 files to read from "Local FS{MatchPattern: \"/etc/alerts/*.yml\"}"
vmalert-1  | 2025-05-06T10:02:22.017Z	info	VictoriaMetrics/app/vmalert/config/log/logger.go:52	finished reading 1 files in 32.301µs from "Local FS{MatchPattern: \"/etc/alerts/*.yml\"}"
vmalert-1  | 2025-05-06T10:02:22.018Z	info	VictoriaMetrics/app/vmalert/rule/group.go:99	label "alertsource"="victorialogs-test.example.com" for rule "TestAlert"."TestAlert" overwritten with external label "alertsource"="victorialogs-test.example.com"
vmalert-1  | 2025-05-06T10:02:22.018Z	info	VictoriaMetrics/app/vmalert/main.go:396	Rules reloaded successfully from "[/etc/alerts/*.yml]"
vmalert-1  | 2025-05-06T10:02:22.018Z	info	VictoriaMetrics/app/vmalert/rule/group.go:502	group "TestAlert" re-started; interval=1m0s; eval_offset=<nil>; concurrency=1
```

### Used command-line flags

docker-compose.yml extract

```yaml
services:
  victorialogs:
    image: victoriametrics/victoria-logs:v1.21.0-victorialogs
    ports:
      - 127.0.0.4:9428:9428
    expose:
      - 9428
    volumes:
      - type: bind
        source: '/container/victorialogs/vlogs-storage'
        target: /vlogs-storage
        read_only: false
    command:
      - '-storageDataPath=/vlogs-storage'
      - '-httpListenAddr=:9428'
      - '-retentionPeriod=1y'
      - '-retention.maxDiskSpaceUsageBytes=10TiB'
      # - '-logNewStreams'
      # - '-loggerLevel INFO' # Minimum level of errors to log. Possible values: INFO, WARN, ERROR, FATAL, PANIC (default "INFO")
    healthcheck:
      test: ["CMD", "wget", "-qO/dev/null", "http://127.0.0.1:9428/health"]
      interval: 30s
      timeout: 5s
      retries: 3
    networks:
      - vm_net
      - webproxy
    restart: always
    ulimits:
      nproc: 65535
      nofile:
        soft: 65535
        hard: 65535

  # vmalert for victorialogs: https://docs.victoriametrics.com/victorialogs/vmalert
  vmalert:
    image: victoriametrics/vmalert:v1.116.0
    depends_on:
      - "victorialogs"
      # - "alertmanager"
    expose:
      - 8880
    ports:
      - 127.0.0.4:8880:8880
    volumes:
      - type: bind
        source: ./rules
        target: /etc/alerts
        read_only: true
    command:
      - '-http.pathPrefix=/vmalert'
      - '-datasource.url=http://victorialogs:9428/'

      - '-remoteWrite.url=https://metrics-test.example.com'
      - '-remoteWrite.basicAuth.username=victorialogs'
      - '-remoteWrite.basicAuth.password=asdf'
      - '-remoteRead.url=https://metrics-test.example.com'
      - '-remoteRead.basicAuth.username=victorialogs'
      - '-remoteRead.basicAuth.password=asdf'

      - '-rule.defaultRuleType=vlogs'
      - '-evaluationInterval=1m'

      - '-notifier.url=https://alertmanager-test.example.com'
      - '-notifier.basicAuth.username=victorialogs'
      - '-notifier.basicAuth.password=asdf'

      - '-rule=/etc/alerts/*.yml'
      # display source of alerts in grafana
      - '-external.url=https://victorialogs-test.example.com'
      - '-external.alert.source=select/vmui/#/?g0.expr={{.Expr|queryEscape}}'
      - '-external.label=alertsource=victorialogs-test.example.com'
      - '-external.label=alerttype=vlogs'
    networks:
      - vm_net
    restart: always
    healthcheck:
      test: ["CMD", "wget", "-qO/dev/null", "http://127.0.0.1:8880/vmalert/health"]
      interval: 30s
      timeout: 5s
      retries: 3
```

**Comment by pgassmann** [comment]
I see the mistake. the alert expression had no condition. I wrote the query based on a [Recording Rule Example](https://docs.victoriametrics.com/victorialogs/vmalert/#alerting-rules) by mistake.

I now added  `| filter requests:>0`


```yaml
  - name: TestAlert
    type: vlogs
    interval: 1m
    rules:
      - alert: TestAlert
        # trigger with: curl https://victorialogs_domain/TEST-ALERT
        expr: |
          compose_project: "victorialogs" and compose_service: "authproxy" and "GET /TEST-ALERT"
          and _time: 10m
          | stats count(*) as requests
          | filter requests:>0
        labels:
          team: ops
          severity: warning
          alertsource: '{{ victorialogs_domain }}'
        annotations:
          summary: VictoriaLogs TEST-ALERT
          description: '`TEST-ALERT` triggered'
          dashboard: https://victorialogs-test.example.com/select/vmui/?#/?query=compose_project%3A+%22victorialogs%22+and+compose_service%3A+%22authproxy%22+and+%22GET+%2FTEST-ALERT%22&g0.relative_time=last_1_hour

```
