### ISSUE TITLE
Kubernetes: second storage unit stuck in Unready Status

### ISSUE THREAD

**Issue by Serrvosky** [VictoriaMetrics/VictoriaMetrics#89]
Hello everyone,

First of all, congrats for this amazing project. Until now, it was the most simplest and cheapest implementation that I found to implement and work with HA monitoring. Very well documented as well.

However I'm having a problem spining the second storage instance. I implemented the cluster version of VictoriaMetrics in Kubernetes, with one instance of each segment (storage, insert and select). Now I'm trying to spin up the second instance of storage to check if all works properly, but this second one it's stuck in unready status.

This is my log line from kubectl command:
```
Error from server (BadRequest): container "vitoria-storage" in pod "vitoria-storage-statefulset-1" is waiting to start: ContainerCreating
```

I'm using rancher as well to managing k8's clusters, and there, I can see this error:
`Containers with unready status: [vitoria-storage]`

This is my storage yaml file:
```
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: vitoria-storage-statefulset
  labels:
    app: vitoria-storage
spec:
  replicas: 3
  selector:
    matchLabels:
      app: vitoria-storage
  serviceName: vitoria-storage
  template:
    metadata:
      labels:
        app: vitoria-storage
        name: vitoria-storage
    spec:
      containers:
      - name: vitoria-storage
        image: victoriametrics/vmstorage:latest
        imagePullPolicy: IfNotPresent
        args:
        - -retentionPeriod=1
        - -storageDataPath=/data/metrics
        volumeMounts:
          - name: data
            mountPath: /data/metrics
        ports:
        - name: insert-port
          protocol: TCP
          containerPort: 8400
        - name: select-port
          protocol: TCP
          containerPort: 8401
        - name: http
          protocol: TCP
          containerPort: 8482
        readinessProbe:
          httpGet:
            path: /health
            port: http
          initialDelaySeconds: 5
          periodSeconds: 15
          timeoutSeconds: 5
        livenessProbe:
          tcpSocket:
            port: http
          initialDelaySeconds: 5
          periodSeconds: 15
          timeoutSeconds: 5
  volumeClaimTemplates:
    - metadata:
        name: data
      spec:
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 10Gi
```
Any help with this problem? Thanks
