### ISSUE TITLE
vmauth: cannot load auth config: failed to parse

### ISSUE THREAD

**Issue by lucrus73** [VictoriaMetrics/VictoriaMetrics#8904]
### Is your question request related to a specific component?

vmauth

### Describe the question in detail

I have two Debian GNU/Linux virtual servers (amd64). One is a server where I installed Debian 12 from scratch and then added some packages from Debian Trixie/Sid. The other is a MS Azure virtual server that came with Debian 11 and then I updated to Debian 12 and added same packages of the first one. 

On the first server vmauth works like a charm. On the second one I tried to clone the first one. The second server has the same `vmauth-prod` executable copied over from the first server and the same `vmauth.yaml` file copied over from the first server. However vmauth there complains upon startup with this error:

```
2025-05-08T11:17:14.470Z	info	VictoriaMetrics/lib/logger/flag.go:12	build version: vmauth-20250117-135521-tags-v1.109.1-0-gf73b40619a
2025-05-08T11:17:14.470Z	info	VictoriaMetrics/lib/logger/flag.go:13	command-line flags
2025-05-08T11:17:14.470Z	info	VictoriaMetrics/lib/logger/flag.go:20	  -auth.config="/srv/victoriametrics/vmauth.yaml"
2025-05-08T11:17:14.471Z	info	VictoriaMetrics/app/vmauth/main.go:91	starting vmauth at "[:8427]"...
2025-05-08T11:17:14.471Z	fatal	VictoriaMetrics/app/vmauth/auth_config.go:601	cannot load auth config: failed to pars -auth.config="/srv/victoriametrics/vmauth.yaml": failed to parse auth config: cannot unmarshal AuthConfig data: yaml: line 38: did not find expected '-' indicator
```

The only differences I can think of between the two servers are 

- the kernel version
- the timezone
- the emulated hardware

I know, there *must* be something else different, but I can't spot it. Here is my `vmauth.yaml` file (with changed passwords and tokens), but, since this file works on the first server, I hardly imagine there being a syntax problem in this file on the second server:

```
users:
  - username: "user"
    password: "secret"
    url_map:
      - src_paths:
          - "/vmui.*"
          - "/prometheus.*"
        url_prefix:
          - "http://localhost:8428/"

  - bearer_token: "876543210"
    url_map:
      - src_paths: 
        - "/influx.*"
        - "/api/v1.*"
        url_prefix:
          - "http://localhost:8428/"
  - bearer_token: "s23"
    url_map:
      - src_paths: 
        - "/influx.*"
        - "/api/v1.*"
        url_prefix:
          - "http://localhost:8428/"  
  - bearer_token: "f1424"
    url_map:
      - src_paths: 
        - "/influx.*"
        - "/api/v1.*"
        url_prefix:
          - "http://localhost:8428/"
  - bearer_token: "bec7972169"
    url_map:
      - src_paths: 
        - "/influx.*"
        - "/api/v1.*"
        url_prefix:
          - "http://localhost:8428/"
   - bearer_token: "85424cf2e9b1"
     url_map:
       - src_paths: 
         - "/influx.*"
         - "/api/v1.*"
         url_prefix:
           - "http://localhost:8428/"
   - bearer_token: "932e347be50b"
     url_map:
       - src_paths: 
         - "/influx.*"
         - "/api/v1.*"
         url_prefix:
           - "http://localhost:8428/"
   - bearer_token: "8ba6553d3465"
     url_map:
       - src_paths: 
         - "/influx.*"
         - "/api/v1.*"
         url_prefix:
           - "http://localhost:8428/"
   - bearer_token: "0661e593d64a"
     url_map:
       - src_paths: 
         - "/influx.*"
         - "/api/v1.*"
         url_prefix:
           - "http://localhost:8428/"
   - bearer_token: "bc1632585a"
     url_map:
       - src_paths: 
         - "/influx.*"
         - "/api/v1.*"
         url_prefix:
           - "http://localhost:8428/"
   - bearer_token: "bc-eee5b9791ea1"
     url_map:
       - src_paths: 
         - "/influx.*"
         - "/api/v1.*"
         url_prefix:
           - "http://localhost:8428/"
```

What am I overlooking?
 

### Troubleshooting docs

- [ ] General - https://docs.victoriametrics.com/victoriametrics/troubleshooting/
- [ ] vmagent - https://docs.victoriametrics.com/victoriametrics/vmagent/#troubleshooting
- [ ] vmalert - https://docs.victoriametrics.com/victoriametrics/vmalert/#troubleshooting

**Comment by func25** [comment]
you need to ensure all `bearer_token` entries have the same indentation level

```yaml
users:
  - username: "user"
    password: "secret"
    url_map:
      - src_paths:
          - "/vmui.*"
          - "/prometheus.*"
        url_prefix:
          - "http://localhost:8428/"

  - bearer_token: "876543210"
    url_map:
      - src_paths: 
        - "/influx.*"
        - "/api/v1.*"
        url_prefix:
          - "http://localhost:8428/"
  - bearer_token: "s23"
    url_map:
      - src_paths: 
        - "/influx.*"
        - "/api/v1.*"
        url_prefix:
          - "http://localhost:8428/"  
  - bearer_token: "f1424"
    url_map:
      - src_paths: 
        - "/influx.*"
        - "/api/v1.*"
        url_prefix:
          - "http://localhost:8428/"
  - bearer_token: "bec7972169"
    url_map:
      - src_paths: 
        - "/influx.*"
        - "/api/v1.*"
        url_prefix:
          - "http://localhost:8428/"
  - bearer_token: "85424cf2e9b1"
    url_map:
      - src_paths: 
        - "/influx.*"
        - "/api/v1.*"
        url_prefix:
          - "http://localhost:8428/"
  - bearer_token: "932e347be50b"
    url_map:
      - src_paths: 
        - "/influx.*"
        - "/api/v1.*"
        url_prefix:
          - "http://localhost:8428/"
  - bearer_token: "8ba6553d3465"
    url_map:
      - src_paths: 
        - "/influx.*"
        - "/api/v1.*"
        url_prefix:
          - "http://localhost:8428/"
  - bearer_token: "0661e593d64a"
    url_map:
      - src_paths: 
        - "/influx.*"
        - "/api/v1.*"
        url_prefix:
          - "http://localhost:8428/"
  - bearer_token: "bc1632585a"
    url_map:
      - src_paths: 
        - "/influx.*"
        - "/api/v1.*"
        url_prefix:
          - "http://localhost:8428/"
  - bearer_token: "bc-eee5b9791ea1"
    url_map:
      - src_paths: 
        - "/influx.*"
        - "/api/v1.*"
        url_prefix:
          - "http://localhost:8428/"
```
