### ISSUE TITLE
vmalert does not create exported label name and label value are identical are identical

### ISSUE THREAD

**Issue by tiny-pangolin** [VictoriaMetrics/VictoriaMetrics#8954]
### Describe the bug

If a recording rule adds a label with the same name and same value, it is duplicated instead of generating a second label prepended with exported. If this result is written to Victoriametrics, the write is accepted, and the duplicate copy of the label is removed, but if it is written to mimir then the write be rejected.

### To Reproduce

1. write a metric like `http_response_response_time{service="collide_blackbox"}` to Victoriametrics
2. add a recording rule that adds the same label
```yaml
groups:
  - name: blackbox_latency_1h
    limit: 0
    interval: 1m
    rules:
      - record: "http:response:time:1h"
        expr: 'quantile_over_time(.99,http_response_response_time{}[1h])'
        labels:
          quantile: "p99"
          service: collide_blackbox
```

3. forward the results through vmagent with mimir as a remotewrite target
```yaml
 vmalert:
    restart: unless-stopped
    image: quay.io/victoriametrics/vmalert:v1.117.1-enterprise
    user: "2070:100"
    volumes:
      - type: bind
        source: /opt/shift-mon/vmalert/rules
        target: /rules
      - type: bind
        source: /opt/shift-mon/vmalert/templates
        target: /templates
    command:
      - "-datasource.url=http://vmauth:8427"
      - "-datasource.bearerToken=REDACTED"
      - "-notifier.url=http://alertmanager:9093"
      - "-remoteWrite.url=http://vmagent:8429"
      - "-remoteRead.url=http://victoriametrics:8428"
      - "-httpListenAddr=0.0.0.0:8880"
      - "-rule.templates=/templates/*.tpl"
      - "-rule=/rules/*.yaml"
      - "-rule=/rules/*.yml"
      - "-configCheckInterval=1m"
      -  "-license=REDACTED"
vmagent:
    restart: unless-stopped
    image: quay.io/victoriametrics/vmagent:v1.117.1-enterprise
    user: '2070:100'
    volumes:
      - type: bind
        source: /opt/shift-mon/vmagent
        target: /vmagent
    command:
      - "-remoteWrite.tmpDataPath=/vmagent/tmp"
      - "-remoteWrite.url=http://victoriametrics:8428/api/v1/write"
      - "-remoteWrite.url=https://user:pass@host/api/prom/push"
      - "-license=REDACTED
```
4. get a 400 error from mimir
```
2025-05-16T01:29:34.748Z   error   VictoriaMetrics/app/vmagent/remotewrite/client.go:662   sending a block with size 2834 bytes to "2:secret-url" was rejected (skipping the block): status code 400; response body: received a series with duplicate label name, label: 'service' series: 'http:response:time:1h{check_name="Authentik", check_type="normal", db="linux", host="kenny", method="GET", quantile="p99", server="redacted' (err-mimir-duplicate-label-names)

```

### Version

Victoriametrics Enterprise v1.117.1

### Logs

2025-05-16T01:29:34.748Z   error   VictoriaMetrics/app/vmagent/remotewrite/client.go:662   sending a block with size 2834 bytes to "2:secret-url" was rejected (skipping the block): status code 400; response body: received a series with duplicate label name, label: 'service' series: 'http:response:time:1h{check_name="Authentik", check_type="normal", db="linux", host="kenny", method="GET", quantile="p99", server="redacted' (err-mimir-duplicate-label-names)
