### ISSUE TITLE
Kubernetes Service Discovery role endpointslice doesn't return __meta_kubernetes_endpointslice_endpoint_node_name

### ISSUE THREAD

**Issue by thejuan** [VictoriaMetrics/VictoriaMetrics#8959]
### Describe the bug

Not sure what the VictoriaMetrics goals in regards to Prometheus compatibility are. Thought I would raise it for others who may convert from Prometheus, so its documented.

The Prometheus `endpointslice` role for Kubernetes Service Discovery doesn't return the __meta_kubernetes_endpointslice_endpoint_node_name label on targets [like Prometheus does] ((https://github.com/prometheus/prometheus/blob/2690761582555fe70391b79227d982d608e6a2b3/discovery/kubernetes/endpointslice.go#L334) (if attach_metadata.node set)

### To Reproduce

```
- job_name: k8s-service-endpoints
  kubernetes_sd_configs:
  - role: endpointslice
    attach_metadata:
      node: true
  relabel_configs:
  - source_labels: [__meta_kubernetes_endpointslice_endpoint_node_name]
    regex: '^$'
    action: drop
```

No targets will be found

### Version

v1.116.0
