### ISSUE TITLE
vmagent: Host header not updated when using SRV records in remoteWrite.url

### ISSUE THREAD

**Issue by xruins** [VictoriaMetrics/VictoriaMetrics#8965]
### Is your feature request related to a problem? Please describe

When specifying an SRV record in remoteWrite.url for vmagent (e.g., `"http://srv+_vmtest/api/v1/write"` ), the HTTP request's host header remains set to the SRV record name instead of being updated to the actual target hostname. 

This causes routing or TLS certificate validation issues on the server side because the host header is not properly rewritten to match the resolved destination from the SRV record.

### Describe the solution you'd like

When vmagent resolves an SRV record and connects to the target endpoint, 
it should update the HTTP Host header to match the target hostname obtained from the SRV record resolution.
Particulaly if SRV record for `_vmtest` refers `vmserver`, I wish vmagent to rewrite host header to `vmserver`. 

### Additional information

I created docker-compse configuration to reproduce this problem.
It creates three containers as follows.
1. vmagent
2. caddy, A HTTP server to log requests from vmagent
3. coredns, A DNS server to respond SRV record for vmagent

<details>
<summary>compose.yaml</summary>

``` yaml
services:
  vmagent-exp:
    image: victoriametrics/vmagent:v1.117.1-scratch
    container_name: vmagent-exp
    command:
      - "-remoteWrite.url=http://srv+_vmtest/api/v1/write"
      - "-promscrape.config=/config.yaml"
      - "-remoteWrite.showURL"
    configs:
      - source: vmagent_config
        target: /config.yaml
    dns:
      - 10.1.0.30
    networks:
      app_net:
        ipv4_address: 10.1.0.10

  # A HTTP server to record remoteWrite requests
  caddy:
    image: caddy:2.10.0-alpine
    container_name: caddy
    command: caddy respond --status 200 --listen 0.0.0.0:80 --access-log
    networks:
      app_net:
        ipv4_address: 10.1.0.20
    expose:
      - "80"

  # A DNS server to respond SRV record
  coredns:
    image: coredns/coredns:1.12.1
    container_name: coredns
    hostname: "coredns"
    command: -conf /etc/coredns/Corefile
    configs:
      - source: corefile
        target: /etc/coredns/Corefile
    networks:
      app_net:
        ipv4_address: 10.1.0.30

networks:
  app_net:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 10.1.0.0/16
          ip_range: 10.1.0.0/16

configs:
  corefile:
    content: |
      . {
        log
        errors
        forward . 8.8.8.8 8.8.4.4
        cache 30

        template IN SRV _vmtest {
          answer "{{ .Name }} 60 IN SRV 0 100 80 caddy"
          fallthrough
        }

        hosts {
            10.1.0.20 caddy
            fallthrough
        }
      }
  vmagent_config:
    content: |
      scrape_configs:
        - job_name: 'localhost'
          static_configs:
            - targets: ['localhost:8429']
```

</details>

By executing `docker logs caddy`, we can get the request log from vmagent.

<details>
<summary>Access log of caddy</summary>

``` json
{
   "level":"info",
   "ts":1747430254.246366,
   "logger":"http.log.access",
   "msg":"handled request",
   "request":{
      "remote_ip":"10.1.0.10",
      "remote_port":"51724",
      "client_ip":"10.1.0.10",
      "proto":"HTTP/1.1",
      "method":"POST",
      "host":"srv+_vmtest", # I wish this field to be `caddy`
      "uri":"/api/v1/write",
      "headers":{
         "User-Agent":[
            "vmagent"
         ],
         "Content-Length":[
            "11983"
         ],
         "Content-Encoding":[
            "zstd"
         ],
         "Content-Type":[
            "application/x-protobuf"
         ],
         "X-Victoriametrics-Remote-Write-Version":[
            "1"
         ],
         "Accept-Encoding":[
            "gzip"
         ]
      }
   },
   "bytes_read":0,
   "user_id":"",
   "duration":0.00001618,
   "size":0,
   "status":200,
   "resp_headers":{
      "Server":[
         "Caddy"
      ],
      "Content-Type":[]
   }
}
```
</details>
