### ISSUE TITLE
Kubernetes - Service storage as storageNode argument

### ISSUE THREAD

**Issue by Serrvosky** [VictoriaMetrics/VictoriaMetrics#90]
Hello guys,

Can I use victoria storage service as storageNode arg? 

For example:
```
...
image: victoriametrics/vminsert:latest
        imagePullPolicy: IfNotPresent
        args:
        - -storageNode=vitoria-storage.default.svc.cluster.local:8400
        ports:
        - name: http
...
```

Or do I have to deploy all insert and select pods with :
-storageNode=data-vitoria-storage-statefulset-0.default.svc.cluster.local:8400
-storageNode=data-vitoria-storage-statefulset-1.default.svc.cluster.local:8400
...
-storageNode=data-vitoria-storage-statefulset-X.default.svc.cluster.local:8400
