### ISSUE TITLE
VMagent relabel branched logic

### ISSUE THREAD

**Issue by JelleSmet-TomTom** [VictoriaMetrics/VictoriaMetrics#9054]
### Is your feature request related to a problem? Please describe

When using VMagent as a "metric proxy" to achieve a black/white list functionality on the metrics going through you quickly run into the limitation its not possible to have a negative match logic. 

For example:

```
- action: drop
  if:
  - metric_1
  - metric_2
  - metric_3
  - metric_4{label_1 != "some_value"}
  - metric_5
```

You'd kind of think that this would drop all `metric_4` metrics except the ones from which label_1 does not match `some_value`. In this context that's a very useful thing to have because it prevents the need to define all the "allowed" label values which can become impossible to manage pretty quickly.

The consequence of `metric_4{label_1 != "some_value"}` would be that pretty much all metrics will be dropped passing through.

### Describe the solution you'd like

It would be handy to have a an action such as `drop_unless` or `keep_unless`

```
- action: drop_unless
  if:
   - metric_4
  unless:
   - {label_1 = "some_value"}
```

or even perhaps something like:

```
- action: match
  if:
   - metric_4
  siblings:
    - action: drop
      if:
       - {label_1 != "some_value"}
```

`action: match` would branch off matching metrics and pass through non-matching metrics ...

### Describe alternatives you've considered

I currently resort to organizing my configurations such that I only have positive matches to evaluate. Of course that works but the problem is I have to continuously rebuild my configuration when new values must be dropped.
