### ISSUE TITLE
Victoria Logs (single instance) High Availability with Helm

### ISSUE THREAD

**Issue by YuryHrytsuk** [VictoriaMetrics/VictoriaMetrics#9076]
### Is your question request related to a specific component?

Victoria logs single (instance)

### Describe the question in detail

I am trying to deploy highly available Victoria Logs Single Stack according to https://docs.victoriametrics.com/victorialogs/#high-availability-ha-setup-with-victorialogs-single-node-instances. I deploy Victoria Logs via [Victoria Logs Single Helm Chart](https://github.com/VictoriaMetrics/helm-charts/releases/tag/victoria-logs-single-0.11.2).

![Image](https://github.com/user-attachments/assets/c9fc6638-10ce-4aaf-8bdc-08ed176d61b2)

Which approach is correct for achieving HA (deploying a helm chart):
* deploy a statefulset with 2+ replicas
* deploy helm chart twice (see configuration files in https://github.com/VictoriaMetrics/helm-charts/issues/2214). 
* Are both approaches valid? If so, what are the pros / cons

### Troubleshooting docs

- [x] General - https://docs.victoriametrics.com/victoriametrics/troubleshooting/
- [x] vmagent - https://docs.victoriametrics.com/victoriametrics/vmagent/#troubleshooting
- [x] vmalert - https://docs.victoriametrics.com/victoriametrics/vmalert/#troubleshooting

**Comment by YuryHrytsuk** [comment]
> both approaches are valid, we'll later introduce distributed chart (which will include vmauth and ability to setup either vlcluster or vlsingle) for victorialogs once [vlagent is ready](https://github.com/VictoriaMetrics/VictoriaMetrics/issues/8766)

@AndrewChubatiuk thanks! 

Could you evaluate (confirm) the following statements?

If I deploy one VL-single chart with 2+ replicas,
1) each replica gets a separate PV (i.e. data replication)
1) vector's config will be automatically configured to ship logs to each replicas's PV (via headless service)
1) if one replica is broken, kubernetes will not send traffic to it anymore and will only use healthy replicas instead (similar to vmauth)?
  * here I am referring to using GUI exposed via Ingress 

PS If all above true, then using 2+ replicas for a VL-single chart seems to be a noticeably easier solution since all is done from the box

**Comment by AndrewChubatiuk** [comment]
vl single chart uses a statefulset by default, so each instances has it's own PV, vector sink is created for each statefulset pod individually. regarding the 3rd point it depends on what you're using for ingress

**Comment by YuryHrytsuk** [comment]
> vl single chart uses a statefulset by default, so each instances has it's own PV, vector sink is created for each statefulset pod individually. regarding the 3rd point it depends on what you're using for ingress

I am using https://github.com/traefik/traefik-helm-chart 
 
```yaml
server:
  ingress:
    enabled: true
    annotations:
        namespace: "my-release"
        cert-manager.io/cluster-issuer: "cert-issuer"
        traefik.ingress.kubernetes.io/router.entrypoints: websecure
        traefik.ingress.kubernetes.io/router.middlewares: ...
    tls:
      - hosts:
          - "my-host.com"
        secretName: secret-tls
    hosts:
      - name: "my-host.com"
        path:
          - /logs
        pathType: Prefix
```
