### ISSUE TITLE
VMalert: Need help understanding weird behavior when evaluating vlogs query containing contains_any filter

### ISSUE THREAD

**Issue by P4P3RCL1P** [VictoriaMetrics/VictoriaMetrics#9086]
### Is your question request related to a specific component?

VMalert

### Describe the question in detail

Apologies if this issue should be reformatted as a bug request (I'm fairly new to vlogs so am unsure if the behavior I'm experiencing is truly a bug or can be attributed to simple user error).

Currently I'm building a recording rule using the `contains_any` filter as such:
`_time:1m AND _stream:{data_type="foo"} | contains_any("fatal","Fatal","FATAL","emergency","Emergency","EMERGENCY") | stats by(bar,baz) count()`

When applying this recording rule against a VMalert instance (currently running `v1.115.0`) I'm presented with the following exception:

```
validation failed for VMRule: example-system-vl/victorialogs-recording-rules group: GeneralRecordingRules err: invalid expression for rule  "Example:contains_any:recording:rule": bad LogsQL expr: "_time:1m AND _stream:{data_type=\"foo\"} | contains_any(\"fatal\",\"Fatal\",\"FATAL\",\"emergency\",\"Emergency\",\"EMERGENCY\") | stats by(bar,baz) count()\n", err: unexpected pipe "contains_any"; context: [:{data_type="cray-logs-containers"} | contains_any]
```

I attempted changing the query used by the recording rule to use `contains_any` after the _stream: field as such:

`_time:1m AND _stream:{data_type="foo"} AND contains_any("fatal","Fatal","FATAL","emergency","Emergency","EMERGENCY") | stats by(bar,baz) count()`

However after applying this recording rule I'm presented with a separate exception:

```
validation failed for VMRule:  example-system-vl/victorialogs-recording-rules group: GeneralRecordingRules err: invalid expression for rule  "Example:contains_any:recording:rulet": bad LogsQL expr: "_time:1m AND _stream:{data_type=\"foo\"} AND contains_any(\"Warn\",\"warn\",\"WARN\") | stats by(bar,baz) count()\n", err: missing whitespace after the search word "contains_any"; context: [data_type="foo"} AND contains_any(]
```

In the second exception it seems VMalert interprets `contains_any` as a search term, while the first doesn't seem to interpret `contains_any` as a valid filter.

For context, both these queries work in the victorialogs vmui as well as in Grafana. I have not tried updating to the latest VMalert version yet as I didn't see anything in the release notes which explicitly addresses this behavior. Essentially I'm looking for clarification into this behavior, and perhaps further guidance if this is something that is caused by user error.

Any help is very much appreciated!

### Troubleshooting docs

- [x] General - https://docs.victoriametrics.com/victoriametrics/troubleshooting/
- [x] vmagent - https://docs.victoriametrics.com/victoriametrics/vmagent/#troubleshooting
- [x] vmalert - https://docs.victoriametrics.com/victoriametrics/vmalert/#troubleshooting

**Comment by P4P3RCL1P** [comment]
Thanks for the context on this issue,

>  I couldn't reproduce the error with your expression, could you share the version of vm-operator and the VMRule yaml?

I am currently running app version [v0.45.0](https://github.com/VictoriaMetrics/helm-charts/blob/master/charts/victoria-metrics-operator/CHANGELOG.md#0450) which I suspect to be the culprit here.

For reference, the recording rule definition is as follows:

```
apiVersion: operator.victoriametrics.com/v1beta1
kind: VMRule
metadata:
  name: victorialogs-recording-rules
  namespace: foobarbazbiz
  labels:
    type: victorialogs
spec:
  groups:
  - name: GeneralContainerLogrErrorMonitoring
    type: vlogs
    interval: 1m
    rules:
      - record: LokiContainerLog:Warning:Test
        expr: |
          _time:1m AND _stream:{data_type="foo"} AND contains_any("fatal","Fatal","FATAL","emergency","Emergency","EMERGENCY") | stats by(bar,baz) count()
```
