### ISSUE TITLE
Replacement string support

### ISSUE THREAD

**Issue by seaurching** [VictoriaMetrics/VictoriaMetrics#9094]
### Is your question request related to a specific component?

I want to replace something in replacement, for example this configuration:
```
    - action: replace
      regex: yunikorn_(.*)_queue_app
      replacement: $1
      sourceLabels:
      - __name__
```
The $1 capture groups content is `root.yunikorn.kcde.scheduler`, I hope replace the string `.` to string `-` with regex like bash-shell's schema "${the//./-}".
Can support this?

### Describe the question in detail

I want to replace strings

### Troubleshooting docs

- [ ] General - https://docs.victoriametrics.com/victoriametrics/troubleshooting/
- [ ] vmagent - https://docs.victoriametrics.com/victoriametrics/vmagent/#troubleshooting
- [ ] vmalert - https://docs.victoriametrics.com/victoriametrics/vmalert/#troubleshooting

**Comment by makasim** [comment]
The following configuration should do the job:

```
- action: replace_all
  source_labels: ["__name__"]
  target_label: "__name__"
  regex: "\\."
  replacement: "-"
```

This rule will replace all dots (.) in the __name__ label with dashes (-).

To test and debug relabeling rules interactively, feel free to use the VictoriaMetrics relabeling playground: [https://play.victoriametrics.com](https://play.victoriametrics.com/select/0/prometheus/graph/#/relabeling?config=-+action%3A+replace_all%0A++source_labels%3A+%5B%22__name__%22%5D%0A++target_label%3A+%22__name__%22%0A++regex%3A+%22%5C%5C.%22%0A++replacement%3A+%22-%22&labels=%7B__name__%3D%22yunikorn_root.yunikorn.kcde.scheduler_queue_app%22%2C+instance%3D%22server-1%22%7D)

You can find more details and examples in the VictoriaMetrics [relabeling cookbook](https://docs.victoriametrics.com/victoriametrics/relabeling/).

Let me know if you need help adapting this further.

**Comment by seaurching** [comment]
> The following configuration should do the job:
> 
> ```
> - action: replace_all
>   source_labels: ["__name__"]
>   target_label: "__name__"
>   regex: "\\."
>   replacement: "-"
> ```
> 
> This rule will replace all dots (.) in the **name** label with dashes (-).
> 
> To test and debug relabeling rules interactively, feel free to use the VictoriaMetrics relabeling playground: [https://play.victoriametrics.com](https://play.victoriametrics.com/select/0/prometheus/graph/#/relabeling?config=-+action%3A+replace_all%0A++source_labels%3A+%5B%22__name__%22%5D%0A++target_label%3A+%22__name__%22%0A++regex%3A+%22%5C%5C.%22%0A++replacement%3A+%22-%22&labels=%7B__name__%3D%22yunikorn_root.yunikorn.kcde.scheduler_queue_app%22%2C+instance%3D%22server-1%22%7D)
> 
> You can find more details and examples in the VictoriaMetrics [relabeling cookbook](https://docs.victoriametrics.com/victoriametrics/relabeling/).
> 
> Let me know if you need help adapting this further.

Your replay doesn't solve my issue

**Comment by makasim** [comment]
Can you provide more details than ?

**Comment by f41gh7** [comment]
Relabeling rules support chaining. 

 At first, capture needed regex into temp label:
```
    - action: replace
      regex: yunikorn_(.*)_queue_app
      replacement: $1
      target_label: __my_tmp_var
      sourceLabels:
      - __name__
``` 

With second rule, modify captured value and write it into needed output:
```
    - action: replace_all
      regex: "\\."
      replacement: "-"
      target_label: __name__
      sourceLabels:
      - __my_tmp_var
```

 See the following example https://play.victoriametrics.com/select/0/vmui/?#/relabeling?config=++++-+action%3A+replace%0A++++++regex%3A+root.yunikorn%5C.%28.*%29%5C.scheduler%0A++++++replacement%3A+%241%0A++++++target_label%3A+__my_tmp_var%0A++++++source_labels%3A%0A++++++-+__name__%0A++++-+action%3A+replace_all%0A++++++regex%3A+%22%5C%5C.%22%0A++++++replacement%3A+%22-%22%0A++++++target_label%3A+__name__%0A++++++source_labels%3A%0A++++++-+__my_tmp_var&labels=%7B__name__%3D%22root.yunikorn.kcde.my_app.scheduler%22%7D

Additional documentation:

https://docs.victoriametrics.com/victoriametrics/relabeling/#relabel-debugging
