### ISSUE TITLE
Remove duplicate slashes when concatenating url_prefix and request path in vmauth

### ISSUE THREAD

**Issue by Tira007** [VictoriaMetrics/VictoriaMetrics#9096]
### Describe the bug

Modify vmauth so that when joining a configured url_prefix and an incoming request path, any duplicate slashes at their boundary are collapsed into a single slash (for example, a prefix ending with “/” and a path beginning with “/” should result in exactly one “/”), ensuring no downstream service sees URLs like “//internal/…”.

Log
`remoteAddr: "10.111.9.201:36500, X-Forwarded-For: 159.69.117.162, 10.111.2.107"; requestURI: /select/logsql/query?start=2025-06-04T13%3A42%3A21.267Z&end=2025-06-04T13%3A47%3A21.267Z&query=%2A&limit=50; unexpected status code for the request to "http://vlogs-ha-5y-3.vlogs-ha-5y.svc.hetz-deckhouse-test.local:9428//internal/select/query?disable_compression=false&query=_time%3A%5B2025-06-04T13%3A42%3A21.267Z%2C2025-06-04T13%3A47%3A21.267Z%5D+%7C+limit+100&tenant_ids=%00%00%00%02%00%00%00%00&timestamp=1749044841266999999&version=v1": 400; want 200; response: "remoteAddr: \"10.111.9.197:51036\"; requestURI: //internal/select/query?disable_compression=false&query=_time%3A%5B2025-06-04T13%3A42%3A21.267Z%2C2025-06-04T13%3A47%3A21.267Z%5D+%7C+limit+100&tenant_ids=%00%00%00%02%00%00%00%00&timestamp=1749044841266999999&version=v1; unsupported path requested: \"//internal/select/query\"\n"`

### To Reproduce

Vmauth config 

```yml
users:
##### Dev RO
  - username: "example-dev-ro"
    dump_request_on_errors: true
    password: "example-dev-ro-password"
    url_map:
      - src_paths:
        - "/select/.*"
        - "/health"
        headers:
          - "AccountID: 1"
          - "ProjectID: 0"
        url_prefix:
          - "http://vlselect.vlogs-select-auth.svc.cluster.local:9471/"
```

`vlselect` config:

```yml
vlselect:
  extraArgs:
    envflag.enable: true
    loggerFormat: json
    httpListenAddr: :9471
    storageNode:
     - "vlogs-30d-1-victoria-logs-single-server.vlogs-30d-1:9428/"
```

### Version

app.kubernetes.io/version=v1.22.2-victorialogs
