### ISSUE TITLE
Detecting an offline host (vmagent and vmalert)

### ISSUE THREAD

**Issue by avalls-smd** [VictoriaMetrics/VictoriaMetrics#9105]
### Is your question request related to a specific component?

vmagent, vmalert

### Describe the question in detail

I have about 70~ machines which each run a vmagent that pushes via remote_write to a single-node Victoriametrics. 

What would be the best way to detect if a host hangs up and stops sending metrics? As they are dedicated servers (not VPSes) it can and does happen from time to time.

Currently I use in vmalert a really long rule: `absent(node_time_seconds{host="host1"}) or absent(node_time_seconds{host="host2"}) ...` but I suspect it's not the best way to do it.

Maybe scraping the vmagents for the self metrics and using an up condition could work, but is that ideal taking into account the many machines to scrape??

### Troubleshooting docs

- [x] General - https://docs.victoriametrics.com/victoriametrics/troubleshooting/
- [x] vmagent - https://docs.victoriametrics.com/victoriametrics/vmagent/#troubleshooting
- [x] vmalert - https://docs.victoriametrics.com/victoriametrics/vmalert/#troubleshooting

**Comment by jiekun** [comment]
Hello. 

You can use VictoriaMetrics Single-node (or a extra vmagent, or vmagents themself) to scrape vmagents. You should receive metrics `vmagent_remotewrite_requests_total` and can set the alerting rule with MetricsQL (you may need to change the label filter and threshold accordingly): 
```
sum(rate(vmagent_remotewrite_requests_total{status_code!="2XX"}[$__rate_interval])) by(instance) > 0
```

Also, I recommend to setup the Grafana dashboard for vmagents. It should provide enough information for you to check the status of them. See: https://grafana.com/grafana/dashboards/12683-victoriametrics-vmagent/

**Comment by tiny-pangolin** [comment]
I use the [lag function](https://docs.victoriametrics.com/victoriametrics/metricsql/#lag) with an alert does not automatically resolve to measure when push based metrics are missing using a rule like this 

```
groups:
  - name: DeadMan
    interval: 1m
    type: prometheus
    labels:
      autoresolve: false
    rules:
      - alert: Linux Host Down
        expr: 'lag(cpu_usage_idle[[24h]) > 300'
        annotations:
          summary: '{{ $labels.host }} is not sending metrics'
          description: '{{ $labels.host }} has not sent metrics in {{ $value }} seconds'
          dashboard: 'https://{{ $externalURL }}/d/ldashboarduid'
```
