### ISSUE TITLE
[VictoriaLogs] occurs "missing _msg field" logs and missing logs by vector

### ISSUE THREAD

**Issue by shsjshentao** [VictoriaMetrics/VictoriaMetrics#9123]
### Describe the bug

I use vector to ingest the k8s logs to victorialogs.
I found two problems:
1. logs missing
2. wrong logs: "**missing _msg field; see https://docs.victoriametrics.com/victorialogs/keyconcepts/#message-field**"

It seems that some logs are lost when high volume of logs is produced in a short time span and "missing_msg" showed when the line is empty.

vector config 
```
   api:
      address: 127.0.0.1:8686
      enabled: false
      playground: true
    data_dir: /vector-data-dir
    sinks:
      vlogs:
        api_version: v8
        compression: gzip
        endpoints:
        - http://vlogs-vlog-1:9428/insert/elasticsearch
        healthcheck:
          enabled: false
        inputs:
        - k8s
        mode: bulk
        type: elasticsearch
        request:
          headers:
            VL-Time-Field: timestamp
            VL-Stream-Fields: stream,kubernetes.pod_name,kubernetes.container_name,kubernetes.pod_namespace
            VL-Msg-Field: message,msg,_msg,log.msg,log.message,log
            AccountID: "0"
            ProjectID: "0"
    sources:
      internal_metrics:
        type: internal_metrics
      k8s:
        node_annotation_fields:
          node_labels: ""
        type: kubernetes_logs
        glob_minimum_cooldown_ms: 500
        rotate_wait_secs: 5
        auto_partial_merge: true
        max_read_bytes: 3145728
    transforms:
      parser:
        inputs:
        - k8s
        source: |
          .log = parse_json(.message) ?? .message
          del(.message)
        type: remap
```

### To Reproduce

vector + victorialogs + k8s

### Version

Victorialogs version is v1.23.3-victorialogs
Vector is the lastest version.

### Screenshots

![Image](https://github.com/user-attachments/assets/d34f341d-cb0e-4682-86b6-5bc941558308)

**Comment by func25** [comment]
> It seems that some logs are lost when high volume of logs is produced in a short time span and "missing_msg" showed when the line is empty.

Could you please clarify what is meant by 'when the line is empty'? Also, if VictoriaLogs drops any logs, it should emit a warning log or metric. Could you please verify this as well?

**Comment by func25** [comment]
Thanks for clarifying.

As for the missing log, I find it highly unlikely, and I haven't identified any scenario where it could go unnoticed. They should either be logged or skipped, then we can check the logs or metrics. Also, check your vector state.

> I means the blank line log may cause the "missing _msg" field by vector.

What behavior are you expecting in this case?

**Comment by shsjshentao** [comment]
The expecting behavior is that no "missing _msg" logs output.

**Comment by func25** [comment]
:) Every ingested log entry must contain at least a `_msg` field with the actual log message (see [Key Concepts](https://docs.victoriametrics.com/victorialogs/keyconcepts/)). VictoriaLogs doesn't filter out empty log lines, as that's not how it works. The proper solution is to filter out empty or blank log lines in Vector before sending them to VictoriaLogs.

**Comment by np22-jpg** [comment]
As with what everyone else is saying, the line `.log = parse_json(.message) ?? .message` parses json. If you look at the logs of whatever is spitting out that error, it'll probably be in JSON format instead of something more conventional. You can use a transform in vector to map a field in that JSON to _msg. For example, this is what I have to do for authentik: 
```
transforms:
  parser:
    type: remap
    inputs: [docker]
    source: |
      # If .message is JSON, parse it; otherwise leave it as-is
      .message = parse_json(.message) ?? .message

      # Map authentik's logs
      if exists(.message.event) { ._msg, err = to_string(.message.event) }
```

Not sure if this is completely correct, though. I'm still new to this too.

**Comment by shsjshentao** [comment]
I use the config by this reference 【https://github.com/VictoriaMetrics/helm-charts/blob/fbb49279c65fd8d930eb571afa368e9e468f40d2/charts/victoria-logs-single/values.yaml#L367】
Also tried the official docs 【https://docs.victoriametrics.com/victorialogs/data-ingestion/vector/】

It does not work.

**Comment by func25** [comment]
You could try:

```yaml
transforms:
  drop_empty:
    type: filter
    inputs: [k8s]
    condition: 'exists(.message) && length(strip_whitespace!(string!(.message))) > 0'
  parser:
    type: remap
    inputs: [drop_empty]
    source: |
      .log = parse_json(.message) ?? .message
      del(.message)
```

If you’d rather not add a new component:

```yaml
transforms:
  source: |
    if !(exists(.message) && length(strip_whitespace!(string!(.message))) > 0) {
      abort
    }
    .log = parse_json(.message) ?? .message
    del(.message)
```
