### ISSUE TITLE
Ability to include log message/field from Victorialogs in vmalert

### ISSUE THREAD

**Issue by tk422** [VictoriaMetrics/VictoriaMetrics#9126]
### Is your feature request related to a problem? Please describe

I have read the documentation thoroughly but I dont see any way to include a sample/last log message in the vmalert config.  Maybe I missed it, but this is quite useful for giving some context to what the alert is about (especially when sending on to places like slack etc).

Example from documentation:
```
      - alert: HasErrorLog
        expr: 'env: "prod" AND status:~"error|warn" | stats by (service, kubernetes.pod) count() as errorLog | filter errorLog:>0'
        annotations:
          description: 'Service {{$labels.service}} (pod {{ index $labels "kubernetes.pod" }}) generated {{$labels.errorLog}} error logs in the last 5 minutes'

```

I would expect the ability to use` | fields _msg ` filter to include the _msg as a label that can be added to the alert.

### Describe the solution you'd like

The ability to include a field/_msg in an alert so the alert can include a log message.

### Describe alternatives you've considered

Looked through all the documentation
