### ISSUE TITLE
Datadog serverless extension v81 failed to send logs to VictoriaLogs

### ISSUE THREAD

**Issue by tommy-ng0** [VictoriaMetrics/VictoriaMetrics#9148]
### Describe the bug

Hey guys, after upgrading datadog serverless extension v81, we see the following error inside the lambda:

```
DD_EXTENSION | ERROR | Failed to send logs to datadog after 5 ms and 3 attempts: reqwest::Error { kind: Request, url: "https://victoria-logs:9427/api/v2/logs", source: hyper_util::client::legacy::Error(SendRequest, hyper::Error(Http2, Error { kind: GoAway(b"", FRAME_SIZE_ERROR, Library) })) }
```

Haven't digged into it too much much tho so not sure what the issue is. My vmauth is 

```
- auth_token: "${bearer_token}"
    url_map:
      - src_paths:
          - "/api/v2/logs"
          - "/api/v1/validate"
        url_prefix: "http://localhost:9428/insert/datadog?_stream_fields=functionname,region,account_id"
```

### To Reproduce

Install datadog serverless extension v81 and try to send logs to victoria-logs v1.23.3.

### Version

v1.23.3-victorialogs
