### ISSUE TITLE
Alert state restoration fails when rule labels contain template expressions

### ISSUE THREAD

**Issue by caryjpaepen** [VictoriaMetrics/VictoriaMetrics#9305]
### Describe the bug

When alerting rules use template expressions in their labels (e.g., {{$labels.instance}}), these templated labels are included in the ALERTS_FOR_STATE restoration query during vmalert restart. Since template expressions are not valid label values, this causes the restoration to fail for those alerts.

### To Reproduce

1. Configure the following alerting rules:

```yaml
groups:
  - name: MyTest
    rules:
    - alert: Example
      expr: topk(1, count by (job) (up)) > 0 
      for: 5m
      labels:
        label1: "{{ $labels.job }}"
    - alert: Example2
      expr: topk(1, count by (job) (up)) > 0 
      for: 5m
      labels:
        label1: "something"
```

2. Wait for both alerts to fire and reach the "firing" state
3. Restart vmalert
4. Observe the restoration behavior:
   - ❌ `Example` alert is NOT restored (starts fresh in pending state)
   - ✅ `Example2` alert is properly restored with its previous state
5. Logs show templated variables are used in the restoration query:
{"ts":"2025-06-30T00:31:48.851Z","level":"info","caller":"VictoriaMetrics/app/vmalert/datasource/client.go:254","msg":"DEBUG datasource request: executing POST request with params \"http://<our vmselect url>:8481/select/0/prometheus/api/v1/query?query=default_rollup%28ALERTS_FOR_STATE%7Balertgroup%3D%22MyTest%22%2Calertname%3D%22Example%22%2Clabel1%3D%22%7B%7B+%24labels.job+%7D%7D+%22%7D%5B600s%5D%29&step=300s&time=2025-06-30T00%3A31%3A48Z\""}

## Proposed Solution

When constructing the `ALERTS_FOR_STATE` query for restoration, vmalert should:

1. **Detect and exclude labels containing template expressions** from the query selectors
2. Only use labels with static values in the restoration query

For the failing example above, the restoration query should be:
```
last_over_time(ALERTS_FOR_STATE{alertname="Example"}[600s])
```

Instead of:
```
last_over_time(ALERTS_FOR_STATE{alertname="Example", label1="{{ $labels.job }}"}[600s])
```

### Version

victoriametrics/vmalert:v1.118.0
