### ISSUE TITLE
VMAlert: {{ $labels.instance }} not working 1.50.1

### ISSUE THREAD

**Issue by BenB196** [VictoriaMetrics/VictoriaMetrics#974]
**Describe the bug**
I recently upgraded to 1.50.1 and it appears that {{ $labels.instance }} is no longer being populated from VMAlert.

**To Reproduce**
- Create a rule that references: {{ $labels.instance }}

```
- alert: Router Down
      expr: probe_success{type=~".*router"} == 0
      for: 5m
      labels:
        severity: warning
        instance: '{{ $labels.instance }}'
      annotations:
        value: '{{ $value }}'
        description: "Router: {{ $labels.instance }} has been down for more than 5 minutes."
```

- Load rule with 1.50.1
- Get alert that contains {{$labels.instance}} instead of the instance value

**Expected behavior**
Based off of the Prometheus [docs](https://prometheus.io/docs/prometheus/latest/configuration/template_examples/), I expect {{$labels.instance}} to populate with the instance name.

**Screenshots**
![image](https://user-images.githubusercontent.com/8277432/102560176-99d84f80-409f-11eb-8eab-90daeef9a7ba.png)

**Version**
victoria-metrics: v1.50.1
vmalert: v1.50.1

**Comment by valyala** [comment]
Confirmed the issue and working on a bugfix. Temporary workaround is to downgrade `vmalert` to v1.49.0

**Comment by f41gh7** [comment]
It seems, that all vmalert versions is affected. Problem at re-declaring label `instance`. try to use following rule as workaround:  
```
- alert: Router Down
      expr: probe_success{type=~".*router"} == 0
      for: 5m
      labels:
        severity: warning
      annotations:
        value: '{{ $value }}'
        description: "Router: {{ $labels.instance }} has been down for more than 5 minutes."
```
