### ISSUE TITLE
vmagent fails to find targets for pod ports not listed in the endpoint

### ISSUE THREAD

**Issue by c10l** [VictoriaMetrics/VictoriaMetrics#982]
**Describe the bug**

According to the [`kubernetes_sd_config` documentation for `endpoints` targets](https://prometheus.io/docs/prometheus/latest/configuration/configuration/#endpoints):

> If the endpoint is backed by a pod, all additional container ports of the pod, not bound to an endpoint port, are discovered as targets as well.

According to [`vmagent` documentation](https://victoriametrics.github.io/vmagent.html#how-to-collect-metrics-in-prometheus-format), it should follow the same criteria.

At present, it fails to find container ports that are not explicitly mentioned in, for instance, a `Service`.

**To Reproduce**

- Create a Deployment with a container with 2 ports, one called `http` where it serves the application's customers, and one called `metrics` which exposes Prometheus metrics for that container;
- Create a Service that selects that pod but only lists the `http` port. Since we don't want to load-balance metrics collection, we don't need to expose that port here;
- Create a VMServiceScrape that matches that service but sets `targetPort` to `metrics`.

Those pods are not going to be found as targets.

**Expected behavior**

Pods should be targets on the `metrics` port.

**Version**

```
$ ./vmagent-prod --version
vmagent-20201215-192003-tags-v1.50.1-0-g795e32be4
```

**Used command-line flags**

```
flag{name="csvTrimTimestamp", value="1ms"} 1
flag{name="dryRun", value="false"} 1
flag{name="enableTCP6", value="false"} 1
flag{name="envflag.enable", value="false"} 1
flag{name="envflag.prefix", value=""} 1
flag{name="fs.disableMmap", value="false"} 1
flag{name="graphiteListenAddr", value=""} 1
flag{name="graphiteTrimTimestamp", value="1s"} 1
flag{name="http.connTimeout", value="2m0s"} 1
flag{name="http.disableResponseCompression", value="false"} 1
flag{name="http.idleConnTimeout", value="1m0s"} 1
flag{name="http.maxGracefulShutdownDuration", value="7s"} 1
flag{name="http.pathPrefix", value=""} 1
flag{name="http.shutdownDelay", value="0s"} 1
flag{name="httpAuth.password", value="secret"} 1
flag{name="httpAuth.username", value=""} 1
flag{name="httpListenAddr", value=":8429"} 1
flag{name="import.maxLineLen", value="104857600"} 1
flag{name="influx.maxLineSize", value="262144"} 1
flag{name="influxListenAddr", value=""} 1
flag{name="influxMeasurementFieldSeparator", value="_"} 1
flag{name="influxSkipMeasurement", value="false"} 1
flag{name="influxSkipSingleField", value="false"} 1
flag{name="influxTrimTimestamp", value="1ms"} 1
flag{name="insert.maxQueueDuration", value="1m0s"} 1
flag{name="loggerDisableTimestamps", value="false"} 1
flag{name="loggerErrorsPerSecondLimit", value="0"} 1
flag{name="loggerFormat", value="default"} 1
flag{name="loggerLevel", value="INFO"} 1
flag{name="loggerOutput", value="stderr"} 1
flag{name="loggerWarnsPerSecondLimit", value="0"} 1
flag{name="maxConcurrentInserts", value="4"} 1
flag{name="maxInsertRequestSize", value="33554432"} 1
flag{name="memory.allowedBytes", value="0"} 1
flag{name="memory.allowedPercent", value="60"} 1
flag{name="metricsAuthKey", value="secret"} 1
flag{name="opentsdbHTTPListenAddr", value=""} 1
flag{name="opentsdbListenAddr", value=""} 1
flag{name="opentsdbTrimTimestamp", value="1s"} 1
flag{name="opentsdbhttp.maxInsertRequestSize", value="33554432"} 1
flag{name="opentsdbhttpTrimTimestamp", value="1ms"} 1
flag{name="pprofAuthKey", value="secret"} 1
flag{name="promscrape.config", value="/etc/vmagent/config_out/vmagent.env.yaml"} 1
flag{name="promscrape.config.dryRun", value="false"} 1
flag{name="promscrape.config.strictParse", value="false"} 1
flag{name="promscrape.configCheckInterval", value="0s"} 1
flag{name="promscrape.consulSDCheckInterval", value="30s"} 1
flag{name="promscrape.disableCompression", value="false"} 1
flag{name="promscrape.disableKeepAlive", value="false"} 1
flag{name="promscrape.discovery.concurrency", value="100"} 1
flag{name="promscrape.discovery.concurrentWaitTime", value="1m0s"} 1
flag{name="promscrape.dnsSDCheckInterval", value="30s"} 1
flag{name="promscrape.dockerswarmSDCheckInterval", value="30s"} 1
flag{name="promscrape.dropOriginalLabels", value="false"} 1
flag{name="promscrape.ec2SDCheckInterval", value="1m0s"} 1
flag{name="promscrape.eurekaSDCheckInterval", value="30s"} 1
flag{name="promscrape.fileSDCheckInterval", value="30s"} 1
flag{name="promscrape.gceSDCheckInterval", value="1m0s"} 1
flag{name="promscrape.kubernetesSDCheckInterval", value="30s"} 1
flag{name="promscrape.maxDroppedTargets", value="1000"} 1
flag{name="promscrape.maxScrapeSize", value="16777216"} 1
flag{name="promscrape.openstackSDCheckInterval", value="30s"} 1
flag{name="promscrape.streamParse", value="false"} 1
flag{name="promscrape.suppressDuplicateScrapeTargetErrors", value="false"} 1
flag{name="promscrape.suppressScrapeErrors", value="false"} 1
flag{name="remoteWrite.basicAuth.password", value="secret"} 1
flag{name="remoteWrite.basicAuth.username", value=""} 1
flag{name="remoteWrite.bearerToken", value="secret"} 1
flag{name="remoteWrite.flushInterval", value="1s"} 1
flag{name="remoteWrite.label", value=""} 1
flag{name="remoteWrite.maxBlockSize", value="8388608"} 1
flag{name="remoteWrite.maxDiskUsagePerURL", value="1073741824"} 1
flag{name="remoteWrite.proxyURL", value=""} 1
flag{name="remoteWrite.queues", value="4"} 1
flag{name="remoteWrite.relabelConfig", value=""} 1
flag{name="remoteWrite.sendTimeout", value=""} 1
flag{name="remoteWrite.showURL", value="false"} 1
flag{name="remoteWrite.significantFigures", value="0"} 1
flag{name="remoteWrite.tlsCAFile", value=""} 1
flag{name="remoteWrite.tlsCertFile", value=""} 1
flag{name="remoteWrite.tlsInsecureSkipVerify", value=""} 1
flag{name="remoteWrite.tlsKeyFile", value="secret"} 1
flag{name="remoteWrite.tlsServerName", value=""} 1
flag{name="remoteWrite.tmpDataPath", value="/tmp/vmagent-remotewrite-data"} 1
flag{name="remoteWrite.url", value="secret"} 1
flag{name="remoteWrite.urlRelabelConfig", value=""} 1
flag{name="tls", value="false"} 1
flag{name="tlsCertFile", value=""} 1
flag{name="tlsKeyFile", value="secret"} 1
flag{name="version", value="false"} 1
```

**Additional context**

Relevant lines in Prometheus source code: https://github.com/prometheus/prometheus/blob/029b45aa307af069a62a6673c800c55c00e4ceae/discovery/kubernetes/endpoints.go#L301-L331

**Comment by f41gh7** [comment]
Yes, thats how `VMServiceScrape` works - main target for scraping service endpoints. You can create workaround for this case with empty VMServiceScrape and manual relabeling. But in your case, i suggest you to try `VMPodScrape` - it could fit your case.
```
apiVersion: operator.victoriametrics.com/v1beta1
kind: VMPodScrape
metadata:
  name: example-pod-scrape
spec:
  podMetricsEndpoints:
    - port: metrics
      scheme: http
  selector:
    matchLabels:
      monitored-by: vm-operator
      app.kubernetes.io/name: example-application
```

**Comment by c10l** [comment]
Hi @f41gh7 ! Thanks for getting back to me, and thanks for working on this project. I'm spiking it to potentially solve scalability problems with Prometheus and so far I'm liking it much more than Thanos, which is the other alternative we're trialing.

I understand your suggestion but it won't work for me. One of my clusters has nearly 700 ServiceMonitors and they're owned by dozens of different tenants. I run 2 other clusters similar in size. Getting all of them to migrate cleanly would not be an easy task.

If you're saying that `vmagent` will not support that use case, then I understand. It won't work for me as the converted `VMServiceScrapers` don't work the same as the `ServiceMonitors` that originate them. In this case I'll file a new ticket to fix the documentation, since currently it implies to follow `kubernetes_sd_config` semantics, but that's not quite correct.

On the other hand, if you wish to support full `kubernetes_sd_config` semantics, I have already started working on a fix for this issue but I could use your help. From my tests, the `appendTargetLabels` method in `Endpoints` [already does that](https://github.com/VictoriaMetrics/VictoriaMetrics/blob/master/lib/promscrape/discovery/kubernetes/endpoints.go#L140-L164). I imagine the labels get removed later on in the process but I haven't yet found out where.

**Comment by f41gh7** [comment]
Can you give some example for `ServiceMonitor` and corresponding `VMServiceScrape`, probably there is some issue at config generation? Need to check it.  `vmagent` supports it, but configuration for it is generated by operator.

  promethues operator and victoria-metrics operator use the same code for config generation: https://github.com/prometheus-operator/prometheus-operator/blob/02a5bac9610299372e9f77cbbe0c824ce636795b/pkg/prometheus/promcfg.go#L1002
 and https://github.com/VictoriaMetrics/operator/blob/master/controllers/factory/scrapes_build.go#L341

 I guess, bug happens during CRD object conversion.

**Comment by c10l** [comment]
There is one difference between those code snippets. The label in [prometheus-operator#L1005](https://github.com/prometheus-operator/prometheus-operator/blob/02a5bac9610299372e9f77cbbe0c824ce636795b/pkg/prometheus/promcfg.go#L1005) is `__meta_kubernetes_endpoint_port_name`, vs [vmoperator#L345](https://github.com/VictoriaMetrics/operator/blob/2daec1b92f1e64dae39826bf404ff442c6f7daf8/controllers/factory/scrapes_build.go#L345) which is `__meta_kubernetes_pod_container_port_name`.

I can't tell if that could be responsible for the difference in behaviour.

Below are the configs you requested. With this configuration, the `ServiceMonitor` uses the `metrics` port from the `Pods` as targets, whereas the `VMServiceScrape` doesn't.

`Service`:

```yaml
---
apiVersion: v1
kind: Service
metadata:
  name: ingress-service
  namespace: tenant
  labels:
    k8s-app: ingress-controller
  annotations:
    service.alpha.kubernetes.io/app-protocols: '{"https":"HTTPS"}'
    beta.cloud.google.com/backend-config: '{"default": "ingress-service"}'
spec:
  ports:
  - port: 80
    name: http
    targetPort: http
  - port: 443
    name: https
    targetPort: https
  selector:
    k8s-app: ingress-controller
  type: NodePort
```

`ServiceMonitor`:

```yaml
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  labels:
    k8s-app: ingress-controller
  name: ingress-service-monitor
  namespace: tenant
spec:
  endpoints:
  - interval: 60s
    metricRelabelings:
    - action: drop
      regex: (nginx_ingress_controller_request_size_bucket|nginx_ingress_controller_response_size_bucket|nginx_ingress_controller_response_duration_seconds_bucket|nginx_ingress_controller_bytes_sent_bucket)
      sourceLabels:
      - __name__
    path: /metrics
    targetPort: metrics
  selector:
    matchLabels:
      k8s-app: ingress-controller
```

And the converted `VMServiceScrape`:

```yaml
---
apiVersion: operator.victoriametrics.com/v1beta1
kind: VMServiceScrape
metadata:
  labels:
    k8s-app: ingress-controller
  name: ingress-service-monitor
  namespace: tenant
spec:
  endpoints:
  - bearerTokenSecret:
      key: ""
    interval: 60s
    metricRelabelConfigs:
    - action: drop
      regex: (nginx_ingress_controller_request_size_bucket|nginx_ingress_controller_response_size_bucket|nginx_ingress_controller_response_duration_seconds_bucket|nginx_ingress_controller_bytes_sent_bucket)
      sourceLabels:
      - __name__
    path: /metrics
    targetPort: metrics
  namespaceSelector: {}
  selector:
    matchLabels:
      k8s-app: ingress-controller
```

**Comment by f41gh7** [comment]
it must generate following config, it fetches all endpoints from `namespace = tenant`, that has labels `k8s-app = ingress-controller` and filters by target, with `__meta_kubernetes_pod_container_port_name= metrics`.  At first look it seems to be valid.

 Another option, probably its ignored by operator? ensure that it has correct selectors.

 And  vmagent exports all targets at `localhost/api/v1/targets` - there is dropped targets as well. any suspicious here? 

```yaml
        job_name: tenant/ingress-service-monitor/0
        honor_labels: false
        kubernetes_sd_configs:
        - role: endpoints
          namespaces:
            names:
            - tenant
        scrape_interval: 60s
        metrics_path: /metrics
        relabel_configs:
        - action: keep
          source_labels:
          - __meta_kubernetes_service_label_k8s_app
          regex: ingress-controller
        - action: keep
          source_labels:
          - __meta_kubernetes_pod_container_port_name
          regex: metrics
        - source_labels:
          - __meta_kubernetes_endpoint_address_target_kind
          - __meta_kubernetes_endpoint_address_target_name
          separator: ;
          regex: Node;(.*)
          replacement: ${1}
          target_label: node
        - source_labels:
          - __meta_kubernetes_endpoint_address_target_kind
          - __meta_kubernetes_endpoint_address_target_name
          separator: ;
          regex: Pod;(.*)
          replacement: ${1}
          target_label: pod
        - source_labels:
          - __meta_kubernetes_namespace
          target_label: namespace
        - source_labels:
          - __meta_kubernetes_service_name
          target_label: service
        - source_labels:
          - __meta_kubernetes_pod_name
          target_label: pod
        - source_labels:
          - __meta_kubernetes_service_name
          target_label: job
          replacement: ${1}
        - target_label: endpoint
          replacement: metrics
        metric_relabel_configs:
        - source_labels:
          - __name__
          regex: (nginx_ingress_controller_request_size_bucket|nginx_ingress_controller_response_size_bucket|nginx_ingress_controller_response_duration_seconds_bucket|nginx_ingress_controller_bytes_sent_bucket)
          action: drop
```
