### ISSUE TITLE
Vmagent stop scraping when hundreds of targets dial timeout.

### ISSUE THREAD

**Issue by zhiyin009** [VictoriaMetrics/VictoriaMetrics#987]
**Describe the bug**
Hundreds of unavailable targets run out of `fasthttp.concurrencyCh`.
Its a bug in fasthttp.tryDial https://github.com/valyala/fasthttp/issues/478
Fixed in https://github.com/valyala/fasthttp/issues/879

**To Reproduce**

```yaml
- job_name: 'vmagent'
  ...

- job_name: 'fake-host-1'
  scrape_interval: 5s
  static_configs:
  - 10.1.1.1:10000
  ...
  - 10.1.1.250:10000

- job_name: 'fake-host-2'
  scrape_interval: 5s
  static_configs:
  - 10.1.2.1:10000
  ...
  - 10.1.2.250:10000
```

**Error log**
`dialing to the given TCP address time out`

**Screenshots**
![image](https://user-images.githubusercontent.com/22493118/103367374-decc9f00-4aff-11eb-9adb-523eba5ac189.png)
![image](https://user-images.githubusercontent.com/22493118/103371192-d1b4ad80-4b09-11eb-91a9-55ddec6a8738.png)

**Version**
The line returned when passing `--version` command line flag to binary. For example:
```
$ ./victoria-metrics-prod --version
victoria-20201215-192003-tags-v1.50.1-0-g795e32be4
```

**Fixed in my way**
https://github.com/VictoriaMetrics/VictoriaMetrics/commit/0acaa4a5e96ea20c36445f90ff3fb8e9be0a426d
