### ISSUE TITLE
functions in alerting templates don't work as in Prometheus

### ISSUE THREAD

**Issue by fmbiete** [VictoriaMetrics/VictoriaMetrics#989]
**Describe the bug**
query, first, value functions in alerting templates don't work as they do in Prometheus

**To Reproduce**
Use this rule file
```
groups:
- name: test
  rules:

  - record: test_record
    expr: 1

  - alert: test_alert
    expr: up == 1
    for: 5m
    labels:
      dynamic: '{{ $x := query "test_record" | first | value }}{{ if eq 1.0 $x }}one{{ else }}unknown{{ end }}'
```

Validate the file; it will return an error, but it's valid for Prometheus

```
2021-01-04T13:42:18.257Z	fatal	/home/builder/rpm/BUILD/VictoriaMetrics-pmm-6401-v1.50.2/app/vmalert/main.go:67	errors(1): invalid group "test" in file "/srv/prometheus/rules/example.yml": invalid labels for rule "test"."tes_alert": errors(1): key "dynamic", template "{{ $x := query \"test_record\" | first | value }}{{ if eq 1.0 $x }}one{{ else }}unknown{{ end }}": error evaluating annotation template: template: :1:97: executing "" at <first>: error calling first: first() called on vector with no elements
```

**Expected behavior**
Rules are valid and dryRun should succeed

**Version**
```
$ ./vmalert --version
vmalert-20201224-155400-pmm-6401-v1.50.2
```
